### ISSUE TITLE
No update information after failure

### ISSUE THREAD

**Issue by jinahya** [ScoopInstaller/Scoop#1093]
Apologies if this issue is already covered. I've been curious for this issue for some time.
When an application is failed to be update, Scoop doesn't care about the new version any more.

```
>scoop update
updating scoop...
updating extras bucket...
scoop was updated successfully!

>scoop update * -i
...
updating go (1.7.1 -> 1.7.3)
uninstalling go (1.7.1)
removing ~\AppData\Local\scoop\apps\go\1.7.1\bin from your path
installing go (1.7.3)
downloading https://storage.googleapis.com/golang/go1.7.3.windows-amd64.zip...(84.7 MB) done
checking hash...ok
extracting...done
go was updated from 1.7.1 to 1.7.3
...
updating nodejs (6.7.0 -> 6.8.1)
uninstalling nodejs (6.7.0)
removing ~\AppData\Local\scoop\apps\nodejs\6.7.0\nodejs from your path
installing nodejs (6.8.1)
downloading https://nodejs.org/dist/v6.8.1/node-v6.8.1-x64.msi...(12.2 MB) done
checking hash...ok
extracting...exit code was 1618
failed to extract files from C:\Users\...\AppData\Local\scoop\apps\nodejs\6.8.1\node-v6.8.1-x64.msi.
log file: ~\AppData\Local\scoop\apps\nodejs\6.8.1\msi.log

>scoop update * -i
...
the latest version of nodejs (6.8.1) is already installed.
run 'scoop update' to check for new versions.
...

>where npm
C:\Users\...\AppData\Local\scoop\apps\nodejs\6.7.0\nodejs\npm
C:\Users\...\AppData\Local\scoop\apps\nodejs\6.7.0\nodejs\npm.cmd

>where node
C:\Users\...\AppData\Local\scoop\apps\nodejs\6.7.0\nodejs\node.exe

>node  --version
v6.7.0
```

Is this normal?

**Comment by lukesampson** [comment]
Thanks for reporting this problem. It is the expected behavior, but it could be improved by having `scoop update` either

* check for failed installations and attempting a reinstall in those cases, or 
* by rolling back failed updates (preferable?)

**Comment by jinahya** [comment]
Let me, please, rephrase the situation.

* Scoop, whatever the reason, failed for `updating nodejs (6.7.0 -> 6.8.1)`
* Scoop is showing `the latest version of nodejs (6.8.1) is already installed`.
* But it seems the `nodejs` is still `6.7.0`.
  * C:\Users\...\AppData\Local\scoop\apps\nodejs\6.7.0\nodejs\npm.cmd

Will Scoop ever try for `6.8.1`? Should I do something for this situation?

**Comment by lukesampson** [comment]
You can `rm ~/appdata/local/scoop/apps/nodejs/6.8.1` to remove the failed install, and `scoop reset nodejs` to restore the last version.

**Comment by lukesampson** [comment]
Probably the reason nodejs isn't working is the insanely long paths it creates. See #847 for similar issue problem, and #249 for the workaround.

**Comment by srimajji** [comment]
Instead of the #249 workaround, i installed nvm (node version manager) via scoop instead and installed node that way. seemed to work fine

**Comment by lukesampson** [comment]
Good to know, @srimajji — thanks.

**Comment by jinahya** [comment]
Removing the wrong app and `reset`ting works. For your information, nodejs 7.0.0 has the same problem.
