### ISSUE TITLE
[FR] Allow apps provide multiple dependencies

### ISSUE THREAD

**Issue by rrelmy** [ScoopInstaller/Scoop#1198]
A manifest should be able to define what it provides.

Currently there are following packages `git`, `openssh`, `git-with-openssh`
The `git-lfs` depends on `git`, `git` will be installed even if `git-with-openssh` is already installed.

It would be great if the `git-with-openssh` manifest could define what it contains.
```
    "provides": ["git", "openssh"],
```

_Nice to have, low priority._ ;-)

**Comment by rashil2000** [comment]
#2217
