### ISSUE TITLE
Feature request: "namespacing" shims

### ISSUE THREAD

**Issue by mrkishi** [ScoopInstaller/Scoop#1290]
Hello, again.

I just avoided installing an app through scoop because of the sheer amount of shims it added and a few conflicts it generated. While I could use `scoop reset` to deal with the conflicts, it's cumbersome to do so, especially when it might not help (outside installations).

I suggest we add a new parameter to `scoop install` that would prepend a string to generated shims.

```
> scoop install --prefix app- app
creating shim for bin1 as app-bin1
creating shim for bin2 as app-bin2
...
```
The actual prefix could be saved in `install.json` so uninstalls would still work.

Possible problems:
- Apps that use `env_add_path` would be incompatible
- `post_install` scripts would also be a tricky subject. Perhaps they could use `${variables}` or `$REPLACEMENTS` to refer to shim'ed executables, but I bet there'd still be incompatible manifests left
- Some apps could break when ran with another name?

I'm not that familiar with scoop so I fully expect there to be other problems. The first two problems, however, are identifiable at installation time and could be dealt with with a warning.

Thoughts?

**Comment by lukesampson** [comment]
It does sound like this could open up a can of worms. Along the lines of the third problem you identified, dependencies might be installed but fail to work because they've been installed with a prefix.

It might be a slightly different problem I'm thinking of, but I like using aliases when there is a possible conflict. Like the Python manifest creating a `python` shim but also aliasing it as `python3` so you don't have to keep `scoop reset`ting if you want to use Python 2 and 3.

Out of interest, what was the app that had too many shims?

**Comment by mrkishi** [comment]
In this specific case, I noticed `sysinternals` was available in the `extras` bucket (while searching for `rg`!) and thought I might as well install it via scoop, as I always end up manually downloading them on my machines. I changed my mind once I saw I'd end up with a few conflicts.

I've been bitten by a `busybox`/`coreutils` <> `gow` overwrite in the past, but I guess that's a different scenario involving dependencies. I did come across problems with `imagemagick`'s `convert`, `compare` and `stream` against non-scoop-managed installs, though.

But this would indeed be a very specific feature.

Perhaps we could enhance the install process to confirm if the user would like to overwrite existing shims ("this will overwrite the following shims, are you sure?") and also hint the prefix option, as long as the manifest doesn't mess with the environment or executes install scripts? I'm afraid it'd be too convoluted for little gain.

Or maybe leave it documented but "undiscoverable?" I'd personally use it for `sysinternals` and `imagemagick`, but could envision power-users wanting both `busybox`, `coreutils` and `gow` versions of tools available for environment testing, for instance.

**Comment by lukesampson** [comment]
Thanks for elaborating. Where do the conflicts with `sysinternals` and `imagemagick` come from?

**Comment by mrkishi** [comment]
`sysinternals` conflicts with `du`, `strings` and `whois` (coreutils/busybox/gow).

`imagemagick`'s `convert` clashed with the Windows one, fixed recently with the `imconvert` alias. `compare` and `stream` were from an specific dev environment -- I don't really know what they were for! In any case, I see no reason to give `imagemagick` such high-profile names! 😛

**Comment by lukesampson** [comment]
Haha yeah that's a bit presumptuous of imagemagick to claim those names. Are they not so heavily contested on Linux?

I might have to think about it more. But I think maybe `--shimprefix` would be worth trying (so it's more clear that it will only affect shims).

**Comment by rasa** [comment]
I uploaded a list of 123 shims that conflict to https://gist.github.com/rasa/61a037bd207454bf1233fc85ab12dac7

Additionally, the following shims conflicts with windows applications:
````
date: bucket/coreutils
date: bucket/busybox
echo: bucket/coreutils
echo: bucket/busybox
expand: bucket/gow
expand: bucket/busybox
find: bucket/findutils
find: bucket/busybox
mkdir: bucket/coreutils
mkdir: bucket/gow
mkdir: bucket/busybox
rmdir: bucket/coreutils
rmdir: bucket/gow
rmdir: bucket/busybox
sort: bucket/coreutils
sort: bucket/busybox
whoami: bucket/gow
whoami: bucket/busybox
````

**Comment by lukesampson** [comment]
Thanks @rasa. Do you have any stories about something you tried to do, but conflicting shims caused an unexpected problem?

I'm having trouble seeing why these conflicts are a problem — my intuition remains that if you install `gow` or `busybox` you expect these tools to be present and under the same names they would be on *nix.

**Comment by dg-nvm** [comment]
some people already overcome that by theirselves:
```
λ scoop info gtools
Name: gtools
Description: Gtools include: pserv, dllusage, gkalk, as well as a couple of command-line only tools: regdiff, supershell, ddupe, pathed, touch, which, md5sums.
Version: 4.2
Website: http://p-nand-q.com/download/gtools
License: BSD-3-Clause (https://spdx.org/licenses/BSD-3-Clause.html)
Manifest:
  C:\Users\dawid.goslawski\scoop\buckets\extras\bucket\gtools.json
Installed: No
Binaries:
  ddupe.exe dllusage.exe GKalk.exe md5sums.exe pathed.exe pserv4.exe regdiff.exe remove_admin_shares.exe gtools-su.exe gtools-touch.exe gtools-which.exe
```

**Comment by viceice** [comment]
A more simple solution could be to warn on install / update, when an existing shim will be overwritten by another app.

**Comment by rashil2000** [comment]
Currently a warning is always printed when overwriting
