### ISSUE TITLE
Windows 10 sshd

### ISSUE THREAD

**Issue by ylluminate** [ScoopInstaller/Scoop#1525]
When using Windows 10's sshd (ex: https://ctrl.blog/entry/how-to-win10-ssh-service) the programs installed via `scoop` are not available.  Presumably this is because Windows 10 fires off `cmd` instead of `PowerShell` with ssh logins.

Any idea of how to deal with this properly?  Can we make `cmd` recognize the path(s) of `scoop` installed tools or do we need to make `sshd` use PowerShell instead?

**Comment by lukesampson** [comment]
There should be .cmd shims in ~/scoop/shims, so it should in theory work with either cmd or PowerShell.

Does `~/scoop/shims` get added to your path for remote sshd sessions?

**Comment by ylluminate** [comment]
Hmm, when I ssh into this Windows 10 (1703) box, `scoop` hangs for about 5 seconds and then just simply returns with no output... so I'm assuming not in this situation.

Interestingly I also am hearing that 1703 uses Powershell as the default shell now, but again, I'm clearly just getting `cmd`.

**Comment by lukesampson** [comment]
What do you get if you run `echo %PATH%` after you ssh in?

`scoop.cmd` would be starting PowerShell behind the scenes, so maybe there is a problem with execution policy for remote sessions. Does `powershell get-executionpolicy` shine any light on that?

**Comment by ylluminate** [comment]
FYI, trying to get to the bottom of why I can't set PS to the default sshd shell here:
https://superuser.com/questions/1214140/using-powershell-as-default-interpreter-on-windows-10-sshd

`C:\Users\username>echo %PATH%` yields:

```
C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Users\username\scoop\shims;C:\Users\username\AppData\Local\Microsoft\WindowsApps
```

**Comment by lukesampson** [comment]
Let us know if you find an answer for setting PowerShell as the default for ssh.

How about `powershell get-executionpolicy` when you've ssh'd into a cmd shell? Or just `powershell` and then run some powershell commands? I'm just wondering if the security context changes when you're logged in remotely. Or does the sshd server prevent you from starting another shell from cmd?

**Comment by ylluminate** [comment]
`powershell get-executionpolicy` when logged in via cmd yields nothing. Blank line; no output.  `powershell` likewise; no output:
```
C:\Users\username>powershell get-executionpolicy

C:\Users\username>powershell get-executionpolicy

C:\Users\username>powershell

C:\Users\username>
```

`cmd` yields:
```
C:\Users\username>cmd
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\username>
```

**Comment by lukesampson** [comment]
Seems like there might be some rough edges with sshd. Working out how to get it to use PowerShell by default might be the only way forward for now.

**Comment by ylluminate** [comment]
I think the trick is going to be finding the config file or reg key for Windows' SSHD... I suspect there are some settings there we can tweak to make this function as expected, but where oh where M$ have you stuck this?...

**Comment by tresf** [comment]
Haven't tested this but perhaps a method to detect scoop and remote SSH and if present, switch the shell over on login?

https://github.com/ericblade/ssh-agent-cmd/blob/master/autorun.reg#L3

**Comment by shmerl** [comment]
How do you launch sshd after it's installed with scoop (Windows 10)? I run the installation script which succeeded.

When doing:

```
Start-Service sshd
```

I get an error:

Start-Service : Service 'OpenSSH SSH Server (sshd)' cannot be started due to the following error: Cannot open sshd service on computer '.'.
```

Any idea how to work around that?
