### ISSUE TITLE
Request: Download mirrors

### ISSUE THREAD

**Issue by simonwjackson** [ScoopInstaller/Scoop#1528]
Not crucial, but thought it would be nice to have.

**Comment by NaanProphet** [comment]
Related to previous pull request https://github.com/lukesampson/scoop/pull/1490

**Comment by hhaoao** [comment]
I'm sad that my proxy has problem after scoop is completely paralysed and I desperately need this feature. `Nvm-windows` recently encountered an extremely difficult problem that caused the [npm upgrade to fail](https://github.com/coreybutler/nvm-windows/issues/300) and was intended to replace the "nvm-window" with the "scoop reset" command, but I found that the spoon does not currently support mirror downloads nodejs.

**Comment by rashil2000** [comment]
#4264
