### ISSUE TITLE
php bad env. variables settings

### ISSUE THREAD

**Issue by silverqx** [ScoopInstaller/Scoop#1583]
Hi,

env variables should be set like this:
```
"env_set": {
    "PHPRC": "$dir\\cli",
    "PHP_INI_SCAN_DIR": "$dir\\cli\\conf.d"
},
```

I'm using different config for cli and other for fastcgi server, so my config dir looks like this:
```
-- cli/
    |-- conf.d/
    |    |-- 90-xdebug.ini
    |    `-- 91-my.ini
    |-- php-cli.ini
    `-- php-cgi.ini
```

Described here: http://php.net/manual/en/configuration.file.php

**Comment by szachara** [comment]
I thought that it will not be clear, why is PHPRC env. var is needed ☺️

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
