### ISSUE TITLE
`scoop status` does not show package updates when Scoop is out of date

### ISSUE THREAD

**Issue by TeaDrivenDev** [ScoopInstaller/Scoop#1713]
When there are updates to both Scoop and installed packages, `scoop status` does not show the package updates. `scoop status` has to be called again after running `scoop update` to get information on any potential package updates, and one has to remember to do so in the first place.

This workflow seems unnecessarily involved and error (or rather omission) prone. Why can't `scoop status` show package updates outright? Or `scoop update` mention that there are updates to the packages too?

**Comment by systemexitzero** [comment]
> Why can't `scoop status` show package updates outright?

`scoop status` only checks if there are more commits to the scoop repo; it doesn't know if those commits are updates to `scoop` itself, or updates to the main bucket.
When [core.ps1:app_status()](/lukesampson/scoop/blob/7450813958b6bdd6d71b6510271d7c31d20e67d9/lib/core.ps1#L80) checks for outdated versions, it's comparing the version from the appdir on disk to the version in its manifest on disk. The manifest is fetched during the status check, but won't be merged until scoop is actually updated. So the information is technically there.

Conceivably, one could extend scoop to also check against any newly fetched manifests using `git show origin/master:buckets/<the app>.json`, but there would need to be disambiguation between the latest version of an app available in one's current version of scoop, and the latest version of an app available in the latest version of scoop when providing feedback.

> Or `scoop update` mention that there are updates to the packages too?

That would effectively just be automatically running `scoop status` (or parts of it) whenever `scoop update` successfully updates scoop. Which may or may not be a good default.
