### ISSUE TITLE
reset python is not working when python35 installed

### ISSUE THREAD

**Issue by yigitemres** [ScoopInstaller/Scoop#1716]
hi,
when i install python(3.6) and python35 together, they creating shims as they should. when i use "scoop reset python" command in order to use python(3.6) as default, scoop execute command but system is continue to use python35 as default python except pip itself. when i have installed packages in pip36 (such as sphinx) and system try to execute python command from python35 packages not found (which is normal)

can you fix this issue and can you add feature like `scoop install x --noshim`?

thank you 

```
 ~ $ scoop install python35
Installing 'python35' (3.5.4).
Loading python-3.5.4-amd64.exe from cache
Checking hash of python-3.5.4-amd64.exe... ok.
Running pre-install script...
Running installer... done.
Linking ~\scoop\apps\python35\current => ~\scoop\apps\python35\3.5.4
Creating shim for 'python'.
Creating shim for 'pythonw'.
Creating shim for 'python3'.
Creating shim for 'python35'.
'python35' (3.5.4) was installed successfully!
~ $ scoop reset python
Resetting python (3.6.2).
Linking ~\scoop\apps\python\current => ~\scoop\apps\python\3.6.2
Creating shim for 'python'.
Creating shim for 'pythonw'.
Creating shim for 'python3'.
~ $ which python
C:\Users\yigit\scoop\apps\python35\current/python.exe
~ $ which pythonw
C:\Users\yigit\scoop\apps\python35\current/pythonw.exe
~ $ which python3
C:\Users\yigit\scoop\shims/python3.exe
~ $ which pip
C:\Users\yigit\scoop\apps\python\current\scripts/pip.exe
~ $
```

**Comment by rasa** [comment]
I think this isn't a scoop issue, it's a PATH issue. Each Python installer updates the PATH variable. You might need to tweak your PATH to point to the version of Python you've reset to. That's outside of scoop's scope (for now anyway).

**Comment by yigitemres** [comment]
@rasa firstly, thx for reply and thx for all contributors of this project. it would be path issue, but i can't sure about it (i don't know exactly how reset option works and im lazy to look at it. that's why i post it here. 😄).  for eliminating such failures, can we have option ``scoop install x --no-path`` or change behavior of reset option to changing PATH also in order to QoL change? i know that's extra work but i think that will be a good feature. (if that is the topic of another discussion, than issue can be closed.)
