### ISSUE TITLE
Cannot install `yarn`

### ISSUE THREAD

**Issue by hoest** [ScoopInstaller/Scoop#1724]
I cannot install `yarn` with the `scoop install yarn` command:

![image](https://user-images.githubusercontent.com/606546/30806222-312b0320-a1f5-11e7-86b8-ffacf30f3abc.png)

This is the error:

```
Installing 'yarn' (1.1.0).
yarn-1.1.0.msi (1,2 MB) 
Checking hash of yarn-1.1.0.msi... ok.
Extracting... % : The term 'local:run' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\jelle\scoop\apps\scoop\current\libexec\scoop-install.ps1:107 char:9
+ $apps | % { install_app $_ $architecture $global $suggested $use_cach ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (local:run:String) [ForEach-Object], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.ForEachObjectCommand
```

I'm running Windows 10 with PowerShell version 5.

**Comment by r15ch13** [comment]
Did you set `set-executionpolicy remotesigned -s cu`?
Does it happen after restarting powershell and trying it again? Maybe related to https://github.com/lukesampson/scoop/issues/1721

**Comment by hoest** [comment]
Error changed after the `set-executionpolicy` command:

```
$ scoop install yarn
Installing 'yarn' (1.1.0).
Loading yarn-1.1.0.msi from cache
Checking hash of yarn-1.1.0.msi... ok.
Extracting... run : The term 'local:run' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\jelle\scoop\apps\scoop\current\lib\install.ps1:567 char:11
+     $ok = run 'msiexec' @('/a', "`"$path`"", '/qn', "TARGETDIR=`"$to` ...
+           ~~~
    + CategoryInfo          : ObjectNotFound: (local:run:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Failed to extract files from C:\Users\jelle\scoop\apps\yarn\1.1.0\yarn-1.1.0.msi.
Log file:
  ~\scoop\apps\yarn\1.1.0\msi.log
```

But the `~\scoop\apps\yarn\1.1.0\msi.log` file is not there...

**Comment by r15ch13** [comment]
Hm, I can't figure out why it doesn't know about the run() function which is also located in the install.ps1 (line 476). Realy strange. Did you run `set-executionpolicy` from an elevated powershell and then restarted it?

**Comment by hoest** [comment]
Yes, both. Ran it in a normal PowerShell and also in an elevated PowerShell.

**Comment by r15ch13** [comment]
Can you try running `. C:\Users\jelle\scoop\apps\scoop\current\libexec\scoop-install.ps1` and then `Get-ChildItem function:`? The output should look somewhat like this:

```
...
Function        rm_shim
Function        rm_shims
Function        rm_startmenu_shortcuts
Function        run
Function        run_installer
Function        run_uninstaller
Function        runtime_deps
...
```
Does it install now?

**Comment by hoest** [comment]
Thanks for the responses b.t.w. ...

**Comment by r15ch13** [comment]
Cool, I would never have guessed it was a problem with a local alias 😁

**Comment by r15ch13** [comment]
I could reproduce it. It seems to be a problem with [reset_alias()](https://github.com/lukesampson/scoop/blob/master/lib/core.ps1#L362).
