### ISSUE TITLE
scoop update - fails

### ISSUE THREAD

**Issue by gigaimage** [ScoopInstaller/Scoop#1733]
![capture](https://user-images.githubusercontent.com/1184087/30902605-a74dd984-a320-11e7-94ba-0b9beeddcc67.JPG)

**Comment by r15ch13** [comment]
Did you try it again?
What is the output of `git status` from inside the `~/scoop/apps/scoop/current` diretory?

**Comment by gigaimage** [comment]
![image](https://user-images.githubusercontent.com/1184087/31008274-5c311c10-a4b8-11e7-95b4-5885d2f979c3.png)

**Comment by gigaimage** [comment]
![image](https://user-images.githubusercontent.com/1184087/31008657-be9fffb4-a4b9-11e7-8368-aef8e9bfb6b6.png)

**Comment by gigaimage** [comment]
![image](https://user-images.githubusercontent.com/1184087/31008948-b0999244-a4ba-11e7-8adb-36a1b58ea126.png)

**Comment by r15ch13** [comment]
What is the output of `fullpath`?
```
> cd ~/scoop/apps/scoop/current
> . .\lib\core.ps1
> versiondir 'scoop' 'current'
> fullpath $(versiondir 'scoop' 'current')
```

**Comment by jsphkm** [comment]
I think I am experiencing the same issue to (I have posted another issue without knowledge of this one):

This is the output for me:
```
PS C:\Users\Username\scoop\apps\scoop\current> versiondir 'scoop' 'current'
C:\Users\Username\scoop\apps\scoop\current
PS C:\Users\Username\scoop\apps\scoop\current> fullpath $(versiondir 'scoop' 'current')
C:\Users\Username\scoop\apps\scoop\current
```
