### ISSUE TITLE
Define user specified directory when installing

### ISSUE THREAD

**Issue by mundusnine** [ScoopInstaller/Scoop#1741]
Hi, 

I wanted to know if it would be possible to add the capability for the install to define and create the folder to extract_to or that would be the new directory to install to in the case that the install is just an extraction of multiple repos from github ? From what I have read this isn't available in the install.ps1 script. The command would look like this: 

scoop install AppToInstall "C:/myDirectoryCreatedByScoop"

Thank you for this tool it is magical :)

m9

**Comment by rashil2000** [comment]
#3559
