### ISSUE TITLE
Make "all" a wildcard alias like "*"

### ISSUE THREAD

**Issue by darthwalsh** [ScoopInstaller/Scoop#1745]
For people comfortable with Chocolatey, `choco update all` is a pretty common phrase.

Could scoop support `all` as another wildcard like `*` (which feels weird to type on a shell as I might expect some kind of globbing.) (Or maybe just a help message?)

Right now you get:
```
>scoop update all
'all' isn't installed.
```

**Comment by ogerardin** [comment]
+1, when I see * on the command line I tend to interpret it as "all files in the current directory", which is obviously not the case here.

**Comment by r15ch13** [comment]
You could add an alias so it's simliar to `apt` and `brew`:
```
λ scoop alias add upgrade "scoop update *"
λ scoop update
λ scoop upgrade
```

**Comment by ogerardin** [comment]
Nice, I guess that will do

**Comment by pedzed** [comment]
Everything after update is a package, so rather than `scoop update all`, I'd say make it `scoop update --all`.

**Comment by darthwalsh** [comment]
@rashil2000  could you clarify why this is closed? If it's WontFix that's fair -- just want to know the outcome.

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Scoop/pull/3871
