### ISSUE TITLE
Change or influence behavior when unable to create shim

### ISSUE THREAD

**Issue by tehbilly** [ScoopInstaller/Scoop#1762]
The current postgresql installation is failing due to commands being different now, and brought this idea to the forefront of my thoughts again: is there a specific reason that shimming is an immediate abort? I would prefer it be a warning, or at least be something I can configure to be a warning instead of a full stop.

Figured I'd open an issue for discussion instead of just making a change and opening a PR, but I'll be happy to help implement a change to bring this about if others think it would be a good idea.

**Comment by rashil2000** [comment]
Fixed
