### ISSUE TITLE
Add `scoop version` to report the git tag (when implemented)

### ISSUE THREAD

**Issue by Ghasan** [ScoopInstaller/Scoop#1829]
Thank you for this awesome tool, it is really handy and minimal.

However, I realized there is no way to get scoop version.

Normally for CLI tools, we just "command --version" to get its details, but there is nothing like this when I checked the help.

**Comment by r15ch13** [comment]
Scoop uses Git to update itself and doesn't use versions. You could say it's a rolling release.
`--version` could print the current git commit it's based on.

**Comment by styfle** [comment]
@r15ch13 Git has the concept of [tags](https://git-scm.com/book/en/v2/Git-Basics-Tagging) which could be used to label each release.
Consequently, tags will show up under [GitHub releases](https://github.com/lukesampson/scoop/releases).

**Comment by r15ch13** [comment]
@styfle Agreed, but that's a decision for @lukesampson to make 😄

**Comment by lukesampson** [comment]
So is the idea to tag as "releases" the commits that affect the program code, rather than just affecting the manifests? I'd be fine with that.

**Comment by rasa** [comment]
Would it make sense to move the main bucket to its own branch, or even a separate repo?
