### ISSUE TITLE
Add command to clear persist data

### ISSUE THREAD

**Issue by dsbert** [ScoopInstaller/Scoop#1854]
It would be nice to add a command to clear persist data for specific apps.

Use case - I installed notepad++ 64bit edition, then uninstalled it and went back to 32bit. This caused the plugins to fail because they were 64bit, and also prevented the 32bit plugins from being installed.

Side note: maybe 32bit and 64bit apps should not share the same persist data?

**Comment by rashil2000** [comment]
Doing `scoop uninstall notepadplusplus --purge` (or `-p` in short) will clear the persistent data.
