### ISSUE TITLE
pre_uninstall post_uninstall

### ISSUE THREAD

**Issue by muhlpachr** [ScoopInstaller/Scoop#1868]
Proposal: support pre_uninstall post_uninstall same way as pre_install post_install

**Comment by vkrol** [comment]
For example we need to unset these settings https://github.com/lukesampson/scoop/blob/master/bucket/yarn.json#L21 in pre_uninstall, I think.

**Comment by wenmin92** [comment]
2 years have passed, why not update the status here?
