### ISSUE TITLE
Documentation: What can I install and how do I add more things to install?

### ISSUE THREAD

**Issue by jchidley** [ScoopInstaller/Scoop#1959]
I find the speed and the simplicity of scoop attractive.  I like that it feels like apt-get or pacman (I am an Arch Linux fan).  

I didn't understand was what 'packages' were available to install, where these 'packages' where found,  how they were updated, etc.

I think they're all held in the [bucket](https://github.com/lukesampson/scoop/tree/master/bucket) and an [extra bucket](https://github.com/lukesampson/scoop-extras).  I assume that this list of packages can be added to somehow - by submitting a pull request?

What else am I missing?  What other documentation is there?

**Comment by h404bi** [comment]
See Wiki: https://github.com/lukesampson/scoop/wiki/Buckets
