### ISSUE TITLE
'scoop cleanup *' raises exception when removing files that used by process

### ISSUE THREAD

**Issue by chawyehsu** [ScoopInstaller/Scoop#2035]
my cases:
- 7zip
- git-with-openssh

``` powershell
$ scoop cleanup *
Removing 7zip: 16.04Remove-Item : Cannot remove item C:\Users\hanabi\scoop\apps\7zip\16.04\7-zip.dll: Access to the path '7-zip.dll' is denied.
At C:\Users\hanabi\scoop\apps\scoop\current\libexec\scoop-cleanup.ps1:48 char:9
+         Remove-Item $dir -Recurse -Force
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (7-zip.dll:FileInfo) [Remove-Item], UnauthorizedAccessException
    + FullyQualifiedErrorId : RemoveFileSystemItemUnAuthorizedAccess,Microsoft.PowerShell.Commands.RemoveItemCommand
Remove-Item : Cannot remove item C:\Users\hanabi\scoop\apps\7zip\16.04: The directory is not empty.
At C:\Users\hanabi\scoop\apps\scoop\current\libexec\scoop-cleanup.ps1:48 char:9
+         Remove-Item $dir -Recurse -Force
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\hanabi\scoop\apps\7zip\16.04:DirectoryInfo) [Remove-Item], IOException
    + FullyQualifiedErrorId : RemoveFileSystemItemIOError,Microsoft.PowerShell.Commands.RemoveItemCommand
```

**Comment by r15ch13** [comment]
Is the file being used by some other process? Did you try deleting it manually?

**Comment by h404bi** [comment]
Restart system would work, but I think if `scoop cleanup` could handle this issue automatically. I have to kill the `ssh-agent` process of git-with-openssh, or even restart the PC every time I update an app.

**Comment by r15ch13** [comment]
We could use some of these solutions to check if a process is accessing any files
https://stackoverflow.com/questions/39190227/how-to-check-if-a-folder-has-no-files-locked-by-any-process

**Comment by dsbert** [comment]
Maybe fail an update by default if the files are in use and display a warning, with a `--force` flag to override.

**Comment by xiaoxstz** [comment]
I came across this issue recently.

* Old version of 7Zip: `24.06`
* New version of 7Zip: `24.07`

I wanted to clean all the old versions with the command `scoop cleanup *`, and then,  I came across this issue.

In the end, I solved it by the steps below.

1. Run the `uninstall-context.reg` in the `24.06` folder
1. Restart the computer
