### ISSUE TITLE
Report the bucket name installing from

### ISSUE THREAD

**Issue by rasa** [ScoopInstaller/Scoop#2121]
If you have a package that's available in two different buckets, scoop doesn't tell you which bucket it's installing an app from. For now, it should tell you the bucket's name, but eventually, perhaps it asks you which one you want?

**Comment by brandon93s** [comment]
Why does the same app exist in multiple buckets, and how does it currently decide which one to install? It could be handled with a prefix, though: 

`bucket:package@version`

In this case, maybe it should error out with a message to choose a bucket instead of choosing one for the user.

**Comment by rasa** [comment]
@brandon93s: To answer your questions:
1. Both [jmcarbo](https://github.com/jmcarbo/scoopbucket.git) and [I](https://github.com/rasa/scoops.git) created a removedrive app ([here](https://github.com/jmcarbo/scoopbucket/blob/master/removedrive.json) and [here](https://github.com/rasa/scoops/blob/master/removedrive.json)). 

2. Scoop probably picks the first bucket alphabetically, but I've have to check the code to be sure.

3. Agreed. If there are multiple matches, perhaps we ask the user to select one (or abort if they add a `--batch` option):
```
$ scoop install remotedrive
A remotedrive package was found in multiple buckets:
1. jmcarbo/remotedrive (2.8.0) (32bit & 64bit)
2. rasa/remotedrive (2.8.7) (64bit only)
Enter the number of the one you want, or press Q to quit: [1-2]? 
```
If the user wants scoop to abort instead, s/he can pass the `--batch` option:
```
$ scoop install --batch remotedrive
ERROR: remotedrive was not installed, as it was found in multiple buckets:
1. jmcarbo/remotedrive (2.8.0) (32bit & 64bit)
2. rasa/remotedrive (2.8.7) (64bit only)
To install from a specific bucket, prefix the package name with 'bucket/`:
scoop install bucket/remotedrive
```

**Comment by rasa** [comment]
@brandon93s: To answer your questions:
1. Both [jmcarbo](https://github.com/jmcarbo/scoopbucket.git) and [I](https://github.com/rasa/scoops.git) created a removedrive app ([here](https://github.com/jmcarbo/scoopbucket/blob/master/removedrive.json) and [here](https://github.com/rasa/scoops/blob/master/removedrive.json)). 

2. Scoop probably picks the first bucket alphabetically, but I've have to check the code to be sure.

3. Agreed. If there are multiple matches, perhaps we ask the user to select one (or abort if they add a `--batch` option):
```
$ scoop install removedrive
A removedrive package was found in multiple buckets:
1. jmcarbo/removedrive (2.8.0) (32bit & 64bit)
2. rasa/removedrive (2.8.7) (64bit only)
Enter the number of the one you want, or press Q to quit: [1-2]? 
```
If the user wants scoop to abort instead, s/he can pass the `--batch` option:
```
$ scoop install --batch removedrive
ERROR: removedrive was not installed, as it was found in multiple buckets:
1. jmcarbo/rremovedrive (2.8.0) (32bit & 64bit)
2. rasa/removedrive (2.8.7) (64bit only)
To install from a specific bucket, prefix the package name with 'bucket/`:
scoop install bucket/removedrive
```

**Comment by rashil2000** [comment]
@rasa 

> Scoop probably picks the first bucket alphabetically

This is correct. The `Get-Manifest` function picks it. 

However, all of Scoop's user-facing commands, and some internal functions too, rely on this alphabetical-first behaviour, so either stopping the function on ambiguity, or pausing for user input, will break all those commands.

The only safe thing to do now is just print the bucket name (which happens to be alphabetically first) that is currently being installed from.
