### ISSUE TITLE
npm install Windows - npm WARN saveError ENOENT: no such file or directory

### ISSUE THREAD

**Issue by kn9** [ScoopInstaller/Scoop#2145]
Hi Guys, Please how do I resolve this error Please.  

PS C:\Users\aa\scoop> scoop install nodejs --global
Installing 'nodejs' (9.8.0) [64bit]
Loading node-v9.8.0-win-x64.7z from cache
Checking hash of node-v9.8.0-win-x64.7z... ok.
Extracting... done.
Linking C:\ProgramData\scoop\apps\nodejs\current => C:\ProgramData\scoop\apps\nodejs\9.8.0
Adding C:\ProgramData\scoop\shims to global path.
Persisting bin
Persisting cache
Running post-install script...
'nodejs' (9.8.0) was installed successfully!
PS C:\Users\aa\scoop> npm install
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\aa\scoop\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\aa\scoop\package.json'
npm WARN scoop No description
npm WARN scoop No repository field.
npm WARN scoop No README data
npm WARN scoop No license field.

**Comment by r15ch13** [comment]
This is not a problem with scoop.
NPM is for installing nodejs dependencies. You have to run it inside a nodejs project folder or use it to install a nodejs program globally (`npm install -g bower`)
See https://docs.npmjs.com/

```
cd your-nodejs-project
npm install
```

**Comment by chisumo2016** [comment]
MINGW64 ~/Desktop/Sites_Project/travel-site
$ npm install jquery
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\bundalla\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\bundalla\package.json'
npm WARN bundalla No description
npm WARN bundalla No repository field.
npm WARN bundalla No README data
npm WARN bundalla No license field.

+ jquery@3.3.1
updated 1 package and audited 1 package in 6.059s
found 0 vulnerabilities

**Comment by trynx** [comment]
I had the same problem and it just was a mistake of not being in the folder of the node it self.
@chisumo2016  as r15ch13 already said try to see that your directory 'C:\Users\buda\' is the one which the project is in.

**Comment by rahulKuthuru** [comment]
@trynx can you elaborate a bit more on what has to be done

**Comment by omar-bakhsh** [comment]
i have error 


Amoory.SO@xxxs MINGW64 ~/Desktop/project
$ npm install
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\Amoory.SO\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Amoory.SO\package.json'
npm WARN Amoory.SO No description
npm WARN Amoory.SO No repository field.
npm WARN Amoory.SO No README data
npm WARN Amoory.SO No license field.

audited 1553 packages in 3.217s
found 0 vulnerabilities

**Comment by virinchimanepalli** [comment]
use npm install -g express

**Comment by israeldavid** [comment]
nothing i try all this solution doesnt work no one,

**Comment by richardbalwane** [comment]
try, npm install npm@latest -g

**Comment by mojo-jojo-ojo** [comment]
do check for package.json file in the directory.
try npm install in the same directory your project is in.
