### ISSUE TITLE
scoop status doesn't work behind proxy

### ISSUE THREAD

**Issue by klauern** [ScoopInstaller/Scoop#2166]
I was following the instructions for using [scoop behind a proxy][1], but I get an error:

    fatal: unable to access 'https://github.com/lukesampson/scoop/': Could not resolve proxy: default

I configured it by using `scoop config proxy currentuser@default`.  This works when trying to install a package, but for whatever reason `scoop status` must not be using this the same way.

[1]: https://github.com/lukesampson/scoop/wiki/Using-Scoop-behind-a-proxy

**Comment by klauern** [comment]
It also appears that unconfiguring the proxy results in `scoop update` not working:

![image](https://user-images.githubusercontent.com/4735/38139058-6c5f92b8-33f3-11e8-95cb-2ee82f20aabc.png)

**Comment by h404bi** [comment]
run `scoop config rm proxy` to unset the proxy

**Comment by klauern** [comment]
That's what I ended up doing, but that means that I have to set the proxy, unset it, and flip it around a bunch because it's not acting consistently.
