### ISSUE TITLE
Autoupdate doesn't support an array of urls

### ISSUE THREAD

**Issue by stkb** [ScoopInstaller/Scoop#2176]
Is there a reason for this? You can have an array of urls in a manifest, and an array or corresponding hashes, but no arrays in the `autoupdate` section.

If not then I'll take a look at fixing this.

**Comment by r15ch13** [comment]
Most of these manifests with an URL array are mingw/msys programs with different version numbers per dependency. Which makes updating them difficult.
For cases like [irfanview](https://github.com/lukesampson/scoop-extras/blob/master/irfanview.json) it definitely makes sense. 👍

**Comment by stkb** [comment]
Yeah those ones don't have any checkver anyway. Thanks for the extra irfanview example. I'm dealing with a similar case now.

**Comment by vii1** [comment]
I encountered this problem trying to [fix the bochs package](https://github.com/ScoopInstaller/Main/pull/567), which needs 2 downloads: one for the data and generic 32-bit binaries, and other for the 64-bit binaries or 32-bit Pentium4 optimized version.

**Comment by linsui** [comment]
See https://github.com/lukesampson/scoop/pull/3518
