### ISSUE TITLE
Updating Python cause PIP Packages Removed!

### ISSUE THREAD

**Issue by yigitemres** [ScoopInstaller/Scoop#2180]
I don't know that is default behavior of Python but, PIP packages are not persistent when updating Python,

**Comment by rasa** [comment]
Are you installing using `pip —user`?

I’m not a python expert, what directories besides `Lib/site-packages` and `bin` does pip install files in?

**Comment by rasa** [comment]
If `—user` is required, we should alert the user via a note.

**Comment by atomicwrites** [comment]
I was actually under the impression you shouldn't use `--user` when you use scoop, i'm not really sure why though. But yeah, I lost my modules, in an update all, and of course the next python thing i did was give a demo. Thankfully i had my dependencies in `requirements.txt` though.

**Comment by zhoujin7** [comment]
Suggest always use virtualenv/venv to create projects and install modules in virtual env. Another recomend tool is pipx.

**Comment by thorstenkampe** [comment]
Please reopen this issue. It's obviously a bug and hasn't been resolved. The suggestion to use `pip --user` results in packages which are only accessible by the current user. The current Python package for Scoop is not portable and thus would be better placed into the "nonportable" bucket.

Background: `pip` by default installs to the `Scripts` and `Lib\site-packages` directories. These are lost when upgrading Python. The obvious solution would be to use the mechanism that Scoop has and link these directories to `persist\python`.

**Comment by thorstenkampe** [comment]
Same issue in #3595 which is still open

**Comment by yigitemres** [comment]
> 
> 
> Suggest always use virtualenv/venv to create projects and install modules in virtual env. Another recomend tool is pipx.

While creating projects you are right. Using venvs is best thing to do but some pip packages are used for daily basis like yeecli, buku etc... When this daily used packages gone after `scoop update *`, scoop turn into very good experience to very bad experience very quickly. For like these reasons I'm not currently use scoop. Scoop has huge potential. Scoop has good community. But scoop lacks very tiny nuances that can damage the experience very badly.

**Comment by meirl1** [comment]
> Please reopen this issue. It's obviously a bug and hasn't been resolved. The suggestion to use `pip --user` results in packages which are only accessible by the current user. The current Python package for Scoop is not portable and thus would be better placed into the "nonportable" bucket.
> 
> Background: `pip` by default installs to the `Scripts` and `Lib\site-packages` directories. These are lost when upgrading Python. The obvious solution would be to use the mechanism that Scoop has and link these directories to `persist\python`.

Good idea, but instead of 'persist\python' I would recommend 'persist\python3.8' or more precisely 'persist\pythonX.Y' as micro updates have backward compatibility.
