### ISSUE TITLE
Invalid path for `scoop\new` when using Cygwin's git instead of git-for-windows

### ISSUE THREAD

**Issue by DRSDavidSoft** [ScoopInstaller/Scoop#2221]
## Details of issue
I was trying to install a new package with scoop (`powershell scoop install sudo`) when the following error occured:
`fatal: Invalid path '/mnt/c/Users/David/C:\Users\David\scoop\apps\scoop\new': No such file or directoryScoop update failed.`

I'm running [Cmder](https://github.com/cmderdev/cmder) on [Hyper](https://github.com/zeit/hyper), and my environment variable `TERM` is set to `cygwin`. Although I wasn't on Cygwin's bash shell at that moment, Cmder uses [Clink](https://mridgers.github.io/clink/) which modifies Cmd's shell with GNU's readline enhancement.

<img width="553" alt="scoop" src="https://user-images.githubusercontent.com/4673812/39214995-a157764c-482b-11e8-80a3-09b59dcba264.png">

## Vanilla CMD
However, when running `scoop update` to trigger the error, even if Cmder/Clink are not running and anything from bash set or injected (notice `TERM` environment variable is not set) the same error is occured:

<img width="445" alt="scoop-cmd-failed" src="https://user-images.githubusercontent.com/4673812/39215256-73a1ef06-482c-11e8-8842-429f15a60718.png">

I don't understand why `/mnt/c/Users/David/` is prepared to scoop's update path.
What should I do to debug this?

Is this problem related to [`unix.ps1`](https://github.com/lukesampson/scoop/blob/master/lib/unix.ps1)?

## Version query

What's the `scoop`'s equivilant of `scoop /v` or `scoop --version` to get the installed version?

**Comment by DRSDavidSoft** [comment]
Here's a screenshot of the result, but a couple of notes first:
- I ran these on powershell, as requested.
- I tried `. C:\Users\David\scoop\apps\scoop\` **`current\`** `lib\core.ps1` instead of the path you specified, I think you meant this instead
- I'm using [Cygwin's git installation](https://stackoverflow.com/q/15692890/1454514) (instead of [git-for-windows](https://gitforwindows.org/))
- When executing `scoop --version`, I get a git error message.

<img width="451" alt="scoop-powershell-test" src="https://user-images.githubusercontent.com/4673812/39329254-fee74e58-49b2-11e8-9f6b-bcea852b9915.png">

## Git issue
I think the most probable issue is related to Git. I didn't know that scoop used Git, so I ran a couple of tests:

- `where-is git.exe`: made sure I was using **Cygwin's Git**, as I've stated above. Returned what I was expecting.
- `$env:Path = "...\git-for-windows\cmd;" + $env:Path`: temporarily switched to **git-for-windows**'s binary.
- `where-is git.exe`: also made sure I indeed switched to **git-for-windows**'s binary.
- `scoop --version`: hmm, it seems that my scoop's installation did not have the `.git` directory. Weird.
- `scoop update`: ran to test if using the `git-for-windows` would make any difference. It actually did! I don't know what `scoop update` actually do, but I think it does something along the lines of `git clone` or `git fetch`.
- `scoop --version`: it's working now! Interestingly, it returns the output of `git log HEAD`.
https://github.com/lukesampson/scoop/blob/e1bb1e91d0027e00874d06c1fb5966cdae27b994/bin/scoop.ps1#L17
- Well, I didn't know that. Guess `scoop` is pretty dependent on git.

<img width="519" alt="scoop-debugging-git-01" src="https://user-images.githubusercontent.com/4673812/39329720-800cabbc-49b4-11e8-8015-71f466e6a9c5.png">

### Result & conclusions

Well, seems everything is working now. I think the culprit of the problem was Git not being able to find the `.git` directory which meant it traversed up to the root directory. I can't make sense of why oddly enough the `.git` directory was missing, but it seems that issuing a `scoop update` regenerated it.

As the results, everything's working fine now in Cmder:
<img width="581" alt="scoop-now-working" src="https://user-images.githubusercontent.com/4673812/39330777-e9620582-49b7-11e8-838b-4edea2700fa1.png">

Seems it didn't had to to with Cmder or environmental variable `TERM` as I previously thought. Anyways I guess this issue can be closed and marked as "SOLVED" now.

Thanks for all the great work you do, I really appreciate your time! :)

**Comment by r15ch13** [comment]
Hi fellow devRanter :smile:

Thanks for this detailed analysis!
Was this a fresh scoop installation or an out of date one?
When scoop is installed the first time it only downloads the master.zip and extracts it, after running `scoop update` for the first time it will update itself to use git.

**Comment by DRSDavidSoft** [comment]
@r15ch13 I considered the latter problem when I stated my possible issue is to modiy `ensure`. 

Anyway, if supporting Cygwin is to be considered, I believe modifying `scoop-update.ps1` to also include `ensure` would be the correct approach. In fact, any call with directory paths (to `git_clone` and similar functions) needs to be `ensure`'d as well.

If this method is acceptable, should I implement it and make a PR? I'd love to see `scoop` working with Cygwin's git! :)

**Comment by r15ch13** [comment]
Okay, please create PR 👍

**Comment by DRSDavidSoft** [comment]
@kenijo Hey, since **shark** provides Scoop and Cygwin, have you ever ran into this issue (#2221) where the Git installation from Cygwin conflicts with Scoop calls?

**Comment by kenijo** [comment]
I actually have never tried. I started shark as a fork of cmder but it is now pretty far from it in its implementation. shark actually download the latest version of the application you are interested in (conemu, consolez, cygwin, git, php, etc) and uses a profile folder with customisations similar to cmder.
At the end of the day, if you install Git and Scoop independently then it should work with shark but I never tried it.
