### ISSUE TITLE
Special characters in Windows user names will cause command scripts in "shims" to fail.

### ISSUE THREAD

**Issue by bjornakr** [ScoopInstaller/Scoop#2230]
My Windows username, automatically created when logging into Microsoft at install time, contains the letter 'ø'.

This is the real path of my recently installed application:
`c:\Users\Bjørn\scoop\apps\sbt\current\bin\`

This is the contents of the shim command:
`@"C:\Users\Bj?rn\scoop\apps\sbt\current\bin\sbt.bat"  %*`

When trying to run my application, it gives the following message:
```
>sbt
The system cannot find the path specified.
```

**Comment by rasa** [comment]
Shouldn’t
https://github.com/lukesampson/scoop/blob/master/lib/core.ps1#L292
etc, use utf-8 encoding, instead of ascii?

**Comment by pendenaor** [comment]
I've got the same issue, but this bug seems to be related to an already fixed issue https://github.com/lukesampson/scoop/issues/572
