### ISSUE TITLE
Package still get installed after hash check failed

### ISSUE THREAD

**Issue by gengen1988** [ScoopInstaller/Scoop#2245]
![image](https://user-images.githubusercontent.com/1947568/39660140-311d7b4a-506b-11e8-88cb-ef777957fc1e.png)

I believe hash checking prevents the man-in-the-middle attack. A package failed in check may injected with malware and should not be install.

**Comment by r15ch13** [comment]
It doesn't get installed. The error message shows up because scoop has already created an empty directory and the check if it's installed gets it wrong. This a bug.

**Comment by niheaven** [comment]
Fixed in #4650
