### ISSUE TITLE
Icon-Logo Proposal

### ISSUE THREAD

**Issue by Tobaloidee** [ScoopInstaller/Scoop#2261]
Hi Sir @lukesampson ,Good day! I am a graphic designer and I want to contribute to your amazing project by proposing an icon-logo design. If you like and want to use it, I will be gladly sending you the files as a gift to the project for free. Please let me know if you have any ideas or suggestions. I saw that Scoop does not have a logo yet that's why i am proposing one. 
here it is Sir with 3 variations:

icons
![scoop-01](https://user-images.githubusercontent.com/36028424/40154388-b2f895e2-59c0-11e8-919d-54dbd1a95eda.png)
![scoop-02](https://user-images.githubusercontent.com/36028424/40154391-b6098b24-59c0-11e8-832d-8521a8e7883b.png)
![scoop-03](https://user-images.githubusercontent.com/36028424/40154392-b812c61a-59c0-11e8-8354-9a043b08b54c.png)

logotypes
![scoop-04](https://user-images.githubusercontent.com/36028424/40154404-c374ea74-59c0-11e8-9cea-a170210af905.png)
![scoop-05](https://user-images.githubusercontent.com/36028424/40154407-c605e90a-59c0-11e8-9ca2-849c317e15bc.png)
![scoop-06](https://user-images.githubusercontent.com/36028424/40154408-c7b78808-59c0-11e8-887f-3a15af29593b.png)

I hope you will like and use it Sir.

Thanks and best regards!
-Tobaloidee

**Comment by apintocr** [comment]
Greetings @Tobaloidee I'm also a graphic designer and I must say **I love your concept**, **great work**!

I'd like to make a suggestion for improvement:

- Add a little more weight to the lines and the S, also increase the spacing on the elements. The logo will be used a lot in lower resolutions and smaller sizes, making it harder to scale down like this.

![image](https://user-images.githubusercontent.com/1459530/40576515-c6e1ed66-60ef-11e8-8cd4-8a9dfe89b6ef.png)

That's just it :)

**Comment by Tobaloidee** [comment]
![scoop-01](https://user-images.githubusercontent.com/36028424/40583190-fc216ffc-61bb-11e8-889a-d24ff2ffd4da.png)
![scoop-02](https://user-images.githubusercontent.com/36028424/40583192-036f5f94-61bc-11e8-9d83-73df481e3bc7.png)
![scoop-03](https://user-images.githubusercontent.com/36028424/40583193-03acafde-61bc-11e8-86d0-182d8bf0fdfc.png)
![scoop-04](https://user-images.githubusercontent.com/36028424/40583194-073801b2-61bc-11e8-8922-c7365b07e782.png)
![scoop-05](https://user-images.githubusercontent.com/36028424/40583195-07937858-61bc-11e8-8a37-aaa8820a6c49.png)
![scoop-06](https://user-images.githubusercontent.com/36028424/40583196-07cc8814-61bc-11e8-92e5-52221a9f7966.png)

![favicon](https://user-images.githubusercontent.com/36028424/40583209-46a8c2a0-61bc-11e8-9b83-9f8172da85a2.png)

**Comment by Calinou** [comment]
This looks pretty nice :smiley:

Maybe the small > should be removed as to simplify the logo and make it easier to identify at small resolutions.

Also, what font did you use for the logotype? Make sure its license allows usage in a logo – the font should preferably be licensed under an open source license.

**Comment by apintocr** [comment]
@calinou removing the > will destroy the concept of the logo. From my point of view, that's something to keep.

Regarding the font, it should be double checked for the license.

**Comment by apintocr** [comment]
@tobaloid I really like the improvement!

Much more readable and kept the same feel :)

Please keep the >  as it is in my opinion the core concept. But I do agree that in small sizes it gets reduced visibility.

Maybe making a different icon for smaller sizes? It's a growing Trent (responsive logos) that makes a lot of sense in the digital world.

But it is very good as is and can be used without further changes, the suggested improvements can be done as needed :)

**Comment by h404bi** [comment]
Beside logo, I'm interested in whether there will be a mascot proposal. 😝  
Like:
![Linuxbrew](https://camo.githubusercontent.com/3bb569e5252ff81064430fba8270c96351ccd20f/687474703a2f2f6c696e7578627265772e73682f696d616765732f6c696e7578627265772d323536783235362e706e67)

**Comment by Tobaloidee** [comment]
I have made it more simple and removed the symbol and i think it is just as fine and more visible in small size..here's it is with its favicon actual size

![favicon-07](https://user-images.githubusercontent.com/36028424/40585939-87d1735a-61ec-11e8-80f2-da85dbff082d.png)
![favicon-08](https://user-images.githubusercontent.com/36028424/40585940-8ae3fef0-61ec-11e8-97bd-b9a457cb6a4e.png)
![favicon-09](https://user-images.githubusercontent.com/36028424/40585941-8d1a46ac-61ec-11e8-814f-3aa4f14141dd.png)



actual favicon size 32x32
![favicon 1](https://user-images.githubusercontent.com/36028424/40585914-650dc062-61ec-11e8-9acf-d730f0a568ab.png)
![favicon 2](https://user-images.githubusercontent.com/36028424/40585942-90ad2faa-61ec-11e8-9b1f-38c4163243da.png)
![favicon 3](https://user-images.githubusercontent.com/36028424/40585944-9914fd1c-61ec-11e8-9a66-b3498e0e8d4f.png)


The font i use in the logotype is [Myriad Pro ](https://www.fontpalace.com/font-download/MyriadPro-Regular/)

**Comment by Calinou** [comment]
> The font i use in the logotype is Myriad Pro

[Myriad Pro](https://en.wikipedia.org/wiki/Myriad_(typeface)) appears to be a proprietary Adobe font; try using a font such as Source Sans Pro, Noto Sans or Lato instead.

**Comment by gbursson** [comment]
"S" in the logo looks funny. As if the top curve wa longer than the bottom one, looks unbalanced for the lack of better word.

**Comment by r15ch13** [comment]
Another Logo by @ekoeryanto (See: https://github.com/lukesampson/scoop/issues/2261)

![](https://scoop.now.sh/scoop.svg "Logo")

**Comment by ekoeryanto** [comment]
@r15ch13 for looping me here.

>  (See: #2261)

eh, why did you point to the same issue page?

**Comment by excitoon** [comment]
For me it is too many details in logo...

**Comment by ekoeryanto** [comment]
@excitoon which logo?

**Comment by Garfield550** [comment]
![40585939-87d1735a-61ec-11e8-80f2-da85dbff082d](https://user-images.githubusercontent.com/3471836/53152731-56bb0b80-35f1-11e9-81d1-29d3eb0c0572.png)

When I first saw this icon, I thought it was a digital currency icon.

**Comment by IhnatKlimchuk** [comment]
How about this?
![Alt text](http://proburo.ru/catalog/350x350/30/-00/30-0021.png "COBOK")

**Comment by dsbert** [comment]
So what does this icon specifically represent about scoop? Seems a bit generic at the moment.

**Comment by kiedtl** [comment]
> > The font i use in the logotype is Myriad Pro
> 
> [Myriad Pro](https://en.wikipedia.org/wiki/Myriad_(typeface)) appears to be a proprietary Adobe font. Please look at using an open source font such as Source Sans Pro, Noto Sans or Lato instead.

What about the Hack font?

**Comment by Calinou** [comment]
@kiedtl Hack is a fixed-width font with a very different appearance, it probably wouldn't fit the logo's current style.

**Comment by kiedtl** [comment]
Not so sure about that. Even if Hack doesn't look nice, I think either Fira or FiraCode would do.

**Comment by CardealRusso** [comment]
close
although it seems to be something harmless, small but beautiful, is something that goes against the basic principles of the scoop:
be functional, nothing more than functional, only functional

to continue without any logo allows the same to pass this virtual image of the program is focused exclusively on functions and not on trivial things that the mass wants
because we are frank, to use scoop, you must have a minimum of intellect. less than 10% of the world's computer users would be able to use the scoop
using an icon or logo would be against your own self-philosophy

**Comment by kiedtl** [comment]
Why close the issue?

**Comment by itsmeboy0** [comment]
https://github.com/ScoopInstaller/Scoop/issues/2261

**Comment by rashil2000** [comment]
Scoop has a logo now: https://github.com/ScoopInstaller.png

**Comment by sitiom** [comment]
I've recreated the Scoop logo in SVG using the original vector source (thanks, free trial) with Scoop's color palette:

| **Logo**<br>https://scoop.sh/logo/scoop-bg.svg            | **Logo (No Background)**<br>https://scoop.sh/logo/scoop.svg                                                                                     |
|------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------|
| <img src="https://scoop.sh/logo/scoop-bg.svg" alt="Scoop Logo" width="350"> | <img src="https://scoop.sh/logo/scoop.svg" alt="Scoop Logo - No Background" width="350"> |

Relevant discussion: #5516
