### ISSUE TITLE
Better documenting of environment variables

### ISSUE THREAD

**Issue by spadino** [ScoopInstaller/Scoop#2270]
Just clean reinstalled my windows to the last build, and I took the chance to rethink the whole layout.
I permanently and globally moved my Users folder to another partition (D:) and, as soon as my OS is ready, I proceeded to install scoop.

Part of my layout rethinking also was how and where programs installed. At first, I took a look at how scoop use its environment variables, and I saw that I could change many of them. So, I decided that I want users installed programs available for all users, but in the same partition of my users, and globally available tools - development, etc... - in the root of the first partition. As I already used c:\Tools for some other addons and programs, I opted for it. So, that's becomes my setup routine:

After opened Power Shell:
```
[environment]::setEnvironmentVariable('SCOOP','D:\Tools','User')
$env:SCOOP='D:\Tools'
```
That's put user installed apps in a folder available for all users to read from.
Than:
```
[environment]::setEnvironmentVariable('SCOOP_GLOBAL','C:\Tools','User')
$env:SCOOP_GLOBAL='C:\Tools'
```
That tell to scoop to install in C:\Tool all global programs, for a convenient and clean approach.

Finally:
```
iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
```
and all is ready to go!

I think that it is not a real issue, but if environment variables could be better documented, many other users can benefit from them!

**Comment by r15ch13** [comment]
Thanks, you are absolutely right! 👍 
It's mentioned briefly on the [Quick-Start Wiki Page](https://github.com/lukesampson/scoop/wiki/Quick-Start) but I think it should also be added to the [README.md](https://github.com/lukesampson/scoop/blob/master/README.md) and also to the main website. May I ask you for a pull-request? 😄

**Comment by spadino** [comment]
@r15ch13, thanks for your feedback. I certainly can prepare a pull request, however I'm not sure I have much more information to include. I'll give it a look, ok? ;)

**Comment by nicksettoon** [comment]
just FYI this is still not clearly documented in either the README or the Quick Start. you have to go to a powershell script to get the full list and defaults as far as i can tell. 

https://github.com/ScoopInstaller/Scoop/pull/4579
