### ISSUE TITLE
ssh-copy-id ERROR

### ISSUE THREAD

**Issue by malikyusuf** [ScoopInstaller/Scoop#2303]
When I try to execute this: `ssh-copy-id -i ./.ssh/id_rsa.pub user@myserver`
I get the following error: 

```
ssh-copy-id -i ./.ssh/id_rsa.pub user@myserver
C:\Users\Malik\scoop\apps\ssh-copy-id\current\ssh-copy-id.ps1 : ERROR: Cannot run a document in the middle of a pipeline: C:\Users\Malik\scoop\shims\ssh.
At C:\Users\Malik\scoop\shims\ssh-copy-id.ps1:2 char:69
+ ... n.expectingInput) { $input | & $path  @args } else { & $path  @args }
+                                                          ~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,ssh-copy-id.ps1
```

Can anyone please tell me what could be the reason for the error ? Thanks.

**Comment by rasa** [comment]
Deevus forked https://github.com/VijayS1/Scripts/tree/master/ssh-copy-id in 2015, and committed [this change](https://github.com/deevus/ssh-copy-id-posh/commit/a75f94aca42aa6c18f631957f3d1ef6b606d0d43), but hasn’t backported any following changes.
