### ISSUE TITLE
scoop checkup could check for mapped drive

### ISSUE THREAD

**Issue by npenin** [ScoopInstaller/Scoop#2355]
Current behavior: scoop install $thing fails due to $env:SCOOP living on an network mapped drive
scoop checkup did not verify that $env:SCOOP (and presumably its $env:SCOOP_GLOBAL friend) resides on an NTFS volume
Expected behavior: scoop checkup would report "Scoop requires an NTFS volume to work" (optionally including to work "to make use of junction links", if the primary audience is technical folks, since I bet that is the clearest)
I have an SSD for my primary volume, and put development stuff (Maven home, most git checkouts, that kind of thing) on the larger, non-Windows volume. So, when I pointed $env:SCOOP at H:\tools\Scoop, things did not end well.
```ps
PS D:\> scoop install 7zip
Installing '7zip' (18.05) [64bit]
7z1805-x64.msi (1,7 MB) [=====================================================================================] 100%
Checking hash of 7z1805-x64.msi... ok.
Extracting... done.
Linking H:\tools\scoop\apps\7zip\current => H:\tools\scoop\apps\7zip\18.05
Des volumes NTFS locaux sont requis pour terminer cette opération.
Creating shim for '7z'.
Can't shim '7z.exe': File doesn't exist.
```

**Comment by npenin** [comment]
outrageously copied well descripted issue #1944

**Comment by rashil2000** [comment]
Hi, are you still facing this issue?
