### ISSUE TITLE
Imagemagick doesn't find ghostscript

### ISSUE THREAD

**Issue by carstenblt** [ScoopInstaller/Scoop#2389]
By default, convert commands fail, because imagemagick is trying to call `gswin32c.exe`, which is not installed on a 64-bit machine. A dirty solution is replacing all `@PSDelegate@` with `gswin32c` in imagemagick's `delegates.xml` file. Maybe there is a cleaner method?

**Comment by raikesy** [comment]
I've just run into this too. It occurs with scoop installed Ghostscript but not with officially installed Ghostscript so I suspect it's to do with registry keys added by the official installer but not by scoop. I tried adding equivalent keys pointing to the scoop Ghostscript installation but while it did cause Imagemagick to look in the correct (scoop) directory, it was still looking for `gswin32c.exe` not `gswin64c.exe` as hoped. 

For now I'm just using a traditional install of Ghostscript until a workaround is figured out.
