### ISSUE TITLE
Update failed.

### ISSUE THREAD

**Issue by hfaran** [ScoopInstaller/Scoop#2410]
```
hamza@DESKTOP-JD1H8BG ~ $ scoop update
Updating Scoop...
Update failed.
hamza@DESKTOP-JD1H8BG ~\scoop\apps\scoop\current master = $
```

Running scoop update just returns an update failed with no further info (and drops me in ~\scoop\apps\scoop\current)

**Comment by 0x326** [comment]
@hfaran Do you have Git installed (e.g. `scoop install git`)?

**Comment by hfaran** [comment]
It turns out there was something really wrong with my git client (previously installed using scoop). It was just crashing without warning.
I installed git from elsewhere and then ran scoop update and it worked.

**Comment by rasa** [comment]
This error message should be enhanced to something like:
```
FATAL git failed pulling bucket x (error n)
```

**Comment by rashil2000** [comment]
Tracked in #4358
