### ISSUE TITLE
Discussion about recent OpenSSH issues

### ISSUE THREAD

**Issue by r15ch13** [ScoopInstaller/Scoop#2414]
Wanted to discuss the issues OpenSSH is causing lately.

- Connection issues with `repo.msys2.org`: #2388
- Mismatching checksums for various files: #2412 #2375 #2373 #2372 #2371 #2366 #2353 #2414
- Extractions not working: #2386

Possible solutions:

1. leave the manifest like it is now? [openssh.json](https://github.com/ScoopInstaller/Main/blob/master/bucket/openssh.json)
2. use another download source than `repo.msys2.org`
3. swap it with the `git-with-openssh` manifest silently
  a. `version` property shows GIT version instead of OpenSSH
  b. auto update works
4. change it to an fixed version of `git-with-openssh` (Example: [rivy/openssh](https://github.com/rivy/scoop-bucket/blob/master/openssh.json))
  a. `version` property shows OpenSSH version
  b. no auto update
5. change it to `win32-openssh` silently
  a. it's still in beta
6. change it to a meta package that installs `git-with-openssh` via `depends` property?
7. change it to an empty meta package that does nothing
  a. will most likely kill all automated processes
    ```json
    {
        "homepage": "https://git-for-windows.github.io/",
        "url": "https://git-for-windows.github.io/",
        "license": "GPL-2.0",
        "version": "7.7p1",
        "suggest": {
            "Git with OpenSSH": [
                "git-with-openssh"
            ],
            "Portable OpenSSH": [
                "win32-openssh"
            ]
        },
        "notes": "This is a placeholder! Please install 'git-with-openssh' or 'win32-openssh' instead!"
    }
    ```

**Comment by rasa** [comment]
Another possibility is openssh depend on git and then shim the usr/bin/ssh*.exes in the post_install. But I guess that would frustrate users who want openssh without git, or who later decide to uninstall git.

**Comment by gbursson** [comment]
If I can add my 0.02PLN:
_change it to **win32-openssh** silently_

The fact that it's still in beta should not matter, I believe it's mature enough to be used.

**Comment by h404bi** [comment]
Changing `openssh` it to `win32-openssh` is my suggestion. It does not matter that it's still in beta, because Windows 10 RS4 has included it as a built-in tool. This is a good enough reason.

**Comment by rasa** [comment]
I added an rsync-via-git.json to show how we can easily install other apps inside the git app's directory. Initial testing is encouraging.

**Comment by se35710** [comment]
There is also the PuTTY way, using plink and Pageant:

1. `$Env:GIT_SSH=~\scoop\apps\putty\current\plink.exe`
2. Import the key to PuTTY's Pageant
3. Clone repo and set `remote.origin.url=git@github.com:<username>/<repo>.git`

**Comment by h404bi** [comment]
But another problem is, win32-openssh isn't a good choice for those users who don't have elevated permission, since it is implemented as an OS service, restricted users cannot install its services.
