### ISSUE TITLE
`scoop install extras atom`

### ISSUE THREAD

**Issue by borekb** [ScoopInstaller/Scoop#2418]
What do you think about adding `scoop install extras atom` as an explicit way to install `atom` from the `extras` bucket? Maybe even doing that without `scoop bucket add extras`.

It would work similarly to Homebrew Cask which is `brew cask install atom`.

BTW, I'm new to Scoop, what an amazing project! Thank you!

**Comment by r15ch13** [comment]
This is already supported, you can even run `scoop install extras/atom@1.0.0`. but you have to add the buckets first. :smile:

**Comment by rasa** [comment]
But should we require adding the bucket, if the user specifies it?

**Comment by h404bi** [comment]
Maybe he wants a feature like: when executing `scoop install extras/atom` to install atom from `extras`, auto tap extras bucket before installation if he didn't add it yet, instead of writing out an error. But the problem is we don't know the bucket name user give does has its corresponding bucket  repository, except for those buckets listed in `buckets.json`.

**Comment by r15ch13** [comment]
May work by combining it with https://github.com/rasa/scoop-directory 😁

**Comment by r15ch13** [comment]
You have to use the actual link to the file (by clicking on the "Raw"): https://raw.githubusercontent.com/lukesampson/scoop-extras/master/atom.json

https://github.com/lukesampson/scoop-extras/blob/master/atom.json is just the GitHub page :smile:

**Comment by borekb** [comment]
OMG it's too late here :) Thank you.

So that would mean that `scoop install extras/<some-app>` gives Scoop enough information on which app to install, right?

**Comment by r15ch13** [comment]
if you added the extras bucket, then yes.

**Comment by borekb** [comment]
I meant without that. `extras` is a known bucket so `extras/atom` provides enough information to Scoop, doesn't it?

**Comment by r15ch13** [comment]
No, then it would show you a message about missing the extras bucket :smile:

**Comment by borekb** [comment]
What would happen if Scoop simply translated

```
scoop install extras/some-app
```

to

```
scoop install https://raw.githubusercontent.com/lukesampson/scoop-extras/master/some-app.json
```

and carried on? Seems like a simpler model than cloning repositories locally (and later having to worry about keeping them up to date).

**Comment by rasa** [comment]
If the `extras` hasn't already been added, and the user requests installing an app from it, we could:
1. Auto-add the bucket, and then install from it
2. Ask the user if he wants to add the bucket, before continuing
3. Fail with an error message.
Right now, we do 3., but 1. and 2. are more user friendly. It could even default to 2. unless the user adds `-y` or `--yes` to the command or sets it as a config setting, say `scoop config SAY_YES 1`

**Comment by borekb** [comment]
> Right now, we do 3., but 1. and 2. are more user friendly. It could even default to 2. unless the user adds -y or --yes to the command or sets it as a config setting, say scoop config DEFAULT_ANSWER yes

Sounds good, though I still wonder why to clone any repo (bucket) to my computer in the first place.

**Comment by gbursson** [comment]
I do not think you clone the repo to your computer when adding a bucket?
you merely add a "pointer" so to speak for scoop to know where are packages located?

**Comment by r15ch13** [comment]
Checking for updated programs or finding programs to install would require a lot more web requests if we didn't have a local copy of these buckets. We could just download the master.zip for each repo, but then Scoop can't show a changelog. Running `git clone/pull` and let it handle new/delete/updated files is easier :smile:

**Comment by borekb** [comment]
@r15ch13 Thanks, that makes sense.

What happens if I install an app by directly pointing scoop to a remote URL, like `scoop install https://raw.githubusercontent.com/lukesampson/scoop-extras/master/some-app.json`? Is such app excluded from updates? Does it have any other side-effects?

**Comment by rashil2000** [comment]
Installing from a local or remote URL excludes the app from getting updated. If you want updates, add a bucket or create your own bucket with app you like.
