### ISSUE TITLE
ssh-copy-id.ps1 is looking for id_rsa.pub in the wrong place

### ISSUE THREAD

**Issue by kenorb** [ScoopInstaller/Scoop#2430]
When running `ssh-copy-id`, it's looking for `id_rsa.pub` in user's folder, instead of in `~/.ssh`.

```
C:\Users\kenorb>ssh-copy-id somehost
C:\Users\kenorb\scoop\apps\ssh-copy-id\current\ssh-copy-id.ps1 : ERROR: Cannot find path 'C:\Users\kenorb\id_rsa.pub' because it
does not exist.
At line:1 char:1
+ & 'C:\Users\kenorb\scoop\apps\ssh-copy-id\current\ssh-copy-id.ps1'  s ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,ssh-copy-id.ps1
```

**Comment by rasa** [comment]
We may want to see if openssh’s ssh-copy-id works. See 
https://github.com/rasa/scoop/blob/19dd7995ac551b37f1e640c7a8429151cc6f2bfc/bucket/openssh.json#L16

**Comment by kenorb** [comment]
I believe  OpenSSL's `ssh-copy-id` is working fine, as after I've uninstalled `ssh-copy-id` package, I could still run `ssh-copy-id` from OpenSSL which worked.

**Comment by leonyu** [comment]
Looks like that's the functionality of the provided package: 
https://github.com/VijayS1/Scripts/blob/master/ssh-copy-id/ssh-copy-id.ps1

It doesn't conform to the OpenSSH implementation, but then again if you are on windows you could be using OpenSSH from Microsoft, Cygwin, Git-Bash, MSYS, etc. They all store your key at different locations.

**Comment by chuanjiao10** [comment]
my ssh-copy-id6.ps1
https://github.com/PowerShell/Win32-OpenSSH/issues/341
