### ISSUE TITLE
Shorter install one-liner

### ISSUE THREAD

**Issue by jordanbtucker** [ScoopInstaller/Scoop#2473]
What is the reason that https://scoop.sh has a long install one-liner

```ps
iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
```

when something like

```ps
iwr -usebasicparsing https://get.scoop.sh | iex
```

is shorter and IMO easier to remember?

I usually just use `iwr get.scoop.sh | iex` since it works in most cases, but `-usebasicparsing` is required in some scenarios.

**Comment by gerardog** [comment]
And why does not provide something that can be pasted on CMD like:
```
powershell -c Set-ExecutionPolicy RemoteSigned -Scope Process; iwr -usebasicparsing https://get.scoop.sh | iex
```

**Comment by Calinou** [comment]
@gerardog Recent versions of Windows 10 default to PowerShell. It might not be worth doing this as much as before now.

Either way, a short installation one-liner was added to https://scoop.sh a while ago. I think this issue can be closed now.
