### ISSUE TITLE
Is there a way to hide the warnning message while using 'aria2c'?

### ISSUE THREAD

**Issue by waderchan** [ScoopInstaller/Scoop#2482]
$ scoop update *
Latest versions for all apps are installed! For more information try 'scoop status'
**WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.**

**Comment by jsamuel1** [comment]
Bump.   Would still be nice to have. :)

**Comment by kylo252** [comment]
Another bump! I think I can recite it backwards having seen for the 500th time :)
