### ISSUE TITLE
Aria2c failed to download from FossHub file links

### ISSUE THREAD

**Issue by LexSong** [ScoopInstaller/Scoop#2488]
Related issue: https://github.com/lukesampson/scoop-extras/issues/1125

Aria2c ended up with corrupt zip files when downloading from FossHub.

I tried to disable Aria2c but still not working.

File link: https://www.fosshub.com/IrfanView.html/iview451_plugins_x64.zip

**Comment by rasa** [comment]
This might be due to FossHub tightening up their requirements.
