### ISSUE TITLE
Support for "Proxied" Manifests

### ISSUE THREAD

**Issue by sgarfinkel** [ScoopInstaller/Scoop#2526]
I have some common, post-install/post-update tasks that I would like to run on existing app manifests, but would prefer to not have to mirror (and also maintain) those parallel manifests.

For example, I need to run keytool on Java installations in order to use it behind a corporate proxy. I need to run this anytime (unless cacerts are persisted, I haven't looked but I suspect not) I install/update Java. 

Instead of self-hosting a complete manifest for the Java installations, is it possible to host a proxying manifest that defers to the production manifests for handling installation then runs whatever other tasks I've defined in the original manifest?

**Comment by rashil2000** [comment]
No. Whatever needs to be done, should be done from the single manifest itself.
