### ISSUE TITLE
Change location of the "Scoop Apps" folder

### ISSUE THREAD

**Issue by Stanzilla** [ScoopInstaller/Scoop#2547]
Why not put the shortcuts into the start menu directly instead of using the `Scoop Apps` folder? Would make them feel more "native" if you know what I mean, taking scoop out of the shortcut making them feel like they were installed "normally".

One suggestion by @rasa was to use 

`scoop config startmenu_folder “Scoop Apps”` as a config option and default to “” for new installs?

Would fix https://github.com/lukesampson/scoop/issues/2124

**Comment by maley-typek** [comment]
It doesn't seems to work. Still adding start menu shortcuts to the "Scoop apps"
