### ISSUE TITLE
python installed, but it does not append root directory into PATH

### ISSUE THREAD

**Issue by ghost** [ScoopInstaller/Scoop#2644]
I installed several different python versions via scoop, followed the order: `pypy2 -> python27 -> python35 -> python36 -> python` (as you know, `python` is python 3.7), but all other versions except 3.7 work fine; python 3.7 cannot be run indirectly (e.g. run cmd and just type `python` and enter.)
Since installing `python` does not append its root directory into PATH (unlike other versions), it was occurred. Thanks.

**Comment by rasa** [comment]
This is a known limitation to scoop, and has been reported previously.

**Comment by snowtale** [comment]
@rasa Could you give me the link previously reported? I thought it is easily solvable by modifying `bucket/python.json` as follows:
```
"env_add_path": [
        ".",
        "scripts"
],
```

**Comment by rasa** [comment]
I found this: https://github.com/lukesampson/scoop/issues/1716

Your fix may work. Reopening.
