### ISSUE TITLE
Batch file scripting is broken

### ISSUE THREAD

**Issue by vsDizzy** [ScoopInstaller/Scoop#2659]
**install.bat**
```bat
scoop install git nodejs
scoop bucket add extras
scoop install vscode
```

Only first line is executed.
Workaround is to use .ps1 instead.

**Comment by vsDizzy** [comment]
I think it is due to the `exit` keyword is used everywhere. I'm not a PowerShell guru, but I believe `throw` should be used to indicate errors.

**Comment by myAlterX** [comment]
exit needs a /b to exit the batch file but not the cmd session:

>  When used in a batch script, this option will exit only the script (or subroutine) but not CMD.EXE
>  If executed on the command-line it will close CMD.exe

see here https://ss64.com/nt/exit.html

I guess this means any script that uses exit without this flag will break a batch file installing multiple programs...

**Comment by rasa** [comment]
The scoop command is a batch file (scoop.cmd), so you need to preface each with `call`:
```
call scoop install git nodejs
call scoop bucket add extras
call scoop install vscode
```
