### ISSUE TITLE
scoop cleanup removes all versions of app.

### ISSUE THREAD

**Issue by ShivanshuKantPrasad** [ScoopInstaller/Scoop#2666]
According to `scoop help`  `cleanup` should remove old versions of all the apps but when i ran `scoop cleanup .`  after updating few apps, it removed all the versions of all apps including itself.
Is this a bug or is the `scoop help` misleading?

**Comment by h404bi** [comment]
You should use `*` to clean all outdated apps instead of `.`. But it's a good catch, perhaps the logic of `cleanup` command needs to be improved.

**Comment by Ash258** [comment]
@h404bi It's same for uninstall. If you uninstall package starting with `_`/`.` all apps will be uninstalled (#2370)

**Comment by ShivanshuKantPrasad** [comment]
I guess then it should either not allow `_/.` or escape them as it seems they are interfering with the regex system used.
