### ISSUE TITLE
Better Docs

### ISSUE THREAD

**Issue by ekoeryanto** [ScoopInstaller/Scoop#2674]
Hello, I have free time here, trying to rework documentation for scoop.

But before I go further, I need to know your response about it.

~~https://scoop.surge.sh/~~ https://scoop.netlify.com or https://scoop.now.sh
source: [pakeweb/scoop.sh](/pakeweb/scoop.sh)

## Plan:
1. Migrate the wiki page to the site
2. Page for searching app (via GitHub Rest API)
3. Localization

**Comment by r15ch13** [comment]
Cool! The logo looks nice 👍 

Utilizing GitHub's API to search for Buckets and Manifests was also on my mind. 😁

Searching for `scoop-bucket` [topics](https://developer.github.com/v3/search/#search-topics) (requires `Accept: application/vnd.github.mercy-preview+json` header):
https://api.github.com/search/repositories?q=topic:scoop-bucket

**Comment by ekoeryanto** [comment]
Thanks @r15ch13.
Aha.. I am not a graphic designer like @apintocr and @Tobaloidee. just quick simple logo creation to fill site design 🤣

**Comment by r15ch13** [comment]
Memo to myself:
GraphQL queries https://developer.github.com/v4/explorer/
```graphql
{
  search(first: 10, query: "scoop-bucket", type: REPOSITORY) {
    edges {
      node {
        ... on Repository {
          name
          nameWithOwner
          url
          description
          stargazers {
            totalCount
          }
        }
      }
    }
  }
}
```

**Comment by r15ch13** [comment]
@Calinou https://github.com/pakeweb/scoop.sh

**Comment by bcatubig** [comment]
These look fantastic! Do you need any additional help?

**Comment by ekoeryanto** [comment]
Thanks @bcatubig.
I am not an _English Man_ also not good in documentation, so the content still need to be altered as it only a migrated github wiki

**Comment by h404bi** [comment]
Now mentioned in [Awesome Scoop](https://github.com/h404bi/awesome-scoop). [![Mentioned in Awesome Scoop](https://awesome.re/mentioned-badge.svg)](https://github.com/h404bi/awesome-scoop/commit/aceb68204eb203c18af17d71d6bfcca47bf93c1d "Awesome Scoop")
