### ISSUE TITLE
Path 'pollution' is not working

### ISSUE THREAD

**Issue by vsDizzy** [ScoopInstaller/Scoop#2693]
According to the docs, scoop should not pollute environment Path, but it does so aggressively.
![image](https://user-images.githubusercontent.com/5798340/47238701-adb69700-d3eb-11e8-889f-04e0944a3299.png)

**Comment by Ash258** [comment]
That depends on manifest. Some apps need to use own registry variables and path extensions to work.

https://github.com/lukesampson/scoop/blob/dd12ec482c8dfa9d2b617e46ff9ceb485471be84/bucket/nodejs.json#L21-L24

Most of manifest use only `\shims`.

**Comment by fujii** [comment]
I don't want to put installed apps in my PATH.
I'd like to suggest a new command 'scoop shell' to start a PowerShell with PATHs of all installed apps, or 'scoop env' to dump all PATHs.

**Comment by bcatubig** [comment]
That idea sounds familiar to how `Pipenv` works. I'm not sure what type of refactoring that would include, but does seem interesting.

**Comment by MunsterPlop** [comment]
That's actually becoming an issue for me. I installed quite a few softwares with scoop and lately I keep hitting the user PATH variable characters limit (2047), which just ends up truncating itself whenever I try to install something new, sometimes even messing up the shims path.

**Comment by kbytesys** [comment]
I've the same problem, when the PATH variable go over the 2047 limit everything is screwed up and I've to remove items manually. I see that the issue type is "enhancement", but is a real bug for me because this breaks my system.

**Comment by rashil2000** [comment]
#1813
