### ISSUE TITLE
Why some scoop apps don't use scoop/apps directory?

### ISSUE THREAD

**Issue by quantuumsnot** [ScoopInstaller/Scoop#2701]
For example I installed OpenTTD and it insist using "C:\Users\X79\Documents\OpenTTD" which means consant rewriting of some areas on drive like when autosave is enabled

This happens also on YamagiQ2, another game

**Comment by Ash258** [comment]
You can't force all applications to install / use scoop directory ([vcredist](https://github.com/lukesampson/scoop-extras/blob/master/vcredist.json), [Spotify](https://github.com/Ash258/scoop-Ash258/blob/master/Spotify.json), ...).

They have hardcoded paths inside installer, which cannot be changed. When installation path can be changed, it does not mean application will always use that directory. 

Lots of apps use AppData, Documents, Registry, for storing settings files, configurations, temporary files. Games normally use Users documents for storing save games, so each user have own save game slot, etc, ...

**Comment by quantuumsnot** [comment]
Except some apps installed on OS drive, I managed to symlink writing of almost all others to the storage drive. Just hoped scoop and similar package managers to do that automatically so OS drive is offloaded enough. On SSDs this definitely lowers wear level

**Comment by quantuumsnot** [comment]
In fact they can't - a lot of them tend to start slowing and reporting for errors way before limits of expensive models (weird is that those expensive models also show 4K write speeds around 100-120MB/s against what is advertised ... there are enough tests over the internet proofing that). Most of SSDs sold are TLC (and this 3D advert) which are awful. In practice they are very weak in securing data integrity or restoring compared to SLC SSDs or especially mainstream RAID1 with HDDs. They just die, often with important data which is not possible to be restored.

**Comment by quantuumsnot** [comment]
@rashil2000, so the issue is fixed or not?

**Comment by rashil2000** [comment]
It's not something Scoop can fix, unless the application provides a portable installer and/or a way to specify storage location.
