### ISSUE TITLE
Scoop shall pass  information about proxy to aria2

### ISSUE THREAD

**Issue by netmoleCZ** [ScoopInstaller/Scoop#2738]
Hello there , is there any way how can  scoop pass  default proxy setted by pac file to aria2  ?

**Comment by se35710** [comment]
Don't think aria2 supports it yet. See issue/enhancement [#747](https://github.com/aria2/aria2/issues/747)

**Comment by netmoleCZ** [comment]
ok ty i have question if i am enter manually proxy to scoop can aria2 get it from scoop ?

**Comment by hxse** [comment]
Hope to add `scoop config aria2-proxy` command to set proxy.
