### ISSUE TITLE
latex installed globally has permission issues

### ISSUE THREAD

**Issue by JanPokorny** [ScoopInstaller/Scoop#2791]
When installing latex (MikTeX) globally, the following error is seen when trying to run pdflatex:

![obrazek](https://user-images.githubusercontent.com/4580066/48772150-c2749c00-ecc3-11e8-837d-3a5b3e3560d7.png)

(The localized broken message says "Access denied".)

It seems like a permission issue: https://tex.stackexchange.com/questions/51799/windows-api-error-5-access-is-denied-when-trying-to-compile-tikz-picture

Everything works when latex is installed locally.

**Comment by Ash258** [comment]
You need to run it from elevated shell.

![proof](https://i.imgur.com/uKIen7X.png) I don't have packages, so nothing is produced

**Comment by JanPokorny** [comment]
@Ash258 Is this the expected behavior for MikTeX? IIRC MikTeX installed in a traditional way does not need administrator permissions for downloading packages.

**Comment by Ash258** [comment]
Because downloading packages need to write into it's directory (inside ProgramData), where are only administrators allowed to write.

**Comment by JanPokorny** [comment]
@Ash258 Looks like MikTeX has two modes of installing packages, global and local. (see: https://tex.stackexchange.com/questions/29616/what-is-the-preferable-setup-for-miktex-to-keep-all-packages-up-to-date-easily) At least the local one should not need admin privileges.

Furthermore, the error appears even on an empty file, after a clean reinstall of MikTeX, so it appears even when no packages are to be installed:

![obrazek](https://user-images.githubusercontent.com/4580066/48775830-7bd86f00-ecce-11e8-98e8-52768b35422a.png)

**Comment by Ash258** [comment]
You will always need admin access for all kind of operations since all database files / temporary files are read / writed / created inside miktex data folder inside (ProgramData).

**Comment by JanPokorny** [comment]
@Ash258 Can't this be fixed by manually setting the permissions for this folder (as suggested here https://tex.stackexchange.com/questions/51799/windows-api-error-5-access-is-denied-when-trying-to-compile-tikz-picture), or by configuring MikTeX to use a different folder for data? (Like the non-scoop installation does.)

**Comment by Ash258** [comment]
I don't use miktex implementation so i cannot tell for sure. If it's somehow manageable using file, command or environment value, then yes.

**Comment by JanPokorny** [comment]
I think that at this moment, it should at least warn about this behavior when installing globally.

**Comment by rashil2000** [comment]
Hi, is this still an issue? If it is, I would suggest creating a non-portable manifest (which requires admin) to install the global variant of miktex.
