### ISSUE TITLE
Switch to nirsoft bucket that has all 250 apps?

### ISSUE THREAD

**Issue by rasa** [ScoopInstaller/Scoop#2808]
We currently use https://github.com/kodybrown/scoop-nirsoft for Nirsoft apps, but it only has 19 apps, and they all appear to be manually updated (no checkver/autoupdate).

The bucket at https://github.com/MCOfficer/scoop-nirsoft
has over 250 apps, and most (all?) have checkver/autoupdate sections.

Would it make sense to switch users to this new repo (adding the requisite logic), or just add a new bucket, say `nirsoft-all`?

**Comment by rasa** [comment]
FYI, https://github.com/kodybrown/scoop-nirsoft has 64bit versions. MCOfficier’s does not appear to.

**Comment by MCOfficer** [comment]
after reading this, just a quick info: yes, all apps have checkver/autoupdate. it's not ideal (nirsoft provides the same URL over version updates, so when an app is updated on his server, the hash is off until i update the bucket), but it gets the job done.

**Comment by MCOfficer** [comment]
Can this be reevaluated? the last time kody's scoop bucket got an update to the manifests was in 2015. i doubt that it will become uptodate again anytime soon.

**Comment by MCOfficer** [comment]
I've made the decision to switch pretty much everything to linux - i might still have windows, but not enough to seriously maintain scoop buckets.

Would the ScoopInstaller org or anyone else be willing to pick up the nirsoft bucket? It's very low maintenance, just run autoupdate daily and the update script (to fetch new manifests) once in a blue moon.

**Comment by PrplHaz4** [comment]
@rashil2000 any guidance on a reliable nirsoft bucket?  the current public default has out of date hashes piling up again...
https://github.com/kodybrown/scoop-nirsoft/issues

Maybe Nirsoft is significant enough where it may warrant bringing into the scoop organization for reliable maintenance?

**Comment by rashil2000** [comment]
See #5293
