### ISSUE TITLE
When Scoop will rely on Microsoft ConPTY API?

### ISSUE THREAD

**Issue by Kenya-West** [ScoopInstaller/Scoop#2833]
Microsoft introduced [Windows Pseudo Console (ConPTY)](https://blogs.msdn.microsoft.com/commandline/2018/08/02/windows-command-line-introducing-the-windows-pseudo-console-conpty/) infrastructure and API.

Is this API production-ready or feature-incomplete? Will Scoop implement iteraction with this API only (for safety and stability reasons)?

**Comment by Playacem** [comment]
From the article you posted:

> The new Win32 ConPTY API (formal docs to follow soon) is now available in recent Windows 10 Insider builds and corresponding Windows 10 Insider Preview SDK, and will ship in the next major release of Windows 10 (due sometime in fall/winter 2018).

It appears that the api is not yet available in the release branch of Windows.

**Comment by Rican7** [comment]
> It appears that the api is not yet available in the release branch of Windows.

The APIs are included in Windows 10 v1809 (10.0.17763) release of the Windows 10 SDK, which was released in October 2018.

**Comment by rashil2000** [comment]
Scoop has nothing to do with console APIs
