### ISSUE TITLE
Ability to install pre-release versions from GitHub

### ISSUE THREAD

**Issue by notlmn** [ScoopInstaller/Scoop#2951]
For some apps downloaded from GitHub, scoop lets you install the latest version by using `"github"` field inside the `"checkver"` field of app manifest, but the release that scoop installs is the latest "Stable" release and not the "Pre-release" version.

There should be something like `scoop install app --prerelease` to get the latest pre-release version of the app from GitHub releases, maybe using the GitHub API.

**Comment by notlmn** [comment]
Some example GH apps using pre-releases:
- [clink](https://github.com/mridgers/clink/releases)
- [alacritty](https://github.com/jwilm/alacritty/releases)

**Comment by rasa** [comment]
We have a few “beta” releases in the versions bucket, like 
https://github.com/scoopinstaller/versions/blob/master/bucket/7zip-beta.json

**Comment by notlmn** [comment]
> We have a few “beta” releases in the versions bucket, like
> [scoopinstaller/versions:bucket/7zip-beta.json@`master`](https://github.com/scoopinstaller/versions/blob/master/bucket/7zip-beta.json)

That's kinda neat, but what I would like to propose is for scoop to use a field (like `"channels"`) in the config file, to be able to `scoop install 7-zip --channel beta` (similar to Linux Snaps).

In case of GitHub hosted apps, this would be way easier, as you do not even have to configure it (`--prerelease` should do it, which would map to `beta` channel in config file if that field exists).
