### ISSUE TITLE
Offline installation

### ISSUE THREAD

**Issue by nembonoid** [ScoopInstaller/Scoop#2953]
Hi,
We use a central server Windows 2012 R2 to connect to all the machines we administer. This server, however, doesn't have Internet access. I tried copying manually files and some commands work, less for example, but there are several commands giving me "the program can't start because msys-1.0dll is missing from your computer.
![vmware_2019-01-05_19-33-55](https://user-images.githubusercontent.com/46407959/50729913-03642b00-1121-11e9-9632-4fa64f5877dd.png)
 
### Is there an offline installer that includes all commands? I would very appreciate it

**Comment by Ash258** [comment]
Have you run `scoop reset *` after you copied scoop installation?

**Comment by nembonoid** [comment]
Hi,

scoop reset * did nothing for me but I was able to install scoop setting a proxy that gets me internet. The dll missing is another issue not related to scoop I suppose. I installed MinGW to solve this issue but I think  i need to reboot the server.

**Comment by Guria** [comment]
I'd like to be able to extract some software installed with scoop as portable self-installable package to transfer on offline machine.

**Comment by fsdrw08** [comment]
I also hope that there is offline installation method for scoop

**Comment by magnus-longva-bouvet** [comment]
I would also appreciate an offline installation alternative. I've gotten the occasional "504 gateway time-out" error upon installing. For an automated pipeline, it poses problems

**Comment by stephenpatten** [comment]
@Ash258 Are you saying there is a way to configure installing an artifact if you have the correct config and dependencies?

Thank you,
Stephen

**Comment by rashil2000** [comment]
#3505

**Comment by i2** [comment]
I concur that it would be nice for Scoop to have true offline install feature, not the copy cache folder work-around. I know chocolatey has this feature. Is it possible to add this feature?

**Comment by rashil2000** [comment]
Are you asking for offline installation of Scoop itself, or the packages?

For Scoop itself, some methods can be explored.

For packages, copying the cache folder is the only way.

**Comment by i2** [comment]
I was implying offline installation of packages using scoop (like it's possible with alternatives). Thanks!

**Comment by denivic** [comment]
Any news on this? Is this possible now or?

**Comment by rashil2000** [comment]
> For packages, copying the cache folder is the only way.

**Comment by shodanx2** [comment]
After investigating further

```
 [bool]$downloadZipsRequired = $True
  if (Test-CommandAvailable('git')) {
      ... download with git, if fail set downloadZipsRequired to true ...
}

  if ($downloadZipsRequired) {
     ... download .zip directly ... (crashes if it can't)
}
```


So I think that 

`  if ($downloadZipsRequired) {`

should be short circuited  if the files scoop.zip and scoop-main.zip already exist

by changing


`if ($downloadZipsRequired) {`

with

`if ($downloadZipsRequired -and !((Test-Path "$SCOOP_APP_DIR\scoop.zip") -and (Test-Path "$SCOOP_MAIN_BUCKET_DIR\scoop-main.zip"))) {`


Which can be performed with this powershell -command "" oneliner

`powershell -Command "(Get-Content 'scoop-install.ps1') | ForEach-Object { if ($_ -match '^\s*if\s*\(\$downloadZipsRequired\)\s*\{') { 'if ($downloadZipsRequired -and !((Test-Path \"$SCOOP_APP_DIR\scoop.zip\") -and (Test-Path \"$SCOOP_MAIN_BUCKET_DIR\scoop-main.zip\"))) {' } else { $_ } } | Set-Content 'scoop-install.ps1'"`

I have corrected the script

offline-install-scoop.bat

```
@echo off

:: Define paths
set "SCOOPDIR=%USERPROFILE%\scoop"
set "SCOOP_APP_CURRENT=%SCOOPDIR%\apps\scoop\current"
set "SCOOP_BUCKET_MAIN=%SCOOPDIR%\buckets\main"

:: Create directories explicitly (one level at a time)
md "%SCOOPDIR%"
md "%SCOOPDIR%\apps"
md "%SCOOPDIR%\apps\scoop"
md "%SCOOPDIR%\apps\scoop\current"
md "%SCOOPDIR%\buckets"
md "%SCOOPDIR%\buckets\main"

:: Copy newest scoop.*.zip to scoop.zip
for /f "delims=" %%f in ('dir /b /a:-d /o:-d scoop.*.zip') do (
    copy /Y "%%f" "%SCOOP_APP_CURRENT%\scoop.zip" >nul
    goto :scoop_copy_break
)
:scoop_copy_break

:: Copy newest scoop-main.*.zip to scoop-main.zip
for /f "delims=" %%f in ('dir /b /a:-d /o:-d scoop-main.*.zip') do (
    copy /Y "%%f" "%SCOOP_BUCKET_MAIN%\scoop-main.zip" >nul
    goto :main_copy_break
)
:main_copy_break

powershell -Command "(Get-Content 'scoop-install.ps1') | ForEach-Object { if ($_ -match '^\s*if\s*\(\$downloadZipsRequired\)\s*\{') { 'if ($downloadZipsRequired -and !((Test-Path \"$SCOOP_APP_DIR\scoop.zip\") -and (Test-Path \"$SCOOP_MAIN_BUCKET_DIR\scoop-main.zip\"))) {' } else { $_ } } | Set-Content 'scoop-install.ps1'"

:: Run the installer script
powershell -ExecutionPolicy Bypass -NoProfile -File scoop-install.ps1

pause

```

However this results in another error

<img width="1922" height="1119" alt="Image" src="https://github.com/user-attachments/assets/741aa415-f3f7-4988-a804-b9abee946b41" />

This is because the extraction of the zip file is being skipped as well this time !

**Comment by shodanx2** [comment]
Here are the download and install batch files described above

Placed in a zip as github does not allow uploading of .bat files

[scoop-offline-installer.zip](https://github.com/user-attachments/files/21457865/scoop-offline-installer.zip)

Next steps 

A script that copies your cache to the local folder

A script that copies the cache in your local folder to you %USERPROFILE%\scoop cache folder on the offline computer

A script to prepare updating scoop itself

A script to prepare updating main or a named repository 

A script to update scoop on the offline computer

A script to update main or a named repository on the offline computer
