### ISSUE TITLE
Current state of installing specific versions?

### ISSUE THREAD

**Issue by janpio** [ScoopInstaller/Scoop#3045]
I am just getting started with using scoop and I think I am in love ❤️ 

One thing that I found missing was a way to install specific versions of programs.

There is a documented "workaround" with another bucket that works for ruby and python: https://github.com/lukesampson/scoop/wiki/Switching-Ruby-and-Python-Versions But this is also only for major versions and only works for these two special cases.

Then I found https://github.com/lukesampson/scoop/pull/1332 which seems to implement parts of what I was looking for - but closes with "Lets leave this as a bit of a hidden feature for a while. I'll write some docs for it soon enough" (in 2017). 
There are other issues that mention this syntax, its possible problems and its  missing documentation: https://github.com/lukesampson/scoop/issues/2254 ScoopInstaller/Scoop#1780 And here even is an open issue to document this behavior: ScoopInstaller/Scoop#2141

- Did I mess up and miss the excellent documentation on this feature?
- Is the `<program>@<version>` syntax considered stable and usable now?
- Are PRs and wiki edits welcome to document the current behavior?
- Is there a way to get older version numbers via `scoop`?

**Comment by janpio** [comment]
Another problem seems to be when the current manifest config does not match the path of older download URLs as it was recently changed: https://github.com/lukesampson/scoop/commit/91d9723b08e86a2db4f94e6164b7fa598f42d49c

```
PS C:\Users\Jan> scoop install ruby@2.5.3-1
WARN  Given version (2.5.3-1) does not match manifest (2.6.0-1)
WARN  Attempting to generate manifest for 'ruby' (2.5.3-1)
Autoupdating ruby
Downloading rubyinstaller-2.5.3-1-x86.7z to compute hashes!
The request was aborted: The connection was closed unexpectedly.
URL https://github.com/oneclick/rubyinstaller2/releases/download/RubyInstaller-2.5.3-1/rubyinstaller-2.5.3-1-x86.7z is not valid
Could not find hash!
Could not install ruby@2.5.3-1
```

New generated path is https://github.com/oneclick/rubyinstaller2/releases/download/RubyInstaller-2.5.3-1/rubyinstaller-2.5.3-1-x86.7z, correct one would have been https://github.com/oneclick/rubyinstaller2/releases/download/rubyinstaller-2.5.3-1/rubyinstaller-2.5.3-1-x86.7z

**Comment by r15ch13** [comment]
There is also another issue. Every manifest that uses custom capture groups will not work. (Like `$matchVersion`, `$matchHead`, $matchMyAwesomeCaptureGroup`)
See [aria2.json](https://github.com/lukesampson/scoop/blob/master/bucket/aria2.json) or [brotli.json](https://github.com/lukesampson/scoop/blob/master/bucket/brotli.json)

**Comment by 573** [comment]
With chrome getting:

>current $ scoop install chrome@73.0.3683.68
WARN  Given version (73.0.3683.68) does not match manifest (74.0.3729.131)
WARN  Attempting to generate manifest for 'chrome' (73.0.3683.68)
Autoupdating chrome
DEBUG[1557912977] $substitutions (hashtable) -> C:\Users\me\scoop\apps\scoop\current\lib\autoupdate.ps1:149:5
DEBUG[1557912977] $substitutions.$buildVersion                  68
DEBUG[1557912977] $substitutions.$baseurl                       https://redirector.gvt1.com/edgedl/release2/chrome/$match32_73.0.3683.68
DEBUG[1557912977] $substitutions.$dashVersion                   73-0-3683-68
DEBUG[1557912977] $substitutions.$url                           https://redirector.gvt1.com/edgedl/release2/chrome/$match32_73.0.3683.68/73.0.3683.68_ch…
DEBUG[1557912977] $substitutions.$matchHead                     73.0.3683
DEBUG[1557912977] $substitutions.$preReleaseVersion             73.0.3683.68
DEBUG[1557912977] $substitutions.$majorVersion                  73
DEBUG[1557912977] $substitutions.$basename                      73.0.3683.68_chrome_installer.exe
DEBUG[1557912977] $substitutions.$patchVersion                  3683
DEBUG[1557912977] $substitutions.$cleanVersion                  730368368
DEBUG[1557912977] $substitutions.$minorVersion                  0
DEBUG[1557912977] $substitutions.$version                       73.0.3683.68
DEBUG[1557912977] $substitutions.$underscoreVersion             73_0_3683_68
DEBUG[1557912977] $substitutions.$matchTail                     .68
DEBUG[1557912977] $hashfile_url = $null -> C:\Users\me\scoop\apps\scoop\current\lib\autoupdate.ps1:152:5
Downloading 73.0.3683.68_chrome_installer.exe to compute hashes!
The remote server returned an error: (404) Not Found.
URL https://redirector.gvt1.com/edgedl/release2/chrome/$match32_73.0.3683.68/73.0.3683.68_chrome_installer.exe#/cosi.7z is not valid
Could not find hash!
Could not install chrome@73.0.3683.68

**Comment by 573** [comment]
@janpio, it seems just like the checksum ($match32 part) is missing there as well as @r15ch13 pointed out already. Does it make sense as a workaround to factor these out from the manifest? Must confess I am a noobie here.

**Comment by 573** [comment]
I have a workaround described [here](https://gist.github.com/573/e806447bf55a09376cf457a8a403ec44) until the match-issue is sorted out.
Applies to chrome only.

**Comment by rashil2000** [comment]
Tracked in #2702

**Comment by ClassicDarkChocolate** [comment]
Current:
```pwsh
> scoop install opentrack@2022.1.1
```
```pwsh
WARN  Given version (2022.1.1) does not match manifest (2022.2.0)
WARN  Attempting to generate manifest for 'opentrack' (2022.1.1)
Autoupdating opentrack
Downloading opentrack-2022.1.1-portable.7z to compute hashes!
The remote server returned an error: (404) Not Found.
URL https://github.com/opentrack/opentrack/releases/download/opentrack-2022.1.1/opentrack-2022.1.1-portable.7z is not valid
Could not install opentrack@2022.1.1
Select-CurrentVersion: C:\Users\Zack\scoop\apps\scoop\current\lib\core.ps1:228
Line |
 228 |      return $null -ne (Select-CurrentVersion -AppName $app -Global:$gl …
     |                                                       ~~~~
     | Cannot bind argument to parameter 'AppName' because it is an empty string.

WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
WARN  To disable this warning, run 'scoop config aria2-warning-enabled false'.
Couldn't find manifest for ''.
```
My workround:
```pwsh
function Get-ScoopPackageVersions {
    param (
        [Parameter(Position = 1, Mandatory = $true)]
        $Name
    )
    
    $info = $(scoop info $Name)
    if (-not $?) {
        exit 1
    }

    $bucket = $info.Bucket
    Push-Location -Path "$env:SCOOP\buckets\$bucket\bucket"

    $rawLogs = $(git grep '\"version\": \?\"' $(git rev-list --all -- "$Name.json") -- "$Name.json")
    $logs = $rawLogs | ForEach-Object {
        ($_ -match '^(?<hash>[\w\d]+):.+?\"version\": ?\"(?<version>.+?)\"') | Out-Null
        [PSCustomObject]@{
            Hash    = $Matches.hash
            Version = $Matches.version
        }
    }

    Pop-Location
    $logs
}
function Install-ScoopPackage {
    param (
        [Parameter(Position = 1, Mandatory = $true)]
        $Name,
        $Version,
        $Commit
    )
    
    $exitCode = 0
    $info = $(scoop info $Name)
    if (-not $?) {
        exit 1
    }

    $bucket = $info.Bucket
    Push-Location -Path "$env:SCOOP\buckets\$bucket\bucket"

    if ($null -ne $Version) {
        $commits = Get-ScoopPackageVersions -Name $Name
        $commit = $commits | Where-Object Version -EQ $Version
        if ($null -ne $commit) {
            git restore --source=$($commit.Hash) "$Name.json"
            if ($?) {
                scoop install "$Name"
            }
        }
        else {
            Write-Error "Could not find manifest for $Name@$Version"
        }
    }
    else {
        git restore --source=$($Commit.Hash) "$Name.json"
        if ($?) {
            scoop install "$Name"
        }
    }

    git restore "$Name.json"

    Pop-Location
    exit $exitCode
}
Install-ScoopPackage -Name opentrack -Version "2022.1.1"
```
```pwsh
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
WARN  To disable this warning, run 'scoop config aria2-warning-enabled false'.
Installing 'opentrack' (2022.1.1) [64bit]
Loading opentrack-2022.1.1-win32-portable.7z from cache.
Checking hash of opentrack-2022.1.1-win32-portable.7z ... ok.
Extracting opentrack-2022.1.1-win32-portable.7z ... done.
Linking ~\scoop\apps\opentrack\current => ~\scoop\apps\opentrack\2022.1.1
Creating shim for 'opentrack'.
Creating shortcut for Opentrack (opentrack.exe)
Persisting ini
Running post-install script...
INFO  [Portable Mode] Adding Portable Mode File...
'opentrack' (2022.1.1) was installed successfully!
```

**Comment by josephnarai** [comment]
I'm having this issue. I'm creating my own apps for an embedded windows application and want to use scoop to manage our OTA updates. I'm hosting my own bucket on github, and have the installer zips on giuhub pages.

The issue I'm having is if I want a particular device to stay on a specific version, or say roll back from an update, I can't seem to get it to work as expected. Latest version of DeviceProxy is 1.7.4.2.

scoop install DeviceProxy@1.7.4.1 results in 

```
WARN  Given version (1.7.4.1) does not match manifest (1.7.4.2)
WARN  Attempting to generate manifest for 'DeviceProxy' (1.7.4.1)
Autoupdating DeviceProxy
Get-Member : You must specify an object for the Get-Member cmdlet.
At C:\Users\j_nar\scoop\apps\scoop\current\lib\autoupdate.ps1:335 char:46
+ ...  $Manifest.architecture | Get-Member -MemberType NoteProperty | ForEa ...
+                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-Member], InvalidOperationException
    + FullyQualifiedErrorId : NoObjectInGetMember,Microsoft.PowerShell.Commands.GetMemberCommand

Writing updated DeviceProxy manifest
WARN  Purging previous failed installation of DeviceProxy.
ERROR 'DeviceProxy' isn't installed correctly.
Removing older version (1.7.4.1).
'DeviceProxy' was uninstalled.
Installing 'DeviceProxy' (1.7.4.1) [64bit]
The remote server returned an error: (404) Not Found.
URL https://design2production.github.io/scoop-dev/DeviceProxy_1.7.4.1.zip is not valid
```

I'm confused how scoop can know about previous versions, and the DeviceProxy.json only contains a reference to the latest version...

I'm clearly missing something fundamental... hoping someone can help me work it out!

**Comment by rashil2000** [comment]
> There is also another issue. Every manifest that uses custom capture groups will not work. (Like `$matchVersion`, `$matchHead`, $matchMyAwesomeCaptureGroup`) See [aria2.json](https://github.com/lukesampson/scoop/blob/master/bucket/aria2.json) or [brotli.json](https://github.com/lukesampson/scoop/blob/master/bucket/brotli.json)

I don't think there's a meaningful way to solve this problem. The captured variables are populated from the checkver.url, and that URL, at any given time, will only have the latest 'values'. 

Using git history is a good workaround to this - https://github.com/ScoopInstaller/Scoop/issues/3894
