### ISSUE TITLE
scoop.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program.

### ISSUE THREAD

**Issue by kn9** [ScoopInstaller/Scoop#3050]
Hi Guys, Please how can I resolve this error. Thanks

~ $ scoop update
& : The term 'C:\Users\adm\scoop\shims\..\apps\scoop\current\bin\scoop.ps1' is
not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify
that the path is correct and try again.
At C:\Users\adm\scoop\shims\scoop.ps1:3 char:71
+ ... on.expectingInput) { $input | & $path  @args } else { & $path  @args  ...
+                                                             ~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\adm\sc...t\bin\scoop.p
   s1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

~ $ scoop help
& : The term 'C:\Users\adm\scoop\shims\..\apps\scoop\current\bin\scoop.ps1' is
not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify
that the path is correct and try again.
At C:\Users\adm\scoop\shims\scoop.ps1:3 char:71
+ ... on.expectingInput) { $input | & $path  @args } else { & $path  @args  ...
+                                                             ~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\adm\sc...t\bin\scoop.p
   s1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by Ash258** [comment]
`C:\Users\adm\scoop\shims..\apps\scoop\current\bin\scoop.ps1` That path is incorrectly joined. When this error occured? Have you change anything, installed fresh scoop, ..?

**Comment by crazy4groovy** [comment]
I also have this problem.
I tried installing `wuzz` which gave me this error:
```
C:\Users\solsen> scoop install wuzz
Updating Scoop...
Remove-Item : Cannot remove item
C:\Users\solsen\scoop\apps\scoop\current\supporting\validator\bin\Newtonsoft.Json.dll: Access to the path
'Newtonsoft.Json.dll' is denied.
At C:\Users\solsen\scoop\apps\scoop\current\libexec\scoop-update.ps1:76 char:9
+         Remove-Item -r -force $currentdir -ea stop
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (Newtonsoft.Json.dll:FileInfo) [Remove-Item], UnauthorizedAccessExcept
   ion
    + FullyQualifiedErrorId : RemoveFileSystemItemUnAuthorizedAccess,Microsoft.PowerShell.Commands.RemoveItemCommand
```

Now I keep getting:
```
C:\Users\solsen> scoop update
& : The term 'C:\Users\solsen\scoop\shims\..\apps\scoop\current\bin\scoop.ps1' is not recognized as the name of a
cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify
that the path is correct and try again.
At C:\Users\solsen\scoop\shims\scoop.ps1:3 char:71
+ if($myinvocation.expectingInput) { $input | & $path  @args } else { & $path  @ar ...
+                                                                       ~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\solsen...t\bin\scoop.ps1:String) [], ParentContainsErrorRecord
   Exception
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by crazy4groovy** [comment]
In my `C:\Users\solsen\scoop\apps\scoop` I have a `current` folder and a `new` folder. Is that right, or did the updater break my scoop?

**Comment by mvalho** [comment]
In my case I had just the "new" folder. So, what I did was copy the "new" folder and rename the copy to "current" everything worked after this.

**Comment by ivanstepanovftw** [comment]
I have only current folder and nothing inside of it

```powershell
PS C:\Users\ashft> dir C:\Users\user\scoop\apps\scoop\


    Directory: C:\Users\user\scoop\apps\scoop


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        9/13/2019   3:16 PM                current

PS C:\Users\ashft> dir C:\Users\user\scoop\apps\scoop\current\
PS C:\Users\ashft>
```

**Comment by ivanstepanovftw** [comment]
OK, I have removed `C:\Users\user\scoop\apps\scoop\` and able to reinstall with `iex (new-object net.webclient).downloadstring('https://get.scoop.sh')`

**Comment by audricchabert** [comment]
> 
> 
> OK, I have removed `C:\Users\user\scoop\apps\scoop\` and able to reinstall with `iex (new-object net.webclient).downloadstring('https://get.scoop.sh')`

It worked for me

BTW I also did what was advised on the scoop website if we have errors : 
https://scoop.sh/
type this in powershell before the install

Set-ExecutionPolicy RemoteSigned -scope CurrentUser
maybe it helps, maybe not

**Comment by sahilkapoorcloudsufi** [comment]
Just run this command- iwr -useb get.scoop.sh | iex. I hope it will work.

**Comment by soleil0-0** [comment]
go to "%USERPROFILE%\scoop\apps\scoop\current", and check it's empty or not.

At least, it should contain ".git" folder.

You can run "git pull" to get all content

**Comment by lvm-5** [comment]
I've met the same issue after running scoop update without any apps installed.  
To fix the error I've renamed "%USERPROFILE%\scoop\apps\scoop\new" back to "current".
After I've installed 1 package at least and then run update again.
This time it was good, there are no any issues.

**Comment by RavenMacDaddy** [comment]
I'll post this in the current topics regarding the issue.

---

For me personally a number of things:

- The 'new' dir is created but it's empty and Scoop still deletes it and the corresponding bin files etc. in its 'current' dir, making it broken.
- There are no permission issues, both regarding what's reported and also confirmed in the properties. When updating Scoop it just halts for a bit and then says "hey, I can't find my files" (it specifically references 'scoop.ps1') on a single line.
- This happens whether or not I'm using forks of the project and regardless of where environment variables are pointing Scoop (where it's installed); could be in its default Users folder dir or somewhere else, doesn't matter, the issue still occurs
- I can reinstall Scoop in the apps folder with the command that was mentioned previously; `iex (new-object net.webclient).downloadstring('https://get.scoop.sh')` - but this only resets the issue, cause Scoop will still try and update when I tell it to and the same issue is repeated
- Doesn't matter if I reinstall Scoop completely any number of times, which I did to try and solve the problem. I tried different combinations mentioned here; installing apps first, looking for .git dir, nothing so far helps.
- The only thing that I managed to do after several tries was to restore my previous installation of Scoop from a backup and eventually after a number of tries and orders of installing apps like 'git' it would behave.

**Comment by jdgregson** [comment]
> OK, I have removed `C:\Users\user\scoop\apps\scoop\` and able to reinstall with `iex (new-object net.webclient).downloadstring('https://get.scoop.sh')`

I tried this, but was getting the following error even after removing the `apps\scoop` folder:

    Scoop is already installed. Run 'scoop update' to get the latest version.

I resolved it by downloading the Scoop installer:

    iwr 'https://get.scoop.sh' -outfile install.ps1

Editing it and commenting out the part that checks if Scoop is already installed:

    # Test if scoop is installed, by checking if scoop command exists.
    #if ([bool](Get-Command -Name 'scoop' -ErrorAction SilentlyContinue)) {
    #    Deny-Install "Scoop is already installed. Run 'scoop update' to get the latest version."
    #}

And then invoking the modified installer:

    ./install.ps1

Scoop worked fine again after this.

**Comment by niheaven** [comment]
Now the new installer checks for `scoop` command, if you met the error, you could check `scoop which scoop` and see if there is an output.

**Comment by qrqhuang** [comment]
This must be PWSH running in Constrained Language mode.
after i change ps policy `__PSLockdownPolicy 4 -> 8`,  it works.

![Image](https://github.com/user-attachments/assets/b236b057-b8f6-496e-a7f7-b66fa58e8cfb)


but i have no idea why this env var has been modified in my office computer.
