### ISSUE TITLE
Consider supporting Windows 10 on ARM?

### ISSUE THREAD

**Issue by KexyBiscuit** [ScoopInstaller/Scoop#3146]
[Windows 10 on ARM](https://docs.microsoft.com/en-us/windows/arm/) has been released for over a year, and a few apps have already released their ARM native versions, such as PowerShell/PowerShell#5664 and dotnet/announcements#29.

**Comment by KexyBiscuit** [comment]
Related: PowerShell/PowerShell/issues/8047

**Comment by soapdog** [comment]
bump! at the moment there is no way to use scoop to install arm64 apps.

**Comment by CEbbinghaus** [comment]
This is something i am super keen to see implemented

**Comment by rashil2000** [comment]
The lack of ARM Windows devices with most people is the main blocker for this... If you have an ARM device, consider making a PR!

**Comment by AntonOks** [comment]
**A LOT** of Windows-on-ARM tools are released in the last months as MS visual studio supports it also out of the box by now... some of the same tools stopped to ship 32bit versions, which was the "fall-back" for us Windows-ARM users...

Other package managers are starting to support the Windows-ARM arch... for me it feels like SCOOP is falling behind (soon) :|

It would be great if someone with the needed know-how could enhance SCOOP to support ARM soon..

**Comment by AntonOks** [comment]
> The lack of ARM Windows devices with most people is the main blocker for this... If you have an ARM device, consider making a PR!

I'm a proud owner of such a device. I'd be happy the test things and give feedback. Pls let me know how / what to test...

**Comment by sirredbeard** [comment]
What is needed for Scoop to support ARM64? It seems like there is already support for 32-bit and 64-bit x86 apps, would adding a third arch be that complicated?

**Comment by rasa** [comment]
I don't think any of our core devs have a ARM system, so if you have an ARM device, please consider submitting a PR!

**Comment by sirredbeard** [comment]
What if I could help some of the core devs get access to a Windows on ARM system, @rasa?

**Comment by rashil2000** [comment]
That would be pretty awesome, @sirredbeard! Not only would it help Scoop core manager, it would also accelerate the adoption of Arm builds into around 3000 package manifests across the ScoopInstaller org.

**Comment by rasa** [comment]
@sirredbeard That **would** be awesome. @ScoopInstaller/maintainers : Would anyone be willing to spearhead this effort? I can assist, but don't have the bandwidth to take point.

**Comment by niheaven** [comment]
I could help if the connection to VM is stable enough for me...

**Comment by rashil2000** [comment]
I'd be willing to help too!

**Comment by sirredbeard** [comment]
@niheaven @rashil2000 Check your e-mails.

**Comment by rashil2000** [comment]
Thank you, received!

**Comment by niheaven** [comment]
Got it, thanks!

**Comment by rashil2000** [comment]
PR is up. Some minor things are left, but it should be usable. Please test and let me know!
