### ISSUE TITLE
[Proposal] Homebrew style scoop-list output option

### ISSUE THREAD

**Issue by chawyehsu** [ScoopInstaller/Scoop#3162]
![capture](https://user-images.githubusercontent.com/5764917/53260649-f7521e00-370c-11e9-908a-fff98b2f834f.PNG)

What is your feeling about this?

**Comment by r15ch13** [comment]
Looks nicer, but contains less information.

**Comment by h404bi** [comment]
@r15ch13 It's neater, and faster from sense if you have installed so many apps. Making this to be an option would be good.

**Comment by h404bi** [comment]
If anyone wants to use this style of `scoop list` output, you can try my implementation here:
https://gist.github.com/h404bi/5c0d5a56486a985638a7cae15973d166
