### ISSUE TITLE
`git` contains gpg executables, but they aren't added to path.

### ISSUE THREAD

**Issue by qm3ster** [ScoopInstaller/Scoop#3167]
Does this mean they shouldn't be used?
What is the recommended approach?
### Installing the standalone one
```powershell
scoop install gpg
git config --global commit.gpgsign true
git config --global gpg.program (resolve-path (scoop which gpg))
```
### Or adding my keys to the bundled one?
```powershell
Set-Alias gpg (join-path (scoop prefix git) 'usr\bin\gpg.exe')
gpg --import KEY\LOCATION"
```

I understand the `git` `git-with-openssh` `win32-openssh` situation is in flux, but what about the gpg side of things?

**Comment by shytikov** [comment]
Same goes for `vim`. I don't see a reason why I should install vim, if I do have already it installed as part of `git`.

**Comment by rasa** [comment]
See https://github.com/lukesampson/scoop/pull/2431 for one proposed solution, that could work for gpg as well.

**Comment by qm3ster** [comment]
@rasa I don't see how that's a good solution.
We should just point all packages as metapackages to the same bundle because no one hosts the binaries separately?
