### ISSUE TITLE
Scoop needs a way to identify apps with installers and/or persistent data

### ISSUE THREAD

**Issue by claudenobs** [ScoopInstaller/Scoop#3176]
I have noticed a few inconsistencies using scoop:

- globally installing a portable version of an app that stores user-data in the registry (like 7zip) has zero advantage. => scoop might as well use the installer version, which integrates better with windows
- globally installing a portable version of an app that has it's user-data in the app folder (handled by the persist key in the app manifest, like notepadplusplus) might be dangerous (shared user data!)
- locally installing an app that uses an installer (like python) makes no sense (because it's installed globally but the installation might only be available to a single user (if scoop/userprofile is on a network share)

at the very least, in the above cases. scoop should print a warning when installing apps.

**Comment by rashil2000** [comment]
These cases should be handled in the individual manifests itself.
