### ISSUE TITLE
Option to skip a failed app while installing multiple apps

### ISSUE THREAD

**Issue by sameerhr84** [ScoopInstaller/Scoop#3215]
While installing scoop with n number of apps at time we faces issue with a particular app(like mirror issues or corrupted downloadable) and not able to proceed further. Is there a possibility to install but skip a particular app without commenting out them from json.

**Comment by 0x326** [comment]
Probably could be tackled along with https://github.com/lukesampson/scoop/issues/3307#issuecomment-480578890

**Comment by rashil2000** [comment]
#4135
