### ISSUE TITLE
Is concurrent use of Cygwin compatible with Scoop?

### ISSUE THREAD

**Issue by E3V3A** [ScoopInstaller/Scoop#3279]
I'm using cygwin for everything, except installing native Windows apps and dev tools. Now I would like to use Scoop but since it seem that Scoop are using many similarly named tools, I am concerned that it might interfere with Cygwin. 

* How are PATHs handled in concurrent Cygwin + Scoop instalaltions?
* How is the **`~`** bashism handled in Scoop when running in a Cygwin mintty? (Where a `~` would be short for `$HOME` and not the Windows User home.)
* Anyone has experience in this?

**Comment by E3V3A** [comment]
I guess nobody cares about compatibility issues here... :-1:

**Comment by Ash258** [comment]
I guess it is only becaue there are few people who use cygwin. I personally try to ditch cygwin always, so I cannot help you. You can always test on your own inside some VM / docker environment and report.

**Comment by E3V3A** [comment]
Well Cygwin has worked more or less flawlessly for the last 10 years for me. However, more and more development is done with "native" msys2 and VC based toolchains, and unfortunately redhat and Cygwin maintainer don't give a shit about keeping their packages updated. So I'm ditching it too when the time is ready, which is why I am asking *here*, because if scoop works as great as everyone claims, then I may no longer need to compile on cygwin. 

That said, the **apt-cyg** (by kou1okada)  package manger for Cygwin works really great. The problem is always the packages from the official Cygwin repos, because Cygwin wankers doesn't want to make it easy to update packages nor to create new ones, leaving most users to try to compile from sources. Which usually works quite all-right, but is a PITA to have to deal with, when there are multiple dependencies. In particular for Windows GUI apps.

**Comment by rashil2000** [comment]
The bash scripts created by Scoop assume an MSYS2 environment. Cygwin is not supported.
