### ISSUE TITLE
XDG Base Directories

### ISSUE THREAD

**Issue by Deide** [ScoopInstaller/Scoop#3285]
I've noticed that in #3242, `XDG_CONFIG_HOME` is preferred as scoop's config directory and persistence is being reworked in #3212.

I was wondering if applying more of the XDG specification to scoop might not be a good idea with regards to `persist` while it's being worked on.

It could be useful to have the ability to link to both `XDG_CONFIG_HOME` and `XDG_DATA_HOME` from manifests. That way, apps can differentiate between persistent configurations and persistent application data.

The new persist object schema could just specify `data` or `config`:

```json
  "persist": {
    "config": [
      {
        "type": "file",
        "name": "config.dat",
        "content": "[Config]`nlanguage=eng",
        "encoding": "UTF-8",
        "method": "copy"
      }
    ],
    "data": [
      {
        "type": "directory",
        "name": "data",
        "method": "link"
      },
      {
        "type": "directory",
        "name": "plugins",
        "method": "merge"
      }
    ]
  }
```

And while at it, `XDG_CACHE_HOME` could be used for the cache.

**Comment by niheaven** [comment]
`XDG_DATA_HOME` is not under scoop's control, so scoop cannot 'persist' it, so as `XDG_CACHE_HOME`. scoop just use `XDG_CONFIG_HOME` to store its own config.

**Comment by Deide** [comment]
Right now, applications installed with scoop keep their persistent configs and data in `$SCOOP/persist/$appname`, where `$SCOOP` is the directory scoop was installed in. And then symlinks are made inside `$SCOOP/apps/$appname`, pointing to files/folders from the persist path. Other than no longer being in the $SCOOP directory, it's not that different if you make the persist path `$XDA_CONFIG_HOME/$appname`.

**Comment by niheaven** [comment]
Then where will be the `XDG_XXX_HOME` if user install scoop under a custom dir instead of `$USERPROFILES`? User who installed scoop in some location, e.g. `D:`, wants to keep persistence out of system, but `XDG_XXX_HOME` shouldn't be changed by scoop, and that broken persistence.

**Comment by Deide** [comment]
XDG directories wouldn't be changed by Scoop. Scoop would only add application folders to the XDG directories *if* they're set in the first place - just like scoop is doing for its own config. Users themselves would set the XDG environment variables.

I have scoop installed in `I:\applications\`, and I could set `XDG_CONFIG_HOME` to `I:\.config\`. If I don't have that environment variable, scoop can just use `I:\applications\persist` as it does now.

The only downside is that if you should ever choose to change or remove the XDG directories, all the symlinks for apps would need to be updated since they can't use environment variables. Though I don't see why you would, personally.
