### ISSUE TITLE
Adding shims to an installation

### ISSUE THREAD

**Issue by garytyler** [ScoopInstaller/Scoop#3303]
Does the scoop cli include a command for adding shims to an installation? Or creating custom shims? I would like to add version appendages to my python installations. For example: `python2` -> `python27`, `python2.7`. Is there a recommended way to go about it?

Sorry if this has been asked before! I looked and couldn't find anything.

**Comment by r15ch13** [comment]
If you installed python from [main/python](https://github.com/lukesampson/scoop/blob/master/bucket/python.json) and [versions/python27](https://github.com/scoopinstaller/versions/blob/master/bucket/python27.json) then `python3` and `python2` shims should already exist.

**Comment by garytyler** [comment]
@r15ch13 Both `python3` and `python2` do exist, so I'm hoping to add the other variations, most particularly `python2.7` and `python3.7, to reflect a typical python CI environment expected by the test automation software `tox`. I usually copy the existing shims, but was just wondering if there is another solution. I know there is the version switcher functionality, and adding the shims might be more involved than just entering them into the manifests, but would you consider a PR for that? If the intention here is to just keep things simple, that's completely understandable. Thanks for the reply, and for this great tool!
