### ISSUE TITLE
[Feature Request] Package statistics

### ISSUE THREAD

**Issue by kiedtl** [ScoopInstaller/Scoop#3311]
Can we implement a statistics feature like [Homebrew analytics](https://formulae.brew.sh/analytics/)? 

There need not be any web interface, there could be a dedicated command for it (e.g. `scoop stats <app>`). It would serve to show package creators how their packages are doing, and if there ever came a time where we would have to curate packages, the statistics could show us the least downloaded packages.

Of course, this would require someone to setup a dedicated server somewhere.

**Comment by Calinou** [comment]
I'm not sure if this can be done currently, considering Scoop uses manifests from locally-cloned Git repositories (buckets) or direct URLs which aren't under Scoop's control. Files are also usually downloaded directly from upstream.

Moreover, I don't think package statistics are very useful to a group of volunteers who work on what they want to work on.

**Comment by rashil2000** [comment]
Closing in favor of #3781
