### ISSUE TITLE
PHP Conf Issues with multiple installed versions

### ISSUE THREAD

**Issue by DonSYS91** [ScoopInstaller/Scoop#3426]
Hello,
Sadly PHP manages this the hard way when you install PHP on windows, it comes precompiled with the flag option " --with-config-file-path" set to windows directory and the flag option "--with-config-file-scan-dir" set to nothing but rather managed by the Environment Variable "PHP_INI_SCAN_DIR", you can check with:
`php --ini`
![image](https://user-images.githubusercontent.com/18079656/57016829-82272b80-6c1c-11e9-87a7-adfa8b28b156.png)

Now the "PHP_INI_SCAN_DIR" env won't help at all and will result in many problems when running multiple PHP versions as we can't specify which version, PHP has a solution to multiple versions with setting paths to .ini file in the registry, sadly that just work for .ini but not additional dir scan.
I attempted to recompile PHP and set the flags like the following:
--with-config-file-path=C:\Users\<username>\scoop\persist\php71\cli
--with-config-file-scan-dir=C:\Users\<username>\scoop\persist\php71\cli\conf.d

This would be the cleanest way to do it in my opinion and that's how Sury compiles for Debian 
https://packages.sury.org/php/
![image](https://user-images.githubusercontent.com/18079656/57017387-4cd00d00-6c1f-11e9-8670-48c12db7f049.png)

But again the biggest problem with that, that I can't assume the username or pass any variable when compiling, or else i thought of configuring a pipeline to test, compile and build on every newly released version of PHP.
So honestly, I'm left with no clean way to scan multiple dir for multiple versions on windows.

Do you have any thoughts or idea on that, If we can solve it, I will be willing to take the compilation and deployment part. 

Similar opened issues:
#1185 
#3262
#1401

**Comment by r15ch13** [comment]
A solution to this might be adding the private environment variables feature: https://github.com/lukesampson/scoop/pull/2917

**Comment by AndrewSav** [comment]
Does scoop support multiple insances of the same app _in principle_? I'm not talking about things like python2 / python3, I'm talking about cases like php, which have a single manifest. My impression was that scoop can only give you the latest version and that's about it.
