### ISSUE TITLE
Support --quiet option for all commands

### ISSUE THREAD

**Issue by krokofant** [ScoopInstaller/Scoop#3430]
To better use scoop commands programmatically it would be nice if all commands support the `--quiet` option as the `scoop update` command **partially** does:
https://github.com/lukesampson/scoop/blob/abe84d5c5e1fb33340f22b4ffd93da671ba7bb39/libexec/scoop-update.ps1#L14

It only seems to be used in a few places

**Comment by AndrewSav** [comment]
Not clear to me. In powershell whatever is piped to the output is dispalyed in console host if it's not consumed elsewhere. "silent" ususally means no output at all.

**Comment by krokofant** [comment]
@AndrewSav In this case `Write-Output` and `Write-Host` are mixed so while you can programatically use the output effectively it still writes to the console.

Take the `scoop status` command:
>   ~  scoop status
> WARN  Scoop is out of date. Run 'scoop update' to get the latest changes.
> Updates are available for:
>     lovelypowershell: 1.5 -> 1.6
>     scoop-completion: 0.0.3 -> 0.0.4

And say I'd want a function like this:
```powershell
function GetScoopOutdatedCount {
  (scoop status).Count
}
```
It works but since scoop uses `Write-Host` it logs more than I want:

>   ~  GetScoopOutdatedCount
> WARN  Scoop is out of date. Run 'scoop update' to get the latest changes.
> Updates are available for:
> 2

So maybe _silent_ is the wrong switch, what should it be called?
___
The `scoop update` command has [a `--quiet` switch](https://github.com/lukesampson/scoop/blob/abe84d5c5e1fb33340f22b4ffd93da671ba7bb39/libexec/scoop-update.ps1#L14) which hides "Extraneous messages"
```powershell
#   -q, --quiet               Hide extraneous messages
```
This actually works as I want 😃

**Comment by AndrewSav** [comment]
I talked with the team on the Discord and it sounds like they are opposed to that. The way I understood them, is that scoop's spirit is to be a first-class command-line **user** experience a-la linux. This means that developer's needs take a back sit and that passing out structured data is a no-no. On unix you have a pletora of ways dealing with output such as grep, awk and sed, and you can install them and use them with scoop output to your heart content.

I expressed a suprise that a powershell based tool so clearly is anti-powershell, and was told, that this is the way it is.

My personall opinion, is that since Powershell already has things like Format-Table and Format-Output for formating structured data and ways that you quoted to work with them, it would be natural to use those on the scoop output. Unfortunately this seems not to be the spirit or intention of scoop.

@r15ch13, @Ash258 and @h404bi took part in the discussion on discord that I'm referring to.

**Comment by krokofant** [comment]
> The way I understood them, is that scoop's spirit is to be a first-class command-line user experience a-la linux. This means that developer's needs take a back sit and that passing out structured data is a no-no. On unix you have a pletora of ways dealing with output such as grep, awk and sed, and you can install them and use them with scoop output to your heart content.

That is a very interesting description. Using pipes in a linux environment is very common which it also is with PowerShell. Just say now that you'd want to grep the version change from a specific module on `scoop status`.

Regular output
```powershell
  ~  scoop status
Scoop is up to date.
Updates are available for:
    lovelypowershell: 1.5 -> 1.6
    scoop-completion: 0.0.3 -> 0.0.4
Everything is ok!
```

Now to get the info about lovelypowershell
```powershell
  ~  scoop status | Select-String -Pattern "lovely"
Scoop is up to date.
Updates are available for:

    lovelypowershell: 1.5 -> 1.6
Everything is ok!
```

Or just save the output to a variable and deal with it later?
```powershell
  ~  $a = scoop status
$aScoop is up to date.
Updates are available for:
Everything is ok!

# or try to suppress all output?
  ~  scoop status | Out-Null
Scoop is up to date.
Updates are available for:
Everything is ok!
```

This would not fit the description of _first-class command-line user experience a-la linux_ and neither grep, awk or sed would help with this.

Something that would work is running the command through another powershell instance:
```powershell
 ~  Invoke-Expression "powershell -Command scoop status" | Select-String -Pattern "lovely"                           
    lovelypowershell: 1.5 -> 1.6
```

An alternative would be to just use `Write-Output` everywhere to be consistent, then it would function like other familiar command-line tools. If coloring is the hindrance it's [possible to support that with Write-Output](https://devblogs.microsoft.com/scripting/powertip-write-powershell-output-in-color-without-using-write-host/).

**Comment by lorengordon** [comment]
I'm kinda having a similar issue. To install `python`, scoop also needs `lessmsi`, but that outputs a non-ASCII character. And the AWS CloudFormation bootstrap package falls over itself when it captures non-ASCII output. So I'm trying to pre-install that package and silence the output. On linux, I could just redirect `> /dev/null`, but powershell doesn't seem to have a simple option. None of this works:

```
> $null = scoop install lessmsi
> scoop install lessmsi > $null
> scoop install lessmsi | out-null
> iex "scoop install lessmsi" | out-null
```

What does work, but is overly convoluted and not intuitive, is the suggestion to use another powershell instance:

```
> iex "powershell -command scoop install lessmsi" | out-null
> iex "powershell -command scoop install lessmsi" | select-string -Pattern 'é' -NotMatch
```

**Comment by rashil2000** [comment]
> On linux, I could just redirect > /dev/null, but powershell doesn't seem to have a simple option.

It does support it. Please refer to [Output Streams](https://stackoverflow.com/a/50937428) in PowerShell.

In essence, do this:

```
scoop install lessmsi 6> $null
```

**Comment by lorengordon** [comment]
Oh that's helpful, thanks! The output is a bit frightful when captured though, bunch of weird return characters in that output?

```
> Invoke-Expression "powershell -command scoop install lessmsi" | select-string -Pattern 'é' -NotMatch

Installing 'lessmsi' (1.10.0) [64bit]
Loading lessmsi-v1.10.0.zip from cache.
Checking hash of lessmsi-v1.10.0.zip ... ok.
Extracting lessmsi-v1.10.0.zip ... done.
Linking ~\scoop\apps\lessmsi\current => ~\scoop\apps\lessmsi\1.10.0
Creating shim for 'lessmsi'.
'lessmsi' (1.10.0) was installed successfully!
```

```
> scoop install lessmsi 6>&1 | select-string -Pattern 'é' -NotMatch

Installing 'lessmsi' (1.10.0) [64bit]
Loading
lessmsi-v1.10.0.zip
 from cache.
Checking hash of
lessmsi-v1.10.0.zip
 ...
ok.
Extracting
lessmsi-v1.10.0.zip
 ...
done.
Linking ~\scoop\apps\lessmsi\current => ~\scoop\apps\lessmsi\1.10.0
Creating shim for 'lessmsi'.
'lessmsi' (1.10.0) was installed successfully!
```

**Comment by rashil2000** [comment]
The output of Write-Host gets rearranged and modified (and colors disappear) when redirected to success stream. I'm afraid nothing can be done about it.

**Comment by lorengordon** [comment]
I guess I'll keep the funky "iex powershell ..." construction, in that case. Easier to read the logs.
