### ISSUE TITLE
Renaming organization and repositories

### ISSUE THREAD

**Issue by r15ch13** [ScoopInstaller/Scoop#3437]
- [x] [`scoopinstaller`](https://github.com/scoopinstaller) > `ScoopInstaller`
- [x] [`scoopinstaller/scoop-main`](https://github.com/scoopinstaller/scoop-main) > `ScoopInstaller/Main`
- [x] [`lukesampson/scoop-extras`](https://github.com/lukesampson/scoop-extras) > `ScoopInstaller/Extras`
- [x] [`scoopinstaller/php`](https://github.com/scoopinstaller/php) > `ScoopInstaller/PHP`
- [x] [`scoopinstaller/versions`](https://github.com/scoopinstaller/versions) > `ScoopInstaller/Versions`
- [x] [`scoopinstaller/binary-mirror`](https://github.com/scoopinstaller/binary-mirror) > `ScoopInstaller/Binary`
- [x] [`scoopinstaller/shimexe`](https://github.com/lukesampson/scoop/tree/master/supporting/shimexe) > `ScoopInstaller/Shim` (extraction required)
- [x] [`scoopinstaller/validator`](https://github.com/lukesampson/scoop/tree/master/supporting/validator) > `ScoopInstaller/Validator` (extraction required)
- [x] [`scoopinstaller/install`](https://github.com/scoopinstaller/install) > `ScoopInstaller/Install`
- [x] [`scoopinstaller/nightlies`](https://github.com/scoopinstaller/nightlies) > `ScoopInstaller/Nightlies` (delete because it's unused or reactivate)
- [x] [`scoopinstaller/awesome-scoop`](https://github.com/scoopinstaller/awesome-scoop) > `ScoopInstaller/Awesome`
- [x] [`scoopinstaller/scoop.sh`](https://github.com/scoopinstaller/scoop.sh) > leave as is
- [x] [`scoopinstaller/scoop-clone`](https://github.com/scoopinstaller/scoop-clone) > `ScoopInstaller/GitCloner`
- [x] [`se35710/scoop-java`](https://github.com/se35710/scoop-java) > `ScoopInstaller/Java`

_Originally posted by @r15ch13 in https://github.com/lukesampson/scoop/issues/2609#issuecomment-487941376_

**Comment by dwettstein** [comment]
Everything done. 🎉
