### ISSUE TITLE
Short-cuts in start menu are always cleaned up.

### ISSUE THREAD

**Issue by NamelessUzer** [ScoopInstaller/Scoop#3448]
Short-cuts in start menu are always cleaned up when Windows 10 update to a new version. In other words short-cuts in the folder `%HomePath%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Scoop Apps` are always cleaned up.
Is there any way to add these short-cuts back quickly? Or could you please provide a new command to add them back?

**Comment by h404bi** [comment]
This is a limitation of Scoop. WIndows Update forces resetting the shortcuts. You can reset all apps by using this command:

`scoop reset *`

**Comment by ssfjhh** [comment]
I believe reset is too heavy and too slow for adding short cuts back.

**Comment by ssfjhh** [comment]
some command like 'scoop fix shortcuts' can break the limitation easily. And it is not so heavy as 'scoop reset *'

**Comment by indrakaw** [comment]
scoop reset app1 app2 app3

Because wildcard is heavily.

**Comment by h404bi** [comment]
`scoop fix shortcuts` does not really help, because not all apps have shortcuts and it still need to walk through all apps to find out those shortcus. `scoop reset <what you need>` should be more suitable for you.

**Comment by ssfjhh** [comment]
> scoop reset app1 app2 app3
> 
> Because wildcard is heavily.

If one wants to add all the short-cuts back, Is there any difference between `scoop reset *` and `scoop reset app1 app2 app3 ...`?

**Comment by ssfjhh** [comment]
> `scoop fix shortcuts` does not really help, because not all apps have shortcuts and it still need to walk through all apps to find out those shortcuts. `scoop reset <what you need>` should be more suitable for you.

app.json files save if a short-cut is necessary for an app. `scoop fix shortcuts` command can read the app.json files to decide to add which shortcuts. `scoop reset app` is surely heaier than what I want.

**Comment by lepicsaintloup** [comment]
And for anyone else looking at this, Windows 10 update also breaks any scoop apps you may have set to auto start.

**Comment by archit9169** [comment]
It will be better if we create a shortcut folder inside scoop dir and link it with start menu shortcut folder.

**Comment by rashil2000** [comment]
#3941
