### ISSUE TITLE
Add package parameter

### ISSUE THREAD

**Issue by nagromc** [ScoopInstaller/Scoop#3498]
It would be great to be able to give additional parameters to the package installer.

Chocolatey can give parameters: https://chocolatey.org/docs/how-to-parse-package-parameters-argument

My use case, is when I want to give some special [configuration file](https://gpg4win.org/doc/en/gpg4win-compendium_35.html) to gpg4win with its `/C` option.

**Comment by rashil2000** [comment]
#3736
