### ISSUE TITLE
Question regarding security

### ISSUE THREAD

**Issue by itziksi** [ScoopInstaller/Scoop#3501]
Hi,
I have a question regarding the security of using scoop.
I couldn't find any document on the wiki,
I wish there was a page similar to https://chocolatey.org/security
( someone already suggested that https://github.com/lukesampson/scoop/issues/1666 )

How secure is the process of uploading manifest to the known buckets ?
how is it checked ? (moderation and virus checking, etc) ? 

Thanks for your help.

**Comment by rashil2000** [comment]
#1666
