### ISSUE TITLE
[Feature Request] scoop bundle, Scoopfile

### ISSUE THREAD

**Issue by AlJohri** [ScoopInstaller/Scoop#3507]
I would like to define the dependencies for my app in a `Scoopfile` just like I currently do with a `Brewfile` on MacOS.

```ruby
brew 'python'
brew 'pipenv'
brew 'tcl-tk'
brew 'ghostscript'
brew 'freetype'
brew 'imagemagick'
```

Then I can change my `Makefile` to `scoop bundle` or `brew bundle` depending on the OS.

```Makefile
install:
    brew bundle
    pipenv install
    pipenv run jupyter nbextension enable --py widgetsnbextension
    pipenv run jupyter labextension install @jupyter-widgets/jupyterlab-manager
    pipenv run jupyter nbextension enable --py qgrid
    pipenv run jupyter labextension install qgrid
```

**Comment by jayvdb** [comment]
There is https://www.powershellgallery.com/packages/ScoopPlaybook ; I've not tried it.

**Comment by kroppt** [comment]
https://github.com/lukesampson/scoop/issues/2609 is adding YAML support, so adding it after then would be best.

**Comment by rashil2000** [comment]
#3934
