### ISSUE TITLE
How to update from chrome to googlechrome?

### ISSUE THREAD

**Issue by wuya666** [ScoopInstaller/Scoop#3544]
When I installed Chrome with scoop a couple months ago, the manifest was named "chrome", but right now it seems it's re-named to "googlechrome" while the original "chrome" manifest is no more, so how should I upgrade from "chrome" to "googlechrome"? Is it safe if I uninstall "chrome" and install "googlechrome", will all my settings, accounts, etc. still be there? Thanks.

**Comment by linsui** [comment]
Just rename scoop\apps\chrome -> scoop\apps\googlechrome.

**Comment by wuya666** [comment]
> Just rename directory `scoop\apps\chrome` -> `scoop\apps\googlechrome` .

Nope, after renaming, the "current" junction breaks, which means the start menu entry breaks. That's exactly why I'm asking this question, I'm not sure what else I need to do to update "chrome" to "googlechrome", and what might break. I wonder if there's official documentation that deals with this kind of situation of manifest name changes, detailed instructions on how to safely update from old name to new name, and if there's any risk in losing previous settings and/or logged-in accounts.

**Comment by linsui** [comment]
Then run `scoop update googlechrome` and everything works well. I just do as this and bump into no error. Your settings are stored in `AppData` and scoop won't touch them. Just `scoop uninstall chrome` and `scoop install googlechrome` is also safe.

**Comment by Rundfunk** [comment]
> Just `scoop uninstall chrome` and `scoop install googlechrome` is also safe.
Just did the above and was able to keep my settings and open tabs, thanks!

**Comment by r15ch13** [comment]
Renaming the directory and running `scoop reset googlechrome` recreates the shortcut and junction.
