### ISSUE TITLE
nvs not working while used in command prompt.

### ISSUE THREAD

**Issue by Tryum** [ScoopInstaller/Scoop#3548]
When installed with scoop and used in `cmd.exe` a `nvs use ***/***/***` won't change the %PATH% and makes nvs unusable with command prompt.

This doesn't happen with the msi installed version of nvs.

**Comment by niheaven** [comment]
Log off and log on may help... That's env refresh prob.

**Comment by kroppt** [comment]
Did logging in again or restarting your computer fix the issue?

`scoop` installs the msi version by extracting it.

**Comment by rashil2000** [comment]
Fixed in https://github.com/ScoopInstaller/Main/pull/2271
