### ISSUE TITLE
WARN  error: Could not find file 'C:\apache.json'.

### ISSUE THREAD

**Issue by DesigningKnights** [ScoopInstaller/Scoop#3552]
When doing a scoop status, I get the following:
Scoop is up to date.
WARN  error: Could not find file 'C:\apache.json'.
These app manifests have been removed:
    apache

Yet it still shows as installed.  This just showed up recently.

**Comment by Ash258** [comment]
What is result of `Get-Content $env:SCOOP\apps\Apache\current\install.json` ?

**Comment by DesigningKnights** [comment]
Get-Content : Cannot find path 'C:\apps\Apache\current\install.json' because it does not exist.
At line:1 char:2
+  Get-Content $env:SCOOP\apps\Apache\current\install.json
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\apps\Apache\current\install.json:String) [Get-Content], ItemNotFound
   Exception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

The odd thing is, I did not uninstall apache.  I just updated scoop, and then that happened.

**Comment by Ash258** [comment]
Missing of `install.json` indicate that installation was broken.

And result of `scoop list apache`?

What was the last time you updated scoop?

**Comment by DesigningKnights** [comment]
I ended up uninstalling and reinstalling, and now it works.  I had updated scoop just before that error occured.
