### ISSUE TITLE
Feature Request: scoop to sideload Windows Store on LTSB/LTSC

### ISSUE THREAD

**Issue by averyfreeman** [ScoopInstaller/Scoop#3574]
Hey,

*NIX fan, but still need windows for proprietary software.  Just started using scoop a few weeks ago, and will undeniably use it for installing most software from here on out.

Was just wondering if there's a way to create a scoop for sideloading the Windows Store on LTSB/LTSC?  I have a script that does it, but it only installs for one user and blocks possibility of adding it for other users, making it very limited.

I put them on my onedrive so you can have a look:  [Link to sideload scripts + dependencies](https://1drv.ms/u/s!AnVJr1Om-YqxgYE_dF1N74_8OX8gAg?e=3KMxik)

It might not be possible to adapt for scoop, in that it uses the pwsh install-windowsfeature cmdlet, but I thought I'd ask anyway since I'm no expert.

would *love* to be able to scoop-manage this.  I absolutely hate feature-rolling W10, but still absolutely need store for a couple key apps unavailable anywhere else.  Plus, only 1 user per install for store is lame.

Any info would be extremely appreciated.  Thanks!

**Comment by rashil2000** [comment]
You can create a custom manifest for running your scripts, but this isn't something that can be added into Scoop core.
