### ISSUE TITLE
Python library loss after update python version.

### ISSUE THREAD

**Issue by zhangzhishan** [ScoopInstaller/Scoop#3595]
After update python version, the original library installed by pip is located in the old version folder. It can not be used directly through command line.

**Comment by copdips** [comment]
just reinstall them by pip install ?

**Comment by Deide** [comment]
One option is to make use of some virtualenv/venv

**Comment by thorstenkampe** [comment]
I don't understand why the Scoop mechanism for [persisting data](https://github.com/lukesampson/scoop/wiki/Persistent-data) is not used. Is the package maintainer aware of this mechanism?

**Comment by zhoujin7** [comment]
> I don't understand why the Scoop mechanism for [persisting data](https://github.com/lukesampson/scoop/wiki/Persistent-data) is not used. Is the package maintainer aware of this mechanism?

After upgrading python, there is no guarantee that the previously installed libraries are still compatible. It is best to reinstall them.

**Comment by thorstenkampe** [comment]
A minor upgrade - say from 3.8.0 to 3.8.1 - is always compatible. Only a major upgrade - say from 3.7 to 3.8 - will affect libraries which have a binary component (`pyd` files).

Not persisting `site-packages` at all is the worst option. If I reinstall Python (`scoop update --force`) or uninstall the old Python (`scoop cleanup python`) ALL packages will be gone! How do I reinstall packages that have been deleted without a trace?

**Comment by zhoujin7** [comment]
> A minor upgrade - say from 3.8.0 to 3.8.1 - is always compatible. Only a major upgrade - say from 3.7 to 3.8 - will affect libraries which have a binary component (`pyd` files).
> 
> Not persisting `site-packages` at all is the worst option. If I reinstall Python (`scoop update --force`) or uninstall the old Python (`scoop cleanup python`) ALL packages will be gone! How do I reinstall packages that have been deleted without a trace?

It is not always compatible, even if a minor upgrade, some libraries is not pure python.

**Comment by zanglg** [comment]
maybe persisting a site-packages folder with python version is a good solution, like: persist/python3.9/site-packages

**Comment by Cologler** [comment]
> A minor upgrade - say from 3.8.0 to 3.8.1 - is always compatible. Only a major upgrade - say from 3.7 to 3.8 - will affect libraries which have a binary component (`pyd` files).
> 
> Not persisting `site-packages` at all is the worst option. If I reinstall Python (`scoop update --force`) or uninstall the old Python (`scoop cleanup python`) ALL packages will be gone! How do I reinstall packages that have been deleted without a trace?

You should install packages in user site: `pip install --user ...`
