### ISSUE TITLE
packages installed by miktex-console cannnot be recognized in terminal

### ISSUE THREAD

**Issue by xarthurx** [ScoopInstaller/Scoop#3609]
So I installed the miktex by

`scoop install latex`

and installed several packages from `miktex-console` (an interface to control latex packages).

However, some packages installed from the console cannot be recognized in `Powershell`.

Might be caused by missing to append the "xxx\scoop\apps\latex\2.9.7152\texmfs\install\miktex\bin\x64\latexmk.exe" to  the PATH?

**Comment by linsui** [comment]
It should be in the path, see https://github.com/ScoopInstaller/Main/blob/124657a4bf820958aba6683b606cbf3732c4ffdf/bucket/latex.json#L21 .

**Comment by xarthurx** [comment]
This is strange....

I installed the 64 bit version by default, but the path of the 32 bit is added by the script...

`texmfs\\install\\miktex\\bin` instead of  `texmfs\\install\\miktex\\bin\\x64`

**Comment by xarthurx** [comment]
I tried to uninstall and re-install, the path issue still exist.
even `miktex-console` cannot be called from the cmd.

**Comment by Ash258** [comment]
https://github.com/lukesampson/scoop/pull/3503

It cannot work because it is not supported. For some reason it was merged even when it should not.

**Comment by rasa** [comment]
Seems the CI didn't catch the schema validation failure

**Comment by xarthurx** [comment]
Is this bug still being fixed?
It seems it was fixed for one or two days, and now it is not working again.

the `x64` folder is not in the path currently.

**Comment by xarthurx** [comment]
This issue is still not fixed...
It should be very easy to fix. May I ask what's the issue here?

**Comment by xarthurx** [comment]
@linsui @niheaven @rasa @Ash258

**Comment by linsui** [comment]
I can't reproduce your problem here... Both of bin and bin\x64 are added.

**Comment by niheaven** [comment]
So just force update miktex may fix the issue.

**Comment by xarthurx** [comment]
Ah, didn't know the force part. Thank you for the help and sorry for the spam.
