### ISSUE TITLE
The variable '$scoopConfig' cannot be retrieved because it has not been set.

### ISSUE THREAD

**Issue by brianary** [ScoopInstaller/Scoop#3626]
I'm unable to install Scoop in strict mode (`Set-StrictMode -Version latest`). I get this error:

> The variable '$scoopConfig' cannot be retrieved because it has not been set.

I can define `$scoopConfig` using a null-object pattern:

```powershell
$scoopConfig = [pscustomobject]@{rootPath=$null;globalPath=$null;cachePath=$null}
```

But then I still get:

> The property 'proxy' cannot be found on this object. Verify that the property exists.

If I disable strict mode (`Set-StrictMode -Off`), installation works fine.

**Comment by MarkMichaelis** [comment]
I see the same issue running:
```
$env:SCOOP='C:\ProgramData\scoop'
[environment]::setEnvironmentVariable('SCOOP',$env:SCOOP,'User')
iwr -useb get.scoop.sh | iex
```
The output I see is:

> Initializing...
> Invoke-Expression : The variable '$scoopConfig' cannot be retrieved because it has not been set.
> At line:33 char:1
> \+ Invoke-Expression (new-object net.webclient).downloadstring($core_url ...
> \+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidOperation: (scoopConfig:String) [Invoke-Expression], RuntimeException
>     + FullyQualifiedErrorId : VariableIsUndefined,Microsoft.PowerShell.Commands.InvokeExpressionCommand
>
