### ISSUE TITLE
Basic Authentication to download a file

### ISSUE THREAD

**Issue by trajano** [ScoopInstaller/Scoop#3636]
I host my binaries in Nexus and it provides a way of doing basic authentication to access the data.  Without actually hard coding the user name and password in the scoop bucket app manifests, is there a way of setting this up so I can download from the Nexus server?

**Comment by dsa-ols** [comment]
Hi, this would be a good options for binaries / parameters you'd want to keep private. Any update regarding the issue?

**Comment by rashil2000** [comment]
You can set a `cookie` property to authenticate the download URL, Scoop will send the cookie while downloading. Other than that, no options.
