### ISSUE TITLE
Scoop can't recognize all installed apps

### ISSUE THREAD

**Issue by carcrazy** [ScoopInstaller/Scoop#3642]
I had used scoop for a while. Today when I want to check status of all installed apps. After I inputting command "scoop status", it reports error "These app manifests have been removed" and "These app failed to install". Below these two message, it lists apps. After checking, I found the listed app covers all apps I downloaded through scoop. It looks like the scoop lost connection with its managed apps. Any idea for solving this? Thanks in advance.

**Comment by niheaven** [comment]
For every such error or missing apps, run `scoop uninstall XXX; scoop install XXX` will fix.

Some are failed to install, while others' manifests may be moved between buckets.

**Comment by triskelcmd** [comment]
https://github.com/lukesampson/scoop/issues/3642#issuecomment-532287196 is informative.
