### ISSUE TITLE
Firefox is not added to environment path

### ISSUE THREAD

**Issue by quantuumsnot** [ScoopInstaller/Scoop#3649]
For example after trying to start Firefox Profile manager to restore a profile

> C:\Windows\system32>firefox -P
'firefox' is not recognized as an internal or external command,
operable program or batch file.

FF version is 70.0b7

**Comment by linsui** [comment]
If you installed firefox-beta, please use `firefox-beta -P` instead of `firefox -P`

**Comment by quantuumsnot** [comment]
Current executable filename is 

> D:\scoop\apps\firefox-developer\current\firefox.exe

Anyway there's a nasty UX problem when people backup and uninstall firefox and jump on the scoop variant - the backup is not detected properly even when redacted `profiles.ini` and during `-P` time you must create a FRESH one profile then pasting backup content in it. Ok, this seems fine at first but if the user picks again the wrong one or deletes it in this profile manager while already deleted the backup it's possible to reach 1 meter before the finish line without wheels (data) :}

**Comment by triskelcmd** [comment]
https://github.com/lukesampson/scoop/issues/3649#issuecomment-533232293 is informative.

**Comment by linsui** [comment]
Why do you link to a comment in this issue?

**Comment by triskelcmd** [comment]
please see https://github.com/lukesampson/scoop/issues/3657#issuecomment-534435083

Click text below to expand!
<details>
  <summary> moreover... </summary>
people attribute incorrect meanings to ambiguous emojis, creating miscommunication and other issues, for a over-simplified example- Attitude polarization due to confirmation bias; which can then lead to living in multiple delusions.
  
</details>

**Comment by CarlGustavAlbertDwarfsteinYung** [comment]
Hi@quantuumsnot 

There may be an issue with making Firefox portable. Chrome seems to have a few issues with setting it as a default browser for example.


But is also possible the hardlink  `current` may be the issue
Could you try changing the path to the actual real folder location and avoid using current? 

I have personally had issues setting the path to the java sdk location when I had `current` hardlink in the path. Instead I used the real path.  It also happens from IDEA for example when is trying to look for an SDK it won't recognize any path with `current` hardlink in it.

**Comment by quantuumsnot** [comment]
Already stated that I fixed the problem, FF is fully portable for me through scoop, ye the `current` directory is probably a no-go for most of the apps as persistent user data storage location

**Comment by trip23app** [comment]
> also possible the hardlink `current` may be the issue

is it hardlink or junction? its junction on my machine.

**Comment by quantuumsnot** [comment]
It's a junction:

> D:\scoop\apps\firefox-developer>dir
>  Volume in drive D has no label.
>  Volume Serial Number is 10A7-C1D1
> 
>  Directory of D:\scoop\apps\firefox-developer
> 
> 10/05/2019  03:26 PM    \<DIR\>          .
> 10/05/2019  03:26 PM    \<DIR\>          ..
> 10/05/2019  02:15 PM    \<DIR\>          70.0b12
> 10/05/2019  03:26 PM    \<JUNCTION\>     current [D:\scoop\apps\firefox-developer\
> 70.0b12]

**Comment by CarlGustavAlbertDwarfsteinYung** [comment]
@quantuumsnot @trip23app I was reading that creating a junction is possible on a networked drive.
