### ISSUE TITLE
After updating scoop's Google Chrome it went nuts

### ISSUE THREAD

**Issue by quantuumsnot** [ScoopInstaller/Scoop#3657]
Mainly 40+ tabs went into the wild - not saved in history or opened after closing, updating and starting the browser

Next time please test the apps BEFORE added to scoop's ecosystem. Thank you very much

**Comment by quantuumsnot** [comment]
Now more on the problem. If you set
`D:\scoop\apps\googlechrome\current\chrome.exe --user-data-dir=d:\scoop\apps\googlechrome\**current**\User`

it's ok to expect that scoop will **MOVE** `User` subdir from symlinked `chromeversiondirname` as `current` to the newer one `chromeNEWERversiondirname`, not leaving it in the old and waiting chrome to create a new one. In this case scoop MUST move the `User` dir from `77.0.3865.75` dir to `77.0.3865.90`

**Comment by linsui** [comment]
If you want a portable chrome by setting `D:\scoop\apps\googlechrome\current\chrome.exe --user-data-dir=d:\scoop\apps\googlechrome\current\User` , please create a new manifest `googlechrome-porable` or something else. Scoop does not know there is a `User` directory which need to be persist unless you tell it by `persist` .

**Comment by Ash258** [comment]
Portable settings configured with parameter are pain for many reason, but main is the obvious one, which will make it unusable.

You cannot set parameter to **Window's Default Apps**. This will make it junk.

1. If you open it from start menu / cmd, it will work with parameter.
1. If some application will spawn `& url.url` (how all application spawn browser) browser will be opened without parameter, which will result in completely different profile located in AppData
1. If you set it as open with, then again you have no parameter.

As I already told you in issue before. Chrome is using AppData. This indicates it is not portable by default. You created your own problem, which has no solution, which will fit most users use cases. Create custom manifest in custom bucker for portable chrome, but it will not work as you want.

**Comment by quantuumsnot** [comment]
Already fixed the problem but I'm too lazy to add parameters to the shortcut in `C:\Users\UserName\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Scoop Apps` :)

**Comment by triskelcmd** [comment]
https://github.com/lukesampson/scoop/issues/3657#issuecomment-533855636
informative post.

github should have a " informative" reaction.

**Comment by quantuumsnot** [comment]
The final fix to make Chrome somewhat portable in scoop is to associate `http` and `https` urls when opened from your mail client or any app that opens them or files with the DEFAULT browser in the system. Just open in the registry `HKEY_CLASSES_ROOT\http\shell\open` and change the registry at `HKEY_CLASSES_ROOT\ChromeHTML.QLSDFSVFTHARQA4CM4IU7I35SY\shell\open\command` to be 

> "yourdrivename:\scoopdirectory\apps\googlechrome\current\chrome.exe" "%1" "--user-data-dir=yourdrivename:\scoopdirectory\apps\googlechrome\yourUserDataDirectory"

instead of

> "yourdrivename:\scoop\apps\googlechrome\current\chrome.exe" -- "%1"

**Comment by trip23app** [comment]
https://github.com/lukesampson/scoop/issues/3657#issuecomment-533850089

<hr>

from https://github.com/lukesampson/scoop/issues/3657#issuecomment-533855636

>You cannot set parameter to Window's Default Apps

this applies only if user tries to make google-chrome work in portable mode?

**Comment by quantuumsnot** [comment]
If I remember correctly if you need chrome to output to stdout you must enable logging with a switch after the exe:
`chrome.exe --enable-logging --v=1`

**Comment by trip23app** [comment]
> you must enable logging with a switch

good to know. but i'm talking about what `curl.exe -h`would do.

**Comment by quantuumsnot** [comment]
There's no `/help` or `/?` switches implemented for `chrome.exe`
