### ISSUE TITLE
Per app install directory

### ISSUE THREAD

**Issue by SonOfDiablo** [ScoopInstaller/Scoop#3659]
Setting the Environmental Variable(s) `SCOOP` and `SCOOP_GLOBAL` is neat and really useful.

But what would be more useful (at least in my case) would be the ability to choose a specific install directory on a per app basis.

Something like `scoop install <appname> -dir <directory>`
Would install the app in the given directory or maybe at least create a symlink. (I have noticed that Scoop keeps track of the apps by looking at the folders in the apps directory)

If not this, then is there any way to run post install actions/scripts?

**Comment by triskelcmd** [comment]
it would be great if all the applications would support `dual apps` scenario.  

if anyone does not know what dual apps is, see https://www.androidcentral.com/what-you-need-know-about-dual-apps-miui-8 for en example implementation.
