### ISSUE TITLE
running scoop update after using checkver.ps1 results in this error

### ISSUE THREAD

**Issue by contigon** [ScoopInstaller/Scoop#3662]
After using checkver.ps1 * -u and then unnning scoop update or other commands are showing this error :

Updating 'extras' bucket...
error: Your local changes to the following files would be overwritten by merge:
        bucket/aida64extreme.json
        bucket/altair.json
        bucket/bitwarden.json
        bucket/brave.json
        bucket/cacher.json
        bucket/ibmcloud-cli.json
        bucket/islc.json
        bucket/protobuf.json
        bucket/whatsapp.json
Please commit your changes or stash them before you merge.

To solve that i had to do run this:
scoop bucket list | foreach {write-host 'resetting bucket:'$_;cd $_;git reset --hard;git pull;git commit}

**Comment by Ash258** [comment]
Why are you running checkver locally?

**Comment by contigon** [comment]
i am using scoop in an offline network so i have changed the install.ps1 so i can install from local http server using the apps that downloaded earlier to the cache folder.
i need to force update of manifests and apps so i can create the offline scoop environment on request .

**Comment by Ash258** [comment]
Since you are editing core for install, then just edit `libexec\scoop-update.ps1` 

https://github.com/lukesampson/scoop/blob/master/libexec/scoop-update.ps1#L283
```diff
-    if (is_scoop_outdated) {
-        update_scoop
-    }
```
Then you will not be downloading bucket updates and you will be updating apps directly.
