### ISSUE TITLE
Is there a way to extract which one of installed apps are using persist dir?

### ISSUE THREAD

**Issue by quantuumsnot** [ScoopInstaller/Scoop#3675]
It would be cool to have a list with all scooped apps that are using `persist` directory or at least an improvement to commands like `scoop status` or `scoop list` to show which ones from the installed use it. Just found that if using a shortcut parameters to `VSCode-Portable`/`VSCodium-Portable` to use different directories for `extensions` and `user-data` doubles the data because they already use the `persist` dir. Simplified for about an year and half I'm loosing around 622MB (652,242,944 bytes) from the drive capacity due to doubling the data

**Comment by Deide** [comment]
`ls $env:SCOOP/persist`

**Comment by quantuumsnot** [comment]
Ash, you cannot trigger me ;) Be a grown-up and act as such <-(_free advice_)

**Comment by quantuumsnot** [comment]
> `ls $env:SCOOP/persist`

Scoop is a Windows package manager, dude ... `ls` is not found in Windowses before 10

**Comment by Deide** [comment]
`ls` is an alias for `Get-ChildItem` in Powershell. Try it.

**Comment by quantuumsnot** [comment]
Some ppl are not using only Poweshell but and the classical cmdprompt. Back compatibility is important

**Comment by Deide** [comment]
`dir %SCOOP%\persist`

**Comment by quantuumsnot** [comment]
That's not the idea. I'm pointing the problem with disk space wasted. The number of installed scooped apps increases thus the disk space wasted due to some modifications done by users, because they are at least power or devs and prefer to control where their user data is stored. For example I'm using a direct connection gigabit backup solution between two cpu-heavily used machines with RAID 1 and each megabyte counts, especially on HDDs because of IO

**Comment by Deide** [comment]
Oh, so you want to choose where the persistent data for each application goes? Or choose where the persistence directory goes in general?

**Comment by quantuumsnot** [comment]
Nope, just when installing an app to see if it's using `persist` dir before the user makes some changes to app's behaviour which could lead to lost disc space

**Comment by Deide** [comment]
How would knowing if it uses persist solve your problem?

**Comment by quantuumsnot** [comment]
For example I won't add to shortcut's `Target` field something like `--extensions-dir="Driveletter:\appextensions"` or changing similar options in its settings

**Comment by Deide** [comment]
Not sure what's stopping you from checking that right now. But if you mean you're doing this programmatically (as a power user), then something like:

```powershell
function Test-Persists {
    param([String] $Name, [String] $Bucket = "main")
    $manifestPath = "$env:SCOOP\buckets\$Bucket\bucket\$Name.json"
    if (Test-Path $manifestPath) {
        $manifest = Get-Content -Path $manifestPath | ConvertFrom-Json
        if ($manifest.persist) {
            $true
        }
        else {
            # The specified app $Bucket/$Name does not have any persistence
            $false
        }
    }
    else {
        # The specified app $Bucket/$Name could not be found
        $false
    }
}
```
will allow you to check if an application uses persistence before you even install it. Like
```
> Test-Persists php
True
> Test-Persists 7zip
False
> Test-Persists -Name someAppThatUsesPersistence -Bucket someInstalledBucket
True
```

Good luck!

**Comment by quantuumsnot** [comment]
Persist check should be integrated as core functionality and be run each time scoop updates or installs while maintaining list of persisted apps because there's a high chance an update to their manifests to add/remove `persist` option

Should I write this as patch or do more important things? Good luck to you too :)

**Comment by trip23app** [comment]
so everyone should just fork it and keep improving it and not upstream their improvements. (●'◡'●)

jokes aside, **deide** has provided a minimal working example that can be integrated into scoop.  thanks to that, problem solved. 

i think doing the same for globally installed apps in $env:SCOOP_GLOBAL will work as a minimal working example. but in both cases more information is required about what could go wrong.

**Comment by Deide** [comment]
@trip23app Well I'm still not sure what should be integrated. What does an automatic "persist check" do? Print some text to say if things were persisted upon install/update? Because scoop already does that! In fact, it goes further and logs exactly what is being persisted.

Now, a `scoop list --persist` or something might be a little more sensible (non-automatic check), but I'm personally against it due to the ease with which you can already check as I pointed out above.

**Comment by quantuumsnot** [comment]
Hmmm, speaking of that I think scoop has the chance to offer a fully portable environment for apps to deal with the problem with writing files everywhere. Most of these apps first check for needed dlls/etc in their own directories ... Think have a couple of spare machines to start running Process Explorer or similar ... Just need more time
