### ISSUE TITLE
Issue install old version of an app that use an autoupdate matcher

### ISSUE THREAD

**Issue by scayssials** [ScoopInstaller/Scoop#3686]
**What**
install with autoupdate matcher do not work

**reproduction case**
scoop install qemu@3.1.0

**acutal result**
`Downloading qemu-w32-setup-$matchYear$matchMonth$matchDay.exe to compute hashes!`
matcher hasn't been called

**expected result**
right url

**Investigation**
When using scoop-install with an unknow manifest we call
`generate_user_manifest $app $bucket $version`
the function will then call 
`autoupdate $app "$(resolve-path $(usermanifestsdir))" $manifest $version $(@{})`
where `$(@{})` represent the `[Hashtable] $matches`

**Comment by rashil2000** [comment]
#2702
