### ISSUE TITLE
Error when comparing versions that are too large

### ISSUE THREAD

**Issue by TheRandomLabs** [ScoopInstaller/Scoop#3687]
For example, if I have `adopt8-hotspot-nightly` installed and run `scoop status`, I get the following error:

    Cannot convert value "201910101115" to type "System.Int32". Error: "Value was either too large or too small for an Int32."

The error occurs [here](https://github.com/lukesampson/scoop/blob/19ed5e42a8c09fc39f10bd13c97d8ac4f689f5b4/lib/versions.ps1#L32) and could probably be fixed by changing `[int]` to `[long]` or `[decimal]`.

**Comment by niheaven** [comment]
Will be fixed after recent hotfixes being merged.

**Comment by rashil2000** [comment]
Fixed in master
