### ISSUE TITLE
Fresh Install and cannot install software due to 7zip Issue 

### ISSUE THREAD

**Issue by m0ll3art** [ScoopInstaller/Scoop#3698]
just wanted to give scoop a try and I tried to install git as the first app but it fails 

I cannot install git because it cannot find 7-zip. I uninstalled the old version of 7-zip I had but nothing helped. It seems this "bug" comes now and then.. see screenshot for details  .. 

![issue-scoop-7zip](https://user-images.githubusercontent.com/11415120/67101799-9a870480-f1c2-11e9-89eb-aa798784c115.png)

**Comment by Ash258** [comment]
Could you please try command below and post result.

`scoop config debug $true; scoop uninstall 7zip; scoop install 7zip`

**Comment by m0ll3art** [comment]
![scoop2](https://user-images.githubusercontent.com/11415120/67107330-8a742280-f1cc-11e9-82bf-204864f9948a.png)

**Comment by Ash258** [comment]
What antivirus do you use? I suspect something locked / cleared these files from extraction. Usually antivirus is the guilty one.

Is the folder really empty when you go to `~/apps/7zip/19.09/_tmp/Files`?

I cannot reproduce on fresh windows sandbox instance 

![image](https://user-images.githubusercontent.com/13260377/67107970-c52a8a80-f1cd-11e9-9ca7-d64786088d37.png)

**Comment by m0ll3art** [comment]
i use  a McAfee scanner  and there is no `_tmp\files` folder only the msi file and a msi.log

**Comment by Ash258** [comment]
Try to disable it for 2 minutes and repeat installation

**Comment by m0ll3art** [comment]
Virus scanner is not the home version and thus some controls missing to disable it but it seems also not to interfere currently with the system since not correctly installed. Appget install of  7zip seems to work

**Comment by Ash258** [comment]
You could potentially install 7zip externally and then use `scoop config '7ZIPEXTRACT_USE_EXTERNAL' $true` So scoop will use external 7zip installation rather than $env:SCOOP\apps\7zip

But this is weird. There is no reason that 7zip folder do not exists after extraction.

One possible cause could be msiexec. try with `scoop install lessmsi; scoop config MSIEXTRACT_USE_LESSMSI $true; scoop install 7zip`

**Comment by m0ll3art** [comment]
Great, that does the trick, thanks for your help

it seems that there is an issue with extracting the 7zip MSI using the standard method (where is this coded (scoop PS1 or bucket package PS1?). And not sure the virus scanner (since more or less absent in the current state of my machine) was the problem. But what is wired is my `msiexec` seems not to work correctly since I tried to extract the 7zip MSI package and passed the `TARGETDIR` as parameter but it ignores it completely and used instead the target directory  G:\Files (one of my network drive why ??) and if I isolate the system, but dropping the network adapter, it uses C:\Files.. Any ideas why?  

Is there a way to test if `msiexec` is healthy?

**Comment by Ash258** [comment]
You could try the same arguments as scoop is using. In your case it should look like this:
`msiexec.exe /a "$env:SCOOP\cache\reallyLongNameOf7zip.msi" /qn "TARGETDIT=`"$env:SCOOP\cache\test7zip`""`

https://github.com/lukesampson/scoop/blob/08af9ff6e7f7b017701c0c9114294b13e1e83fb8/lib/decompress.ps1#L132-L135

Or investigate msi.log inside application directory after failed installation with msiexec.

**Comment by m0ll3art** [comment]
thanks will investigate ..

**Comment by jordancluts** [comment]
Wanted to comment that I was having issues with 7zip. My corporate environment somehow blocks the installation of 7zip (cannot even install manually by downloading and running the MSI), this prevented the installation of any app which used `"innosetup" = true`.

The above trick to switch the MSI installer to lessmsi and then use that msi installer let me install 7zip and then the other applications I was aiming for.
