### ISSUE TITLE
Option to run an app's installer wizard

### ISSUE THREAD

**Issue by shoogle** [ScoopInstaller/Scoop#3709]
Scoop rightly defaults to a portable installation (i.e. no registry changes) in the user's home directory. However, sometimes it is desirable to install applications for all users, with the necessary registry changes to support:

- Document icons for the application in File Explorer
- Right-click > Open with... this application
- Make it the default application for a particular filetype
- etc.

The easiest way to do this is run the application's installer wizard. This could be done via a new `--wizard` option to `scoop install`.

```
scoop install --wizard [appname]
```

Here, scoop is simply used as a way to automate the process of visiting the application website, finding the download page, performing the download, and running the installer.

Scoop would not be used to manage the application beyond its installation (i.e. create shims, perform updates and removal), though such abilities could always be added at a later date. 😉 

This could also help with #2651, #3176 and #3691.

**Comment by Deide** [comment]
Would running the installer show the installer UI and have you click through it? Or do you mean do do silent installations?

If silent installations, then installer arguments need to be given. How would you go about unifying all the different ways to install common (and uncommon where necessary) installer arguments? I suppose a line would have to be added to all manifests, right?

So realistically, this is a proposal to add to the manifest schema.

On the other hand, if you're not interested in silent/headless installations, then you could easily add an alias to just look at an app's manifest, download the link and run it.

**Comment by shoogle** [comment]
I'd be happy clicking through the wizard. This is simplest and avoids changing the maifests.

As I hinted above, there is scope to add more features later, such as handling updates, removal and shims of apps installed via this method, but doing so would involve changes to the manifest. I would regard silent installs as one of these "bonus" features that could be considered later on.

**Comment by rashil2000** [comment]
#3736
