### ISSUE TITLE
Your local changes to the foll ... what changes?

### ISSUE THREAD

**Issue by quantuumsnot** [ScoopInstaller/Scoop#3713]
> Updating 'extras' bucket...
> error: Your local changes to the following files would be overwritten by merge:
>         bucket/googlechrome.json
> Please commit your changes or stash them before you merge.
> Aborting
> Updating 'games' bucket...
> error: Your local changes to the following files would be overwritten by merge:
>         .editorconfig
>         .pre-commit-config.yaml
>         appveyor.yml
> Please commit your changes or stash them before you merge.
> Aborting

Never changed those files ...

**Comment by Calinou** [comment]
Could this be an issue with line endings?

Either way, to solve the issue, you can `cd` to the respective bucket folders (they're in `%USERPROFILE%\scoop\buckets) then run `git reset --hard HEAD`.

**Comment by quantuumsnot** [comment]
Well, first my scoop is not there and secondly:

> D:\scoop\buckets>git reset --hard HEAD
> fatal: not a git repository (or any of the parent directories): .git

**Comment by Deide** [comment]
> respective bucket folders

As in `D:\scoop\buckets\main` or `D:\scoop\buckets\extras`

**Comment by Calinou** [comment]
@Deide You should run that command in all the buckets which give you conflicts. If you're not sure, just run it in all buckets :slightly_smiling_face:

**Comment by Deide** [comment]
@Calinou I was correcting @quantuumsnot, haha. I have no issue.

**Comment by quantuumsnot** [comment]
Well, I've edited my post because it wasn't clear enough, but the error is the same ... Sorry, don't have more time to investigate

**Comment by quantuumsnot** [comment]
The error 'Your local changes ...' is fixable by simply deleting those files ... Outstanding

**Comment by JanPokorny** [comment]
Happened to me once with the `games` bucket. Removing and re-adding the broken bucket is the easiest fix.

**Comment by quantuumsnot** [comment]
Shift + Delete is an old technology, older than Git and still works faster, better and psychologically more stable ...

**Comment by JanPokorny** [comment]
@quantuumsnot I'd say telling people "Do `scoop bucket rm X` and then `scoop bucket add X`" is way easier than explaining where to go and what files to delete...

But the underlying issue here is that Scoop can't do this automatically. I believe the right course of action, when update fails, would be to offer something like `scoop update --force` to overwrite changes (ie. do git reset internally). (Overwriting by default may be too destructive.)

**Comment by quantuumsnot** [comment]
Shush, comrade! If the party said those files must be deleted, well ... they must be deleted
