### ISSUE TITLE
[Suggestion] Replicating the install configuration on multiple machines

### ISSUE THREAD

**Issue by cmoisei** [ScoopInstaller/Scoop#3744]
I have a suggestion as a result of changing/swapping/replacing laptops/desktops.

Bottom line would be nice to be able to copy or store via git the scoop configuration, downloaded it or pull it to other machines and then run an scoop update to have the new machine match exactly that configuration!

I admit, I don't know if this is currently possible, might well be but didn't find any docs about it.

Thanks!

**Comment by Calinou** [comment]
See #2105. Scoop can export the installed package list, but not import it yet.

**Comment by rashil2000** [comment]
#3934
