### ISSUE TITLE
The SSL connection could not be established, see inner exception. Authentication failed, see inner exception.

### ISSUE THREAD

**Issue by danny-su** [ScoopInstaller/Scoop#3746]
The SSL connection could not be established, see inner exception. Authentication failed, see inner exception.                          
At C:\Users\danny\scoop\apps\scoop\current\lib\install.ps1:130 char:9                                                                  
+         throw $e                                                                                                                     
+         ~~~~~~~~                                                                                                                     
+ CategoryInfo          : OperationStopped: (:) [], WebException                                                                       
+ FullyQualifiedErrorId : The SSL connection could not be established, see inner exception. Authentication failed, see inner exception.

**Comment by Ash258** [comment]
What are you trying to install? Scoop itself or some application?

**Comment by danny-su** [comment]
for example, scoop install dart

**Comment by danny-su** [comment]
Run the following command on powershell will fix the issue:
`[Net.ServicePointManager]::SecurityProtocol = "tls12, tls11, tls"`
for more information, refer to https://stackoverflow.com/questions/41618766/powershell-invoke-webrequest-fails-with-ssl-tls-secure-channel

**Comment by yihuajack** [comment]
Same issue.
```
The SSL connection could not be established, see inner exception.
URL https://raw.githubusercontent.com/lukesampson/psutils/c7116ac143ca81f223e6091d0974f45ac241eb1d/sudo.ps1 is not valid
```
scoop can successfully install apps on cmd but failed on PowerShell Core 7.

**Comment by chuan-325** [comment]
> Same issue though it's temporary (fixed after rebooting).
> 
> ```
> The SSL connection could not be established, see inner exception.
> URL https://raw.githubusercontent.com/lukesampson/psutils/c7116ac143ca81f223e6091d0974f45ac241eb1d/sudo.ps1 is not valid
> ```
> 
> scoop can successfully install apps on cmd but failed on PowerShell Core 7.

I do not know how it works, but everything turned to the right way after I switch to **cmd** from _powershell_ (new) and _windows powershell_ (old). Thanks for the piece.
