### ISSUE TITLE
extract_dir fails on tar.xz archive

### ISSUE THREAD

**Issue by kostrse** [ScoopInstaller/Scoop#3750]
Example manifest:

```json
{
    "version": "2.24.0",
    "url": "https://github.com/newren/git-filter-repo/releases/download/v2.24.0/git-filter-repo-2.24.0.tar.xz",
    "hash": "92188d3c44b9ff0dd40dfeed72859e0a088f775c12fb24c4e3e27a8064cfcc84",
    "extract_dir": "git-filter-repo-2.24.0"
}
```

The _.xz_ archive contains a _.tar_ file inside which in turn contains the directory with the same name: `git-filter-repo-2.24.0`.

Without the `extract_dir` field, everything works fine, but all files extracted to the version-specific `git-filter-repo-2.24.0` folder:

```
C:\Users\sekost\scoop\apps\git-filter-repo\2.24.0\git-filter-repo-2.24.0
```

I wanted to cut the version-specific folder from the archive using the `extract_dir`, but it breaks the installation:

```
scoop install .\bucket\git-filter-repo.json
Installing 'git-filter-repo' (2.24.0) [64bit]
Loading git-filter-repo-2.24.0.tar.xz from cache
Checking hash of git-filter-repo-2.24.0.tar.xz ... ok.
Extracting git-filter-repo-2.24.0.tar.xz ... Could not find 'git-filter-repo-2.24.0'! (error 11)
At C:\Users\user1\scoop\apps\scoop\current\lib\core.ps1:510 char:9
+         throw "Could not find '$(fname $from)'! (error $($proc.ExitCo ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (Could not find 'git\u20262.24.0'! (error 11):String) [], RuntimeException
+ FullyQualifiedErrorId : Could not find 'git-filter-repo-2.24.0'! (error 11)
```

I suspect that something wrong with the handling of `.tar.xz` archives.

**Comment by linsui** [comment]
There is symlink in the archive. See https://superuser.com/questions/1076527/7zip-cannot-create-symbolic-link-access-is-denied-to-libhdfs-so-and-libhadoop-s

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Main/issues/3042
