### ISSUE TITLE
[feature request] extract_dir: wildcard support

### ISSUE THREAD

**Issue by Harakku** [ScoopInstaller/Scoop#3755]
It would be useful to be able to use wildcards in the "extract_dir" field to flatten an archive. With wildcards we don't have to care if the outer directory names change between different versions of an app.

For example, with an extract_dir value of `*\*`, these zip file contents
```
.
├── a.txt
├── zipdir
│   ├── appdir
│   │   └── c.txt
│   └── b.txt
└── zipdir2
    └── d.txt
```
would turn into this:
```
.
├── a.txt
├── appdir
│   └── c.txt
├── b.txt
└── d.txt
```

The reason it doesn't work like this right now ([an error would be thrown](https://github.com/lukesampson/scoop/blob/master/lib/core.ps1#L510)) seems to be robocopy not supporting wildcards in the source directory parameter.

Some options for implementing this feature would be mangling the robocopy call in a way that robocopy would be happy or using another method for moving files and deleting the source directories.

**Comment by rashil2000** [comment]
You can put extract_dir in autoupdate field
