### ISSUE TITLE
Using VSCode and scoop installed git crashes system

### ISSUE THREAD

**Issue by fv-ian** [ScoopInstaller/Scoop#3756]
When utilizing git via `scoop install git`, VSCode 1.40.1 will spawn a unlimited # of git proceses that are hung.   

Thousands of git.exe are executed and hung in the background.   

If someone can tell me how to pull more info from the process and how / why it's hanging, I'll update the ticket with that info.

**Comment by r15ch13** [comment]
Does it happen when you use git from the Console/PowerShell as well?
Somehow I have the feeling that I encountered this problem myself and it had something to do with `openssh`.
Could you try `git-with-openssh`?
