### ISSUE TITLE
[enhancement] Have the ability to add in associations in Windows

### ISSUE THREAD

**Issue by fv-ian** [ScoopInstaller/Scoop#3757]
When running python installed via scoop (`scoop install python37`) it does not configure the user or system level association.  

A workaround is to run the following if in powershell
```
cmd /c assoc .py=py_auto_file
cmd /c ftype py_auto_file="<scoop root directory>\scoop\shims\python.ps1" "%1" %*
```

**Comment by fv-ian** [comment]
Found this to turn it into a full powershell solution:

https://p0w3rsh3ll.wordpress.com/2012/04/18/assoc-and-ftype/

**Comment by linsui** [comment]
You can add a reg file or just a note, see [vscode.json](https://github.com/lukesampson/scoop-extras/blob/master/bucket/vscode.json). Scoop won't pollute registry by default.

**Comment by idbrii** [comment]
Note: assoc + ftype don't seem to work anymore to pass arguments to python and you need to [edit the registry](https://superuser.com/a/669154).
