### ISSUE TITLE
Declarative launcher configuration in manifest

### ISSUE THREAD

**Issue by kostrse** [ScoopInstaller/Scoop#3772]
There's a lot of apps which require external runtime and launcher/interpreter to run:
* portable .NET Core apps (.dll files)
* JVM apps (.jar files)
* Python, Ruby scripts etc.

In most cases these apps require the `pre_install` script with manual creation of the launcher:

```json
{
    "pre_install": "Set-Content -Path \"$dir\\foobar.ps1\" -Value \"python3 '$dir\\foobar.py' @args\"",
    "bin": "foobar.ps1"
}
```

It's verbose and error prone. Different packages may have different variations of the same code with slightly different behavior and side effects. Also, scoop already generates shims, so it becomes shim for another shim.

Would it make sense to introduce some more declarative syntax in the manifest, like:
```json
{
    "bin": {
        "path": "foobar.py",
        "launcher": "python3.exe"
    }
}
```
Ideally the defined launcher configuration could be incorporated directly into the shim.

**Comment by kostrse** [comment]
Related #3769

**Comment by Deide** [comment]
It's possible to use a combination of `bin` and `suggest` or `depends`. See the [wiki](https://github.com/lukesampson/scoop/wiki/App-Manifests).

For example:
```json
"bin": [
  ["java.exe", "cool-app", "-jar $dir\\coolApp.jar"]
],
"suggest": {
  "JRE8": ["java/oraclejre8", "java/openjdk8"]
},
...
```
