### ISSUE TITLE
Version reset example fails

### ISSUE THREAD

**Issue by jeff-hykin** [ScoopInstaller/Scoop#3792]
The error is on a fresh install of Windows 10 inside a VM specifically created for testing python installations

### The example here
https://github.com/lukesampson/scoop/wiki/Switching-Ruby-And-Python-Versions
![Screen Shot 2019-12-11 at 2 38 47 PM](https://user-images.githubusercontent.com/17692058/70658668-0cf4ed80-1c24-11ea-83e8-c62ee14c830c.png)

### Doesn't end up resetting the version
![Screen Shot 2019-12-11 at 2 36 09 PM](https://user-images.githubusercontent.com/17692058/70658703-1e3dfa00-1c24-11ea-95f8-7af81bf4c230.png)

It looks like the scoop apps python.exe is not being reset, and is overriding the shim.

**Comment by r15ch13** [comment]
That's because of the `C:\Users\joe\AppData\Local\Microsoft\WindowsApps\python.exe`.
This is provided by Windows and is loaded last. You need to move `C:\Users\r15ch\AppData\Local\Microsoft\WindowsApps` up in the `PATH` or remove it entirely.

**Comment by jeff-hykin** [comment]
The `C:\Users\joe\AppData\Local\Microsoft\WindowsApps\python.exe` just opens the windows store, it's an exe that ships with windows and isn't actually python.

![Screen Shot 2019-12-12 at 10 35 56 AM](https://user-images.githubusercontent.com/17692058/70730783-3a48a680-1ccb-11ea-9e33-778f5946073a.png)
