### ISSUE TITLE
.ps1 shims cause lots of problems

### ISSUE THREAD

**Issue by JustinGrote** [ScoopInstaller/Scoop#3795]
Are the .ps1 shims really necessary? Aren't they already met by the .cmd and .exe shims?

Often when discovering or trying to run a command, the .ps1 shim gets resolved and breaks. For instance, & (get-command git) you have to know to add -CommandType application to not have it fail.

**Comment by Deide** [comment]
One potential use for .ps1 shims is program documentation with `man`/`Get-Help`, but that's currently not used.

Other than that, I don't know the use either.

**Comment by JustinGrote** [comment]
@r15ch13 would you accept a PR to make .ps1 shims optional? I'd be happy to work on it.

**Comment by Cologler** [comment]
If the target is a `.ps1` script, `.ps1` shims can run on the current PowerShell instance instead of a spawned subprocess.

**Comment by rashil2000** [comment]
Merged in develop branch - #4543
