### ISSUE TITLE
update is no progress

### ISSUE THREAD

**Issue by blowsnowit** [ScoopInstaller/Scoop#3797]
the update is no progress, i can not know this is ok.
![image](https://user-images.githubusercontent.com/34737801/70856999-d23fcd80-1f21-11ea-91cd-a5d40b9c3587.png)

**Comment by blowsnowit** [comment]
i update 20 minutes
i wait for this

**Comment by issaclin32** [comment]
Looks like a network issue. Try run it again later?

If the problem has not been solved, try if `git clone github.com/lukesampson/scoop/` works. **(remember to test this in a directory other than C:\Users\xxx)**

If `git clone github.com/lukesampson/scoop/` does not work, your connection may be blocked by firewall rules or your ISP. You can [use a proxy](https://github.com/lukesampson/scoop/wiki/Using-Scoop-behind-a-proxy) to solve the problem.
