### ISSUE TITLE
Can you add an index to the search?

### ISSUE THREAD

**Issue by blowsnowit** [ScoopInstaller/Scoop#3798]
Can you add an index to the search?
now,the search is so slow when has large bucket

**Comment by linsui** [comment]
https://scoop-docs.now.sh/apps/

**Comment by blowsnowit** [comment]
> https://scoop-docs.now.sh/apps/

no is that, i use 'scoop search xx' is so slow

**Comment by quantuumsnot** [comment]
Searching is slow, yes

**Comment by shilangyu** [comment]
Out of frustration I created a fast drop-in replacement for `scoop search`:

https://github.com/shilangyu/scoop-search

Returns identical output to scoop, just 50 times faster.
