### ISSUE TITLE
multiple files install with scoop?

### ISSUE THREAD

**Issue by yuceltoluyag** [ScoopInstaller/Scoop#3801]
Hi

Can we install multiple files with scoop? for example
scoop install aria2 sublimation

or can we install from the folder? for example

scoop install /myfolder/*.json

this way I'll upload all the json files

**Comment by Calinou** [comment]
> Can we install multiple files with scoop?

Sure, `scoop install aria2 sublimation` should work fine :slightly_smiling_face: 

> or can we install from the folder?

That works too (if your shell expands the glob), but I'd recommend using the bucket approach to benefit from update checks.

**Comment by yuceltoluyag** [comment]
![Scoop](https://i.ibb.co/gPpQt9V/scoop.png "Scoop")
it can be tedious to load long files like this one by one.

**Comment by r15ch13** [comment]
You are using PowerShell so could always fall back to something like this:
```pwsh
Get-ChildItem | ForEach-Object { Invoke-Expression "scoop install $($_.BaseName)" }
```

**Comment by yuceltoluyag** [comment]
would you consider adding this as the default feature ? @r15ch13
