### ISSUE TITLE
[Feature Request] Uninstall package and all dependencies

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [ScoopInstaller/Scoop#3806]
Would be useful for the package or two that has dependencies, minor nitpick though as most do not.

**Comment by ThatNerdyPikachu** [comment]
I did it myself for the time being, not in PowerShell though. See https://github.com/ThatNerdyPikachu/scoop-uninstall-with-deps

**Comment by rashil2000** [comment]
Gonna track this in #4276, i.e. dependency tracking.
