### ISSUE TITLE
[FR] do not install

### ISSUE THREAD

**Issue by Cologler** [ScoopInstaller/Scoop#3807]
I am installed `dotnet-sdk` from visual studio installer.

When I install the package `LINQPad` (depends on `dotnet-sdk`), scoop will auto install  `dotnet-sdk` unless I use `--independent` parameter.

There is no easy way to see if any package depends on `dotnet-sdk` before install.

Can scoop keep a list to auto skip some dependencies?

Maybe a file flag:

```
~\scoop\apps\dotnet-sdk\
    |- DO_NOT_INSTALL <--- a empty file
```

**Comment by Ash258** [comment]
LINQPAD do not depend on dotnet-sdk since 13. December

**Comment by Cologler** [comment]
@Ash258 linqpad and dotnet-sdk just a example here.

**Comment by Ash258** [comment]
Then this is covered in #2217 and related to #3769

**Comment by Cologler** [comment]
> Then this is covered in [#2217](https://github.com/lukesampson/scoop/issues/2217) and related to [#3769](https://github.com/lukesampson/scoop/issues/3769)

I don't think scoop can add a `"provides": ["dotnet.exe"]` to visual studio installer.

**Comment by KScottDB** [comment]
this is a seperate but related problem. cologler is talking about the automatic detection of already installed dependencies that weren't installed from scoop.
e.g. if you install something that requires something like 7-zip which you can install independently of scoop, it shouldn't install 7-zip again.

**Comment by rashil2000** [comment]
#3800
