### ISSUE TITLE
scoop think a download interrupted package as installed

### ISSUE THREAD

**Issue by yetangye** [ScoopInstaller/Scoop#3816]
> Updating 'versions' bucket...
Scoop was updated successfully!
Installing 'ojdkbuild8-full' (1.8.0.232-2.b09) [64bit]
java-1.8.0-openjdk-1.8.0.232-2.b09.ojdkbuild.windows.x86_64.msi (142.8 MB) [>                                               ]   1%
无法从传输连接中读取数据: 远程主机强迫关闭了一个现有的连接。。(connection closed)
URL https://github.com/ojdkbuild/ojdkbuild/releases/download/java-1.8.0-openjdk-1.8.0.232-2.b09/java-1.8.0-openjdk-1.8.0.232-2.b09.ojdkbuild.windows.x86_64.msi is not valid

> ~ $ scoop install ojdkbuild8-full
ERROR It looks like a previous installation of ojdkbuild8-full failed.
Run 'scoop uninstall ojdkbuild8-full' before retrying the install.
WARN  'ojdkbuild8-full' () is already installed.
Use 'scoop update ojdkbuild8-full' to install a new version.

**Comment by linsui** [comment]
It's a connection issue. Please try again.

`scoop uninstall ojdkbuild8-full; scoop install ojdkbuild8-full`

**Comment by yetangye** [comment]
I mean scoop should not recognize a download interrupted package as installed.

**Comment by lisonge** [comment]
+1
scoop should not recognize a download interrupted package as installed.
it always make me distressed

**Comment by niheaven** [comment]
Fixed in #3281
