### ISSUE TITLE
$basename doesn't ignore fragments when the file has no extension

### ISSUE THREAD

**Issue by MCOfficer** [ScoopInstaller/Scoop#3823]
I have the following (nonsensical) autoupdate snippet:
```
"url": "https://github.com/pomerium/pomerium/releases/download/v$version/pomerium-windows-amd64#/pomerium.exe",
"hash": {
    "url": "$basename.sha256",
    "find": "^([a-fA-F0-9]{32,128}).*$basename$"
}
```

the way i read [the docs](https://github.com/lukesampson/scoop/wiki/App-Manifest-Autoupdate#url-variables), scoop should check for hashes in the file `pomerium-windows-amd64.sha256`.

Instead, what it does is this:
```
.\bin\checkver.ps1 -f pomerium
pomerium: 0.5.2 (scoop version is 0.5.2)
Forcing autoupdate!
Autoupdating pomerium
Searching hash for pomerium.exe in pomerium.exe.sha256
```

[Here](https://github.com/MCOfficer/scoop-bucket/blob/master/bucket/pomerium.json)'s the actual manifest to play around with.

**Comment by Ash258** [comment]
`$basename` is name of file.

![image](https://user-images.githubusercontent.com/13260377/72622570-c5a8fd80-3943-11ea-832e-857ac679c76e.png)

You need to use `$baseurl`

**Comment by MCOfficer** [comment]
> 
> 
> `$basename` is name of file.
> 
> ![image](https://user-images.githubusercontent.com/13260377/72622570-c5a8fd80-3943-11ea-832e-857ac679c76e.png)
> 
> You need to use `$baseurl`

i know, the manifest doesn't make sense -  i just needed a way to print out `$basename`. 

The issue is that $basename should be `pomerium-windows-amd64` (the actual filename), but it is `pomerium.exe` (the fragment).

**Comment by Ash258** [comment]
That is why you have debug ...

![image](https://user-images.githubusercontent.com/13260377/72622696-0d2f8980-3944-11ea-8cfe-3e9f26afe174.png)

**Comment by Ash258** [comment]
It is working if filename have extension.
