### ISSUE TITLE
Do not use `dl` as a name for function

### ISSUE THREAD

**Issue by jetersen** [ScoopInstaller/Scoop#3830]
`dl` is terrible function name for downloading files scoop that can leak into profile alias

**Comment by Ash258** [comment]
#3149 Downloading refactor / unify

**Comment by rashil2000** [comment]
Files and line numbers using the `dl` function:
```
lib/install.ps1    134, 376, 420
lib/core.ps1       466
bin/install.ps1    47, 64
```

**Comment by examosa** [comment]
@rashil2000 I think this can be closed now.
