### ISSUE TITLE
When intall scoop, system indicated that scoop.zip was accessed by another process!!!

### ISSUE THREAD

**Issue by HUGO-BEIJING** [ScoopInstaller/Scoop#3833]
PS C:\Users\hujf> Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
Initializing...
Downloading scoop...
Extracting...
Remove-Item : 无法删除项 C:\Users\hujf\scoop\apps\scoop\current\scoop.zip: 文件“C:\Users\hujf\scoop\apps\scoop\current\scoop.zip”正由另一进程使用，因此该进程无
法访问此文件。
所在位置 行:53 字符: 1
+ Remove-Item "$dir\_tmp", $zipfile -Recurse -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\hujf\s...rrent\scoop.zip:FileInfo) [Remove-Item], IOException
    + FullyQualifiedErrorId : RemoveFileSystemItemIOError,Microsoft.PowerShell.Commands.RemoveItemCommand
![scoop](https://user-images.githubusercontent.com/48665434/73373415-8b504080-42f3-11ea-802b-c821ed94056a.png)

**Comment by Ash258** [comment]
The most probably your Antivirus was scanning the file for potential problems.
