### ISSUE TITLE
I tried to make a scoop app store

### ISSUE THREAD

**Issue by trizau** [ScoopInstaller/Scoop#3841]
website is https://scoop.ccheng.live

**Comment by Ash258** [comment]
https://scoop-docs.now.sh/apps/

**Comment by rasa** [comment]
I *love* the background logo/graphic!

**Comment by rashil2000** [comment]
> website is https://scoop.ccheng.live

No longer reachable :( 

Is it open source?

**Comment by trizau** [comment]
It is still available at https://scoop.if-she.com

**Comment by rashil2000** [comment]
Can we see the source? How does it generate an index? Which apps does it index?

**Comment by trizau** [comment]
It just reads what's on https://raw.githubusercontent.com/rasa/scoop-directory/master/by-apps.md, maybe you should try https://scoopsearch.github.io/#/apps, or [winget](https://docs.microsoft.com/en-us/windows/package-manager/winget/)
