### ISSUE TITLE
7zip is detected as a potential error

### ISSUE THREAD

**Issue by shepherdless** [ScoopInstaller/Scoop#3844]
7zip is detected as a potential error even if 7zip is installed locally on my machine without the use of scoop. I think there should be a fix to this. 

`ERROR '7-Zip' is not installed! It's required for unpacking most programs. Please Run 'scoop install 7zip' or 'scoop install 7zip-zstd'.`

When this statement is false.

**Comment by linsui** [comment]
```
7ZIPEXTRACT_USE_EXTERNAL: $true\$false
External 7zip (from path) will be used for archives extraction.
```

**Comment by WanderingRonin** [comment]
There are issues with it, still...

**Comment by niheaven** [comment]
If there is still an issue, please reopen it.
