### ISSUE TITLE
GitHub API rate limiting

### ISSUE THREAD

**Issue by g2p** [ScoopInstaller/Scoop#3853]
While running scoop search multiple times, I've hit GitHub's API rate limit.

The message looks like this on scoop stderr:
```
invoke-webrequest : {"message":"API rate limit exceeded for IPADDRESS. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation    for more details.)","documentation_url":"https://developer.github.com/v3/#rate-limiting"}
```

`curl.exe -i https://api.github.com/` confirms it's a [60 req/hour limit](https://developer.github.com/v3/#rate-limiting) that's been hit.

Is there a way to authenticate with GitHub and get a bit more quota?

**Comment by mmelvin0** [comment]
Just ran into this and it seems like this can be accomplished with GithHub personal access tokens.

Would need to add something like this:

```
-Headers @{'Authorization' = 'token 2c1f9ee43d3806184b4d6717a31d394bb07037b1'}
```

To the the Invoke-WebRequest call here: https://github.com/lukesampson/scoop/blob/a9fa775d59b14e7dce335313faa0eff855469764/libexec/scoop-search.ps1#L52
