### ISSUE TITLE
[Question/Feature Request] Redirecting a package URL

### ISSUE THREAD

**Issue by silverkorn** [ScoopInstaller/Scoop#3858]
Hi,

We have a situation at my office in which the firewall is blocking dangerous domains.
A concrete example is our case is PuTTY and the other security tools (from the `extras` bucket) where the official URL is hosted on "the.earth.li", known to be blacklisted on many security softwares and devices.

Unfortunately, they cannot allow a whitelisting for this domain for obvious security reasons and their devices cannot redirect to one of their official mirrors, at least, not from an URL prefix.

This said, is there a way, potentially with `scoop config`, to redirect a package URL to another one with scoop?

If not, could I suggest some kind of local configuration that could redirect an URL to another one?
Maybe something like one of the following (Maybe as a RegExp compatible):

- A single key with a JSON value containing a dictionary of all redirections:
  - `scoop config redirections "{""https://the.earth.li/~sgtatham/putty/"":""https://www.puttyssh.org/"", ""https://www.test.com/"": ""https://www.test.org/""}"`

- A key per redirection with a JSON value for a single dictionary :
  - `scoop config redirection.1 "{""https://the.earth.li/~sgtatham/putty/"":""https://www.puttyssh.org/""}"`
     `scoop config redirection.2 "{""https://www.test.com/"":""https://www.test.org/""}"`

- A key per redirection prefixed by something like "redirect:" then a single value  <sup>(Seems to save properly with current version)</sup>:
  - `scoop config redirect:https://the.earth.li/~sgtatham/putty/ https://www.puttyssh.org/`
    `scoop config redirect:https://www.test.com/ https://www.test.org/`

Thanks!

**Comment by rashil2000** [comment]
#4264
