### ISSUE TITLE
"The variable '$scoopConfig' cannot be retrieved because it has not been set"

### ISSUE THREAD

**Issue by MarkMichaelis** [ScoopInstaller/Scoop#3859]
When I try to install Scoop, I get the error, "The variable '$scoopConfig' cannot be retrieved because it has not been set."  I have tried on two different computers from an Administrator instance of PowerShell.

```
iwr -useb get.scoop.sh | iex
```
The output I see is:

> Initializing...
> Invoke-Expression : The variable '$scoopConfig' cannot be retrieved because it has not been set.
> At line:33 char:1
> \+ Invoke-Expression (new-object net.webclient).downloadstring($core_url ...
> \+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidOperation: (scoopConfig:String) [Invoke-Expression], RuntimeException
>     + FullyQualifiedErrorId : VariableIsUndefined,Microsoft.PowerShell.Commands.InvokeExpressionCommand
> 

Note: The same issue is reported in #3477 but closed with the recommendation to use the standalone installer.

**Comment by thorstenkampe** [comment]
@MarkMichaelis , any chance you enabled strict mode (`Set-StrictMode -Version latest`)?

**Comment by MarkMichaelis** [comment]
@thorstenkampe, Yes, I invoke `Set-StrictMode -version latest` from my profile.

**Comment by thorstenkampe** [comment]
@MarkMichaelis , so do I. Do `Set-Strictmode -Off` during installation.

**Comment by rashil2000** [comment]
#3626
