### ISSUE TITLE
Add Language option during install

### ISSUE THREAD

**Issue by graphixillusion** [ScoopInstaller/Scoop#3864]
I've searched around but i didn't find anything related. By default scoop install the english version of the specified app: is it possible to change this behaviour adding an option to specify which languages version you want to download/install? It would be very usefull with multilanguage's apps like firefox. Something like

**scoop install firefox --lang xx-XX**

or whatever you like... thank you

**Comment by Calinou** [comment]
Most apps only distribute a single installer/ZIP archive containing all languages. However, some large applications like Firefox distribute one installer per language. It's very difficult to support both in a consistent manner, so I don't think this would be worthwhile to implement.
