### ISSUE TITLE
How to install latest ssh through scoop?

### ISSUE THREAD

**Issue by yfxwardy** [ScoopInstaller/Scoop#3873]
https://www.openssh.com/portable.html
I don't understand who care about main bucket and who control it?
**Does it refer to official app repos or bucket's author have to prepare own repo and installation code for each app?**
Who and how often updates app version in scoop buckets?

How can I install app that are not in known scoop buckets?

**Comment by Deide** [comment]
[This github repo](https://github.com/ScoopInstaller/Main) is the main bucket. The bucket directory contains text files called manifests that describe where and how to download and install applications. These manifests are updates programmatically for the most part, with fields called `checkver` and `autoupdate` in each manifest.

You can create a custom manifest and just `scoop install <path to manifest>`, or you can create a custom bucket filled with multiple manifests and add that bucket to your scoop installation. Many people create [third party buckets](https://github.com/rasa/scoop-directory/blob/master/by-date-updated.md).

For further information, refer to the [wiki](https://github.com/lukesampson/scoop/wiki).

**Comment by Robespeler** [comment]
@Deide Thanks
I have read wiki autoupdate and checkvers and seen several manifests. 

I tried to execute .\bin\checkver.ps1 * command in powershell and get checkver list I suppose.
Obviously, there are no checkver and autoupdate in openssh.json
openssh manifest in main bucket is rather different than others and rather difficult for me to prepare correct new one manifest.

I am looking for something folk good solution.
What's the problem with openssh and other such apps? Why author or somebody goodman can't integrate checkver and autoupdate feauture? I try to figure it out to understand do I need to try update manifest and do pull request.
I saw that official repo is specific but there is also the github mirror

**Comment by Deide** [comment]
In the `openssh` case, it's updated manually. It's the msys2 OpenSSH. If you can work out a sensible checkver and autoupdate, by all means submit a pull request.

It's worth mentioning that Windows 10 comes with OpenSSH these days, and if not enabled, can usually be enabled under Optional Features. If it's more desirable to use a scoop managed version, I would recommend `win32-openssh`, which _does_ have checkver and autoupdate. It is a port, so it's not entirely equal.

Maybe [this website](https://scoop.netlify.com/) will be useful to you.
