### ISSUE TITLE
Is it possible to install Scoop itself globally, for all users?

### ISSUE THREAD

**Issue by tutume** [ScoopInstaller/Scoop#3875]
I would like to be able to install scoop itself globally making it possible to install scoop once and any use account on my computer could use same scoop installation, are there any ways to do that?

By now I can do almost everything that I tried, but I have to install scoop for each user.

Example of how I would like it to work:

```bash
C:\Users\AdminUser>
irw get.scoop.sh/g | iex
scoop bucket add versions -g
scoop install sudo -g
scoop install python37 python -g
scoop install python36 python # local
scoop firefox
scoop list
> python 3.7 *global*
> python36 3.6 [versions]
> firefox
```
```bash
C:\Users\UserB>
scoop install python
scoop install python27 python
scoop googlechorme
scoop list
> python *global*
> python27  2.7 [versions]
> googlechrome 80
scoop reset python37 python
```

**Comment by vvuk** [comment]
To add to this -- I'd love to have a way to set "global" as the default (erroring out if `sudo` is not used), with an explicit `-u` needed for a user install.  I'm "all" of the users on my machine (personal user, work user) and would prefer to have everything be global so I don't accidentally install something local.

**Comment by rashil2000** [comment]
You can try this #4424 

But there's a listing bug (does not seem to affect functionality).

**Comment by rashil2000** [comment]
_From @contigon in #3624:_

> ```powershell
> $env:SCOOP_GLOBAL='c:\GlobalScoopApps';[Environment]::SetEnvironmentVariable('SCOOP_GLOBAL', $env:SCOOP_GLOBAL, 'Machine')
> $env:SCOOP='c:\Scoop';[Environment]::SetEnvironmentVariable('SCOOP', $env:SCOOP, 'MACHINE');iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
> $Reg='Registry::HKLM\System\CurrentControlSet\Control\Session Manager\Environment';$OldPath=(Get-ItemProperty -Path $Reg -Name PATH).Path;$NewPath=$OldPath+';'+'c:\Scoop\shims';Set-ItemProperty -Path $Reg -Name PATH -Value $NewPath
>  $CurrentValue=[Environment]::GetEnvironmentVariable('PSModulePath','Machine') ;[Environment]::SetEnvironmentVariable('PSModulePath', $CurrentValue + ';c:\Scoop\modules', 'Machine')}"
> ```

**Comment by MNLierman** [comment]
I just wanted to say, that although this was 3 yrs ago, Google and Bing prefer showing this result at the top of the list, so because of the high visibility, this was one of the first attempts I made and it didn't work. I also would advise anyone looking to do this to install into Program Files, not the root of the C drive. Either way, this command needed some changes. The syntax isn't even correct, It has an extra quote and bracket and there is no start `{`. The code as is cannot be used. Furthermore, it would be better to allow the user to customize the path and use a variable.

I have corrected the code, and the below should work just fine. It also needs to be run as admin, and the allow admin switch was missing. You cannot install this globally without the admin switch.

```
$scoopPath="C:\Program Files\Scoop";
$env:SCOOP_GLOBAL='$scoopPath\GlobalApps';[Environment]::SetEnvironmentVariable('SCOOP_GLOBAL', $env:SCOOP_GLOBAL, 'Machine')
$env:SCOOP='$scoopPath';[Environment]::SetEnvironmentVariable('SCOOP', $env:SCOOP, 'MACHINE'); iex "& {$(irm get.scoop.sh)} -RunAsAdmin"
$Reg='Registry::HKLM\System\CurrentControlSet\Control\Session Manager\Environment';$OldPath=(Get-ItemProperty -Path $Reg -Name PATH).Path;$NewPath=$OldPath+';'+'$scoopPath\shims';Set-ItemProperty -Path $Reg -Name PATH -Value $NewPath
$CurrentValue=[Environment]::GetEnvironmentVariable('PSModulePath','Machine') ;[Environment]::SetEnvironmentVariable('PSModulePath', $CurrentValue + ';$scoopPath\modules', 'Machine')
```

**Comment by dyllan-to-you** [comment]
Just ran this script on Windows 10 Pro with some changes to get it to work. Main changes:
- Using `C:\ProgramData\scoop` for the global scoop directory to conform with defaults
- fix string concatenationi/quoting around `$scoopPath` for the Path and PSModulePath updates. Powershell didn't seem to expand the variable correctly within the string.

```ps
$scoopPath="C:\Program Files\Scoop";
$env:SCOOP_GLOBAL='C:\ProgramData\scoop';[Environment]::SetEnvironmentVariable('SCOOP_GLOBAL', $env:SCOOP_GLOBAL, 'Machine')
$env:SCOOP=$scoopPath;[Environment]::SetEnvironmentVariable('SCOOP', $env:SCOOP, 'MACHINE'); iex "& {$(irm get.scoop.sh)} -RunAsAdmin"
$Reg='Registry::HKLM\System\CurrentControlSet\Control\Session Manager\Environment';$OldPath=(Get-ItemProperty -Path $Reg -Name PATH).Path;$NewPath=$OldPath+';'+$scoopPath+'\shims';Set-ItemProperty -Path $Reg -Name PATH -Value $NewPath
$CurrentValue=[Environment]::GetEnvironmentVariable('PSModulePath','Machine');[Environment]::SetEnvironmentVariable('PSModulePath', $CurrentValue + ';'+$scoopPath+'\modules', 'Machine')
```

**Comment by SorYoshino** [comment]
Hello, @MNLierman @dyllan-to-you. There are some issues with the code you provided. In PowerShell, strings enclosed in single quotes `'...'` are treated as **literal strings**, meaning **variables and escape characters will not be expanded or interpreted**. This can lead to incorrect behavior when setting environment variables.

Furthermore, according to the latest Scoop installation documentation, [**it is no longer recommended to install Scoop by manually setting environment variables**](https://github.com/ScoopInstaller/Install/blob/ff4eedda58d832b8225d7697510f097ebe8ab071/README.md?plain=1#L50-L57). Using [this script](https://gist.github.com/SorYoshino/c55ce1de6a8032a0bcd6975ad57db5f3) achieves the same goal and complies with current best practices.
<br>

You can customize the installation path by modifying the following three variables.

```powershell
$scoopPath = "C:\Software\Scoop"
$localPath = "$scoopPath\Local"
$globalPath = "$scoopPath\Global"
```
<br>

The script execution process is as follows:

```powershell
PS C:\Users\WDAGUtilityAccount\Desktop> .\Install-Scoop.ps1
Initializing...
Downloading...
Extracting...
Creating shim...
Adding C:\Software\Scoop\Local\shims to your path.
Scoop was installed successfully!
Type 'scoop help' for instructions.

VERBOSE: Getting current value of environment variable 'Path' at scope 'Machine'.
VERBOSE: Current values: C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\
VERBOSE: Adding 'C:\Software\Scoop\Local\shims' to 'Path'.
Added 'C:\Software\Scoop\Local\shims' to Machine environment variable 'Path'.
VERBOSE: Getting current value of environment variable 'PSModulePath' at scope 'Machine'.
VERBOSE: Current values: C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules
VERBOSE: Adding 'C:\Software\Scoop\Local\modules' to 'PSModulePath'.
Added 'C:\Software\Scoop\Local\modules' to Machine environment variable 'PSModulePath'.
```
<br>

If you need to add other paths to a specific system environment variable, simply replace `$variableName` and `$path` in the code below with the appropriate variable name and path.

```powershell
Add-ToEnvironmentPath -VariableName $variableName -NewEntry $path -Scope "Machine"
```
