### ISSUE TITLE
scoop bash shim broken if Windows username contains spaces

### ISSUE THREAD

**Issue by shenker** [ScoopInstaller/Scoop#3878]
My Windows home directory contains a space, `C:\Users\Firstname Lastname`. When I try to run scoop in Git Bash, I get:
```
C:\Users\Firstname: The term 'C:\Users\Firstname' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

In `~/scoop/shims/scoop` I have:
```
#!/bin/sh
powershell.exe -noprofile -ex unrestricted "C:\Users\Firstname Lastname\scoop\apps\scoop\current\bin\scoop.ps1"  "$@"
```
If I change the double quotes to single quotes and add a backtick to escape the space, it works:
```
#!/bin/sh
powershell.exe -noprofile -ex unrestricted 'C:\Users\Firstname` Lastname\scoop\apps\scoop\current\bin\scoop.ps1'  "$@"
```

Note that this does not fix handling of paths containing spaces in arguments to scoop, which is broken even in powershell (see #3561).

**Comment by shenker** [comment]
`code ~/scop/shims/scoop` and change to the following (substituting your Windows username for `Firstname Lastname`):
```
#!/bin/sh
powershell.exe -noprofile -ex unrestricted 'C:\Users\Firstname` Lastname\scoop\apps\scoop\current\bin\scoop.ps1' "$@"
```

**Comment by jontaylor224** [comment]
I am also having this same issue because my user home directory contains a space
