### ISSUE TITLE
Improve install command and aria2 download

### ISSUE THREAD

**Issue by crushglass** [ScoopInstaller/Scoop#3881]
1. Sometimes the network status is bad and install failed. When I restart the install, scoop prompts that 'software'  is already installed. So I must uninstall software and then reinstall it, and the download progress is reset to 0. It is really not good feel, when installing some large size software. Can we have an reinstall command, just like "scoop reinstall something" or "scoop install something -r" to make installation progress continue? aria2 can resume download from breakpoint.

2. aria2 can download from different urls. I think we can set more than one download url in config json to increase download speed and reduce download fail, like "urls: url1, url2, ..."

**Comment by Calinou** [comment]
1. is already being tracked in #3816.

As for 2., I'm not sure if this is a good idea as not all servers may have the latest version available for a given package. Moreover, some servers may be located far away from the user, which will translate to lower download speeds.

**Comment by crushglass** [comment]
When I use scoop to download software from github, the url often redirects to "s3.amazonaws.com". I can't get good download speed from "s3.amazonaws.com" and downloads often failed. So I use aria2 download software as a scoop cache from more than one release url and install it. It's always work. The download speed is getting faster. aria2 chooses faster server for me.

 Many softwares have more than one distribution server. If url configuration item is an array, when the software only one server for distribution we can set it like "url":["url1"]; when the software has more than one server for distribution we can set it like "url":["url1", "url2", "url3", ...].
