### ISSUE TITLE
Ability to add more complex alias

### ISSUE THREAD

**Issue by kid1412621** [ScoopInstaller/Scoop#3885]
such as: 
`scoop alias ls` -> `scoop alias list`
I've tried `scoop alias add 'alias ls' 'scoop alias list'`, but it will only work when I type `scoop 'alias ls'`.

And another support feature I want is flag. like:
`scoop rm -g` -> `scoop uninstall -g`

**Comment by linsui** [comment]
```
# Usage: scoop alias add|list|rm [<args>]
# Summary: Manage scoop aliases
# Help: Add, remove or list Scoop aliases
#
# Aliases are custom Scoop subcommands that can be created to make common tasks
# easier.
#
# To add an Alias:
#     scoop alias add <name> <command> <description>
#
# e.g.:
#     scoop alias add rm 'scoop uninstall $args[0]' 'Uninstalls an app'
#     scoop alias add upgrade 'scoop update *' 'Updates all apps, just like brew or apt'
#
# Options:
#   -v, --verbose   Show alias description and table headers (works only for 'list')
```

`scoop alias add ls 'scoop list'`

**Comment by Ash258** [comment]
Aliases could be as complex as you need. It is only powershell script. You can handle everything when you know powershell

![A](https://i.imgur.com/6Mizqas.png)

**Comment by kid1412621** [comment]
> Aliases could be as complex as you need. It is only powershell script. You can handle everything when you know powershell
> 
> 
> 
> ![A](https://i.imgur.com/6Mizqas.png)
> 
> 
> 
> Just create new alias file `scoop alias add whatever '#TODO:' 'Awesome custom script'` and then edit it

Thx, but I think a simple command for a shell file is way too heavy.

**Comment by leni8ec** [comment]
> And another support feature I want is flag. like:
> `scoop rm -g` -> `scoop uninstall -g`

I support this idea - it's very uncomfortable without it..
