### ISSUE TITLE
ps1 shims for git are reseting $? PowerShell variable

### ISSUE THREAD

**Issue by Demivan** [ScoopInstaller/Scoop#3890]
Shims for `git` package are breaking GitLab runner. When runner tries to fetch git repo it checks for exit code of git but shims are resetting `$?` variable.
So even if git command fails `$?` will report no error.

**Comment by AndrewSav** [comment]
It's not just for git. Many other shims do that too, which is not surprising, since it's the same basic shim...

**Comment by rashil2000** [comment]
Merged in develop branch - #4543
