### ISSUE TITLE
Unable to install older versions of python using scoop

### ISSUE THREAD

**Issue by ElizabethVincent261190** [ScoopInstaller/Scoop#3899]
Unable to install older versions of python using scoop. 
The issue occurs when running: 

`scoop install python@3.5.2`

This results in: 
```
WARN  Given version (3.5.2) does not match manifest (3.8.2)
WARN  Attempting to generate manifest for 'python' (3.5.2)

```
This creates a folder called 3.5.2. 
Within this it installed python version 3.8.2 and does not install version 3.5.2.

This is not limited to python version 3.5.2. 
When I have tried other versions, I get similar warnings as above. It then creates a folder for the version number (for example, 3.7.7) and then installs 3.8.2. 

I am running windows 10 and do not have admin permissions.

**Comment by shenbo** [comment]
add `versions` bucket :
```
scoop bucket add versions
scoop search python
```

then try:
```
scoop install python35      # the latest version is 3.5.4

# or
scoop install python35@3.5.2 
```

**Comment by h0lg** [comment]
If you need a version of an app not in the versions bucket, try [this approach](https://github.com/lukesampson/scoop/issues/3933#issuecomment-744043576).

**Comment by sebma** [comment]
@shenbo Do you have an idea why this does not work : 
```pwsh
PS> sudo scoop install -g python38@3.8.9
WARN  Given version (3.8.9) does not match manifest (3.8.10)
WARN  Attempting to generate manifest for 'python38' (3.8.9)
Autoupdating python38
Searching hash for python-3.8.9.exe in https://www.python.org/downloads/release/python-389/
Found: md5:1b5456a52e2017eec31c320f0222d359 using Extract Mode
Searching hash for python-3.8.9-amd64.exe in https://www.python.org/downloads/release/python-389/
Found: md5:f69d9c918a8ad06c71d7f0f26ccfee12 using Extract Mode
Writing updated python38 manifest
Installing 'python38' (3.8.9) [64bit]
python-3.8.9-amd64.exe (26,9 MB) [=============================================================] 100%
Checking hash of python-3.8.9-amd64.exe ... ok.
Running installer... error.
ERROR Exit code was 1603!
Installation aborted. You might need to run 'scoop uninstall python38' before trying again.
```

**Comment by sebma** [comment]
#4351

**Comment by sebma** [comment]
#4351

**Comment by sebma** [comment]
@rashil2000 The workaround **[ERROR Exit code was 1603!](https://github.com/ScoopInstaller/Main/discussions/2801)** does not fix the error `1603` in my case, please re-open.
