### ISSUE TITLE
Feature request: Remove multiple apps from cache, be verbose

### ISSUE THREAD

**Issue by ddubson** [ScoopInstaller/Scoop#3904]
Current behavior of `scoop cache` is that you can view all the cached downloads all at once, and have the ability to remove each cached download individually via `scoop cache rm [name-of-app]`.

In order to expedite clearing of the cache, it would be great to extend the functionality of `scoop cache rm` to be able to remove multiple apps at once, instead of a single one.

Currently, if you provide multiple apps to the `rm` command, only the first app in the parameter list is cleared.

**Comment by Playacem** [comment]
You can run `scoop cache rm *` to clean the cache completely.

**Comment by Deide** [comment]
In the meantime, if you want to remove multiple (chosen apps) in one command in Powershell, you can make a list and pipe it to a `ForEach-Object`. For example: `@("app-one", "app-two", "app-three") | ForEach-Object { scoop cache rm $_ }`.

**Comment by ddubson** [comment]
@Playacem was not aware of the `*` option, very useful!

@Deide Thanks for the tip! I'll use that in the meantime.

**Comment by rashil2000** [comment]
_From @tukanos in #4400:_ 

> I tried to clean-up the old cache but it virtually gives no information on what is happening.
> 
> * For example:
> 
> I had about 10 vivaldis' installators.
> 
> * When I entered:
> 
> `scoop cleanup --cache vivaldi`
> 
> I got only `vivaldi is already clean` message. No message what was removed or that actually something happened. I had to check manually.
> 
> * What I would expect:
> 
> Is to get list of deleted vivaldis' exe files from cache.
