### ISSUE TITLE
Cannot install mysql

### ISSUE THREAD

**Issue by hirushacooray** [ScoopInstaller/Scoop#3913]
Hello there,

I just installed scoop and trying to install some apps but I cannot install mysql. Every time I ran the command, I get the following error.

C:/Users/Hirusha/scoop/shims/mysqld.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory

Any idea what this means?

Thanks

**Comment by rashil2000** [comment]
Reopen if this issue still occurs in latest version. Also, such issue should be reported in the https://github.com/ScoopInstaller/Main repo
