### ISSUE TITLE
FIPS issue

### ISSUE THREAD

**Issue by PipeItToDevNull** [ScoopInstaller/Scoop#3914]
```
❯ scoop install lf vim
Installing 'lf' (r13) [64bit]
Loading lf-windows-amd64.zip from cache
Checking hash of lf-windows-amd64.zip ... ok.
Extracting lf-windows-amd64.zip ... done.
Linking ~\terminus\bin\scoops\apps\lf\current => ~\terminus\bin\scoops\apps\lf\r13
Creating shim for 'lf'.
'lf' (r13) was installed successfully!
Installing 'vim' (8.2) [64bit]
Loading gvim82.exe from cache
Checking hash of gvim82.exe ... ERROR Exception calling ".ctor" with "0" argument(s): "This implementation is not part of the Windows Platform FIPS valida
ted cryptographic algorithms."
ERROR Hash check failed!
App:         main/vim
URL:         https://ftp.nluug.nl/pub/vim/pc/gvim82.exe#/dl.7z
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    aa84543492cd8260f44a5acf1ec35641
Actual:

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=vim%408.2%3a+hash+check+failed
```

**Comment by Calinou** [comment]
Which Windows version are you using? Also, are you using specific security settings on Windows?

**Comment by PipeItToDevNull** [comment]
Windows 10 pro v1909

FIPS is enabled on the machine via registry. Oddly though disabling FIPS did not remove the error. Normally flipping the registry value resolves issues immediately.

**Comment by PipeItToDevNull** [comment]
I had to flip the key and restart my entire terminal for some reason.

I am not sure whose side this FIPS error is though. It would be nice for there to be no FIPS check if compliance is not possible.

**Comment by PipeItToDevNull** [comment]
Issue is still present in 120. Checking for FIPS is a choice something is making, if compliance is not possible then not checking would be simple fix here. I am not sure if a Lib is being used that may be doing the check instead of Scoop directly.

**Comment by johnallers** [comment]
There's really no good reason to have FIPS enabled on Windows, other than "my company is making me do it".

If that's the case, certain crypto operations will fail. This is enforced by the operating system. In this instance, the usage of MD5 for hashing is considered non-compliant. I would expect it to fail on both lines 691 and 695 here:
https://github.com/lukesampson/scoop/blob/3d67b7d37c4a2714e8942724d4677dcbd3678f01/lib/install.ps1#L690-L697

Ideally, we could just use a modern hash like SHA256, but it looks like gvim only provides MD5.

Another alternative is to skip the hash check, which you should already be able to do with the `--skip` parameter. @PipeItToDevNull Does that not work for you?
