### ISSUE TITLE
scoop update 7zip cause an error «URL https://7-zip.org/a/7z1900-x64.msi is not valid»

### ISSUE THREAD

**Issue by avgolubev** [ScoopInstaller/Scoop#3918]
Executing 
$scoop update 7zip
cause an error «URL https://7-zip.org/a/7z1900-x64.msi is not valid»
This error occurs because this URL is blocked on the territory of Russia, although I do not understand the meaning of this blocking. 
Maybe you should somehow change this URL to an alternative or there is no other address for installing 7zip?

**Comment by r15ch13** [comment]
Try installing `7zip-zstd`

**Comment by Robespeler** [comment]
> 
> 
> Try installing `7zip-zstd`
```
scoop install 7zip-zstd
Scoop uses Git to update itself. Run 'scoop install git' and try again.
Couldn't find manifest for '7zip-zstd'.
```

**Comment by r15ch13** [comment]
Sorry, forgot that it's in the versions bucket.
Try `scoop install https://raw.githubusercontent.com/ScoopInstaller/Versions/master/bucket/7zip-zstd.json` that should work.

**Comment by avgolubev** [comment]
@r15ch13 if i run `scoop install https://raw.githubusercontent.com/ScoopInstaller/Versions/master/bucket/7zip-zstd.json` i get URL `https://7-zip.org/a/7z1900-x64.msi is not valid`
@Robespeler if i run `scoop install 7zip-zstd` i get `Couldn't find manifest for '7zip-zstd'.`

**Comment by r15ch13** [comment]
`7zip-zstd` is packed and it also requires 7zip. Dang it. 😐

Is the IP of 7-zip.org (159.65.89.65) completely unreachable for you? Could an entry in the `hosts` file fix this?

**Comment by r15ch13** [comment]
You could download the `7z1900-x64.msi` from https://sourceforge.net/projects/sevenzip/files/7-Zip/19.00/, put it in the `~\scoop\cache\` directory and call it `7zip#19.00#https_7-zip.org_a_7z1900-x64.msi`

**Comment by Robespeler** [comment]
> i get `https://7-zip.org/a/7z1900-x64.msi is not valid`

This is because of scoop trying to install usual 7zip first and we get the same error.
If you try this command one more time maybe you get success, but this is what I had:
```
Installing '7zip-zstd' (19.00-v1.4.4-R3) [64bit]
7z19.00-zstd-x64.exe (2.3 MB) [===============================================================================] 100%
Checking hash of 7z19.00-zstd-x64.exe ... ok.
Extracting dl.7z ... Invoke-ExternalCommand : Cannot validate argument on parameter 'FilePath'. The argument is null or empty. Provide an
argument that is not null or empty, and then try the command again.
At D:\scoop\apps\scoop\current\lib\decompress.ps1:81 char:38
+     $Status = Invoke-ExternalCommand $7zPath $ArgList -LogPath $LogPa ...
+                                      ~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-ExternalCommand], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Invoke-ExternalCommand

git : The term 'git' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ git config --get remote.origin.url
+ ~~~
    + CategoryInfo          : ObjectNotFound: (git:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Failed to extract files from D:\scoop\apps\7zip-zstd\19.00-v1.4.4-R3\dl.7z.
Log file:
  D:\scoop\apps\7zip-zstd\19.00-v1.4.4-R3\7zip.log
```

But I want to know what are we doing here? Problem with 7zip was one year later. Is it official solution or just some user help. I feel very bad now to realize this. From both sides: country blocking politics and scoop devs reaction. How can it be? So much time and nobody cares

**Comment by Robespeler** [comment]
Sorry, I somehow missed two last responses.

@r15ch13 Could you clarify please. Is there any official correct solution? I don't understand. There were so many closed issues here [https://github.com/lukesampson/scoop/pull/3399](https://github.com/lukesampson/scoop/pull/3399 ) and what? How did it end?

**Comment by Robespeler** [comment]
> You could download the `7z1900-x64.msi` from https://sourceforge.net/projects/sevenzip/files/7-Zip/19.00/, put it in the `~\scoop\cache\` directory and call it `7zip#19.00#https_7-zip.org_a_7z1900-x64.msi`

What is the strange syntax? 7zip#19.00#https_7-zip.org_a_7z1900-x64.msi
Do you mean manually launch execute file or use some command?

**Comment by dmi3mis** [comment]
Hi!
It seems to me that site www.7-zip.org is blocked in Russia.
Everyone can check, https://isitblockedinrussia.com/?host=7-zip.org
I had changed download link in \scoop\buckets\main\bucket\7zip.json from blocked https://7-zip.org/a/7z1900-x64.msi to https://sourceforge.net/projects/sevenzip/files/7-Zip/19.00/7z1900-x64.msi/download
====
        "64bit": {
            "url": "https://sourceforge.net/projects/sevenzip/files/7-Zip/19.00/7z1900-x64.msi/download",
            "hash": "a7803233eedb6a4b59b3024ccf9292a6fffb94507dc998aa67c5b745d197a5dc"
        },
        "32bit": {
            "url": "https://sourceforge.net/projects/sevenzip/files/7-Zip/19.00/7z1900.msi/download",
            "hash": "b49d55a52bc0eab14947c8982c413d9be141c337da1368a24aa0484cbb5e89cd"
        }

It seems to me that 7zip msi now downloading but i got an error at last.

PS C:\> sudo scoop install 7zip
Installing '7zip' (19.00) [64bit]
7z1900-x64.msi (1.7 MB) [===========================================================================================================================================================] 100%
Checking hash of download ... ok.
Linking ~\scoop\apps\7zip\current => ~\scoop\apps\7zip\19.00
Creating shim for '7z'.
Can't shim '7z.exe': File doesn't exist.

Can anyone explain me what to do next?

**Comment by r15ch13** [comment]
@Robespeler 

No there is not official solution to this. 
By downloading the file manually and moving it to the cache directory it is possible to install 7zip because Scoop doesn't redownload the file if it's in the cache.
The filename has to be `7zip#19.00#https_7-zip.org_a_7z1900-x64.msi` because Scoop uses this format for cached files.

The workaround from @dmi3mis should work too.

**Comment by avgolubev** [comment]
@r15ch13 That's working. Thank you and all guys for your helping.

**Comment by Robespeler** [comment]
I get round this with proxy. Thank you for help.

@r15ch13 @avgolubev 
Summarize the full solution for others. I didn't understund what means by "call it" What command?

And I suggest it is not right to close the issue, because it is temporary solution.
And maybe there will be good correct way in the future

**Comment by avgolubev** [comment]
@Robespeler Yes, you're right, i open the issue.
"call it" means run `scoop install 7zip` after you copy 7zip#19.00#https_7-zip.org_a_7z1900-x64.msi file in the `~\scoop\cache\` .

**Comment by niheaven** [comment]
The official solution:

- Install 7zip by yourself (from SF and just make sure `7z.exe` is in your PATH)
- Run `scoop config 7ZIPEXTRACT_USE_EXTERNAL true`
- Now scoop will use `7z` from your own PATH and will skip all `7-zip` dependency.

As @r15ch13 said, you sould install `7zip-zstd` by scoop, which is more powerful and robust.

**Comment by Bug-terminator** [comment]
> The official solution:
> 
> * Install 7zip by yourself (from SF and just make sure `7z.exe` is in your PATH)
> * Run `scoop config 7ZIPEXTRACT_USE_EXTERNAL true`
> * Now scoop will use `7z` from your own PATH and will skip all `7-zip` dependency.
> 
> As @r15ch13 said, you sould install `7zip-zstd` by scoop, which is more powerful and robust.

what is PATH? pls & thx.

**Comment by niheaven** [comment]
> 
> 
> > The official solution:
> > 
> > * Install 7zip by yourself (from SF and just make sure `7z.exe` is in your PATH)
> > * Run `scoop config 7ZIPEXTRACT_USE_EXTERNAL true`
> > * Now scoop will use `7z` from your own PATH and will skip all `7-zip` dependency.
> > 
> > As @r15ch13 said, you sould install `7zip-zstd` by scoop, which is more powerful and robust.
> 
> what is PATH? pls & thx.

Let `7z` be found in your terminal, usually install 7zip by the installer should work.

**Comment by Robespeler** [comment]
> what is PATH? pls & thx.

Path it is the path to the application that you need to add to the variables so that the OS knows how to find this application. For some applications, you need to manually add the path if they cannot do this automatically during installation. For example, this applies to portable programs.

![Environment-Variables](https://user-images.githubusercontent.com/4341610/86250092-fcc34200-bb64-11ea-87aa-3e72500105e5.png)
