### ISSUE TITLE
Feature request: Automatic configuration for GitHub

### ISSUE THREAD

**Issue by heaths** [ScoopInstaller/Scoop#3920]
Since scoop already depends heavily - though not solely - on GitHub, can configuration of downloads and updates be easier for GitHub repos that use the release functionality? I don't want my build modifying the repo (a second repo would be an option but makes discoverability harder), and the GitHub API already supports what you'd need for download URL, checkver, and autoupdate. People might still need to configure which downloads to use for multi-platform releases, but this would allow us to commit a single static JSON file to our repo to simply configure a bucket.

**Comment by Calinou** [comment]
> I don't want my build modifying the repo (a second repo would be an option but makes discoverability harder), and the GitHub API already supports what you'd need for download URL, checkver, and autoupdate.

If your application is publicly available, we recommend you make a pull request to the [main bucket](https://github.com/ScoopInstaller/main) (for CLI apps) or [extras bucket](https://github.com/lukesampson/scoop-extras) (for graphical apps).
