### ISSUE TITLE
How to specify how many versions are kept in cache

### ISSUE THREAD

**Issue by Bios-Marcel** [ScoopInstaller/Scoop#3921]
Hey, I've noticed that my cache contains many versions of certain applications that often get updates. I have a rather small harddrive and this takes a lot of space. My cache has reached a size of 9GB now. Is there a way to say "Keep at max 3 versions of one software"? I couldn't find anything in the wiki. If any configuration is possible, it'd be great to document this in the GitHub wiki.

**Comment by Calinou** [comment]
As far as I know, you can't choose to keep only N versions, but you can cleanup all old versions using `scoop cleanup *` (try `scoop cleanup "*"` if that doesn't work).

**Comment by Bios-Marcel** [comment]
I see, too bad. Thanks anyway.
