### ISSUE TITLE
Scoop update fails fatal: this operation must be run in a work tree

### ISSUE THREAD

**Issue by attilastrba** [ScoopInstaller/Scoop#3927]
Unable to run scoop update 

`$ scoop update
` 
This happens only if the SCOOP environment variable is set. 

The update works once and than after this we get the error

```
fatal: this operation must be run in a work tree
Update failed.

```

**Comment by attilastrba** [comment]
This is caused by this issue in git: https://github.com/git-for-windows/git/issues/2569

**Comment by Mosney** [comment]
Same issue, I think I need stop using scoop before git patch this bug.

**Comment by Mosney** [comment]
@attilastrba Any idea for me? I try totally reinstall scoop and its apps, it worked for a while, the same issue occur now. I noticed you compile a different git version, could you send it to me to fix this problem?

**Comment by Mosney** [comment]
OK, I try again and success fix it.
Just edit `%userprofile%\scoop\apps\scoop\current\.git\config`
Change 
>worktree = %userprofile%/scoop/apps/scoop/**new**

to
>worktree = %userprofile%/scoop/apps/scoop/**current**

**Comment by Mosney** [comment]
It looks like caused by a scoop update fail. I'm not sure, but it work.

**Comment by attilastrba** [comment]
@Mosney no need to compile git. All what you have to do is to remove the property `worktree` from the `.git\config`. You just do it only once, than it works for the rest of the time until you re-install scoop. Let me know if you need any more help.

**Comment by Mosney** [comment]
@attilastrba thx a lot, I found a easier way to fix this issue writed it above.
