### ISSUE TITLE
Is there a way to dynamically create shims in a post-install script?

### ISSUE THREAD

**Issue by pfmoore** [ScoopInstaller/Scoop#3928]
I have an application that I'd like to bundle via scoop (a personal "wrapper" around certain Cygwin utilities). Ideally, I'd like to have a post-install step that creates shims for some utilities, based on what is already installed on the user's PC. Is there a utility or command I can use to create Scoop shims dynamically like this?

I guess I can just copy the shim exe and write my own `xxx.shim` file in the absence of any official means.

**Comment by archit9169** [comment]
use cmd /c mklink shim.exe bin.exe in the post-install script to create symbolic links. Use Full path eg: 
cmd /c mklink D:/scoop/shims/7zip.exe D:/scoop/apps/7zip/current/7zip.exe 
This will create a symbolic link which should work fine.

**Comment by r15ch13** [comment]
You can use the internal [`shim()`](https://github.com/lukesampson/scoop/blob/a9fa775d59b14e7dce335313faa0eff855469764/lib/core.ps1#L549-L609) function in `pre/post_install` scripts.

It gets called like this when you install a program:
https://github.com/lukesampson/scoop/blob/a9fa775d59b14e7dce335313faa0eff855469764/lib/install.ps1#L818

Example for manifest:
```json
...
"post_install": "shim \"$dir\\some.exe\" $global myshimname",
...
```

**Comment by archit9169** [comment]
> You can use the internal [`shim()`](https://github.com/lukesampson/scoop/blob/a9fa775d59b14e7dce335313faa0eff855469764/lib/core.ps1#L549-L609) function in `pre/post_install` scripts.
> 
> It gets called like this when you install a program:
> https://github.com/lukesampson/scoop/blob/a9fa775d59b14e7dce335313faa0eff855469764/lib/install.ps1#L818
> 
> Example for manifest:
> 
> ```json
> ...
> "post_install": "shim \"$dir\\some.exe\" $global myshimname",
> ...
> ```

Also make sure to use internal rm_shim() function in the uninstall script to make sure that the shim gets uninstalled if you uninstall the app.

**Comment by pfmoore** [comment]
> Also make sure to use internal rm_shim() function in the uninstall script

There's an option for an uninstall script?!? I've been struggling to work out how to do the equivalent of a `post_install` script in my manifest! Can you point me at an example somewhere?

**Comment by r15ch13** [comment]
You could use `installer.script` and `uninstaller.script` properties.
Example manifest that uses them: https://github.com/lukesampson/scoop-extras/blob/master/bucket/bgpkiller.json

**Comment by pfmoore** [comment]
Ah, I see, thanks! I'd misunderstood the use of `installer`/`uninstaller` as being simply ways of managing apps that used a "standard" installer. That example will be a great help to me.
