### ISSUE TITLE
BUG:  Cannot install fixed version of git (except current one)

### ISSUE THREAD

**Issue by tharilya** [ScoopInstaller/Scoop#3933]
Hi There,

### Problem in short:
It is currently impossible to install any Version of git which is not the current one.

#### Similar issue:
* #2702 
  * but seems to be ignored / other use-case

### System-Setup (Steps to reproduce):
I have a Dockerfile with the following context:
```
FROM mcr.microsoft.com/powershell:windowsservercore-1909

RUN pwsh.exe -Command \
    Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')

RUN pwsh.exe -Command \
    scoop install --global git@2.26.0.windows.1
```

This command will fail with:
```
WARN  Given version (2.26.0.windows.1) does not match manifest (2.26.1.windows.1)
WARN  Attempting to generate manifest for 'git' (2.26.0.windows.1)
Autoupdating git
Searching hash for PortableGit-$matchVer-32-bit.7z.exe in https://github.com/git-for-windows/git/releases/latest
Could not find hash in https://github.com/git-for-windows/git/releases/latest
Downloading PortableGit-$matchVer-32-bit.7z.exe to compute hashes!
The remote server returned an error: (404) Not Found.
URL https://github.com/git-for-windows/git/releases/download/v2.26.0.windows.1/PortableGit-$matchVer-32-bit.7z.exe#/dl.7z is not valid
Could not find hash!
Could not install git@2.26.0.windows.1
Couldn't find manifest for ''.
```

The behavior is the same for all releases. There is no "fixed" version of git which can be installed this way (except the current one).
I wrote some suggestions in [Comment-2702](https://github.com/lukesampson/scoop/issues/2702#issuecomment-614554514) There is a simple way to fix at least the stable versions of git.

**Comment by niheaven** [comment]
There's something wrong with `generate_user_manifest@lib/manifest.ps1`, so let's check it and think if there's some solutions.

**Comment by h0lg** [comment]
I have the same issue for **gcc**: I need it to build another project I'm working on and the current gcc version 9.3.0-2 runs into an error.
So I tried to find what versions of gcc are available via scoop and found that this is the only one, unless I'm missing something.
I tried the following:
```
scoop bucket add versions
scoop search gcc
'main' bucket:
    avr-gcc (10.2.0)
    gcc (9.3.0-2)

'versions' bucket:
    gcc45 (4.5.2)
```

Looking at the history of [gcc.json in the main bucket](https://github.com/ScoopInstaller/Main/blob/master/bucket/gcc.json) though I found it was updated from gcc 8.1.0.0 about 8 months ago in [this commit](https://github.com/ScoopInstaller/Main/commit/ed79022d1584316571dfae02fad60c08a168f79b#diff-b4e782d3e46b68a3230014b6d7ca8b6e2f6daedfbad5580d82f6a3ffaa928d53).

So I ended up installing `gcc 8.1.0.0` as follows:
1. reset the `master` branch of the `~/scoop/buckets/main` repo to **the parent of** above mentioned commit (i.e. the last commit using version 8.1.0.0)
2. run `scoop install gcc`
3. revert step 1., i.e. reset the `master` back to the `origin/master`
 
At that point **you can install gcc 9.3.0-2 in parallel** running `scoop install gcc@9.3.0-2` and then **switch in between gcc versions** using `scoop reset gcc@8.1.0.0` and `scoop reset gcc@9.3.0-2` respectively.

**Comment by h0lg** [comment]
> At that point **you can install gcc 9.3.0-2 in parallel** running `scoop install gcc@9.3.0-2` and then **switch in between gcc versions** using `scoop reset gcc@8.1.0.0` and `scoop reset gcc@9.3.0-2` respectively.

One thing I've noticed about this parallel gcc installation though is that `scoop list` will invariably show 9.3.0-2 even if I reset gcc to version 8.1.0.0:
```
scoop reset gcc@8.1.0.0
scoop list
Installed apps:

  7zip 19.00 [main]
  gcc 9.3.0-2 [~\scoop\buckets\main\bucket\gcc.json]
  go 1.15.6 [main]
```
 Notice also how the bucket name is replaced with the path to the json manifest file. I don't know what's up with that.

**Comment by rashil2000** [comment]
#2702
