### ISSUE TITLE
After the windows 10 updates, all shortcuts of scoop will disappear.

### ISSUE THREAD

**Issue by walterlv** [ScoopInstaller/Scoop#3941]
1. Scoop creates shortcuts into `%APPDATA%\Microsoft\Windows\Start Menu\Programs\Scoop Apps`;
2. After windows 10 updates, all shortcuts in that folder will disappear.

This might be a bug of scoop? Or it's a bug of Windows but we have to work around this.

PS. My windows 10 is an Insiders Preview version that updates every week, so my shortcuts disappear every week and I can't find ways to restore them expect backing up them manually.

**Comment by h404bi** [comment]
Known issue. https://github.com/lukesampson/scoop/issues/2233

**Comment by walterlv** [comment]
So we should type and execute this command every time after the Windows 10 updates?

```powershell
scoop reset *
```

1. I'm interested in the critical reason why the shortcuts will disappear.
2. I think this issue should not be fixed manually but be fixed automatically.

**Comment by walterlv** [comment]
I'm doing a test that whether the Junction Point is the key reason that Windows will delete the shortcuts.

![image](https://user-images.githubusercontent.com/9959623/80299668-cebe2c00-87c8-11ea-967c-07152a6a1b26.png)

As the image shows above, I've made a test folder in the `%USERPROFILE%` folder and a `current` Junction Point targeting a neighbor folder. The shortcut targets the text file in the Junction Point folder.

Wait for the Insider's update next week, and I'll find that whether if it is a Windows shortcut bug.

**Comment by walterlv** [comment]
A whole week passed with an Insider's update restart, and I've got the answer:

**The shortcut will disappear when the shortcut is linked to a file that is in a Junction Point.**

This is the screenshot after the Windows Update, comparing to the one 6 days ago which is posted above.

![image](https://user-images.githubusercontent.com/9959623/80853240-aec3b800-8c61-11ea-8a85-763225e04549.png)

So this issue can be closed as I'll report this issue as a Windows Bug.

**Comment by h404bi** [comment]
@walterlv Thank you for your investigations and reports, which are really helpful.

**Comment by archit9169** [comment]
Will the problem persist if symbolic link is used instead of junction when linking current?

**Comment by walterlv** [comment]
@archit9169 I'll do another test for that and thanks for your suggestion.

**Comment by archit9169** [comment]
> @archit9169 I'll do another test for that and thanks for your suggestion.
> 
> ![image](https://user-images.githubusercontent.com/9959623/80898931-26661580-8d3c-11ea-97eb-681049168c37.png)
> 
> And now, I've created two shortcuts for a controlled experiment. What we need to do is to wait for the next Insider's Update next week.

I have a solution for this problem. I already mentioned that in one other discussion. We can just simply move the shortcuts folder from $WINDIR to $SCOOPDIR and then create a symlink or junction to that folder. 

Since windows updates removes shortcuts which refer to a location inside a junction, this will keep the shortcuts safe. In an event like the windows update erasing the shortcuts folder instead, we can simply modify <scoop update scoop> which at the moment does nothing to re-create the shortcut symlink or junction.

**Comment by walterlv** [comment]
![image](https://user-images.githubusercontent.com/9959623/81286766-2d6e8a00-9094-11ea-9bdc-8d3af2de4a43.png)

OK, the new test is done!

- The shortcuts in the start menu linking files in the junction points are lost.
- The shortcuts in the start menu linking files in the symbol link persist.
- The shortcuts outside the start menu (D:\ etc.) are all persist no matter what types they are linking.

**Comment by walterlv** [comment]
@archit9169 Maybe your suggestion that we move the shortcuts outside of the start menu folder can solve this issue.

It means that I'll do another test to make the `Scoop Apps` folder in the start menu as a Junction Point which links to a `shortcuts` folder in the scoop directory which contains all the shortcuts of the scoop apps.

![image](https://user-images.githubusercontent.com/9959623/81287786-f8633700-9095-11ea-922f-326a25278383.png)

**Comment by archit9169** [comment]
@walterlv yeah you are right, i just checked myself. So the next best solution is using symbolic links instead of junctions.

**Comment by walterlv** [comment]
@archit9169 Unfortunately as I said above, the symbolic links need to run as Administrator but scoop never got this privilege.

**Comment by archit9169** [comment]
> @archit9169 Unfortunately as I said above, the symbolic links need to run as Administrator but scoop never got this privilege.

Not with the new updates. mklink /d link target works without admin priv.

**Comment by walterlv** [comment]
@archit9169 Yes you're right. I'll fix the wrong description in my blog:

- [比较 Windows 上四种不同的文件（夹）链接方式（NTFS 的硬链接、目录联接、符号链接，和大家熟知的快捷方式） - walterlv](https://blog.walterlv.com/post/ntfs-link-comparisons.html)
- [Compare four different file (folder) link methods on Windows (NTFS hard links, directory links, symbolic links, and well-known shortcuts)](https://translate.google.com/translate?sl=zh-CN&tl=en&u=https%3A%2F%2Fblog.walterlv.com%2Fpost%2Fntfs-link-comparisons.html)

**Comment by rmobis** [comment]
Has this been fixed? All my shortcuts just disappeared and coincidently it was after a Windows Update. I think it was `Windows 11, version 22H2` and I'm not sure if that's a recent update, as my machine is only a few days old and it might have been an old update.

**Comment by rashil2000** [comment]
We don't know the cause for it yet, but you can quickly fix it by running `scoop reset *`

**Comment by SiriosDev** [comment]
some news?
