### ISSUE TITLE
Using reg.exe to import registry files.

### ISSUE THREAD

**Issue by archit9169** [ScoopInstaller/Scoop#3944]
So, windows registry allows you to manage HKEY_CURRENT_USER without admin privileges and all the changes made to this are user specific. So adding python reg file to HKCU can be done without admin rights, same with adding to context menu and other things.

Command:
reg.exe import regfile.reg

As long as the registry files pertains to HKCU,no admin rights are required and for global apps, they can make change to root and other HKEY locations with admin rights since installing global apps requires admin right by default.

**Comment by rashil2000** [comment]
Tracked in #2651
