### ISSUE TITLE
Using scoop after reinstall windows

### ISSUE THREAD

**Issue by fiammanda** [ScoopInstaller/Scoop#3948]
It tells me
```
Scoop is already installed. Run 'scoop update' to get the latest version.
```
but
```
scoop : The term 'scoop' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ scoop
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (scoop:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by archit9169** [comment]
Navigate to scoopdir/app and delete scoop folder.
Navigate to scoopdir/shims and delete scoop.ps1 and scoop.cmd
And then install scoop
Then do scoop reset * to create all the shims, shortcuts and current junctions.

**Comment by twocs** [comment]
Not sure if you got the same issue, but for me, scoop did not add itself to the path.
It started working after I added it to the user path: %USERPROFILE%\scoop\shims

![image](https://user-images.githubusercontent.com/72763/105628975-30164700-5e90-11eb-8c66-35ee8384ff57.png)
