### ISSUE TITLE
Feature Request: Please add "persist" to "architecture" part

### ISSUE THREAD

**Issue by digitalentiert** [ScoopInstaller/Scoop#3959]
For some applications like "[AlwaysMouseWheel Portable](https://www.softwareok.com/?Download=AlwaysMouseWheel)" the name of the ini file is different for 32bit and 64 bit versions (AlwaysMouseWheel_p.ini for 32bit and AlwaysMouseWheel_x64_p.ini for 64bit).
It would be great if there was a possibility to persist the setting files in the architecture part. Something like this:
<pre>
...
    "architecture": {
        "64bit": {
            "url": "...",
            "hash": "...",
            "shortcuts": [
                [
                    "AlwaysMouseWheel_x64_p.exe",
                    "AlwaysMouseWheel"
                ]
            ],
            <b><i>"persist": "AlwaysMouseWheel_x64_p.ini"</i></b>
        },
        "32bit": {
            "url": "...",
            "hash": "...",
            "shortcuts": [
                [
                    "AlwaysMouseWheel_p.exe",
                    "AlwaysMouseWheel"
                ]
            ],
            <b><i>"persist": "AlwaysMouseWheel_p.ini"</i></b>
        }
    },
...
</pre>

**Comment by ViCrack** [comment]
It seems to be related to the filename


![图片](https://user-images.githubusercontent.com/18179821/195299925-f3eff601-8a6e-4e61-a78b-2664abc60b8b.png)

**Comment by digitalentiert** [comment]
@ViCrack Thank you!

**Comment by o-l-a-v** [comment]
Why was this closed @digitalentiert? How did you solve your initial problem of the `*.ini` file name not being equal across architecture? Renamed the EXE file?
