### ISSUE TITLE
Installation/Update failures should clean themselves up

### ISSUE THREAD

**Issue by pigsflew** [ScoopInstaller/Scoop#3965]
It's quite annoying that when scoop fails to install a thing, `scoop install` doesn't work anymore, needing the user to run `scoop uninstall` first.

Installation failures should keep the cached downloaded file, but otherwise wind themselves back, running uninstall tasks before considering their job done, and then bubbling up an error result.

Similarly, update failures should undo any changes to the `app/current` directory if already done, undo any new folder creation/script changes, and reset.

**Comment by pigsflew** [comment]
A complex idea for solving this would be a path like this:

```
backup
try {
  // upgrade if manifest specifies specific upgrade instructions 
  upgrading ? install && upgrade : install
} catch {
  // rollback if manifest specifies specific rollback instructions
  // reset does nothing if no previous version is installed.
  upgrading ? ( revert && reset ) : uninstall
}
```

- `Backup` would default to doing nothing
- `Upgrade` would default to doing nothing.
- `Revert` would default to just deleting the directory for that version.
- Manifests could override / add to `backup`, `upgrade`, and `revert` if necessary to make sure their app is cleaned up properly.
- In the future with features like supporting HKCU reg entries, `revert` would support removing or resetting those entries to their earlier values, their stored in the `backup` phase.

I might be overengineering this for scoop though.

**Comment by alannotnerd** [comment]
I think that's quit easy to do so, but it doesn't. SO, I think this might be a feature? The developer said that reversed due to debug propose. #3580

**Comment by rashil2000** [comment]
Fixed
