### ISSUE TITLE
Allow disabling aria2c warning

### ISSUE THREAD

**Issue by eugenesvk** [ScoopInstaller/Scoop#3967]
Whenever I'm trying to update an app, I get the following annoying (due to repetition) warning:
```
    warn "Scoop uses 'aria2c' for multi-connection downloads."
    warn "Should it cause issues, run 'scoop config aria2-enabled false' to disable it."
```
Is there a way to set up scoop to disable them?
I've manually commented them out in scoop-update.ps1 and scoop-install.ps1, but would prefer a more permanent config-based solution

**Comment by ViCrack** [comment]
run 'scoop config aria2-enabled false' to disable it.

`    "aria2-warning-enabled":  false`

**Comment by rashil2000** [comment]
Yes, thanks for the reminder @ViCrack!

**Comment by eugenesvk** [comment]
@ViCrack it should be `scoop config aria2-warning-enabled false` as introduced in this [commit](https://github.com/ScoopInstaller/Scoop/commit/8bb7390a75055b74de86c12cafa99bfcde3f9c34#diff-504b3c7b00e3f730b6ebbfa732362b86c37902a05a9dc88eeca3a9e41df4b6d6) rather than disabling aria2 itself with `scoop config aria2-enabled false`

**Comment by ViCrack** [comment]
@eugenesvk Yes, that's right.😂
