### ISSUE TITLE
help for scoop reset unclear

### ISSUE THREAD

**Issue by Bios-Marcel** [ScoopInstaller/Scoop#3968]
Scoop reset doesn't really show how to use it. It says you can switch between `python` and `python27` for examples. It looks like these are different apps that are not installed via the same manifest. As far as I understood reset can be used to switch between version of an app that were installed via the same manifest. An example would be very nice here.

For example:

```
To revert to a specific version, run for example:

scoop reset someapp@v1.0.2

Reset back to the latest installed version with

scoop reset someapp
```

**Comment by quantuumsnot** [comment]
Or the other problem with reset:

> scoop reset firefox-developer
> Resetting firefox-developer (current).
> Linking D:\scoop\apps\firefox-developer\current => D:\scoop\apps\firefox-developer\current
> Error: Version 'current' is not allowed!

**Comment by Bios-Marcel** [comment]
Might wanna create a new issue for that

**Comment by quantuumsnot** [comment]
Not needed, this looks like a standard behavior of moving data from a drive to drive in Windows 7/8/10 - directory junctions are not saved

**Comment by rashil2000** [comment]
> As far as I understood reset can be used to switch between version of an app that were installed via the same manifest. 

That's not necessary. `reset`'s primary function is to recreate shims, shortcuts, persistence, environment variables etc. 

Switching between versions of 2 apps that provide similarly-names shims/shortcuts is a side effect of that.
