### ISSUE TITLE
How to list versions of installed app

### ISSUE THREAD

**Issue by Bios-Marcel** [ScoopInstaller/Scoop#3969]
I was trying to revert my java installation to an older version due to an incompatibility problem with the latest version. The problem is, that java has very stupid version number, such as `1.8.0.252-2.b09`. So in order to find out what string exactly to type, I had to navigate into the scoop folder and find out which versions I had installed. It'd be nice to have a command to do this.

**Comment by JoBrad** [comment]
You can get this from `scoop info _appname_`. There is an "Installed" section which will list all install versions.

**Comment by Bios-Marcel** [comment]
I wish such stuff would be more obvious from reading the help pages for each command. Thanks anyway.

**Comment by h0lg** [comment]
> You can get this from `scoop info appname`. There is an "Installed" section which will list all install versions.

This does not work for all apps though. `gcc` for example doesn't list the versions I have installed.
May this be dependent on the **autoupdate** capability of an app I've seen popping up in scoop output?

**Comment by sebma** [comment]
@rashil2000 Hi, how do I list all the versions available for a specific package ?

**Comment by rashil2000** [comment]
There's only one version of a package available to install - the latest one. 

You can use the `scoop search` command to find it. 

If you want more versions, add the `Versions` bucket which contains historical versions.

**Comment by sebma** [comment]
I already added the `Versions` bucket and was able to install a specific version of the `aws` package (for example) with this command : 
```shell
C:\WINDOWS\system32> scoop install -g aws@2.22.35
```
I would like to know how to list all the available versions of a package before installing a version of a package : Is that possible with scoop ?
