### ISSUE TITLE
Question: any way to prioritise shim sources?

### ISSUE THREAD

**Issue by fluffynuts** [ScoopInstaller/Scoop#3971]
After having a strange time with vim, I found that my scoop shim for vim was pointing to a vim.exe from within the `gow` package. However, I also have the `vim` package installed. I've rectified the shim config and .ps1 files so that I get the vim I'm expecting, but I also expect that this could be destroyed by a subsequent update, so I'm wondering if there's any way to tell scoop that the shim from one package should take priority over others so that it doesn't get wiped out?

I would imagine that this problem isn't limited to my particular instance.

**Comment by Ash258** [comment]
`scoop reset vim`

**Comment by fluffynuts** [comment]
I would imagine that this perhaps resets to the last one that was implemented before now -- is there a way to _always_ pin a shim? What if I install 3 things in succession which provide the same utility? And updates after the fact? The onus is on the user to keep track of links -- which sounds like something the system could rather do.

If it's not a current feature, I'd like to propose it -- I can open a new issue or rename this one to make it clearer, if you like? Any package management system has to, at some point, deal with conflicts -- it would be really nice to have a deterministic solution to that (:

**Comment by Rohaq** [comment]
I'd love this too - it would be useful to keep multiple versions of say, PHP or Python up to date, whilst maintaining a default version in my shims so it doesn't change behaviour on my $PATH.

**Comment by NotWearingPants** [comment]
It's also a problem between `sudo` and `psutils`, and between `python` and `python27`, and between `gow` and `coreutils` and `grep`

**Comment by rashil2000** [comment]
#1290
