### ISSUE TITLE
Concept of installing without UAC/admin rights is not the right way

### ISSUE THREAD

**Issue by smsteel** [ScoopInstaller/Scoop#3975]
Short: it opens a huge vulnerability potential for any scoop user.

Long:
Generally, there should be NO rights to run a program outside of known locations by default and this method is used by many organizations on a group policies level.
And as a general rule of thumb it is a GOOD thing to have a restriction for installing 3rd party software for a default user account and any package manager should follow that rule.
This feature comes with close to little luxury (you don't usually install much) and big problems afterwards.
Thoughts?

**Comment by Calinou** [comment]
I'd say it's a good thing :slightly_smiling_face: Scoop is user-centered, it won't bend backwards to try to please system administrators.

You can still install packages globally (which requires administrator privileges) by passing `--global`.
