### ISSUE TITLE
Use %localappdata% instead of %userprofile%/.config to store config.json

### ISSUE THREAD

**Issue by piotrek-szczygiel** [ScoopInstaller/Scoop#3977]
Most new Windows applications store configuration in %appdata% or %localappdata%.

Polluting the home directory is very annoying.
I personally think the 'scoop' directory should also be moved to %localappdata%, but that is
probably too big of a change to ask for.

**Comment by archit9169** [comment]
> Most new Windows applications store configuration in %appdata% or %localappdata%.
> 
> Polluting the home directory is very annoying.
> I personally think the 'scoop' directory should also be moved to %localappdata%, but that is
> probably too big of a change to ask for.

Instead of that, it would be better to keep it inside SCOOP_DIR

**Comment by borkdude** [comment]
You can set `XDG_CONFIG_HOME` to make scoop put the config anywhere you like.
