### ISSUE TITLE
Stability of the buckets.json file format

### ISSUE THREAD

**Issue by 0xced** [ScoopInstaller/Scoop#3978]
I am currently implementing a [Shields](https://shields.io) badge for Scoop: https://github.com/badges/shields/pull/5081. Once merged you'll be able to get dynamically generated nice badges like this (using ngrok and dnspy as examples):

`https://img.shields.io/scoop/v/ngrok` → <img src="https://img.shields.io/badge/scoop-2.3.35-blue">
`https://img.shields.io/scoop/v/dnspy?bucket=extras` → <img src="https://img.shields.io/badge/scoop-6.1.4-blue">

I don't think you plan to move or rename the `buckets.json` file, but I wanted to let you know that it would be really nice to keep it at the same location (root of this repository) and not change its format in order not to break the badges in the future (and possibly other scoop integrations too).

**Comment by r15ch13** [comment]
Currently, there are no plans for changing the `buckets.json`.
But only relying on the `buckets.json` would limit it to only the official buckets.
Would it be possible to make it available for any bucket by using `scoop/<user>/<repo>/<program>` or something?

**Comment by prantlf** [comment]
@0xced, is somebody maintains all buckets in a single repository, it would be helpfkl tu support multiple application manifests there, as @r15ch13 wrote, for example:

    user/repo/
      program1.json
      program2.json
      ...

It is similar to a repository with a Homebrew tap. Such distribution repositories are maintained by `goreleaser`, for example.
