### ISSUE TITLE
Scoop update failed

### ISSUE THREAD

**Issue by Decem6er** [ScoopInstaller/Scoop#3979]
I can't update the scoop or install other apps for the following reasons.
```
PS C:\Users\Xuyy1> scoop update
Updating Scoop...
fatal: unable to access 'https://github.com/lukesampson/scoop/': Failed to connect to 127.0.0.1 port 1080: Connection refused
Scoop update failed.
```
I have tried `git config --global --unset http.proxy` , `git config --global --unset https.proxy` and `scoop config rm proxy` but it didn't work.

**Comment by h404bi** [comment]
> `scoop config rm proxy` but it didn't work.

Try to open `C:\Users\yourname\.config\scoop\config.json` and remove proxy from the config file.

**Comment by Decem6er** [comment]
I have tried it just now. However, there is nothing about proxy. The things in `config.json` are as follows.
```
{
    "lastupdate":  "2020-05-12T22:59:48.7972001+08:00",
    "SCOOP_REPO":  "https://github.com/lukesampson/scoop",
    "SCOOP_BRANCH":  "master"
}
```
Then I deleted all of them, however, the problem still existed.

**Comment by StarsbySea** [comment]
Try this command and see if it works.
`scoop config proxy none`
It looks like you are using Shadowsocks, but it doesn't work. Please check if you have set up a system proxy (Settings-Network and Internet-Proxy), if so please turn it off and try again.

**Comment by xiaoyangren513** [comment]
翻墙关闭就可以更新了

**Comment by Lars-Malmgren** [comment]
I had this issue after i had used Fiddler which works as a proxy.
StarsbySea's suggestion worked for me `scoop config proxy none`
