### ISSUE TITLE
Search of available JDKs

### ISSUE THREAD

**Issue by bykka** [ScoopInstaller/Scoop#3988]
It's not easy to get a list of available JDKs because search looks only into the names but not in the descriptions.

As result command "scoop search jdk" does not show amazon's JDK "corretto"
So, expected to see the next packages included to the result:
-  corretto (11.0.7.10.1)
-  corretto11 (11.0.7.10.1)
-  corretto8-jre (8.252.09.2)
-  corretto8 (8.252.09.2)

**Comment by rashil2000** [comment]
#4412
