### ISSUE TITLE
Support zstd for extraction

### ISSUE THREAD

**Issue by trajano** [ScoopInstaller/Scoop#3990]
Msys2 repo uses zstd for their new packages, can you add support for zstd decompression?

**Comment by Calinou** [comment]
Scoop depends on 7-zip to extract formats other than ZIP, but the official 7-zip distribution doesn't support Zstandard. Many third-party forks do, though.

**Comment by r15ch13** [comment]
Scoop can use 7zip-zstd.
```
scoop bucket add versions
scoop install 7zip-zstd
scoop uninstall 7zip
```

https://github.com/lukesampson/scoop/blob/96de9c14bb483f9278e4b0a9e22b1923ee752901/lib/core.ps1#L252-L258

**Comment by Augiiz** [comment]
Still no luck extracting zst packages upon installation, they just sit there.

**Comment by r15ch13** [comment]
Do you have some example files?

**Comment by Augiiz** [comment]
![](https://i.imgur.com/oLbUwAa.png)

Since main buckets gcc still on 9.3 trying to set my own bucket for gcc 10, but mingw moved some of their archives to zst starting gcc 10.

**Comment by niheaven** [comment]
Need some manual tweaks:

1. Add `zst` to L19 of `lib/decompress.ps1` of scoop (`%SCOOP%/apps/scoop/current/lib/decompress.ps1`)
1. `scoop reset 7zip-zstd`
1. Install your gcc10

**Comment by Augiiz** [comment]
Did it for me, thanks a bunch.

**Comment by trajano** [comment]
> Scoop depends on 7-zip to extract formats other than ZIP, but the official 7-zip distribution doesn't support Zstandard. Many third-party forks do, though.

Is there a PR on the 7Zip mainline to integrate it?

**Comment by Calinou** [comment]
@trajano I think there have been several, but none of them was merged so far: https://sourceforge.net/p/sevenzip/discussion/45797/thread/a7e4f3f3/

**Comment by trajano** [comment]
@Calinou from the discussions you linked it seems that there's no further work on integrating it and it had started in 2016.  Maybe scoop should consider an alternative to 7z or at least use the official distribution to do the decompression at least it would decouple scoop from 7zip in case there are new compression formats that it does not support.

**Comment by wstein** [comment]
msys2 has purged many older file version.
Now many packages of msys2 are only available as zstd compressed files.

If this issue will not be fixed, the msys2 based packages like gcc and openssh should be dropped.

**Comment by psydvl** [comment]
There are also `zstd` package in `main` bucket
Why not use only it?
https://github.com/ScoopInstaller/Main/blob/master/bucket/zstd.json

**Comment by rashil2000** [comment]
This is a pretty important blocker right now.

@niheaven Since you are somewhat familiar with Scoop's internals, can you have a look at which one of these is more appropriate - #4137 or #4372?

**Comment by niheaven** [comment]
I'll use `7zip-zstd` to extract `zstd` as https://github.com/ScoopInstaller/Scoop/issues/3990#issuecomment-631327549 and make a PR, maybe in this week.

**Comment by rasa** [comment]
Imo, #4372 is probably mire appropriate, as it appears to borrow heavily from https://github.com/Ash258/Scoop-Core/pull/97/files .
