### ISSUE TITLE
Scoop-Reset: The architecture specific 'env_add_path' would not be reset.

### ISSUE THREAD

**Issue by sinloss** [ScoopInstaller/Scoop#4000]
Hi, all.

Recently, I've tried to move my `SCOOP` home to another directory, and I can not reset the architecture specific `env_add_path` stated in some of my custom manifests. For example, I have a snippet of the manifest looks like this:
```
{
    //...
    "architecture": {
        "64bit": {
            "env_add_path": [
                "Bin",
                "Tools"
            ]
        },
        "32bit": {
            "env_add_path": [
                "Bin32",
                "Tools32"
            ]
        }
    },
    //...
}
```

It is expected that the path should be set targeting my new `SCOOP_HOME`, yet it did not.

After some debugging, I found out that the function `env_add_path` *https://github.com/lukesampson/scoop/blob/96de9c14bb483f9278e4b0a9e22b1923ee752901/lib/install.ps1#L940* actually takes an `$arch` parameter, yet the calling line of `env_add_path $manifest $dir` *https://github.com/lukesampson/scoop/blob/96de9c14bb483f9278e4b0a9e22b1923ee752901/libexec/scoop-reset.ps1#L76* choose not to pass the `$architecture` as well as the `$global`.

**So...** 
Is this line intended to be like this and why, or just an inadvertent issue and I should submit a PR?

**Comment by archit9169** [comment]
scoop reset is still not complete. if you can fix this and file a pr it would be great. also i you notice then scoop reset does not execute post or pre install commands or normal install commands too.

**Comment by sinloss** [comment]
> scoop reset is still not complete. if you can fix this and file a pr it would be great. also i you notice then scoop reset does not execute post or pre install commands or normal install commands too.

Yeah, I've noticed it a long time ago, but that part is clearly acknowledged. But the `env_add_path` is different, as long as the normal `env_add_path` works, the architecture-specific `env_add_path` should also work.
