### ISSUE TITLE
Installation failed, due to SSL/TLS Error [fix]

### ISSUE THREAD

**Issue by LarsOlt** [ScoopInstaller/Scoop#4002]
I had to do the following to get the installation to work.
Maybe this helps someone.

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
Set-ExecutionPolicy RemoteSigned -scope CurrentUser
iwr -useb get.scoop.sh | iex

Source: [Stackoverflow](https://stackoverflow.com/questions/41618766/powershell-invoke-webrequest-fails-with-ssl-tls-secure-channel)

**Comment by imgx64** [comment]
This issue is caused by TLSv1.3, but I'm not sure why. I looked at the failing connections with Wireshark and noticed they're TLSv1.3. Firefox and Chrome successfully connect to GitHub using TLSv1.3, but in PowerShell even a simple `iwr https://github.com` fails unless I manually set SecurityProtocol to TLSv1.2.

I can't confirm it, but I think Windows 10 Version 2004 enabled TLSv1.3 in SystemDefault SecurityProtocol. Should scoop disable TLSv1.3 until the PowerShell implementation matches whatever Firefox and Chrome do?

Windows 10, Version 2004, Build 19041.329
PSVersion: 5.1.19041.1

**Comment by imgx64** [comment]
I tried on a different machine, and it worked perfectly on a fresh install of Windows 10 version 2004, so the Windows version is not to blame.

However, I found out the following:
1- My work's firewall seems to be blocking TLSv1.3 connections from PowerShell but not from Firefox or Chrome. Connecting directly to the internet solves the problem.
2- I had a registry key enabling TLSv1.3 (HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.3\Client). I'm not sure how it got there, but removing it solved the issue.

**Comment by alexxtasi** [comment]
@LarsOlt ... this saved my day (on Windows 7)

**Comment by LarsOlt** [comment]
> @LarsOlt ... this saved my day (on Windows 7)

I am glad I could help

**Comment by aldebran97** [comment]
I deleted the scoop directory and reinstalled it. With an earlier version of powershell, there were no errors when installing the package.

**Comment by aetonsi** [comment]
<details><summary>screenshot</summary><img src="https://github.com/ScoopInstaller/Scoop/assets/18366087/89ffa129-4339-4529-b4e5-1c1d9c94041c"></details>

i couldn't resolve this problem for the life of me.
security protocols all enabled (tls,tls11,tls12,tls13).
scoop couldn't download this file [`curl-8.4.0_6-win64-mingw.tar.xz`](https://curl.se/windows/dl-8.4.0_6/curl-8.4.0_6-win64-mingw.tar.xz).

so i did a little of trial and error and i temporarily fixed it this way:
- i downloaded the file in a browser
- i placed it in `~/scoop/cache`
- i renamed it to match the correct format (`curl#8.4.0_6#https_curl.se_windows_dl-8.4.0_6_curl-8.4.0_6-win64-mingw.tar.xz`)
- i then run `scoop install curl`
it used the existing `cache`d file and installed correctly.

so there's really something up with the environment..
i was on windows server 2012. tried both with pwsh and winposh. same results.
