### ISSUE TITLE
.ps1 shim for Git masks command failure ($? is True, $LASTEXITCODE is non-zero)

### ISSUE THREAD

**Issue by gavinfoley** [ScoopInstaller/Scoop#4003]
## What's the issue?

When running a Git command which fails, I want to check for that failure using the `$?` variable.  (More concretely, I'd like to use it implicitly with the `&&` operator added in PowerShell 7.)

This works as expected if the `git` command resolves to `git.exe`, but fails if it resolves to `git.ps1`.

This is surprising behavior, and makes the shims a leaky abstraction over the command they represent.

## Steps to reproduce

- Run `Get-Command git` and verify that the `Name` property is `git.ps1`
- In a directory which is not a Git repository, run a Git command such as `git status`
- Observe that the value of the `$?` variable is `True`
- Remove or rename the `git.ps1` shim
- Run `Get-Command git` and verify that the `Name` property is `git.exe`
- Run the same command as above in the same directory
- Observe that the value of the `$?` variable is `False`

**Comment by rashil2000** [comment]
Merged in develop branch - #4543
