### ISSUE TITLE
[BUG] If 'scoop update' failed, scoop itself will be removed.

### ISSUE THREAD

**Issue by GalaxySnail** [ScoopInstaller/Scoop#4005]
## Description
Scoop is installed with 'bin/install.ps1' ('\~/scoop/apps/scoop/current/.git' doesn't exist), if I run 'scoop update' and use 'Ctrl + C' to interrupt it, '\~/scoop/apps/scoop/current' will be removed silently.

## Solution
There is a bug in 'libexec/scoop-update.ps1', when '$currentdir/.git' doesn't exist and 'git clone' fails, the currentdir will always be removed. I fixed it in my pull request.

**Comment by rashil2000** [comment]
Related https://github.com/ScoopInstaller/Scoop/issues/3050
