### ISSUE TITLE
Delete unnecessary shortcuts code from 2017

### ISSUE THREAD

**Issue by NotWearingPants** [ScoopInstaller/Scoop#4016]
I was browsing the code and randomly bumped into this reminder you left for yourselves 3 years ago:

https://github.com/lukesampson/scoop/blob/f3ddf0c0f81ee2a11466edf5d9f6e38a0fc2b9d4/lib/shortcuts.ps1#L75-L76

Added in this [commit](https://github.com/lukesampson/scoop/commit/9a0dbfd23602f77cde5178f9b1a46bfbf2c8c30b)

I have no idea what it's about, but the date has passed and maybe you can delete this now like you wanted.

**Comment by rashil2000** [comment]
Removed https://github.com/ScoopInstaller/Scoop/pull/4410
