### ISSUE TITLE
Support folder buckets which are not a git repo

### ISSUE THREAD

**Issue by NotWearingPants** [ScoopInstaller/Scoop#4019]
Currently, scoop buckets are a git repo with a `bucket` folder.
Git is used for auto-updating the package index.

Scoop also supports installing manifests directly - `scoop install .\path\to\local\app.json`, or `scoop install http://example.com/path/to/remote/app.json`

Scoop should support something like `scoop bucket add local .\path\to\local` or `scoop bucket add example http://example.com/path/to/remote`, which should register the local/remote bucket, and when using `scoop install app` it should attempt to fetch the manifest from that local directory or url.

**Comment by rashil2000** [comment]
Closed in #4670

**Comment by nicksettoon** [comment]
this appears to be bunk. I'm not sure why, but the bucket is just not showing up at all when i run `scoop bucket list`, nor can i search for or install any app in the bucket. 

my folder structure is a local git repo that is just a clone of https://github.com/ScoopInstaller/BucketTemplate

C:\ProgramData\scoop\buckets\basics\ is that clone
