### ISSUE TITLE
Support packages which are plugins to other packages

### ISSUE THREAD

**Issue by NotWearingPants** [ScoopInstaller/Scoop#4021]
To explain, I will use Paint.net as an example.

Paint.net can be installed using scoop (`scoop bucket add extras; scoop install paint.net`).

Paint.net also has a plugins feature, where you can place dll files inside the `Effects` folder in its installation directory, and Paint.net will load them as plugins.

But Paint.net does not have a plugin manager, so one must add or remove plugins manually.

Also common are plugin packs, which are many dll files that are to be copied to the `Effects` folder.
So if comes a day when you want to remove the plugin pack, you need to scout for the specific dll files belonging to that pack.

So it seems a valid use case to use scoop to mange plugins for Paint.net, e.g. `scoop install paint.net-plugin-smudge` to install the smudge plugin, which will download and add the `smudge.dll` file to `~\scoop\persist\paint.net\Effects\`, and when uninstalled will delete it.

This is what I'm currently doing:
```json
{
    "installer": {
        "script": [
            "(Get-ChildItem \"$dir\\*.dll\").Name | Out-File \"$dir\\plugins.txt\"",
            "Move-Item \"$dir\\*.dll\" \"$dir\\..\\..\\..\\persist\\paint.net\\Effects\\\""
        ]
    },
    "uninstaller": {
        "script": [
            "Get-Content \"$dir\\plugins.txt\" | ForEach-Object { Remove-Item \"$dir\\..\\..\\..\\persist\\paint.net\\Effects\\$_\" }"
        ]
    }
}
```

But it feels like a hack, and that scoop is not meant for this.
What is the best way to use scoop to install plugins, where installing is putting files in the `persist` folder of another package? Are there maybe features that can be added to scoop to support this usecase? Is it a popular usecase?

**Comment by rashil2000** [comment]
Each application and plugin has different ways of enabling plugins, so Scoop can't manage them. It is best left to the individual manifest. The plugin name should begin with the app name, that's the only hard requirement.
