### ISSUE TITLE
Can't have two apps which depend on different java versions

### ISSUE THREAD

**Issue by NotWearingPants** [ScoopInstaller/Scoop#4023]
Let's suppose I install `app-a` which depends on Java 14, and `app-b` which depends on Java 8.

While there is a [documented way to switch java versions manually](https://github.com/lukesampson/scoop/wiki/Java#switching-javas), before I run either `app-a` or `app-b` I have to make sure to switch to the correct java version.

Instead, scoop should see that they depend on different versions of the same thing, and the shim/shortcut should set up the environment such that they would use the correct version of the dependency.

**Comment by rashil2000** [comment]
You can a `"depends": "java/openjdk10"` or `"depends": "java/openjdk14"` to pin dependency to a specific version in the manifest
