### ISSUE TITLE
Error installing 7-Zip or any program that depends on it (like vim)

### ISSUE THREAD

**Issue by jdavid82** [ScoopInstaller/Scoop#4024]
![image](https://user-images.githubusercontent.com/463793/84338461-76f44c80-abdf-11ea-963c-2118df64d7a6.png)

Thank you, also, great product, I've recommended it to my workmates

**Comment by juanjosegarciaripoll** [comment]
I get a different error message but the same problem It seems that the installer is looking for "git" but "git" is not installed (it depends on 7zip).

```
PS C:\Users\python> scoop install 7zip
Installing '7zip' (19.00) [64bit]
7z1900-x64.msi (1,7 MB) [=============================================] 100%
Checking hash of 7z1900-x64.msi ... ok.
Extracting 7z1900-x64.msi ... ERROR Exit code was 1601!
```

**Comment by zoof** [comment]
I was getting the same problem as @juanjosegarciaripoll but then I tried from a `cmder` instance which comes bundled with `git` and instead get
```
scoop install curl
Installing '7zip' (19.00) [64bit]
Loading 7z1900-x64.msi from cache
Checking hash of 7z1900-x64.msi ... ok.
Extracting 7z1900-x64.msi ... ERROR Exit code was 1603!
Failed to extract files from C:\Users\username\scoop\apps\7zip\19.00\7z1900-x64.msi.
Log file:
  ~\scoop\apps\7zip\19.00\msi.log

Please try again or create a new issue by using the following link and paste your console output:
https:////
```

I am behind a proxy and initially thought it had something to do with the proxy but even after setting `scoop config proxy ...` it is still not working.  Please let me know what I can provide to help diagnose this -- is there any way to set `scoop install` to provide verbose output?

**Comment by xxthunder** [comment]
@zoof  Hi, any update here? Found this issue because we are having the same problem. scoop cannot install 7zip due to extraction failure. But we get a 1601 exit code. Regards, Karsten

**Comment by zoof** [comment]
@xxthunder Sadly no.  I had a system admin install 7zip for me and then ran `scoop config 7ZIPEXTRACT_USE_EXTERNAL true`.  I also had to add the 7zip directory to the `PATH`.  At that point, I was able to install most everything else -- 7zip still wouldn't install and for some reason I was unable to install geany.

**Comment by HUMORCE** [comment]
@zoof @xxthunder @juanjosegarciaripoll 

for issue about msi extraction, try `scoop config MSIEXTRACT_USE_LESSMSI true`

**Comment by xxthunder** [comment]
@zoof @HUMORCE Thank you guys, that solved our problems.

**Comment by zoof** [comment]
I'm not sure that this issue is actually resolved.  I have an up-to-date lessmsi installed and scoop is configured to use it but I am still unable to install 7zip -- instead of the error code I reported earlier, it now fails with code -1.  It is able to unpack some of the 7zip package but then fails on one file (`en.ttt`).  The msi.log is:
```
$ cat .\scoop\apps\7zip\21.06\msi.log
Extracting 'C:\Users\username\scoop\apps\7zip\21.06\7z2106-x64.msi' to 'C:\Users\username\scoop\apps\7zip\21.06\_tmp\'.
1/106   7zFM.exe
2/106   7-zip32.dll
3/106   7-zip.dll
4/106   7zG.exe
5/106   7z.dll
6/106   7z.exe
7/106   7z.sfx
8/106   7zCon.sfx
9/106   descript.ion
10/106  History.txt
11/106  License.txt
12/106  readme.txt
13/106  7-zip.chm
14/106  en.ttt

Error: System.Exception: Error 'MSPACK_ERR_OPEN' extracting file to \\?\C:\Users\To_T\scoop\apps\7zip\21.06\_tmp\SourceDir\Files\7-Zip\Lang\en.ttt.
   at LibMSPackN.MSCompressedFile.ExtractTo(String destinationFilename)
   at LessMsi.Msi.Wixtracts.ExtractFiles(Path msi, String outputDir, MsiFile[] filesToExtract, AsyncCallback progressCallback)
   at LessMsi.Cli.Program.DoExtraction(String msiFileName, String outDirName, List`1 filesToExtract)
   at LessMsi.Cli.ExtractCommand.Run(List`1 allArgs)
   at LessMsi.Cli.Program.Main(String[] args)
```
