### ISSUE TITLE
Can I auto  run a custom post_install scripts?

### ISSUE THREAD

**Issue by fcying** [ScoopInstaller/Scoop#4029]
after `scoop update *` or `scoop install app`, can I auto run a custom scripts?
ex: after `update` or `install` bandizip, I will run a script to register right menu.
How can I auto run this script?

**Comment by archit9169** [comment]
Modify the manifest file to include post install scripts.

**Comment by fcying** [comment]
`manifest file` is the json in the bucket?
modify this file git repo will be changed.
may be effect `scoop update`?

**Comment by rashil2000** [comment]
Use a custom bucket or manifest.
