### ISSUE TITLE
piping mechanism of "scoop list"

### ISSUE THREAD

**Issue by xarthurx** [ScoopInstaller/Scoop#4030]
So for a normal "ls" command to list files, I can do pipe like `ls | grep xxx` to filter out the things I care about.

However, for the command "scoop list" to list all software installed by scoop, commands like:

`scoop list | grep xxx`
`scoop list | rg xxx`

all failed by relisting all the software installed.
The grepping mechanism doesn't work.

Is this sth related to the design of scoop?

**Comment by archit9169** [comment]
I think list command is still using write-host instead of write-output and thus it fails when pipelining. Or maybe i am wrong and this is because of some other issue.

**Comment by Playacem** [comment]
You can use `scoop export` instead. That has the same information but writes to the pipeline instead.

**Comment by sebma** [comment]
@Playacem Why keep both `scoop export` and `scoop list` ?
Or if you want to keep both, is it harmfull to do a Seach&Replace of `Write-Host` by `Write-Output` inside the `scoop list` code ?

**Comment by rashil2000** [comment]
Write-Host and Write-Output are extremely different, so no, they're not interchangeable in the code

**Comment by sebma** [comment]
@r15ch13 Oh I see. And it also seems that `Write-Output` does not support coloring the text. Hence the two `scoop export` and `scoop list` functionalities.
