### ISSUE TITLE
The term 'D:\Scoop\shims\..\apps\scoop\current\bin\scoop.ps1' is not recognized?

### ISSUE THREAD

**Issue by xianzheTM** [ScoopInstaller/Scoop#4033]
This problem comes up frequently these two days.
![image](https://user-images.githubusercontent.com/25103583/84844942-22891b00-b07e-11ea-8a4e-13e4faca1107.png)
There was a warning when installing the app, but it seems to have worked. The same error occurs if you use commands like Scoop uninstall and Scoop Status.
![image](https://user-images.githubusercontent.com/25103583/84845103-7136b500-b07e-11ea-9acf-0d1a4e395e2b.png)
I used PowerShell 7.0.1.

**Comment by jcyongqin** [comment]
I have a temporary solution.

open powershell in admain

`cd ${the scoop install path}\apps\scoop ` .  In there, you can find `new\bin\scoop.ps1`
what we need is link the `current` to `new`.

so exec this ` New-Item -Path ./current -ItemType SymbolicLink -Value .\new\`

**Comment by DLopezJr** [comment]
This also just happened to me. Why is this happening?
