### ISSUE TITLE
Using compact.exe to reduce size of installed apps

### ISSUE THREAD

**Issue by ftk** [ScoopInstaller/Scoop#4034]
Windows 10 includes compact.exe tool which can transparently compress files.

I made the following simple script (put in libexec/scoop-compact.ps1) to compact exe and dll files and achieved ~2.5x-3x compression ratio on average.
```powershell
# Usage: scoop compact <app>
# Summary: Compacts exe and dll files using compact.exe
param($app)

. "$psscriptroot\..\lib\core.ps1"
. "$psscriptroot\..\lib\help.ps1"
. "$psscriptroot\..\lib\manifest.ps1"
. "$psscriptroot\..\lib\buckets.ps1"

reset_aliases

if(!$app) { my_usage; exit 1 }

$app_path = versiondir $app 'current' $false
if(!(Test-Path $app_path)) {
    $app_path = versiondir $app 'current' $true
}

if(Test-Path $app_path) {
    # compact *.exe and *.dll
    compact /c /exe:lzx @(Get-ChildItem -LiteralPath $app_path -File -Recurse | Where { $_.extension -In ".exe", ".dll" } | % { $_.FullName })
} else {
    abort "Could not find app path for '$app'."
}

exit 0
```
Maybe it is worth it to somehow allow user to configure auto-compacting after install/update.

**Comment by Calinou** [comment]
Keep in mind compressing binaries will make them slower to start, since they have to be extracted every time they're started (unlike `compact` uses some sort of caching mechanism).

**Comment by rashil2000** [comment]
This is not something that Scoop is supposed to do; if a user wants to compress there apps, they can do it themselves.

**Comment by WyvernIXTL** [comment]
I think this would be great to add, at least as option. A user normally does not think about storage until it is too late. Some applications only need to be used sometimes, but are very large. For example any bun compiled typescript code becomes a 100MB executable. If I do not need to use that tool often, the size becomes burdensome.

Compressing every executable as @rashil2000 stated maybe does not make sense, but the manifest should have an easy toggle to enable compression with [`compact`](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/compact). `compact` is much better than UPX for the startup of programs and ram usage.

When I tested with my own program `crop4mkv` the uncompressed executable executed in 106ms, the compact compressed executable was slightly slower with 113ms, while the UPX compressed program took over 500ms.
The executable is 116MB in size, the `compact` with LZX compressed executable is 38MB in size and the UPX compressed with `--best` option is also 38MB in size.

I added the `compact` command execution to the `post_install` script, but I really think, that this should be a settable option for the manifest.


https://github.com/WyvernIXTL/stupid-bucket/blob/bd8877eaff8aa93f7c90c52b822b115248567b01/bucket/crop4mkv.json#L25-L29

**Comment by WyvernIXTL** [comment]
`compact` actually does exactly what [this post in upx repo](https://github.com/upx/upx/discussions/723) suggested for linux with squashfs. `compact` just simply uses the NTFS compression, which is very fast.
I doubt that people that search for how to make their executables take up less disk space, stumble over `compact` that easily.
