### ISSUE TITLE
Pinning "current" exe takes about half a minute (24 seconds) to close

### ISSUE THREAD

**Issue by mangelozzi** [ScoopInstaller/Scoop#4037]
This issue occured when I updated to `Microsoft Windows [Version 10.0.19041.329]`

Related issue: <https://github.com/equalsraf/neovim-qt/issues/708>

I pinned to the task bar:  
`C:\Users\Michael\scoop\apps\neovim-nightly\current\bin\nvim-qt.exe`
When I try to close Neovim, it will hang (freeze) for about 24 seconds. Once it eventually closes I can then open and close it fine immediately for a short while, before returning to the 24 second delay on the next close.

Pinning the "none current" exe does not have this problem:  
`C:\Users\Michael\scoop\apps\neovim-nightly\nightly-20200618\bin\nvim-qt.exe`

**Comment by iguyking** [comment]
@michael-angelozzi I installed the version from 20200619 and it opens and closed immediately.  What does your `~\AppData\Local\nvim\init.vim` file look like?

**Comment by michael-angelozzi** [comment]
My VimRC file is quite complex, but i had the same behaviour with no vimrc file.

**Comment by iguyking** [comment]
Other thoughts on how we can reproduce this?   It works as expected in my testing.   Anti-virus software being used?
