### ISSUE TITLE
add bucket commoand should use git --depth=1

### ISSUE THREAD

**Issue by lihongjie0209** [ScoopInstaller/Scoop#4044]
## Clone time test  

use ` --depth=1` is two time faster then normal clone

```
PS D:\code> Measure-Command {git clone --depth=1 https://github.com/lukesampson/scoop-extras.git}
Cloning into 'scoop-extras'...
remote: Enumerating objects: 1159, done.
remote: Counting objects: 100% (1159/1159), done.
remote: Compressing objects: 100% (1131/1131), done.
Rremote: Total 1159 (delta 51), reused 278 (delta 26), pack-reused 0eceiving objects:  98% (1136/1159), 516.00 KiB | 1012.00 KiB/s
Receiving objects: 100% (1159/1159), 585.19 KiB | 1.08 MiB/s, done.
Resolving deltas: 100% (51/51), done.


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 5
Milliseconds      : 587
Ticks             : 55877764
TotalDays         : 6.4673337962963E-05
TotalHours        : 0.00155216011111111
TotalMinutes      : 0.0931296066666667
TotalSeconds      : 5.5877764
TotalMilliseconds : 5587.7764
```

```
PS D:\code> Measure-Command {git clone  https://github.com/lukesampson/scoop-extras.git}
Cloning into 'scoop-extras'...
remote: Enumerating objects: 62312, done.
remote: Total 62312 (delta 0), reused 0 (delta 0), pack-reused 62312
Receiving objects: 100% (62312/62312), 13.86 MiB | 2.79 MiB/s, done.
Resolving deltas: 100% (43442/43442), done.


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 9
Milliseconds      : 122
Ticks             : 91222573
TotalDays         : 0.000105581681712963
TotalHours        : 0.00253396036111111
TotalMinutes      : 0.152037621666667
TotalSeconds      : 9.1222573
TotalMilliseconds : 9122.2573

```

**Comment by koitsu** [comment]
Offending code as of this writing: https://github.com/ScoopInstaller/Scoop/blob/f93028001fbe5c78cc41f59e3814d2ac8e595724/lib/buckets.ps1#L141-L151

1. `git clone --depth=1 --no-tags single-branch` should help even more
2. Another approach is not to use git at all, but instead use GitHub's tarball or zipball features: https://blog.abelotech.com/posts/how-download-github-tarball-using-curl-wget/ or https://stackoverflow.com/a/18222354 -- but this is only applicable if no other git-related commands are used throughout scoop (I'm new to it so I'm unsure)
3. This isn't just about real-world time or CPU time, it's also about disk space and network traffic.  For `Extras`, we're talking 3-4MBytes vs. 41MBytes at present.  GitHub would appreciate such efforts; every little bit counts.

**Comment by rashil2000** [comment]
Filing this under https://github.com/ScoopInstaller/Scoop/issues/4881
