### ISSUE TITLE
Calibre does not launch with error "Path to Calibre Portable (....) too long'

### ISSUE THREAD

**Issue by shoan** [ScoopInstaller/Scoop#4049]
![image](https://user-images.githubusercontent.com/333168/86152413-bf879180-bb1d-11ea-8acc-69199beab884.png)

**Comment by Cupbox** [comment]
As mentioned in #4011, this is a [calibre-portable](https://www.mobileread.com/forums/showthread.php?t=142913) issue. Use normal Calibre instead

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Extras/issues/2535
