### ISSUE TITLE
Reporting Scoop updating error.

### ISSUE THREAD

**Issue by midaspt** [ScoopInstaller/Scoop#4050]
It isn't the first time it happens but just now when I ran:

`> scoop update *`

in my Windows 7 (x64), I got the following error and the updating fails.

```
Invalid URI: The URI is empty.
At D:\_PROGS\_CLI\scoop\apps\scoop\current\lib\install.ps1:130 char:9
+         throw $e
+         ~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], UriFormatException
    + FullyQualifiedErrorId : Invalid URI: The URI is empty.
```

To be able to update the remaining apps, I have to put the programs affected on `hold` -- currently, **cudatext** and **mp3directcut**.

My **Powershell** version:

```
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      14409  1018
```

**Comment by midaspt** [comment]
Reported errors are still present today.

**Comment by xianzheTM** [comment]
> Reported errors are still present today.

install innounp or undate innounp

**Comment by midaspt** [comment]
> > Reported errors are still present today.
> 
> install innounp or undate innounp

Thanks, but it was installed all along.

```
PS > scoop update innounp
innounp: 0.49 (latest version)
Latest versions for all apps are installed! For more information try 'scoop status'
```

Update error still present.

**Comment by oceanborn2** [comment]
Hello, I have just had this error too. It seems the installer is looking for "https://www.fosshub.com/CudaText.html/cudatext-win-x64-1.109.2.2.zip"  instead of "https://www.fosshub.com/CudaText.html?dwl=cudatext-win-x64-1.109.2.2.zip".  It works from a browser but not from curl / wget (invalid argument)

**Comment by midaspt** [comment]
It really sucks that such a simple error (replace "_/_" with "_?dwl=_" in download URL) has now been open for **two whole months**!
