### ISSUE TITLE
Git not working with scoop

### ISSUE THREAD

**Issue by Alien10123** [ScoopInstaller/Scoop#4054]
I am trying to install stripe ci with scoop, but when i install git it comes up with the error code 2. When i get it from the github website, it is the same as installing it. It knows it is there, but the same if I run the command scoop install git, but there is no error. How do I fix this??

**Comment by MorphicResonance** [comment]
git installed but not working properly under scoop . unable to update any apps.
problem with post-install scriptsa step.

`Running post-install script...
Unrecognized name 'git'

+ git config --global credential.helper manager
+ ~~~
    + CategoryInfo          : ObjectNotFound: (git:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
`

**Comment by OneManMonkeySquad** [comment]
Just to be sure: Have you tried a new shell window?
