### ISSUE TITLE
funny error message when git is uninstalled

### ISSUE THREAD

**Issue by steveklabnik** [ScoopInstaller/Scoop#4056]
I was reinstalling git for Reasons, and so I had run

```console
> scoop uninstall git
```

I then wanted to reinstall it, so I tried, and got this message:

![image](https://user-images.githubusercontent.com/27786/86840025-d2dbb500-c067-11ea-9f5b-5055aa133d4d.png)

that is, of course, what I'm already doing! It worked, but the message is kind of amusing :)

**Comment by rashil2000** [comment]
The message was shown because Scoop was outdated (it has a period of 3 hours) and it tried to update the buckets first.
