### ISSUE TITLE
iex: An exception occurred when calling "SetEnvironmentVariable" with "3" parameters: "Trying to perform an unauthorized operation."

### ISSUE THREAD

**Issue by qgxcry** [ScoopInstaller/Scoop#4060]
iwr -useb get.scoop.sh | iex
Initializing...
Downloading scoop...
Extracting...
Creating shim...
Downloading main bucket...
Extracting...
Adding ~\scoop\shims to your path.
iex: An exception occurred when calling "SetEnvironmentVariable" with "3" parameters: "Trying to perform an unauthorized operation."
Location Line: 1 Character: 26
+ iwr -useb get.scoop.sh | iex
+ ~~~
     + CategoryInfo: NotSpecified: (:) [Invoke-Expression], MethodInvocationException
     + FullyQualifiedErrorId: UnauthorizedAccessException, Microsoft.PowerShell.Commands.InvokeExpressionCommand

**Comment by wholegale39** [comment]
Can you solve the problem？

**Comment by PeerXu** [comment]
I got the same problem, because the Windows PC installed the "360杀毒软件", an antivirus software.
finally, I quit the antivirus and reinstall scoop again, it is solved.
