### ISSUE TITLE
Rolling back incorrect install

### ISSUE THREAD

**Issue by haristz** [ScoopInstaller/Scoop#4063]
I misinterpreted the instructions for installing scoop on a non-default directory and wanted to ask if the process I followed to recover is OK or if I missed something.
*What I (erroneously) did:* I ran the scoop install script with no changes and then I changed the SCOOP environment variable to a different directory. I then installed packages, which after an initial error message ended up in the new directory (so scoop created additional new directories at the new location). Only the initial (default) shim directory was however added to my path and I had to add the "extra" shim directory for the packages manually. I also changed the default global install folder env variable but did not install any global packages.
*How I corrected (?) it:* When I realized my error, I used "scoop uninstall scoop" to remove the custom directory. I then changed the SCOOP env variable to its default (ie C:\Users\<user>\scoop) and reran "scoop uninstall scoop".
This took out the folder with the scoop executables.
I then deleted the SCOOP env variables (user + global) and reinstalled everything following the "custom directory" instructions correctly (ie first change the env variable and then run installer).
It seems to have worked but I wanted to ask if I missed anything.
Thanks!

**Comment by rashil2000** [comment]
Seems fine
