### ISSUE TITLE
Scoop unable uninstall node-lts ERROR Couldn't remove '~\scoop\apps\nodejs-lts\8.11.3'; it may be in use.

### ISSUE THREAD

**Issue by samk-ayyagari** [ScoopInstaller/Scoop#4072]
While try to uninstall nodejs-lts I am getting the following error.

**scoop uninstall nodejs-lts**
**ERROR Couldn't remove '~\scoop\apps\nodejs-lts\8.11.3'; it may be in use.**

when I check scoop info nodejs-lts  it shows me the path environmental variables

How to check where exactly it is being used ? 

Cant we force uninstall it ?

**Comment by NotWearingPants** [comment]
https://www.techsupportalert.com/content/how-find-out-which-windows-process-using-file.htm

In Windows you can't delete a file while it is being used, so no you can't force uninstall.
