### ISSUE TITLE
Scoop add bucket/update inconsistent proxy setup

### ISSUE THREAD

**Issue by taro-ball** [ScoopInstaller/Scoop#4086]
I've found the following issue when using scoop behind proxy that requires NTLM authentication:

If you try to run `scoop config proxy currentuser@proxy.example.org:8080` and then `scoop bucket add extras` it won't work because scoop passes these credentials directly to git and git has a different proxy format. So for "bucket add" to work you will have to change the proxy string to the format git understands so `currentuser@proxy.example.org:8080` becomes `:@proxy.example.org:8080`

```
# 'add' wont work with standard scoop proxy setup as discribed in https://github.com/lukesampson/scoop/wiki/Using-Scoop-behind-a-proxy :
scoop config proxy 'currentuser@proxy.example.org:8080'
scoop bucket add extras #this fails
# lets change to git proxy format:
scoop config proxy ':@proxy.example.org:8080'
scoop bucket add extras # now 'add' works
# but 'install' won't work, because proxy is still in git format
scoop install vscode # this fails
# now we change back to scoop format
scoop config proxy 'currentuser@proxy.example.org:8080'
scoop install vscode # 'install' works now
```

**Comment by rashil2000** [comment]
#1615
