### ISSUE TITLE
scoop shim executables can fail if invoked with short paths

### ISSUE THREAD

**Issue by nickhutchinson** [ScoopInstaller/Scoop#4089]
The shim executables scoop creates look for a .shim file with the same basename as the shim executable without the ".exe" suffix. However they don't account for [Win32 short path names](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#short-vs-long-names), which can alter the basename, and this can be a problem, for example:

```powershell
> & $home\scoop\shims\clang++.exe --version
clang version 10.0.0

> (New-Object -ComObject Scripting.FileSystemObject).GetFile("$home\scoop\shims\clang++.exe").ShortPath
C:\Users\NICKHU~1\scoop\shims\CLANG_~1.EXE

> & C:\Users\NICKHU~1\scoop\shims\CLANG_~1.EXE --version
Couldn't find CLANG_~1.shim in C:\Users\Nick Hutchinson\scoop\shims
```

Note that some common build systems (e.g. CMake) will invoke tools using Win32 short paths.

[supporting/shimexe/shim.cs](https://github.com/lukesampson/scoop/blob/master/supporting/shimexe/shim.cs) likely needs to resolve the current exe path to its long path name before looking for the accompanying .shim file.

**Comment by rashil2000** [comment]
We recently switched to https://github.com/kiennq/scoop-better-shimexe as the default. Does this issue occur there too?
