### ISSUE TITLE
A dependency avoided with --independent is installed when running scoop update

### ISSUE THREAD

**Issue by daniel-a-melo** [ScoopInstaller/Scoop#4102]
I installed `gitui` with the flag `--independent` to avoid having the packaged `git` installed as a dependency. 

`scoop install gitui --independent`. 

However, when gitui is updated the package `git` is installed again.

**Comment by rashil2000** [comment]
The `scoop update` command also supports `-i, --independent` flag. Use that.

**Comment by daniel-a-melo** [comment]
However, if you run `scoop update *`  it does not honor the `-i` flag used on install. It will install dependencies and that's exactly what it was not instructed to do during install

**Comment by ltGuillaume** [comment]
I don't think `scoop update *` should install dependencies in _any_ case. Instead, it should warn about depencies that aren't installed.

**Comment by rashil2000** [comment]
#3800
