### ISSUE TITLE
How do I find shims for an installed app?

### ISSUE THREAD

**Issue by david-bakin** [ScoopInstaller/Scoop#4111]
Given an installed app by its name, how do I find which shims launch it?  (via scoop command - I guess I could grep in $HOME/scoop/shims but that shouldn't be necessary...)

**Comment by PrefixCoder** [comment]
A regular `which` command? Not the `scoop which` one, that always shows path to exe in apps folder.

**Comment by rashil2000** [comment]
> Given an installed app by its name, how do I find which shims launch it?

The `scoop info <app>` command will list the shims the app uses.
