### ISSUE TITLE
[Question] Automatic (per background service?) 'scoop update *' as soon as an update for an app exists?

### ISSUE THREAD

**Issue by 7wells** [ScoopInstaller/Scoop#4112]
Hello,

I see the following:

```
PS C:\Users\user> scoop status
Scoop is up to date.
Updates are available for:
    beyondcompare: 4.3.5.24893 -> 4.3.6.25063
    github: 2.5.3 -> 2.5.5
    gpg: 2.2.22 -> 2.2.23
    uniextract2: 2.0.0-rc.2 -> 2.0.0-rc.3
Everything is ok!
```

Would it be recommandable to have an app automatically updated as soon as an update exists?
If yes, how could `scoop update *` be invoked? I assume that some continuous background service would be needed for this. Would this be possible at all? Thanks for your help (and sorry if this is not the right place to ask this)!

**Comment by rashil2000** [comment]
#3633
