### ISSUE TITLE
Not found Error when installing gcc

### ISSUE THREAD

**Issue by Celthund** [ScoopInstaller/Scoop#4132]
When trying to install gcc with `scoop install gcc`, the following lib gives a error when trying to download.

```
The remote server returned an error: (404) Not Found.
URL http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-libtasn1-4.9-1-any.pkg.tar.xz is not valid
```

Is there a way to change it manually? Since in the repository exists the following versions:
```
mingw-w64-x86_64-libtasn1-4.15.0-1-any.pkg.tar.xz
mingw-w64-x86_64-libtasn1-4.16.0-1-any.pkg.tar.xz
```

**Comment by wstein** [comment]
There are other files missing, at least:

    http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-libtasn1-4.9-1-any.pkg.tar.xz
    http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-p11-kit-0.23.9-1-any.pkg.tar.xz
    http://repo.msys2.org/mingw/i686/mingw-w64-i686-libtasn1-4.9-1-any.pkg.tar.xz
    http://repo.msys2.org/mingw/i686/mingw-w64-i686-p11-kit-0.23.9-1-any.pkg.tar.xz

please refer: ScoopInstaller/Main#1485

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Main/issues/1752
