### ISSUE TITLE
 How to write search query in list/search? Is there any docs?

### ISSUE THREAD

**Issue by shutaozhenzhen** [ScoopInstaller/Scoop#4138]
I want to find all apps in a bucket installed by me. What is the search query? I try to find docs telling me How to write search query but I failed.

**Comment by Calinou** [comment]
There's `scoop list` to find all installed packages, but I don't think there's a built-in option to filter on a per-bucket basis. I guess you could use `grep` or an equivalent on the output of `scoop list` to achieve this.
