### ISSUE TITLE
Can Scoop have an auto start function?

### ISSUE THREAD

**Issue by shutaozhenzhen** [ScoopInstaller/Scoop#4156]
By using a list of shims, divided by sudo or not sodu. Then I can menage my apps' auto start function by scoop.

Or is there any app for me to gain the target of manage my auto start program?

**Comment by jedieaston** [comment]
You can add shortcuts to applications/files into your user's startup directory and they will start on login.

https://support.microsoft.com/en-us/windows/add-an-app-to-run-automatically-at-startup-in-windows-10-150da165-dcd9-7230-517b-cf3c295d89dd
