### ISSUE TITLE
Malwarebytes Interfeers with Scoop Downloads

### ISSUE THREAD

**Issue by ntcarver0** [ScoopInstaller/Scoop#4157]
It appears that Malwarebytes interferes with Scoop downloads. When Malwarebytes is operating, hash checks fail for several downloads such as LAME, however when the application's real-time scanning functionality is disabled these problems do not occur. Is this fixable? What paths should I exclude from Malwarebytes?

**Comment by gordlord** [comment]
> PS C:\Users\Gordon Freeman> scoop install lame
> Installing 'lame' (3.100.1) [64bit]
lame3.100.1-x64.zip (1,2 MB) [================================================================================] 100%
> Checking hash of lame3.100.1-x64.zip ... ok.
> Extracting lame3.100.1-x64.zip ... done.
> Linking ~\scoop\apps\lame\current => ~\scoop\apps\lame\3.100.1
> Creating shim for 'lame'.
> 'lame' (3.100.1) was installed successfully!

No problems here with Malwarebytes Version 4.3.0 with all security modules enabled.
