### ISSUE TITLE
Some people reporting that Paint.NET file detected as malware during scoop update

### ISSUE THREAD

**Issue by quantuumsnot** [ScoopInstaller/Scoop#4159]
`D:\scoop\apps\paint.net\4.2.14\SourceDir\Bundled\AvifFileType\AvifFileType.dll`

Heuer, detected by COMODO CIS 12.0.0.6818

**Comment by rashil2000** [comment]
Add an exception for the Scoop folder in your antivirus

**Comment by quantuumsnot** [comment]
> Add an exception for the Scoop folder in your antivirus

Outstanding idea, dude

**Comment by rashil2000** [comment]
I know, thanks

**Comment by quantuumsnot** [comment]
![image](https://user-images.githubusercontent.com/12394810/148592654-e6c8f25d-265a-486c-9486-ee3fb20136ad.png)

**Comment by rashil2000** [comment]
![image](https://user-images.githubusercontent.com/46838874/148593916-b3c04d51-018f-41a1-b725-ff51d8f8c5ef.png)

**Comment by quantuumsnot** [comment]
I highly doubt ... And started asking myself two things:
1. How old are you (have a feeling about missing some common sense)
2. Who are your security teachers


P.S. btw you can read [code of conduct]https://github.com/ScoopInstaller/.github/blob/b54fecd3fc818779011f5c75100a0ceaeb44d786/.github/CODE_OF_CONDUCT.md) and see who first made a mistake here in the issue

Bye
