### ISSUE TITLE
Failed to connect to 127.0.0.1:1080. Connection refused.

### ISSUE THREAD

**Issue by JYShaw** [ScoopInstaller/Scoop#4165]
shaw D:\PCO ❯❯❯ scoop update *
Updating Scoop...
fatal: unable to access 'https://github.com/lukesampson/scoop/': Failed to connect to 127.0.0.1 port 1080: Connection refused
Update failed.
shaw D:\PCO ❯❯❯ scoop config proxy
127.0.0.0.1:7890

and proxy in config.json is  "proxy":  "127.0.0.0.1:7890" .
I tried to run scoop config rm proxy and set the proxy again. But it didn't work. It still use 1080 port rather than 7890

**Comment by devdanzin** [comment]
Two observations: it doesn't seem to hit the `Failed to use proxy...` message from ` setup_proxy()` in `core.ps1`. And your proxy IP has an extra octet: 127.0.0.**0**.1.

Can you sprinkle some `write-output` calls in `setup_proxy()` to figure out when the proxy port becomes 1080?

**Comment by fungtion** [comment]
@WilsonShaw Have you set git proxy before?

**Comment by jiayaoO3O** [comment]
@WilsonShaw I found that @fungtion  is right, if your **git** has set the proxy value, then no matter how you set the `scoop config proxy` , it will use the configuration in the **.gitconfig** file, so the answer is to just fix the wrong proxy information in `.gitconfig`.
