### ISSUE TITLE
git config --global merge.verifySignatures true breaks Scoop updates

### ISSUE THREAD

**Issue by 0x326** [ScoopInstaller/Scoop#4166]
## Issue

A user might set `git config --global merge.verifySignatures true` according to their typical Git workflow.  Enabling this setting breaks Scoop's `git pull` since buckets typically do not sign Git commits.

## Solution

Set `git config --local merge.verifySignatures false` in `~/scoop/buckets` repositories or run `git pull --no-verify-signatures` when performing updates.

**Comment by magneticflux-** [comment]
Globally requiring signatures would break _many_ Git repos, so I don't think it's really an issue with Scoop in particular. I would instead recommend setting `merge.verifySignatures` on a per-repository basis, especially if you work with other Git repos.

As a workaround, you might be able to run `git config --local merge.verifySignatures false` in each of the buckets' clones to disable signature verification.

**Comment by FriendlyNeighborhoodShane** [comment]
@magneticflux- That's true, but I still don't think that the package manager should break when it's easily avoidable, a user could just set it not having Scoop in mind.

Scoop should clone repos with the flags `-c merge.verifySignatures=false` or set the config locally, just in case.

**Comment by rashil2000** [comment]
See #3707
