### ISSUE TITLE
How do I derive/copy/export a list of apps in buckets I subscribe to?

### ISSUE THREAD

**Issue by umbellipher** [ScoopInstaller/Scoop#4174]
Alongside Scoop, I use conemu (linked to Powershell 7.1) and have alias-additions installed.

I want to export or paste-and copy into a text editor all apps contained in the buckets to which I subscribe.

'scoop info-all' generates a long list. What do I do next, either to select-all-copy-paste, or to export, not just what's on the screen, but the whole generated list?

Or is there a more sane way of listing, and saving, a list of all the apps available in my buckets?

Thanks!

**Comment by Deide** [comment]
In powershell: `scoop bucket list |% { echo "$_"; gci $env:SCOOP/buckets/$_/bucket |% { echo "    - $($_.BaseName)" } }`.
If you want it in a file, then append ` > apps.txt` to the end of that line.

You can play around with that. If you don't have the `SCOOP` environment variable, then just replace `$env:SCOOP` with the path to your scoop installation.

**Comment by umbellipher** [comment]
Thank you, Deide: that is so very helpful!

The output is in list form: names of apps only. I was rather hoping for info form, such that there would be the description of each app that you get when you use 'info' or 'info-all'.

Is there a way to do that? Many thanks!

**Comment by Deide** [comment]
What kind of format are you looking for, exactly? CSV? JSON?
If you just want to look through all the apps in the buckets you have, you can just look in the buckets folder. The manifests are simple json files.

If you want to get an idea of how to parse them on the command line, you can do something like `$curlManifest = cat $env:SCOOP/buckets/main/bucket/curl.json | ConvertFrom-Json` and then use the variable as you see fit `$curlManifest.description`.

**Comment by rashil2000** [comment]
Use `scoop export`
