### ISSUE TITLE
Support for Github Sponsors

### ISSUE THREAD

**Issue by shurane** [ScoopInstaller/Scoop#4175]
Any idea of setting up support for https://github.com/sponsors? 

The money could help for using VMs for testing packages, testing different versions of Windows (i.e. Home vs Pro vs Server 2019 vs LTSB, x86 vs x86_64 vs ARM). 

I back a few projects and developers on Github for software I get a lot of value out of. And I definitely get a lot of value out of `scoop`. I'm sure I'm not the only one that would be interested in pitching in, either.

**Comment by Calinou** [comment]
> The money could help for using VMs for testing packages

We can use free CI services for that already :slightly_smiling_face: 

> testing different versions of Windows (i.e. Home vs Pro Server 2019 vs LTSB, x86 vs x86_64 vs ARM).

Scoop doesn't support ARM yet, only x86 and x86_64 are supported. It was developed in an area where Windos was only available in x86 (in non-RT form).

**Comment by shurane** [comment]
> We can use free CI services for that already 🙂

True, was mainly a suggestion. The money could also go towards funding developer work or hardware costs. 

As a developer, I thought it might be nice to have a way to contribute to the project for those (like me) who can't contribute with their time.

One question Regarding AppVeyor and CI on scoop. It seems like it only supports Windows Server builds -- wouldn't it be helpful to also be able to test Windows 7, 8, and 10 at least?

> Scoop doesn't support ARM yet 

I mentioned ARM mainly because of [Windows 10x](https://docs.microsoft.com/en-us/dual-screen/windows/get-dev-tools), which I can see getting more interest when other laptop manufacturers start making ARM Windows devices.

> Likewise, most ISVs don't provide Windows ARM builds of their software yet.

I think a lot of tools from *nix (7z, rsync, etc) have an ARM variant already.

**Comment by rashil2000** [comment]
Scoop supports Windows on Arm now, and there's a GitHub Sponsors profile that you can donate to ☺️
