### ISSUE TITLE
Windows feature upgrade moves all scoop shortcuts into Windows.old

### ISSUE THREAD

**Issue by Luckz** [ScoopInstaller/Scoop#4176]
Every time there's a bi-yearly Windows upgrade (20H2 / 2009 most recently), both the shortcuts scoop created in the Start Menu as well as my own (Quick Launch or whatever) are moved to `C:\Windows.old\...`.
I assume this is because whatever faulty logic MS uses to detect no longer valid shortcuts does not understand junctions (scoop's `current`)?

I have reported this to Microsoft a long time ago, but it's evidently not addressed.

Would using symbolic links instead of junctions help avoid this?

**Comment by brunovieira97** [comment]
That's probably done because Windows does not allow SymLinks to be created without admin privileges. Would break Scoop's user-only installs without UAC objective.

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Scoop/issues/3941
