### ISSUE TITLE
Held apps color is not visible in Scoop List

### ISSUE THREAD

**Issue by vsDizzy** [ScoopInstaller/Scoop#4179]
There was an asterisk `*` indicating apps on hold and now it is gone.

![image](https://user-images.githubusercontent.com/5798340/99748326-f9fdc500-2ae4-11eb-8f09-513008adbc94.png)

**Comment by chawyehsu** [comment]
They are "hidden" in those spaces between version number and bucket name (e.g. `adb 30.0.5` and `main`)

**Comment by h0lg** [comment]
> They are "hidden" in those spaces between version number and bucket name (e.g. `adb 30.0.5` and `main`)

Do you mean more than one space between version number and bucket name indicates the app is on hold? That's what I can observe in my list.

Could this status not be made explicit? Like
```
adb 30.0.5 *hold* [main]
```

instead of
```
adb 30.0.5        [main]
```

**Comment by chawyehsu** [comment]
@h0lg No, the actual reason is the color of `*hold*` is the same as your terminal background color, therefore you can't see it. Changing to another color scheme may help.

**Comment by h0lg** [comment]
@chawyehsu I see now. Just copied the output from my PS using the default theme and pasted it into an editor. Maybe the font color choice for this status is not the best then? Also, what a weird coincidence that it uses the exact same syntax as my random an manually typed (!) proposal above.

**Comment by vsDizzy** [comment]
I believe this should work well for the default PS theme. But it is not.
![image](https://user-images.githubusercontent.com/5798340/102024429-bbcd8b80-3d9a-11eb-8721-a909152b8fdb.png)
