### ISSUE TITLE
`$url.sha256` can't work on file ending with '`r`n'

### ISSUE THREAD

**Issue by Vixb1122** [ScoopInstaller/Scoop#4180]
```
"hash": {
    "url": "$url.sha256"
}
```
can't find hash in [.sha256](https://github.com/JanDeDobbeleer/oh-my-posh3/releases/download/v3.43.2/posh-windows-amd64.exe.sha256) file ending with '\r\n'

**Comment by Ash258** [comment]
Intended..

https://github.com/lukesampson/scoop/blob/643cfb0da8369dbbe2964511698763c5ff179492/lib/autoupdate.ps1#L53-L55

**Comment by Vixb1122** [comment]
https://github.com/lukesampson/scoop/blob/643cfb0da8369dbbe2964511698763c5ff179492/lib/autoupdate.ps1#L54

Why not replace `'^([a-fA-F0-9]+)$'` with `'^([a-fA-F0-9]+)\s*$'`

**Comment by rashil2000** [comment]
Closed in #4619
