### ISSUE TITLE
Allow the shim to provide a capability of setting the ANSI support

### ISSUE THREAD

**Issue by trajano** [ScoopInstaller/Scoop#4182]
In Windows Terminal some older (or current) console apps do not set a flag to enable ANSI console support.  To work around this, I use `ansicon` available in scoop before the command.  

An example of a program that does not set the ANSI console support is awscli.

So when you do `aws logs tail --follow ...` you will get the ANSI codes written out.  So what I do is have an alias so that I get `ansicon aws logs tail --follow ...`

**Comment by rashil2000** [comment]
I don't think this has anything to do with Scoop. If AWS CLI binary does not support it, we can't either.
