### ISSUE TITLE
Add cache / clean up message to `status`

### ISSUE THREAD

**Issue by dsbert** [ScoopInstaller/Scoop#4191]
It's easy to forget and some may not even realize that old installers and programs are not automatically removed. There is no automatic process to do this either. Since `git cache` already displays the size on disk, it would be helpful to display this information when running `scoop status`.

Something like the following.

```
> scoop status
Scoop is using 4.6 GB for cached installers. Use "scoop cache rm" to free up space.
Scoop is using 9.1 GB for outdated application files.  Use "scoop cleanup" to free up space.
Scoop is up to date.
Everything is ok!
```

I think `apt` does something similar to this.

**Comment by rashil2000** [comment]
`scoop cache show`
