### ISSUE TITLE
Global 7zip ignored, 7ZIPEXTRACT_USE_EXTERNAL not working

### ISSUE THREAD

**Issue by Brawl345** [ScoopInstaller/Scoop#4195]
I've installed 7zip globally with scoop, but when I install an application which has `Expand-7zipArchive` (e.g. FreeTube from extras) it installs 7zip for the current user instead of taking the global install. I found the config key 7ZIPEXTRACT_USE_EXTERNAL, and set it to True, but it doesn't work, 7zip is still installed for the current user.

**Comment by bc-185** [comment]
I think this has already been reported. (see #3700)
