### ISSUE TITLE
allow user to keep both 32bit and 64bit version of app

### ISSUE THREAD

**Issue by KnaveM** [ScoopInstaller/Scoop#4196]
here is the problem:
i need to build c++ for both 32bit and 64bit platform, but the thing is gcc only support one platform, if i want to build for 32bit platform i need to uninstall the gcc, and then use` scoop install -a 32bit gcc` to install the 32bit version of gcc.
if i try to install the 64bit-version gcc, scoop tell me that i have already installed gcc.

it there any possible way that i can keep both 32bit and 64bit version of gcc by scoop.

any idea is appreciated. :)

![image](https://user-images.githubusercontent.com/33738071/101272091-fe53fe80-37c3-11eb-998b-3b72bd376455.png)
![image](https://user-images.githubusercontent.com/33738071/101272074-eed4b580-37c3-11eb-9819-905b49bb3f7f.png)

**Comment by rashil2000** [comment]
AFAIK, all 64bit compilers support generating 32bit binaries - with the use of flags like `-m32` or something.
