### ISSUE TITLE
[feature] Support custom plugins to scoop itself?

### ISSUE THREAD

**Issue by hyrious** [ScoopInstaller/Scoop#4198]
For example, I may want to use [fastgit](https://fastgit.org/) to speed up all github releases' download. Currently I can achieve that by doing something like this: https://gist.github.com/hyrious/754a8ff3134750fdb381b6e090fd493e

Although, powershell itself may not be a good choice to handle too many programming stuffs :/

**Comment by rashil2000** [comment]
#4264
