### ISSUE TITLE
scoop install kustomize fails

### ISSUE THREAD

**Issue by bo0ts** [ScoopInstaller/Scoop#4199]
`> scoop install kustomize
Installing 'kustomize' (3.9.0) [64bit]
Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden.
URL https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v3.9.0/kustomize_v3.9.0_windows_amd64.tar.gz is not valid`

The error message is in German but I guess the meaning is clear: installation of kustomize via scoop failed. The link returns 404.

**Comment by amalagaura** [comment]
Looks like they did not release the binaries for kustomize 3.9.0 on the releases page.

**Comment by rashil2000** [comment]
Fixed
