### ISSUE TITLE
Scoop not recognized in Powershell 7.1.0 and running fine in Powershell 5.1

### ISSUE THREAD

**Issue by BobMilli** [ScoopInstaller/Scoop#4203]
Hello,
I successfully installed scoop from a Powershell 5.1 prompt and it recognized when I type scoop but from a Powershell 7.1 prompt, it says "The term 'scoop' is not recognized...".
Thx
Bob

**Comment by brunovieira97** [comment]
Seems like Scoop is not present on your PATH. Can you check?
