### ISSUE TITLE
Make shims use fixed configuration files? GUI Application support?

### ISSUE THREAD

**Issue by bc-185** [ScoopInstaller/Scoop#4206]
I would like to have the exe in a separate directory from the configuration files. However, the shim looks for the configuration file in the directory its in. Is that possible? Also, does shim support GUI Applications?

**Comment by Onixmiha** [comment]
#4206

**Comment by rashil2000** [comment]
> Is that possible?

No. It needs to look in the same place for the .shim file.

> Also, does shim support GUI Applications?

Yes.
