### ISSUE TITLE
Unable to start Fork

### ISSUE THREAD

**Issue by djemar** [ScoopInstaller/Scoop#4208]
Installed Fork, it crashes at startup because it doesn't find the git instance that apparently it ships with. This is the log, it doesn't find its 7z instance, too.

I've already tried to edit its config file and point the gitInstance path to my install of git, but it ignores it and resets it to null.

Both git and 7z are installed through scoop on my pc.

> ?? 2020-12-25 21:22:44.062 Loading settings.
> ?? 2020-12-25 21:22:44.186 Start ipc server Fork_5620_Pipe_AskPass
> ?? 2020-12-25 21:22:44.186 Start ipc server Fork_5620_Pipe_Default
> ?? 2020-12-25 21:22:44.186 Waiting for next IPC event '708'
> ?? 2020-12-25 21:22:44.186 Waiting for next IPC event '708'
> ? 2020-12-25 21:24:22.393 7Zip not found at 'C:\Users\username\scoop\apps\fork\current\7z.exe'
> ?? 2020-12-25 21:24:22.393 Running 'C:\Users\username\AppData\Local\Fork\gitInstance\2.29.2.2\bin\git.exe' with arguments 'config --system credential.helper manager-core'.
> ? 2020-12-25 21:24:22.398 Cannot enable git credential manager for 'C:\Users\username\AppData\Local\Fork\gitInstance\2.29.2.2\bin\git.exe'
> ? 2020-12-25 21:24:22.398 System.ComponentModel.Win32Exception (0x80004005): Unable to find the specified file
>    in System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
>    in System.Diagnostics.Process.Start()
>    in Fork.Shell.Interaction.ShellRequest.Execute()
>    in Fork.Git.Commands.EnableGitCredentialManagerGitCommand.Execute(Boolean force)
> ?? 2020-12-25 21:24:36.692 Saving settings.
> ?? 2020-12-25 21:24:36.709 Stop ipc server Fork_5620_Pipe_Default
> ?? 2020-12-25 21:24:36.709 Stop ipc server Fork_5620_Pipe_AskPass

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Extras/issues/3623
