### ISSUE TITLE
.ps1 shim passes incorrect arguments to app

### ISSUE THREAD

**Issue by CrendKing** [ScoopInstaller/Scoop#4216]
I was calling ffmpeg (without any extension) in PowerShell (the shim directory is in PATH), and noticed ffmpeg gives me error even though the command line was correct in cmd.exe. After some digging, I found that the ffmpeg.ps1 shim is passing the arguments incorrectly. And in PowerShell it prioritizes ffmpeg.ps1 over ffmpeg.exe if they both exist, while it's the other way in cmd.exe.

Consider this command line:
```
test.ps1 -a:b c
```
The expected result is that `test` receives two arguments: `-a:b` and `c`.
The actual result is that `test` receives three arguments: `-a:`, `b` and `c`.
To get the correct result in PowerShell, this has to be used:
```
test.ps1 '-a:b' c
```

I understand this is caused by PowerShell's handling of named arguments (there are quite some [issues](https://github.com/PowerShell/PowerShell/issues/6360) in PowerShell repo), but it manifests in Scoop. I'm sure Scoop can add some special handing in the .ps1 shim, but I don't know if you guys are willing to go that route.

Also, thanks to https://github.com/lukesampson/scoop/issues/1606, I really don't see the point of .ps1 shim. Removing them thus "forcing" PowerShell to use .exe shim actually solves the problem. Is there a way to tell Scoop not to generate .ps1 shim?

**Comment by Bauxitedev** [comment]
Running into the same issue here. I was dumbfounded at the fact that my ffmpeg commands didn't work in Powershell, but copy-pasting the exact commands into cmd.exe *did* work. I kept getting vague errors like "Unable to find a suitable output format for 'copy'". Now I understand why.

**Comment by rashil2000** [comment]
Merged in develop branch - #4543
