### ISSUE TITLE
Unable to install GDB

### ISSUE THREAD

**Issue by PedroAlves24** [ScoopInstaller/Scoop#4224]
The command `scoop install gdb` produces the following output:

```
Installing 'gdb' (9.1-3) [64bit]
The remote server returned an error: (404) Not Found.
URL http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-bzip2-1.0.8-1-any.pkg.tar.xz is not valid
```

**Comment by sudo-Ilyria** [comment]
Same with gcc - Same error

**Comment by yostane** [comment]
Hi, please try my fix here https://github.com/lukesampson/scoop/issues/4235#issuecomment-766168326 :)

**Comment by Victorious3** [comment]
Would be nice if this could get fixed, I depend on gdb and gcc for a project and it's a lot harder to install them by hand.

**Comment by Lightlyflow** [comment]
I'm still getting the same error:
`Installing 'gdb' (9.1-3) [64bit]
The remote server returned an error: (404) Not Found.
URL http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-bzip2-1.0.8-1-any.pkg.tar.xz is not valid`
