### ISSUE TITLE
The following error occurred when adding a bucket

### ISSUE THREAD

**Issue by Dukro** [ScoopInstaller/Scoop#4226]
Checking repo... ok
error: RPC failed; curl 56 OpenSSL SSL_read: Connection was reset, errno 10054
error: 3938 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: index-pack failed
The jetbrains bucket was added successfully.

**Comment by youssefmellah** [comment]
the same problem.

is there any solution ?

**Comment by mateobur** [comment]
WSL2 Ubuntu Windows 10:

This worked for me: https://github.com/microsoft/WSL/issues/4253#issuecomment-673633785 @youssefmellah @Dukro 

sudo ip link set dev eth0 mtu 1350
