### ISSUE TITLE
Scoop update doesn't work behind proxy

### ISSUE THREAD

**Issue by Dukro** [ScoopInstaller/Scoop#4227]
PS C:\Users\Dukro> scoop update
Updating Scoop...
fatal: unable to access 'https://github.com/lukesampson/scoop/': Proxy CONNECT aborted
Scoop update failed.
PS C:\Users\Dukro> scoop config rm proxy
'proxy' has been removed
PS C:\Users\Dukro> scoop updat
scoop: 'updat' isn't a scoop command. See 'scoop help'.
PS C:\Users\Dukro> scoop update
Updating Scoop...
fatal: unable to access 'https://github.com/lukesampson/scoop/': Proxy CONNECT aborted
Scoop update failed.
PS C:\Users\Dukro>

**Comment by HUMORCE** [comment]
check the proxy field in the config file:
`cat ~\.config\scoop\config.json`

or just try:
`scoop config proxy default` or `scoop config proxy none`

**Comment by undrivendev** [comment]
I'd suggest running a local proxy on `127.0.0.1:3128` such as [px](https://github.com/genotrance/px) or [winfoom](https://github.com/ecovaci/winfoom) acting as a middleware for local applications and taking care of the authentication towards the corporate proxy. 
After properly configuring it, you should be able to reach the outside world by setting `scoop config proxy "127.0.0.1:3128"`

**Comment by xiaodl813** [comment]
I have a simular issue. I have tried to set a proxy on either pwsh or scoop, but it still failed.
When the proxy was seting on scoop, it tells me "Proxy CONNECT aborted". While on pwsh, there is only a "scoop updating...".

**Comment by rashil2000** [comment]
Scoop uses git. Check your git's proxy configuration too.
