### ISSUE TITLE
git errors (FilePath?) after moving scoop to a new drive

### ISSUE THREAD

**Issue by ibonobo** [ScoopInstaller/Scoop#4228]
I followed the guide: backed up, uninstalled, set up new path, reinstalled scoop at new location, but after reboot, I keep getting git errors. I tried reinstalling, but it won't install: 

> scoop uninstall git; scoop install git
Uninstalling 'git' (2.30.0.windows.1).
'git' was uninstalled.
Scoop uses Git to update itself. Run 'scoop install git' and try again.
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'git' (2.30.0.windows.1) [64bit]
Loading PortableGit-2.30.0-64-bit.7z.exe from cache.
Checking hash of PortableGit-2.30.0-64-bit.7z.exe ... ok.
Extracting dl.7z ... Invoke-ExternalCommand : Cannot validate argument on parameter 'FilePath'. The argument is null or empty. Provide an
argument that is not null or empty, and then try the command again.
At E:\scoop\apps\scoop\current\lib\decompress.ps1:81 char:38
+     $Status = Invoke-ExternalCommand $7zPath $ArgList -LogPath $LogPa ...
+                                      ~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-ExternalCommand], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Invoke-ExternalCommand

git : The term 'git' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ git config --get remote.origin.url
+ ~~~
    + CategoryInfo          : ObjectNotFound: (git:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Failed to extract files from E:\scoop\apps\git\2.30.0.windows.1\dl.7z.
Log file:
  E:\scoop\apps\git\2.30.0.windows.1\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https:////

**Comment by rashil2000** [comment]
Are you still facing this issue?

**Comment by miguelmsoler** [comment]
I solved with:

- scoop uninstall git
- scoop uninstall 7zip
- scoop install 7zip
- scoop install git

The problem is that when you import your backed up scoop folder, git and 7zip does not work. You can also install them from an installer.
