### ISSUE TITLE
Set non-zero exit code if error happens

### ISSUE THREAD

**Issue by CrendKing** [ScoopInstaller/Scoop#4230]
I want to write a script that if I successfully updated an app, run `scoop cleanup` and `scoop cache rm` on that app. But if the update failed (e.g. the app is still running), don't run those.

Currently regardless if a command succeeds or fails, it always returns 0 as exit code. There is no way to check the status of that command.

**Comment by CrendKing** [comment]
I think this is a duplicate of other issues such as https://github.com/lukesampson/scoop/issues/3936, but it seems no one is taking care of this. Isn't this just replacing those empty `return`s with something like `exit 1` in lines like https://github.com/lukesampson/scoop/blob/227de6cfb8433a86ac0f0a279e691327ae04554c/libexec/scoop-update.ps1#L241? I could make a PR, but I really don't know if anyone will ever look at it.

**Comment by rashil2000** [comment]
Hey @CrendKing, could you send us a PR (after ensuring no duplicate PR exists) for your change?

**Comment by rashil2000** [comment]
Also, let's follow the original discussion at #3936

**Comment by CrendKing** [comment]
@rashil2000 Sorry. I switched to https://github.com/Ash258/Scoop-Core, which handles the error code. For example, https://github.com/Ash258/Scoop-Core/blob/main/libexec/scoop-install.ps1#L217

Maybe consider porting the code back?
