### ISSUE TITLE
An unknown error occurred

### ISSUE THREAD

**Issue by Dukro** [ScoopInstaller/Scoop#4232]
PS C:\Users\Dukro> scoop search webstorm
convertfrom-json : 无效的 JSON 基元: 。
所在位置 C:\Users\Dukro\scoop\apps\scoop\current\lib\manifest.ps1:10 字符: 45
+     Get-Content $path -raw -Encoding UTF8 | convertfrom-json -ea stop
+                                             ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand

'apps' bucket:
    lukesampson-webstorm (2020.3.1)
    WebStorm-EAP-portable (2020.3-203.5981.31)
    WebStorm-EAP (2020.3-203.5981.31)
    WebStorm-portable (2020.3.1-203.6682.155)
    WebStorm (2020.3.1-203.6682.155)

'extras' bucket:
    webstorm (2020.3.1)

'jetbrains' bucket:
    WebStorm-EAP-portable (2020.3-203.5981.31)
    WebStorm-EAP (2020.3-203.5981.31)
    WebStorm-portable (2020.3.1-203.6682.155)
    WebStorm (2020.3.1-203.6682.155)

**Comment by rashil2000** [comment]
This is due to an improper manifest in one of your buckets
