### ISSUE TITLE
Error "Version 'current' is not allowed!" when running "scoop reset firefox"

### ISSUE THREAD

**Issue by pcgeek86** [ScoopInstaller/Scoop#4233]
After upgrading Windows 10 Insiders, all of my scoop app shortcuts disappeared, similar to #3941 and #2233. To fix this, I am running `scoop reset *`, according to the other threads, at which point I received the following error message.

```
PS > scoop reset firefox
Resetting firefox (current).
Linking ~\scoop\apps\firefox\current => ~\scoop\apps\firefox\current
Error: Version 'current' is not allowed!
```

How can I resolve this error?

**Comment by rashil2000** [comment]
Hi, is this still an issue?
