### ISSUE TITLE
Scoop doesn't show available update even though bucket file has been updated

### ISSUE THREAD

**Issue by jmesserli** [ScoopInstaller/Scoop#4236]
I'm trying to update IntelliJ-IDEA-Ultimate from the [JetBrains Bucket](https://github.com/Ash258/Scoop-JetBrains).
The local clone of the bucket seems to have the updated version `2020.3.1-...`, but when I use `scoop update IntelliJ-IDEA-Ultimate` it tells me that the latest version is already installed:
![image](https://user-images.githubusercontent.com/613138/105138407-1d4cec80-5af5-11eb-8078-773e41e738b9.png)

I've had this issue in the past and could fix it by uninstalling IntelliJ, removing, and re-adding the bucket. But I'd prefer not to do that every time.
It might be primarily a problem with the IntelliJ package, the other apps seem to work fine.

I'm using
* Windows 10 Pro 20H2 19042.746
* Powershell 5.1.19041.610
* Windows Terminal 1.4.3243.0

Please let me know if I can provide any more information.

**Comment by cech12** [comment]
Same issue for me. My version is `2021.1-211.6693.111` and the actual one is `2021.1.2-211.7442.40`. 
Past updates from version `2020.3.2-203.7148.57` to `2020.3.3-203.7717.56` to `2021.1-211.6693.111` worked without problems.

It looks like that the version comparison between `2021.1-...` and `2021.1.X-...` is not correct here.

**Comment by rashil2000** [comment]
Fixed in master
