### ISSUE TITLE
Can't install openssh error 404

### ISSUE THREAD

**Issue by Kreijstal** [ScoopInstaller/Scoop#4237]
Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden.
URL http://repo.msys2.org/msys/x86_64/heimdal-7.7.0-1-x86_64.pkg.tar.xz is not valid
I am unable to install openssh because it can't find this package.

yes, scoop is up to date.

**Comment by Kreijstal** [comment]
I installed aria2c now I get a different error

```
ERROR Download failed! (Error 3) Resource was not found
ERROR http://repo.msys2.org/msys/x86_64/heimdal-7.7.0-1-x86_64.pkg.tar.xz
    referer=http://repo.msys2.org/msys/x86_64/
    dir=C:\Users\jpardo\scoop\cache
    out=openssh#8.2p1-1#http_repo.msys2.org_msys_x86_64_heimdal-7.7.0-1-x86_64.pkg.tar.xz
http://repo.msys2.org/msys/x86_64/heimdal-libs-7.7.0-1-x86_64.pkg.tar.xz
    referer=http://repo.msys2.org/msys/x86_64/
    dir=C:\Users\jpardo\scoop\cache
    out=openssh#8.2p1-1#http_repo.msys2.org_msys_x86_64_heimdal-libs-7.7.0-1-x86_64.pkg.tar.xz
http://repo.msys2.org/msys/x86_64/libcrypt-2.1-2-x86_64.pkg.tar.xz
    referer=http://repo.msys2.org/msys/x86_64/
    dir=C:\Users\jpardo\scoop\cache
    out=openssh#8.2p1-1#http_repo.msys2.org_msys_x86_64_libcrypt-2.1-2-x86_64.pkg.tar.xz
http://repo.msys2.org/msys/x86_64/libdb-5.3.28-2-x86_64.pkg.tar.xz
    referer=http://repo.msys2.org/msys/x86_64/
    dir=C:\Users\jpardo\scoop\cache
    out=openssh#8.2p1-1#http_repo.msys2.org_msys_x86_64_libdb-5.3.28-2-x86_64.pkg.tar.xz
http://repo.msys2.org/msys/x86_64/libedit-20191231_3.1-1-x86_64.pkg.tar.xz
    referer=http://repo.msys2.org/msys/x86_64/
    dir=C:\Users\jpardo\scoop\cache
    out=openssh#8.2p1-1#http_repo.msys2.org_msys_x86_64_libedit-20191231_3.1-1-x86_64.pkg.tar.xz
http://repo.msys2.org/msys/x86_64/libopenssl-1.1.1.e-1-x86_64.pkg.tar.xz
    referer=http://repo.msys2.org/msys/x86_64/
    dir=C:\Users\jpardo\scoop\cache
    out=openssh#8.2p1-1#http_repo.msys2.org_msys_x86_64_libopenssl-1.1.1.e-1-x86_64.pkg.tar.xz
http://repo.msys2.org/msys/x86_64/libsqlite-3.30.0-1-x86_64.pkg.tar.xz
    referer=http://repo.msys2.org/msys/x86_64/
    dir=C:\Users\jpardo\scoop\cache
    out=openssh#8.2p1-1#http_repo.msys2.org_msys_x86_64_libsqlite-3.30.0-1-x86_64.pkg.tar.xz
http://repo.msys2.org/msys/x86_64/msys2-runtime-3.0.7-6-x86_64.pkg.tar.xz
    referer=http://repo.msys2.org/msys/x86_64/
    dir=C:\Users\jpardo\scoop\cache
    out=openssh#8.2p1-1#http_repo.msys2.org_msys_x86_64_msys2-runtime-3.0.7-6-x86_64.pkg.tar.xz
http://repo.msys2.org/msys/x86_64/ncurses-6.2-1-x86_64.pkg.tar.xz
    referer=http://repo.msys2.org/msys/x86_64/
    dir=C:\Users\jpardo\scoop\cache
    out=openssh#8.2p1-1#http_repo.msys2.org_msys_x86_64_ncurses-6.2-1-x86_64.pkg.tar.xz
http://repo.msys2.org/msys/x86_64/openssh-8.2p1-1-x86_64.pkg.tar.xz
    referer=http://repo.msys2.org/msys/x86_64/
    dir=C:\Users\jpardo\scoop\cache
    out=openssh#8.2p1-1#http_repo.msys2.org_msys_x86_64_openssh-8.2p1-1-x86_64.pkg.tar.xz
http://repo.msys2.org/msys/x86_64/openssl-1.1.1.e-1-x86_64.pkg.tar.xz
    referer=http://repo.msys2.org/msys/x86_64/
    dir=C:\Users\jpardo\scoop\cache
    out=openssh#8.2p1-1#http_repo.msys2.org_msys_x86_64_openssl-1.1.1.e-1-x86_64.pkg.tar.xz
http://repo.msys2.org/msys/x86_64/zlib-1.2.11-1-x86_64.pkg.tar.xz
    referer=http://repo.msys2.org/msys/x86_64/
    dir=C:\Users\jpardo\scoop\cache
    out=openssh#8.2p1-1#http_repo.msys2.org_msys_x86_64_zlib-1.2.11-1-x86_64.pkg.tar.xz

ERROR & 'C:\Users\jpardo\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\jpardo\scoop\cache\openssh.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=18544 --continue --summary-interval 0

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=openssh%408.2p1-1%3a+download+via+aria2+failed
```

**Comment by franzhaas** [comment]
I changed the content of openssh.json to 
{
    "version": "8.2p1-1",
    "description": "A suite of secure networking utilities based on the Secure Shell protocol.",
    "homepage": "https://www.openssh.com/",
    "license": "ISC",
    "architecture": {
        "64bit": {
            "url": [
                "http://repo.msys2.org/msys/x86_64/bash-4.4.023-2-x86_64.pkg.tar.xz",
                "http://repo.msys2.org/msys/x86_64/gcc-libs-9.3.0-1-x86_64.pkg.tar.xz",
                "http://repo.msys2.org/msys/x86_64/heimdal-7.7.0-2-x86_64.pkg.tar.zst",
                "http://repo.msys2.org/msys/x86_64/heimdal-libs-7.7.0-2-x86_64.pkg.tar.zst",
                "http://repo.msys2.org/msys/x86_64/libcrypt-2.1-2-x86_64.pkg.tar.xz",
                "http://repo.msys2.org/msys/x86_64/libdb-5.3.28-3-x86_64.pkg.tar.zst",
                "http://repo.msys2.org/msys/x86_64/libedit-20191231_3.1-1-x86_64.pkg.tar.xz",
                "http://repo.msys2.org/msys/x86_64/libopenssl-1.1.1.e-1-x86_64.pkg.tar.xz",
                "http://repo.msys2.org/msys/x86_64/libsqlite-3.30.0-1-x86_64.pkg.tar.xz",
                "http://repo.msys2.org/msys/x86_64/msys2-runtime-3.1.4-1-x86_64.pkg.tar.zst",
                "http://repo.msys2.org/msys/x86_64/ncurses-6.2-1-x86_64.pkg.tar.xz",
                "http://repo.msys2.org/msys/x86_64/openssh-8.2p1-1-x86_64.pkg.tar.xz",
                "http://repo.msys2.org/msys/x86_64/openssl-1.1.1.e-1-x86_64.pkg.tar.xz",
                "http://repo.msys2.org/msys/x86_64/zlib-1.2.11-1-x86_64.pkg.tar.xz"
            ],
            "hash": [
                "ed17af38e37e0790b467b9887b98bdfb4c711279d067a34b440cdb583ebc12ea",
                "79a74bb1ef1d7f4eb12f7437ac24371ec9e41a3d96b653a2ec7f09d1e7aa9c63",
                "e64fcf00ddd4158ac56dc3b282698d616bedeece3466376bc03ff61f09a0c044",
                "eda2132707ef438db009613c011b47217cb00ee4d4a28ad4f6cb10ad1845f74e",
                "333b5089ea0d27c167e7bcf786bf0ceb2192d76c18f338379d771adda18bda3e",
                "00caef39902d34112fe9f9e5f9aad063cbde3922c212558ce4cec5f8c33534ee",
                "236bedb6a8a90c0ecb70c1bc9c90ccd347f2f1ae96df11aa9af8e6878a606fe3",
                "e142b12df8b5f1765a1a0739a5a304d18f810523ac5d36dc66bb92ff00d67d1b",
                "45dcd0b4ac5444cfa8a7b9b98908b398710b65277e639666135746d7ffe0bfbb",
                "7905fc21dbe30abde0d9d08a3138b90a07c57bc423fc0c44e891ee15511d76b3",
                "0943eb05da94d3ab8efac1a923bfcd515a9ba7251186e29401f06f155ce4d2ba",
                "bc633859967a1a3f99f97e79daae6a9b520bf2cdc7e7c14e7647f1e86adee289",
                "c9d1b2e4854bc425043b577b535d28826cd5d6fb5dda20b4b578066da62b264c",
                "4af63558e39e7a4941292132b2985cb2650e78168ab21157a082613215e4839a"
            ]
        }
    },
    "pre_install": [
        "ensure \"$dir\\tmp\" | Out-Null",
        "ensure \"$dir\\home\" | Out-Null",
        "ensure \"$dir\\home\\$env:UserName\" | Out-Null",
        "ensure \"$env:UserProfile\\.ssh\" | Out-Null",
        "cmd /c mklink /j \"$dir\\home\\%UserName%\\.ssh\" \"%UserProfile%\\.ssh\""
    ],
    "bin": [
        [
            "usr\\bin\\sh.exe",
            "findssl.sh",
            "$dir/usr/bin/findssl.sh"
        ],
        "usr\\bin\\scp.exe",
        "usr\\bin\\sftp.exe",
        "usr\\bin\\ssh.exe",
        "usr\\bin\\ssh-add.exe",
        "usr\\bin\\ssh-agent.exe",
        [
            "usr\\bin\\sh.exe",
            "ssh-copy-id",
            "$dir/usr/bin/ssh-copy-id"
        ],
        "usr\\bin\\ssh-keygen.exe",
        "usr\\bin\\ssh-keyscan.exe",
        "usr\\bin\\sshd.exe"
    ]
}
and it worked for me

**Comment by franzhaas** [comment]
It apears to me as if the source of the installers no longer supplies the referenced versions...

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Main/issues/1769
