### ISSUE TITLE
suggestion: add a repair scoop installation command

### ISSUE THREAD

**Issue by idbrii** [ScoopInstaller/Scoop#4241]
Using Windows's [reset your PC](https://support.microsoft.com/en-us/windows/how-to-refresh-reset-or-restore-your-pc-51391d9a-eb0a-84a7-69e4-c2c1fbceb8dd) wipes out registry and environment variables, but doesn't remove your scoop installation. Adding a repair command would be helpful.

Users have to run %USERPROFILE%\scoop\shims\scoop.exe directly in this case since part of the repair is adding shims to the path.

Possibly all the repair command needs to do is adding shims to the PATH? I think reinstalling all the applications would be out of scope (but uninstall and reinstall would ensure they get hooked back up).

Note that attempting to install scoop complains that scoop is already installed even though the install is not functional which is the other way I'd expect a repair might work.

**Comment by brunovieira97** [comment]
Doesn't `scoop reset <app>` already accomplish this? It's meant to be used as a conflict solving command, but actually what it does is basically doing all of the installation steps except downloading and extracting.

So, at the end of the day, it just restores an app shims, settings, symlinks etc when it's already installed.

**Comment by idbrii** [comment]
I didn't know that `scoop reset` would work instead of uninstall/reinstall! However, that fixes apps, but I'm talking about a command to **fix scoop**. 

`iwr -useb get.scoop.sh | iex` fails if scoop's install directory already exists.

**Comment by HUMORCE** [comment]
rename `scoop` direcotry to `scoop.old` or any you like, then run scoop installer.
when scoop installation is complete:
1. move/copy/rename `scoop.old` to `scoop`
2. exec `scoop reset *`
3. try to open/exec previously installed app(s)

**Comment by brunovieira97** [comment]
Well, about fixing Scoop, all it does is download a bunch of scripts and shims and place its own folder on PATH. Fixing Scoop would be just adding Scoop's own folder back on PATH. That seems more like a manual one-time thing and not a recurrent operation that justifies a new command IMHO.

Of course, I'm just expressing my point of view and the project's maintainers may find it a nice addition to the project.

**Comment by idbrii** [comment]
Maybe instead of a new command, the installer could ensure scoop is in the PATH.

> Is editing the PATH not enough for your case?

Seems like that was enough to get scoop working properly. I think the user flow could be better.
