### ISSUE TITLE
No valid scoop shim, breaks repo scripts

### ISSUE THREAD

**Issue by lmartinez-mirror** [ScoopInstaller/Scoop#4249]
I'm trying to update a manifest that I wrote using `checkver`, but since the scripts all have `scoop which scoop` and return `Not a scoop shim.`, I get an error.

How do I fix this?

**Comment by HUMORCE** [comment]
How to reproduce this problem?

**Comment by apommel** [comment]
I get the same issue. In my case just executing `./bin/checkver.ps1` in a local bucket produces an error, which is also due to the fact that `scoop which scoop` returns `Not a scoop shim.`

**Comment by rashil2000** [comment]
There was an upstream bug in PowerShell which has been fixed. Reopen if it occurs again.
