### ISSUE TITLE
Allow installing "lower priority" packages to skip shim overwrites

### ISSUE THREAD

**Issue by vvuk** [ScoopInstaller/Scoop#4253]
This is similar to #364 -- having "latest installed overrides" makes package installs very annoying in a few cases, and hard to maintain exactly what you want with future upgrades.  For example, the `unxutils` package includes a bunch of stuff where there are newer versions provided elsewhere, e.g. `grep`, `ln`, etc.  It would be nice to be able to install `unxutils` with a "never overwrite shims and always accept someone else overwriting my shims" option.

**Comment by rashil2000** [comment]
You can do that by using  a custom unxutils manifest, or do `scoop reset <earlier-app-name>` to restore the earlier shims.
