### ISSUE TITLE
FeatureRequest: continue on next app (when hash validation error occured)

### ISSUE THREAD

**Issue by webartoli** [ScoopInstaller/Scoop#4259]
As a user I want to keep my computer updated so that i type `scoop update *` weekly.

Supposing this update scenario
```
app1: 7.3.4 -> 7.3.5
app2: 1.7.2 -> 1.7.4   // this app hash is not yet updated; hash vaidation fails
app3: 6.1.0 -> 6.1.1
...
appN: 4.5.0 -> 4.5.1
```

this is very annoyng becouse hash check failure block the entire update process and you have to update applications one by one. 
(in this moment an application that start with `b` letter has hash failure error and i have 15 app to update.)

This issue occurs quite often.

I propose an option:
```
Options:
   -c, --continue   Continue to the next app when command fails.
```

This option can be applicabile to `update`, `install` commands for sure; maybe also `uninstall` command.

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Scoop/issues/4135
