### ISSUE TITLE
Need to check for updates

### ISSUE THREAD

**Issue by juanjosegarciaripoll** [ScoopInstaller/Scoop#4260]
A freshly installed MikTeX refuses to run because the user has not checked for updates. This would be done during ordinary installation, but it does not seem to take place when installed from scoop. The user has to run "miktex-update" which is a graphical program asking for information on how to do the update. Maybe a hint about this would be required. I do not remember seeing it when upgrading "latex".

**Comment by rashil2000** [comment]
If the application provides a way to disable update checks (through a config file or similar), it should be disabled as a part of install process, i.e. a post_install step in the manifest. Otherwise the user will have to configure it manually.
