### ISSUE TITLE
scoop search now fails when query string resolves to possible parameter -- e.g. 'scoop search "-NF"'

### ISSUE THREAD

**Issue by s-a-c** [ScoopInstaller/Scoop#4270]
>>>
PS C:\Windows\Temp> scoop search "-NF"
ERROR scoop search: Option -N not recognized.
PS C:\Windows\Temp>
>>>
The above error now disrupts a formerly working  scriptblock, intended t install "Nerd-Fonts"
>>>
( scoop search "-nf" ).trim() | ForEach-Object -Process { scoop install --global $_.Split(" ")[0] }
>>>

**Comment by HUMORCE** [comment]
```
scoop search "\-NF"
```

enjoy it.

**Comment by s-a-c** [comment]
Many thanks @HUMORCE, that's done the trick.
Easy when you know how 😀

**Comment by s-a-c** [comment]
Maybe I spoke to soon ...
"scoop search" seems to no longer return a PowerShell object
>>>
`
PS C:\Users\sunav> (scoop search "3270\-nf\-mono") | get-member
Searching in local buckets ...
nerd-fonts/3270-NF-Mono
  Version: 2.1.0

Get-Member: You must specify an object for the Get-Member cmdlet.
PS C:\Users\sunav>
`

**Comment by HUMORCE** [comment]
maybe it's `scoop info`?
