### ISSUE TITLE
"scoop search" seems to no longer return a PowerShell object

### ISSUE THREAD

**Issue by s-a-c** [ScoopInstaller/Scoop#4274]
"scoop search" seems to no longer return a PowerShell object

```
PS C:\Users\sunav> (scoop search "3270\-nf\-mono") | get-member
Searching in local buckets ...
nerd-fonts/3270-NF-Mono
Version: 2.1.0

**_Get-Member: You must specify an object for the Get-Member cmdlet._**
PS C:\Users\sunav>
```
the following scriptblock no longer works
`( scoop search "\-nf" ).trim() | ForEach-Object -Process { scoop install --global $_.Split(" ")[0] }`

**Comment by rashil2000** [comment]
It never returned a PSObject.
