### ISSUE TITLE
Can't install 'gcc' from scoop, please update url for gcc

### ISSUE THREAD

**Issue by Charlestar** [ScoopInstaller/Scoop#4277]
When I use scoop to install gcc, there is an error:
```
The remote server returned an error: (404) Not Found.
URL http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-expat-2.2.9-1-any.pkg.tar.xz is not valid
```
Then I find that the url here is not available, there is no file called "mingw-w64-x86_64-expat-2.2.9-1-any.pkg.tar.xz", instead, there is a file called "mingw-w64-x86_64-expat-2.2.10-1-any.pkg.tar.zst", please update the url and fix this bug. Thank you.

**Comment by mquinson** [comment]
We got hit by the same bug here. Does anyone knows a temporaly workaround, maybe?
Thanks for your help,

**Comment by Charlestar** [comment]
> We got hit by the same bug here. Does anyone knows a temporaly workaround, maybe?
> Thanks for your help,

I don't know how to deal with this problem, I just installed Mingw64 manually to use C in my computer.

**Comment by IZBH** [comment]
waitting

**Comment by chawyehsu** [comment]
see: https://github.com/ScoopInstaller/Main/issues/1752

**Comment by dwettstein** [comment]
Relates: https://github.com/lukesampson/scoop/issues/3990
