### ISSUE TITLE
switch shim to another app?

### ISSUE THREAD

**Issue by mralusw** [ScoopInstaller/Scoop#4280]
Today I installed `busybox`, and watched "in horror" as it replaced proper shims with its minimalistic versions:
```
Creating shim for 'vi'.
WARN  Overwriting shim to busybox.exe installed from vim
Creating shim for 'watch'.
Creating shim for 'wc'.
WARN  Overwriting shim to busybox.exe installed from coreutils
Creating shim for 'wget'.
WARN  Overwriting shim to busybox.exe installed from wget
Creating shim for 'which'.
WARN  Overwriting shim to busybox.exe installed from which
Creating shim for 'whoami'.
```

Other than re-installing all the affected apps (I copy/pasted the console log somewhere), what can I do? Is there an equivalent of debian's update-alternatives system, i.e. can I switch my shim to another app? I looked in `scoop/apps/*/*.json`  but I didn't see any shim information.

And for the future, can I tell `scoop install` not to overwrite existing shims?

**Comment by HUMORCE** [comment]
```
$ scoop help reset
Usage: scoop reset <app> [options]

Reset an app to resolve conflicts

Used to resolve conflicts in favor of a particular app. For example,
if you've installed 'python' and 'python27', you can use 'scoop reset' to switch between
using one or the other.

Options:
  -h, --help      Show help for this command.
```

or create a copy of `busybox.json` and customize it.
