### ISSUE TITLE
Can't install nmap: requires elevation + "Silent installation is only supported in Nmap OEM"

### ISSUE THREAD

**Issue by pmorch** [ScoopInstaller/Scoop#4284]
If I try to install nmap *without* elevation, I get:

```
Scoop was updated successfully!
Installing 'nmap' (7.91) [64bit]
Loading nmap-7.91-setup.exe from cache
Checking hash of nmap-7.91-setup.exe ... ok.
Running installer... error.
ERROR Exception calling "Start" with "0" argument(s): "The requested operation requires elevation"
Installation aborted. You might need to run 'scoop uninstall nmap' before trying again.
```

If I then try to install it with *with* elevation, cmd run as Administrator, I get:

![image](https://user-images.githubusercontent.com/159292/110331202-19324b00-801f-11eb-8cd9-96761593b63f.png)

When I hit enter, I see this in the cmd console:

```
Running installer... error.
ERROR Exit code was 2!
Installation aborted. You might need to run 'scoop uninstall nmap' before trying again.
```

Installing https://nmap.org/dist/nmap-7.91-setup.exe from https://nmap.org/download.html worked fine.

**Comment by 2552552550** [comment]
Hello. Silent install is present in OEM version only. 
[https://nmap.org/npcap/oem/internal.html](https://nmap.org/npcap/oem/internal.html)

> Silent installer—Npcap OEM includes a silent installation option (/S), including customization using command-line arguments to ease deployment across a company or devision. The free/demo Npcap does not include a silent installer.

**Comment by EricViakoo** [comment]
> Hello. Silent install is present in OEM version only.
> https://nmap.org/npcap/oem/internal.html
> 
> > Silent installer—Npcap OEM includes a silent installation option (/S), including customization using command-line arguments to ease deployment across a company or devision. The free/demo Npcap does not include a silent installer.

Yes, that was the error message listed. What that means is that scoop is going to have to not call /s (and we'll need to click thru the npcap install). Or else scoop is going to have to revert back to a version of nmap that doesn't use a version of npcap that doesn't have this limitation.

**Comment by rashil2000** [comment]
>  is it possible for Scoop to adopt this solution?

No, if it's not possible to install silently, then it shouldn't be installed by Scoop

**Comment by pmorch** [comment]
Hi @rashil2000 - As far as I can see, nmap is still shown as an app that can be installed:

```
C:\Windows>scoop search nmap
'main' bucket:
    nmap-portable (7.92)
    nmap (7.92)
```

and there are no commits associated with this issue.

Shouldn't here be a commit that removes nmap from the search output? Currently one can try to install nmap but it fails.
