### ISSUE TITLE
Can't create a manifest without a URL

### ISSUE THREAD

**Issue by pfmoore** [ScoopInstaller/Scoop#4285]
I'd like to create a manifest that doesn't download anything. The idea is that it depends on another app (specifically git) and then has an install script that sets up some aliases, but doesn't need to download anything apart from the dependency.

According to [the documentation](https://scoop-docs.now.sh/docs/concepts/App-Manifests.html#required-properties), url is optional, but if I leave it out, the install fails with

```
>scoop install .\example.json
Test-LessmsiRequirement: C:\Users\Gustav\scoop\apps\scoop\current\lib\depends.ps1:83
Line |
  83 |  … Lessmsi) -and (Test-LessmsiRequirement -URL (url $manifest $arch))) {
     |                                                ~~~~~~~~~~~~~~~~~~~~~
     | Cannot bind argument to parameter 'URL' because it is null.

'example' doesn't support 64bit architecture!
```

I could just point the url at some dummy file as a workaround, but that seems a bit annoying.

**Comment by pfmoore** [comment]
Hmm, having got this working with a dummy URL, I realised that setting up aliases in the installer is a dumb idea because it doesn't work 🙁

Nevertheless, I still think that at least the documentation should be updated to note that URL is mandatory.

**Comment by rashil2000** [comment]
Closed in https://github.com/ScoopInstaller/Scoop/wiki/App-Manifests/_compare/54c5b58ffbf01ec4be697c803bd8669f45e414c9
