### ISSUE TITLE
Scoop downloading files to compute hashes

### ISSUE THREAD

**Issue by kamiyubidan** [ScoopInstaller/Scoop#4289]
Why is Scoop downloading files to compute hashes?

This is happening when the server may be temporarily unavailable, which could occur due to closely timed multiple requests, or other issues.

For example, I have multiple Visual Studio code installations with separately named manifests. Each one resulted in a download.

The same issue occurs with other manifests.

This occur has only started occurring in the last few weeks.

Please refrain from auto-downloading anything unless we authorize it explicitly via one of the commands such as 'update'.

```
Searching hash for dl.7z in https://code.visualstudio.com/sha?build=stable
The remote server returned an error: (500) Internal Server Error.
URL https://code.visualstudio.com/sha?build=stable is not valid
Could not find hash in https://code.visualstudio.com/sha?build=stable
Downloading dl.7z to compute hashes!
```

**Comment by rashil2000** [comment]
This is not a normal workflow. You're using either `checkver` or `checkhashes` utility, where this happens.
