### ISSUE TITLE
Can I move the shortcuts location?

### ISSUE THREAD

**Issue by s1-en** [ScoopInstaller/Scoop#4296]
When I install a GUI application via scoop, it creates a shortcut under "Scoop Apps" folder. I want the shortcuts to be outside that folder so that I can find them using the proper letter category instead of everything being piled under "S" (for Scoop Apps).

![image](https://user-images.githubusercontent.com/63731521/111373700-362de480-86d7-11eb-8a02-a24260ecf7a4.png)

Is there a way to do this?

**Comment by HUMORCE** [comment]
the scoop does not provide option for that, but i think you should search instead of mouse clicks.

**Comment by neolectron** [comment]
Still, people customise where they put their shortcuts all the time,
If I want it to be in the root "Start Menu" folder or anywhere else, I can't.

It's unlucky that's not a environment variable.

**Comment by rashil2000** [comment]
#2547
