### ISSUE TITLE
[Feature Request] FlashDrive portability

### ISSUE THREAD

**Issue by Merith-TK** [ScoopInstaller/Scoop#4299]
So this idea came from me getting back into using MobaXterm alot more, whose package manager is not only lacking, but slow.

I was wondering if there was a way i could install scoop inside of mobaxterm, in a way that it does not affect Host envVars, and instead save the envVars it needs to set, to a file that can then be sourced?

This could also be done with possibly a differnt shell that is more focused on the windows commandline rather than cygwin/msys2

**Comment by rashil2000** [comment]
You can follow the instruction in the Readme to setup the installation directory to wherever desired.
