### ISSUE TITLE
Script output color persists after execution

### ISSUE THREAD

**Issue by rkoten** [ScoopInstaller/Scoop#4300]
Example:

Python installer script sets a custom output color for warnings, exits, then scoop takes over with the warning color persisting. It even persists for the shell prompt after scoop is done, and is only reset after that prompt.

![image](https://user-images.githubusercontent.com/10389042/111890371-f8b2ab00-89a5-11eb-838f-9475815f0527.png)

**Comment by rashil2000** [comment]
Python manifest has been modified since. Reopen if this still occurs.
