### ISSUE TITLE
Setting up private repository with private software application downloads

### ISSUE THREAD

**Issue by damienbutt** [ScoopInstaller/Scoop#4301]
Hi all,

I want to setup a private bucket but I can't seem to the get scoop to download the files.

I have created a private repository and added it as a bucket. That part works. I have then created some app manifest files in that bucket in a folder called "bucket" that points to some non-portable executable installers in the same private repository. Each app has its own folder in the root of the repository with folders for individual versions contained in those and then finally the .exe installer file.

The software in question is free but is not available to the general public. You have to be affiliated with the companies to have access to the software. I can't put the files anywhere that is publicly accessible. 

At the minute when I try to run a scoop install on any of the apps I just get an invalid URL error. 

I am new to scoop so I am probably doing something wrong.

Is anyone able to assist?

Thanks,
D

**Comment by HUMORCE** [comment]
deploy git or http on the LAN to provide manifests and binaries.

**Comment by skyhoshi** [comment]
when you go to add your custom private bucket are you sepcifiying the git repo like this ? 
```
scoop bucket add extras https://github.com/lukesampson/scoop-extras.git
```

You can find out more about special buckets at this page. 
[Buckets - Wiki](https://github.com/lukesampson/scoop/wiki/Buckets)

can you give us examples of your setup and error? 

each bucket is a seperate Git Repo. so if you attempt to point a bucket to a location that is not a Git Repo, you'll recieve errors related to that. 

yes you can specify a file location as the repo. 
```
# file://host/path

scoop bucket add specialLocalRepo file://C:/MyCustomScoopRepo/
```

**Comment by rashil2000** [comment]
#4243
