### ISSUE TITLE
ERROR Exit code was 1639! when install charles

### ISSUE THREAD

**Issue by DoveBoy** [ScoopInstaller/Scoop#4305]
Can't install charles on windows10 via scoop install,`ERROR Exit code was 1639!`.
Pop-up window appears during installation.How can I solve it?
![image](https://user-images.githubusercontent.com/19201447/112745265-a4c54900-8fd9-11eb-8c7d-2eb74a3f7343.png)
![image](https://user-images.githubusercontent.com/19201447/112745279-b4449200-8fd9-11eb-8632-8973d7820619.png)

**Comment by HUMORCE** [comment]
where are the manifest?

**Comment by DoveBoy** [comment]
> where are the manifest?
> 
> but try:
> 
> ```
> scoop install lessmsi
> scoop config MSIEXTRACT_USE_LESSMSI $True
> ```

I have try:

```
scoop install lessmsi
scoop config MSIEXTRACT_USE_LESSMSI $True
```
but `ERROR Exit code was 1639!.`

**Comment by HUMORCE** [comment]
leave the charles manifest here.

**Comment by DoveBoy** [comment]
> leave the charles manifest here.

The bucket is [scoop-apps](https://github.com/kkzzhizhou/scoop-apps), it's include [Charles](https://raw.githubusercontent.com/kkzzhizhou/scoop-apps/master/bucket/Charles.json)

**Comment by HUMORCE** [comment]
i can't understand the people who wrote it.

modified, and works now:
https://gist.github.com/HUMORCE/bd39fe4a6b126a68e76d1b2532efa4b0

**Comment by DoveBoy** [comment]
> i can't understand the people who wrote it.
> 
> modified, and works now:
> [gist.github.com/HUMORCE/bd39fe4a6b126a68e76d1b2532efa4b0](https://gist.github.com/HUMORCE/bd39fe4a6b126a68e76d1b2532efa4b0)
> 
> this issue isn't caused by scoop,
> you should open issue to the bucket repo it is publish, if it still doesn't work.

Excellent! I successfully installed Charles with the [charles.json](https://gist.github.com/HUMORCE/bd39fe4a6b126a68e76d1b2532efa4b0) file you gave me! Thank you!
