### ISSUE TITLE
[Feature Request] Mount/Unmount app directories

### ISSUE THREAD

**Issue by raizam** [ScoopInstaller/Scoop#4312]
Currently applications are accessed using the shim folder exposed in the PATH.
But there are cases where applications are toolchains, like clang/llvm, supposed to have their folder exposed for dll resolution or with many small executables.
It would be very useful if scoop had commands to expose/hide app folders easilly.
Something like `scoop mount llvm` that would add the llvm base folder to the current process PATH. `scoop unmount llvm` to hide.
As well as an option to add to path permanently `scoop mount llvm --persist`

**Comment by rashil2000** [comment]
This can be easily accomplished by a 2-liner script. Adding such functionality to Core will introduce unnecessary complexity.
