### ISSUE TITLE
'D:\scoop\shims\..\apps\scoop\current\bin\scoop.ps1' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by Skips75** [ScoopInstaller/Scoop#4316]
Installed scoop on a Win10 20H2 machine on D:\scoop; then continuing installing other applications via scoop
in D:\scoopapps, some with the -g flag. After that I've launched the scoop status command and the program
tell me to update scoop by means of the "scoop update" command.
After executing that command, every new scoop command I run (for example scoop help) terminates with the following message:

**"& : The term 'D:\scoop\shims\..\apps\scoop\current\bin\scoop.ps1' is not recognized as the name of a cmdlet..."**

I checked that there is not a scoop.ps1 in D:\scoop\apps\scoop\current\bin\ directory.

**Comment by HUMORCE** [comment]
required file(s) are missing, try fix by git command:

```
cd d:\scoop\apps\scoop\current
git pull
```

**Comment by Skips75** [comment]
Hi,
git pull done in d:\scoop\apps\scoop\current does not resolve the problem: the cmdlet scoop.ps1 is not still
present int the d:\scoop\apps\scoop\current folder.

**Comment by HUMORCE** [comment]
clone [scoop repo](https://github.com/lukesampson/scoop) in other place and check if the `scoop.ps1` exists.
if it still does not exist, check anti-virus or what others,
else, overwrite `scoop\current` with cloned files.

**Comment by Skips75** [comment]
Hi HUMORCE,

Not done the first part of your suggestion (scoop repo cloning + checking scoop.ps1 file presence).
Instead removed previous installed scoop directory and reinstalled scoop with anti virus totally disabled. After having installed via scoop git and 7zip I made `scoop update` command and after that any next scoop commands (e.g. `scoop help`) fail again.

**Comment by HUMORCE** [comment]
> the scoop cli does not work(missing file `$env:SCOOP\apps\scoop\current\bin\scoop.ps1`.) after executing `scoop update`.

more information required.
- scoop config: `cat $env:USERPROFILE\.config\scoop\config.json`
- reinstall the scoop again then set debug mode ON and reproduce it. `scoop config debug $true`

**Comment by Skips75** [comment]
Today I can not operate on the problem, tomorrow I will give you the info you require me

**Comment by Skips75** [comment]
Hi HUMORCE,
here the info you requested:

- `cat $env:USERPROFILE\.config\scoop\config.json`:

> `{
    "lastupdate":  "2021-04-12T10:44:00.8095934+02:00",
    "SCOOP_REPO":  "https://github.com/ScoopInstaller/Main",
    "SCOOP_BRANCH":  "master",
    "rootPath":  "D:\\Applications\\Scoop",
    "globalPath":  "D:\\GlobalScoopApps"
}`

The problem seems in the **rootPath** and **globalPath** fields. `D:\\Applications\\Scoop` and `D:\\GlobalScoopApps` were
the initial path I used the first time I reistalled scoop. The next new reinstallation were always done `D:\scoop` and D:\scoopapp.
This day perhaps I will have time to reinstall scoop again in the same locations with the debug mode set to ON. I will send you other infos based on that.

Thanks in advance.

**Comment by HUMORCE** [comment]
👀
reset or unset config: rootPath / globalPath

**Comment by Skips75** [comment]
Hi HUMORCE,

Before to install again from scratch the scoop package, I disabled totally the antivirus program (not Windows Defender).
To install scoop I used the following commands in a powershell:
- `set-executionpolicy remotesigned -scope currentuser`
- `$env:SCOOP='D:\scoop'`
- `[environment]::setEnvironmentVariable('SCOOP',$env:SCOOP,'User')`
- `Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')`

Then I opened an Administrator powershell and made:
- `$env:SCOOP_GLOBAL='D:\scoopapp'`
- `[environment]::setEnvironmentVariable('SCOOP_GLOBAL',$env:SCOOP_GLOBAL,'Machine')`
- scoop install sudo -g

Then I opened a new normal powershell and made enable debug feature to true value using the command You suggested:
`scoop config debug $true`

In the same poweshell I installed the apps I need using the command:
`sudo scoop install <app> -g`

Now `cat $env:USERPROFILE\.config\scoop\config.json` returns:
`{
    "lastupdate":  "2021-04-14T10:02:31.4195663+02:00",
    "SCOOP_REPO":  "https://github.com/ScoopInstaller/Main",
    "SCOOP_BRANCH":  "master",
    "rootPath":  "D:\\scoop",
    "globalPath":  "D:\\scoopapp",
    "debug":  true
}`

Restart the PC (after this operation antivirus return on);
logged in, and in a normal powershell I run:
`sudo scoop install IBMPlexMono-NF -g`
which tells me:
`& : The term 'D:\scoop\shims\..\apps\scoop\current\bin\scoop.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is
correct and try again.
At D:\scoop\shims\scoop.ps1:3 char:71
+ ... on.expectingInput) { $input | & $path  @args } else { & $path  @args  ...
+                                                             ~~~~~
    + CategoryInfo          : ObjectNotFound: (D:\scoop\shims\...t\bin\scoop.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException`

**Comment by HUMORCE** [comment]
![screenshot](https://user-images.githubusercontent.com/4353480/114709209-d3eaf280-9d1b-11eb-9081-310f55efb562.png)

i repeated your steps in the virtual machine, but scoop works after reboot or sign out.

the difference:
the config file does not contain the 'rootPath' and 'globalPath'
```
$ Get-Content $env:USERPROFILE\.config\scoop\config.json
{
    "lastupdate":  "2021-04-14T13:06:32.2936128+01:00",
    "debug":  true
}
```

file scoop.ps1 still exists:
```
$ Test-Path $env:SCOOP\apps\scoop\current\bin\scoop.ps1
True
```

**Comment by Skips75** [comment]
The only `scoop.ps1` file I have on my machine is the `D:\scoop\shims\scoop.ps1`.
I think this is the file that tries to locate `D:\scoop\apps\scoop\current\bin\scoop.ps1`
Another valuable difference between mine and your system is the main drive on which
**Scoop** is installed on.

**Comment by Skips75** [comment]
Also installed Scoop in `C:\scoop` and applications into `D:\scoopapp' but the error persists.
It seems that the first instruction that breaks the system is `scoop update'.

**Comment by Skips75** [comment]
Also installed Scoop in `C:\scoop` and applications into `D:\scoopapp` but the error persists. It seems that the first instruction that breaks the system is `scoop update`.

**Comment by Skips75** [comment]
After installed in `C:\scoop` the **scoop** package and the `sudo`, `7zip`, `git` and `dark` app in `D:\scoopapp` (using an
Admin powershell), the command `Test-Path $env:SCOOP\apps\scoop\current\bin\scoop.ps1` returns `True`.

**Comment by Skips75** [comment]
After installed in C:\scoop the scoop package and the sudo, 7zip, git and dark app in D:\scoopapp (using an
Admin powershell and the `--global` flag), the command Test-Path $env:SCOOP\apps\scoop\current\bin\scoop.ps1 returns True.

**Comment by Skips75** [comment]
After installed in C:\scoop the scoop package and the sudo, 7zip, git and dark app in D:\scoopapp (using an
Admin powershell and the --global flag), the command Test-Path $env:SCOOP\apps\scoop\current\bin\scoop.ps1 returns True.
At this point `scoop update` does not anymore fail and it outputs:
`Updating Scoop...`
`Updating 'main' bucket...`
`Checking repo... ok`
`The main bucket was added successfully.`
`Scoop was updated successfully!`

**Comment by HUMORCE** [comment]
it's strange, because people have installed the scoop in non-system drive, in many cases.
i would assume that there are other programs/behaviours causing this problem, if cannot reproduce the problem in the virtual machine (or a clear OS environment).

**Comment by Skips75** [comment]
I do not know if the things that resolved the problem were the union of to disable also Windows Defender and to install
**scoop** on `C:` driver and the rest of applications still in `D:` driver.. At the moment this seems the solution (together to
install after **scoop** installation only `sudo` + `7zip` + `dark` and to make immediately the `scoop update` command).

**Comment by Skips75** [comment]
I do not know if the things that resolved the problem were the union of to disable also Windows Defender and to install
scoop on C: driver and the rest of applications still in D: driver.. At the moment this seems the solution (together to
install after scoop installation only sudo + 7zip + dark and to make immediately the scoop update command).

**Comment by rashil2000** [comment]
#3050
