### ISSUE TITLE
Unity Package Manager can not resolve packages using git if it was installed through scoop 

### ISSUE THREAD

**Issue by Linard11** [ScoopInstaller/Scoop#4317]
I know this is mainly a Unity Package Manager issue that appeared with one of the latest version 2020.3.2f1 where they also fixed a lot of bugs with the package manager and I also submitted a bug report to Unity but I thought I also submit it here because it specifically only happens if git was installed through scoop.

I think it may has something to do with the fact that scoop uses shims that redirect to the real git.exe but I am not sure.

Here is the issue on the Unity Bug Tracker for a detailed description: https://fogbugz.unity3d.com/default.asp?1328102_lvj454k6ub9k2kj3

```
Package Manager does not resolve new packages added through GIT URLs when using git installed through scoop

1. What happened
This issue always happens in both 2020.3.2f1 and the newly released 2020.3.3f1. In 2020.3.1f1 and earlier the issue does not appear.
This issue appears on machines that gave git installed through scoop. On a machine with a manual installation of git the issue did not appear.
A package added as a GIT URL either through the package manager UI or by editing the manifest.json does not resolve and instead throws the error that it could not clone the repository because it does not find the specified revision. This always fails regardless if the revision is HEAD/<branch>/<tag>/<commit hash>. This issue only happens when adding new packages. When upgrading a project from an older Unity versions, already added git packages continue to work, only new packages can not be added.

2. How can we reproduce it using the example you attached
Install git through scoop. This creates a shim for git.exe which is added to PATH instead of the real git.exe.
Open the attached project in Unity 2020.3.2f1 or 2020.3.3f1 and notice the error message on startup. In the manifest.json a small example package hosted publicly on gitlab is already added. Other git packages added from other websites fail the same regardless of their url form (git/https/ssh).

I know in a way this is an issue linked to the scoop package manager, but given that it worked before the changes to the unity package manager made in 2020.3.2f1 it might be possible the Unity Team has a better understanding on how to fix the problem.
```

**Comment by HUMORCE** [comment]
tried alt-shim already?

https://github.com/lukesampson/scoop/commit/7db0fe938287a141d5e133be04d0a61bc3564ee8

**Comment by Linard11** [comment]
> tried alt-shim already?
> 
> [7db0fe9](https://github.com/lukesampson/scoop/commit/7db0fe938287a141d5e133be04d0a61bc3564ee8)

I don't quite understand. How do I try it?

**Comment by HUMORCE** [comment]
here: https://github.com/lukesampson/scoop/issues/3634#issuecomment-750371232

**Comment by Linard11** [comment]
Sadly did not help both 71 and kiennq have the same problems with Unity.

**Comment by HUMORCE** [comment]
add 'env_add_path' property to replace some filed of 'bin' property.

```
    "bin": [
        "usr\\bin\\tig.exe",
        "git-bash.exe"
    ],
    "env_add_path": "cmd",
```


I have not Unity installed, try it yourself.

**Comment by shinymerlyn** [comment]
> add 'env_add_path' property to replace some filed of 'bin' property.

In which file? Do I need to rescan/do anything afterwards? I see a lot of git related scoop files here. Probably need full instructions that someone who isn't a scoop dev/package maintainer can understand.
