### ISSUE TITLE
Where are scoop logs located? Trying to find out which app update caused my PC to restart without warning

### ISSUE THREAD

**Issue by ferdinandwinters** [ScoopInstaller/Scoop#4319]
I did genuinely try to find where the logs are or some mention of them in the wiki but I could not.

I ran "scoop update *" and while it was running an app updated and then my PC restarted without warning. It didn't halt for any open apps or anything, every process was just terminated and within 20 seconds I was at the login screen again.

I lost some work and data and I know it might be outside of best practice to update scoop while doing other stuff, but I have the idea that no app update should ever restart your PC without informing you first and then setting a delay for a minute or two.

**Comment by HUMORCE** [comment]
`cd $env:SCOOP\cache` to check recently updated.

i think it has nothing to do with scoop.

**Comment by ferdinandwinters** [comment]
Turns out it was winfsp-np, the MSI has a prompt that it needs to restart to continue. Wondering if it's possible to get scoop to pause if the app it's going to update will restart the machine.

**Comment by maphew** [comment]
For me in Powershell `cd $env:SCOOP\cache` fails with _"cd : Cannot find path 'C:\cache' because it does not exist."_ and the drive letter changes depending on what drive the current directory is on. 

(For completeness: in CMD it fails with _"The filename, directory name, or volume label syntax is incorrect."_)

**Comment by maphew** [comment]
I haven't found a location for log files, but in the process did write a first pass document on other folders that might be useful when troubleshooting: https://github.com/ScoopInstaller/Scoop/wiki/Scoop-Folder-Layout

**Comment by rashil2000** [comment]
Scoop does not store generic logs. 

While installing an app, sometimes errors can arise in decompression process. For such errors, log file is stored in the `~/scoop/apps/<app>/<version>` folder
