### ISSUE TITLE
Rolling back to old verison via `reset` can lead `cleanup` to delete the active version

### ISSUE THREAD

**Issue by gavinbeatty** [ScoopInstaller/Scoop#4322]
## Goal
Roll back version of windows-terminal to a version that works for me.

I had 1.6 installed, updated to 1.7, and perhaps because of my custom config file, it fails to start up on the new version. So I wanted to just roll back to 1.6 for now.

## Problem
When following #2254 (specifically [this comment](https://github.com/lukesampson/scoop/issues/2254#issuecomment-388108551)), I experienced inconsistencies in how `hold`, `update`, and `cleanup` work, that led scoop to try to uninstall the active version (as determined by the `current` junction).

## Steps to reproduce

```
C:\Users\gavin>scoop update windows-terminal
windows-terminal: 1.7.1033.0 (latest version)
Latest versions for all apps are installed! For more information try 'scoop status'

C:\Users\gavin>scoop reset windows-terminal@1.6.10571.0
Resetting windows-terminal (1.6.10571.0).
Linking ~\scoop\apps\windows-terminal\current => ~\scoop\apps\windows-terminal\1.6.10571.0
Creating shim for 'WindowsTerminal'.
Creating shim for 'wt'.
Creating shortcut for Windows Terminal (WindowsTerminal.exe)

C:\Users\gavin>scoop info windows-terminal
Name: windows-terminal
Description: The new Windows Terminal, and the original Windows console host - all in the same place!
Version: 1.7.1033.0
Website: https://github.com/microsoft/terminal
License: MIT (https://spdx.org/licenses/MIT.html)
Manifest:
  C:\Users\gavin\scoop\buckets\extras\bucket\windows-terminal.json
Installed:
  C:\Users\gavin\scoop\apps\windows-terminal\1.6.10571.0
  C:\Users\gavin\scoop\apps\windows-terminal\1.7.1033.0
Binaries:
  WindowsTerminal.exe wt.exe

C:\Users\gavin>dir c:\Users\gavin\scoop\apps\windows-terminal
 Volume in drive C has no label.
 Volume Serial Number is XXX

 Directory of c:\Users\gavin\scoop\apps\windows-terminal

04/14/2021  11:27 PM    <DIR>          .
04/14/2021  11:27 PM    <DIR>          ..
04/14/2021  11:21 PM    <DIR>          1.6.10571.0
04/14/2021  11:17 PM    <DIR>          1.7.1033.0
04/14/2021  11:27 PM    <JUNCTION>     current [C:\Users\gavin\scoop\apps\windows-terminal\1.6.10571.0]
               0 File(s)              0 bytes
               5 Dir(s)  102,926,860,288 bytes free

C:\Users\gavin>scoop cleanup windows-terminal
Removing windows-terminal: 1.6.10571.0
```

`dir` shows the junction pointing at 1.6 still. I also tried a `hold` right after `reset`, which seemed to have no effect on the chain of events compared to the above.

## Specifically what's the bug

After `reset` to previous version and `hold`, `update` still chooses the newer version, and `cleanup` removes the active version (leaving the junction dangling).

## Workaround

When the junction is dangling, I can `scoop install windows-terminal@1.6.10571.0`, and while `info` still shows 1.7, if I manually delete the 1.7 dir, I can `hold` on 1.6, and `update` won't upgrade to 1.7, and `cleanup` does nothing (as it should).

## Comments

I don't expect `info` to show 1.6 by the way, I understand it probably just shows what's in the manifest, which is now pointing at 1.7 -- quite reasonable. for that to be the case. I just add it in case it's useful.

**Comment by niheaven** [comment]
Fixed now, if not, please wait for next version bump.
