### ISSUE TITLE
checkver tool encoding problem

### ISSUE THREAD

**Issue by everyx** [ScoopInstaller/Scoop#4324]
I need extract version number from a page with CJK characters, and it does not work correctly, because the `webclient.Encoding` is not set.

should we add a `checkver.encoding` option in App-Manifests file?

```json
"checkver": {
    "url": "https://www.todesk.com/download.html",
    "re": "当前版本:(\\d+.\\d+.\\d+)",
    "encoding": "UTF8"
},
```

and set `webclient` encoding in `checkver.ps1`

https://github.com/lukesampson/scoop/blob/643cfb0da8369dbbe2964511698763c5ff179492/bin/checkver.ps1#L99

```powershell
    $encoding = 'utf-8'
    if ($json.checkver.encoding) {
        $encoding = $json.checkver.encoding
    }
    $wc.Encoding = [System.Text.Encoding]::GetEncoding($json.checkver.encoding)
```

**Comment by HUMORCE** [comment]
```pwsh
$ cat .\bucket\todesk.json      
{
    "version": "0",
    "checkver": {
        "url": "https://www.todesk.com/download.html",
        "regex": "当前版本:([\\d.]+)"
    }
}
$ .\bin\checkver.ps1 -App todesk
todesk: 3.0.0 (scoop version is 0)
DONE
```

works fine.

**Comment by everyx** [comment]
> ```powershell
> $ cat .\bucket\todesk.json      
> {
>     "version": "0",
>     "checkver": {
>         "url": "https://www.todesk.com/download.html",
>         "regex": "当前版本:([\\d.]+)"
>     }
> }
> $ .\bin\checkver.ps1 -App todesk
> todesk: 3.0.0 (scoop version is 0)
> DONE
> ```
> 
> works fine.

@HUMORCE Hi, what's your default Active code page or language? I use scoop in my win10 build 19042 simplified chinese version, Maybe different language versions have different default encodings?

**Comment by HUMORCE** [comment]
same build in english but **unicode utf-8 for worldwide language support** enabled.

```
$ [System.Console]::InputEncoding

Preamble          :
BodyName          : utf-8
EncodingName      : Unicode (UTF-8)
HeaderName        : utf-8
WebName           : utf-8
WindowsCodePage   : 1200
IsBrowserDisplay  : True
IsBrowserSave     : True
IsMailNewsDisplay : True
IsMailNewsSave    : True
IsSingleByte      : False
EncoderFallback   : System.Text.EncoderReplacementFallback
DecoderFallback   : System.Text.DecoderReplacementFallback
IsReadOnly        : True
CodePage          : 65001
```

**Comment by everyx** [comment]
> same build in english but **unicode utf-8 for worldwide language support** enabled.
> 
> ```
> $ [System.Console]::InputEncoding
> 
> Preamble          :
> BodyName          : utf-8
> EncodingName      : Unicode (UTF-8)
> HeaderName        : utf-8
> WebName           : utf-8
> WindowsCodePage   : 1200
> IsBrowserDisplay  : True
> IsBrowserSave     : True
> IsMailNewsDisplay : True
> IsMailNewsSave    : True
> IsSingleByte      : False
> EncoderFallback   : System.Text.EncoderReplacementFallback
> DecoderFallback   : System.Text.DecoderReplacementFallback
> IsReadOnly        : True
> CodePage          : 65001
> ```

I found that if I check

> Beta: Use Unicode UTF-8 for worldwide language support

It's get worked, but If I enable this option, the Chinese characters were garbled on some apps.

![image](https://user-images.githubusercontent.com/1665522/115231248-edd76b80-a147-11eb-8479-97b5fab2472f.png)

**Comment by HUMORCE** [comment]
i think this is an unexpected bug.

btw, the app can handle garbled: [extras/locale-emulator](https://github.com/lukesampson/scoop-extras/blob/master/bucket/locale-emulator.json)

**Comment by everyx** [comment]
> i think this is an unexpected bug.
> 
> btw, the app can handle garbled: [extras/locale-emulator](https://github.com/lukesampson/scoop-extras/blob/master/bucket/locale-emulator.json)

As a program that may be used by users in different languages around the world, I think we should use `utf-8` as the default encoding.

@HUMORCE what's your opinion?

**Comment by ViCrack** [comment]
It should get the character encoding from the Content-Type header in the response

checkver.ps1

[https://stackoverflow.com/a/30049848/8529873](https://stackoverflow.com/a/30049848/8529873)
