### ISSUE TITLE
Scoop status double prints apps on hold

### ISSUE THREAD

**Issue by bjubes** [ScoopInstaller/Scoop#4331]
Just want to confirm this is a bug and not expected behavior before submitting a fix. This is my output after holding youtube-dl. youtube-dl shows in both sections:
```
>scoop status
Scoop is up to date.
Updates are available for:
    audacity: 3.0.0 -> 3.0.2
    ffmpeg: 4.3.2-162 -> 4.4-5
    gh: 1.8.1 -> 1.9.1
    imagemagick: 7.0.11-6 -> 7.0.11-8
    youtube-dl: 2021.04.01 -> 2021.04.17
These apps are outdated and on hold:
    youtube-dl: 2021.04.01 -> 2021.04.17
Everything is ok!
```
I expect it should only show youtube-dl in the second section and not the first.

**Comment by HUMORCE** [comment]
https://github.com/lukesampson/scoop/blob/3d67b7d37c4a2714e8942724d4677dcbd3678f01/libexec/scoop-status.ps1#L65-L105

**Comment by bjubes** [comment]
Basically I'm asking if the code should actually print outdated and not on hold apps in the if statement on 65

**Comment by rashil2000** [comment]
This is expected behavior - not a bug
