### ISSUE TITLE
permission denied on git bash config z.lua package

### ISSUE THREAD

**Issue by zzehli** [ScoopInstaller/Scoop#4340]
I have scoop installed for a while and really enjoy the experience. But I am not very familiar with internals and how to config tools that are installed by scoop.

I recently installed z.lua which needs to be activated through shell. I am using git bash and I follow the config instruction and put the following line in my .bashrc file

The config instruction asks to put the following to bash config
```
eval "$(lua /path/to/z.lua --init bash)"
```
which for me is:
```
eval "$(lua C:/Users/homer/scoop/apps/z.lua --init bash)"
```
The bashrc file is located at ~

But I got the following error msg even when I open the git bash with admin permission. 
```
C:\Users\homer\scoop\apps\lua\current\lua.exe: cannot open C:/Users/homer/scoop/apps/z.lua: Permission denied
```

I am i referring to the install location?

**Comment by HUMORCE** [comment]
```bash
$ cat $SCOOP/apps/z.lua/current/z.lua | head -n 7
#! /usr/bin/env lua
--=====================================================================
--
-- z.lua - a cd command that learns, by skywind 2018, 2019, 2020, 2021
-- Licensed under MIT license.
--
-- Version 1.8.12, Last Modified: 2021/02/15 00:05
```

$SCOOP/apps/z.lua/current/z.lua = lua file
$SCOOP/apps/z.lua = directory

but z.lua does not seem to work on git-bash.

```bash
$ eval "$(lua $SCOOP/apps/z.lua/current/z.lua --init bash)"
bash: @echo: command not found
bash: setlocal: command not found
bash: syntax error near unexpected token `('
```
