### ISSUE TITLE
When using NO_JUNCTIONS config, helpers like dark or lessmsi are not found

### ISSUE THREAD

**Issue by dwettstein** [ScoopInstaller/Scoop#4350]
The `NO_JUNCTIONS` config can be used if users don't want or cannot use the `current` symlinks.

> NO_JUNCTIONS: $true|$false
>   The 'Current' version alias will not be used.
>   Shims and shortcuts will point to specific version instead.

Unfortunately, when this setting is set to `true`, Scoop doesn't find decompression helpers like _dark_ or _lessmsi_ anymore. Reason is, the method `Get-AppFilePath` used by `Get-HelperPath` searches for a hard-coded path `current`.

https://github.com/lukesampson/scoop/blob/3d67b7d37c4a2714e8942724d4677dcbd3678f01/lib/core.ps1#L220
at https://github.com/lukesampson/scoop/blob/3d67b7d37c4a2714e8942724d4677dcbd3678f01/lib/core.ps1#L208
at https://github.com/lukesampson/scoop/blob/3d67b7d37c4a2714e8942724d4677dcbd3678f01/lib/core.ps1#L242

Eventually this could be fixed, if Scoop would use the shims instead of looking at `current` path?

**Comment by rashil2000** [comment]
Closed in #4722
