### ISSUE TITLE
cygwin@2.908: hash check failed

### ISSUE THREAD

**Issue by miguelmsoler** [ScoopInstaller/Scoop#4352]
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'cygwin' (2.908) [64bit]
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 37333e|OK  |    83KiB/s|C:/Users/migue/scoop/cache/cygwin#2.908#https_cygwin.com_setup-x86_64.exe_cygwin-setup.exe
Download: Status Legend:
Download: (OK):download completed.
Checking hash of setup-x86_64.exe ... ERROR Hash check failed!
App:         main/cygwin
URL:         https://cygwin.com/setup-x86_64.exe#/cygwin-setup.exe
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    499b0f5d94488588c5e7f0e73edbb95bf92c0bfbe5379139f79b4d259132486ee026e12cd4191300a7355f28ee19274e9aec472e393cc79f018487034f2d8bf1
Actual:      4d86a04959464eb31c259dca04e679a42de31a1cc5e742984f09ebb35e0d7925609241ba09895933ce08facf0bce7f8616fcb15d3e5f8ac16a787aeb3dd6d019

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=cygwin%402.908%3a+hash+check+failed

**Comment by damienbutt** [comment]
scoop update *
cygwin: 2.907 -> 2.908
Updating one outdated app:
Updating 'cygwin' (2.907 -> 2.908)
Downloading new version
setup-x86_64.exe (1.3 MB) [===================================================================================] 100%
Checking hash of setup-x86_64.exe ... ERROR Hash check failed!
App:         main/cygwin
URL:         https://cygwin.com/setup-x86_64.exe#/cygwin-setup.exe
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    499b0f5d94488588c5e7f0e73edbb95bf92c0bfbe5379139f79b4d259132486ee026e12cd4191300a7355f28ee19274e9aec472e393cc79f018487034f2d8bf1
Actual:      4d86a04959464eb31c259dca04e679a42de31a1cc5e742984f09ebb35e0d7925609241ba09895933ce08facf0bce7f8616fcb15d3e5f8ac16a787aeb3dd6d019

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=cygwin%402.908%3a+hash+check+failed
