### ISSUE TITLE
fail installing gcc

### ISSUE THREAD

**Issue by ikonomn** [ScoopInstaller/Scoop#4354]
Installing 'gcc' (9.3.0-2) [64bit]
Loading mingw-w64-x86_64-binutils-2.34-1-any.pkg.tar.xz from cache
Checking hash of mingw-w64-x86_64-binutils-2.34-1-any.pkg.tar.xz ... ok.
Loading mingw-w64-x86_64-crt-git-8.0.0.5815.9517d302-1-any.pkg.tar.xz from cache
Checking hash of mingw-w64-x86_64-crt-git-8.0.0.5815.9517d302-1-any.pkg.tar.xz ... ok.
The remote server returned an error: (404) Not Found.
URL http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-expat-2.2.9-1-any.pkg.tar.xz is not valid

C:\Users\xxxxxxx>scoop uninstall gcc
Uninstalling 'gcc' (9.3.0-2).
'gcc' was uninstalled.

**Comment by dsbert** [comment]
https://github.com/lukesampson/scoop/issues/4235

**Comment by skanga** [comment]
The same issue occurs when you install openssh and openssl too

**Comment by skanga** [comment]
Additionally, I tried to install JMC and it worked but gave an error at the end after the install.

`Installing 'jmc' (8.0.1-02) [64bit]
jmc-8.0.1_windows-x64.zip (124.2 MB) [========================================================================] 100%
Checking hash of jmc-8.0.1_windows-x64.zip ... ok.
Extracting jmc-8.0.1_windows-x64.zip ... done.
Linking ~\scoop\apps\jmc\current => ~\scoop\apps\jmc\8.0.1-02
Creating shortcut for JDK Mission Control (jmc.exe)
Persisting configuration
'jmc' (8.0.1-02) was installed successfully!
'itcode"' is not recognized as an internal or external command,
operable program or batch file.
`

Perhaps that is a different issue?

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Main/issues/1752
