### ISSUE TITLE
Working directory changed if we cancelled `scoop update` via `CTRL+C`

### ISSUE THREAD

**Issue by Cologler** [ScoopInstaller/Scoop#4358]
Sometimes I only want to use the `scoop status` command to quickly check apps versions, but it becomes `scoop update` if the buckets are outdated. I try to cancel the job, but the working directory stays on the bucket directory.

Scoop uses `Push-Location` to change the working directory to the bucket directory and fetch it from the remote repo. 

To fix this, simply use the `finally` block:

Change

``` ps1
Push-Location $path
...
Pop-Location
```

To

``` ps1
Push-Location $path
try {
   ...
} finally { Pop-Location }
```

**Comment by rashil2000** [comment]
Closed in #4697
