### ISSUE TITLE
how to install scoop in Pycharm since I cannot get access to http://www.get.scoop.sh?

### ISSUE THREAD

**Issue by Julie-Zhong** [ScoopInstaller/Scoop#4360]

**Comment by WhiteCanvas6** [comment]
You first need to have the 'extras' bucket or the 'jetbrains' bucket

add one of them by typing (without the $)
```$ scoop bucket add jetbrains``` or ```$ scoop bucket add extras```

then search by using ```scoop search <search term>```, so in this case it will be ```scoop search pycharm```,

copy one of the packages (without the version number) and use ```scoop install <package name>```

> note 1: package names are case sensitive, so 'pycharm' is different than 'Pycharm'
>
> note 2: if you don't know which package to choose using ```scoop info  <package name>``` will show information about the package
>
>note 3: if you want to know all the available buckets use ```scoop bucket known``` and then ```scoop bucket add <bucket name>``` to add one or ```scoop bucket list``` to list installed buckets and ```scoop bucket rm <bucket name>``` to remove one

**Comment by WhiteCanvas6** [comment]
Sorry i misread the title,
Scoop can be installed on the whole system where it will work on most terminals (Git Bash, Powershell), if you got problems installing be sure to be in an elevated(admin) Powershell window and follow the steps in https://scoop.sh/

**Comment by rashil2000** [comment]
#4264
