### ISSUE TITLE
Add the possibility to ignore dependencies for certain packages

### ISSUE THREAD

**Issue by buehler** [ScoopInstaller/Scoop#4374]
Hey there

First of all: great work! I really like scoop and in my opinion it is one of the best managers for windows altogether.

However, I'd like to be able to ignore dependencies for certain packages. As an example: the flutter package depends on a java version and on android-sdk. If I have the sdk already installed (as well as java) I don't need (and don't want) to install another adk and another java version. But every time I try to install - and later update - flutter, scoop wants to install android again. It would be cool to have some kind of config (file?), where I could put the `-i` flag for certain packages permanently.

I'm also happy to contribute, if you take PRs and put me into the right direction, although I'm not fluent in PowerShell programming

Regards
Christoph

**Comment by rashil2000** [comment]
A PR would be much appreciated!

However, this is being tracked in #3800 so I'll close this
