### ISSUE TITLE
Scoop Shims Interfere with Child Process Creation in Node.js

### ISSUE THREAD

**Issue by rbrisita** [ScoopInstaller/Scoop#4376]
Installing Scoop programs with shims forces two instances to be created when Node.js 'child_process' methods are called regardless of their configuration parameters. For example:

```shell
scoop install ffmpeg
```
Creates ~\scoop\shims\
```
ffmpeg.exe
ffmpeg.ps1
ffmpeg.shim
ffplay.exe
ffplay.ps1
ffplay.shim
```

Writing code:
```js
const child_process = require('child_process');
const ffplay = child_process.spawn('ffplay', ['audio.mp3']);
```
Creates two 'ffplay' processes when only one should have been created.

**Comment by rashil2000** [comment]
Merged in develop branch - #4543
