### ISSUE TITLE
Cannot update the proxy config

### ISSUE THREAD

**Issue by finalwhy** [ScoopInstaller/Scoop#4380]
I chang my proxy config to an new port of localhost， but when i run "scoop update" and it still use the old one
 
Screenshot
![WindowsTerminal_wgqSDBPofR](https://user-images.githubusercontent.com/24859256/121453211-5d910680-c9d3-11eb-9dba-dcc7b69e7251.png)

**Comment by HUMORCE** [comment]
scoop-update(by git) does not seem to through the proxy server

some ways for anti gfw and dns pollution:
- set http_proxy/https_proxy env variables
- use [proxychains-windows](https://github.com/HUMORCE/scoop-nuke/blob/master/bucket/proxychains.json)
- update via ssh (https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh), `scoop config SCOOP_REPO git@github.com:lukesampson/scoop.git`

**Comment by flespark** [comment]
It also happened to me. When I remove the proxy relative environment and `scoop config rm proxy`. scoop try to update and download from proxy port

**Comment by wsxyeah** [comment]
That happens to me because I have set my git global proxy to `localhost:1080`.

You may clear your global git proxy config by running
```powershell
git config --global --unset http.proxy
```
