### ISSUE TITLE
[FEATURE] "scoop import" Command 

### ISSUE THREAD

**Issue by finalwhy** [ScoopInstaller/Scoop#4384]
We already have an “export ” command which allow us to export the list of applications installed by scoop
So I think there will also be a "import" command  that allows us to install applications based on the list exported by "export", right?

**Comment by HUMORCE** [comment]
try the method iam using:
https://gist.github.com/HUMORCE/1add93259ed5cbabd31e0c2bb28b4caf

**Comment by rashil2000** [comment]
#3934
