### ISSUE TITLE
Post-install script for NodeJS 16.3.0 contaminated by Heur.BZC.ZFV.Boxter.830.CD4F31A8

### ISSUE THREAD

**Issue by luzb3l** [ScoopInstaller/Scoop#4385]
I tried to install NodeJS 16.3.0 through scoop, and the installation went well but the antivirus stopped the post-install script with the following notice:

"Antivirus

PowerShell tried to load a malicious resource detected as Heur.BZC.ZFV.Boxter.830.CD4F31A8 and was blocked. Your device is safe."

![image](https://user-images.githubusercontent.com/36280942/122167989-53429280-ce41-11eb-8809-5568cbbc1590.png)

Even though node seemed to install successfully, I uninstalled it.

**Comment by Deide** [comment]
That's odd. Here is the contents of the post install script:

    "post_install": [
         "# Set npm prefix to install modules inside bin and npm cache so they persist",
        "Set-Content -Value \"prefix=$persist_dir\\bin`ncache=$persist_dir\\cache\" -Path \"$dir\\node_modules\\npm\\npmrc\""
    ],

**Comment by rashil2000** [comment]
You can read the manifest's content to ensure if something is malicious. On a related note, it is advised to add an exclusion for Scoop's folder to the antivirus settings to prevent false positives like this.
