### ISSUE TITLE
[Windows] resolve path emitted by 'scoop which'

### ISSUE THREAD

**Issue by jannick0** [ScoopInstaller/Scoop#4388]
Currently `scoop which` emits something like  `~\scoop\apps\act\current\app.exe` on Windows.

I would expect `~` to be resolved such that the result, an absolute path, could be used without any additional step (like using PS's `Resolve-Path`).

**Comment by HUMORCE** [comment]
`scoop alias add which-abs '(scoop which $args[0] | Resolve-Path).Path'`
