### ISSUE TITLE
scoop search error

### ISSUE THREAD

**Issue by DoveBoy** [ScoopInstaller/Scoop#4394]
Using the `sccop search` command to search, the same error is reported every time
![image](https://user-images.githubusercontent.com/19201447/123090937-53ebb200-d45b-11eb-8664-10b5b294f18e.png)
![image](https://user-images.githubusercontent.com/19201447/123091031-72ea4400-d45b-11eb-8bc7-b5c5921c8562.png)

**Comment by HUMORCE** [comment]
caused by the bucket(s) you added.
