### ISSUE TITLE
Windows Update 21H1

### ISSUE THREAD

**Issue by damienbutt** [ScoopInstaller/Scoop#4397]
Has anyone else updated to the 21H1 May update? 

I updated but it messed up my scoop app installations. The scoop directory in the start menu had loads of apps missing. The apps are still there in the scoop directory in the user directory. You cant search for the apps either using start or PowerToys Run. 

Thank god I took a snapshot before updating! Rolled it back straight away.

**Comment by dannyvoid** [comment]
I have. I was able to manually reset each app, and they showed up.
`scoop reset "name"`

But any use of resetting all installs at once would break horribly.
`scoop reset *`

**Comment by NatoBoram** [comment]
I'm personally running it with Scoop. The upgrade removed my Scoop installation, but I just had to rename `%UserProfile%\scoop`, run `iwr -useb get.scoop.sh | iex` and replace the new `%UserProfile%\scoop` with the renamed one.

`sudo scoop reset *` throws lots of errors, but at the end, all app shortcuts are fine. If an app doesn't work correctly, try to force-upgrade it or reinstall it.
