### ISSUE TITLE
Cleaning up the cache gives no information to the user

### ISSUE THREAD

**Issue by tukanos** [ScoopInstaller/Scoop#4400]
I tried to clean-up the old cache but it virtually gives no information on what is happening.

- For example:

I had about 10 vivaldis' installators. 

- When I entered: 

`scoop cleanup --cache vivaldi`

I got only `vivaldi is already clean` message.  No message what was removed or that actually something happened.  I had to check manually.

- What I would expect:

Is to get list of deleted vivaldis' exe files from cache.

**Comment by rashil2000** [comment]
Tracked in #3904
