### ISSUE TITLE
Scoop not installing

### ISSUE THREAD

**Issue by forkmaster14** [ScoopInstaller/Scoop#4401]
When I try to install scoop, it throws an error saying that it can't make a directory because there is no drive D:

**Comment by HUMORCE** [comment]
leave a full error message.

**Comment by Forkmaster14** [comment]
Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
Initializing...
mkdir : Cannot find drive. A drive with the name 'D' does not exist.
At line:354 char:49
+ ... ion ensure($dir) { if(!(test-path $dir)) { mkdir $dir > $null }; reso ...
+                                                ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (D:String) [New-Item], DriveNotFoundException
    + FullyQualifiedErrorId : DriveNotFound,Microsoft.PowerShell.Commands.NewItemCommand

**Comment by HUMORCE** [comment]
has installed before this error?

**Comment by Forkmaster14** [comment]
no, I have never installed scoop before.

**Comment by HUMORCE** [comment]
and environment variables? `ls env:`

**Comment by Forkmaster14** [comment]
Name                           Value
----                           -----
ALLUSERSPROFILE                C:\ProgramData
APPDATA                        C:\Users\prate\AppData\Roaming
ChocolateyInstall              c:\ProgramData\chocoportable
ChocolateyLastPathUpdate       132699262592305081
ChocolateyToolsLocation        C:\tools
CommonProgramFiles             C:\Program Files\Common Files
CommonProgramFiles(x86)        C:\Program Files (x86)\Common Files
CommonProgramW6432             C:\Program Files\Common Files
COMPUTERNAME                   PRATEEK-WINDOWS
ComSpec                        C:\WINDOWS\system32\cmd.exe
DriverData                     C:\Windows\System32\Drivers\DriverData
HOMEDRIVE                      C:
HOMEPATH                       \Users\prate
IntelliJ IDEA                  C:\Users\prate\IntelliJ IDEA 2021.1.3\bin;
LOCALAPPDATA                   C:\Users\prate\AppData\Local
LOGONSERVER                    \\PRATEEK-WINDOWS
NUMBER_OF_PROCESSORS           8
OneDrive                       C:\Users\prate\OneDrive - Loudoun County Public Schools
OneDriveCommercial             C:\Users\prate\OneDrive - Loudoun County Public Schools
OneDriveConsumer               C:\Users\prate\OneDrive
OnlineServices                 Online Services
OS                             Windows_NT
Path                           C:\Program Files\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\...
PATHEXT                        .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL
platformcode                   KV
PROCESSOR_ARCHITECTURE         AMD64
PROCESSOR_IDENTIFIER           Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
PROCESSOR_LEVEL                6
PROCESSOR_REVISION             8c01
ProgramData                    C:\ProgramData
ProgramFiles                   C:\Program Files
ProgramFiles(x86)              C:\Program Files (x86)
ProgramW6432                   C:\Program Files
PSModulePath                   C:\Users\prate\OneDrive\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsP...
PUBLIC                         C:\Users\Public
PyCharm                        C:\Program Files\JetBrains\PyCharm 2021.1.3\bin;
RegionCode                     NA
RG_GPU_FRAMEWORK_ENGINE_RES... C:\Program Files\Red Giant\RGFX
SCOOP                          D:\Applications\Scoop
SESSIONNAME                    Console
SystemDrive                    C:
SystemRoot                     C:\WINDOWS
TEMP                           C:\Users\prate\AppData\Local\Temp
TMP                            C:\Users\prate\AppData\Local\Temp
USERDOMAIN                     PRATEEK-WINDOWS
USERDOMAIN_ROAMINGPROFILE      PRATEEK-WINDOWS
USERNAME                       prate
USERPROFILE                    C:\Users\prate
windir                         C:\WINDOWS
ZES_ENABLE_SYSMAN              1

**Comment by HUMORCE** [comment]
> SCOOP D:\Applications\Scoop

unset or edit it, following this: https://github.com/lukesampson/scoop/wiki/Quick-Start#installing-scoop-to-custom-directory
