### ISSUE TITLE
FEATURE: Use existing `sh` script if one exists

### ISSUE THREAD

**Issue by BatmanAoD** [ScoopInstaller/Scoop#4413]
VSCode (and possibly other applications) installs a shell script, `code`, with no file extension and a valid shebang. The primary use for this script is for WSL integration.

`scoop` currently can't expose this script, because it generates its own `code` shim that invokes `code.cmd`. This is despite the fact that the manifest for VSCode [includes `code` as a `bin` entry](https://github.com/lukesampson/scoop-extras/blob/master/bucket/vscode.json#L39).

Symlinking the VSCode `code` script _in place of_ the Scoop-generated shim appears to work as expected, both for the standard use-case of the shim (i.e. launching the application from something like Git Bash) and for WSL.

I suggest that when a file with no extension is included in the `bin` entry of a package manifest, a symlink to this file should be generated in place of a normal shim.

**Comment by BatmanAoD** [comment]
Related to #4035 and https://github.com/lukesampson/scoop-extras/issues/2581

**Comment by rashil2000** [comment]
Merged in develop branch - #4543
