### ISSUE TITLE
Bucket PR reviews for new/updated manifests?

### ISSUE THREAD

**Issue by dennisroche** [ScoopInstaller/Scoop#4430]
What is the current review process for getting new/updated manifests? 

At the moment there 166 PRs open on the [main bucket](https://github.com/ScoopInstaller/Main/pulls), mostly with green builds. 

e.g. do we need to add `please-review` labels to get a maintainer to review?

**Comment by telenieko** [comment]
> What is the current review process for getting new/updated manifests?

I don't think there is a formal process, except for the criteria for inclusion to main. Everything else is pretty much left to the maintainer's discretion.

> At the moment there 166 PRs open on the [main bucket](https://github.com/ScoopInstaller/Main/pulls), mostly with green builds.

There appears to be some backlog. Both in main and extras.  Automating the merge of the "Hash fix" PR's could clear a lot of that, @lukesampson ?

> e.g. do we need to add `please-review` labels to get a maintainer to review?

This kind of exists already, all PRs have a "review required" (or not required) status at the bottom. You can search against that:

> is:pr is:open review:required 
> is:pr is:open review:approved

**Comment by dennisroche** [comment]
There is an existing `please-review` tag that was used previously. Not recommending or suggesting we adopt this as GitHub now has reviews built-in. 

> is:pr is:open review:required

Suggest `is:pr is:open review:required status:success` to only show PRs that have passed automated checks (filters [main](https://github.com/ScoopInstaller/Main/pulls?q=is%3Apr+is%3Aopen+review%3Arequired+status%3Asuccess) down to 144 from 166).
