### ISSUE TITLE
Installing: The term 'scoop' is not recognized as a name of a cmdlet, function, script file, or executable program.

### ISSUE THREAD

**Issue by stmax82** [ScoopInstaller/Scoop#4432]
Trying to install scoop, I get the following error somewhere around the end:

```Invoke-Expression: The term 'scoop' is not recognized as a name of a cmdlet, function, script file, or executable program.```

Full command and output:

```
PowerShell 7.1.4
Copyright (c) Microsoft Corporation.

(base) PS C:\Users\xxx> Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
Initializing...
Downloading scoop...
Extracting...
Creating shim...
Downloading main bucket...
Extracting...
Invoke-Expression: The term 'scoop' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
(base) PS C:\Users\xxx>
```

**Comment by HUMORCE** [comment]
exit from the virtual environment.

**Comment by stmax82** [comment]
@HUMORCE thanks for the recommendation - I ran `conda deactivate` first to get out of the base environment, but that didn't help:

```
PowerShell 7.1.4
Copyright (c) Microsoft Corporation.

(base) PS C:\Users\xxx> conda deactivate
PS C:\Users\xxx>
PS C:\Users\xxx> Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
Initializing...
Downloading scoop...
Extracting...
Creating shim...
Downloading main bucket...
Extracting...
Invoke-Expression: The term 'scoop' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
PS C:\Users\xxx>
```

For some reason it doesn't seem to add scoop to the path?

If I later manually add `%USERPROFILE%\scoop\shims` to the user's environment, scoop seems to work.

**Comment by HUMORCE** [comment]
some program (e.g. antivirus software ) have blocked environment variable modification?

**Comment by stmax82** [comment]
Not that I know of... plain Windows 10 on a private system (no corporate policy stuff) with default antivirus software.

I guess I'll have to download and debug this script..

**Comment by rashil2000** [comment]
Try using PowerShell 5.1, or upgrade PowerShell version if you;ve installed from Store.
