### ISSUE TITLE
scoop search error

### ISSUE THREAD

**Issue by DoveBoy** [ScoopInstaller/Scoop#4434]
use scoop search app function error on Windows10 x64
![image](https://user-images.githubusercontent.com/19201447/129898135-0598a995-751d-410e-b7b2-f093de4d66b5.png)

**Comment by rashil2000** [comment]
Looks like an error in your added bucket

**Comment by DoveBoy** [comment]
> Looks like an error in your added bucket

In fact, upgrading pwsh works fine
