### ISSUE TITLE
Lack of encoding feature on package installation

### ISSUE THREAD

**Issue by emrengsi** [ScoopInstaller/Scoop#4435]
My username in Windows 10 is with a glyph that could be supported only by UTF-8, when I installed nodejs even installation went fine, I had so many errors while installing npm packages and seen environment-variables-path problems. Then I noticed that the scoop doubled the user folder with another username with non-utf-8 chars and placed the global npm bin folder there that causes the npm scripts to throw errors as if the path didn't exist.

**Comment by rashil2000** [comment]
#2230
