### ISSUE TITLE
Feature request for programmatically check if package is installed (or scoop list could output as return instead of write-host)

### ISSUE THREAD

**Issue by arberg** [ScoopInstaller/Scoop#4437]
I would like to be able to determine if a package is installed. I want this so I can run my install-all-my-programs script without getting warnings. My solution for this is to check whether package is already installed and skip install/uninstall based on that.

I can't seem to figure out how to determine if a package is installed programmatically, because `scoop list` uses write-host to print installed packages. I could perhaps write something like a transcript to pick it up, but it seems more reasonable to just get some programmatic access to this. Could be an argument to scoop that cause it to print output that is parsable, or powershellish object-like.

**Comment by TonyApuzzo** [comment]
use `scoop export` see: https://github.com/ScoopInstaller/Scoop/issues/4030

**Comment by rashil2000** [comment]
You can also do `scoop list $query 6>&1` to output strings and use them
