### ISSUE TITLE
Installing anything new fails with multiple PS errors, 'local:url' not recognized

### ISSUE THREAD

**Issue by ev-dev** [ScoopInstaller/Scoop#4444]
Any attempts to install something throws multiple unexpected powershell errors from scoop's depends.ps1 & install.ps1

Steps to reproduce:
`> scoop install wget` (tested with many apps)

Output:
```
url: C:\Users\evdev\scoop\apps\scoop\current\lib\depends.ps1:83
   83 |  … lled -Helper Lessmsi) -and (Test-LessmsiRequirement -URL (url $manife
        | The term 'local:url' is not recognized as a name of a cmdlet, function,....

url: C:\Users\evdev\scoop\apps\scoop\current\lib\install.ps1:529
 529 |      $urls = @(url $manifest $architecture)
        | The term 'local:url' is not recognized as a name of a cmdlet, function,....

url: C:\Users\evdev\scoop\apps\scoop\current\lib\install.ps1:203
 203 |      $urls = @(url $manifest $architecture)
        | The term 'local:url' is not recognized as a name of a cmdlet, function,....
...

Can't shim 'wget': File doen't exist.
```

It's been a few weeks since I installed anything new via scoop, and updates have been working fine so I'm pretty stumpted as to what the actual underlying problem is and whether or not it's something specific to my env. 
Any help would be greatly appreciated!

**Comment by HUMORCE** [comment]
already reinstalled scoop?

**Comment by ev-dev** [comment]
Welp I was trying to avoid that since I have so many running services/apps installed with scoop but since I'm the one asking for help I figured I should go thru with the trouble so after `scoop list > ~\scoop_apps.txt` I nervously `del -Force ~\scoop` (note to others seeking a clean reinstall, you may have other scoop related directories like `C:\Program Files (x86)\scoop` to remove if true clean state is desired).

I actually did run into the same errors from this issue when I tried `scoop install sudo` BUT then I realized I've been doing everything in powershell preview (7.2 p9) so I repeated the reinstall via powershell 5 (the preinstalled old school blue one) and of course, the issue went away 😥

I tried to do a bit of exploring the src to try and come up with what may be a potential issue coming in powershell 7.2, but I'm not really well versed enough in debugging powershell (if anyone is...sorry to hate). Seems like the error is coming from the `Find-Manifest` or `find_manifest` functions perhaps when checking for paths of local manifests. Apologies for lack of effort...I'll try harder if anyone else encounters this!

(Wasn't sure if I should close in case there really is a powershell 7.2 compat bug)

**Comment by Cologler** [comment]
Currently, scoop is run on the current PowerShell instance, I guess your `$profile` added alias and it overrides the default scoop function.

To confirm that, try using `pwsh -NoProfile $(Resolve-Path ~\scoop\shims\scoop.ps1) install ...` to install the app and see if it is okay.

**Comment by Fooughhy** [comment]
I believe at least one version of the same issue has been present for a long time, #4185, but was fixed. I've had the Pansies module disabled, but was able to enable it again once that issue was fixed. It seems that (#4342 and #4492) did not fix all instances of the issue.

If I do "Remove-Module Pansies", the issue disappears.

**Comment by rashil2000** [comment]
Could you point us to more instances of the code which causes the error?

**Comment by Fooughhy** [comment]
Sorry, this might not be exactly the same. I simply saw the same error that I've seen before, but I see now that he has "local:url" everywhere, and not "script:url" or simply "url" which was the issue before.

But there is an error in the repo:
https://github.com/ScoopInstaller/Scoop/blob/37a886947df6cfdc76ebede44af6d1f10d426ba1/lib/depends.ps1#L92

**Comment by rashil2000** [comment]
> But there is an error in the repo:
> 
> https://github.com/ScoopInstaller/Scoop/blob/37a886947df6cfdc76ebede44af6d1f10d426ba1/lib/depends.ps1#L92

Yes, looks like this was indeed overlooked. Can you make this change in your local Scoop folder and see if it resolves the Pansies error?

**Comment by Fooughhy** [comment]
Yes, that seems to fix it.

**Comment by rashil2000** [comment]
Fixed.

Thanks!
