### ISSUE TITLE
dotnet-sdk - Why is it so slow and flakey to download/update???

### ISSUE THREAD

**Issue by damienbutt** [ScoopInstaller/Scoop#4445]
Any ideas why this package is an absolute pain to install/update?

The download is so slow and most of the time is fails.

Don't have issues with any other package. Just dotnet-sdk.

D

**Comment by damienbutt** [comment]
Trying to install it now on a new machine. The last two attempts failed at 28%. Attempts prior to that got to around 38%.

Always the same error...

```
Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
URL https://dotnetcli.blob.core.windows.net/dotnet/Sdk/5.0.400/dotnet-sdk-5.0.400-win-x64.zip is not valid
```

**Comment by damienbutt** [comment]
![Capture1](https://user-images.githubusercontent.com/22627489/132068178-e708b975-fb1c-41f7-ab05-02d40015599e.PNG)

**Comment by HUMORCE** [comment]
four hours ago, i was also slow in downloading it. but now, it can be done in ~3 secs.

so it is related to your network environment, or server status.

scoop does not store any package.

**Comment by AlizerUncaged** [comment]
2024 this is still the problem 
![image](https://github.com/ScoopInstaller/Scoop/assets/86959368/226b827f-b1fc-4018-b173-cb5c3ff18e5d)

**Comment by PwccaCode** [comment]
2025 this still a problem
