### ISSUE TITLE
A Error when install gcc

### ISSUE THREAD

**Issue by zhcBaike** [ScoopInstaller/Scoop#4446]
PS C:\Users\ZC> scoop install gcc
Installing 'gcc' (9.3.0-2) [64bit]
Loading mingw-w64-x86_64-binutils-2.34-1-any.pkg.tar.xz from cache
Checking hash of mingw-w64-x86_64-binutils-2.34-1-any.pkg.tar.xz ... ok.
Loading mingw-w64-x86_64-crt-git-8.0.0.5815.9517d302-1-any.pkg.tar.xz from cache
Checking hash of mingw-w64-x86_64-crt-git-8.0.0.5815.9517d302-1-any.pkg.tar.xz ... ok.
远程服务器返回错误: (404) 未找到。
**URL http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-expat-2.2.9-1-any.pkg.tar.xz is not valid**

the website has only "mingw-w64-x86_64-expat-2.2.10-1" rather than "mingw-w64-x86_64-expat-2.2.9-1"

**Comment by yesudeep** [comment]
The fix from @Ash258 appears to work. Please consider including the updated gcc.json in the main repository.

**Comment by robusoft-tangye** [comment]
I also encountered this problem, both gcc and gdb.

> scoop install gdb
Installing 'gdb' (9.1-3) [64bit]
The remote server returned an error: (404) Not Found.
URL http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-bzip2-1.0.8-1-any.pkg.tar.xz is not valid

> scoop install gcc
Installing 'gcc' (9.3.0-2) [64bit]
Loading mingw-w64-x86_64-binutils-2.34-1-any.pkg.tar.xz from cache
Checking hash of mingw-w64-x86_64-binutils-2.34-1-any.pkg.tar.xz ... ok.
Loading mingw-w64-x86_64-crt-git-8.0.0.5815.9517d302-1-any.pkg.tar.xz from cache
Checking hash of mingw-w64-x86_64-crt-git-8.0.0.5815.9517d302-1-any.pkg.tar.xz ... ok.
The remote server returned an error: (404) Not Found.
URL http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-expat-2.2.9-1-any.pkg.tar.xz is not valid

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Main/issues/1752
