### ISSUE TITLE
Include date last updated in scoop info

### ISSUE THREAD

**Issue by ev-dev** [ScoopInstaller/Scoop#4448]
As a suggestion, it would be really helpful to users to include the date last updated when calling `scoop info <app>` 

Example output from `scoop info starship`
```
Name: starship
Description: The minimal, blazing fast, and extremely customizable prompt for any shell!
Version: 0.57.0
Updated: 2021-08-26
Website: https://starship.rs
License: ISC (https://spdx.org/licenses/ISC.html)
Manifest:
  C:\Users\evdev\scoop\buckets\main\bucket\starship.json
Installed:
  C:\Users\evdev\scoop\apps\starship\0.57.0
Binaries:
  starship.exe
Notes
-----
```

I'm starting to investigate what it would take for this and it does seem to require a bunch of changes so I'm not sure if it's a worthy endeavor but if others want to see it, I'd be happy to give it a go. 

Possible implementations:

- a) Update manifest spec to include date when updates are pushed
  - Probably ideal implementation, otherwise additional network calls?
  - Allow this to be optional (and output "Unknown" for Updated: when not included (so that mainters aren't required to make changes?)
- b) Changes to `checkver.ps1` to include date when updated manifest is found
  - Not sure this makes sense since it still requires some way of retrieving the actual date of a version which may not be possible for app sources other than github
- c) Better idea

Any thoughts on implementation would be appreciated!

**Comment by rashil2000** [comment]
Using Git history would be the best way to implement this - https://stackoverflow.com/a/56373126
