### ISSUE TITLE
Cannot install gcc

### ISSUE THREAD

**Issue by midnightexigent** [ScoopInstaller/Scoop#4453]
Hi, I just tried to install `gcc` and got this error

```
~
❯ scoop install gcc
Installing 'gcc' (9.3.0-2) [64bit]
mingw-w64-x86_64-binutils-2.34-1-any.pkg.tar.xz (13.9 MB) [===========================================================================================] 100%
Checking hash of mingw-w64-x86_64-binutils-2.34-1-any.pkg.tar.xz ... ok.
mingw-w64-x86_64-crt-git-8.0.0.5815.9517d302-1-any.pkg.tar.xz (3.1 MB) [==============================================================================] 100%
Checking hash of mingw-w64-x86_64-crt-git-8.0.0.5815.9517d302-1-any.pkg.tar.xz ... ok.
The remote server returned an error: (404) Not Found.
URL http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-expat-2.2.9-1-any.pkg.tar.xz is not valid
```

**Comment by sskras** [comment]
PS. @Ash258, you seem to be reacting to my comment. 

Can you explain what's going on between these three repos + how do they relate:
https://github.com/lukesampson/scoop
https://github.com/Ash258/Scoop-Core
https://github.com/ScoopInstaller/Main

What's the deal or the roadmap?

**Comment by sskras** [comment]
@Ash258, as you react with 😄 the second time, I tried googling a bit more.

Now my guess is that you just want to say you have hard time maintaining documentation of your own repo.
(namely public relations between these two projects).

So it your repo could speak out something clear like [rasa/scoop-directory](https://github.com/rasa/scoop-directory) by @rasa 

Did I get your `:smile:` right? Or do you just try being offensive?

Either way, these URLs bring more clarity about the relation mess:
https://github.com/lukesampson/scoop/issues/2609
https://github.com/lukesampson/scoop/issues/4456
https://github.com/ScoopInstaller/Main/issues/2403
https://github.com/Ash258/Scoop-Core/issues/63

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Main/issues/1752
