### ISSUE TITLE
Is there a way to create a "metapackage"?

### ISSUE THREAD

**Issue by pigsflew** [ScoopInstaller/Scoop#4454]
This would be a package that contains a list of packages that should be installed as dependencies, and otherwise does nothing.

I attempted to create the following:

`graalvm.json`
```json
{
    "description": "Alias for `graalvm-jdk11`: GraalVM Community Edition; powered by OpenJDK 11.",
    "version": "1.0",
    "depends": "graalvm-jdk11"
}
```

but attempting to install it says `graalvm does not support 64bit architecture`.

I'd like it to simply do nothing and install the dependencies.

**Comment by Deide** [comment]
No, but it could be tangentially connected to #4384

**Comment by pigsflew** [comment]
That would work, yeah--I'll give it a shot. I still think It'd be cool to have this as a feature though, maybe with a type flag or something.

Thanks for the help!

**Comment by rashil2000** [comment]
#2155
