### ISSUE TITLE
Is there a way to recognize already installed applications similarly to winget?

### ISSUE THREAD

**Issue by nickshanks347** [ScoopInstaller/Scoop#4455]
I've been using winget for 3-4 months and I found out about scoop today.

The good thing about winget is it recognizes which programs you already have installed. You can simply install winget-cli, do a `winget export` and then `winget import` on another machine, as long as the app exists in the winget repository, it will get installed because it recognizes that the program was installed (regardless of whether it was installed by winget, or not). Is there any way to make scoop recognize which programs you currently have installed so that I don't have uninstall every program and re-install with scoop. It would be great if this was possible. Any ideas?

**Comment by HUMORCE** [comment]
no

**Comment by rashil2000** [comment]
This is not possible, neither is it the goal of scoop.
