### ISSUE TITLE
Does this project need more maintainers?

### ISSUE THREAD

**Issue by akirayamamoto** [ScoopInstaller/Scoop#4456]
I am seeing more and more forks of this project. It's good that this project is open source so whoever feels like can fork it. However, that just spreads the energy all over and will tend to weaken this project which was the main one.

So, are you accepting more contributors?

**Comment by dwettstein** [comment]
To me, this project has the same problems as discussed in https://github.com/ScoopInstaller/Main/issues/2403. Additionally, no one is able or willing to add more maintainers.

Some of the very important missing features were already implemented by @Ash258 in his fork https://github.com/Ash258/Scoop-Core.

**Comment by sskras** [comment]
@dwettstein, thanks for the info.
Is the owner of this repo available/alive?

**Comment by cprieto** [comment]
It is funny because I actually did the same question (do you need more maintainers?) months ago and "our favourite rude maintainer" answer with a simple "No, we are fine, thanks".

It breaks my heart how this amazing project is dying, I mean, it is common now to see broken packages and wait months for the package to be fixed, I wish there could be anything we can do but in my case I got a little tired of rude people who doesn't need help.

😞

**Comment by deevus** [comment]
Hey everyone. I'm one of the original maintainers, and although I'm not active anymore (https://github.com/ScoopInstaller/Main/issues/2403#issuecomment-947185550) I'm willing to help where I can so that the project can live on.

**Comment by deevus** [comment]
@rasa You should now have permission to add people to the maintainers team.

**Comment by rasa** [comment]
@niheaven or @issaclin32 are now owners.

**Comment by rasa** [comment]
> > Isn't `ScoopInstaller/scoop.sh` the website repo?
> 
> That was a WIP remake of the [Scoop Wiki](https://github.com/ScoopInstaller/Scoop/wiki) by an user, being forked to this org. It's not affiliated to the org and the fork can be deleted safely.
> 
> could you please enable the branch protection rule of **Requiring a pull request before merging, and at least 2 member approvals** (was 1 for the main bucket repo) for all writable repos? 

@chawyehsu OK, I set up our bucket repos to have branch protected but only with 1 member approval (for now). I left it as 1 for bucket repos as that is what it was previously for the Main bucket. If we see commit/merge mistakes slip through, we can bump this up to 2. The Scoop repo requires 2 approvals, but I removed the branch protection for the develop branch, as that didn't make sense.
