### ISSUE TITLE
Hope to add aria2 command

### ISSUE THREAD

**Issue by hxse** [ScoopInstaller/Scoop#4458]
Hope to add `scoop config aria2-proxy` command to set up proxy.

**Comment by HUMORCE** [comment]
https://github.com/lukesampson/scoop/blob/092005046454d94d141d5c68fdbdb4c4a1229ae9/lib/install.ps1#L201-L251

choose one of them:

- L235 - 245: `scoop config proxy "http://127.0.0.1:1234"`
- L248 - 251: `scoop config aria2-options @('--all-proxy="http://127.0.0.1:1234"')`
