### ISSUE TITLE
pcsx2-dev update and install error

### ISSUE THREAD

**Issue by Tyler-Osborne** [ScoopInstaller/Scoop#4460]
Terminal says "Loading index.php from cache
Extracting dl.7z ... Could not find 'pcsx2-v1.7.0-dev-1794-gffbfd2c84-windows-x86'! (error 16)
At C:\Users\gothi\scoop\apps\scoop\current\lib\core.ps1:510 char:9
+         throw "Could not find '$(fname $from)'! (error $($proc.ExitCo ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find ...86'! (error 16):String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find 'pcsx2-v1.7.0-dev-1794-gffbfd2c84-windows-x86'! (error 16)"
When trying to update or install pcsx2-dev

**Comment by ompadu** [comment]
I've been having the same error:

```
Installing 'pcsx2-dev' (1.7.0-1800) [64bit]
index.php (5.9 MB) [==========================================================================================] 100%
Checking hash of index.php ... ok.
Extracting dl.7z ... Could not find 'pcsx2-v1.7.0-dev-1800-g2406ae6e0-windows-x86'! (error 16)
At C:\Users\<username>\scoop\apps\scoop\current\lib\core.ps1:510 char:9
+         throw "Could not find '$(fname $from)'! (error $($proc.ExitCo ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find ...86'! (error 16):String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find 'pcsx2-v1.7.0-dev-1800-g2406ae6e0-windows-x86'! (error 16)
```

**Comment by ompadu** [comment]
It's working again 🎉

**Comment by ompadu** [comment]
Broken again....

**Comment by rashil2000** [comment]
Which bucket is pcsx2-dev in?

**Comment by ompadu** [comment]
> 
> 
> Which bucket is pcsx2-dev in?

games

**Comment by rashil2000** [comment]
Have you tried reporting it in that bucket repo? This looks like a manifest problem.

**Comment by ompadu** [comment]
> 
> 
> Have you tried reporting it in that bucket repo? This looks like a manifest problem.

[It is now](https://github.com/Calinou/scoop-games/issues/463).
