### ISSUE TITLE
things are not really installed but marked as "is already installed", worst thing about of Scoop

### ISSUE THREAD

**Issue by yilmazdurmaz** [ScoopInstaller/Scoop#4462]
I am trying to install "rust" and somewhere on the line, there are problems to prevent downloading the complete file.

I first tried without aria2, and it was 1-3% of the file where connection to file server breaks and leaves me with this "is already installed" message if I try the install again, and asks me to "first uninstall, then try again".

then I tried with aria2, somewhere over 50% it breaks again. and then the same "is installed, first uninstall". the process is also started from the ground because the partially downloaded file was also broken and aria2 had to redownload the file at full. fortunately, I was not is a mobile network and it was not something urgent to have.

though it finally got the full file and installed, this process left its scars as "Scoop marks packages as installed without really and fully installing them", also does not seem to resume broken downloads.

please review this installation process and fix this false installation of not-really-installed packages.

**Comment by yilmazdurmaz** [comment]
@rashil2000  do you guys close issues without a word all the time?

**Comment by rashil2000** [comment]
Would have been better if you had searched if the exact same issue existed already.

https://github.com/ScoopInstaller/Scoop/pull/3281

**Comment by yilmazdurmaz** [comment]
@rashil2000  I understand, things would be better if things were as we wish, like if that post was not 3 years old and had more descriptive text in it would help me to find and understand it.

anyways, I hope what you fixed lately solves the problem and it is all on me misunderstanding older posts.

thanks for the link

**Comment by rashil2000** [comment]
No worries. I was just pointing out that the issue was reported multiple times before - #3816, #4058.
