### ISSUE TITLE
Scoop install/update sbcl 2.1.9 fails

### ISSUE THREAD

**Issue by tensor-programming** [ScoopInstaller/Scoop#4464]
Error I am getting looks like this. 
```
Installing 'sbcl' (2.1.9) [64bit]
Loading sbcl-2.1.9-x86-64-windows-binary.msi from cache.
Checking hash of sbcl-2.1.9-x86-64-windows-binary.msi ... ok.
Extracting sbcl-2.1.9-x86-64-windows-binary.msi ... Exception: C:\users\tensor\scoop\apps\scoop\current\lib\core.ps1:510
Line |
 510 |          throw "Could not find '$(fname $from)'! (error $($proc.ExitCo …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not find '2.1.9'! (error 16)
```

The MSI is in the folder, it just doesn't seem to find it with the powershell script.

**Comment by demcgovern** [comment]
`❯ scoop update sbcl -f
sbcl: 2.1.9 -> 2.1.9
Updating one outdated app:
Updating 'sbcl' (2.1.9 -> 2.1.9)
Downloading new version
Loading sbcl-2.1.9-x86-64-windows-binary.msi from cache
Checking hash of sbcl-2.1.9-x86-64-windows-binary.msi ... ok.
Uninstalling 'sbcl' (2.1.9)
Installing 'sbcl' (2.1.9) [64bit]
Loading sbcl-2.1.9-x86-64-windows-binary.msi from cache
Extracting sbcl-2.1.9-x86-64-windows-binary.msi ... DEBUG[1632843478] $out = -------------------------------------------------------------------------------
   ROBOCOPY     ::     Robust File Copy for Windows
-------------------------------------------------------------------------------

  Started : Tuesday, 28 September, 2021 10:37:58
   Source : C:\Users\dmcgovern\scoop\apps\sbcl\2.1.9\_tmp\SourceDir\PFiles\Steel Bank Common Lisp\2.1.9\
     Dest : C:\Users\dmcgovern\scoop\apps\sbcl\2.1.9\

    Files : *.*

  Options : *.* /S /E /DCOPY:DA /COPY:DAT /MOVE /R:1000000 /W:30

------------------------------------------------------------------------------

2021/09/28 10:37:58 ERROR 2 (0x00000002) Accessing Source Directory C:\Users\dmcgovern\scoop\apps\sbcl\2.1.9\_tmp\SourceDir\PFiles\Steel Bank Common Lisp\2.1.9\
The system cannot find the file specified. -> C:\Users\dmcgovern\scoop\apps\scoop\current\lib\core.ps1:509:9
Exception: C:\Users\dmcgovern\scoop\apps\scoop\current\lib\core.ps1:510
Line |
 510 |          throw "Could not find '$(fname $from)'! (error $($proc.ExitCo …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not find '2.1.9'! (error 16)`

**Comment by rashil2000** [comment]
Not reproducible in latest version
