### ISSUE TITLE
When using NO_JUNCTIONS config, scoop prefix command fails

### ISSUE THREAD

**Issue by dwettstein** [ScoopInstaller/Scoop#4474]
https://github.com/lukesampson/scoop/blob/3d67b7d37c4a2714e8942724d4677dcbd3678f01/libexec/scoop-prefix.ps1#L14

As the version `current` is hardcoded in the `scoop prefix` command, it will just output `ERROR 'git' is not installed` although it is properly installed.

This issue relates #4350, but it's not a duplicate of it.

**Comment by rashil2000** [comment]
Closed in #4722
