### ISSUE TITLE
[Feature Request] scoop info --version <app>

### ISSUE THREAD

**Issue by dwettstein** [ScoopInstaller/Scoop#4475]
Currently the command `scoop info <app>` shows a lot of useful information. However, sometimes it would be useful to have a command to show only the version(s).

Examples:
- `scoop info --version <app>`
- `scoop info --version --latest <app>`

Current workaround:
```
# Git for Windows
scoop info <app> | grep "Version: " | sed 's/Version: //'

# PowerShell
((scoop info <app> | Out-String) -split "`r`n" | Select-String "Version: .*").ToString().Replace("Version: ", "")
```

Relates #3969

**Comment by rashil2000** [comment]
Closed in #4475

**Comment by melMass** [comment]
> Closed in #4475

Thanks!!
I guess you meant #4741 ? I think it should be added to the FAQ https://github.com/ScoopInstaller/Scoop/wiki/FAQ

**Comment by rashil2000** [comment]
Hi yes, sorry for the misquote.

I didn't get you, what should be added in the FAQ?

**Comment by melMass** [comment]
> Hi yes, sorry for the misquote.
> 
> I didn't get you, what should be added in the FAQ?

This part, I guess it could explain the new flag now:
> Please note: running scoop list or scoop info will show the LATEST version installed, not all of them.

**Comment by rashil2000** [comment]
Done, thanks!
