### ISSUE TITLE
Shims for Bash?

### ISSUE THREAD

**Issue by okonomiyaki3000** [ScoopInstaller/Scoop#4486]
When I install vscode, my shims folder gets `code.ps1`, `code.cmd`, and `code`, which are suitable for running from powershell, cmd, and bash. This is great but it seems like VSCode is alone in this. When I install other apps, I get only `xxx.exe`, `xxx.ps1`, and `xxx.shim`. Why this discrepancy? Why is VSCode so special and why don't other apps behave this way?

**Comment by rashil2000** [comment]
Merged in develop branch - #4543
