### ISSUE TITLE
scoop search very slowly

### ISSUE THREAD

**Issue by diklios5768** [ScoopInstaller/Scoop#4491]
Updated scoop few days ago. Now scoop search apps very slowly, not only local but remote, always take long time to finished search, need 10 minutes or longer. I don't know why.

**Comment by niheaven** [comment]
Scoop will try to search apps online, and may you check your network? The infrastructure doesn't change for a long time.

**Comment by Valinor** [comment]
10 minutes is not "normal". Can you try to "_git pull_" manually to see if it's your network, pull, or other things.
How many application do you have?
Did you check you disk? (use tools to monitor usage (network, disk, memory) when you update scoop (see if it's not your antivirus).
Maybe an antivirus update recently?

**Comment by tech189** [comment]
You could also try [scoop-search](https://github.com/shilangyu/scoop-search) - an alternative search program that replaces the slow built-in `scoop search`.

I just tried it out on `scoop search scoop-search` which took 42 seconds with the default search and less than a second using `scoop-search`!

**Comment by Valinor** [comment]
@tech189 : Even 42 seconds seem very long for me : 

![image](https://user-images.githubusercontent.com/2079654/139804631-3c62af9b-5c92-4fd8-a713-514034b7213c.png)

What is your antivirus?

**Comment by zhoujin7** [comment]
https://github.com/zhoujin7/scoop-search/blob/master/scoopSearch.ps1

**Comment by Valinor** [comment]
@zhoujin7 I understand your answer. Thanks to point it and show alternative.

This is not the problem here. It's the same as "I have a bug with windows => Use Linux".
We should understand the root cause. And.... Nobody answer me about antivirus or monitoring data....

**Comment by tech189** [comment]
I'm using the built in Microsoft/Windows Defender, so no custom antivirus and no exceptions on the scoop folder.

**Comment by diklios5768** [comment]
Thanks. But this situation is strange. It is not a problem of network. I checked my network, use scoop to install or update, it done well. Only search has problem. e.g. I search python use `scoop search python`, it will search in local bucket firstly, and this will take exceptionally long time, at least 5 minutes. It will slowly show many results, it may take 10 minutes or longer time to show them all. I have closed Windows Defender, had no antivirus, and used SSD. Although I have many buckets, but just two or three weeks ago still search fast. I don't know if it caused by scoop or some bucket. I had WSL2 and apt also work well.

**Comment by diklios5768** [comment]
> 10 minutes is not "normal". Can you try to "_git pull_" manually to see if it's your network, pull, or other things. How many application do you have? Did you check you disk? (use tools to monitor usage (network, disk, memory) when you update scoop (see if it's not your antivirus). Maybe an antivirus update recently?

Network has no problem and use SDD. It worked well before but recently have problem

**Comment by diklios5768** [comment]
> Thanks. But this situation is strange. It is not a problem of network. I checked my network, use scoop to install or update, it done well. Only search has problem. e.g. I search python use `scoop search python`, it will search in local bucket firstly, and this will take exceptionally long time, at least 5 minutes. It will slowly show many results, it may take 10 minutes or longer time to show them all. I have closed Windows Defender, had no antivirus, and used SSD. Although I have many buckets, but just two or three weeks ago still search fast. I don't know if it caused by scoop or some bucket. I had WSL2 and apt also work well.

use scoop-search:
![image](https://user-images.githubusercontent.com/47837462/140445726-1ddf454e-c09f-4ed4-8113-3e10be219071.png)

use default scoop search command:
![image](https://user-images.githubusercontent.com/47837462/140446052-550dab22-8d12-45a6-8f0e-18961c637a92.png)

**Comment by Valinor** [comment]
O_o 11 minutes ! You are very patient :) 

![image](https://user-images.githubusercontent.com/2079654/140490628-1a5564ff-e0e9-4ae1-86b2-b462de543c05.png)

You have scoopet and user. Try to disable all bucket except main and extras to see the impact.

You can clean some scoop info :
```
scoop cache rm *
scoop cleanup *
scoop checkup
```
and show here the result of scoop checkup.

**Comment by diklios5768** [comment]
My bucket has 16000+ files:
![image](https://user-images.githubusercontent.com/47837462/140593897-3a8c9c37-e049-407c-832a-b42538f6c234.png)

Run `Measure-Command { Get-ChildItem -Path "*.json" -Recurse | Select-String -Pattern 'python' } | Select -ExpandProperty TotalSeconds` in `scoop/buckets`:
![image](https://user-images.githubusercontent.com/47837462/140594244-14067a51-a168-4332-8af7-5cf48a5ea3c5.png)
3 seconds! So fast! Looks good!!!

After run `scoop checkup`:
![image](https://user-images.githubusercontent.com/47837462/140593479-a29323ad-5988-4045-aff9-0c6a0272c3dc.png)

First problem fixed by run `scoop bucket rm 'extras'; scoop bucket add 'extras'`: change nothing
![image](https://user-images.githubusercontent.com/47837462/140593797-2e70a818-2764-47d1-b92d-e6a7a8cff5fe.png)

Then run `sudo Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1`
![image](https://user-images.githubusercontent.com/47837462/140593819-c4476666-08f9-492b-bd6e-af56e82cb296.png)

and change nothing:
![image](https://user-images.githubusercontent.com/47837462/140594169-94ad2cf4-c36b-427c-8bee-dc8e83564a68.png)

At last, I finished all problem and it still change nothing, it still cost 12 minutes.
![image](https://user-images.githubusercontent.com/47837462/140594320-4d6725a1-198e-4652-8929-9c89c20a3df6.png)

I clear all commands in PowerShell $profile, change nothing.

Then I use cmd.exe to run `scoop search python`, It run faster. It finished before fixed all scoop checkup problems and clear all commands in PowerShell $profile. But still cost about 5mintues.

And my SSD and system runs well when run `scoop search python`:
![image](https://user-images.githubusercontent.com/47837462/140594339-ddb738f9-c68c-4d27-b892-c6765c3ea2b2.png)

Now I doubt it caused by Ash258 scoop-core, it searches many contents and give more results.
![image](https://user-images.githubusercontent.com/47837462/140594060-205b0bca-775b-409b-9038-c4cc0f887789.png)

But why not happen weeks ago. I can't remember if I add some large buckets. So, I'm not sure again.
。゜゜(´Ｏ`) ゜゜。

**Comment by diklios5768** [comment]
After disable all buckets but main, extras and nonportable:
Now it has 3000+ files:
![image](https://user-images.githubusercontent.com/47837462/140595005-7dd6ac32-1f5a-40ef-9103-249701015b88.png)

Run `scoop search python`:
![image](https://user-images.githubusercontent.com/47837462/140594924-06fec25d-27b2-4023-aabf-7c9c6da92251.png)

Use scoop-search:
![image](https://user-images.githubusercontent.com/47837462/140594988-873f159f-d660-4ee1-a418-8d96111e7686.png)

**Comment by diklios5768** [comment]
After disable all buckets but main, extras and nonportable:
Now it has 3000+ files:
![image](https://user-images.githubusercontent.com/47837462/140595028-5abe6a21-e2fe-455e-8465-7a1d2ca188ce.png)

Run scoop search python:
![image](https://user-images.githubusercontent.com/47837462/140595083-e52a8318-4a4b-4246-8069-5e5f26c18b23.png)

Use scoop-search:
![image](https://user-images.githubusercontent.com/47837462/140595112-88b3adc9-48e6-44cb-9843-3bcab013eb9c.png)

**Comment by xianzheTM** [comment]
I just use "Base" & "main" bucket.And I searched anaconda for 20 seconds.
Then I added the bucket of apps, which is an aggregate bucket, and it is relatively large.
I searched again. It took three minutes this time.

**Comment by diklios5768** [comment]
At last use `scoop-search` tool to replace `scoop search`.
Still don't know why search so slowly.

**Comment by adamency** [comment]
This is really not a motive for closing "as completed".... No package manager has ever officially told its users to use a 3rd party software to search its own repositories. You should keep this issue open until scoop-search is integrated in scoop or `scoop search` is fixed.

**Comment by Michaelzhouisnotwhite** [comment]
I have the same problem...

**Comment by tech189** [comment]
@adamency It's okay to keep this closed as we already have an issue for tracking this: https://github.com/ScoopInstaller/Scoop/issues/4239. Please follow that one instead.

**Comment by adamency** [comment]
Alright, thanks for the link.

**Comment by sebma** [comment]
Hi, It takes ~27s on my system : 

```powershell
PS C:\> ( Measure-Command { scoop search pstube | Out-Host } ).TotalSeconds
WARN  No matches found.
26.7692606
PS C:\>
```
How can I make it faster ?

**Comment by sebma** [comment]
After a : 
```powershell
scoop cache rm *
scoop cleanup *
```
It takes ~26 seconds : 
```powershell
PS C:\> ( Measure-Command { scoop search pstube | Out-Host } ).TotalSeconds
WARN  No matches found.
25.6554159
PS C:\>
```

**Comment by RayyanNafees** [comment]
> My bucket has 16000+ files: ![image](https://user-images.githubusercontent.com/47837462/140593897-3a8c9c37-e049-407c-832a-b42538f6c234.png)
> 
> Run `Measure-Command { Get-ChildItem -Path "*.json" -Recurse | Select-String -Pattern 'python' } | Select -ExpandProperty TotalSeconds` in `scoop/buckets`: ![image](https://user-images.githubusercontent.com/47837462/140594244-14067a51-a168-4332-8af7-5cf48a5ea3c5.png) 3 seconds! So fast! Looks good!!!
> 
> After run `scoop checkup`: ![image](https://user-images.githubusercontent.com/47837462/140593479-a29323ad-5988-4045-aff9-0c6a0272c3dc.png)
> 
> First problem fixed by run `scoop bucket rm 'extras'; scoop bucket add 'extras'`: change nothing ![image](https://user-images.githubusercontent.com/47837462/140593797-2e70a818-2764-47d1-b92d-e6a7a8cff5fe.png)
> 
> Then run `sudo Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1` ![image](https://user-images.githubusercontent.com/47837462/140593819-c4476666-08f9-492b-bd6e-af56e82cb296.png)
> 
> and change nothing: ![image](https://user-images.githubusercontent.com/47837462/140594169-94ad2cf4-c36b-427c-8bee-dc8e83564a68.png)
> 
> At last, I finished all problem and it still change nothing, it still cost 12 minutes. ![image](https://user-images.githubusercontent.com/47837462/140594320-4d6725a1-198e-4652-8929-9c89c20a3df6.png)
> 
> I clear all commands in PowerShell $profile, change nothing.
> 
> Then I use cmd.exe to run `scoop search python`, It run faster. It finished before fixed all scoop checkup problems and clear all commands in PowerShell $profile. But still cost about 5mintues.
> 
> And my SSD and system runs well when run `scoop search python`: ![image](https://user-images.githubusercontent.com/47837462/140594339-ddb738f9-c68c-4d27-b892-c6765c3ea2b2.png)
> 
> Now I doubt it caused by Ash258 scoop-core, it searches many contents and give more results. ![image](https://user-images.githubusercontent.com/47837462/140594060-205b0bca-775b-409b-9038-c4cc0f887789.png)
> 
> But why not happen weeks ago. I can't remember if I add some large buckets. So, I'm not sure again. 。゜゜(´Ｏ`) ゜゜。

Please send your terminal wallpaper to nafees.rayyan@gmail.com I love it

**Comment by tadghh** [comment]
Installing aria2 solves this 
```
scoop install aria2;
scoop config aria2-warning-enabled false
```

**Comment by sebma** [comment]
@tadghh After installing `aria2`, the search takes 17s.

**Comment by tadghh** [comment]
@sebma 

Change some of the config ops

https://github.com/ScoopInstaller/Scoop?tab=readme-ov-file#multi-connection-downloads-with-aria2

**Comment by sebma** [comment]
@tadghh It now takes 16s

My guess is that maybe my connection is crap.

**Comment by tadghh** [comment]
@sebma yup no clue. Its currently faster to use the scoop.sh site to look for packages. Needing to open the browser and search + navigate to a whole page just to look for a package is so clunky.

**Comment by mpathy** [comment]
Just an information, there is an option to use SQLite with scoop.

You activate it with:
`scoop config useSQLite true`

This speeds up the process quite a lot.

**Comment by sebma** [comment]
> Just an information, there is an option to use a SQLite database with scoop.
> 
> You activate it with: `scoop config use_sqlite_cache true`
> 
> This speeds up the process quite a lot. It's almost instant on most PCs.
> 
> Don't know why they dont activate it per default.

@mpathy Thanks a lot, now the results come in less than 1s (instead of 16s previously) 👍 

BTW : How can I refresh the SQLite cache when I need to ? : 
```powershell
PS C:\> scoop info notepadnext | % Version
0.12
PS C:\> time { scoop search notepadnext | % Version }
Results from local buckets...
0.11
00:00:00.3982168
PS C:\>
```

**Comment by cworld1** [comment]
@leaumar Appreciate for your opinion. I tried to add the scoop path to the `Exclude path` of the Windows Security, it works, and finished the search within 3 seconds. The navigation is:

- (Open the Windows Security)
- [Nav] Virus & threat protection
- [Section] Virus & threat protection settings
- [Button] Manage settings
- [Section] Exclusions
- [Button] Add or remove exclusions

Then you can manage the path as you want. Hope this can help others who are in trouble! ❤️

**Comment by mpathy** [comment]
> BTW : How can I refresh the SQLite cache when I need to ? :

Oh, you are correct.
I was so happy about the speedup that I didnt check this.

But the update process picks the correct version! 
So, most likely, the cache is up to date, but the database has the version number as a string in the search database, it uses lexicographical sorting / dictonary order when it tries to pick the right line. But thats just a guess. 
It is not used for installing though, the sqlite cache is just some kind of search engine addon for scoop. 

If it bothers you, you can reference my assumption in a bug report, but I am too busy to post one myself. Maybe they could just go by timestamp instead of sorting the version number field.
