### ISSUE TITLE
How can I go back to original REPO https://github.com/lukesampson/scoop

### ISSUE THREAD

**Issue by phpcitizen** [ScoopInstaller/Scoop#4495]
I changed the repo to another one, and now I want to go back to https://github.com/lukesampson/scoop

What I did:
`scoop config SCOOP_REPO https://github.com/lukesampson/scoop`
`scoop config SCOOP_BRANCH master`
`scoop update`

> Updating Scoop...
WARN  Master branch should not be used anymore. Migrating to 'main'
Your configuration specifies to merge with the ref 'refs/heads/main'
from the remote, but no such ref was fetched.
ERROR Update failed.

What can I do to restore?

Thanks

**Comment by phpcitizen** [comment]
Seems like just cloning the original repository to c:\Users\<user>\scoop\apps\scoop\current solves the problem.

**Comment by phpcitizen** [comment]
It makes the installed apps vanished. Which file hold the data for installed apps?

**Comment by pratikpc** [comment]
> I changed the repo to another one

@phpcitizen which one?

**Comment by phpcitizen** [comment]
Shovel. I had to reinstall all apps to restore.

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Extras/issues/7204#issuecomment-958022511

**Comment by phpcitizen** [comment]
This should be documented in install for new users.

**Comment by rashil2000** [comment]
Why?

This is something that should be documented in _that fork's own documentation_. 

The Scoop upstream is not responsible for any incompatibilities that arise as a result of people using random forks.

**Comment by phpcitizen** [comment]
Yes, but it is your responsibility to protect your users, seems like happening very often until you realize what's really happening. Both side should inform users, sand shovel should inform how to uninstall properly.

This is unethical just because you have a feud between.

**Comment by rashil2000** [comment]
What feud are you talking about?

This is a community project: please refrain from making stupid accusations.

What I said is standard practice. What opensource project have you seen that takes responsibilities for any and all random modifications that a user does to their software? Show me one example.

**Comment by phpcitizen** [comment]
If you see something like this:
https://rasa.github.io/scoop-directory/by-score.html

Someone new might think this is like an upgrade... and go for it after installing a lot of applications.

Thanks for accusing me being stupid, I just will ignore it and think it is just because your age.

**Comment by chawyehsu** [comment]
@phpcitizen I assume you don't know how Open Source work. **There is NO RESPONSIBILITY for the maintainers to PROTECT users that choose random forks.** And it's unfair and so impolite of blaming maintainers with the word of *unethical*.

The license has documented:

```
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.
```

Thanks to all participants in #4456, the project and the team are re-active, we all want to make the project to be better, willing to help our users to solve problems, and make a better community. But this requires kind words and friendly talks from all of us, instead of accusing or attacking.

**Comment by rashil2000** [comment]
@phpcitizen You still haven't mentioned what feud you thought was happening here, but never mind, I just will ignore it and think it is just because your age.

> If you see something like this: https://github.com/Ash258/Scoop-Core https://github.com/Ash258/Shovel-Ash258 https://rasa.github.io/scoop-directory/by-score.html
> 
> Someone new might think this is like an upgrade... and go for it after installing a lot of applications.

Not denying that. However, once you move away from the upstream, there's no coming back. If a new user finds the fork more interesting, then it's a fair assumption that they will report any issues they find, in that fork itself.

Thanks for chiming in @chawyehsu, I was about to quote the licensing terms myself, but you stated them much better.

**Comment by phpcitizen** [comment]
I will not link the feud talks here, this is clearly what you want from me... none of my business.

OK, I understand of course it is not your responsibility per se, but it might have been common sense to inform this obvious your own words "Not denying that." part and save a lot of important time of other people, rather than being stubborn and not willing to see the obvious.

This all is subject to the other project/fork too.

**Comment by pratikpc** [comment]
Then that is a decision which is up to you. We here try our best as unpaid volunteers to update and maintain packages, manifests and update Scoop scripts themselves. The only third party components we list ever are buckets, but those are not full replacements for Scoop itself.

To protect from issues like this, @Ash258 for example always makes it clear we aren't even supposed to mention Shovel here. Shovel, while being based on Scoop has taken different design decisions in quite a few cases. As a whole, this is an issue which should be discussed on the Shovel repo. Scoop is not at fault here.

**Comment by dwettstein** [comment]
Just for documentation purpose, to fix all the installed apps after reverting to original `SCOOP_REPO` value, you need to rename the following files in every folder within `apps`:
- `scoop-install.json` to `install.json`
- `scoop-manifest.json` to `manifest.json`

This is needed as Shovel has migrated these files previously (see https://github.com/Ash258/Scoop-Core/issues/18).

BTW, maybe we want to consider this migration as well sometime, as the `scoop-` prefix clearly distinguish the Scoop files from the app's files.

**Comment by JanPokorny** [comment]
@phpcitizen I'm actually interested to know what controversy are you talking about. I don't really follow Scoop's communication channels, I only know that for some period of time the core wasn't very well maintained and Ash258's version fixed some upstream bugs. Also apparently he's a mod of the "official Scoop Discord", where he banned discussing Shovel? Apart from that, I know pretty much nothing about Shovel's author and his relation to Scoop maintainers. Oh, and there's also a completely unrelated tool with a different author to search Scoop packages, also called Shovel.

So if you (or anyone else?) know something more about the politics here, I'm keen to hear. I don't particularly thrive in internet drama, I just want to feel more in the loop on what's happening around one of my favorite opensource projects.

(Yeah and sorry for hijacking the issue 😶)

**Comment by leni8ec** [comment]
@dwettstein thanks for your solution!

Based on [your code](https://github.com/ScoopInstaller/Scoop/issues/4495#issuecomment-992876959), solution for **PowerShell 7+**.


## Migrate from [Shovel](https://github.com/Ash258/Shovel-Ash258) (Ash258) to [Scoop](https://github.com/ScoopInstaller/Scoop) (original)
> Solution for PowerShell 7+
### 1. Replace the scoop app itself
```
# revert repo in config
scoop config SCOOP_REPO https://github.com/lukesampson/scoop
scoop config SCOOP_BRANCH master

# replace scoop itself
rm -r -force "$Env:SCOOP/apps/scoop/current"
git clone https://github.com/lukesampson/scoop "$Env:SCOOP/apps/scoop/current"

# update scoop
scoop update
```
### 2. Fix all installed apps
> Rename 'scoop-install.json' and 'scoop-manifest.json' to 'install.json' and 'manifest.json'
```
# local apps
dir -path "$Env:SCOOP/apps/" -s -in "scoop-install.json" | ren -n { $_.Name.replace("scoop-","") }
dir -path "$Env:SCOOP/apps/" -s -in "scoop-manifest.json" | ren -n { $_.Name.replace("scoop-","") }
# global apps
dir -path "$Env:SCOOP_GLOBAL/apps/" -s -in "scoop-install.json" | ren -n { $_.Name.replace("scoop-","") }
dir -path "$Env:SCOOP_GLOBAL/apps/" -s -in "scoop-manifest.json" | ren -n { $_.Name.replace("scoop-","") }
```

### 3. Revert autocompletion module (in 'shovel' it was a built-in)

**3.1. _Manually_ remove the old entry from $profile:**
> Import-Module 'C:\Scoop\apps\scoop\current\supporting\completion\Scoop-Completion.psd1'
```
# open profile and manually remove the next entry:
# Import-Module 'C:\Scoop\apps\scoop\current\supporting\completion\Scoop-Completion.psd1'

ii $Profile
```

**3.2 Add scoop auto-completion module by [Moeologist](https://github.com/Moeologist/scoop-completion) (from bucket '[extras](https://github.com/ScoopInstaller/Extras)')**
```
scoop install scoop-completion
Add-Content -Path $Profile -Value "`nImport-Module $env:SCOOP\modules\scoop-completion"
```

**Comment by ahmedmoselhi** [comment]
```
scoop update
Updating Scoop...
fatal: detected dubious ownership in repository at 'C:/Users/Admin/scoop/apps/scoop/current'
'C:/Users/Admin/scoop/apps/scoop/current' is owned by:
        BUILTIN/Administrators (S-1-5-32-544)
but the current user is:
        AHMED-EBRAHIM2/ahmed (S-1-5-21-4218969372-1645167379-354272111-1000)
To add an exception for this directory, call:

        git config --global --add safe.directory C:/Users/Admin/scoop/apps/scoop/current
fatal: detected dubious ownership in repository at 'C:/Users/Admin/scoop/apps/scoop/current'
'C:/Users/Admin/scoop/apps/scoop/current' is owned by:
        BUILTIN/Administrators (S-1-5-32-544)
but the current user is:
        AHMED-EBRAHIM2/ahmed (S-1-5-21-4218969372-1645167379-354272111-1000)
To add an exception for this directory, call:

        git config --global --add safe.directory C:/Users/Admin/scoop/apps/scoop/current
warning: Not a git repository. Use --no-index to compare two paths outside a working tree
usage: git diff --no-index [<options>] <path> <path>

Diff output format options
    -p, --patch           generate patch
    -s, --no-patch        suppress diff output
    -u                    generate patch
    -U, --unified[=<n>]   generate diffs with <n> lines context
    -W, --[no-]function-context
                          generate diffs with <n> lines context
    --raw                 generate the diff in raw format
    --patch-with-raw      synonym for '-p --raw'
    --patch-with-stat     synonym for '-p --stat'
    --numstat             machine friendly --stat
    --shortstat           output only the last line of --stat
    -X, --dirstat[=<param1>,<param2>...]
                          output the distribution of relative amount of changes for each sub-directory
    --cumulative          synonym for --dirstat=cumulative
    --dirstat-by-file[=<param1>,<param2>...]
                          synonym for --dirstat=files,<param1>,<param2>...
    --check               warn if changes introduce conflict markers or whitespace errors
    --summary             condensed summary such as creations, renames and mode changes
    --name-only           show only names of changed files
    --name-status         show only names and status of changed files
    --stat[=<width>[,<name-width>[,<count>]]]
                          generate diffstat
    --stat-width <width>  generate diffstat with a given width
    --stat-name-width <width>
                          generate diffstat with a given name width
    --stat-graph-width <width>
                          generate diffstat with a given graph width
    --stat-count <count>  generate diffstat with limited lines
    --[no-]compact-summary
                          generate compact summary in diffstat
    --binary              output a binary diff that can be applied
    --[no-]full-index     show full pre- and post-image object names on the "index" lines
    --[no-]color[=<when>] show colored diff
    --ws-error-highlight <kind>
                          highlight whitespace errors in the 'context', 'old' or 'new' lines in the diff
    -z                    do not munge pathnames and use NULs as output field terminators in --raw or --numstat
    --[no-]abbrev[=<n>]   use <n> digits to display object names
    --src-prefix <prefix> show the given source prefix instead of "a/"
    --dst-prefix <prefix> show the given destination prefix instead of "b/"
    --line-prefix <prefix>
                          prepend an additional prefix to every line of output
    --no-prefix           do not show any source or destination prefix
    --default-prefix      use default prefixes a/ and b/
    --inter-hunk-context <n>
                          show context between diff hunks up to the specified number of lines
    --output-indicator-new <char>
                          specify the character to indicate a new line instead of '+'
    --output-indicator-old <char>
                          specify the character to indicate an old line instead of '-'
    --output-indicator-context <char>
                          specify the character to indicate a context instead of ' '

Diff rename options
    -B, --break-rewrites[=<n>[/<m>]]
                          break complete rewrite changes into pairs of delete and create
    -M, --find-renames[=<n>]
                          detect renames
    -D, --irreversible-delete
                          omit the preimage for deletes
    -C, --find-copies[=<n>]
                          detect copies
    --[no-]find-copies-harder
                          use unmodified files as source to find copies
    --no-renames          disable rename detection
    --[no-]rename-empty   use empty blobs as rename source
    --[no-]follow         continue listing the history of a file beyond renames
    -l <n>                prevent rename/copy detection if the number of rename/copy targets exceeds given limit

Diff algorithm options
    --minimal             produce the smallest possible diff
    -w, --ignore-all-space
                          ignore whitespace when comparing lines
    -b, --ignore-space-change
                          ignore changes in amount of whitespace
    --ignore-space-at-eol ignore changes in whitespace at EOL
    --ignore-cr-at-eol    ignore carrier-return at the end of line
    --ignore-blank-lines  ignore changes whose lines are all blank
    -I, --[no-]ignore-matching-lines <regex>
                          ignore changes whose all lines match <regex>
    --[no-]indent-heuristic
                          heuristic to shift diff hunk boundaries for easy reading
    --patience            generate diff using the "patience diff" algorithm
    --histogram           generate diff using the "histogram diff" algorithm
    --diff-algorithm <algorithm>
                          choose a diff algorithm
    --anchored <text>     generate diff using the "anchored diff" algorithm
    --word-diff[=<mode>]  show word diff, using <mode> to delimit changed words
    --word-diff-regex <regex>
                          use <regex> to decide what a word is
    --color-words[=<regex>]
                          equivalent to --word-diff=color --word-diff-regex=<regex>
    --[no-]color-moved[=<mode>]
                          moved lines of code are colored differently
    --[no-]color-moved-ws <mode>
                          how white spaces are ignored in --color-moved

Other diff options
    --[no-]relative[=<prefix>]
                          when run from subdir, exclude changes outside and show relative paths
    -a, --[no-]text       treat all files as text
    -R                    swap two inputs, reverse the diff
    --[no-]exit-code      exit with 1 if there were differences, 0 otherwise
    --[no-]quiet          disable all output of the program
    --[no-]ext-diff       allow an external diff helper to be executed
    --[no-]textconv       run external text conversion filters when comparing binary files
    --ignore-submodules[=<when>]
                          ignore changes to submodules in the diff generation
    --submodule[=<format>]
                          specify how differences in submodules are shown
    --ita-invisible-in-index
                          hide 'git add -N' entries from the index
    --ita-visible-in-index
                          treat 'git add -N' entries as real in the index
    -S <string>           look for differences that change the number of occurrences of the specified string
    -G <regex>            look for differences that change the number of occurrences of the specified regex
    --pickaxe-all         show all changes in the changeset with -S or -G
    --pickaxe-regex       treat <string> in -S as extended POSIX regular expression
    -O <file>             control the order in which files appear in the output
    --rotate-to <path>    show the change in the specified path first
    --skip-to <path>      skip the output to the specified path
    --find-object <object-id>
                          look for differences that change the number of occurrences of the specified object
    --diff-filter [(A|C|D|M|R|T|U|X|B)...[*]]
                          select files by diff type
    --output <file>       output to a specific file

fatal: not in a git directory
fatal: not in a git directory
fatal: detected dubious ownership in repository at 'C:/Users/Admin/scoop/apps/scoop/current'
'C:/Users/Admin/scoop/apps/scoop/current' is owned by:
        BUILTIN/Administrators (S-1-5-32-544)
but the current user is:
        AHMED-EBRAHIM2/ahmed (S-1-5-21-4218969372-1645167379-354272111-1000)
To add an exception for this directory, call:

        git config --global --add safe.directory C:/Users/Admin/scoop/apps/scoop/current
fatal: detected dubious ownership in repository at 'C:/Users/Admin/scoop/apps/scoop/current'
'C:/Users/Admin/scoop/apps/scoop/current' is owned by:
        BUILTIN/Administrators (S-1-5-32-544)
but the current user is:
        AHMED-EBRAHIM2/ahmed (S-1-5-21-4218969372-1645167379-354272111-1000)
To add an exception for this directory, call:

        git config --global --add safe.directory C:/Users/Admin/scoop/apps/scoop/current
fatal: detected dubious ownership in repository at 'C:/Users/Admin/scoop/apps/scoop/current'
'C:/Users/Admin/scoop/apps/scoop/current' is owned by:
        BUILTIN/Administrators (S-1-5-32-544)
but the current user is:
        AHMED-EBRAHIM2/ahmed (S-1-5-21-4218969372-1645167379-354272111-1000)
To add an exception for this directory, call:

        git config --global --add safe.directory C:/Users/Admin/scoop/apps/scoop/current
Invoke-GitLog: C:\Users\Admin\scoop\apps\scoop\current\libexec\scoop-update.ps1:143
Line |
 143 |  …           Invoke-GitLog -Path $currentdir -CommitHash $previousCommit
     |                                                          ~~~~~~~~~~~~~~~
     | Cannot bind argument to parameter 'CommitHash' because it is an empty string.
Update failed.

```

**Comment by HUMORCE** [comment]
@ahmedmoselhi Search 'Failed to update Scoop Core or Buckets caused by damaged/conflicted git repo' on #6378 It applies to the situation as well.
