### ISSUE TITLE
Making it possible to store Scoop config in the root directory for increased portability.

### ISSUE THREAD

**Issue by pratikpc** [ScoopInstaller/Scoop#4498]
Current behaviour is to save at ~/.config/scoop/config.json.

Could we add an optional behaviour that if a user creates a config.json file in the root directory, then Scoop would prioritise that over the Scoop present in ~/.config/scoop/config.json.

If absent, ~/.config/scoop/config.json is used by default.

This would probably make Scoop a bit more portable and for most users would make it possible to copy paste Scoop from one directory to another or one system to another or one user to another without facing major issues.

**Comment by hgkamath** [comment]
How about a ```SCOOP_CONFIG_DIR``` environment variable pointing to wherever ```.../scoop``` folder containing ```config.json```
and if the environment variable does not exist then fall back to the hard-coded dir.

**Comment by hgkamath** [comment]
Scoop windows start-menu shortcuts may also require recreation/resyncingfor increased portability #4562
