### ISSUE TITLE
Why scoop list command can't be filtered by findstr or Select-String command?

### ISSUE THREAD

**Issue by diklios5768** [ScoopInstaller/Scoop#4503]
Code in `scoop-list.ps1` use `Write-Host` command. It can't use pipe command.
Why not use `Write-Output`？
Because scoop install too many apps, it's annoying that it can't filter app which I want to confirm if it is installed.

**Comment by rashil2000** [comment]
#4030

**Comment by diklios5768** [comment]
> #4030

Strange Close. It can't help. The core problem is not why can't use pipeline but is how to filter apps installed.

`scoop export` also can't use findstr or Select-String command.

**Comment by diklios5768** [comment]
> #4030

Strange Close. It can't help. The core problem is not why can't use pipeline but is how to filter apps installed.

`scoop export` also can't use findstr or Select-String command.

**Comment by diklios5768** [comment]
> #4030

Strange Close. It can't help. The core problem is not why can't use pipeline but is how to filter apps installed.

`scoop export` also can't use findstr or Select-String command.

**Comment by diklios5768** [comment]
> #4030

Strange Close. It can't help. The core problem is not why can't use pipeline but is how to filter apps installed.

`scoop export` also can't use findstr or Select-String command.

**Comment by rashil2000** [comment]
The reason why Write-Output is not used is explained in the linked issue.

**Comment by diklios5768** [comment]
> The reason why Write-Output is not used is explained in the linked issue.

I know why Write-Output is not used.
The core problem is how to filter apps installed.

**Comment by rashil2000** [comment]
`scoop list 6>&1`

See #4437

**Comment by diklios5768** [comment]
Okay, thanks. Finally I know how to filter.
Use `scoop export` or `scoop list 6>&1` command with one of these pipelines (e.g. find python):
* ` | findstr 'python'`
* ` | Select-String 'python'`
* if installed `grep`:` | grep 'python'`
* if installed `ripgrep`:` | rg 'python'`

**Comment by diklios5768** [comment]
Because of pay no attention to the office prompt message, I ignore the official API.
It can be seen use command: `scoop help list`, or `scoop list --help`
![image](https://user-images.githubusercontent.com/47837462/140912063-57e32f6b-1ffb-4291-af9e-51c6f46c5868.png)

So, the easiest way to find install apps is use command (e.g., search python) `scoop list python`.
The `6>` can also be used to output file. e.g., `scoop list python 6> scoop.txt`
