### ISSUE TITLE
Move common .github files to .github repo

### ISSUE THREAD

**Issue by rasa** [ScoopInstaller/Scoop#4507]
Per https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file

**Comment by rasa** [comment]
We can move shared workflows, too. See https://github.com/pages-themes/.github/tree/master/.github

**Comment by rasa** [comment]
See 
https://github.com/ScoopInstaller/Main/pull/2889/ and 
https://github.com/ScoopInstaller/Extras/pull/7248

**Comment by rasa** [comment]
I started to work on this, but now realize that Main's .github files are different than Extras' files, so this may not work. 

Perhaps .github's are used, unless Main has the same named file, in which case, it's used instead?

**Comment by rashil2000** [comment]
> Perhaps .github's are used, unless Main has the same named file, in which case, it's used instead?

Yes, if a repo has it's own file with the same name/path, it will override the .github repo's files.
