### ISSUE TITLE
Is there a way to port my scoop from current to new machine?

### ISSUE THREAD

**Issue by Rafeqm** [ScoopInstaller/Scoop#4508]
I just discover scoop a few days ago, and already installed yesterday. So as of now, I installed `curl`, `python3.10`, `sudo`, and `oh-my-posh`. The problem is: my dad is gonna buy me **_a new laptop_** next week (currently I use my mom's laptop) and I already configured scoop in `C:\Users\myTempName\scoop`. So say I've already get my new laptop, can I just move my scoop folder to my new laptop at `C:\Users\myNewUserName\scoop` and add `\scoop\shims` to **PATH**? Or are there several other steps I must do?

**_NOTE_**: **_I don't have unlimited data plan/bandwidth_**, So I don't want to redownload/reinstall everything except `scoop` itself if needed.

**Comment by rashil2000** [comment]
Do this:
1. Reinstall scoop on new laptop
2. Copy everything from `C:\Users\myTempName\scoop\cache\` to `C:\Users\myNewUserName\scoop\cache\`
3. Install your 4 apps. Since everything is in cache, Scoop will not download anything new.

**Comment by Rafeqm** [comment]
If I've already installed some python packages like `black`, `flake8`, and `isort`. Should I copy the full `~\scoop` instead of just `~\scoop\cache`?

**Comment by rashil2000** [comment]
Copying the entire folder might cause unknown problems. You can try it, but be warned.

The method I told is error-free.

**Comment by niheaven** [comment]
1. Copy entire scoop dir. (e.g., new dir is `D:\Scoop`)
2. Add `$env:SCOOP` to point to your new location (`$env:SCOOP` is `D:\Scoop`)
3. Add `D:\Scoop\shims` to `$env:PATH` and make sure it is before WindowsApps's
4. Restart your terminal to reload Environment Variables
5. `scoop reset *`
6. All done.

**Comment by pratikpc** [comment]
Depending on the app, sometimes simple copy paste can also work

**Comment by rashil2000** [comment]
@Rafeqm is your problem solved?

**Comment by AntonOks** [comment]
> Do this:
> 
>     1. Reinstall scoop on new laptop
> 
>     2. Copy everything from `C:\Users\myTempName\scoop\cache\` to `C:\Users\myNewUserName\scoop\cache\`
> 
>     3. Install your 4 apps. Since everything is in cache, Scoop will not download anything new.

Hmmm... shouldn't one also copy ​```C:\Users\<user>\scoop\persist``` then to make sure the previous setting / configs of his app's are also taken over?

**Comment by rashil2000** [comment]
Persist can contain files with hardcoded paths (created by packages themselves), so I'm not sure. It depends on the installed apps.

**Comment by niheaven** [comment]
Just `scoop reset *`, it will persist everything again and let them work.

**Comment by Rafeqm** [comment]
I got my new laptop now. But after `scoop reset *`, scoop throws errors with:
```py
ERROR 'starship ()' isn't installed
ERROR 'sudo ()' isn't installed
ERROR 'Ubuntu-NF ()' isn't installed
ERROR 'UbuntuMono-NF ()' isn't installed
ERROR 'vscode ()' isn't installed
ERROR 'yarn ()' isn't installed
```

What is the reason @niheaven ?

**Comment by niheaven** [comment]
Does your `starship` dir contains `current` and a versioned subdir?

**Comment by Rafeqm** [comment]
Yes. I just copy the entire scoop folder which contains all apps I installed to my new laptop. So everything is just the same as before and actually there are more apps I installed.

**Comment by niheaven** [comment]
It's strange. Okay, let's check it step by step.

- What's the output of `scoop status`?
- If your cache folder is there, you could install these apps without fresh downloading, so could you try `scoop install yarn`?
