### ISSUE TITLE
Clear criteria for main bucket

### ISSUE THREAD

**Issue by deevus** [ScoopInstaller/Scoop#451]
As mentioned in lukesampson/scoop-extras#112 ragel was added to extras since phantomjs and latex were already here. 

I thought this might be a good chance to reconsider any apps that could be better off in the main bucket, but I think we first need to be clear about what the criteria for the main bucket is.

Here's what I gather apps need to be:
- Open source (and have a license)
- Command line (not mutually exclusive)
- Portable (no installer required)
- No registry (generally no exceptions)

Anything I missed?

**Comment by lukesampson** [comment]
Stable versions only

**Comment by deevus** [comment]
@lukesampson You mentioned loosening up on the criteria for the main bucket. Should we update the documentation?

**Comment by lukesampson** [comment]
Yes—I'm just not sure where the documentation is that you're referring to.

These are the latest requirements that I used in the [scoop-extras README](https://github.com/lukesampson/scoop-extras):

1. a reasonably well-known and widely used developer tool
1. the latest stable version of the program
1. a fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

I think that is relaxed enough.

Requirement 1 is a bit of a judgement call. I just don't think we should include stuff you whipped up on the weekend and you're still trying to find an audience for.

Requirement 3 kind of implies that portable installs are desirable. We have to allow for Python which only distribute an installer.

**Comment by deevus** [comment]
I can perhaps go in scoop under a contributions section of the wiki, or in
the README

**Comment by ShanConn** [comment]
I was browsing the winget repo and yep, msft is still as awful as always.

**Comment by EqualDust** [comment]
love scoop, and msft even with a fairly standard install of calibre portable manages to get the install/uninstall borked. Gotta love that we as a community manage to ship better tools than msft paid professionals. https://github.com/microsoft/winget-cli/issues/1750
