### ISSUE TITLE
Scoop appreciation thread

### ISSUE THREAD

**Issue by keenbowl3009** [ScoopInstaller/Scoop#4516]
Hello community, 

I would like to know about ways in which we can support the scoop community and their efforts. 

We're seeing aggressive marketing of winget by microsoft, and as we all know, winget has absolutely no philosophy. 

I would like to know what is the philosophy of scoop, and how much in agreement with it the scoop community stands!

Here is a problem that shows the lack of philosophy: 

https://github.com/microsoft/winget-cli/issues/1711

The same lack of philosophy does not occur with scoop packages because they are as easy to get rid of than they are of installing!

**Comment by keenbowl3009** [comment]
Another huge problem of winget's lack of philosophy and microsoft's inferior implementation of products, is that to this day, a feature that is marked as fixed, is still broken, which is the ability to uninstall software from a windows system. 

https://github.com/microsoft/winget-cli/issues/121

**Comment by tajetaje** [comment]
If you want to have a discussion make a discussion (big button at the top if the screen). 
Issues are for bugs, feature requests, etc.

**Comment by JanPokorny** [comment]
Scoop is made for unzipping CLI tools -- ideal for Git, Python, ffmpeg...
WinGet is made for running installers -- ideal for Steam, IDEs, browsers...

For ideal workflow, it is beneficial to use both.

**Comment by keenbowl3009** [comment]
"WinGet is made for running installers -- ideal for Steam, IDEs, browsers"

That is a fantastic description. Emphasis on running installers - winget will not allow you to properly uninstall most things that you have acquired with it.

**Comment by JanPokorny** [comment]
@keenbowl3009 Not my experience at all. If the installer properly registers an uninstaller, winget will run it.
