### ISSUE TITLE
Couldn't find manifest for 'aws-federator'.

### ISSUE THREAD

**Issue by nwandyji** [ScoopInstaller/Scoop#4519]
When I type command:  scoop install 'aws-federator'  It shows error:

Couldn't find manifest for 'aws-federator'.

**Comment by rashil2000** [comment]
This package does not exist on Scoop. You can search similar packages [here](https://rasa.github.io/scoop-directory/search) or make a request [here](https://github.com/ScoopInstaller/Main).
