### ISSUE TITLE
Please do add support for management of MSIX.

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [ScoopInstaller/Scoop#4520]
Please do observe "http://github.com/yereverluvinunclebert/Rocketdock-Enhanced-Settings-VB6/issues/1" for the reason that support for "MSIX" shall be beneficial for "http://github.com/ScoopInstaller/Scoop".

Please do observe "http://github.com/ScoopInstaller/Scoop/discussions/4518#discussioncomment-1652950" for demonstration of lack of support for "MSIX" currently by "http://github.com/ScoopInstaller/Scoop".

**Comment by pratikpc** [comment]
Could you help create a PR for the same?

**Comment by RokeJulianLockhart** [comment]
@pratikpc, no. I'm not sufficiently competent at writing PowerShell, yet. I apologize.

**Comment by niheaven** [comment]
Most of msix or msixbundle are zip file and can be extracted by 7z, but I wonder are there some special cases.

**Comment by rashil2000** [comment]
So this can be closed? MSIX is already supported as in your PR - https://github.com/ScoopInstaller/Extras/pull/7631

**Comment by rasa** [comment]
> So this can be closed? MSIX is already supported as in your PR - [ScoopInstaller/Extras#7631](https://github.com/ScoopInstaller/Extras/pull/7631)

Seems like it.

**Comment by rashil2000** [comment]
Another example https://github.com/ScoopInstaller/Extras/blob/master/bucket/windows-terminal.json

**Comment by ENDlezZenith** [comment]
> Most of msix or msixbundle are zip file and can be extracted by 7z, but I wonder are there some special cases.

Guess the [NanaZip manifest](https://github.com/ScoopInstaller/Main/blob/master/bucket/nanazip.json) would be a [special case which actually causes issues](https://github.com/M2Team/NanaZip/issues/787)?
"_It's not using the MSIX, it's manually unpacking the MSIX and getting the files within. This method of installation will not be supported. The official unattended installation method is clearly documented here: https://github.com/M2Team/NanaZip?tab=readme-ov-file#msix-package_"
which is `PowerShell -NoLogo -NoProfile -NonInteractive -InputFormat None -ExecutionPolicy Bypass Add-AppxPackage -DeferRegistrationWhenPackagesAreInUse -ForceUpdateFromAnyVersion -Path The path of the MSIX package`

Related: [Main#7428](https://github.com/ScoopInstaller/Main/issues/7428)
