### ISSUE TITLE
Installing some packages exits Docker container

### ISSUE THREAD

**Issue by thejohnfreeman** [ScoopInstaller/Scoop#4523]
I run scoop in a Docker container. Whenever I try to install vim or openssl, scoop finishes the installation successfully, returns to PowerShell, and then a second later, the container stops. Any idea what might be happening? Does scoop try to restart the machine or something? Other packages like nano and cmake don't have this problem.

**Comment by pratikpc** [comment]
I don't think that to be the case

**Comment by rasa** [comment]
@thejohnfreeman Can you point us to your Dockerfile?

**Comment by rashil2000** [comment]
Reopen if this is still an issue
