### ISSUE TITLE
ffmpeg install/update issue due to 404

### ISSUE THREAD

**Issue by Zzyzx-Wolfe** [ScoopInstaller/Scoop#4526]
Greetings,

I noticed today that when trying to install or update ffmpeg, it fails due to a 404 error:
```
scoop install ffmpeg
Installing 'ffmpeg' (4.4.1-2) [64bit]
The remote server returned an error: (404) Not Found.
URL https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2021-11-06-12-24/ffmpeg-n4.4.1-2-gcc33e73618-win64-gpl-4.4.zip is not valid
```

And I have verified myself by browsing to that URL that is now missing. Browsing the [releases for FFmpeg-Builds](https://github.com/BtbN/FFmpeg-Builds/releases), it appears that the 2021-11-06 build has been since removed.

Thanks in advance,
Zzyzx Wolfe

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Main/issues/2982
