### ISSUE TITLE
Make "scoop update" __NOT__ fail once one app fails

### ISSUE THREAD

**Issue by AntonOks** [ScoopInstaller/Scoop#4529]
Hi devs.

One core strength of SCOOP is the "autoupdate" feature. But if there are multiple apps to update, scoop fails as soos as one of the update fails.

See:
```powershell
λ  scoop update *
ffmpeg: 4.4-190 -> 4.4.1-2
gitlab-runner: 14.4.0 -> 14.5.0
hugo-extended: 0.88.1 -> 0.89.4
insomnia: 2021.5.3 -> 2021.6.0
kdiff3-aoks: 1.9.2 -> 1.9.4
kopia: 0.9.5 -> 0.9.6
kopia-aoks: 0.9.5 -> 0.9.6
kopiaUI-aoks: 0.9.5 -> 0.9.6
liberica-jre: 17-35 -> 17.0.1-12
notepadplusplus-aoks: 8.1.9.1 -> 8.1.9.2
nu: 0.39.0 -> 0.40.0
openjdk: 17-35 -> 17.0.1-12
qownnotes-aoks: 21.11.7 -> 21.11.8
uncrustify: 0.73.0 -> 0.74.0
vscodium: 1.62.2 -> 1.62.3
Updating 15 outdated apps:
Updating 'ffmpeg' (4.4-190 -> 4.4.1-2)
Downloading new version
OperationStopped: C:\Users\oks\scoop\apps\scoop\current\lib\install.ps1:130
Line |
 130 |          throw $e
     |          ~~~~~~~~
     | The remote server returned an error: (404) Not Found.

```

How about changing "scoop update" so that an ERROR is printed and the update just continues with the outstanding apps?!?

**Comment by chrismeller** [comment]
OP's requested behavior would make this consistent with the behavior of `scoop update` when an application is still running.

As a shameless plug, this would work really well with my request for a summary at the end of `scoop update *` from #4547.

**Comment by filipworksdev** [comment]
This would be the preferred behavior for me as well. Just update what is possible to update but if not possible simply throw error and skip .

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Scoop/issues/4135
