### ISSUE TITLE
WARN  "current_version" will be deprecated. Please change your code/manifest to use "Select-CurrentVersion"

### ISSUE THREAD

**Issue by phanirithvij** [ScoopInstaller/Scoop#4534]
https://github.com/ScoopInstaller/Scoop/blob/59088a9f0094ecaa0c36793eef232b3af237a59b/lib/install.ps1#L1079

Whenever I install something I get this warning.

```powershell
scoop install scratch
WARN  "current_version" will be deprecated. Please change your code/manifest to use "Select-CurrentVersion"
      -> C:\Users\Rithvij\scoop\apps\scoop\current\lib\install.ps1:1079:37
Installing 'scratch' (3.27.0) [64bit]
...
'scratch' (3.27.0) was installed successfully!
```

**Comment by phanirithvij** [comment]
Hmmm I wonder why github linked issue auto closing didn't work.

**Comment by rashil2000** [comment]
That's because that PR was merged in develop branch. Auto closing works only in default branches.

**Comment by phanirithvij** [comment]
I see

**Comment by lobanov4real** [comment]
I can't understand how I can fix this warning when I update Luarocks?

**Comment by HUMORCE** [comment]
> I can't understand how I can fix this https://github.com/luarocks/luarocks/issues/1473 when I update Luarocks?

report to [extras bucket repo](https://github.com/ScoopInstaller/Extras)

**Comment by niheaven** [comment]
> I can't understand how I can fix this [warning](https://github.com/luarocks/luarocks/issues/1473) when I update Luarocks?

Is fixed https://github.com/ScoopInstaller/Main/commit/8730cb9c714798a34e7a7e8b7e8c951fdd892f7f
