### ISSUE TITLE
How-to remove commands from scoop help

### ISSUE THREAD

**Issue by collinsmith** [ScoopInstaller/Scoop#4538]
I was playing around and trying to add an alias for `zulu8-jdk` as `zulu8` and I've somehow ended up creating an extra entry in my help doc for `zulu8` that references/does nothing -- is there any way to remove this? Thank you!

Scoop version:
59088a9f (HEAD -> master, tag: 2021-11-22, origin/master, origin/HEAD) Merge from ScoopInstaller/develop (#4527), 2021/11/22

![image](https://user-images.githubusercontent.com/4914327/143325134-dae73b40-1908-4ae2-903f-7814d6a4f630.png)

**Comment by rashil2000** [comment]
What does your ~/.config/scoop/config.json file contain?

Also paste the output of `dir ~\Scoop\apps\scoop\current\libexec\`.

**Comment by collinsmith** [comment]
@rashil2000 

~/.config/scoop/config.json
```json
{
  "lastupdate": "2021-11-24T19:49:26.9769136-08:00",
  "SCOOP_REPO": "https://github.com/lukesampson/scoop",
  "SCOOP_BRANCH": "master",
  "alias": {}
}
```

dir ~\Scoop\apps\scoop\current\libexec\
```bash
❯ dir C:\Users\csmith\Scoop\apps\scoop\current\libexec\

    Directory: C:\Users\csmith\scoop\apps\scoop\current\libexec

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          2021-11-19  6:20 PM           3021 scoop-alias.ps1
-a---          2021-11-19  6:20 PM           1142 scoop-bucket.ps1
-a---          2021-11-19  6:20 PM           1662 scoop-cache.ps1
-a---          2021-11-19  6:20 PM           1809 scoop-checkup.ps1
-a---          2021-11-22  6:20 PM           2546 scoop-cleanup.ps1
-a---          2021-11-19  6:20 PM           1530 scoop-config.ps1
-a---          2021-11-19  6:20 PM           1545 scoop-create.ps1
-a---          2021-11-19  6:20 PM            723 scoop-depends.ps1
-a---          2021-11-22  6:20 PM           1799 scoop-export.ps1
-a---          2021-11-19  6:20 PM           1182 scoop-help.ps1
-a---          2021-11-19  6:20 PM            772 scoop-hold.ps1
-a---          2021-11-19  6:20 PM            612 scoop-home.ps1
-a---          2021-11-22  6:20 PM           4330 scoop-info.ps1
-a---          2021-11-22  6:20 PM           4670 scoop-install.ps1
-a---          2021-11-22  6:20 PM           1835 scoop-list.ps1
-a---          2021-11-22  6:20 PM            472 scoop-prefix.ps1
-a---          2021-11-22  6:20 PM           2906 scoop-reset.ps1
-a---          2021-11-22  6:20 PM           3732 scoop-search.ps1
-a---          2021-11-19  6:20 PM           2879 scoop-status.ps1
-a---          2021-11-19  6:20 PM            774 scoop-unhold.ps1
-a---          2021-11-22  6:20 PM           4506 scoop-uninstall.ps1
-a---          2021-11-22  6:20 PM          13183 scoop-update.ps1
-a---          2021-11-19  6:20 PM           8794 scoop-virustotal.ps1
-a---          2021-11-19  6:20 PM           1330 scoop-which.ps1
```

**Comment by rashil2000** [comment]
Remove the `alias` from you config, like this:
```json
{
  "lastupdate": "2021-11-24T19:49:26.9769136-08:00",
  "SCOOP_REPO": "https://github.com/lukesampson/scoop",
  "SCOOP_BRANCH": "master"
}
```

> I was playing around and trying to add an alias for zulu8-jdk as zulu8 and I've somehow ended up creating an extra entry in my help doc for zulu8 that references/does nothing

The aliases are not for the apps, but for Scoop commands themselves. Which command did you use to create alias?

**Comment by collinsmith** [comment]
@rashil2000

I removed that line and still have the same behavior.

I know that now :), I shot ahead of the doc and thought I could create shims using the alias command.

I'm honestly not sure which specific command did it, I was screwing around, so likely some variation of `scoop alias add zulu8 zulu8-jdk`.

**Comment by rashil2000** [comment]
And `scoop alias rm zulu8` does nothing?

**Comment by collinsmith** [comment]
@rashil2000 

Like you said, it's not an alias, I don't know how it got in there.

```bash
❯ scoop alias rm zulu8
Alias zulu8 doesn't exist.
```

**Comment by rashil2000** [comment]
Well that's definitely strange. It doesn't affect any functionality though, right? Only an extra entry in the help output.

**Comment by collinsmith** [comment]
Correct. Even `scoop help zulu8` does nothing

**Comment by rashil2000** [comment]
Ah, there's the error. Delete this file C:\Users\csmith\scoop\shims\scoop-zulu8.ps1

**Comment by collinsmith** [comment]
I removed `C:\Users\csmith\scoop\shims\scoop-zulu8.ps1` and success. Thank you!
