### ISSUE TITLE
Fallback urls when primary url is unavailable

### ISSUE THREAD

**Issue by eugenesvk** [ScoopInstaller/Scoop#4539]
Given that there are issues with GitHub rate limits that prevent many apps from being automatically updated, would it make sense to add a fallback url to the manifest so that in case the first github url fails you could fallback to an app's website for donwload (provided, of course, there is such an alternative website with binaries)? The hashes and all the install logic can remain the same
(as far as I understood, currently manifest supports arrays of urls only when you need to install several things at once)

**Comment by rasa** [comment]
If I understand your comment correctly, the two are unrelated. The GitHub API limit is only for hits to *.github.com urls (and only affects the Excavator and similar processes). The url to the applications themselves are not limited by GitHub.

**Comment by eugenesvk** [comment]
> affects the Excavator and similar processes

Yeah, I mean them, currently they can't do their magic for GitHub links, but if the link field allowed an array of links with two links: one from GitHub, and another from a non-GH site, then on failure they could apply an alternative checking method and still complete instead of failing

Just to illustrate based on a local `checkver.ps1` update process:
[This imageglass app](https://github.com/ScoopInstaller/Extras/blob/master/bucket/imageglass.json) uses GitHub to check for the latest version `"checkver": {"github": "https://github.com/d2phap/ImageGlass" },`, and if I were rate limited, it'd fail for me.
However, if I change it to:
```json
"checkver": {
"url": "https://imageglass.org/releases",
"regex": "Version: ([\\d.]+)"},
```

then I can get the latest version and do the manifest-update process without facing GitHub rate limits

But as far as I understand `checkver` does not allow different urls/methods to be specified at the same time, you have to either set "github" or a "url+regex" (or skip "url" to parse the homepage)

**Comment by rashil2000** [comment]
#4264
