### ISSUE TITLE
Provide a way to switch internal decompression helpers

### ISSUE THREAD

**Issue by HUMORCE** [ScoopInstaller/Scoop#4540]
`versions/7zip-zstd` depend on `main/7zip`

see also:
https://github.com/ScoopInstaller/Extras/issues/7425#issuecomment-980271210

https://github.com/ScoopInstaller/Scoop/blob/59088a9f0094ecaa0c36793eef232b3af237a59b/lib/core.ps1#L253-L257

**Comment by rashil2000** [comment]
Tracked here https://github.com/ScoopInstaller/Versions/issues/352

**Comment by HUMORCE** [comment]
@rashil2000 the bug cannot be solved by solving ScoopInstaller/Versions#352

**Comment by rashil2000** [comment]
Assuming 7zip-zstd can be installed without 7zip, then the helperpath will point to 7zip-zstd's 7z.exe binary, right?

**Comment by HUMORCE** [comment]
yes, but what if users need to install both of them.

**Comment by rashil2000** [comment]
![Screenshot (109)](https://user-images.githubusercontent.com/46838874/149623378-c800f6ca-2722-43a2-85f4-6417d7f2e188.png)

I'm not able to reproduce the issue

**Comment by HUMORCE** [comment]
nothing to do with `scoop-reset`.

func `Get-HelperPath` always use `main/7zip` as helper of `Expand-7zipArchive`, if you have both `main/7zip` and `versions/7zip-zstd` installed.

reproduction steps:
```
PS C:\Users\HUMOR\Desktop> scoop list 7zip
Installed apps matching '7zip':

  7zip 21.07 [main]
  7zip-zstd v21.03-v1.5.0-R2 [versions]

PS C:\Users\HUMOR\Desktop> scoop install .\t.json
Installing 't' (0) [64bit]
Loading dl.7z from cache
WARN  Warning: No hash in manifest. SHA256 for 'dl.7z' is:
    4ff3f914fc6c1b56cbfe16fee1c95f46e6c72c1817406e8a5397a5b30fba0c5f
Extracting dl.7z ... ERROR Exit code was 2!
Failed to extract files from C:\Users\HUMOR\scoop\apps\t\0\dl.7z.
Log file:
  ~\scoop\apps\t\0\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https:////
PS C:\Users\HUMOR\Desktop> cat ~\scoop\apps\t\0\7zip.log

7-Zip 21.07 (x64) : Copyright (c) 1999-2021 Igor Pavlov : 2021-12-26
...
PS C:\Users\HUMOR\Desktop> scoop uninstall 7zip
Uninstalling '7zip' (21.07).
Removing shim '7z.exe'.
Removing shim '7z.shim'.
Removing shortcut ~\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Scoop Apps\7-Zip.lnk
Unlinking ~\scoop\apps\7zip\current
PS C:\Users\HUMOR\Desktop> scoop install .\t.json
Installing 't' (0) [64bit]
Loading dl.7z from cache
WARN  Warning: No hash in manifest. SHA256 for 'dl.7z' is:
    4ff3f914fc6c1b56cbfe16fee1c95f46e6c72c1817406e8a5397a5b30fba0c5f
Extracting dl.7z ... ERROR Exit code was 2!
Failed to extract files from C:\Users\HUMOR\scoop\apps\t\0\dl.7z.
Log file:
  ~\scoop\apps\t\0\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https:////
PS C:\Users\HUMOR\Desktop> cat ~\scoop\apps\t\0\7zip.log

7-Zip 21.03 ZS v1.5.0 R2 (x64) : Copyright (c) 1999-2021 Igor Pavlov, 2016-2021 Tino Reichardt : 2021-10-05
...
PS C:\Users\HUMOR\Desktop> cat .\t.json
{
    "version": "0",
    "url": "https://github.com#/dl.7z"
}
```

**Comment by rashil2000** [comment]
I see. 

But what is the benefit of using 7zip-zstd in the helper instead of 7zip (if you have both installed)?

(I assume for .zst archives, Scoop will download zstd.exe separately, and not use 7zip-zstd for that.)

**Comment by HUMORCE** [comment]
just another option? users may think that the decompression is done by the version of 7z set with `scoop-reset`.

**Comment by rashil2000** [comment]
I see.

But since this is a special case, it shouldn't be handled by `scoop reset`.
