### ISSUE TITLE
is scoop team on holidays?

### ISSUE THREAD

**Issue by BentramLawrence** [ScoopInstaller/Scoop#4546]
winget team is on holidays https://github.com/microsoft/winget-cli/issues/1684

**Comment by BentramLawrence** [comment]
they banned me because i'm black https://github.com/microsoft/vscode/issues/138080#issuecomment-981903154

**Comment by BentramLawrence** [comment]
found out: no latex support for winget https://github.com/microsoft/winget-pkgs/issues/34998

**Comment by rashil2000** [comment]
They just locked the thread. They haven't been you yet, but I'm pretty sure I will if you post one more comment in this org.
