### ISSUE TITLE
Question: How long does it take for a manifest in an official bucket to be auto-updated?

### ISSUE THREAD

**Issue by redactedscribe** [ScoopInstaller/Scoop#4549]
I can't figure out why, but a manifest available via the Extras bucket still hasn't been updated, despite the manifest containing autoupdate code.

I copied the manifest to my system and ran `checkver.ps1 -app playnite` and Scoop returns `playnite: 9.10 (scoop version is 9.6) autoupdate available`.

I must be missing something because I don't understand why Playnite via Scoop is still on 9.6 when the manifest is capable of fetching 9.10. Are auto-updates something that require a manual review? What's causing the delay in a the newer version being available for download?

Thanks.

Edit: After some more thought, maybe this delay is because there is no autoupdate hash value defined so the file must be downloaded and hash calculated locally?

**Comment by niheaven** [comment]
Sorry for this delay, but it is because scoop's autoupdate agent reaches GitHub's rate limit, and it may took some days to recover...

**Comment by rasa** [comment]
See https://github.com/ScoopInstaller/Excavator/issues/5  and the 429s in 
https://scoop.r15.ch/extras/mud-20211201-021001.log
