### ISSUE TITLE
Relative dot-path leads to attempting to uninstall {wildcard|anything}?

### ISSUE THREAD

**Issue by maphew** [ScoopInstaller/Scoop#4556]
While trying to figure out how one might install a specific version for an app PR which hasn't yet been accepted into a bucket  I tried the syntax of `install {relative\path\to\local.json}` with `@{version}`. Scoop then goees on to tell me it's uninstalling everything in current directory, `.`.

~~~
$ scoop install bucket\pyzo.json@v4.11.2
Couldn't find manifest for 'bucket'.

$ scoop install .\bucket\pyzo.json@v4.11.2
WARN  Purging previous failed installation of ..
Uninstalling '.' ().
~~~

Thankfully it appears scoop just stalls at this point and as far as I can tell nothing actually happened. It does look as though something _might_ happen if the current directory held something it recognized. This looks like a bug waiting to bite.

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Scoop/issues/2370
