### ISSUE TITLE
undo reset on a version

### ISSUE THREAD

**Issue by kennedy** [ScoopInstaller/Scoop#4558]
I use the `scoop reset` version often to switch between different versions. It is great because scoop update wont mess with it. However, sometimes I would like to un-lock it and return the app to scoop's update cycle like the other applications.

There isn't any documentation to undo the reset command, Can someone share with me how to do this?

**Comment by rashil2000** [comment]
Doing `scoop reset` doesn't prevent the app from getting updated. I think you're confusing it with `scoop hold`.
