### ISSUE TITLE
'git' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by Zzyzx-Wolfe** [ScoopInstaller/Scoop#4566]
Greetings,
When I try to update scoop, I get the following:
```
scoop update
Updating Scoop...
'git' is not recognized as an internal or external command,
operable program or batch file.
Scoop update failed.
```
I have completely removed and reinstalled scoop and deleted the ~/scoop directory, yet the issue seems to remain.

Here is some additional information if it helps:
```
PS C:\Users\Zzyzx> which git

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
ExternalScript  git.ps1                                                       C:\Users\Zzyzx\scoop\shims\git.ps1

PS C:\Users\Zzyzx> scoop which git
~\scoop\apps\git-with-openssh\current\cmd\git.exe
PS C:\Users\Zzyzx> git version
git version 2.34.1.windows.1
```

**Comment by Zzyzx-Wolfe** [comment]
Alright, well, I'm not entirely sure why, but adding `C:\Users\Zzyzx\scoop\shims` to the system path and not just the user path seems to have fixed it.

**Comment by rashil2000** [comment]
Great! Please reopen if it occurs again.

**Comment by onacit** [comment]
Happened again. I needed to add `C:\Users\<me>\scoop\apps\git\current\bin` into my `PATH`.

**Comment by rashil2000** [comment]
Scoop creates a shim for that. So no need to add git folder to PATH.

Only the scoop shims folder should be in PATH
