### ISSUE TITLE
[Bug] Unhandled Exception while searching 

### ISSUE THREAD

**Issue by dakehero** [ScoopInstaller/Scoop#4574]
## Bug Report

**Package Name:** [name of package which has bug(s)]
nanazip

### Current Behaviour

*No matches found* and exception message thrown by `Invoke-WebRequest`

### Expected Behaviour
no exception message

### Additional context/output
![image](https://user-images.githubusercontent.com/23186318/145511332-0d691c0a-26b6-4d8f-ba22-a3f76a321da9.png)

### Possible Solution
use `try-catch-finally` expression to handle it

### System details

**Windows version:** [e.g. 7, 8, 10]
Windows 11 21H2

**OS architecture:** [e.g. 32bit, 64bit]
64bit

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]
7.2.0
**Additional software:** [(optional) e.g. ConEmu, Git]
Windows Terminal

**Comment by rashil2000** [comment]
Looks like a bug. 

Can you make a PR?

**Comment by niheaven** [comment]
This will be occurred when you cannot access github.com, and existed for a long time.

**Comment by rashil2000** [comment]
I can access github.com, all scoop functions work fine, but I can still reproduce this error

**Comment by FDUZS** [comment]
same here.

<img width="938" alt="8qkvTFektI" src="https://user-images.githubusercontent.com/20297872/145662369-5d2f399b-ff85-4d98-8ec8-283933255b9a.png">

**Comment by Mouriya-Emma** [comment]
same problam .i can access github.com and implement scoop update.

![Snipaste_2021-12-13_10-48-35.png](https://s2.loli.net/2021/12/13/GgYs3MtmCcrn1Ql.png)
