### ISSUE TITLE
[Feature] rsync instead of cwrsync

### ISSUE THREAD

**Issue by yonnig** [ScoopInstaller/Scoop#4583]
#### Is your feature request related to a problem? Please describe.
I had some trouble using cwrsync, trying to sync files with a remote Raspberry Pi OS. The sync was actually failing at the very beginning of the process, printing some read error (sorry, I do not remember the exact message).
However it works perfectly with a rsync version of the MSYS2 project, manually installed within gitforwindows (git-bash). 

#### Describe the solution you'd like
As scoop.sh is an excellent project, with a quite comfortable ease of use, would it be possible to have a "true" (not sure I can use that word) rsync version, rather than the itefix.net one ?

#### Describe alternatives you've considered
gitforwindows (git-bash) along with a manual install of rsync from MSYS2.

**Comment by rashil2000** [comment]
MSYS2 packages are not supported on Scoop because there's no way to autoupdate them. Please use pacman to install rsync in MSYS2.
