### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by zuiaiyutu** [ScoopInstaller/Scoop#4584]
scoop update
Updating 'extras' bucket...
fatal: unable to access 'https://github.com/lukesampson/scoop-extras/': OpenSSL SSL_read: Connection was reset, errno 10054
Updating 'main' bucket...
fatal: unable to access 'https://github.com/ScoopInstaller/Main/': Failed to connect to github.com port 443 after 21054 ms: Timed out
Scoop was updated successfully!

Sometimes it works properly, like scoop update annie
Sometimes, it goes wrong, like scoop update ffmpeg

**Comment by rashil2000** [comment]
Marking this issue as invalid for ignoring the template.
