### ISSUE TITLE
Scoop Wiki can't be checked out on Windows

### ISSUE THREAD

**Issue by maphew** [ScoopInstaller/Scoop#4601]
## Bug Report

The Scoop wiki cannot be cloned or otherwised used by git on Windows due to one more files that use characters unsupported by the file system. There is a workaround that doesn't change anything in the wiki repo but using it entails disabling a git security setting.

- Clearest description of the issue I've found is https://confluence.atlassian.com/bitbucketserverkb/error-invalid-path-during-git-clone-to-windows-client-1085186345.html
- The main tracking issue on Github appears to be https://github.com/git-for-windows/git/issues/2803

#### Current Behavior
```
» git clone https://github.com/ScoopInstaller/Scoop.wiki.git        
Cloning into 'Scoop.wiki'...                                        
remote: Enumerating objects: 1339, done.                            
remote: Counting objects: 100% (6/6), done.                         
remote: Compressing objects: 100% (6/6), done.                      
remote: Total 1339 (delta 1), reused 0 (delta 0), pack-reused 1333R 
Receiving objects: 100% (1339/1339), 189.76 KiB | 6.00 KiB/s, done. 
Resolving deltas: 100% (812/812), done.                             
error: invalid path 'Can-I-Use-Scoop-in-Bash,-Zsh,-etc?.md'         
fatal: unable to checkout working tree                              
warning: Clone succeeded, but checkout failed.                      
You can inspect what was checked out with 'git status'              
and retry with 'git restore --source=HEAD :/'                       
```

#### Possible Solution

Workarounds for users: 
- Disable NTFS file system protection with `git config core.protectNTFS false` (unsupported characters will be replaced with something else), or
- use WSL (Windows Subsystem for Linux) or Cygwin

Solution at repo level: remove `?` from `Can-I-Use-Scoop-in-Bash,-Zsh,-etc?.md` and maybe others.

### System details

Any version of Windows.

**Comment by maphew** [comment]
The list of reserved characters:

>     `<` (less than)
>     `>` (greater than)
>     `:` (colon)
>     `"` (double quote)
>     `/` (forward slash)
>     `\` (backslash)
>     `|` (vertical bar or pipe)
>     `?` (question mark)
>     `*` (asterisk)

from https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file

**Comment by rashil2000** [comment]
I have renamed the page to remove the ? character

Can you try cloning now?

**Comment by maphew** [comment]
yes, works now. Thanks!
