### ISSUE TITLE
Update failed [Bug] 

### ISSUE THREAD

**Issue by Mylo17** [ScoopInstaller/Scoop#4602]
#### Current Behavior
Can't update scoop after recent merge

#### Expected Behavior
When i run scoop update * scoop should update itself and the needed packages

#### Additional context/output
error: Your local changes to the following files would be overwritten by merge:
        lib/install.ps1
Please commit your changes or stash them before you merge.
Aborting
Update failed.

### System details

**Windows version:**  10

**OS architecture:** 64 bit 

**PowerShell version:** 7.2

#### Scoop Configuration

```json
{
  "lastupdate": "2021-12-25T10:32:45.3941178+01:00",
  "SCOOP_REPO": "https://github.com/lukesampson/scoop",
  "SCOOP_BRANCH": "master",
  "aria2-warning-enabled": false,
  "aria2-enabled": true
}
```

**Comment by niheaven** [comment]
Have you edit `lib/install.ps1` file?

You could discard these changes by `git restore .` in scoop's current dir.

**Comment by Mylo17** [comment]
Thanks a lot that worked, but i did not touch anything in the scoop repo. yesterday after turning on the pc and trying too update scoop that alert came up

**Comment by rashil2000** [comment]
No worries, can you close the issue if it's resolved?
