### ISSUE TITLE
On a fresh Windows 10 scoop install, scoop update removes the ~\scoop\apps\scoop\current directory [Bug] 

### ISSUE THREAD

**Issue by dsa-ols** [ScoopInstaller/Scoop#4607]
#### Current Behavior
On Windows 10, following sequence of actions:
 >  iwr -useb get.scoop.sh | iex
 > scoop update

Leads to ~\scoop\apps\scoop\current directory being removed and breaking the install

#### Expected Behavior
On install I guess I have correct tree structure:
![scoop-tree-struct-orig](https://user-images.githubusercontent.com/62901751/147662486-a39a027a-9117-47fc-b353-ac0b88c54051.PNG)

After update I have no more current directory:
![scoop-tree-struct-after-update](https://user-images.githubusercontent.com/62901751/147662482-2b17b2b4-69fe-4fa8-808d-c37d082f99d2.PNG)

### System details

**Windows version: 10 Pro 21H2 19044.1415**

**OS architecture: 64bit**

**PowerShell version: 5.1.19041.1320**

#### Scoop Configuration
```json
{
    "lastupdate":  "2021-12-29T12:48:34.1876612+01:00",
    "SCOOP_REPO":  "https://github.com/lukesampson/scoop",
    "SCOOP_BRANCH":  "master"
}
```

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Scoop/issues/4005

**Comment by dsa-ols** [comment]
Hi @rashil2000 ,
Thanks! The scenario of #4005 is not exactly similar (I do not press CTRL-C) but could well be linked.
I didn't get how you fix #4005 this though? Could you explain a bit more?
Best regards,
Olivier

**Comment by rashil2000** [comment]
It's not exactly similar, but the failure mechanism is same.

The issue is still not fixed, it's a known bug.

**Comment by dsa-ols** [comment]
OK thanks for the clarification ; how could I put back on track an existing scoop install. I intend to rename existing scoop directory, reinstall scoop (and git?) in new directory, then recopy (add on top) the previous apps. Would that be a proper way?

**Comment by rashil2000** [comment]
You might have to run `scoop reset *` after all that.
