### ISSUE TITLE
Option to force install held package

### ISSUE THREAD

**Issue by dw72** [ScoopInstaller/Scoop#4625]
#### Describe the solution you'd like
It would be nice to have an option to force update held package.

**Comment by niheaven** [comment]
Have you tried `scoop update [app] -f`?

**Comment by rashil2000** [comment]
Why hold a package if you want to force update it?

**Comment by dw72** [comment]
Yes, but packet is still in hold

**Comment by rashil2000** [comment]
I can understand your use case, but that conflicts with the whole purpose of `hold`. Held apps are not updated in any scenario, unless manually unheld.

**Comment by dw72** [comment]
But I can imagine that sometimes held packages are updated by admin for some reason (not only this one in my example). Then a switch that shortens the path of this update will be helpfull.

**Comment by susanonec** [comment]
Is it possible to write an alias to finish this job?

**Comment by rashil2000** [comment]
Write a small Powershell script to unhold the app, update it, and then hold it again. Now make this script a scoop alias.

**Comment by susanonec** [comment]
> Write a small Powershell script to unhold the app, update it, and then hold it again. Now make this script a scoop alias.

Exactly what I mean! But I think there's no need to write a powershell script, in the document it shows multiple commands can be excecuted in a single alias, which for example:
```
scoop alias add [your alias name] 'scoop unhold $args[0] && scoop update $args[0] && scoop hold $args[0]'
```

And @dw72, it that what you want?

**Comment by dw72** [comment]
Not exactly what I wanted, but it works... so we can consider this topic to be finished :)

**Comment by beyond9thousand** [comment]
> > Write a small Powershell script to unhold the app, update it, and then hold it again. Now make this script a scoop alias.
> 
> Exactly what I mean! But I think there's no need to write a powershell script, in the document it shows multiple commands can be excecuted in a single alias, which for example:
> 
> ```
> scoop alias add [your alias name] 'scoop unhold $args[0] && scoop update $args[0] && scoop hold $args[0]'
> ```
> 
> And @dw72, it that what you want?

![image](https://github.com/ScoopInstaller/Scoop/assets/77363063/2a292125-30ae-48a7-895a-3ddcd6c565cb)
 keep getting the following error

**Comment by rashil2000** [comment]
Use `;` instead of `&&`
