### ISSUE TITLE
[Feature] Number of downloads and other Scoop statistics

### ISSUE THREAD

**Issue by redactedscribe** [ScoopInstaller/Scoop#4626]
## Feature Request

It would be cool to have some insight into the number of downloads a given bucket has served, or the number of times an app has been downloaded overall and for a given version. Does Scoop collect any kind of interesting anonymous statistics that could be published online and updated automatically? Maybe these stats could be displayed under `scoop bucket info` (doesn't exist) and `scoop info`? I realise this would be a low priority, but I'd be very interested in seeing such numbers if anyone would be willing to bring this to life. I don't have much experience with [Chocolatey](https://community.chocolatey.org/packages/chocolatey) but it tracks [some basic download statistics](https://community.chocolatey.org/packages/chocolatey#versionhistory).

Thanks!

**Comment by rashil2000** [comment]
Tracked here #3781
