### ISSUE TITLE
[Feature] Ability to use Variables like $version in `persist` parameter

### ISSUE THREAD

**Issue by lenicyl** [ScoopInstaller/Scoop#4630]
#### Is your feature request related to a problem? Please describe.
I was trying to make a manifest for [Flow Launcher](https://github.com/Flow-Launcher/Flow.Launcher/), however I had an issue while doing so. 
Flow Launcher has a folder called `app-[version]`, the screenshot below will help you relate to what im talking about. This folder contains a folder that i would like to be placed at persist

![image](https://user-images.githubusercontent.com/73347143/148539311-587ae472-dde2-4ec5-bb22-27919697192e.png)

However since the folder name would change every update, that wouldnt really work unless I make use of some hacky post-install script.

---

#### Describe the solution you'd like
Ability to use variables like `$version` for `persist` parameter

Thanks.

**Comment by rashil2000** [comment]
All properties except `persist` support substitution variables. For `persist`, I'm not sure as it needs to be consistent between different versions. @issaclin32 is my assumption correct?

**Comment by niheaven** [comment]
A long long ago PR solved this kind of persisting work: https://github.com/ScoopInstaller/Scoop/pull/3248.

**Comment by Ash258** [comment]
https://github.com/ScoopInstaller/Scoop/blob/1dbab1fee8e8d775fc06248d2a3301d633c580a1/lib/install.ps1#L1149-L1156

```yml
persist:
- - app-1.9.1
  - appPersisted
autoupdate:
  persist:
  - - app-$version
    - appPersisted 
```

**Comment by niheaven** [comment]
Forget this basic usage. Autoupdate WILL update `persist`, as the following existed in `autoupdateArch`

https://github.com/ScoopInstaller/Scoop/blob/c864f68c0ba31cfa493a5b91074807f1cc3f067a/schema.json#L221-L223

**Comment by lenicyl** [comment]
> https://github.com/ScoopInstaller/Scoop/blob/1dbab1fee8e8d775fc06248d2a3301d633c580a1/lib/install.ps1#L1149-L1156
> 
> ```yaml
> persist:
> - - app-1.9.1
>   - appPersisted
> autoupdate:
>   persist: # Autoupdate should allow it
>   - - app-$version
>     - appPersisted 
> ```

I tried `"app-$version\\UserData"` and i dont think it worked, did i do anything wrong ?

ill try again just in case and report back

**Comment by lenicyl** [comment]
> https://github.com/ScoopInstaller/Scoop/blob/1dbab1fee8e8d775fc06248d2a3301d633c580a1/lib/install.ps1#L1149-L1156
> 
> ```yaml
> persist:
> - - app-1.9.1
>   - appPersisted
> autoupdate:
>   persist: # Autoupdate should allow it
>   - - app-$version
>     - appPersisted 
> ```

Thanks but since im trying to achieve ` "persist": "app-1.9.1\\UserData",`
Using the persist in autoupdate wont really make sense since the `UserData` folder will be reset every update

**Comment by rashil2000** [comment]
> Thanks but since im trying to achieve ` "persist": "app-1.9.1\\UserData",` Using the persist in autoupdate wont really make sense since the `UserData` folder will be reset every update

What they meant is that you can persist a folder using a different name - by specifying a source and a target in an array. That will help you persist across versions.

**Comment by lenicyl** [comment]
Oh, ok
Thanks for your help everyone
