### ISSUE TITLE
Saying goodbye to JetBrains bucket?

### ISSUE THREAD

**Issue by ths95049** [ScoopInstaller/Scoop#4642]
I try to run `scoop update *` to update my packages but found that jetbrain bucket is no longer available.
And found that [a recent merge](https://github.com/ScoopInstaller/Scoop/commit/1dbab1fee8e8d775fc06248d2a3301d633c580a1#diff-e9814a5e9323d0f56ff5b7dd78efaf026328a9dbaac602ed603dfe8c78e8eaf2) removed jetbrain from the bucket list.
Is that an intended or merge mistake?

Of cause, I can add the repo manually but just to check if it is by mistake or on purpose.
My apologies for not using the template, for that I don't think this could fit in any of those categories.

**Comment by rashil2000** [comment]
https://github.com/Ash258/Scoop-JetBrains/issues/49

**Comment by HUMORCE** [comment]
related: https://github.com/Ash258/Scoop-JetBrains/issues/49

the extras bucket contains jetbrains series applications.

**Comment by rashil2000** [comment]
> the extras bucket contains jetbrains series applications.

IDEs are in _Extras_, CLI tools in _Main_, Early Access and Release Candidates in _Versions_.

**Comment by ths95049** [comment]
@rashil2000 @HUMORCE 
thank you for the quick response.
I found that too, which "add the repo manually" means that repo.

By the time now, is there any buckets are planning to be extracted from `known`?

**Comment by rashil2000** [comment]
> By the time now, is there any buckets are planning to be extracted from known?

Not as of now
