### ISSUE TITLE
[Bug] The unauthenticated git protocol on port 9418 is no longer supported.

### ISSUE THREAD

**Issue by getsueineko** [ScoopInstaller/Scoop#4645]
Today I got next error when I was trying scoop update:

❯ scoop update
Updating Scoop...
fatal: remote error:
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.

My scoop config is:
{
  "lastupdate": "2022-01-11T17:45:09.3151845+03:00",
  "SCOOP_REPO": "https://github.com/lukesampson/scoop",
  "SCOOP_BRANCH": "master",
  "7ZIPEXTRACT_USE_EXTERNAL": true
}

I tried change https to ssh in config but haven't success.

I can't find a solution on the project page.

**Comment by tech189** [comment]
Have you tried following the steps on the page you linked? Especially in this section: https://github.blog/2021-09-01-improving-git-protocol-security-github/#how-do-i-prepare

**Comment by rasa** [comment]
Run 
`scoop bucket list`
and if you have any buckets with a `git:` prefix, they will need to be removed and re-added with an `https:` (or `http:`) prefix:
```
scoop bucket rm name
scoop bucket add name https://ex.com
```

**Comment by getsueineko** [comment]
This is strange. But today everything is working fine. I haven't changed anything.

**Comment by rashil2000** [comment]
You can close the issue if it is fixed for you

**Comment by tech189** [comment]
It is working today again only because it was a 'brownout'. GitHub deliberately made it stop working temporarily yesterday so that you are aware that it will completely stop working on the 15th March.

**Comment by rasa** [comment]
Would it make sense for scoop to either:
1. Rewrite `git:` urls as `https:`
or
2. Tell the user to save an access token via `scoop config`
3. ?

**Comment by tech189** [comment]
Probably the first option would be good. But in addition, @getsueineko should probably set up an access token too: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token

**Comment by getsueineko** [comment]
Today it stops working again =( Someone also?

**Comment by getsueineko** [comment]
> scoop bucket list

❯ scoop bucket list


Name   Source                                   Updated             Manifests
----   ------                                   -------             ---------
extras https://github.com/ScoopInstaller/Extras 14.03.2022 19:30:02      1432
main   https://github.com/ScoopInstaller/Main   14.03.2022 19:29:47       991

**Comment by rashil2000** [comment]
![image](https://user-images.githubusercontent.com/46838874/158787624-0c546608-58d2-482b-ae58-97299214a430.png)


Working here

**Comment by getsueineko** [comment]
![image](https://user-images.githubusercontent.com/14312837/159133700-7effe78b-b6e4-4ebf-82bd-c7f32152aeb3.png)

**Comment by getsueineko** [comment]
I changed config
https://github.com/lukesampson/scoop to http://github.com/ScoopInstaller/Scoop and got new errors
![image](https://user-images.githubusercontent.com/14312837/159134045-6afb5b9e-1b66-498a-81b4-d960ddfa293f.png)

Any idea?

**Comment by getsueineko** [comment]
My bad. The problem was with my git config 

**git config --list --show-origin**
file:C:/Program Files/Git/etc/gitconfig diff.astextplain.textconv=astextplain
file:C:/Program Files/Git/etc/gitconfig filter.lfs.clean=git-lfs clean -- %f
file:C:/Program Files/Git/etc/gitconfig filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Program Files/Git/etc/gitconfig filter.lfs.process=git-lfs filter-process
file:C:/Program Files/Git/etc/gitconfig filter.lfs.required=true
file:C:/Program Files/Git/etc/gitconfig http.sslbackend=openssl
file:C:/Program Files/Git/etc/gitconfig http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
file:C:/Program Files/Git/etc/gitconfig core.autocrlf=true
file:C:/Program Files/Git/etc/gitconfig core.fscache=true
file:C:/Program Files/Git/etc/gitconfig core.symlinks=false
file:C:/Program Files/Git/etc/gitconfig pull.rebase=false
file:C:/Program Files/Git/etc/gitconfig credential.helper=manager-core
file:C:/Program Files/Git/etc/gitconfig credential.https://dev.azure.com.usehttppath=true
file:C:/Program Files/Git/etc/gitconfig init.defaultbranch=master
file:C:/Users/saiba.DESKTOP-7HGEO0P/.gitconfig  credential.helper=manager-core
file:C:/Users/saiba.DESKTOP-7HGEO0P/.gitconfig  **url.git://github.com/.insteadof=https://github.com/**

Fix it!
