### ISSUE TITLE
[Bug] Unable to check for latest app version with scoop status or scoop update *

### ISSUE THREAD

**Issue by Driek123** [ScoopInstaller/Scoop#4646]
#### Current Behavior
When I run `scoop status` I get the following error: 

```
> PS C:\Users\$username\scoop\apps> scoop status
Scoop is up to date.
Compare-Version : Cannot process argument transformation on parameter 'ReferenceVersion'. Cannot convert value to type
System.String.
At C:\Users\$username\scoop\apps\scoop\current\lib\core.ps1:312 char:68
+ ... utdated = ((Compare-Version -ReferenceVersion $status.version -Differ ...
+                                                   ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Compare-Version], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Compare-Version

Everything is ok!
```
When I run `scoop update *` I get the same error: 

```
Compare-Version : Cannot process argument transformation on parameter 'ReferenceVersion'. Cannot convert value to type
System.String.
At C:\Users\HP\scoop\apps\scoop\current\lib\core.ps1:312 char:68
+ ... utdated = ((Compare-Version -ReferenceVersion $status.version -Differ ...
+                                                   ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Compare-Version], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Compare-Version

Latest versions for all apps are installed! For more information try 'scoop status'
```

#### Expected Behavior
The absence of that error message at least, or showing a list of outdated apps in its place if any. Even if the output message says it's all ok, the presence of the error doesn't seem ok. 

#### Additional context/output
I recently reinstalled scoop because of a mess up in an earlier installation. Only copied over the persist & bucket folders before reinstalling all the apps. There weren't any errors before this. 

Running `scoop list` or `scoop update` gives no errors. 

I've tried reinstalling scoop with ` git clone 'https://github.com/scoopinstaller/scoop.git' 'C:\Users\$username\scoop\apps\scoop\current'` already, did not fix the error. 

### System details

**Windows version:** [e.g. 7, 8, 10]
Windows 10 

**OS architecture:** [e.g. 32bit, 64bit]
64bit 

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]
```
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      19041  1320
```

#### Scoop Configuration

```
{
    "SCOOP_BRANCH":  "master",
    "debug":  false,
    "lastupdate":  [today],
    "SCOOP_REPO":  "https://github.com/ScoopInstaller/Scoop",
    "virustotal_api_key":  "[key]"
}
```

**Comment by rashil2000** [comment]
I think there's a particular app that's causing this. Can you run `scoop update <app>` for each app to pinpoint the cause?

**Comment by Driek123** [comment]
Ran through each app individually and it turns out it was a particular app (was my own manifest oops) with that error - uninstalled it and the error went away :) Strange that this didn't cause issues in the previous installation though. But good to have the error gone! 

Thanks for the quick reply and have a good day 👍
