### ISSUE TITLE
[Bug] `core.ps1\installed()` cannot distinct failed install

### ISSUE THREAD

**Issue by niheaven** [ScoopInstaller/Scoop#4648]
## Bug Report

In commit [`53dcb5a` (#4638)](https://github.com/ScoopInstaller/Scoop/pull/4638/commits/53dcb5a460ff2a450f11a0961cd8cde34d4eeb06), the update logic has changed, and there is a bug in `core.ps1\installed()` that it reports a failed installing app as `installed`.

#### Current Behavior

So, this causes:

![image](https://user-images.githubusercontent.com/5832170/149077377-1307011f-6947-4b32-a915-e8e091618a86.png)

Okay, it thinks just uninstalled app (`ag` here) as installed and doesn't install it again...

#### Possible Solution

I'll fix `installed()` function by checking `install.json` in installed dir.

**Comment by HUMORCE** [comment]
failed installation(s cannot uninstall, after https://github.com/ScoopInstaller/Scoop/pull/4650

```
> scoop -v
Current Scoop version:
d9f55a3a (HEAD -> develop, origin/develop) refactor(ci,tests): Support both AppVeyor and GitHub Actions (#4655)
```


```
> scoop install x264
Installing 'x264' (3081) [64bit]
--- ctrl + c ---
> scoop list x264
Installed apps matching 'x264':

  x264  *failed*

> scoop uninstall x264
ERROR 'x264' isn't installed.
```

**Comment by niheaven** [comment]
That app is NOT installed, so the list and uninstall output are fine, IMO. I'll add some logic in `scoop-cleanup` to cleanup these false installed apps.
