### ISSUE TITLE
Angry IP Scanner 3.7.6 won't start if JVM is 32bit

### ISSUE THREAD

**Issue by quantuumsnot** [ScoopInstaller/Scoop#4661]
OS: Windows 8.1 x64
![bug ipscan](https://user-images.githubusercontent.com/12394810/149637822-8d496c2f-8d9e-4933-aeed-670c6320d9e8.jpg)

**Comment by rashil2000** [comment]
Which bucket is the app in?

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Extras/blob/master/bucket/ipscan.json#L7-L8

https://github.com/ScoopInstaller/Extras/pull/956#issuecomment-394118844

**Comment by quantuumsnot** [comment]
Yeah, seems it was fixed THREE years ago and still it's broken :+1:
