### ISSUE TITLE
[DEV BRANCH][Bug] install/update app from the wrong bucket

### ISSUE THREAD

**Issue by HUMORCE** [ScoopInstaller/Scoop#4662]
#### Current Behavior

app cannot be installed/updated from specified/original bucket.

#### Expected Behavior
install the app from the specified bucket.

#### Additional context/output
```
> scoop list firefox
Installed apps matching 'firefox':

  firefox 96.0 [nuke]
> scoop update firefox
> scoop list firefox
Installed apps matching 'firefox':

  firefox 96.0.1 [extras]
> scoop install nuke/discord
> scoop list discord
Installed apps matching 'discord':

  discord 0.0.311 [extras]
```

**all shortcuts defined in the original manifest still exist, even if the wrong manifest is installed.**

#### Possible Solution
i have not checked the source code yet.

### System details

**Windows version:** 11 21H2

**OS architecture:** x64

**PowerShell version:** win 5.1.22000.282 / core 7.1.2

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
{
    "lastupdate":  "2022-01-16T03:14:56.4497163+00:00",
    "SCOOP_REPO":  "git@github.com:ScoopInstaller/Scoop.git",
    "SCOOP_BRANCH":  "develop",
    "debug":  true,
    "alias":  {
                  "rife":  "scoop-rife",
                  "replace":  "scoop-replace",
                  "kill":  "scoop-kill"
              },
    "MSIEXTRACT_USE_LESSMSI":  true,
    "proxy":  "none",
    "aria2-enabled":  false,
    "aria2-options":  [
                          "--all-proxy=\"http://127.0.0.1:1080\""
                      ]
}
```

**Comment by niheaven** [comment]
Please test the fixed PR so I could merge it, thanks.
