### ISSUE TITLE
[Bug] cleanup cannot delete old version 

### ISSUE THREAD

**Issue by zhangchaoza** [ScoopInstaller/Scoop#4663]
#### Current Behavior

After scoop cleanup *, there were nothing cleaned up.
```
$ scoop cleanup *
Everything is shiny now!
```
#### Expected Behavior

Should clear old version, such like 
```
Removing pe-bear: _0.5.5.2.old
```
I found all the directories like "_$version.old" cannot be deleted.
#### Possible Solution

I changed [function Get-InstalledVersion in `lib\versions.ps1`](https://github.com/ScoopInstaller/Scoop/blob/5602083868ed04224ea8edf1ff0c3a2a3f6588b9/lib/versions.ps1#L98)
```
return $versions | Where-Object { ($_ -ne 'current') -or ($_ -like '_*.old*') }
```
### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** 7.2.1

**Additional software:** [(optional) 
Current Scoop version:
56020838 (HEAD -> master, tag: 2021-12-26, origin/master, origin/HEAD) fix(schema): Add 'license' definition (#4596)

**Comment by rashil2000** [comment]
@niheaven looks like this was added in https://github.com/ScoopInstaller/Scoop/pull/3721. Any reason for excluding `*.old` folders?

**Comment by niheaven** [comment]
It's not a bug of `Get-InstalledVersion`, it's a bug of `scoop-cleanup`, I'll fix it soon.
