### ISSUE TITLE
[Bug] scoop does not support bucket path with blanks

### ISSUE THREAD

**Issue by Metal-Frog** [ScoopInstaller/Scoop#4668]
#### Current Behavior
scoop is not able to add a buckets with blanks in the path:
![image](https://user-images.githubusercontent.com/11056711/149738208-d7ba62ba-cbed-4d68-89d2-62e4aa29208a.png)

#### Expected Behavior
scoop must support bucket paths with blanks

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** 5.1.19041.1320

#### Scoop Configuration

```
{
    "lastupdate":  "2022-01-17T08:50:30.1227428+01:00",
    "alias":  {

              },
    "SCOOP_REPO":  "https://github.com/ScoopInstaller/Scoop",
    "SCOOP_BRANCH":  "master"
}
```

**Comment by rashil2000** [comment]
Currently scoop does not support adding local bucket paths. This is being tracked here - https://github.com/ScoopInstaller/Scoop/issues/4019
