### ISSUE TITLE
[Bug] scoop does not recognize updates

### ISSUE THREAD

**Issue by Metal-Frog** [ScoopInstaller/Scoop#4669]
#### Current Behavior
I've been trying this for days now. I couldn't manage to let scoop know that an app has an update.
Here are the steps I did exactly:

1. Created a bucket with the provided template
2. Created a manifest (version 1.0)
3. Added the bucket to scoop
4. Installed app
5. Updated manifest file to version 1.1
6. git commit
7. scoop status => no updates
8. scoop update myapp => Latest versions for all apps are installed ...

#### Expected Behavior
scoop must recognize the provided app update

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** 5.1.19041.1320

#### Scoop Configuration
```json
{
    "lastupdate":  "2022-01-17T08:50:30.1227428+01:00",
    "alias":  {

              },
    "SCOOP_REPO":  "https://github.com/ScoopInstaller/Scoop",
    "SCOOP_BRANCH":  "master"
}
```

**Comment by HUMORCE** [comment]
manifests in `SCOOP\buckets\*` updated properly?

**Comment by Metal-Frog** [comment]
Unfortunately not!

**Comment by rashil2000** [comment]
> 1. Created a bucket with the provided template
> 2. Created a manifest (version 1.0)
> 3. Added the bucket to scoop
> 4. Installed app
> 5. Updated manifest file to version 1.1
> 6. git commit
> 7. scoop status => no updates
> 8. scoop update myapp => Latest versions for all apps are installed ...

You forgot to `git push`!

As an alternative, you can trying changing the manifest directly on GitHub. Then Scoop will pull the commit.

**Comment by Metal-Frog** [comment]
No, I've changed the file directly on GitHub - so no push ...

**Comment by rashil2000** [comment]
What is the output of `scoop --version`?

Is your bucket private or public?

**Comment by Metal-Frog** [comment]
Current Scoop version:
56020838 (HEAD -> master, tag: 2021-12-26, origin/master, origin/HEAD) fix(schema): Add 'license' definition (#4596)

'test' bucket:
d5d3a23 (HEAD -> master, origin/master, origin/HEAD) Update hello2.json

And it is private.

**Comment by rashil2000** [comment]
> And it is private.

Well, it's not supported yet. 

This is being tracked here - https://github.com/ScoopInstaller/Scoop/issues/4243

And there's a PR here - https://github.com/ScoopInstaller/Scoop/pull/4254

**Comment by HUMORCE** [comment]
example for add gh private bucket:
make sure: https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh
```
scoop bucket add <bucket> git@github.com:USERNAME/BUCKET.git
OR
cd <YOUR_BUCKET>
git remote set-url origin git@github.com:USERNAME/BUCKET.git
```
