### ISSUE TITLE
question for ``scoop list``

### ISSUE THREAD

**Issue by nibazshab** [ScoopInstaller/Scoop#4682]
#### Current Behavior
when ``scoop list``, it show ``xxx *global* [xx]`` and ``xxx [xx]``

#### Expected Behavior
how to delete ``xxx *global* [xx]``, just keep ``xxx [xx]``？

#### Additional context/output
![](https://user-images.githubusercontent.com/44338441/150573116-0940d32b-1df2-45e5-8ed0-c54ea2169208.png)

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** Major 5 , Minor 1 , Build 19041 , Revision 1320

**Additional software:**

#### Scoop Configuration

```json
{
    "lastupdate":  "258|2022-01-22 00:08:04",
    "SCOOP_REPO":  "https://gitee.com/glsnames/Scoop-Core",
    "SCOOP_BRANCH":  "master"
}
```

value of SCOOP environment variable: ``C:\ProgramData\scoop``

**Comment by rashil2000** [comment]
Fill the issue template.

And tell the value of SCOOP environment variable.

**Comment by nibazshab** [comment]
## Bug Report

#### Current Behavior
when ``scoop list``, it show ``xxx *global* [xx]`` and ``xxx [xx]``

#### Expected Behavior
how to delete ``xxx *global* [xx]``, just keep ``xxx [xx]``？

#### Additional context/output
![](https://user-images.githubusercontent.com/44338441/150573116-0940d32b-1df2-45e5-8ed0-c54ea2169208.png)

#### Possible Solution


### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** Major 5 , Minor 1 , Build 19041 , Revision 1320

**Additional software:**

#### Scoop Configuration


```json
{
    "lastupdate":  "258|2022-01-22 00:08:04",
    "SCOOP_REPO":  "https://gitee.com/glsnames/Scoop-Core",
    "SCOOP_BRANCH":  "master"
}
```

value of SCOOP environment variable: ``C:\ProgramData\scoop``
