### ISSUE TITLE
no help of ``scoop reset *``

### ISSUE THREAD

**Issue by nibazshab** [ScoopInstaller/Scoop#4684]
After reinstalling the system, i do as [#2894](https://github.com/ScoopInstaller/Scoop/issues/2894), i copy ``scoop`` to ``c:\user\x\``, and i add the ``Path`` and ``SCOOP``

but when i run ``scoop reset *``,i got
```
PS C:\Users\zuokan> scoop reset *
ERROR '7zip ()' isn't installed
ERROR 'clash ()' isn't installed
ERROR 'git ()' isn't installed
ERROR 'neteasemusic ()' isn't installed
ERROR 'steam ()' isn't installed
ERROR 'vscode ()' isn't installed
```
run ``scoop list``,got this
```
PS C:\Users\zuokan> scoop list
Installed apps:
  7zip  *failed*
  clash  *failed*
  git  *failed*
  neteasemusic  *failed*
  steam  *failed*
  vscode  *failed*
```
``SCOOP``: ``C:\User\zuokan\scoop``

**Windows version:** 10

**OS architecture:** 64

**PowerShell version:** Major 5 ,Minor 1 ,Build 22000 ,Revision 282

```json
{
    "lastupdate":  "2022-01-23T23:51:51.1889212+08:00",
    "SCOOP_REPO":  "https://gitee.com/glsnames/Scoop-Core",
    "SCOOP_BRANCH":  "master"
}
```

**Comment by rashil2000** [comment]
The fork of Scoop that you are using has diverged extremely far from upstream. I'm afraid we can't help you.

**Comment by nibazshab** [comment]
i think i have to reinstall again .😢

**Comment by rashil2000** [comment]
Is GitHub geoblocked in your location?

**Comment by nibazshab** [comment]
> Is GitHub geoblocked in your location?

yeah, sometimes i can user github all right , but often can't connect github

**Comment by rashil2000** [comment]
You can use Gitee to import https://github.com/ScoopInstaller/Scoop repo too

**Comment by nibazshab** [comment]
> You can use Gitee to import https://github.com/ScoopInstaller/Scoop repo too
> 
> Or use mirrors like fastgit etc.

ok, thanks

**Comment by rashil2000** [comment]
You can find more info here https://github.com/ScoopInstaller/Scoop/issues/4264

So I'll close this.

**Comment by fsdrw08** [comment]
I meet the same problem, may I know what should be the right process to backup and restore scoop apps for now? I using the method in https://github.com/ScoopInstaller/Scoop/issues/2894 to backup and restore my scoop apps in the past

**Comment by HUMORCE** [comment]
@fsdrw08

scoop export > installed_app.txt

then using this script to import: (used buckets need to be added manually)
https://gist.github.com/HUMORCE/1add93259ed5cbabd31e0c2bb28b4caf

**this is NOT an official tool/script and it is incomplete.**

**Comment by fsdrw08** [comment]
> 

Any method to backup and restore scoops apps offline? I used this script to backup and restore scoop apps offline before (remove all current folder and zip all files in scoop to a compressed file) https://github.com/fsdrw08/SysOps/blob/master/Scoop/Backup-Scoop.ps1
but now I got failed after I tried to and current folder back with `scoop reset *`

**Comment by HUMORCE** [comment]
@fsdrw08 
backup: (default path, if you have not set custom directory for them)
- `~\.config\scoop\config.json`
- `~\scoop`
- `C:\ProgramData\scoop` // If you have not global apps, unnecessary
- environment variables // if you have not set it for Scoop, unnecessary

restore:
1. install scoop
2. replace backups to same path
3. `scoop update`
4. `scoop reset *`

if you switch back to Scoop from Shovel, you need to rename all `SCOOP\apps\APP\current\scoop-install.json` and `SCOOP\apps\APP\current\scoop-manifest.json` to `install.json`/`manifest.json`, then `scoop reset` work again.
