### ISSUE TITLE
[Bug] Scoop Wiki links broken

### ISSUE THREAD

**Issue by redactedscribe** [ScoopInstaller/Scoop#4686]
#### Current Behavior
Visiting links on https://github.com/ScoopInstaller/Scoop/wiki, such as the one for App Manifests, link back to the mentioned URL. The links contain `/wiki/wiki/`, e.g. https://github.com/ScoopInstaller/Scoop/wiki/wiki/App-Manifests, which seems to be the problem.

**Comment by rashil2000** [comment]
I'm not able to find such links. Can you paste a screenshot?

**Comment by redactedscribe** [comment]
I think this was user error (manually editing the URL).

The bug only occurs when visiting https://github.com/ScoopInstaller/Scoop/wiki/ not https://github.com/ScoopInstaller/Scoop/wiki (the former has a trailing `/`).

Screenshot:
![scoop_wiki](https://user-images.githubusercontent.com/25013746/150941317-effb2a22-2e06-43bb-a210-7a9a984011d0.jpg)

**Comment by niheaven** [comment]
Fixed, thanks.
