### ISSUE TITLE
Rename storageexplorer to azure-storageexplorer

### ISSUE THREAD

**Issue by Anselmoo** [ScoopInstaller/Scoop#4693]
#### Is your feature request related to a problem? Please describe.
 It would be nice and more consistent if `Azure`-related software also includes the name `azure` as a prefix for faster searching.

#### Describe the solution you'd like
`storageexplorer` to `azure-storageexplorer` or `azure-storage-explorer`

#### Describe alternatives you've considered

or `azure-storage-explorer`

**Comment by rashil2000** [comment]
Please create this issue in the relevant bucket. This tracker is for the package manager itself, not packages.
