### ISSUE TITLE
Uninstall gow in main bucket also remove some features in coreutils.

### ISSUE THREAD

**Issue by hungpham3112** [ScoopInstaller/Scoop#4700]
#### Current Behavior
```
Try to reproduce: 
scoop install coreutils
touch <some.file> -> it OK.
scoop install gow
scoop uninstall gow
touch <some.anotherfile> -> will raise error
```

#### Expected Behavior
` gow `and `coreutils` have same tools like` vim `and `touch`. When uninstall gow, I suppose that I still can use touch from coreutils

#### Additional context/output
It seems like when installing 2 or more packages have same tool, for instance: touch, ls, vim...  Scoop will share the same `shim file` or `shim link`? I don't know. So that when you uninstall 1 off them the rest will lose some features. It look like the `double free` in `C programming lang`

### System details

**Windows version:**  11

**OS architecture:** 64bit

**PowerShell version:** 
```
Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      2      1
```

#### Scoop Configuration
```json
{
  "lastupdate": "2022-01-30T09:54:08.0971711+07:00",
  "SCOOP_REPO": "https://github.com/ScoopInstaller/Scoop",
  "SCOOP_BRANCH": "master",
  "alias.reinstall": "scoop uninstall {0}; scoop install {0}",
  "alias": {}
}

```

**Comment by rasa** [comment]
`scoop reset coreutils` or
`scoop reset *`
will restore the missing shims.

**Comment by rashil2000** [comment]
This is expected behaviour (not a bug). When you install `gow` _after_ `coreutils`, it will overwrite shims with the same name. As @rasa suggested, run **scoop reset coreutils** after uninstalling `gow` to restore the shims.
