### ISSUE TITLE
Use scoop uninstall scoop raise "access is denied".

### ISSUE THREAD

**Issue by hungpham3112** [ScoopInstaller/Scoop#4701]
#### Current Behavior
Trying to uninstall scoop with ` scoop uninstall scoop ` and see those messages:

![image](https://user-images.githubusercontent.com/75968004/151732134-fec82747-8e42-4d83-91fc-b65933c703d5.png)

#### Expected Behavior
`scoop uninstall scoop` removes scoop and related information.

#### Additional context/output
If I remove package 1 by 1, finally remove scoop, it will works.

#### Possible Solution
I have no idea, I just used scoop for 1 week.
### System details

**Windows version:**: 11

**OS architecture:**: 64bit

**PowerShell version:**:

Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      2      1
**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
{
  "lastupdate": "2022-01-31T09:39:29.9450785+07:00",
  "SCOOP_REPO": "https://github.com/ScoopInstaller/Scoop",
  "SCOOP_BRANCH": "master",
  "alias.reinstall": "scoop uninstall {0}; scoop install {0}",
  "alias": {}
}
```

**Comment by HUMORCE** [comment]
Scoop does not have a complete self-uninstaller, If you want a complete uninstallation of Scoop:

remove these directories.
- C:\Users\\\<USERNAME>\scoop
- C:\ProgramData\scoop
- C:\Users\\\<USERNAME>\\.config\scoop

remove any paths from $PATH that starts with them: 
- C:\Users\\\<USERNAME>\scoop\
- C:\ProgramData\scoop\

if custom directory and environment variable is sets, then remove them too.
https://github.com/ScoopInstaller/Scoop/wiki/Quick-Start#installing-scoop-to-custom-directory

**Comment by rashil2000** [comment]
I just tried this on a fresh install:

![Screenshot 2022-02-20 024706](https://user-images.githubusercontent.com/46838874/154838375-638ebbc1-9b87-4791-a843-21006139f278.png)

In this case the persist folder is left behind. Everything else is cleaned.

To remove the persist folder too, the command is `scoop uninstall scoop --purge`

**Comment by hungpham3112** [comment]
> I just tried this on a fresh install:
> 
> ![Screenshot 2022-02-20 024706](https://user-images.githubusercontent.com/46838874/154838375-638ebbc1-9b87-4791-a843-21006139f278.png)
> 
> In this case the persist folder is left behind. Everything else is cleaned.
> 
> To remove the persist folder too, the command is `scoop uninstall scoop --purge`

![image](https://user-images.githubusercontent.com/75968004/155247153-5752147e-a330-4e4e-a7ea-c70bf0f4f629.png)

I still get error today. What is Access is denied? I'm the admin of this computer, how is this possible.

**Comment by hungpham3112** [comment]
> > I just tried this on a fresh install:
> > ![Screenshot 2022-02-20 024706](https://user-images.githubusercontent.com/46838874/154838375-638ebbc1-9b87-4791-a843-21006139f278.png)
> > In this case the persist folder is left behind. Everything else is cleaned.
> > To remove the persist folder too, the command is `scoop uninstall scoop --purge`
> 
> ![image](https://user-images.githubusercontent.com/75968004/155247153-5752147e-a330-4e4e-a7ea-c70bf0f4f629.png)
> 
> I still get error today. What is Access is denied? I'm the admin of this computer, how is this possible.

I thinks this is my fault because I tried to uninstall scoop in another machine and it's worked fine. But I don't know how t fix that, seem like every file I want to remove say access is denied. Maybe my account not admin?

**Comment by hungpham3112** [comment]
> > > I just tried this on a fresh install:
> > > ![Screenshot 2022-02-20 024706](https://user-images.githubusercontent.com/46838874/154838375-638ebbc1-9b87-4791-a843-21006139f278.png)
> > > In this case the persist folder is left behind. Everything else is cleaned.
> > > To remove the persist folder too, the command is `scoop uninstall scoop --purge`
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/75968004/155247153-5752147e-a330-4e4e-a7ea-c70bf0f4f629.png)
> > I still get error today. What is Access is denied? I'm the admin of this computer, how is this possible.
> 
> I thinks this is my fault because I tried to uninstall scoop in another machine and it worked fine. But I don't know how t fix that, it seems like every file I want to delete says access is denied. Maybe my account is not admin?
> 
> ![image](https://user-images.githubusercontent.com/75968004/155248214-e15c9a48-85e9-4a95-a04c-e9b9fa70fc2b.png)

Ok, finally I found it. `Scoop\Window~1\` is being used by other process so it can't delete. What is `scoop\window~1\`. I didn't download it to this machine. 

![image](https://user-images.githubusercontent.com/75968004/155249086-4c22cdbb-6186-48ed-9a7e-b2ba2936cad2.png)

**Comment by rashil2000** [comment]
Have you installed Windows Terminal through scoop?

In that case you need to close it and run the command in plain cmd.exe terminal.

**Comment by hungpham3112** [comment]
> Have you installed Windows Terminal through scoop?
> 
> In that case you need to close it and run the command in plain cmd.exe terminal.

I didn't open it. Those processes run in background.

**Comment by rashil2000** [comment]
You need to completely close Windows Terminal (and disable automatic startup at boot in Windows Terminal settings).

**Comment by hungpham3112** [comment]
> You need to completely close Windows Terminal (and disable automatic startup at boot in Windows Terminal settings).

Oh, my fault sorry, It not cause by window terminal, actually it's winfetch. Winfetch still use .dll file in the background. You can check it.

**Comment by rashil2000** [comment]
The best option would be to reboot the computer (after disabling auto start). Then use the cmd.exe terminal.
