### ISSUE TITLE
[Bug] checkver.ps1 's -Dir is a complusory parameter

### ISSUE THREAD

**Issue by zStruCat** [ScoopInstaller/Scoop#4702]
According to the [wiki:](https://github.com/ScoopInstaller/Scoop/wiki/App-Manifest-Autoupdate#querying-current-version)

```
# To query the current version of a specific app in the bucket, run:
.\bin\checkver.ps1 <app>
# or .\bin\checkver.ps1 -App <app>
```
In which -Dir Parameter isn't mandatory.

Yet in the [source code](https://github.com/ScoopInstaller/Scoop/blob/1dbab1fee8e8d775fc06248d2a3301d633c580a1/bin/checkver.ps1#L51)：
```
param(
    [String] $App = '*',
###
    [Parameter(Mandatory = $true)]
###
    [ValidateScript( {
        if (!(Test-Path $_ -Type Container)) {
            throw "$_ is not a directory!"
        } else {
            $true
        }
    })]
```

Which is an obstacle to me when trying to test the autoupdate of my manifest

**Comment by rashil2000** [comment]
This is not a bug. You need to be in the git root of the bucket your app is in. If not, only then `Dir` is necessary. What is the error you are seeing?

**Comment by zStruCat** [comment]
You are right, I misunderstood the point.
