### ISSUE TITLE
[Bug] Unable to run uninstaller script if any app is running

### ISSUE THREAD

**Issue by CrendKing** [ScoopInstaller/Scoop#4710]
## Bug Report

I'm trying to create a manifest for https://github.com/sandboxie-plus/Sandboxie. This app installs two services when runs.

In order to perform scoop update or uninstall, I put something like `Stop-Process sandboxie` in the scoop uninstaller script. However, the script doesn't even run because of the error message:
```
$ scoop uninstall sandboxie
Uninstalling 'sandboxie' (1.0.9).
ERROR Application is still running. Close all instances and try again.
```
I think this is originally due to https://github.com/ScoopInstaller/Scoop/pull/3608. I understand the scoop wants user to terminate the process explicitly to avoid data loss, but in this case simply terminating the main process is not enough, because the services also needs stopping (fortunately Sandboxie provides an utility to easily do that).

#### Current Behavior

Scoop refuses to uninstall if any process from the app directory is running, regardless what happens in uninstaller script.

#### Expected Behavior

The manifest should has some power to control how to perform uninstallation when the processes are running.

#### Additional context/output

See above.

#### Possible Solution

Ideally the manifest author can change the existing behavior by specifying some option. With that, when scoop detects process running, instead of immediately error out, it prompts user "Do you want to proceed uninstallation of <app_name>? All unsaved data will be lost [y/N]" When user confirms, it performs the uninstaller script as usual. On the other hand, if scoop does not detects process running, nothing will change from existing logic.

By implementing this, manifest authors can streamlining the update/uninstall procedure by properly implementing uninstaller script. Most of the cases a simple `Stop-Process app_name` is needed.

Basically, instead of the current
```
if (Get-Process | Where-Object { $_.Path -like "$processdir\*" }) {
    error "Application is still running. Close all instances and try again."
    continue
}
```
do something like this
```
if ((Get-Process | Where-Object { $_.Path -like "$processdir\*" }) -and
    (Read-Host "Do you want to proceed uninstallation of '$app'? All unsaved data will be lost [y/N]") -ne 'y') {
    error "Application is still running. Close all instances and try again."
    continue
}
```

### System details

**Windows version:** Windows 11

**OS architecture:** 64bit

**PowerShell version:** 7.2.1

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
{
  "SCOOP_REPO": "https://github.com/ScoopInstaller/Scoop",
  "SCOOP_BRANCH": "master",
  "shim": "kiennq",
  "aria2-warning-enabled": false
}
```

**Comment by rashil2000** [comment]
```
if ((Get-Process | Where-Object { $_.Path -like "$processdir\*" }) -and
    (Read-Host "Do you want to proceed uninstallation of '$app'? All unsaved data will be lost [y/N]") -ne 'y') {
    error "Application is still running. Close all instances and try again."
    continue
}
```

This won't really do anything, right? You still need to close the programs manually. Scoop will not close them under any circumstances. 

For services, I agree that the handling could be better. That is being tracked in https://github.com/ScoopInstaller/Scoop/issues/3412 and https://github.com/ScoopInstaller/Scoop/issues/1526. So I'm closing this as duplicate.

**Comment by CrendKing** [comment]
If user answers "y", the `if` will be false, the whole block is skipped, and the `run_uninstaller` below will have chance to run.

Normal services might be handled by the two issues you linked, but it does not cover all cases, such as Sandboxie. In addition to a normal "SbieSvc" service, it also registers a driver service "SbieDrv", which can't be stopped by either `Stop-Service` or `sc`. The app provides a "kmdutil" utility to handle the driver operations.

I didn't mention all these details at beginning because I don't want to complicate the discussion. What I'm trying to say is, I wholeheartedly welcome a support for service in Scoop, but there will always be some corner cases. Giving manifest author a way to handle these rare cases might be valuable.

**Comment by rashil2000** [comment]
I see.

Can you make a PR for the Read-Host prompt?

**Comment by CrendKing** [comment]
https://github.com/ScoopInstaller/Scoop/pull/4712
