### ISSUE TITLE
[Feature] Install an APP from a specific local bucket

### ISSUE THREAD

**Issue by tan-wei** [ScoopInstaller/Scoop#4724]
#### Is your feature request related to a problem? Please describe.

Suppose an APP (may be with the same name but they are not exactly the same) exists in at least two local buckets, simply use `scoop install xxx` will just select a random one to install. A workaound to solve this is to install the APP with manifest JSON file with `scoop install C:\foo\bar\xxx.json`.

However, it seems that, we can't update the APP with `scoop update *`. Is that true?
#### Describe the solution you'd like

 If not supported, how about adding the feature which lets the usre install an APP from a specific local bucket? For example, `scoop install xxx[bucket_name]`.

**Comment by niheaven** [comment]
You could use `scoop install <bucket/app>` to install specific apps.

If you install an app from local manifest and the manifest has been updated, you could update the app by `scoop update *`.
