### ISSUE TITLE
[Bug] Exception calling "DownloadFile" with "2" argument(s): "An error occurred while sending the request."  

### ISSUE THREAD

**Issue by pan102887** [ScoopInstaller/Scoop#4739]
#### Current Behavior  

when I tried to run the following script, and the following error occurred.

1. environment  

    > system: windows11  
    > shell: powershell 7  
    > ExecutionPolicy: RemoteSigned  
    > $env:SCOOP: ~\scoop  

2. erro log  

    > PS C:\Users\jupeter\source\xp-lark\xp-lark-common> iwr -useb get.scoop.sh | iex  
    > Initializing...  
    > Downloading scoop...  
    > Invoke-Expression: Exception calling "DownloadFile" with "2" argument(s): "An error occurred while sending the request."  

3. analysis  
the erro seems occurred when install.ps1 try to run `dl` command to download file  

    ```ps1
    # download scoop zip
    $zipurl = 'https://github.com/ScoopInstaller/Scoop/archive/master.zip'
    $zipfile = "$dir\scoop.zip"
    Write-Output 'Downloading scoop...'
    dl $zipurl $zipfile
    # here is intall.ps1 line 47
    ```  

so I tried ran the following command to Repetition  
```ps
PS C:\Users\jupeter> $zipurl = 'https://github.com/ScoopInstaller/Scoop/archive/master.zip'
PS C:\Users\jupeter> $zipfile = "$dir\scoop.zip"
PS C:\Users\jupeter> dl $zipurl $zipfile
ParentContainsErrorRecordException:
Line |
466  |      $wc.downloadFile($url,$to)
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "DownloadFile" with "2" argument(s): "An error occurred while sending the request."  
```

### System details

**Windows version:** 11

**OS architecture:** 64bit

**PowerShell version:**

|Major|  Minor | Patch | PreReleaseLabel| BuildLabel|
|-----|  -----  |----- | ---------------| ----------|
|7 |     2 |     1|

#### Scoop Configuration

cannot find anythings or path like "\~/.config/scoop/config.json", the only folder that the name contain "scoop" is "~/scoop"

**Comment by rashil2000** [comment]
Do not use tilde (~). It is not a recognized symbol in .NET methods. Use full path, or UserProfile environment variable.

**Comment by pan102887** [comment]
> Do not use tilde (~). It is not a recognized symbol in .NET methods. Use full path, or UserProfile environment variable.

The problem was solved, thank you
