### ISSUE TITLE
[Bug] Error in updating 'extra' bucket

### ISSUE THREAD

**Issue by lepicsaintloup** [ScoopInstaller/Scoop#4740]
#### Current Behavior
```
Updating Scoop...
Updating 'extras' bucket...
error: Your local changes to the following files would be overwritten by merge:
        bucket/ytsubconverter.json
Please commit your changes or stash them before you merge.
Aborting
```

### System details

**Windows version:**  10

**OS architecture:**  64bit

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]

**Additional software:**  ConEmu

#### Scoop Configuration

```json
{
  "SCOOP_BRANCH": "master",
  "SCOOP_REPO": "https://github.com/lukesampson/scoop",
  "lastupdate": "2022-02-16T07:58:11.6907647+11:00"
}

```

**Comment by rashil2000** [comment]
```
scoop bucket rm extras
scoop bucket add extras
```

**Comment by niheaven** [comment]
cd to your extras bucket folder, then:

```console
git restore .
git clean -f
```

If the above command doesn't help, try @rashil2000's

**Comment by lepicsaintloup** [comment]
The @rashil2000 soluton worked thank you.

**Comment by rashil2000** [comment]
@niheaven should we remove the following line from all buckets? I think it is the reason for this. https://github.com/ScoopInstaller/Extras/blob/063bccd11a7e3df58bb4c3930b3a35afd6443e0a/.gitattributes#L2

**Comment by niheaven** [comment]
AppVeyor check CRLF and the file pass that test, so what's wrong with `bucket/ytsubconverter.json`?

**Comment by rashil2000** [comment]
Maybe UTF-16 instead of UTF-8?

**Comment by niheaven** [comment]
Maybe some fixes on https://github.com/ScoopInstaller/Scoop/blob/5602083868ed04224ea8edf1ff0c3a2a3f6588b9/test/Import-File-Tests.ps1#L25-L48
