### ISSUE TITLE
[Bug] Shims miss path quotes " 

### ISSUE THREAD

**Issue by kpolitis-msim** [ScoopInstaller/Scoop#4749]
### System details

**Windows version:** [e.g. 7, 8, 10]

**OS architecture:** [e.g. 32bit, 64bit]

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
//# Your configuration here
```

**Comment by rashil2000** [comment]
#4728
