### ISSUE TITLE
[Bug] checkurls treats "302 Found" as a failure

### ISSUE THREAD

**Issue by beyondmeat** [ScoopInstaller/Scoop#4768]
#### Current Behavior
checkurls will fail on 302 Found

#### Expected Behavior
302 is treated as OK

#### Additional context/output
when running checkurls.ps1 against a manifest

#### Possible Solution
include 302 where you check for 200

### System details
N/A
**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration
N/A

**Comment by niheaven** [comment]
Could you provide some URLs to test?

**Comment by rashil2000** [comment]
Closing due to no feedback...
