### ISSUE TITLE
[Feature] Scoop for Linux

### ISSUE THREAD

**Issue by lucypero** [ScoopInstaller/Scoop#4771]
#### Is your feature request related to a problem? Please describe.

No

#### Describe the solution you'd like

I'd like to have Scoop for Linux, as I use WSL. Scoop is better than every Linux package manager that I've tried.

#### Describe alternatives you've considered

Maybe the Nix package manager is similar.

**Comment by piq9117** [comment]
scoop is the package manage of the lord :pray:

**Comment by rashil2000** [comment]
Duplicate of https://github.com/ScoopInstaller/Scoop/issues/2137

Would love to see it happen. Though not difficult, it will still be a huge effort.
