### ISSUE TITLE
aria2 proxy

### ISSUE THREAD

**Issue by Vzz1c** [ScoopInstaller/Scoop#4781]
I set it via the system environment variable
http_proxy=socks5://x.x.x.x:xxxx
I have set the proxy for aria2

Some of these configurations:
"proxy":  "none",
 "aria2-options": [
                          "--all-proxy=\"http://x.x.x.x:xxxx\""
                      ]

I have tested the correct configuration of aria2 agent, but because I configured the system environment variables and the following problem, I delete the system environment variables will not have this error, how do I do it

```
Starting download with aria2 ...
Caught Error while parsing environment variable 'http_proxy'
Exception: [AbstractOptionHandler.cc:69] errorCode=28 We encountered a problem while processing the option '--http-proxy'.
  -> [OptionHandlerImpl.cc:520] errorCode=1 unrecognized proxy format

Caught Error while parsing environment variable 'https_proxy'
Exception: [AbstractOptionHandler.cc:69] errorCode=28 We encountered a problem while processing the option '--https-proxy'.
  -> [OptionHandlerImpl.cc:520] errorCode=1 unrecognized proxy format
```

**Comment by HUMORCE** [comment]
> unrecognized proxy format

aria2 does not support SOCKS proxy.
