### ISSUE TITLE
[Bug] Shim path with umlauts is not encoded in utf-8

### ISSUE THREAD

**Issue by kunago** [ScoopInstaller/Scoop#4784]
#### Current Behavior

Often when I try to run commands I receive an error because of the path. My username contains a space and umlauts. Unfortunately scoop does not seem to use utf-8 or so it seems. So instead of "á" in the username in the path I see a question mark instead which obviously results in an error. This is a current issue, I guess a month old.

#### Expected Behavior

I expect the path to be encoded correctly with umlauts as well.

#### Additional context/output

```
PS C:\Users\Peter Novám> scoop bucket list
Could not create process with command 'C:\Users\Peter Nov?k\scoop\apps\git\current\cmd\git.exe  -C "C:\Users\Peter Novßk\scoop\buckets\extras" log --format=%aD -n 1'.
Could not create process with command 'C:\Users\Peter Nov?k\scoop\apps\git\current\cmd\git.exe  -C "C:\Users\Peter Novßk\scoop\buckets\extras" config remote.origin.url'.
Could not create process with command 'C:\Users\Peter Nov?k\scoop\apps\git\current\cmd\git.exe  -C "C:\Users\Peter Novßk\scoop\buckets\games" log --format=%aD -n 1'.
Could not create process with command 'C:\Users\Peter Nov?k\scoop\apps\git\current\cmd\git.exe  -C "C:\Users\Peter Novßk\scoop\buckets\games" config remote.origin.url'.
Could not create process with command 'C:\Users\Peter Nov?k\scoop\apps\git\current\cmd\git.exe  -C "C:\Users\Peter Novßk\scoop\buckets\java" log --format=%aD -n 1'.
Could not create process with command 'C:\Users\Peter Nov?k\scoop\apps\git\current\cmd\git.exe  -C "C:\Users\Peter Novßk\scoop\buckets\java" config remote.origin.url'.
Could not create process with command 'C:\Users\Peter Nov?k\scoop\apps\git\current\cmd\git.exe  -C "C:\Users\Peter Novßk\scoop\buckets\nirsoft" log --format=%aD -n 1'.
Could not create process with command 'C:\Users\Peter Nov?k\scoop\apps\git\current\cmd\git.exe  -C "C:\Users\Peter Novßk\scoop\buckets\nirsoft" config remote.origin.url'.
Could not create process with command 'C:\Users\Peter Nov?k\scoop\apps\git\current\cmd\git.exe  -C "C:\Users\Peter Novßk\scoop\buckets\versions" log --format=%aD -n 1'.
Could not create process with command 'C:\Users\Peter Nov?k\scoop\apps\git\current\cmd\git.exe  -C "C:\Users\Peter Novßk\scoop\buckets\versions" config remote.origin.url'.

Name     Source Updated Manifests
----     ------ ------- ---------
extras                       1430
games                         215
java                          220
nirsoft                       266
versions                      278
```

### System details

**Windows version:** [e.g. 7, 8, 10]
Windows 11

**OS architecture:** [e.g. 32bit, 64bit]
64bit

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]
```
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      22000  282
```

**Additional software:** [(optional) e.g. ConEmu, Git]
I also use conemu but in this case it happens also with pure PowerShell

#### Scoop Configuration

```json
{
    "lastupdate":  "2022-03-08T09:11:13.4293955+01:00",
    "SCOOP_REPO":  "https://github.com/lukesampson/scoop",
    "SCOOP_BRANCH":  "master"
}

```

**Comment by HUMORCE** [comment]
```
PS C:\Users\Peter Novßk> cat ~\scoop\shims\git.shim
path = "C:\Users\Peter Nov?k\scoop\apps\git\current\cmd\git.exe"
```

/cc @niheaven

**Comment by kunago** [comment]
Yes, apparently, that is what is in the shim. It is in all shims so the questions is whether there needs to be some encoding changed or turned on.

**Comment by rashil2000** [comment]
Did you face this issue just today or before today also?

**Comment by kunago** [comment]
Otehr days as well. I noticed for the first time a few weeks ago when using adb which needed to be launched directly from the dir to bypass the wrong shim path. As of today, it started happening with other commands too.

**Comment by niheaven** [comment]
We have `Out-UTF8File` now, but it doesn't support `-Append` so I haven't replaced `Out-File` in shim creation. Will be fixed in 'develop' and may in next main release.

**Comment by rashil2000** [comment]
Similar issues:
- https://github.com/ScoopInstaller/Scoop/issues/2573
- https://github.com/ScoopInstaller/Scoop/issues/2230

**Comment by chawyehsu** [comment]
@kunago @HUMORCE Could you please type `$OutputEncoding` and paste the result?

**Comment by HUMORCE** [comment]
![screenshot_20220309091632](https://user-images.githubusercontent.com/4353480/157410882-60ab8183-455b-4779-91f4-c79853b076d0.png)


```
PS C:\Users\Peter Novßk> $OutputEncoding

IsSingleByte      : True
BodyName          : us-ascii
EncodingName      : US-ASCII
HeaderName        : us-ascii
WebName           : us-ascii
WindowsCodePage   : 1252
IsBrowserDisplay  : False
IsBrowserSave     : False
IsMailNewsDisplay : True
IsMailNewsSave    : True
EncoderFallback   : System.Text.EncoderReplacementFallback
DecoderFallback   : System.Text.DecoderReplacementFallback
IsReadOnly        : True
CodePage          : 20127
```

i simply created a user with samename as @kunago in the VM.

**Comment by kunago** [comment]
As it seems, I am uble to run "scoop" from cmd with powershell at the beginning. While simply running ```scoop``` returns the invalid path error, running ```powershell scoop``` passes fine. I am update, see the status of apps and use all other scoop commands.

The problem can be partially solved this way which is the way I am using now to run scoop.

However, the umlauts in *.shim files returns an error anytime running any other app from the command line. For instance running ```php``` from the command line, which was previously installed with scoop, once again returns the error, and regardless whether I run it with ```php``` or ```powershell php```.

Do you know of a workaround for this use case?

**Comment by niheaven** [comment]
Wait for scoop version bump, and reset all your shims may help. And if bugs are still there, please report again.
