### ISSUE TITLE
[Bug] or not? Scoop cleanup /* -k -g remove all download cache.

### ISSUE THREAD

**Issue by ustsv** [ScoopInstaller/Scoop#4788]
#### Current Behavior
```
C:\tmp>scoop cleanup * -k -g
Everything is shiny now!
C:\tmp>scoop cleanup /* -k -g
Removing /*: 7zip 7zip-zstd aida64engineer aimp android-sdk android-studio apache ...skip... youtube-dl zeal
```

Remove all, old and last download cache. Not installed too.

#### Possible Solution
Check input argument or add documentation?

### System details

**Windows version:** 7sp1

**OS architecture:** 64bit

**PowerShell version:** Major  Minor  Build  Revision
5      1      14409  1018

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
//# Your configuration here
```

**Comment by rashil2000** [comment]
I did not understand the issue. What documentation change is needed?

**Comment by HUMORCE** [comment]
> I did not understand the issue.

no exception handling for unexpected input.

**Comment by rashil2000** [comment]
Oh, and how to handle it?

**Comment by HUMORCE** [comment]
determine the starting character of the `$apps` param?

```
@('\', '/', '*', '?', '"', '<', '>', '|')
```

**Comment by rashil2000** [comment]
I'm not against exception handling, but it seems like a very unusual behaviour to me. Why would you add a forward slash before the asterisk? It's not even an escape character.

**Comment by rashil2000** [comment]
Closing due to lack of feedback
