### ISSUE TITLE
[Bug] No longer installs arrays of packages?

### ISSUE THREAD

**Issue by lorengordon** [ScoopInstaller/Scoop#4789]
#### Current Behavior

Scoop no longer installs packages specified as a powershell array.

```
❯ $ScoopPackages = @("7zip", "direnv")
❯ scoop install $ScoopPackages
```

#### Expected Behavior

Prior to today, it used to work.

```
❯ $ScoopPackages = @("7zip", "direnv")
❯ scoop install $ScoopPackages
WARN  '7zip' (21.07) is already installed. Skipping.
WARN  'direnv' (2.30.3) is already installed. Skipping.
```

### System details

**Windows version:** 11

**OS architecture:** 64bit

**PowerShell version:** 7.2.1

#### Scoop Configuration

```json
{
  "lastupdate": "2022-03-08T06:32:31.3702338-08:00",
  "alias": {},
  "SCOOP_REPO": "https://github.com/lukesampson/scoop",
  "SCOOP_BRANCH": "master",
  "aria2-enabled": false
}
```

**Comment by rashil2000** [comment]
Can you go to ~\scoop\apps\scoop\current folder and find the commit where it stopped working? There haven't been a lot of changes to `scoop install`.

**Comment by lorengordon** [comment]
oh, let me check how that works, i didn't know that was a thing

**Comment by rashil2000** [comment]
Basically, you will do a `git bisect`. Here's a guide on how to do it: https://flaviocopes.com/git-bisect/

**Comment by lorengordon** [comment]
I don't feel like I'm doing that right. I can go back 2 years of commits and it still doesn't work. But we rebuild this system every day and it was working fine until this morning, installing from `Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')`.

**Comment by rashil2000** [comment]
To be honest I wasn't aware that passing arrays like that ever worked. It has been asked as a feature request here, but wasn't implemented. My personal workaround has been using `Invoke-Expression "scoop $subcommand $($apps -join ' ') $subcommandflags"`

**Comment by lorengordon** [comment]
Heh, and I just assumed that since scoop was powershell, that native things like arrays ought to "just work", so we never did anything else. But that workaround is fine for me. I always forget about using Invoke-Expression like that.

Since we started using scoop several months ago, the array approach was working for us. Not exactly sure what changed such that it suddenly stopped. Below is our larger setup... Until this morning (presumably a result the 0.1.0 release?), it was working fine:

```
# Install Scoop
Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh/')
scoop install aria2
scoop config aria2-warning-enabled false
scoop install --global 7zip git  # Needed to manage buckets and update scoop
scoop bucket add extras
scoop bucket add java
scoop update

# Packages to install with Scoop
$ScoopPackages = @(
    "atom",
    "aws",
    "firefox",
    "googlechrome",
    "mobaxterm",
    "nodejs-lts",
    "notepadplusplus",
    "openjdk",
    "openssh",
    "putty",
    "python",
    "shellcheck",
    "slack",
    "vscode"
)

# Deps needed for python. Need to silence output from lessmsi since it has non-ASCII characters
scoop install --global lessmsi 6> $null
scoop install --global dark

# Install packages with Scoop
scoop install --global $ScoopPackages

# Test scoop packages
Invoke-Expression "scoop list" -InformationVariable ScoopList
foreach ($Package in $ScoopPackages + @("git", "7zip")) {
    if (-not "$ScoopList".Contains($Package)) {
        Write-Error "Failed to install Scoop package: $Package"
    } else {
        Write-Verbose "Found Scoop package: $Package"
    }
}
```

As of this morning, we've had to adjust a couple things to get it to build...

```diff
@@ -319,13 +319,13 @@ scoop install --global lessmsi 6> $null
 scoop install --global dark

 # Install packages with Scoop
-scoop install --global $ScoopPackages
+Invoke-Expression "scoop install --global $($ScoopPackages -join ' ')"

 # Test scoop packages
-Invoke-Expression "scoop list" -InformationVariable ScoopList
+Invoke-Expression "scoop list" -OutVariable ScoopList
 foreach ($Package in $ScoopPackages + @("git", "7zip")) {
-    if (-not "$ScoopList".Contains($Package)) {
-        Write-Error "Failed to install Scoop package: $Package"
+    if (-not $ScoopList.Name.Contains($Package)) {
+        Write-Error "ERROR: Failed to install Scoop package: $Package"
     } else {
         Write-Verbose "Found Scoop package: $Package"
     }
```

**Comment by lorengordon** [comment]
Right, the changes to `scoop list` made sense. The output is much nicer now, more useable. I think I was tracking a related issue to that, so I was expecting that to change eventually.

The only thing that surprised me, and that seemed like a regression, was that our prior call to `scoop install $ScoopPackages` suddenly stopped working also. But you're saying it was never intended to be working with an array, so I guess it's not really a regression. Feel free to close the issue in that case, or leave it open if you want this issue to stand in as a feature request. But the workaround is sufficient for me, we're now unblocked. Thanks for responding so quickly!
