### ISSUE TITLE
[Bug] `scoop prefix` not working for global installs

### ISSUE THREAD

**Issue by sitiom** [ScoopInstaller/Scoop#4790]
## Bug Report
Starting [0.1.0](https://github.com/ScoopInstaller/Scoop/releases/tag/v0.1.0), `scoop prefix <app>` fails to find the path if the app is installed globally.

#### Current Behavior
`scoop prefix <app>` does not work if the app is installed globally.

#### Expected Behavior
It should work.

#### Additional context/output

```console
$ scoop list
Installed apps:

Name                       Version             Source                                                       Updated             Info
----                       -------             ------                                                       -------             ----
7zip                       21.07               main                                                         2022-03-04 14:03:47
scoop-completion           0.2.3               extras                                                       2022-03-04 14:03:53
aria2                      1.36.0-1            main                                                         2022-03-04 14:03:49 Global install
neovim                     0.6.1               main                                                         2022-03-04 14:03:52 Global install

$ scoop prefix neovim
Could not find app path for 'neovim'.
```

### System details

**Windows version:** [e.g. 7, 8, 10]
11

**OS architecture:** [e.g. 32bit, 64bit]
64bit

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]
7.2.1

#### Scoop Configuration

```json
{
  "lastupdate": "2022-03-09T15:18:49.3892465+08:00",
  "SCOOP_REPO": "https://github.com/ScoopInstaller/Scoop",
  "SCOOP_BRANCH": "master",
  "aria2-warning-enabled": false
}
```

**Comment by rashil2000** [comment]
Responsible commit: https://github.com/ScoopInstaller/Scoop/commit/285ffd03222ec7497cf5f359fd08db6536627d18#diff-b86556b90396fd186838988e9b31aed17fac56b0d40a453198e971b9c3480b7c

Another regression caused by https://github.com/ScoopInstaller/Scoop/pull/4722

/cc @niheaven

**Comment by rashil2000** [comment]
We have no way to know 😅

**Comment by test210820** [comment]
Is there any progress on this issue?

**Comment by sitiom** [comment]
> Is there any progress on this issue?

The answer is just two comments up https://github.com/ScoopInstaller/Scoop/issues/4790#issuecomment-1063141481.
