### ISSUE TITLE
[Bug] [Dev] Skipping chores in logs not working

### ISSUE THREAD

**Issue by rashil2000** [ScoopInstaller/Scoop#4799]
![image](https://user-images.githubusercontent.com/46838874/157601042-bb9a76ff-3fdc-4bde-af3a-93a53e3ad149.png)

Feature added to `develop` branch in https://github.com/ScoopInstaller/Scoop/pull/4672

**Comment by rashil2000** [comment]
Current implementation works when the log "starts with **chore**". But what if app's name starts with **chore**?

**Comment by niheaven** [comment]
Oh, it's started with `chore`, no parentheses.

For an app started with `chore`, add whitespaces before it? Though ugly, it works.

**Comment by niheaven** [comment]
Or change the filter to `(chore)`? Both okay.

**Comment by rashil2000** [comment]
> Or change the filter to `(chore)`? Both okay.

This should be better in the long run
