### ISSUE TITLE
[Bug] scoop list not work in windows 11 cmd

### ISSUE THREAD

**Issue by changxinjie** [ScoopInstaller/Scoop#4801]
#### Current Behavior

![image](https://user-images.githubusercontent.com/9565184/157626308-3b45bfdb-712b-41f5-8f97-7109f89e281d.png)

### System details

Windows 11 Enterprise Edition (Build 22543), 64-bit

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]

works well.   version:  5.1.22543.1000

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json

{
    "SCOOP_BRANCH":  "master",
    "SCOOP_REPO":  "https://github.com/lukesampson/scoop",
    "lastupdate":  "2022-03-10T14:41:40.0009896+08:00",
    "aria2-enabled":  true
}


```

**Comment by rashil2000** [comment]
Please run `scoop update` and try again

**Comment by changxinjie** [comment]
ok, it works now. 😓
