### ISSUE TITLE
[Bug] `scoop which` not working for shim app with ".ps1"

### ISSUE THREAD

**Issue by epoweripione** [ScoopInstaller/Scoop#4802]
## Bug Report
Starting [0.1.0](https://github.com/ScoopInstaller/Scoop/releases/tag/v0.1.0), `scoop which <app>` fails to find the path if the app shim  with ".ps1".

#### Current Behavior
`scoop which git` does work, but `scoop which hub` does not work with error:
```
Convert-Path: C:\Users\user01\scoop\apps\scoop\current\libexec\scoop-which.ps1:38
Line |
  38 |          $exepath = Convert-Path $exepath
     |                     ~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'C:\Users\apps\hub\current\bin\hub.exe' because it does not exist.
```

#### Expected Behavior
work for all shims.

#### Additional context/output
```powershell
$ Get-Command git
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     git.exe                                            0.0.0.0    C:\Users\user01\scoop\shims\git.exe

$ Get-Command hub
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
ExternalScript  hub.ps1                                                       C:\Users\user01\scoop\shims\hub.ps1
```

#### Possible Solution
`libexec\scoop-which.ps1` line 33 return the relative path (`..\apps\hub\current\bin\hub.exe`) and should be replaced with scoop's app path (`C:\Users\<username>\scoop\apps\hub\current\bin\hub.exe`).

such as:
```powershell
    if (!$exepath) {
        $exepath = ((Select-String -Path $path -Pattern '[''"]([^@&]*?)[''"]' -AllMatches).Matches.Groups | Select-Object -Last 1).Value
    }

    # fix relative path in ".ps1"
    if ($exepath.StartsWith('..')) {
        $apppath = $exepath
        $userapps = Convert-Path (basedir $false)
        $exepath = $apppath -replace '\.\.', $userapps
        if (!(Test-Path $exepath)) {
            $globalapps =fullpath (basedir $true)
            $exepath = $apppath -replace '\.\.', $globalapps
        }
    }
```

### System details

**Windows version:**
10

**OS architecture:**
64bit

**PowerShell version:**
7.2.1

#### Scoop Configuration
```json
{
  "lastupdate": "2022-03-11T10:03:38.6226742+08:00",
  "aria2-enabled": false,
  "SCOOP_REPO": "https://github.com/lukesampson/scoop",
  "SCOOP_BRANCH": "master"
}
```

**Comment by niheaven** [comment]
Could you please run `scoop reset hub` and try again?

**Comment by epoweripione** [comment]
run `scoop reset hub` still got this error:
```powershell
$ scoop reset hub
Resetting hub (2.14.2).
Linking ~\scoop\apps\hub\current => ~\scoop\apps\hub\2.14.2
Creating shim for 'hub'.

$  scoop which hub
Convert-Path: C:\Users\user01\scoop\apps\scoop\current\libexec\scoop-which.ps1:38
Line |
  38 |          $exepath = Convert-Path $exepath
     |                     ~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'C:\Users\apps\hub\current\bin\hub.exe' because it does not exist.
```

But when i try reinstall `hub` with `scoop uninstall hub` and `scoop install hub`, it seems okay. By the way, the file `C:\Users\user01\scoop\shims\hub.ps1` no longer exists.

I have installed a lot of apps like dart, usql,, vlc wget, etc. Do I need to reinstall them all? This seems like a lot of work, is there an easier way to fix this?

**Comment by niheaven** [comment]
Just remove all files in `shims` folder (except for `scoop.ps1`, `scoop.cmd` and `scoop`), then run `scoop reset *`, that's all.

**Comment by epoweripione** [comment]
This workaround is great, thanks a lot.
