### ISSUE TITLE
[Bug] Using scoop checkup recommends to install something when I have it already

### ISSUE THREAD

**Issue by mspaulding06** [ScoopInstaller/Scoop#4804]
NOTE:  This was edited because the "sudo" package appears to exist now.

#### Current Behavior

I ran `scoop checkup` and got the following output.

```
# matts @ pixel in ~ [11:37:19]
$ scoop checkup
WARN  LongPaths support is not enabled.
  You can enable it by running:
    sudo Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
  (Requires 'sudo' command. Run 'scoop install sudo' if you don't have it.)
WARN  Found 1 potential problem.
```

When trying to install the recommended package I get an error because it doesn't exist anymore.

```
# matts @ pixel in ~ [11:38:01]
$ scoop install sudo
Installing 'sudo' (0.2020.01.26) [64bit]
The requested address is not valid in its context. [::ffff:185.199.111.133]:443 (raw.githubusercontent.com:443)
URL https://raw.githubusercontent.com/lukesampson/psutils/c7116ac143ca81f223e6091d0974f45ac241eb1d/sudo.ps1 is not valid
```

After inspect my network it turns out that the package is there, but didn't appear to be for some reason.  So this issue is really about scoop not detecting that I had "psutils" installed already.

#### Expected Behavior

It should have recognized that I had the psutils package installed, so I already had sudo available to me and didn't need to install it.

#### Possible Solution

Fix output to recommend installing psutils instead, maybe, and check if it is there first.

### System details

**Windows version:** 11

**OS architecture:** 64bit

**PowerShell version:** 7.2.1

**Additional software:** Terminal Preview

**Comment by HUMORCE** [comment]
it's just a hint for suggest command line, not a suggestion. consistent with expected behavior.

btw, `main/gsudo` also provides 'sudo' command.
