### ISSUE TITLE
[Bug] Scoop now reporting it isn't installed correctly.

### ISSUE THREAD

**Issue by neandrake** [ScoopInstaller/Scoop#4811]
#### Current Behavior
Running `scoop update scoop` results in 
```
ERROR 'scoop' isn't installed correctly.
INFO  Please reinstall it or fix the manifest.
```

This started happening within the past week. I keep scoop and applications updated pretty regularly.

#### Additional context/output
I've been using scoop for ~2 years. This seemed to start happening after I had installed some recent Windows 10 Updates, or that's the only thing on my system that has changed in the recent timeframe that I would think to affect this. PowerShell and Windows Terminal haven't updated in a while.

#### Possible Solution
I don't know any possible solution. I have no idea what "fix the manifest" means or how to actually reinstall scoop, as running the script from get.scoop.sh reports that it's already installed and doesn't appear to provide an option for repairing the install or re-installing.

### System details

**Windows version:** Windows 10 Pro. Version 21H2

**OS architecture:** 64bit

**PowerShell version:** 7.2.1

**Additional software:** Windows Terminal 1.11.3471.0

#### Scoop Configuration
```json
{
  "lastupdate": "2022-03-14T19:49:00.5033944-04:00",
  "SCOOP_REPO": "https://github.com/lukesampson/scoop",
  "SCOOP_BRANCH": "master"
}
```

**Comment by niheaven** [comment]
This may be due to recent refactoring of `installed()` function that checks installation status. What if you run `scoop update`?

**Comment by neandrake** [comment]
Running `scoop update` seems to behave normally. It updates buckets and then at the end it reports `Scoop was updated successfully!` however trying `scoop update scoop` again reports the same error as before.

**Comment by niheaven** [comment]
So your purpose is update scoop separately? What's the use case? If needed, I'll try to add this functionality.

**Comment by rashil2000** [comment]
For the first part, you only need to do `scoop update`. It updates buckets and scoop itself.

**Comment by neandrake** [comment]
Thanks, I'll switch to just doing `scoop update`. Indeed the documentation states this at https://github.com/ScoopInstaller/Scoop/wiki/Quick-Start#updating-scoop. I suspect the documentation ~2 years ago then had indicated running `scoop update scoop`, or maybe I just misread it at the time.

**Comment by filipworksdev** [comment]
Originally scoop was updated as `scoop update scoop` before being changed at some point along the way to `scoop update`. So technically an undocummented change/feature. It should at least tell you to use `scoop update` instead of giving an error.

**Comment by mloyd** [comment]
> Originally scoop was updated as `scoop update scoop` before being changed at some point along the way to `scoop update`. So technically an undocumented change/feature.
> 
> ![image](https://user-images.githubusercontent.com/99937119/174213272-163680e9-494b-46e5-bd2c-46f5d9ebbbc5.png) Should at least say `Please use scoop update instead` rather than tell you scoop is not installed correctly. It sends you on a wild goose chase to fix scoop if you by accident do this.

Concur with @filipworksdev because I was doing the exact same thing @neandrake was doing... which is why I'm reading/commenting on this.  Glad to see #4992 courtesy of @chawyehsu
