### ISSUE TITLE
[Bug] scoop install . bricks scoop and all installed programs

### ISSUE THREAD

**Issue by optimizasean** [ScoopInstaller/Scoop#4812]
`scoop install .` breaks scoop - it uninstalls scoop partially (enough not to be easily fixable if at all) and everything else (only the shims I think?).

This command should be checked for and ignored, definitely not something that should happen by default as I just undid an hour of work setting something up in seconds.

**Comment by rashil2000** [comment]
Duplicate of https://github.com/ScoopInstaller/Scoop/issues/2370
