### ISSUE TITLE
[Bug] `scoop which` is broken

### ISSUE THREAD

**Issue by chawyehsu** [ScoopInstaller/Scoop#4820]
#### Current Behavior

```
Desktop ~
❯ scoop which hub
Convert-Path: C:\Users\hanabi\scoop\apps\scoop\current\libexec\scoop-which.ps1:36
Line |
  36 |          $exepath = Convert-Path $exepath
     |                     ~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'C:\Users\apps\hub\current\bin\hub.exe' because it does not exist.


```

#### Expected Behavior

Should work as expected

#### Additional context/output

Regression was introduced in the [v0.1.0](https://github.com/ScoopInstaller/Scoop/commit/04b30de9dde613acec8bb0014b42f381f83e2ec9) release at https://github.com/ScoopInstaller/Scoop/commit/04b30de9dde613acec8bb0014b42f381f83e2ec9#diff-70d7462330a7a17dae5e0be7312c25c40a64c8a058afdef1d1a53bc6a268a907L34, the upstream PR was #4780.

#### Possible Solution

Base path of shimsdir was removed by the commit, `Convert-Path` converted exepath based on PWD which causes the bug. Revert this `Convert-Path` change applied to scoop-which command.
```diff
- $exepath = Convert-Path $exepath
+ $exepath = resolve-path (join-path (split-path $path) $exepath)
```

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** 7.2.1

#### Scoop Configuration

```
❯ scoop -v
Current Scoop version:
635ae171 (HEAD -> develop, origin/develop) fix(shim): Correctly quote $@ in sh->ps1 shims (#4809)
...
```

```json
{
    "aria2-enabled": true,
    "lastupdate": "2022-03-16T21:00:29.0624212+08:00",
    "msiextract_use_lessmsi": true,
    "scoop_branch": "develop",
    "scoop_repo": "https://github.com/scoopinstaller/scoop",
    "shim": "kiennq",
    "show_update_log": false
}
```

**Comment by niheaven** [comment]
Is this a same bug as https://github.com/ScoopInstaller/Scoop/issues/4802? It's because of the new shim implement.

**Comment by chawyehsu** [comment]
Sorry it is. But Why `scoop reset hub` does not help and I have to manually remove shims?

**Comment by niheaven** [comment]
Hmm, it should be added (auto remove unused ps1 shim), I'll add it later.
