### ISSUE TITLE
[Bug] Install PowerShell 7.2.2 not working

### ISSUE THREAD

**Issue by FelixHe** [ScoopInstaller/Scoop#4821]
#### Current Behavior
I try to install the newest version of PowerShell 7.2.2 via scoop update pwsh but I am always getting the error:
ERROR Application "pwsh" is still running. Close all instances and try again.

I tried this in the Windows Console application as I did all the times I updated pwsh but this time it's not working.
I looked into the resource monitor of windows (resmon.exe) to see if I have a running instance of pwsh.exe but there is none.
But what I can see is that when I execute the command "scoop update pwsh" a running process of pwsh.exe appears for a short amount of time. Is it possible that scoop itself uses pwsh to execute the commands in the background and so blocks the update?

#### Expected Behavior
It should update the PowerShell to version 7.2.2

#### Possible Solution
Install it the old fashioned way =P

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** 7.2.1

#### Scoop Configuration
{
  "lastupdate": "2022-03-17T11:47:20.1589343+01:00",
  "SCOOP_REPO": "https://github.com/lukesampson/scoop",
  "SCOOP_BRANCH": "master"
}

**Comment by rashil2000** [comment]
Scoop will use pwsh.exe if it exists. To update `pwsh`, run `scoop update pwsh` in Windows PowerShell (i.e. powershell.exe).
