### ISSUE TITLE
[Bug] Impossible to upgrade pwsh on windows.

### ISSUE THREAD

**Issue by gdoenlen** [ScoopInstaller/Scoop#4823]
#### Current Behavior
Trying to update pwsh causes the update to fail because its still running.

#### Expected Behavior
pwsh should not run and be updated successfully

#### Additional context/output
It looks like the behavior of scoop.cmd was changed to run `pwsh` if it's available here: https://github.com/ScoopInstaller/Scoop/pull/4543/files?diff=split&w=0#diff-cfd4446b6fd477007943865889b4cdbf84e1c089d960b82cd3b57c6bf019fce3R617

#### Possible Solution
revert the change

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Scoop/issues/4821#issuecomment-1070925165
