### ISSUE TITLE
[Feature] Logo for Scoop

### ISSUE THREAD

**Issue by itsmeboy0** [ScoopInstaller/Scoop#4828]
#### Is your feature request related to a problem? Please describe.
Continuation of https://github.com/ScoopInstaller/Scoop/issues/2261. I do not see why that issue got closed. Most package managers have their own logo and it would make sense that Scoop should have one.
#### Describe the solution you'd like
An easily identifiable logo for Scoop.

**Comment by rashil2000** [comment]
Don't create new issues for old discussions. If you want an issue to be reopened, comment on the old thread with a reason.
