### ISSUE TITLE
Gitter badge in README points to 404

### ISSUE THREAD

**Issue by sitiom** [ScoopInstaller/Scoop#4829]
The Gitter room hasn't been migrated yet and still points to https://gitter.im/lukesampson/scoop, but the README has been updated to point to https://gitter.im/ScoopInstaller/Scoop, which doesn't exist yet.

**Comment by rasa** [comment]
The gitter 404 was my bad, as I assumed gitter would 302. @rashil2000 has [fixed](https://github.com/ScoopInstaller/Scoop/pull/4830/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L27) this in https://github.com/ScoopInstaller/Scoop/pull/4830
