### ISSUE TITLE
[Bug] Can't update pwsh: in use by scoop

### ISSUE THREAD

**Issue by fluffynuts** [ScoopInstaller/Scoop#4838]
## Bug Report
As it says on the tin: I can't update pwsh via scoop because of the following error:
```
pwsh: 7.2.1 -> 7.2.2
Updating one outdated app:
Updating 'pwsh' (7.2.1 -> 7.2.2)
Downloading new version
Loading PowerShell-7.2.2-win-x64.zip from cache
Checking hash of PowerShell-7.2.2-win-x64.zip ... ok.
ERROR Application "pwsh" is still running. Close all instances and try again.
```

When I run `scoop update *` and watch process explorer, I see that scoop is the one holding pwsh open.

#### Current Behavior
Scoop uses pwsh, so can't update pwsh.

#### Expected Behavior
I don't know what was different before, but I've updated pwsh before via scoop without issues. This is what I'd expect.

#### Possible Solution
There is discussion here: https://github.com/ScoopInstaller/Scoop/issues/3947 about updating running programs. Alternatively, `scoop update *` should run pwsh from within the currently-versioned app folder so that the `current` link and shims can be moved? or perform the update with a reboot action, like other apps which have to overwrite things that are running (not great, but at least it would work). Or something else that I'm not thinking of

### System details

**Windows version:** ``

**OS architecture:** 64bit

**PowerShell version:** 7.2.1

**Additional software:** running within cmd.exe to attempt to avoid issues like this, so nothing else to report

#### Scoop Configuration

```json
{
  "lastupdate": "2022-03-23T08:05:26.8873309+02:00",
  "SCOOP_REPO": "https://github.com/lukesampson/scoop",
  "SCOOP_BRANCH": "master"
}
```

**Comment by niheaven** [comment]
Hmm, have you update pwsh in powershell? This could be done.

If you start scoop in pwsh console, of cause it could not be updated.

**Comment by rashil2000** [comment]
Run `scoop update pwsh` in Windows PowerShell (powershell.exe)

**Comment by rashil2000** [comment]
Cmd, Bash, Fish, Zsh will all use 'pwsh', if it exists. The only workaround is the one I mentioned.

**Comment by fluffynuts** [comment]
what's confusing is that this _used_ to work. All the way from pwsh 6.x, iirc. I don't expect the update of pwsh to work within pwsh (on windows, because, windows), but the fact that this suddenly stopped working is the gotcha.

**Comment by rashil2000** [comment]
It doesn't work anymore because the cmd and bash shims got "smarter", they use pwsh instead powershell, if pwsh exists in PATH

**Comment by fluffynuts** [comment]
then that seems like a bug - powershell is never going to be installed via scoop, where pwsh is very likely to be installed by scoop.

**Comment by rashil2000** [comment]
How is that a bug?

Do you have a solution in mind?

**Comment by fluffynuts** [comment]
yes, if the solution is for the user to have to manually use powershell.exe instead of pwsh.exe and powershell.exe works without issues, then that's what scoop should be using, instead of pwsh.exe, to run ps scripts.

if powershell.exe doesn't do everything that's required in every situation, then perhaps just the situations where it works (eg on update) should use powershell.exe

it's a bug because something that worked before now doesn't work due to an upstream code-change, and that breakage requires user intervention to circumvent; at the very least, the upstream change could be reverted and things would go back to working correctly, no?

it's a bug because windows locks executables for running processes, so running an executable that's going to be updated on a windows machine will reliably produce an error, unless the original intent of `scoop update *` is to fail, which I highly doubt.
