### ISSUE TITLE
[Feature] Display app's installation size in `scoop info`

### ISSUE THREAD

**Issue by tech189** [ScoopInstaller/Scoop#4840]
#### Is your feature request related to a problem? Please describe.

I would like to be able to quickly find out how much space a currently installed application is taking on my computer while I am looking at the app's info in `scoop info`. Especially useful if I've just run out of space and want to check if I really need a certain app.

#### Describe the solution you'd like

When running `scoop info` another line would display the app's current size including all versions and any cached downloads. Something like the following:
```
❯ scoop info losslesscut

Name        : losslesscut
Description : Lossless trimming tool for video and audio files
Version     : 3.44.0
Bucket      : extras
...
App size    : 378 MB (471 MB including cache)
```
This would be useful for working out whether an app is worth keeping on smaller hard drives and might remind users to clean their cache.

However the drawback might be a slightly slower output for this command on all types of drives but especially HDDs. Probably negligible for most drives as it's just checking the size of two folders (app folder & cached items).

#### Describe alternatives you've considered

The user could always navigate to the app directory in File Explorer or run WizTree or a similar program but that would require multiple extra steps/programs. This could be good for staying in the terminal while installing/uninstalling old programs and running out of space for example.

**Comment by rashil2000** [comment]
Cool idea! We can hide this behind the verbosity flag. Would you like to work on it?

**Comment by tech189** [comment]
Yes I'd like to have a go at least! Any reason why it might go behind the `--verbose` flag?

**Comment by rashil2000** [comment]
- Fetching a directory size takes time. We want the default UX of scoop-info to be quick.
- Like other information hidden by the verbose flag, size of installation will be different for each user. Unless of course we fetch the size of download package itself, like `apt show` and `pacman -Qi` do.

**Comment by Rafeqm** [comment]
Can you add the size of "package" as well? It will help user determine whether they have enough bandwith (or data plan) to download it.

**Comment by rashil2000** [comment]
IMO `Package Size` and `Installed size` should be 2 separate fields.

**Comment by tech189** [comment]
I got the app size working :D

![image](https://user-images.githubusercontent.com/10728085/164118521-62ad988a-8e20-49cd-853c-34a7b571c0de.png)

Next up is trying to determine the download size if the app isn't installed.

**Comment by Rafeqm** [comment]
Wow thanks very much 🎉🎉🎉! I updated scoop and now this long-awaited feature comes saving my bandwidth.
