### ISSUE TITLE
Suggest adding the ability to rebuild environment variables

### ISSUE THREAD

**Issue by Vzz1c** [ScoopInstaller/Scoop#4847]
As far as I know, not all paths exist in shims, some need to establish environment variables, if the environment variables are lost will look very confusing (I accidentally lost the backup), so you can only wait until the application update to regenerate the environment variables, I think you can save the software to generate environment variable information, and then when needed, you can rebuild this information

Translated with www.DeepL.com/Translator (free version)

**Comment by rashil2000** [comment]
Can you give an example of an app?

**Comment by Vzz1c** [comment]
> Can you give an example of an app?

gcc,python,ant... There are too many

**Comment by rashil2000** [comment]
I meant an example of what environment variables need modification.

**Comment by Vzz1c** [comment]
> shims 中



> I meant an example of what environment variables need modification.

It may be a translation problem, I did not modify any environment variables, some software such as gcc, it does not appear in the shims, the installation of this software will add additional environment variables to facilitate the work, but if you lose this environment variable, you need to add it manually, or update the time to add on, for this one is not a trouble, but I use scoop I have installed dozens of software, (discussed here only for the main repository and other portable software), many of them need to add additional environment variables when installing, and some do not need to, because they exist in shims, so after installing a software, I will look at whether the new environment variables, and then I need to back up to facilitate the subsequent restoration (unfortunately, my Unfortunately, my computer had a problem that caused me to lose the environment variables, so the idea was created)

**Comment by rashil2000** [comment]
Shims do not contain environment variables. What environment variables are installed by a package is defined in its manifest. If you lose any environment variable for any package, just run `scoop reset <package name>`, and they will be recreated.

**Comment by Vzz1c** [comment]
This is amazing, and I swear I'll take a little more time to learn more about the command.

**Comment by rashil2000** [comment]
You can also run `scoop reset *` to repeat the action for all installed apps.

**Comment by Vzz1c** [comment]
> You can also run `scoop reset *` to repeat the action for all installed apps.
Thanks for the reminder. I did exactly that, and it's back to normal.
