### ISSUE TITLE
[Bug] Shim breaks interoperability between restic and rclone

### ISSUE THREAD

**Issue by Zottelchen** [ScoopInstaller/Scoop#4849]
#### Current Behavior
When attempting to use restic backups with rclone (both installed via scoop) it does not work with error messages like:
`Fatal: unable to open repo at rclone:onedrive:snapshot: error talking HTTP to rclone: Get "http://localhost/file-5577006791947779410": unexpected EOF`

#### Expected Behavior
restic should be able to work, like it does with a non-scoop install.

#### Additional context/output
> Scoop is "shimming" apps installed via https://github.com/ScoopInstaller/Shim/blob/master/src/shim.cs . However, for unknown reason, the stdin/stdout handles which should be inherited from shim process (set by restic by redirecting) aren't passed to rclone process properly if shim process is started with DETACHED_PROCESS. Even when I modified shim.cs to manually pass handles, the issue persists. I observed that a blank console window flashed which may indicate a new console was allocated.

Originally posted by @cqjjjzr in https://github.com/restic/restic/issues/3681#issuecomment-1081441509

#### Possible Solution
—

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** 5.1.19041.1320

**Additional software:** restic, rclone

#### Scoop Configuration

```json
{
    "lastupdate":  "2022-03-28T14:42:06.1230313+02:00",
    "SCOOP_REPO":  "https://github.com/lukesampson/scoop",
    "SCOOP_BRANCH":  "master"
}
```

**Comment by rashil2000** [comment]
Scoop currently uses the kiennq shim by default. Can you try opening an issue about this at https://github.com/kiennq/scoop-better-shimexe?

**Comment by Zottelchen** [comment]
Literally can't since issues are disabled for that repository.
Hopefully, @kiennq receives notifications ;)

**Comment by cqjjjzr** [comment]
I managed to pass the handles properly by modifying the shim implementation. Will open a PR in the kiennq repo later. But I noticed the kiennq repo hasn't been updated for over 1 year...

**Comment by rashil2000** [comment]
> I noticed the kiennq repo hasn't been updated for over 1 year...

@issaclin32 should we fork the repo?

**Comment by issaclin32** [comment]
> @issaclin32 should we fork the repo?

I think we should.

**Comment by kiennq** [comment]
> Literally can't since issues are disabled for that repository. Hopefully, @kiennq receives notifications ;)

Sorry, I didn't notice the issues are being disabled on that repo. Re-enable it now

**Comment by niheaven** [comment]
Transfer repos to ScoopInstaller and don't change the ownership?

**Comment by kiennq** [comment]
> Transfer repos to ScoopInstaller and don't change the ownership?

That's brilliant.
I don't have permission to create public repositories on ScoopInstaller now, so how to I transfer it?

**Comment by kiennq** [comment]
@niheaven I still don't have permission to create a public repository on `ScoopInstaller` (I have merge permission, but don't have permission to create a new repository).
But worry not, I've requested to transfer the `kiennq/scoop-better-shimexe` repo to you, so please put it to the `ScoopInstaller` repo later :)

**Comment by chawyehsu** [comment]
I suggest putting all shim implementations into https://github.com/ScoopInstaller/Shim so we can use CI/CD to deliver different shim binaries concurrently. If you @niheaven @kiennq agree with it, I could help to refactor code structure.

**Comment by kiennq** [comment]
> I suggest putting all shim implementations into https://github.com/ScoopInstaller/Shim so we can use CI/CD to deliver different shim binaries concurrently. If you @niheaven @kiennq agree with it, I could help to refactor code structure.

Sure, please go ahead with that.
Note that I've also added the CI/CD to my repro to automatically build and publish a new version, hope it can help with the current CI/CD

**Comment by niheaven** [comment]
Go ahead @chawyehsu 🎉 

I'm thinking of some type of `plugin` system that several types of `shim` or other additional features should be added into Scoop Core after installation in need. The plugins are different choices or some performance improvements. I don't know if it is a good idea to be added to Scoop since this may increase some code/UX complexity.

**Comment by viceice** [comment]
I seeing the same issue with terraform. no interactive input possible. `ctrl+c` is also not working

btw: I'm using cmder as console host with powershell v7 on windows server 2016

**Comment by rashil2000** [comment]
Filing this under #1606
