### ISSUE TITLE
[Feature] List app manifests from user added/official buckets.

### ISSUE THREAD

**Issue by Aetopia** [ScoopInstaller/Scoop#4852]
#### Is your feature request related to a problem? Please describe.
At the moment it is not possible to list any applications from an official bucket or user added bucket.   
Say, a user adds a bucket and they installed an particular app(s) from it and want to see what other apps the bucket offers.     
I could find this useful in scenarios where a user wants to take a glance of available apps from an added bucket.           

#### Describe the solution you'd like

Say the user runs `scoop bucket apps <Bucket Name>`:
```ps
App  Version  Description
---  -------  -----------
App1  v1.0    This an application.
App2  v1.1    Another application.
```
It should list all given manifests/apps within the specified bucket, incase if all manifests' information cannot be fitted then a page system can be implemented.

So a user can run: `scoop bucket apps <Bucket Name> <Page Number>`.

A few ways how apps can be listed from a bucket.
1. Check for `.json` files in a bucket.
2. Look for `.json` files which follow the scoop manifest format and list them as listable apps.

#### Describe alternatives you've considered

You can use Windows/File Explorer to explore the bucket and check out app manifests but this is extremely inconvenient.
Bringing this directly into the terminal make viewing apps from buckets from accessible.

**Comment by HUMORCE** [comment]
this should be implemented in `scoop-list`.
