### ISSUE TITLE
[Feature] Addition of the ability to read a configuration file in which the specified version is written.

### ISSUE THREAD

**Issue by popurax** [ScoopInstaller/Scoop#4857]
#### Is your feature request related to a problem? Please describe.

Although there is a version switching function in scoop, it is not possible to automatically switch versions for each project.

#### Describe the solution you'd like

Addition of the ability to read a configuration file in which the specified version is written.

#### Describe alternatives you've considered

[I refer you to this feature.](https://github.com/Schniz/fnm#shell-setup)

I thought it would be easier to switch versions of various apps using only scoop if there was a version-specified file like `.node-version`, as shown in the link.

**Comment by rashil2000** [comment]
Please refer to the discussion https://github.com/ScoopInstaller/Scoop/discussions/4695
