### ISSUE TITLE
[Bug] scoop update pgadmin4-np yields "The remote server returned an error: (404) Not Found."

### ISSUE THREAD

**Issue by hlampert** [ScoopInstaller/Scoop#4859]
#### Current Behavior
Apologies for opening this issue in the main Issues section, but I did not see a "Nonportable" bucket!  running "scoop update pgadmin4-np" yields the following powershell output:

pgadmin4-np: 4.28 -> 4.29
Updating one outdated app:
Updating 'pgadmin4-np' (4.28 -> 4.29)
Downloading new version
The remote server returned an error: (404) Not Found.
At C:\Users\ny11571\scoop\apps\scoop\current\lib\install.ps1:142 char:9
+         throw $e
+         ~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], WebException
    + FullyQualifiedErrorId : The remote server returned an error: (404) Not Found.

#### Expected Behavior
scoop updates pgadmin4.

### System details

**Windows version:** [e.g. 7, 8, 10]
Windows 10

**OS architecture:** [e.g. 32bit, 64bit]
64 bit

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]
5.1

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
{
    "lastupdate":  "2022-04-06T09:01:21.6745938-04:00",
    "SCOOP_REPO":  "https://github.com/lukesampson/scoop",
    "SCOOP_BRANCH":  "master"
}
```

**Comment by rashil2000** [comment]
You need to open this issue here https://github.com/TheRandomLabs/scoop-nonportable
