### ISSUE TITLE
[Bug] Windows doesn't recognise apps installed by scoop

### ISSUE THREAD

**Issue by wisdomtooth** [ScoopInstaller/Scoop#4860]
#### Current Behavior
Apps installed with Scoop don't show up in the Control Panel's list of installed apps.

#### Expected Behavior
Apps installed via Chocolatey or Winget do.

### System details
Windows 10 Home 64-bit
PowerShell 7.2.2

#### Scoop Configuration

```json
{
  "lastupdate": "2022-04-09T19:36:54.8567024+10:00",
  "SCOOP_REPO": "https://github.com/lukesampson/scoop",
  "SCOOP_BRANCH": "master",
  "aria2-warning-enabled": false
}
```

**Comment by rashil2000** [comment]
Tracked in https://github.com/ScoopInstaller/Scoop/issues/2651
