### ISSUE TITLE
[Bug] Scoop updating apps installed with other pkg mgrs creates duplicates instead of updating

### ISSUE THREAD

**Issue by wisdomtooth** [ScoopInstaller/Scoop#4861]
#### Current Behavior
If an app is already installed by another package manager or its own installator, `scoop update` creates a new, duplicate instance.

#### Expected Behavior
I'd expect it to update the installed app, not create a new instance of it, as Chocolatey and Winget do.

### System details
Windows 10 Home 64-bit
PowerShell 7.2.2

#### Scoop Configuration

```json
{
  "lastupdate": "2022-04-09T19:36:54.8567024+10:00",
  "SCOOP_REPO": "https://github.com/lukesampson/scoop",
  "SCOOP_BRANCH": "master",
  "aria2-warning-enabled": false
}
```

**Comment by rashil2000** [comment]
It's not recommended to mix and match different package managers for installing the same application. Scoop works uniquely, and this isn't a bug.
