### ISSUE TITLE
[Bug] Held app updated anyway

### ISSUE THREAD

**Issue by m4gnify** [ScoopInstaller/Scoop#4862]
#### Current Behavior
Specific held app updated anyway

#### Expected Behavior
Shouldn't update

#### Additional context/output
The app "**mpv.net**" was updated, even though I had **held** it before updating. 
Another app, "**mpv-git**" was also held, and was not updated.

I think this has happened before too, with specifically mpv.net, but I'm unsure.

### System details

**Windows version:** 11

**OS architecture:** 64bit

**PowerShell version:** 7.2.2

#### Scoop Configuration

```json
{
  "lastupdate": "2022-04-10T12:33:11.8502028+02:00",
  "SCOOP_REPO": "https://github.com/ScoopInstaller/Scoop",
  "SCOOP_BRANCH": "master"
}

```
![pwsh_tLz9664cKI](https://user-images.githubusercontent.com/8404962/162614918-315f44e2-190a-4267-a2f6-261e29db93be.jpg)

**Comment by rashil2000** [comment]
Is the updated app a globally installed app?

**Comment by m4gnify** [comment]
Not completely sure what that entails, but it is installed in the scoop directory, 
`C:\Users\*\scoop\apps\mpv.net\current`

**Comment by m4gnify** [comment]
I don't have any following problems with this btw, I just thought I should report it.

**Comment by rashil2000** [comment]
What does `scoop list` show?

**Comment by m4gnify** [comment]
![pwsh_H0lvltHGLo](https://user-images.githubusercontent.com/8404962/162633145-5beddbab-5f64-4868-b263-de6f4590d430.jpg)

Maybe it has something to do with the "mpv-" and "mpv." parts? (I have literally no idea, just guessing)

**Comment by rashil2000** [comment]
I can't repro:

![image](https://user-images.githubusercontent.com/46838874/162725768-1fc4eca8-9d18-47b5-8b39-c61dd87a5031.png)

**Comment by m4gnify** [comment]
Could try with the "mpv-git" installed too?
Or it could just be something weird with my specific config, who knows. 
Can maybe just close this, if it isn't reproducible.
