### ISSUE TITLE
[Feature] The excavator GitHub action run does not report error if something fails to update

### ISSUE THREAD

**Issue by CrendKing** [ScoopInstaller/Scoop#4863]
#### Current Behavior

Take a look at the "Excavate" step of this GitHub Action run: https://github.com/ScoopInstaller/Extras/runs/5963485483. There are plenty of errors that some apps fail to update. However, the whole run completed successfully. If no one notices these hidden errors, some apps may never get auto updated. This is not big problem of large repo like Scoop/Extras, but could be for people that maintain personal bucket.

#### Expected Behavior

If the current behavior is expected, that for some reason you guys don't want error from the action run, please provide an option so that personal bucket maintainers can get notification when action fails.

#### Additional context/output

Not sure if this issue belongs here or https://github.com/ScoopInstaller/GithubActions.

#### Possible Solution

Is this because https://github.com/ScoopInstaller/GithubActions/blob/main/src/ActionWrapper.psm1 `Invoke-Action` does not propagate the error from [autoupdate.ps1](https://github.com/ScoopInstaller/Scoop/blob/master/lib/autoupdate.ps1#L578)?

### System details

**Windows version:** 11

**OS architecture:** 64bit

**PowerShell version:** 7.2.2

#### Scoop Configuration

```json
{
  "SCOOP_REPO": "https://github.com/ScoopInstaller/Scoop",
  "SCOOP_BRANCH": "master",
  "shim": "kiennq",
  "ignore_running_processes": true,
  "aria2-warning-enabled": false
}
```

**Comment by rashil2000** [comment]
The current behavior is intentional. Given the immensely dynamic nature of webpages that checkver scrapes, the chance of failure, even if you have something like 4-5 manifests, is quite high. Bucket maintainers would see a lot of runs failed as a result.

**Comment by CrendKing** [comment]
I figured so. That's why I put this as feature request. The app count in many self maintained buckets are quite manageable (I have one myself), and they usually have very few maintainers. Errors like this could go undetected for long time if they don't get notification.

I have no experience at working on github action, but if you think this a good idea, I could try a pull request.

**Comment by rashil2000** [comment]
An optional, off by default setting should be good.

**Comment by CrendKing** [comment]
That's my intention.

**Comment by CrendKing** [comment]
The PR consists of two parts:

https://github.com/ScoopInstaller/Scoop/pull/4867
https://github.com/ScoopInstaller/GithubActions/pull/5
