### ISSUE TITLE
[Bug] Cannot install Git with Scoop

### ISSUE THREAD

**Issue by TamamoNoMae13** [ScoopInstaller/Scoop#4864]
#### Current Behavior

`scoop` refuses to install `git` and says "Scoop uses Git to update itself. Run 'scoop install git' and try again."

#### Expected Behavior

Scoop installing Git.

#### Additional context/output

```
PS C:\Users\hung\scoop\apps\pwsh\current> scoop install git
ERROR Scoop uses Git to update itself. Run 'scoop install git' and try again.
```
I got a fork bomb issues like this issue: https://github.com/ScoopInstaller/Scoop/issues/4323, but with Git _version 2.35.1.windows.2_
I ran `scoop uninstall git` successfully but cannot `scoop install git`.

#### Possible Solution

None

### System details

**Windows version:** 10 21H2

**OS architecture:** 64bit

**PowerShell version:** Happened on both 7.2.2 and 5.1 (build 19041 revision 1320)

**Additional software:** pwsh (7.2.2) installed from scoop, the 5.1 one is built-in

#### Scoop Configuration

```json
{
  "lastupdate": "258|2022-04-11 16:26:10",
  "SCOOP_REPO": "https://github.com/Ash258/Scoop-Core",
  "SCOOP_BRANCH": "main",
  "aria2-enabled": true,
  "aria2-retry-wait": 2,
  "aria2-split": 5,
  "aria2-max-connection-per-server": 5,
  "aria2-min-split-size": "5M",
  "MSIEXTRACT_USE_LESSMSI": true
}
```

**Comment by rashil2000** [comment]
Report your issue here https://github.com/Ash258/Scoop-Core
