### ISSUE TITLE
Gotcha in README.md doc display on page https://github.com/ScoopInstaller/Scoop

### ISSUE THREAD

**Issue by BloomingAzaleas** [ScoopInstaller/Scoop#4866]
#### Current Behavior

The README.md instructions for customizing various scoop directories via environment vars SCOOP_GLOBAL, SCOOP_CACHE, and SCOOP_CHECKVER_TOKEN (but not SCOOP) use the construct:

$env:SCOOP_GLOBAL='some_Windows_path'
[Environment]::SetEnvironmentVariable('SCOOP_GLOBAL', $env:SCOOP_GLOBAL, 'Machine')

But the use of 'Machine' scope requires Administrator privilege to the Windows Registry, meaning the Powershell session for the SetEnvironmentVariable command has to be started as Administrator. However, that same Powershell session cannot then be used to actually run the installer because, well, "Running the installer as administrator is disabled by default, see https://github.com/ScoopInstaller/Install#for-admin for details."

Gotcha.

#### Expected Behavior

The instructions should note the (mutually exclusive) Powershell session privilege levels needed for the SetEnvironmentVariable command of 'Machine' scope versus the enforced lesser privilege of the default install script.

Note that 'User' scope in SetEnvironmentVariable command does NOT require elevated privilege.

#### Possible Solution

Two Powershell sessions of differing privilege is of course the workaround but unless the new scoop user is also a Windows power user that new scoop user will wander around in the weeds for a while upon encountering that first Registry perms error from screen-scrape-paste from the browser window to the PS command line.

### System details

**Windows version:** [e.g. 7, 8, 10]
Edition	Windows 10 Pro for Workstations
Version	21H2
Installed on	‎11/‎4/‎2020
OS build	19044.1620
Experience	Windows Feature Experience Pack 120.2212.4170.0

**OS architecture:** [e.g. 32bit, 64bit]
x86_64

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]
PowerShell 7.2.2

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
//# Your configuration here
```

**Comment by rashil2000** [comment]
This has been fixed in the https://github.com/ScoopInstaller/Scoop/tree/develop branch
