### ISSUE TITLE
[Feature] Do not use the Unlicense for scoop

### ISSUE THREAD

**Issue by Tyler887** [ScoopInstaller/Scoop#4868]
## Feature Request

**Note: This is not legal advice. I am not a lawyer.**
#### Is your feature request related to a problem? Please describe.

Scoop is currently using the Unlicense and was using it since development of it began (that means Scoop is released to the public domain). I have an issue with Scoop's license - the Unlicense is **invalid** in some countries (e.g. Germany), and does not seem to be clear in a few countries (e.g. Australia). This is a problem with the Unlicense, so we should be moving to MIT or Apache because "public domain" does not exist everywhere. Also, [the Unlicense is not allowed to be used inside Google](https://opensource.google/docs/patching/#forbidden), so Google would not be allowed to make contributions to Scoop or fork it to @google. However, Google employees are important contributors to open-source, so always stay away from the Unlicense. There are also rumours going on in github/choosealicense.com#805.

This should apply to all Scoop repositories using the Unlicense (yes, that means most of the repositories).

Note that [0BSD](https://choosealicense.com/licenses/0bsd) is an exception.
#### Describe the solution you'd like

I would edit the `LICENSE` file to use a permissive license instead of the Unlicense or any other public domain dedication.
#### Describe alternatives you've considered

Using Chocolatey instead. I am also writing [CPPM](https://github.com/Tyler887/CPPM), a package manager not only for Windows, but for _any operating system that supports Python_. It's not released into the public domain but is under a permissive license.

**Comment by rasa** [comment]
Instead of replacing, we could perhaps dual license? My preference would be to use MIT.

**Comment by Tyler887** [comment]
> Instead of replacing, we could perhaps dual license? My preference would be to use MIT.

Okay, that would mean *we would use the Unlicense for anyone in a country allowing releasing into PD so they could relicense Scoop*, and outside these countries, the MIT would apply which would have more conditions (I call the MIT license a "permissive license" while I call the Unlicense a "public-domain dedication").

I would place the MIT license in `LICENSE.MIT`, and we would rename the Unlicense file in this repo to `LICENSE.PD`.

**Comment by Tyler887** [comment]
Opened #4869 so Scoop can dual-license simply by merging it.

**Comment by Tyler887** [comment]
I would have to go through every repo and open a PR there, that would be very slow, so I only opened it here. Members of this organisation (@ScoopInstaller) can manually dual-license the other repositories.

**Comment by hornyjailfish** [comment]
what the hell????
only point to changing license is GOOGLE DONT USE IT
corporations want use this code to make money so you came and change license like this?

**Comment by Tyler887** [comment]
> what the hell???? only point to changing license is GOOGLE DONT USE IT corporations want use this code to make money so you came and change license like this?

Can you please not spam? I know, but Google does patch open-source projects, but not ones under forbidden licenses like the Unlicense which is applied. Anyways, @lukesampson, can you delete https://github.com/ScoopInstaller/Scoop/issues/4868#issuecomment-1100927812?

**Comment by beerpiss** [comment]
Just my two cents, but why not the [0BSD license](https://spdx.org/licenses/0BSD)? The 0BSD is a public-domain-equivalent license that is well understood (as it is part of the BSD license family) and keeps the spirit(?) of the Unlicense: free, unencumbered software released to everyone.
