### ISSUE TITLE
[Bug] Missing robocopy

### ISSUE THREAD

**Issue by Hetox123** [ScoopInstaller/Scoop#4875]
I dont understand any of this thing
but im trying to install scoop and it say the following error when i type iwr -useb get.scoop.sh | iex in powershell
powershell is running as an administrator

Scoop requires 'C:\Windows\System32\Robocopy.exe' to work. Please make sure 'C:\Windows\System32' is in your PATH

 pls explain me the fix and error in simple language i do not understand any thing related to coding

**Comment by rashil2000** [comment]
Two things:
- Well, the error is pretty simple. Scoop requires 'robocopy', a Windows system tool to work. It's either missing on your system or not available in PATH.
- You should **never** ignore the issue template, which asks for important information about your system. It helps to diagnose problems faster.

**Comment by Hetox123** [comment]
How do i fix the error Though 
i want to install scoop

**Comment by rashil2000** [comment]
Create a new issue, and properly fill in the template with the details this time. Also, show the output of `$env:PATH.Split(';')`.
