### ISSUE TITLE
[Feature] AUTOMATIC persist file/folder during update

### ISSUE THREAD

**Issue by NSP-0123456** [ScoopInstaller/Scoop#4877]
## Feature Request
In many software installed by scoop i have some custom files/folder i would like to automatically link during update. (license key, additional plugin, additional ini/property files ... )

#### Describe the solution you'd like
During update, all files in curent persist folder for the application and not only what is described in json manifest will be linked in install folder if a conflict is raised (file exist in new install folder) a question ask for resolution :
- Replace persisted file/folder with newest installed file
- Rename new file/folder and link persisted object

#### Describe alternatives you've considered
Add a fake user repository with partial manifest file json.user to complement persist, pre-post installation script.
When an update is done, both manifest are "joined" to add persisted file, pre and post install script.

**Comment by rashil2000** [comment]
Your use case is quite rare, I don't think most users would want to persist everything. 

The manifest will persist things that should be officially persisted according to the app developers, and nothing else. The best way to achieve what you want is already described by you, i.e. a custom manifest.
