### ISSUE TITLE
`scoop update` returns exit code 0 even when update fails

### ISSUE THREAD

**Issue by fluffynuts** [ScoopInstaller/Scoop#4883]
## Bug Report
As per the title, `scoop update` returns exit code 0 when the update fails. This means that a controller process (eg a little parallel-update script I hacked together because some larger updates were holding up smaller ones) can't easily tell if an update fails.

#### Current Behavior
`scoop update` always returns exit code 0, irrespective of whether or not the update completed.

#### Expected Behavior
`scoop update` should return a non-zero exit code if the update doesn't complete successfully

#### Additional context/output
![image](https://user-images.githubusercontent.com/4669340/164255737-b6641584-5ae5-4ff6-95be-4df408c01193.png)

#### Possible Solution
ideally, the exit code could mean something, eg
1: app is currently open (can't be updated)
2: download fails
3: hash check fails
4: installation fails for some reason (eg disk full)

but I'd settle for any non-zero on any error, tbh

### System details

**Windows version:**
11

**OS architecture:**
64bit

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]
7.2.2

#### Scoop Configuration

```json
{
  "lastUpdate": "2022-04-20T16:04:45.4031884+02:00",
  "SCOOP_REPO": "https://github.com/ScoopInstaller/Scoop",
  "SCOOP_BRANCH": "master"
}
```

**Comment by rashil2000** [comment]
Hi!

Thanks for the report. This is being tracked here - https://github.com/ScoopInstaller/Scoop/issues/3936
