### ISSUE TITLE
[Feature] Add --all switch to "scoop cleanup" subcommand.

### ISSUE THREAD

**Issue by martinlindhe** [ScoopInstaller/Scoop#4887]
## Feature Request

Make "scoop cleanup --all" available, in the same way as "scoop update --all" is currently available.

#### Is your feature request related to a problem? Please describe.

I am trying to use msys2 bash as a main shell on Windows, and encountered this 
error:
```
$ scoop update '\*'
Compare-Version : Cannot process argument transformation on parameter 'ReferenceVersion'. Cannot convert value to type System.String.
At C:\Users\marti\scoop\apps\scoop\current\lib\core.ps1:353 char:68
+ ... utdated = ((Compare-Version -ReferenceVersion $status.version -Differ ...
+                                                   ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Compare-Version], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Compare-Version

\*: 21.07 0.2.26 1.36.0-1 0.20.0 0.6.8 2022-03-29 3.23.1 1.47.0 7.82.0_4 3.6 0.8.0 5.0.1 5.38 11.2.0 2.36.0.windows.1 1.18.1 3.4.4 1.45.2 2.3.6 3.0.0 6.2.5 0.9.0 1.9 0.50 1.6 1.1.2 0.21.0 4.3 3.20.4 2022-03-19 6.2-16 1.10.2 7.92 18.0.0 0.61.0 3.0.2 3.2.0.0 8.1.5 1.8.11 5.0.14.1 0.5.0 13.0.0 3.38.2 1.6.2 0.2020.01.26 4.11 1.19.2 0.22.0 2.2.1 0.8.1 20220319-142410-0fcdea07 1.21.3 2021.12.17 (latest version)
Latest versions for all apps are installed! For more information try 'scoop status'
```
But then I found that "scoop update --all" works correctly. But after that, I wanted to clean the scoop cache but same problem there. But the "scoop cleanup" subcommand lacks a --all alias.

#### Describe the solution you'd like
Add --all, -a flags to the "scoop cleanup" subcommand.

```
  -a, --all                 Update all apps (alternative to '*')
```

**Comment by rashil2000** [comment]
Simple and reasonable request! Would you like to work on it?

**Comment by martinlindhe** [comment]
@rashil2000 I have way too much work on my table. I am not able to work on this for now, sorry.

**Comment by martinlindhe** [comment]
The new feature is working as intended, thank you very much @niheaven

**Comment by ClassicDarkChocolate** [comment]
Isn't it `scoop update \*` (no quotes)
