### ISSUE TITLE
[Bug] github checkver misbehaving for main/mvndaemon package

### ISSUE THREAD

**Issue by mateusz-bajorek** [ScoopInstaller/Scoop#4894]
#### Current Behavior
Github autoupdater/checkver picks up the new tag, commits the change, picks up the old tag and commits the change again.

#### Expected Behavior
The new tag is used and not overwritten.

#### Additional context/output
When updating my local env, I noticed there was a log about `mvndaemon` being updated to version `0.8.0` but it wasn't updated locally. When I investigated more thoroughly, I figured out it was later downgraded to the previous version. I understand it's an automatic action so I figured out the github checkver might not behave correctly.

Below's a screenshot from the commit history of the bucket file:
![firefox_2022-05-02_08-59-56](https://user-images.githubusercontent.com/11185738/166197424-932aebd8-63c5-42ee-90ee-30d8f5f411b2.png)

It _might_ be related to the fact that the mvndaemon release page is still on the previous version:
https://github.com/apache/maven-mvnd/releases
but the 0.8.0 tag was indeed created:
https://github.com/apache/maven-mvnd/tags

In such case, the question is why did the autoupdater pick the tag and then rollbacked to release.

**Comment by HUMORCE** [comment]
https://github.com/apache/maven-mvnd/actions/runs/2246273817

**Comment by rashil2000** [comment]
checkver is working as intended. It will change to the latest release it finds, even if the change is a downgrade. This is to keep packages in sync with upstream developers who sometimes recall latest releases in case of critical bugs or vulnerabilities.
