### ISSUE TITLE
[Feature] Persist Folder Cleanup Command

### ISSUE THREAD

**Issue by Dante-Vergilson** [ScoopInstaller/Scoop#4898]
I came across this issue when I decided to manage Thunderbird and LibreOffice through Chocolatey instead of Scoop since I don't like how it handles them. Mainly that Thunderbird resets the profile so I have to point it back to the scoop folder each time (I know I can just setup in the AppData folder as well but I also wanted to play with Chocolatey), and with LibreOffice Scoop can only handle doing the portable versions.

Right now if your app has a persist data folder it won't be deleted when or if you delete the app. This is fine for the most part depending on use case. However, if you want to keep things clean and have no plans of managing the app through Scoop then the only way to cleanup your persist folders is to do it manually.

We already have a "cleanup" command for when updating apps. I propose there should be a command for cleaning up persist folders for when an app is uninstalled. It could simply be an addon or flag to the cleanup command.

All it would do is to check to see if the folders in the persist folders have an associated app and deletes a folder if it doesn't.

**Comment by rashil2000** [comment]
> there should be a command for cleaning up persist folders for when an app is uninstalled

```
scoop uninstall <app> --purge
```

:)
