### ISSUE TITLE
[Bug] scoop list apps path broken

### ISSUE THREAD

**Issue by Eccomi21** [ScoopInstaller/Scoop#4899]
#### Current Behavior

When executing `scoop list` I get an Error stating:
```
C:\Users\Eccomi
λ scoop list
Get-ChildItem : Cannot find path 'C:\Users\Eccomi\scoop\apps\apps\shims' because it does not exist.
At C:\Users\Eccomi\scoop\apps\apps\scoop\current\lib\commands.ps1:3 char:12
+         + (Get-ChildItem "$scoopdir\shims") `
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Eccomi\scoop\apps\apps\shims:String) [Get-ChildItem], Item
   NotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand

There aren't any apps installed.
```

#### Expected Behavior

When executing `scoop list`, show list of installed packages/apps

#### Additional context/output

Line 3 in `C:\Users\Eccomi\scoop\apps\apps\scoop\current\lib\commands.ps1` that looks for "shims" seems to look in the wrong directory, as shims exists in
`C:\Users\Eccomi\scoop\apps\shims`
not
`C:\Users\Eccomi\scoop\apps\apps\shims`
This behavior started randomly today
I added a PATH variable yesterday. 
`Variable: SCOOP `
`Variable: C:\Users\Eccomi\scoop\apps\apps`
Deleting this variable did not solve the issue

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** 5.1.19041.1645

**Additional software:** CMDer, ConEmu

#### Scoop Configuration

```json
{
    "lastUpdate":  "2022-05-05T09:17:13.9306343+02:00",
    "SCOOP_REPO":  "https://github.com/ScoopInstaller/Scoop",
    "SCOOP_BRANCH":  "master"
}
```

**Comment by rashil2000** [comment]
What's the output of

```pwsh
> $env:SCOOP
> $env:SCOOP_GLOBAL
> $env:Path.Split(';')
```

**Comment by Eccomi21** [comment]
@rashil2000 First one does nothing, second one does nothing, third one reads as follows
```
PS C:\Users\Eccomi> $env:SCOOP

PS C:\Users\Eccomi> $env:SCOOP_GLOBAL

PS C:\Users\Eccomi> $env:Path.Split(';')
C:\Windows\system32
C:\Windows
C:\Windows\System32\Wbem
C:\Windows\System32\WindowsPowerShell\v1.0\
C:\Windows\System32\OpenSSH\
C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
C:\Program Files\Git\cmd
C:\Users\Eccomi\scoop\apps\apps\openjdk\current\bin
C:\Users\Eccomi\scoop\apps\apps\python\current\Scripts
C:\Users\Eccomi\scoop\apps\apps\python\current
C:\Users\Eccomi\scoop\apps\shims
C:\Users\Eccomi\scoop\apps\oraclejdk\current\bin
C:\Users\Eccomi\scoop\apps\python\current\Scripts
C:\Users\Eccomi\scoop\apps\python\current
C:\Users\Eccomi\scoop\shims
C:\Users\Eccomi\AppData\Local\Microsoft\WindowsApps
C:\Users\Eccomi\AppData\Local\Programs\Microsoft VS Code\bin
PS C:\Users\Eccomi>
```

**Comment by rashil2000** [comment]
> I added a PATH variable yesterday. `Variable: SCOOP ` `Variable: C:\Users\Eccomi\scoop\apps\apps` Deleting this variable did not solve the issue

You've broken your Scoop installation by doing this.

Delete the C:\Users\Eccomi\scoop\apps\apps folder and all PATH entries containing this folder.

**Comment by Eccomi21** [comment]
Thanks @rashil2000, that worked!
