### ISSUE TITLE
[Feature] scoop install --no-env or similar

### ISSUE THREAD

**Issue by quotidian-ennui** [ScoopInstaller/Scoop#4900]
## Feature Request

Add a scoop install option such that the installer does not override environment variables specified in the manifest.

#### Is your feature request related to a problem? Please describe.

If you install multiple java runtimes, then each time you update the java runtime it overrides the environment variable "JAVA_HOME" for the user, which means that post-update there is a non-obvious exception sometimes when executing java.

e.g. 

```
scoop install zulu8-jdk # after this point JAVA_HOME is set to c:\users\me\scoop\apps\zulu8-jdk\current
scoop install zulu11-jdk # after at this point JAVA_HOME is set to c:\users\me\scoop\apps\zulu11-jdk\current
scoop install graalvm-jdk11 # after at this point JAVA_HOME is set to c:\users\me\scoop\apps\graalvm-jdk11\current
```

This is apparent if you install something like intellij-idea, since this uses JAVA_HOME; you might inadvertently be using a version of java you didn't expect to be using to build your project (depending on how you have idea setup).

#### Describe the solution you'd like

Add a flag to the install process so that you can optionally "not process" the manifest environment settings

#### alternatives solution

Add a hook into the manifest file so that a post-install script could be triggered when doing an installation? 
I'm not sure that's the right way to go about it since we'd have to have a naming convention about the script etc.

#### Current work-around

I just have a very naive powershell script that I execute after I do any `scoop update java-ery` things (i'm not a powershell person to be honest).

```powershell
[Environment]::SetEnvironmentVariable('JAVA_HOME','C:\storage\java\jdk', [EnvironmentVariableTarget]::User)

#Get Current Path
$Environment = [Environment]::GetEnvironmentVariable("Path", [EnvironmentVariableTarget]::User)

#Remove "java variations" from Path
foreach ($path in ($Environment).Split(";"))
{
  if ($path -like "*zulufx11-jdk\current*") {
    $Environment = $Environment.Replace($Path ,"")
  }
  if ($path -like "*zulu8-jdk\current*") {
    $Environment = $Environment.Replace($Path ,"")
  }
  if ($path -like "*graalvm-jdk11\current*") {
    $Environment = $Environment.Replace($Path ,"")
  }
}

[Environment]::SetEnvironmentVariable("Path", $Environment, [EnvironmentVariableTarget]::User)
```

**Comment by HUMORCE** [comment]
```
❯ scoop update *; scoop reset zulu11-jdk
❯ scoop install temurin11-jdk; scoop reset zulu11-jdk

❯ scoop alias _env add 'scoop reset 7zip-zstd ... zulu11-jdk'
❯ scoop install/update <app>/*; scoop _env
```

**Comment by quotidian-ennui** [comment]
I can live with that; thanks.
