### ISSUE TITLE
`scoop cat` doesn't use `bat`

### ISSUE THREAD

**Issue by YSCohen** [ScoopInstaller/Scoop#4905]
#### Current Behavior

`scoop cat python` outputs the plain text of the `python` manifest

#### Expected Behavior

it should pretty-print the manifest with `bat`

#### Additional context/output

I have `bat`

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** 7.2.3

**Additional software:** bat@0.20.0

#### Scoop Configuration

```json
{
  "lastupdate": "2022-05-06T09:39:53.3111793-04:00",
  "SCOOP_REPO": "https://github.com/lukesampson/scoop",
  "SCOOP_BRANCH": "master"
}
```

**Comment by rashil2000** [comment]
You need to set the `cat_style` environment variable:

https://github.com/ScoopInstaller/Scoop/blob/7d5a47cc774961c15fdae6be1daf6331282b0161/libexec/scoop-config.ps1#L88-L92

**Comment by YSCohen** [comment]
> You need to set the `cat_style` environment variable:

as in windows env var?

**Comment by rashil2000** [comment]
Oops sorry, I meant a config variable, through `scoop config`

**Comment by YSCohen** [comment]
that makes more sense

**Comment by YSCohen** [comment]
that makes more sense

**Comment by milnak** [comment]
This is confusing, as `scoop help` shows:

`cat        Show content of specified manifest. If available, `bat` will be used to pretty-print the JSON.`

it should instead state that if *configured*, bat will be used.

**Comment by niheaven** [comment]
We planned to enable `bat` by default, just as `aria2` does. But using `bat` means more time to show the content, and change the default behavior. Maybe the info hasn't been changed.
