### ISSUE TITLE
[Bug]  Using double quotes around the app name for the scoop home command is not working.

### ISSUE THREAD

**Issue by amreus** [ScoopInstaller/Scoop#4910]
## Bug Report

Using quotes around the app name for the `home` command does not work.  It appears single quotes are added to the string.  

Using double quotes does work for other commands such as 'info', 'cat', 'depends', etc.  

The fact that `scoop home` does not work is inconsistent with the other commands.

    > scoop home "0ad"
    Could not find manifest for ''0ad''.

### System details

**Windows version:** [e.g. 7, 8, 10]

**OS architecture:** [e.g. 32bit, 64bit]

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
//# Your configuration here
```

**Comment by lewis-yeung** [comment]
Unable to reproduce this. `scoop home "0ad"` works correctly on my end, either on the branch `master` or `develop`.

**Comment by amreus** [comment]
Odd. I just uninstalled scoop and reinstalled. Same issue. Happens in both `cmd` and `windows-terminal`.

If I add `Write-Host $app` and `Write-Host $app.Length` to the top of `scoop-home.ps1`, I get

```
> scoop home "0ad"
'0ad'
5
Could not find manifest for ''0ad''.
```

scoop version v0.1.0 7d5a47cc
Windows 10 64bit 10.0.19043 Build 19043
Powershell:
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      19041  1645

**Comment by lewis-yeung** [comment]
> Perhaps I should add that I do use `scoop` from `cmd` and not `powershell`.

@amreus Reproduced in CMD and confirmed the bug. The double quotes are replaced with single ones in the .cmd shim `scoop.cmd`:

```bat
...
:: replace problem characters in arguments
set args=%args:"='%
...
```

**Comment by amreus** [comment]
@lewis-yeung 

Good catch. However I don't think that's the root problem. The double quoting would also be a problem for some the other scoop commands instead of only `scoop home`.

I think the fix is that `scoop-home.ps1` should call `parse_app` for consistency.

These commands use `parse_app` to modify `$app`:
```
scoop-reset.ps1
scoop-install.ps1
scoop-info.ps1
scoop-download.ps1
scoop-cat.ps1
```

**Comment by lewis-yeung** [comment]
@amreus Fair point. I just noticed this too. However I found a problem in `parse_app`:

```powershell
if($app -match '(?:(?<bucket>[a-zA-Z0-9-]+)\/)?(?<app>.*\.json$|[a-zA-Z0-9-_.]+)(?:@(?<version>.*))?') {
    return $matches['app'], $matches['bucket'], $matches['version']
}
```

The regular expression doesn't begin with a prefix `^` or end with a suffix `$`, which means the matched app name can be just a substring of the input string `$app`. E.g., `scoop info %python` works just as a normal call `scoop info python`. That's unreasonable, isn't it? 😆

**Comment by lewis-yeung** [comment]
On the other hand, I think this legacy logic on shim-generating should be removed:

https://github.com/ScoopInstaller/Scoop/blob/b93d0b415737d648ba2dd4e211872f0e19895ed5/lib/core.ps1#L684-L689

since #4721 has changed `-command` to `-file` in .cmd -> .ps1 shims, which supports passing arguments as they are, so "problem characters" should become an outdated problem.

**Comment by rashil2000** [comment]
Hi! Could you create a PR for your proposal?

**Comment by lewis-yeung** [comment]
@rashil2000 I'm on it. Should it go out with v0.2.0?

**Comment by rashil2000** [comment]
Not necessarily. Take your time :)
