### ISSUE TITLE
[Bug] Can not install with url encoded in `utf-8`

### ISSUE THREAD

**Issue by yi-Xu-0100** [ScoopInstaller/Scoop#4911]
#### Current Behavior

![图片](https://user-images.githubusercontent.com/25523606/167342667-52a55f2c-3fef-4d3c-908e-0731cbbefed8.png)

#### Expected Behavior

The file is encoding with utf-8, but the `Webclient` use `default` encoding, and it is not recommended.

See more in [system.net.webclient.encoding](https://docs.microsoft.com/en-us/dotnet/api/system.net.webclient.encoding?view=net-6.0#system-net-webclient-encoding) and [system.text.encoding.default](https://docs.microsoft.com/en-us/dotnet/api/system.text.encoding.default?view=net-6.0#system-text-encoding-default).

#### Possible Solution

We can solve this problem by set the `Encoding` for `Webclient`.

### System details

**Windows version:** [e.g. 7, 8, 10]

win10 

**OS architecture:** [e.g. 32bit, 64bit]

64bit

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]

5.1.19041.1645

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

default setting.

**Comment by yi-Xu-0100** [comment]
@rashil2000 I get the character encoding from the Content-Type header in the response with the help of https://github.com/ScoopInstaller/Scoop/issues/4324#issuecomment-982758728.

```ps1
$wc = New-Object Net.Webclient
$wc.Headers.Add('User-Agent', (Get-UserAgent))
$rawData = $wc.downloadData($url)
if($wc.ResponseHeaders["Content-Type"] -match 'charset=([^;]*)') {
  $encoding = [System.Text.Encoding]::GetEncoding($Matches[1])
} else {
  $encoding = [System.Text.Encoding]::GetEncoding('utf-8')
}
$str = $encoding.GetString($rawData)
```

And I found many `webclient.downloadstring` statements were used in different files.

May we add a function about it in files that include the utils? Or create a new file to provide this function?

**Comment by rashil2000** [comment]
> May we add a function about it in files that include the utils? 

We can do this

**Comment by yi-Xu-0100** [comment]
@rashil2000 I did not find a file that includes common utils. Or did I miss it?

**Comment by rashil2000** [comment]
lib/core.ps1
