### ISSUE TITLE
[Bug] Scoop checking ~/scoop instead of custom dir after update

### ISSUE THREAD

**Issue by Vedabahu** [ScoopInstaller/Scoop#4919]
#### Current Behavior
Instead of looking in the custom directory of scoop, it is looking in `C:\Users\Users\Scoop\` and giving me error. I tried removing scoop and reinstalling it. Showing the same problem.
`scoop help` Output:
![image](https://user-images.githubusercontent.com/79869936/168145669-82588a6b-b588-4a5d-978a-de32d6c4d603.png)

#### Expected Behavior

Look for buckets and all installs directly in the desired directory as in scoop's `config.json` file.

### System details

**Windows version:** 7

**OS architecture:** 64bit

**PowerShell version:** 
```powershell
PS D:\Vedabahu\Scoop> $PSVersionTable.PSVersion

Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      2      3
```

#### Scoop Configuration

```json
{
  "lastUpdate": "2022-05-12T23:26:56.2305288+05:30",
  "rootPath": "D:\\Vedabahu\\Scoop\\Scoop",
  "globalPath": "D:\\Vedabahu\\Scoop\\ScoopGlobal",
  "cachePath": "D:\\Vedabahu\\Scoop\\ScoopCache",
  "SCOOP_REPO": "https://github.com/ScoopInstaller/Scoop",
  "SCOOP_BRANCH": "master",
  "aria2-split": 16,
  "aria2-max-connection-per-server": 16,
  "aria2-warning-enabled": false,
  "MSIEXTRACT_USE_LESSMSI": true,
  "aria2-enabled": true
}
```

**Comment by rashil2000** [comment]
Hi! This sounds similar to https://github.com/ScoopInstaller/Scoop/issues/4918.

Can you post your findings in that issue? Thanks.
