### ISSUE TITLE
error in scoop update command

### ISSUE THREAD

**Issue by anvaralimov** [ScoopInstaller/Scoop#4926]
i have a scoop update error. I reinstalled it but it still didn't fix the bug

![photo_2022-05-16_11-22-16](https://user-images.githubusercontent.com/87275043/168531342-5b36df1f-1deb-424a-859e-d94b3b984b0a.jpg)

**Comment by HUMORCE** [comment]
try, and restore your config if it works.

```powershell
Rename-Item .config\scoop scoop.backup
scoop update
```
