### ISSUE TITLE
[Feature] (Cosmetic) if manifest not found, then scoop just reports the last-searched-bucket/manifest

### ISSUE THREAD

**Issue by quotidian-ennui** [ScoopInstaller/Scoop#4928]
## Feature Request

(Could be a bug, but is mainly cosmetic). If you try to do `scoop info` on a manifest that can't be found, then scoop reports that the manifest can't be found in the last bucket searched rather than just simply saying, "Couldn't find it in any bucket".

It's easiest to describe the behaviour with some logging : 

```powershell
PS C:\Users\Me> scoop bucket list

Name      Source                                    Updated             Manifests
----      ------                                    -------             ---------
extras    https://github.com/ScoopInstaller/Extras  16/05/2022 12:05:35      1501
java      https://github.com/ScoopInstaller/Java    14/05/2022 21:01:48       220
jetbrains https://github.com/Ash258/Scoop-JetBrains 13/05/2022 21:07:27        99
main      https://github.com/ScoopInstaller/Main    16/05/2022 10:43:16      1020
tilt-dev  https://github.com/tilt-dev/scoop-bucket  12/05/2022 22:24:02         0

PS C:\Users\Me scoop search posh
'extras' bucket:
    posh-docker (0.7.0)
    posh-git (1.1.0)

'main' bucket:
    oh-my-posh (7.85.0)

### This is is the problem command, mainly because I can't spell!
PS C:\Users\Me> scoop info pos-git
Could not find manifest for 'tilt-dev/pos-git'.
```

#### Describe the solution you'd like

It feels like it's as simple as changing https://github.com/ScoopInstaller/Scoop/blob/aaa726c09f786d2af902d827ae8d0caee964ca1e/libexec/scoop-info.ps1#L32-L34

so that you don't pass in `$bucket` so we can just have something like

```powershell
if (!$manifest) {
    abort "Could not find manifest for '$(show_app $app)' in any buckets"
}
```

```
PS C:\Users\Me> scoop info pos-git
Could not find manifest for 'pos-git' in any buckets.
```

**Comment by rashil2000** [comment]
Can you make a PR?

**Comment by quotidian-ennui** [comment]
Sure, since it's a (relatively) minor textual change I can raise a PR. I won't be able to run the tests since I'm not even sure how to start installing the BuildHelpers powershell modules etc.

**Comment by quotidian-ennui** [comment]
Since the PR has been merged, I guess we can close this issue.
