### ISSUE TITLE
[Bug] Config is ready when `$scoopdir` is populated

### ISSUE THREAD

**Issue by CrendKing** [ScoopInstaller/Scoop#4937]
#### Current Behavior
At https://github.com/ScoopInstaller/Scoop/blob/aaa726c09f786d2af902d827ae8d0caee964ca1e/lib/core.ps1#L1113, `$scoopdir` is attempted to be initialized as `get_config 'rootPath'` in case `$env:SCOOP` is empty. However, config file is only initialized, i.e. populating `$scoopConfig`, after that line. Therefore, `get_config 'rootPath'` always returns empty string.

#### Expected Behavior
Config file should be initialized before the three "dir" variables are populated.

#### Possible Solution
Move lines 1125 through 1137 above, to line 1111.

I can make PR if needed. Apologize in advance if I'm missing something obvious.

### System details

**Windows version:** 11

**OS architecture:** 64bit

**PowerShell version:** 7.2.4

#### Scoop Configuration

```json
{
  "lastupdate": "2022-05-18T14:56:58.7641392-07:00",
  "SCOOP_REPO": "https://github.com/ScoopInstaller/Scoop",
  "SCOOP_BRANCH": "master",
  "shim": "kiennq",
  "rootPath": "C:\\Scoop",
  "ignore_running_processes": true,
  "aria2-warning-enabled": false
}
```

**Comment by chawyehsu** [comment]
fixed in #4932
