### ISSUE TITLE
[Bug] `scoop search` for remote buckets might get irrelevant `json` files

### ISSUE THREAD

**Issue by amorphobia** [ScoopInstaller/Scoop#4943]
#### Current Behavior

```
scoop.ps1 search markdownlint
Results from other known buckets...
(add them using 'scoop bucket add <name>')

'versions' bucket (install using 'scoop install versions/<app>'):
    .markdownlint
```

The file `.markdownlint.json` is not an app manifest, but a profile of the (remote) bucket itself.

#### Expected Behavior

```
scoop.ps1 search markdownlint
No matches found.
```

#### Additional context/output

The regex in `scoop-search.ps1` matches all `json` files even if it's not in `bucket` directory:

```PowerShell
function search_remote($bucket, $query) {
    $uri = [System.Uri](known_bucket_repo $bucket)
    if ($uri.AbsolutePath -match '/([a-zA-Z0-9]*)/([a-zA-Z0-9-]*)(?:.git|/)?') {
        $user = $Matches[1]
        $repo_name = $Matches[2]
        $api_link = "https://api.github.com/repos/$user/$repo_name/git/trees/HEAD?recursive=1"
        $result = download_json $api_link | Select-Object -ExpandProperty tree |
            # I think the regex here is equivalent to "^(.*$query.*)\.json$"
            Where-Object -Value "^(?:bucket/)?(.*$query.*)\.json$" -Property Path -Match |
            ForEach-Object { $Matches[1] }
    }

    $result
}
```

#### Possible Solution

Only search for `json` files in `bucket` directory, as all known buckets retain this structure.

### System details

**Windows version: 10 Version 20H2 (OS Build 19042.1645)**

**OS architecture: 64bit**

**PowerShell version: 7.2.3**

**Additional software:**

#### Scoop Configuration

```json
{
  "aria2-enabled": false,
  "SCOOP_BRANCH": "master",
  "SCOOP_REPO": "https://github.com/lukesampson/scoop",
  "lastupdate": "2022-05-22T07:28:59.8324856+08:00"
}
```

**Comment by rashil2000** [comment]
The code searches in the root directory because of backward compatibility. Earlier, the 'bucket' directory wasn't standard, and a lot of community repos still don't have it.

**Comment by amorphobia** [comment]
I don't think there is necessary to do "backward compatibility" in remote search. Please note that 

1. **All** known buckets in `buckets.json` store their manifests in `bucket` directory. ([main](https://github.com/ScoopInstaller/Main), [extras](https://github.com/ScoopInstaller/Extras), [versions](https://github.com/ScoopInstaller/Versions), [nirsoft](https://github.com/kodybrown/scoop-nirsoft), [php](https://github.com/ScoopInstaller/PHP), [nerd-fonts](https://github.com/matthewjberger/scoop-nerd-fonts), [nonportables](https://github.com/TheRandomLabs/scoop-nonportable), [java](https://github.com/ScoopInstaller/Java), [games](https://github.com/Calinou/scoop-games))
2. This regex is **only** used for searching these remote buckets. (in function [`search_remote`](https://github.com/ScoopInstaller/Scoop/blob/aaa726c09f786d2af902d827ae8d0caee964ca1e/libexec/scoop-search.ps1#L59-L71))
