### ISSUE TITLE
[Bug] cannot install git with no manifest after install with -ScoopDir option

### ISSUE THREAD

**Issue by atsushifx** [ScoopInstaller/Scoop#4959]
#### Current Behavior

I install scoopinstaller locally with -ScoopDir option. command line is here.

.\inst.ps1 -ScoopDir C:\Users\atsushifx\app\scoop

After installed, I install git from scoop, but "Couldn't find manifest for 'git'."
 message is given.

#### Expected Behavior

can install git and can do it.

#### Additional context/output

check bucket by `scoop bucket list', this error message is outputted.

``` powershell
C: /temp # scoop bucket list
Get-Item: C:\Users\atsushifx\app\scoop\apps\scoop\current\lib\buckets.ps1:138
Line |
 138 |              $bucket.Updated = (Get-Item "$path\bucket").LastWriteTime
     |                                 ~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'C:\Users\atsushifx\scoop\buckets\main\bucket' because it does not exist.


Name Source               Updated Manifests
---- ------               ------- ---------
main ~\scoop\buckets\main                 0
```

expected bucket directory is '~/app/scoop/buckets', maybe scoop does not read config file.

#### Possible Solution

in lib/core.ps1, insert line 1125 to 1136 blocks to line 1112 to 
load config file before $scoopDir set up.

### System details

**Windows version:** [e.g. 7, 8, 10]
Windows 11 (22H2)

**OS architecture:** [e.g. 32bit, 64bit]
64bit

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]
7.2.4

**Additional software:** [(optional) e.g. ConEmu, Git]
Windows Terminal

#### Scoop Configuration

``` Environment
XDG_CONFIG_HOME=C:\Users\atsushifx\.config
```

```json
//# Your configuration here
{
  "SCOOP_REPO": "https://github.com/ScoopInstaller/Scoop",
  "SCOOP_BRANCH": "master",
  "rootPath": "C:/Users/atsushifx/app/scoop",
  "globalPath": "c:/app/scoop",
  "cachePath": "c:/app/scoop/.system/cache",
  "lastUpdate": "2022-05-31T22:55:43.4951545+09:00"
}
```

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Scoop/issues/4918
