### ISSUE TITLE
[Feature] scoop export  all what need file to tar.gz not only lists

### ISSUE THREAD

**Issue by zerols** [ScoopInstaller/Scoop#4963]
#### Is your feature request related to a problem? Please describe.

if network connect to github is terribel, maybe i need to copy all scoop file to another pc, and setting powershell and system env
#### Describe the solution you'd like

maybe we can adding a parameter like docker save to change all we need to a tar file ,not only a app list

**Comment by rashil2000** [comment]
Applications installed through Scoop store a large amount of machine-specific data/path locations in their installation or persist folders, so this is not recommended.
