### ISSUE TITLE
[Bug] scoop-virustotal is not working

### ISSUE THREAD

**Issue by ClassicDarkChocolate** [ScoopInstaller/Scoop#4965]
#### Current Behavior

It seems that this exists for a long time.

```powershell
> scoop virustotal imageglass
imageglass: VirusTotal request failed: The remote server returned an error: (429) Too Many Requests. 4
```

#### Expected Behavior

```powershell
> scoop virustotal imageglass
imageglass: 0/, see https://www.virustotal.com/#/file/8ee32ec15d2135e3a69ba4916d01908bc450cce5/detection
```

### System details

**Windows version:** [e.g. 7, 8, 10]

**OS architecture:** [e.g. 32bit, 64bit]

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
//# Your configuration here
```

**Comment by rashil2000** [comment]
Good catch! Can you make a PR?

**Comment by ClassicDarkChocolate** [comment]
After some investigations, Web api is now protected by a 'X-VT-Anti-Abuse-Header' headder.

So even getting a simple scan result now requires a api key too.

```diff
diff --git a/libexec/scoop-virustotal.ps1 b/libexec/scoop-virustotal.ps1
index b7d16cfe..9ab7dd7b 100644
--- a/libexec/scoop-virustotal.ps1
+++ b/libexec/scoop-virustotal.ps1
@@ -81,10 +81,12 @@ $explained_rate_limit_sleeping = $False
 $requests = 0

 Function Get-VirusTotalResult($hash, $app) {
+    $api_key = get_config virustotal_api_key
     $hash = $hash.ToLower()
-    $url = "https://www.virustotal.com/ui/files/$hash"
+    $url = "https://www.virustotal.com/api/v3/files/$hash"
     $wc = New-Object Net.Webclient
     $wc.Headers.Add('User-Agent', (Get-UserAgent))
+    $wc.Headers.Add('x-apikey', $api_key)
     $result = $wc.downloadstring($url)
     $stats = json_path $result '$.data.attributes.last_analysis_stats'
     $malicious = json_path $stats '$.malicious'
```

**Comment by rashil2000** [comment]
Can you give an example of package that asks for API key? I can still use the `/gui` link without errors.

**Comment by ClassicDarkChocolate** [comment]
> Can you give an example of package that asks for API key? I can still use the `/gui` link without errors.

It's embarrassing that the link I provided is not even valid. It's just that the scoop code consumes the invalid url and does not throw errors.

**Comment by ClassicDarkChocolate** [comment]
I have had a tested fix done.
