### ISSUE TITLE
[Bug] "persist" creates dir junction for missing files

### ISSUE THREAD

**Issue by gavenkoa** [ScoopInstaller/Scoop#4974]
I `scoop install idea`, it has:

```
    "extract_to": "IDE",
    "persist": [
        "IDE\\bin\\idea.properties",
        "IDE\\bin\\idea.exe.vmoptions",
        "IDE\\bin\\idea64.exe.vmoptions",
        "profile"
    ],
```

In the app archive the file `idea.exe.vmoptions` is missing and scoop created a junction dir for it:

```
dir /a
<JUNCTION>     idea.exe.vmoptions [\??\C:\opt\scoop\persist\idea\IDE\bin\idea.exe.vmoptions]
```

I'm not sure if it is possible to resolve the issue owing to the facts:

* Windows file cannot be a junction...
* If a resource is missing in the archive we don't know if it is a file or a dir
* Scoop creates dir junction for missing items
* Creation of empty file (if we have a syntax for marking a resource as a file `{"path": "IDE\\bin\\idea.exe.vmoptions", "type": "file"}`) for a missing file might break the app (could be the file is omitted in newer version for a reason)
* Later an app won't create a file because it is occupied by a dir.

Extended syntax for omitting missing files might be sufficient, like `{"path": "IDE\\bin\\idea.exe.vmoptions", "if-exists": "true"}`.

Original problem comes from the 32/64-bit flavor of installers: one of `idea.exe.vmoptions` or `idea64.exe.vmoptions` is missing...

**Comment by gavenkoa** [comment]
As suggested here:  https://github.com/ScoopInstaller/Scoop/issues/4757 the app installation script could perform some `"pre_install"` actions, like to create an empty file or remove a junction for file in `"post_install"`.

**Comment by gavenkoa** [comment]
Note: the problem is in two places: 

* the junction instead of the file in the  `apps\APP` dir
* the dir instead of the file in the `persist\APP` dir

This complicates possible cleanup actions in `"post_install"`.

**Comment by rashil2000** [comment]
> Scoop creates dir junction for missing items

Correct. If the path doesn't exist, Scoop will create a folder there and then create a junction for it. It's just a convention, not a bug. You can create an empty file in the `pre_install` script, as is done in many of the manifests.

Related #1372
