### ISSUE TITLE
[Feature] How to deal with manifest naming conflicts between different buckets?

### ISSUE THREAD

**Issue by so1ve** [ScoopInstaller/Scoop#4975]
#### Is your feature request related to a problem? Please describe.

In fact, there are two buckets here:
https://github.com/chawyehsu/dorado (community)
https://github.com/so1ve/destiny (mine)

Both buckets contain the `dvm` manifest. But their content is different.
If I add both buckets, when I run `scoop install dvm`, scoop will get the manifest in dorado, not the one in destiny.

#### Describe the solution you'd like

Maybe we can add a syntax: `scoop install destiny:dvm`?
Or add a parameter: `scoop install dvm -Bucket so1ve_destiny`?

#### Describe alternatives you've considered

as said above

**Comment by rashil2000** [comment]
`scoop install destiny/dvm`

**Comment by so1ve** [comment]
Damn. Never imagined.
