### ISSUE TITLE
[Bug] Scoop not updating

### ISSUE THREAD

**Issue by DOFfactory** [ScoopInstaller/Scoop#4980]
#### Current Behavior
Whenever I type `scoop update` I receive the following result:

> Scoop was updated successfully!

Then I type `scoop status`

> Scoop is up to date.
> Everything is ok!

However, when I type `scoop info librewolf`, I get the following:

> Name        : librewolf
> Description : A fork of Firefox, focused on privacy, security and freedom.
> Version     : 97.0
> Bucket      : extras
> Website     : https://librewolf.net
> License     : MPL-2.0
> Updated at  : 09/02/2022 13:39:39
> Updated by  : github-actions[bot]
> Installed   : 97.0
> Binaries    : librewolf.exe
> Shortcuts   : Librewolf

**The problem**: I know that the latest librewolf version should be 101.0

#### Expected Behavior
Update to the latest versions of apps.

#### Additional context/output
I tried to delete the whole scoop package system and recreated it from scratch, the result is the same.

#### Possible Solution
N/A

### System details

**Windows version:** Windows 10

**OS architecture:** 64bit

**PowerShell version:** 5.1.19041.1682

**Additional software:** N/A

#### Scoop Configuration

```json
{
    "SCOOP_BRANCH":  "master",
    "SCOOP_REPO":  "https://github.com/lukesampson/scoop",
    "lastupdate":  "2022-06-10T12:30:01.8050491+02:00"
}
```

**Comment by rashil2000** [comment]
scoop bucket rm extras
scoop bucket add extras
