### ISSUE TITLE
scoop install mupdf@<version> fails

### ISSUE THREAD

**Issue by brechtm** [ScoopInstaller/Scoop#4984]
## Bug Report

**Package Name:** mupdf

### Current Behaviour

```
PS C:\Users\Brecht> scoop install mupdf@1.18.0
WARN  Given version (1.18.0) does not match manifest (1.20.0-rc2)
WARN  Attempting to generate manifest for '/mupdf' (1.18.0)
Autoupdating /mupdf
Searching hash for mupdf-1.18.0-windows.zip in https://www.mupdf.com/releases/
Writing updated /mupdf manifest
Couldn't find manifest for 'mupdf'.
```

### Expected Behaviour

scoop installs mupdf 1.18.0

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** 5.1.19041.1645

#### Scoop Configuration

```json
{
    "lastupdate":  "2022-06-10T20:58:28.7705611+02:00",
    "SCOOP_REPO":  "https://github.com/lukesampson/scoop",
    "SCOOP_BRANCH":  "master"
}
```

**Comment by rashil2000** [comment]
Relevant PR: https://github.com/ScoopInstaller/Scoop/pull/4966

**Comment by hoilc** [comment]
> Ah, this might be bug due to a recent refactor. I'll transfer this issue to core.

For the same reason, `scoop install \path\to\app.json` is broken.

**Comment by niheaven** [comment]
Yes, the function needs a trimstart, and will be fix tommorow.
