### ISSUE TITLE
[Bug] Couldn't find manifest for 'adopt8-hotspot' from 'main' bucket

### ISSUE THREAD

**Issue by FEgguri** [ScoopInstaller/Scoop#4989]
PS C:\WINDOWS\system32> Set-ExecutionPolicy RemoteSigned -Scope CurrentUser

PS C:\WINDOWS\system32> $env:SCOOP='C:\Scoop'

PS C:\WINDOWS\system32> iex (New-Object net.webclient).DownloadString('https://get.scoop.sh')
Initializing...
Running the installer as administrator is disabled by default, see https://github.com/ScoopInstaller/Install#for-admin for details.
Abort.

PS C:\WINDOWS\system32> irm get.scoop.sh -outfile 'install.ps1'

PS C:\WINDOWS\system32> iex "& {$(irm get.scoop.sh)} -RunAsAdmin"
Initializing...
Downloading...
Extracting...
Creating shim...
Scoop was installed successfully!
Type 'scoop help' for instructions.

PS C:\WINDOWS\system32> scoop bucket add java
Checking repo... OK
The java bucket was added successfully.

PS C:\WINDOWS\system32> scoop install adopt8-hotspot
Couldn't find manifest for 'adopt8-hotspot' from 'main' bucket.

PS C:\WINDOWS\system32> scoop update
Updating Scoop...
Updating 'java' bucket...
Updating 'main' bucket...
 Converting 'main' bucket to git repo...
Checking repo... OK
The main bucket was added successfully.
Scoop was updated successfully!

PS C:\WINDOWS\system32> scoop bucket add java https://hub.fastgit.org/ScoopInstaller/Java.git
WARN  The 'java' bucket already exists. Use 'scoop bucket rm java' to remove it.
---------------------------------------------------------------------------------------------------------

I think the installation path of adopt8-hotspot is wrong, is there any way to fix it?

**Comment by niheaven** [comment]
The output is something mislead and there's no `adopt8-hotspot` in java bucket, please try other JRE 8 alternatives.
