### ISSUE TITLE
[Bug] Cannot hold and unhold apps if app is global and command is run without admin

### ISSUE THREAD

**Issue by sitiom** [ScoopInstaller/Scoop#4990]
#### Current Behavior

If the app is global and `hold` is run without admin, this error appears:
![image](https://user-images.githubusercontent.com/56180050/173982852-17c18a5f-e3ba-4ae3-ad80-0749280110c9.png)

Despite the "success" message, the `install.json` is not updated to reflect the change otherwise. The inverse is true for `unhold`:
![image](https://user-images.githubusercontent.com/56180050/173983173-711ebdc3-8023-4067-8b80-a9662b7a2f09.png)

#### Expected Behavior
It should successfully hold and unhold the apps

### System details

**Windows version:** 11

**OS architecture:** 64bit

**PowerShell version:** 7.2.4

#### Scoop Configuration

```json
{
  "lastupdate": "2022-06-16T08:47:17.2852108+08:00",
  "SCOOP_REPO": "https://github.com/ScoopInstaller/Scoop",
  "SCOOP_BRANCH": "master",
  "aria2-warning-enabled": false
}
```

**Comment by lewis-yeung** [comment]
Or should we show an error requiring for admin privileges in this use case? It's reasonable that operations on a global app need an elevated token.

**Comment by niheaven** [comment]
Yes, should be fixed.

> Or should we show an error requiring for admin privileges in this use case? It's reasonable that operations on a global app need an elevated token.

Could you submit a PR or I'll do it in a few days.

**Comment by lewis-yeung** [comment]
I notice that a `-g`/`--global` flag is not available for `scoop hold`/`scoop unhold`. I think this can be added for holding/unholding a globally installed app.

**Comment by lewis-yeung** [comment]
@niheaven See #4991.
