### ISSUE TITLE
[Bug] Scoop doesn't seem to exist after installation

### ISSUE THREAD

**Issue by Jamesking56** [ScoopInstaller/Scoop#4995]
#### Current Behavior
After installing Scoop as normal with a non-elevated PowerShell window, scoop doesn't appear to exist. After running `scoop help` I get this output:

```
scoop : The term 'scoop' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.
At line:1 char:1
+ scoop help
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (scoop:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException
```

#### Expected Behavior
Scoop is present after installation

### System details

**Windows version:** 11

**OS architecture:** 64bit

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]

```
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      22000  653
```

**Additional software:** [(optional) e.g. ConEmu, Git] Git, WSL2 with Ubuntu

#### Scoop Configuration

```json
{
    "lastUpdate":  "2022-06-18T18:47:24.1962107+01:00"
}
```

**Comment by rashil2000** [comment]
How did you install Scoop? Have you tried restarting the shell?

**Comment by Jamesking56** [comment]
Works after a reboot, not sure why I've had to reboot to get it to work though?

**Comment by rashil2000** [comment]
If you were using PowerShell, restarting shell is not required.

If you were using any other shell, the shell session needs to be restarted.

A reboot should not be required in any circumstances 😅

Let me know if you face any other problems.

**Comment by Jamesking56** [comment]
I was using Powershell, restarting Powershell didn't work I had to do a full reboot... Surely thats still a bug right?

**Comment by rashil2000** [comment]
How did you restart PowerShell (i.e. which terminal, or from Start Menu)?

**Comment by Jamesking56** [comment]
I was using Windows Terminal, closed and reopened it

**Comment by rashil2000** [comment]
The Terminal needs to be restarted because it will still have the old values in its instance/runspace (and hence all new tabs in that instance).
