### ISSUE TITLE
[Bug] `Couldn't find manifest` error occurs trying to install apps using local manifests

### ISSUE THREAD

**Issue by qyurila** [ScoopInstaller/Scoop#4999]
#### Current Behavior

```sh
> scoop install C:\foo\bar.json
Couldn't find manifest for 'bar'.
```

#### Expected Behavior

`bar` should be installed without issue, or a more appropriate error message should be given.

#### Additional context/output

I can assume that the `bar.json` file has no problem. When I try to install `bar` with a bucket that has the same `bar.json` file, `bar` is installed succesfully. But just in case, here is [one of the manifest files](https://github.com/qyurila/scoop-bucket/blob/master/bucket/wavetone.json) I used when the problem occured.

Also, IIRC this issue never happened with scoop 0.2.0.

### System details

**Windows version:** [e.g. 7, 8, 10]
11

**OS architecture:** [e.g. 32bit, 64bit]
64bit

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]
5.1.22000.653

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
{
    "rootPath":  "C:\\scoop",
    "lastUpdate":  "2022-06-20T23:14:48.5984179+09:00",
    "SCOOP_REPO":  "https://github.com/ScoopInstaller/Scoop",
    "SCOOP_BRANCH":  "master",
    "alias":  {

              },
    "aria2-warning-enabled":  false
}

```

**Comment by niheaven** [comment]
Will be fixed in version 0.2.2 (#4988)
