### ISSUE TITLE
[Feature] Autoupdate: Version variables that support letters (for example at the end)

### ISSUE THREAD

**Issue by RavenMacDaddy** [ScoopInstaller/Scoop#5030]
## Feature Request

I Googled "version variables that include letters scoop", but couldn't find anything and checked the _Issues_ a bit, but still couldn't find anything. 

I also went through the documentation to try and find a solution.

If a discussion for this feature is on-going or has been asked for previously, well that's that, feel free to close and refer.

#### Is your feature request related to a problem? Please describe.

I was in the process of creating a manifest for an emulator called [RAINE](https://raine.1emulation.com/).

This app for small bug fixes uses letters at the end for its versioning, which is fine for `checkver` thanks to `regex`, but I can't find the solution for the `autoupdate` property.

#### Describe the solution you'd like

A `version variable` that accounts for letters, for example at the end - e.g. _0.93.5b_, _0.93.5c_, _0.93.5d_ and so on which is the case with RAINE.

#### Describe alternatives you've considered

Replacing the versioning that's part of the new `URL` by using what was changed in the `regex` property, that's, the version - this was something I was looking for in the documentation.

This is risky though since the author of the app might change more than just the version-part.

**Comment by niheaven** [comment]
You mean version w/ letters? That's acceptable in scoop's manifest, and e.g., [Versions/7zip-zstd](https://github.com/ScoopInstaller/Versions/blob/master/bucket/7zip-zstd.json) has letters in its version number, and is this what you want?

**Comment by RavenMacDaddy** [comment]
So the example _0.93.5d_ is possible with $version, or have I misunderstood?
