### ISSUE TITLE
[Bug] scoop should try other URLs and continue update after a 403 error

### ISSUE THREAD

**Issue by val1984** [ScoopInstaller/Scoop#5035]
#### Current Behavior
I am behind a company proxy which blocks some downloads with ever changing rules and when I `scoop update *`, scoop will stop updating once it encounters a 403 error.

#### Expected Behavior
I would expect scoop to carry on after a 403 error:
- Try next URL for current package
- Update next package if there is no alternate URL for current package

#### Additional context/output
```
❯ scoop update *
autohotkey: 1.1.33.10 -> 1.1.34.03
groovy: 3.0.9 -> 4.0.3
Updating 2 outdated apps:
Updating 'autohotkey' (1.1.33.10 -> 1.1.34.03)
Downloading new version
OperationStopped: C:\Users\myuser\scoop\apps\scoop\current\lib\install.ps1:107
Line |
 107 |          throw $e
     |          ~~~~~~~~
     | The remote server returned an error: (403) URLBlockedExtended.
>
```

### System details

**Windows version:**
10 20H2

**OS architecture:**
64bit

**PowerShell version:**
7.2.5

#### Scoop Configuration
```json
{
  "lastupdate": "2022-07-04T13:31:21.2168552+02:00",
  "proxy": "currentuser@default",
  "SCOOP_REPO": "https://github.com/ScoopInstaller/Scoop",
  "SCOOP_BRANCH": "master",
  "shim": "kiennq"
}
```

**Comment by rashil2000** [comment]
> - Try next URL for current package

Not recommended since the install procedure might have a dependency on that downloaded item.

> - Update next package if there is no alternate URL for current package

Tracked here https://github.com/ScoopInstaller/Scoop/issues/4135

**Comment by rashil2000** [comment]
Fallback mirrors are being tracked https://github.com/ScoopInstaller/Scoop/issues/4264
