### ISSUE TITLE
[Feature] Provide a Json Schema for import and export json

### ISSUE THREAD

**Issue by zStruCat** [ScoopInstaller/Scoop#5037]
We currently already have json schema for manifest. For the sake of correctness, it seems appropriate to also have one for the import and export function.

**Comment by rashil2000** [comment]
I'm not sure it's necessary. The export file is not meant to be edited or even created by humans, unlike the package manifests. 

Completeness might not be a compelling reason here 😅

**Comment by snowman** [comment]
But then why now `scoop export` output JSON format?

```sh
$ scoop help export
Usage: scoop export > scoopfile.json

Options:
  -c, --config       Export the Scoop configuration file too
```

How to bring back the original format like below?
```text
7zip (v:21.07) [main]
aria2 (v:1.36.0-1) [main]
autohotkey (v:1.1.33.10) [extras]
```

**Comment by rashil2000** [comment]
Original format can't be brought back. It wasn't importable, so it was changed to JSON.

**Comment by snowman** [comment]
Maybe provide a switch to change output format like pip does?
1. `$ pip list --format freeze` 
2. `$ pip list --format json`

```sh
$ pip list --help
--format <list_format>
    Select the output format among: columns(default), freeze, or json
```

so `$ scoop export -f json` or `$ scoop export --format json` outputs JSON format, or set `JSON` format as default.
and `$ scoop export -f what-ever-name` export original format?

#### Solution:
To output the old format, use `jq` command

```bat
REM This is backup.bat file
scoop export | jq -r ".apps[] | \"\(.Name) (v:\(.Version)) [\(.Source)]\""
```

Anyway, for the reason you said, I would NOT bother to add switch output to the old format, I just leave a comment about what other people may think.
