### ISSUE TITLE
[Feature] Support a detection of a `scoop update` context

### ISSUE THREAD

**Issue by lewis-yeung** [ScoopInstaller/Scoop#5040]
### Is your feature request related to a problem? Please describe.

Currently, we don't have a proper way to detect if installing/uninstalling an app is part of a `scoop update` process. Sometimes we want to do something different for an app in an update context other than a fresh installation. For example, there may be no need to add entries to or clean up the registry during an update process. Without a detection of an update context, we have to perform a full uninstallation and a full installation in this use case, causing some steps to be redundant or even totally wrong.

### Describe the solution you'd like

Add a support of boolean variable `$in_update` for the `installer`/`uninstaller`/`pre_install`/`post_install`/`pre_uninstall`/`post_uninstall` script to detect if it is in a `scoop update` context.

**Comment by rashil2000** [comment]
> Currently, we don't have a proper way to detect if installing/uninstalling an app is part of a `scoop update` process.

We do. The `$cmd` variable holds the subcommand which is being run, and plenty of manifests utilize it. See: 

https://github.com/ScoopInstaller/Extras/blob/master/bucket/vscode.json#L54
https://github.com/ScoopInstaller/Extras/blob/master/bucket/spotify.json#L29
https://github.com/ScoopInstaller/Extras/blob/master/bucket/windows-terminal.json#L38
https://github.com/ScoopInstaller/Extras/blob/master/bucket/bioedit.json#L24

**Comment by lewis-yeung** [comment]
@rashil2000 Thanks for your help. BTW, I notice that `$cmd` is undocumented in [the Wiki page](https://github.com/ScoopInstaller/Scoop/wiki/Pre--and-Post-install-scripts). It is reasonable to add an entry so that all users can know this. 😄
