### ISSUE TITLE
[Wiki] Incorrect quotations of `scoop upgrade`

### ISSUE THREAD

**Issue by lewis-yeung** [ScoopInstaller/Scoop#5041]
In the Wiki page of [App Manifests](https://github.com/ScoopInstaller/Scoop/wiki/App-Manifests), there are two quotations of `scoop upgrade`, which should be corrected to `scoop update`.

**Comment by rashil2000** [comment]
Thanks for the info!

Fixed https://github.com/ScoopInstaller/Scoop/wiki/App-Manifests/_compare/06407ec8c510cd442c7bbfac2d0e63043dafbdd9
