### ISSUE TITLE
[Bug] Optionally disable remote-checking in `scoop status`

### ISSUE THREAD

**Issue by twirlse** [ScoopInstaller/Scoop#5044]
#### Current Behavior
scoop status takes ~3 times more time in v0.2.3 vs v.0.2.2

#### Additional context/output
scoop status in v0.2.3
![image](https://user-images.githubusercontent.com/52166/178531670-d0d35f6c-6171-4624-bdd7-c217fb73bc4c.png)

scoop status in v0.2.2
![image](https://user-images.githubusercontent.com/52166/178531785-03d2f7c7-56d3-43f8-a431-c9390f707c18.png)

top functions
![image](https://user-images.githubusercontent.com/52166/178532100-3783961c-9bf3-4a19-9ccd-2c9de531d965.png)

#### Possible Solution
It seems that in 0.2.3 Test-UpdateStatus is run for each bucket which is quite expensive.
![image](https://user-images.githubusercontent.com/52166/178532524-c4e28f1f-a89f-4bc6-a04a-a3bff327c077.png)

### System details
windows 11 (21H2 build 22000.778)
x64
ps core: 7.2.5
git version 2.37.0.windows.1

#### Scoop Configuration

```json
{
  "lastupdate": "2022-07-12T16:41:04.1824139+02:00",
  "SCOOP_REPO": "https://github.com/lukesampson/scoop",
  "SCOOP_BRANCH": "master",
  "shim": "kiennq",
  "aria2-warning-enabled": false
}
```

**Comment by twirlse** [comment]
I understand the rationale behind the change, however in my opinion this is a *major* degradation in performance. Perhaps it is possible to run those tests in parallel?

**Comment by twirlse** [comment]
I understand the rationale behind the change, however in my opinion this is a *major* degradation in performance. Perhaps it is possible to run those tests in parallel or to find some other solution? 

I wonder how often you are running status without running update first?
I personally don't really care about outdated buckets check in ```scoop status``` because I will always run ```scoop update``` first, and than scoop status (multiple times) in order to see what should be updated.

I thinks there should be a distinction in what is assumed for different scoop commands (local vs remote status).

I personally don't expect ```scoop status``` to check remote status for buckets.
Neither do I except ```scoop status``` to show me that there is a new scoop version. 
That is because there is no way (as far as I know) to rollback to previous scoop version or get latest buckets without updating scoop. So I just let scoop do it thing when I run ```scoop update```.
For me it'll be best to just remind a user to run scoop update before scoop status (if there are no faster solutions for remote status check) because it what I do naturally.

**Comment by rashil2000** [comment]
> I understand the rationale behind the change, however in my opinion this is a **major** degradation in performance. Perhaps it is possible to run those tests in parallel or to find some other solution?

I wouldn't really call it a degradation as this was a feature addition. It was requested a long time ago and many maintainers (including me) felt the need to make `scoop status` fully comprehensive. 


> I wonder how often you are running status without running update first? I personally don't really care about outdated buckets check in `scoop status` because I will always run `scoop update` first, and than scoop status (multiple times) in order to see what should be updated.

Technically any subcommand of Scoop should be independent of any other; I understand your particular workflow but the decision to include a particular feature should not depend on what other subcommand has been run previously. Obviously we don't have any stats on what commands users run and when they run it (because Scoop does not collect any data).

> I personally don't expect `scoop status` to check remote status for buckets. Neither do I except `scoop status` to show me that there is a new scoop version. That is because there is no way (as far as I know) to rollback to previous scoop version or get latest buckets without updating scoop. So I just let scoop do it thing when I run `scoop update`.

Removing those particular checks (by default) would be a breaking change for users.

----

Perhaps it would be best to explore alternative methods: such as parallel tasks as you said, or hide the remote checking behind some flag.

**Comment by aoisummer** [comment]
> Perhaps it would be best to explore alternative methods: such as parallel tasks as you said, or hide the remote checking behind some flag.

Maybe provide an option like `autoupdate: false` to prevent this behavior before update app or check status?

In fact, this behavior will often lead to operation failure in some places with poor network quality, I mean ISPs in some places deliberately degrade the network quality to github.

**Comment by goyalyashpal** [comment]
* https://github.com/ScoopInstaller/Scoop/issues/3818
