### ISSUE TITLE
[Feature] Status output: Improve the spacing/formatting for the text when an app has failed to install

### ISSUE THREAD

**Issue by RavenMacDaddy** [ScoopInstaller/Scoop#5046]
![image](https://user-images.githubusercontent.com/67732686/179066591-e5a8bb9d-291f-4992-b36d-93f7fca36ab0.png)

Noticed that the text was very tight for an app that didn't successfully install.

#### Is your feature request related to a problem? Please describe.

Not really a problem, just a matter of spacing and UI design.

#### Describe the solution you'd like

It could be:

**"Installation failed - Manifest removed"**

Something simple like that would instantly improve the design.

#### Describe alternatives you've considered

While testing the behavior by resizing the terminal window to be smaller or bigger, I didn't really find any alternatives coming to mind.

**Comment by lewis-yeung** [comment]
Related code:

https://github.com/ScoopInstaller/Scoop/blob/80b52e32a11fda2089949aaec00295d6185da3f7/libexec/scoop-status.ps1#L60

Easy to fix it: `$()` -> `@()`.
