### ISSUE TITLE
[Bug] Scoop Status emits ANSI codes which are not displayed correctly

### ISSUE THREAD

**Issue by quotidian-ennui** [ScoopInstaller/Scoop#5054]
#### Current Behavior

`scoop status` emits ansi codes in powershell 7.2.5 running in windows terminal. Note that `Scoop is up to date` is emitted in green, as is the `Scoop was updated successfully`. I know you're probably trying to show the table headers in green or similar, but it isn't working...

```
PS C:\Users\MyUser> scoop update
Updating Scoop...
Updating 'extras' bucket...
Updating 'java' bucket...
Updating 'jetbrains' bucket...
Updating 'main' bucket...
Updating 'tilt-dev' bucket...
Scoop was updated successfully!
PS C:\Users\MyUser> scoop status
Scoop is up to date.

←[32;1mName     Installed Version Latest Version   Missing Dependencies Info←[0m
←[32;1m----     ----------------- --------------   -------------------- ----←[0m
aws      2.7.0             2.7.16
```

### System details

**Windows version:** 11

**OS architecture:** 64

**PowerShell version:** 7.2.5

**Additional software:** Windows Terminal (1.13.11432.0)

#### Scoop Configuration

```json
{
  "lastupdate": "2022-07-19T09:17:37.9886304+01:00",
  "SCOOP_REPO": "https://github.com/lukesampson/scoop",
  "SCOOP_BRANCH": "master",
  "alias": {},
  "aria2-warning-enabled": false
}
```

**Comment by rashil2000** [comment]
Can you check if the following commands display the header colours correctly?

```
Get-InstalledModule
$PSVersionTable
scoop list
scoop bucket list
```

**Comment by quotidian-ennui** [comment]
I'm doing a select paste out of the terminal window, it appears all good (there's no visible ansi codes)

``
> Get-InstalledModule
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      7.2.5
```

```
> scoop list
Installed apps:

Name             Version                 Source           Updated             Info
----             -------                 ------           -------             ----
7zip             19.00                   <auto-generated> 2021-12-23 09:28:09
```

```
> scoop bucket list

Name      Source                                    Updated             Manifests
----      ------                                    -------             ---------
extras    https://github.com/ScoopInstaller/Extras  19/07/2022 05:49:45      1607
```

**Comment by quotidian-ennui** [comment]
As of 0953 2022-07-19; this is the output (so it's now correct, but wasn't 30 mins ago).

```
> scoop status
WARN  Scoop bucket(s) out of date. Run 'scoop update' to get the latest changes. // in yellow

Name    Installed Version Latest Version Missing Dependencies Info  // in green
----    ----------------- -------------- -------------------- ----  // in green.
aws     2.7.0             2.7.16
```

I do a scoop update; and run it again, and it's all still fine.

**Comment by markhewett** [comment]
@quotidian-ennui Do you know if you changed something to fix this?  I'm still seeing this issue.

![image](https://user-images.githubusercontent.com/1621581/180471490-5e8c4481-7d94-4775-a339-71a9b2d891d7.png)
