### ISSUE TITLE
[Bug] Scoop not properly installed into current version folder

### ISSUE THREAD

**Issue by xasx** [ScoopInstaller/Scoop#5058]
#### Current Behavior

When I run an all-new installed scoop in PS, I get an error message 
```

PS C:\Users\aschoeneck> scoop
&: C:\Users\aschoeneck\scoop\shims\scoop.ps1:3
Line |
   3 |  … on.ExpectingInput) { $input | & $path  @args } else { & $path  @args  …
     |                                                            ~~~~~
     | The term 'C:\Users\aschoeneck\scoop\shims\..\apps\scoop\current\bin\scoop.ps1' is not recognized as a
     | name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or if
     | a path was included, verify that the path is correct and try again.

PS C:\Users\aschoeneck>  irm get.scoop.sh | iex
Initializing...
Scoop is already installed. Run 'scoop update' to get the latest version.
Abort.

```

Checking for the `current` folder in the `app` directory, I only found `old` and `new` folders.

#### Expected Behavior

Scoop runs just fine.

#### Additional context/output

see above 

#### Possible Solution

Manually rename `new` to `current`.

### System details

**Windows version:** 10

**OS architecture:**  64bit

**PowerShell version:**

```
Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      2      5

```

#### Scoop Configuration

```json
{
    "lastUpdate":  "2022-07-20T18:23:53.1291462+02:00",
    "SCOOP_REPO":  "https://github.com/ScoopInstaller/Scoop",
    "SCOOP_BRANCH":  "master"
}

```

**Comment by rashil2000** [comment]
This error can happen if there's a network failure or other manual interruption during the install or update process.

You can delete the ~/scoop folder and try running `irm get.scoop.sh | iex` again.

**Comment by popovs** [comment]
I got a similar error and also fixed by renaming the 'new' directory to 'current'. Posting here in case its helpful to anyone in the future.

```
The argument 'C:\Users\SPOPOV\scoop\apps\scoop\current\bin\scoop.ps1' to the -File parameter does not exist. Provide the path to an existing '.ps1' file as an argument to the -File parameter.
```
