### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Masonta1976** [ScoopInstaller/Scoop#5060]
### System details

**Windows version:** [e.g. 7, 8, 10]

**OS architecture:** [e.g. 32bit, 64bit]

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
//# Your configuration here
```

**Comment by Masonta1976** [comment]
good stuffs

**Comment by HUMORCE** [comment]
re-edit then reopen
