### ISSUE TITLE
[Bug] Updating Scoop with admin rights in PowerShell and Git Global Config "init.defaultbranch" is not set results in error

### ISSUE THREAD

**Issue by Twoleeland** [ScoopInstaller/Scoop#5070]
#### Current Behavior
Running PowerShell (`pswh.exe` and `powershell.exe`) as Admin, trying to update scoop (or adding bucket "extras") results in error:
```
fatal: invalid branch name: init.defaultBranch=
```

#### Expected Behavior
1. Scoop should set itself `init.defaultBranch` or better, use a default value like `master`, if `init.defaultBranch` is empty (or not set or null), regardless of user mode (normal or elevated).
2. Error messages, like the above, should include the app name which is causing the error:
   -> in this case, "Git for Windows" which caused above error.
   -> till I found out what was causing this error, several hours were gone, because I thought it was a fault of Scoop and not Git! 😉

#### Possible Solution
After executing `git config --global init.defaultBranch master` described at StackOverflow [Git Error "fatal: invalid branch name: init.defaultBranch ="](https://stackoverflow.com/questions/64349920/git-error-fatal-invalid-branch-name-init-defaultbranch), I could update Scoop and add the bucket "extras" without any problems anymore.

It would be far better if you could set default values within Scoop that can be used by Scoop when such values as `init.defaultBranch` are set incorrectly or even not set at all.
Or add a default configuration for Git (- and also for other tools you use in Scoop -) and use the values of this configuration if the values are not set correctly as expected by Scoop. This way, such errors could be avoided in the future! 😉

Translated with www.DeepL.com/Translator (free version)

### System details
| | Version |
| --- | --- |
| **Windows** | 10 Business v21H2 Build 19044.1865 |
| **OS architecture** | 64bit |
| **PowerShell** (`pwsh.exe`) | 7.2.5 |
| **PowerShell** (`powershell.exe`) | 5.1.19041.1682 |
| **Git for Windows** | 2.37.1 |

**Comment by rashil2000** [comment]
See #3707
