### ISSUE TITLE
[Feature]  Completely portable, with no path modification and start menu mod

### ISSUE THREAD

**Issue by JesseRacine** [ScoopInstaller/Scoop#5071]
Is there any consideration on making a completely portable install for Scoop? I know that you can use env variables to control the install directory, but I would also like to prevent it from installing anything in the start menu, and also prevent it from modifying the path. Basically I want a completely isolated, portable install.

**Comment by rashil2000** [comment]
> I would also like to prevent it from installing anything in the start menu

Changing/disabling the location of Start Menu shortcuts is being tracked here - https://github.com/ScoopInstaller/Scoop/issues/2124

> prevent it from modifying the path

This is being tracked here - https://github.com/ScoopInstaller/Scoop/issues/1813

**Comment by candrapersada** [comment]
is there an option to make `\.config\scoop` portable?

**Comment by rashil2000** [comment]
No, see https://github.com/ScoopInstaller/Scoop/issues/4498

**Comment by hagaigold** [comment]
I start a discussion about this here - #5675
