### ISSUE TITLE
Scoop won't allow update conflicting files[Bug] 

### ISSUE THREAD

**Issue by ZeldrexK0DE** [ScoopInstaller/Scoop#5076]
Installing or updating tools retunrs this aswell as trying to run the update on its own, I do use bitdefender but its not being blocked in its current state. I don't know where these files are located but completely reinstalling scoop which includes removing the folder from my userprofile folder doesn't solve the problem.

![image](https://user-images.githubusercontent.com/83987610/182406820-dddf1294-2f68-4f74-973a-29268c1ce2eb.png)

Using W10 pro x64 Terminal Powershell 7.3.0 preview 6

#### Scoop Configuration

`{
  "lastUpdate": "2022-07-13T19:50:33.3414392+02:00",
  "SCOOP_REPO": "https://github.com/ScoopInstaller/Scoop",
  "SCOOP_BRANCH": "master"
}
`

**Comment by r15ch13** [comment]
Go to `~\scoop\apps\scoop\current` (or `%USERPROFILE%\scoop\apps\scoop\current`) and run `git reset --hard` and it should work again.

**Comment by ZeldrexK0DE** [comment]
Tried running the command, I believe it did reset but the error still persists.
![image](https://user-images.githubusercontent.com/83987610/182436497-15beb5ab-286f-4224-bc43-17edd17785b3.png)

**Comment by r15ch13** [comment]
Try deleting those files and then try `git reset --hard` again. Seems like those file have CR/LF problems.

**Comment by ZeldrexK0DE** [comment]
Alright that did it, thnks

> Try deleting those files and then try `git reset --hard` again. Seems like those file have CR/LF problems.
