### ISSUE TITLE
[Feature] Add custom "don't update" list for installed apps

### ISSUE THREAD

**Issue by quantuumsnot** [ScoopInstaller/Scoop#5079]
## Feature Request
Add custom "don't update" list for installed apps

#### Is your feature request related to a problem? Please describe.
Yes, there's always a chance some apps don't like to be updated on some heavily modified systems and fail very destructively (missing configs or data)

#### Describe the solution you'd like
Example command:
`scoop ban appname` - for adding the app to the update banlist
`scoop unban appname` - for removing the app from the update banlist

**Comment by rashil2000** [comment]
Please read the Scoop help documentation before posting.

`scoop hold app` for adding the app to the update banlist

`scoop unhold app` for removing the app from the update banlist

**Comment by quantuumsnot** [comment]
Well, good point. Also I should knew when this improvement was implemented, right?

**Comment by rashil2000** [comment]
3 years ago - https://github.com/ScoopInstaller/Scoop/pull/3444

**Comment by quantuumsnot** [comment]
Good, but you still think that the user is required to read the whole functionality, right? :D

**Comment by rashil2000** [comment]
Umm, yes?

The user should at least run the very basic `scoop` command to see what features are available - that's the very first thing people do after installing something.

![image](https://user-images.githubusercontent.com/46838874/182678121-9f8c6f57-39f2-4ee4-80e5-32ba5d0f7a0a.png)

**Comment by quantuumsnot** [comment]
So, yeaaaah ... The user also asks him/herself why the command is named `hold` :D

Bye!
