### ISSUE TITLE
[Feature] Add description about `pre_uninstall` and `post_uninstall` in `App-Manifests` Wiki

### ISSUE THREAD

**Issue by yi-Xu-0100** [ScoopInstaller/Scoop#5084]
#### Is your feature request related to a problem? Please describe.

I did not find `pre_uninstall` and `post_uninstall` in [App-Manifests](https://github.com/ScoopInstaller/Scoop/wiki/App-Manifests) Wiki. Did it missing?
#### Describe the solution you'd like

Add description about `pre_uninstall` and `post_uninstall` in [App-Manifests](https://github.com/ScoopInstaller/Scoop/wiki/App-Manifests) Wiki.
#### Describe alternatives you've considered

I searched the `pre_uninstall` to find it in this repository, and find #5040, then I got it description with [Pre-and-Post-install-and-uninstall-scripts](https://github.com/ScoopInstaller/Scoop/wiki/Pre-and-Post-install-and-uninstall-scripts), but the link is broken.

I can find the right link in Wiki overview is [Pre-Post-(un)install-scripts](https://github.com/ScoopInstaller/Scoop/wiki/Pre-Post-(un)install-scripts). May we can add the description about `pre_uninstall` and `post_uninstall` in [App-Manifests](https://github.com/ScoopInstaller/Scoop/wiki/App-Manifests) Wiki and introduction the `Pre-Post-(un)install-scripts` in description?

I can not edit the Wiki, so I can not make a PR to fix this issue. Hope for your help!❤️

**Comment by rashil2000** [comment]
Thanks for the heads up!

Updated https://github.com/ScoopInstaller/Scoop/wiki/App-Manifests/_compare/a97d90580434a5c4194ff505a9a53b150cee99d6
