### ISSUE TITLE
[Bug] on install or updates newest version of application of multiple buckets not taken

### ISSUE THREAD

**Issue by shakeyourbunny** [ScoopInstaller/Scoop#5086]
#### Current Behavior

If you have multiple buckets in your scoop installation and they have the same packages, but with different versions, only the version of the alphabetical first bucket is taken, ignoring other versions.

#### Expected Behavior

scoop should take the version of the application with the highest version number and not the first one of the alphabetical first bucket in the list.

#### Additional context/output

````
PS > scoop search windows-terminal
Results from local buckets...

Name                          Version      Source                 Binaries
----                          -------      ------                 --------
windows-terminal              1.14.1861.0  anderlli0053_DEV-tools
Windows-Terminal              1.12.10393.0 dodorz_scoop
windows-terminal              1.14.1962.0  extras

PS > scoop install windows-terminal
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
WARN  To disable this warning, run 'scoop config aria2-warning-enabled false'.
Installing 'windows-terminal' (1.14.1861.0) [64bit]
...
'windows-terminal' (1.14.1861.0) was installed successfully!
````
scoop should install 1.14.1962.0 from the extras bucket, not 1.14.1861.0 from anderlli0053_DEV-tools.

#### Possible Solution

A solution would be, that you implement repository/bucket priorities ( 0 .. 99 ) management, where scoop should go through the priority list and look first at the higher priority number buckets first down to to lower priority buckets. Standard buckets should have priority 90, community buckets should have default priority 50 or so.

perhaps a new bucket command like eg
PS > scoop bucket priority list|set/get bucketname (priority)

scoop bucket priority list may be redundant if it is integrated within scoop bucket list.

in addition improve the scoop install, status and update command with these flags:

-b|--bucket bucketname  -> use explicitly this bucket for installation (not usable with -n in combination)
-n|--numeric  -> ignore priority system and check all buckets for the most recent version of an application. allow change of bucket source for application

standard behaviour should be the priority system.

example outputs
````
PS > scoop bucket list
Name                         Source                                             Updated              Manifests      Priority
----                         ------                                             -------              ---------       -------
anderlli0053_DEV-tools       https://github.com/anderlli0053/DEV-tools/         8/6/2022 10:50:47 AM      6996       50
dodorz_scoop                 https://github.com/dodorz/scoop                    7/29/2022 4:32:31 PM         0       50
extras                       https://github.com/ScoopInstaller/Extras           8/6/2022 10:29:35 AM      1636       90
main                         https://github.com/ScoopInstaller/Main             8/6/2022 10:30:53 AM      1069       90
````

standard behaviour (with prorities active)
````
scoop install windows-terminal
Installing 'windows-terminal' (1.14.1962.0) [64bit]
...
'windows-terminal' (1.14.1962.0) was installed successfully!
````

force numerical installation (with warning message)
````
scoop install --bucket anderlli0053_DEV-tools windows-terminal
WARN: forcing bucket source to "anderlli0053_DEV-tools".
Installing 'windows-terminal' (1.14.1861.0) [64bit]
...
'windows-terminal' (1.14.1861.0) was installed successfully!
````

now, I am updating windows-terminal with the --numerical flag
````
scoop update -n windows-terminal
WARN: newer version in bucket 'extras' found, forcing update to 1.14.1962.0.
WARN: original bucket was 'anderlli0053_DEV-tools'
....
'windows-terminal' was updated to 1.14.1962.0 successfully!
````
Note that without the -n flag, scoop update windows-terminal SHOULD NOT switch the bucket source, but just inform that a newer version may available elsewhere.
````
 scoop update windows-terminal
windows-terminal: 1.14.1861.0 (latest version, installed)
windows-terminal: 1.14.1962.0 available in 'extras'.
Latest versions for all apps are installed! For more information try 'scoop status'
````

### System details

**Windows version:** [e.g. 7, 8, 10] 10

**OS architecture:** [e.g. 32bit, 64bit] 64 Bit

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`] 5.1.19041.1682

**Additional software:** [(optional) e.g. ConEmu, Git]

**Comment by niheaven** [comment]
You should install it with `scoop install extras/windows-terminal`.
