### ISSUE TITLE
[Bug]scoop shim info : ERROR: Option -global not recognized.

### ISSUE THREAD

**Issue by sebma** [ScoopInstaller/Scoop#5094]
#### Current Behavior
Hi, I'm trying to display the scoop shim information of the `sudo` command : 
```shell
# scoop shim info sudo
Local shim not found: sudo
But a global shim exists, run 'scoop shim info sudo -global' to show its info
```
This comment suggest us to type the command **scoop shim info sudo -global** : 
```shell
# scoop shim info sudo -global
ERROR: Option -global not recognized.
Usage: scoop shim <subcommand> [<shim_names>] [<command_path> [<args>...]] [-g(lobal)]
```
#### Expected Behavior
The shim information of `sudo` is displayed.

### System details

**Windows version:** 10 Pro

**OS architecture:** 64bit

**PowerShell version:**
```powershell
# echo $PSVersionTable.PSVersion
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      19041  1682
```
**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
{
    "lastUpdate":  "2022-08-10T17:20:34.7655612+02:00",
    "SCOOP_REPO":  "https://github.com/ScoopInstaller/Scoop",
    "SCOOP_BRANCH":  "master"
}
```

**Comment by lewis-yeung** [comment]
Related code:

https://github.com/ScoopInstaller/Scoop/blob/4a31bd330244f7f89f16208cdddda3f9edac2d65/libexec/scoop-shim.ps1#L71-L76

**Comment by rashil2000** [comment]
Discussion about avoiding `getopt` is here: https://github.com/ScoopInstaller/Scoop/pull/4736

**Comment by lewis-yeung** [comment]
@rashil2000 @niheaven Alternatively, we can make `getopt` compatible with the GNU extensions to the POSIX conventions for command line options. See [The GNU C Library Reference Manual](https://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html):

> The argument -- terminates all options; any following arguments are treated as non-option arguments, even if they begin with a hyphen.

If so, we have to use `'--'` in PowerShell CLI since the unquoted `--` is also the terminator flag in PowerShell syntax, which makes it excluded from `$args`.

**Comment by niheaven** [comment]
Hmm, it's a bug, yes. I'll fix it.

**Comment by niheaven** [comment]
https://github.com/ScoopInstaller/Scoop/blob/4a31bd330244f7f89f16208cdddda3f9edac2d65/lib/commands.ps1#L32-L36

The above function handles parameters and something likes `-g` is passed as string, and could not be treated as switch...

![image](https://user-images.githubusercontent.com/5832170/184316372-9e976ab3-d6e6-4ce0-b6e8-b1c2662fb7f2.png)

I'm not sure how to fix it (we've discussed that `getopt` cannot handle param of the shim) 🤣

**Comment by lewis-yeung** [comment]
> The above function handles parameters and something likes `-g` is passed as string, and could not be treated as switch...

I noticed this while debugging yesterday. So IMO, we definitely have to give up the current way of parsing arguments in the `shim` subcommand.

> we've discussed that `getopt` cannot handle param of the shim

Why? If we just introduce the terminator flag `--` and tweak the invocation method in the shims as I mentioned in [this comment](https://github.com/ScoopInstaller/Scoop/issues/5094#issuecomment-1211692946), it works well with `getopt` in my test. The only fly in the ointment is that users have to use a quoted version (`'--'`) either in PowerShell or CMD CLI. Another reason I recommend using `getopt` is that it makes the argument parsing far more consistent with other subcommands.

**Comment by niheaven** [comment]
`scoop shim add xxxx -g` if the shim needs `-g` as its param.

I'll test `--` and find the way.

**Comment by lewis-yeung** [comment]
> `scoop shim add xxxx -g` if the shim needs `-g` as its param.

💡 This can also be resolved if the terminator flag `--` is introduced.

**Comment by lewis-yeung** [comment]
@niheaven Anything I can do to help?

**Comment by sebma** [comment]
The weird thing is also that `scoop info shim sudo` does not find the shim for sudo although it is there : 
```powershell
# scoop shim info sudo
Local shim not found: sudo
But a global shim exists, run 'scoop shim info sudo -global' to show its info
# (gcm sudo -ShowCommandInfo | Out-String).Trim()
Name          : sudo.exe
ModuleName    :
Module        : @{Name=}
CommandType   : Application
Definition    : C:\ProgramData\scoop\shims\sudo.exe
ParameterSets : {}
```

**Comment by lewis-yeung** [comment]
> We should also change to use the call operator (`&`) in .cmd -> .ps1 shims and use `'--'` to pass an exact `--` argument in CMD.

@niheaven Sorry, I made a mistake. 🤦🏻‍♂️ We don't have to change this. Using `--` directly in CMD is just fine.

File `test.ps1`:

```powershell
$args
```

File `test.cmd`:

```cmd
pwsh -file test.ps1 %*
```

Run `test.cmd arg1 -- arg2` in CMD, output: 

```
arg1
--
arg2
```

**Comment by niheaven** [comment]
Yes, I've found that, and cannot continue 🤣

**Comment by lewis-yeung** [comment]
Let me try. I'll create PRs for this later.
