### ISSUE TITLE
[Feature]Please update the "credential.helper" in "wiki/Github-with-SSH-key" according to the notes in "ScoopInstaller/Main/bucket/git.json"

### ISSUE THREAD

**Issue by sebma** [ScoopInstaller/Scoop#5097]
Hi,

Your [Github-with-SSH-key wiki page](https://github.com/ScoopInstaller/Scoop/wiki/Github-with-SSH-key#use-pshazz-to-remember-your-password) says to set the `credential.helper` to `manager` but the notes in [`git.json`](https://github.com/ScoopInstaller/Main/blob/master/bucket/git.json) suggest to set it to `manager-core` : 
```shell
$ curl -s https://github.com/ScoopInstaller/Main/raw/master/bucket/git.json | jq -r .notes
Set Git Credential Manager Core by running: "git config --global credential.helper manager-core"
```

**Comment by HUMORCE** [comment]
Fixed.

Thank you!
