### ISSUE TITLE
[Feature] scoop info [app] 可以支持查看软件的所有版本（Can support viewing all versions of the software）

### ISSUE THREAD

**Issue by Edge-coordinates** [ScoopInstaller/Scoop#5105]
我希望有一个命令可以支持查看某个软件得所有版本，通过version仓库来做到这一点会使得我的搜索结果中出现大量的冗余选项，目前，我感觉scoop info [app] 除了查看软件信息，也可以支持查看这个软件的所有版本，它可以直接展开版本，也可以通过参数做到这一点，对于有的时候需要安装特定版本的我来说，这个功能是必要的，这样就可以不用打开官网查看版本列表了，谢谢您！

Translate via Google：
I wish there was a command that would support viewing all versions of a software, doing this through the version repository would make my search results a lot of redundant options, currently, I feel like scoop info [app] is not just for viewing software information , it can also support viewing all versions of this software, it can directly expand the version, or it can do this through parameters. For me who sometimes need to install a specific version, this function is necessary, so that I don't need to open it. Check out the version list on the official website, thank you!

我期望的是列出所有可以使用scoop安装的该软件的版本，比如对于V2rayn，我可以通过scoop install v2rayn@5.25来安装5.25版本的软件，但是，这样做的前题是我知道该软件版本存在且合法，我希望有一个命令可以得到该软件的所有可被安装版本，这样会很方便，谢谢。

Translate via Google：
I want to list all the versions of the software that can be installed using scoop, for example, for V2rayn, I can install version 5.25 by scoop install v2rayn@5.25, however, the premise of this is that I know the software Versions exist and are legal, I wish there was a command to get all installable versions of the software, that would be handy, thanks.

谢谢大家提供的帮助，我希望这个问题可以早日得到解决。
Thank you all for your help, I hope this issue can be resolved soon.

**Comment by rashil2000** [comment]
Can you explain what you mean by all versions of a software? Do you mean something like what the `scoop search` command shows?

**Comment by lewis-yeung** [comment]
> 对于有的时候需要安装特定版本的我来说，这个功能是必要的

> For me who sometimes need to install a specific version, this function is necessary

@Edge-coordinates If you want to install a specific version (not the latest in the existing app manifest), you can just run a command like `scoop install app-name@version-number` so that Scoop will try to generate a manifest for the version from the existing one in local buckets. Note that it has a precondition: the version number must be valid and the existing app manifest (JSON file) MUST have an `autoupdate` section which tells how to update the app download URL(s) and hash.

**Comment by Edge-coordinates** [comment]
> Can you explain what you mean by all versions of a software? Do you mean something like what the `scoop search` command shows?

我的意思是列出所有可以使用scoop安装的该软件的版本，比如对于V2rayn，我可以通过`scoop install v2rayn@5.25`来安装5.25版本的软件，但是，这样做的前题是我知道该软件版本存在且合法，我希望有一个命令可以得到该软件的所有可被安装版本，这样会很方便，谢谢。

Translate via Google：
I mean to list all the versions of the software that can be installed using scoop, for example, for V2rayn, I can install version 5.25 by `scoop install v2rayn@5.25`, however, the premise of this is that I know the software Versions exist and are legal, I wish there was a command to get all installable versions of the software, that would be handy, thanks.

**Comment by Edge-coordinates** [comment]
> > 对于有的时候需要安装特定版本的我来说，这个功能是必要的，这样就可以不用打开官网查看版本列表了
> 
> > For me who sometimes need to install a specific version, this function is necessary, so that I don't need to open it.
> 
> @Edge-coordinates `scoop search app-name` is somewhat helpful. However, not all versions of any app are available in Scoop buckets since all app manifests are maintained by the community. In fact, each app version is respected as a separate app in a Scoop bucket.

是的，但是如图所示，它表现的比较凌乱。
Yes, but as the picture shows, it behaves messy.
![image](https://user-images.githubusercontent.com/68896486/184543400-dfd60c73-79b8-48e4-b2bb-f7f30cdcce1d.png)

我期望的结果是在使用如图中`scoop info python`命令的时候可以获得该软件的完整版本列表：
The result I expect is to get a full list of versions of the software when using the `scoop info python` command as shown:
![image](https://user-images.githubusercontent.com/68896486/184543514-c33ede7b-e459-4e1f-a753-d2e1df1ff425.png)

谢谢您的帮助！
Thank you for your help!

**Comment by huangyinhaow** [comment]
https://user-images.githubusercontent.com/64564727/184543758-914da87e-5889-4efe-bd56-5d310f4c46a1.mp4

**Comment by Edge-coordinates** [comment]
> WindowsTerminal_GW3zulU7Lx.mp4

谢谢您提供的例子，它真是太棒了！
Thanks for the example, it's awesome!

**Comment by Edge-coordinates** [comment]
我明白您的意思，但是我期望一个命令，可以获取所该软件支持的版本，谢谢。
Translate via Google
I see what you mean, but I was expecting a command that would get the
version supported by the software, thanks.

L. Yeung ***@***.***> 于2022年8月14日周日 20:26写道：

**Comment by rashil2000** [comment]
@Edge-coordinates What you're asking is not possible. Scoop follows a rolling release model, so only the latest 'version' of a manifest is available, and all older 'versions' are auto-generated from that latest manifest. Even then, the generated manifest is not guaranteed to work because developers sometimes remove older release artifacts, or change the installation method etc. 

There's a request to pipe the results of `scoop search` into `scoop info`, tracked here: #4889

**Comment by lewis-yeung** [comment]
> 是的，但是如图所示，它表现的比较凌乱。
> Yes, but as the picture shows, it behaves messy.

@Edge-coordinates `scoop search` 的输出包含了一组对象，你可以利用 PowerShell 的格式化功能剔除其中的冗余信息，只保留你想要的属性列，例如：

```powershell
scoop search python | Format-Table -Property @('Name', 'Version')
```

至于你想要的功能（命令）无法在 Scoop 实现，我和楼上也已经解释得很清楚了，Scoop 仓库的维护工作并不包括记录某软件的所有可用版本。软件版本列表的维护和发布是软件开发者的责任。😄

**Comment by Edge-coordinates** [comment]
> @Edge-coordinates What you're asking is not possible. Scoop follows a rolling release model, so only the latest 'version' of a manifest is available, and all older 'versions' are auto-generated from that latest manifest. Even then, the generated manifest is not guaranteed to work because developers sometimes remove older release artifacts, or change the installation method etc.
> 
> There's a request to pipe the results of `scoop search` into `scoop info`, tracked here: #4889

OK，thank you for your help！

**Comment by Edge-coordinates** [comment]
> > 是的，但是如图所示，它表现的比较凌乱。
> > Yes, but as the picture shows, it behaves messy.
> 
> @Edge-coordinates `scoop search` 的输出包含了一组对象，你可以利用 PowerShell 的格式化功能剔除其中的冗余信息，只保留你想要的属性列，例如：
> 
> ```powershell
> scoop search python | Format-Table -Property @('Name', 'Version')
> ```
> 
> 输出仅保留「名称」和「版本」两列，相对简洁：
> 
> ```
> Results from local buckets...
> 
> Name      Version
> ----      -------
> python    3.10.6
> python39  3.9.13
> python    3.10.6
> winpython 3.10.5.0
> ```
> 
> 当然，这也仅能列出收录在 Scoop 仓库中的版本。至于你想要的功能（命令）暂时无法在 Scoop 实现，我和楼上也已经解释得很清楚了，Scoop 仓库的维护工作并不包括记录某软件的所有可用版本。软件版本列表的维护和发布是软件开发者的责任。😄

我现在明白您的意思了，非常感谢您提供的帮助，但是我仍然比较好奇，scoop是怎么在不存储旧的软件版本的情况下生成该版本的软件的，既然scoop可以生成该版本的软件，那么scoop十分可以在将来通过某种方案得知他到底可以生成该软件得那些版本，从而获得所有的可以生成得版本。

> the generated manifest is not guaranteed to work because developers sometimes remove older release artifacts, or change the installation method etc.

对于这一点，我非常清楚这是一个问题，但是，这不妨碍您可以先列出可能支持得软件版本（用户可以通过配置打开这个功能），这样可以通过试安装来发现到底是否可以安装该版本（不管怎样，我最起码是搜索过这个软件的，在装一下也不是很费事）。
我所希望的这一切，归根结底是希望可以在命令行解决的问题就不用打开浏览器，毕竟如果我想要安装一个旧版本号的V2rayn的话，我还要先上官网查看所有支持的版本，在使用scoop安装，我其实不如直接从官网上下载。。。
依然谢谢您提供的帮助。
另：添加了Version bucket 后，我的搜索时间大大的增长，这还是比较讨厌的。

**Comment by lewis-yeung** [comment]
@Edge-coordinates

> scoop是怎么在不存储旧的软件版本的情况下生成该版本的软件的

准确地说，是生成某个软件的清单（app manifest）。并非所有软件清单都有自动更新的能力，你之前提到的安装特定版本的方法（例如 `scoop install v2rayn@5.25`）生效的前提条件之一是软件清单中包含一个有效的 `autoupdate` 配置段，这样 Scoop 才明白如何去获取该软件的最新版本，并尝试更新清单中的版本号、下载 URL(s) 及文件 hash（可选）等。据我所知，获取最新版本号等更新信息所采用的手段主要是在网页源中进行正则匹配，如果你感兴趣，可以查看[相关代码](https://github.com/ScoopInstaller/Scoop/blob/4a31bd330244f7f89f16208cdddda3f9edac2d65/lib/manifest.ps1#L135-L157)以了解这一逻辑（并不复杂）。

> scoop是否可以在将来通过某种方案得知他到底可以生成该软件得那些版本，从而获得所有的可以生成得版本。

正如我之前所述，软件版本的更新是软件开发者负责的，其版本号的变化方式、公布途径以及开发者是否保留旧版本等因素千变万化，而软件清单由 Scoop 社区维护，自动更新也是滞后的。从逻辑复杂度层面来讲，获取所有版本号并非易事：就某些托管在 GitHub 上的软件而言，我们可以从 tags, releases 或 changelog 等信息获取所有已知版本号；有些在官网有 changelog 的软件也还好说；但其他软件就比较难办，甚至不可能。如果采取在清单中保留旧版本号的做法，确实很容易实现你想要的 `scoop info <app>` 列出所有可用版本的需求，但那样只能记录该功能上线之后更新的软件版本号，且 Scoop 无法确保这些版本号之后能够一直有效。从效益层面讲，考虑到适用该功能的软件可能只占较少数，我猜短期内不会实现（当然，如果你愿意提交 PR 的话就不一样了 😜）。至于更远的将来能否实现，就取决于需求与效益的平衡了。Scoop 任何新功能的实现都依赖开源社区，一个新功能的需求量大时，其关注度和价值自然就高，也会有更多积极提方案、交 PR 的人。

> 添加了Version bucket 后，我的搜索时间大大的增长，这还是比较讨厌的。

`scoop search` 的逻辑是：搜索**所有**本地仓库（local buckets）的**所有**软件清单。若找不到任何结果，才会搜索远程的已知仓库（known buckets）。

当前 Versions 仓库中软件清单总数不到 350 个（可以使用 `scoop bucket list` 查看所有本地仓库的详细信息），按理来说影响不会很大。我的本地仓库总共只有 5 个（也包含 Versions 仓库），软件清单总数接近 1700 个。`scoop search python` 肯定只搜索了本地仓库。我的电脑上跑一次耗时在 2.6s 左右，不知你那边耗时是多少。

**Comment by Edge-coordinates** [comment]
> @Edge-coordinates
> 
> > scoop是怎么在不存储旧的软件版本的情况下生成该版本的软件的
> 
> 准确地说，是生成某个软件的清单（app manifest）。并非所有软件清单都有自动更新的能力，你之前提到的安装特定版本的方法（例如 `scoop install v2rayn@5.25`）生效的前提条件之一是软件清单中包含一个有效的 `autoupdate` 配置段。「根据给定版本号自动生成清单」和「清单自动更新」所使用的是同一逻辑，就是这个 `autoupdate` 配置段告诉 Scoop 如何去更新（替换）清单中的版本号、下载 URL(s) 及文件 hash（可选）等。如果你感兴趣，可以查看 [`generate_user_manifest` 函数](https://github.com/ScoopInstaller/Scoop/blob/4a31bd330244f7f89f16208cdddda3f9edac2d65/lib/manifest.ps1#L135-L157)和 [`Invoke-AutoUpdate` 函数](https://github.com/ScoopInstaller/Scoop/blob/4a31bd330244f7f89f16208cdddda3f9edac2d65/lib/autoupdate.ps1#L416-L474)的相关代码以了解这一逻辑（并不复杂）。
> 
> > scoop是否可以在将来通过某种方案得知他到底可以生成该软件得那些版本，从而获得所有的可以生成得版本。
> 
> 正如我之前所述，软件版本的更新是软件开发者负责的，其版本号的变化方式、公布途径以及开发者是否保留旧版本等因素千变万化，而软件清单由 Scoop 社区维护，自动更新也是滞后的。从逻辑复杂度层面来讲，获取所有版本号并非易事：就某些托管在 GitHub 上的软件而言，我们可以从 tags, releases 或 changelog 等信息获取所有已知版本号；有些在官网有 changelog 的软件也还好说；但其他软件就比较难办，甚至不可能。如果采取在清单中保留旧版本号的做法，确实很容易实现你想要的 `scoop info <app>` 列出所有可用版本的需求，但那样只能记录该功能上线之后更新的软件版本号，且 Scoop 无法确保这些版本号之后能够一直有效。从效益层面讲，考虑到适用该功能的软件可能只占较少数，我猜短期内不会实现（当然，如果你愿意提交 PR 的话就不一样了 😜）。至于更远的将来能否实现，就取决于需求与效益的平衡了。Scoop 任何新功能的实现都依赖开源社区，一个新功能的需求量大时，其关注度和价值自然就高，也会有更多积极提方案、交 PR 的人。
> 
> > 添加了Version bucket 后，我的搜索时间大大的增长，这还是比较讨厌的。
> 
> `scoop search` 的逻辑是：搜索**所有**本地仓库（local buckets）的**所有**软件清单。若找不到任何结果，才会搜索远程的已知仓库（known buckets）。
> 
> 当前 Versions 仓库中软件清单总数不到 350 个（可以使用 `scoop bucket list` 查看所有本地仓库的详细信息），按理来说影响不会很大。我的本地仓库总共只有 5 个（也包含 Versions 仓库），软件清单总数接近 1700 个。`scoop search python` 肯定只搜索了本地仓库。我的电脑上跑一次耗时在 2.6s 左右，不知你那边耗时是多少。

感谢您耐心的回复，我差不多明白了，谢谢您。还有最后一条确实是我的问题，它的搜索速度非常不稳定，有的时候比较快（3s这样），有的时候非常慢，多达14s。。。
**再次对你表示衷心的感谢！**
