### ISSUE TITLE
[Feature] make scoop install --no-update-scoop options available in scoop config

### ISSUE THREAD

**Issue by yangjiahao265** [ScoopInstaller/Scoop#5111]
#### Is your feature request related to a problem? Please describe.

we have to use -u or --no-update-scoop every time we use scoop install if we want to skip scoop update, it could be an option in scoop config, so we can always skip scoop update

**Comment by rashil2000** [comment]
See https://github.com/ScoopInstaller/Scoop/pull/5112#issuecomment-1216199340
