### ISSUE TITLE
[Feature] Would like a command similar to `brew outdated`

### ISSUE THREAD

**Issue by chingc** [ScoopInstaller/Scoop#5114]
It would be nice to have a command similar to `brew outdated` that show which of your installed programs have an update available.

An alternative would be to tell the user there's an update under the `Info` column when one does `scoop list`.

**Comment by lewis-yeung** [comment]
You can use `scoop status`.

**Comment by rashil2000** [comment]
Yes, the equivalent of `brew outdated` is `scoop status`

**Comment by chingc** [comment]
Sorry, I missed that command.  It wasn't immediately obvious.
