### ISSUE TITLE
[Bug] Start Menu shortcuts lost after system updates

### ISSUE THREAD

**Issue by shirok1** [ScoopInstaller/Scoop#5117]
#### Current Behavior

Shortcuts in `$env:APPDATA\Microsoft\Windows\Start Menu\Programs\Scoop Apps` will be removed after system updates. `scoop reset` is required to recreate shortcuts. Copies of shortcut files (.lnk) will also be removed (even if they are not in Start Menu folder)

#### Expected Behavior

Shortcuts persist through system updates.

### System details

**Windows version:** Windows 11 22H2 25182 (Dev Channel)

**OS architecture:** 64bit

**PowerShell version:** 7.2.6

**Additional software:** None

#### Scoop Configuration

```json
{
  "lastupdate": "2022-08-21T21:41:32.7461687+08:00",
  "SCOOP_REPO": "https://github.com/ScoopInstaller/Scoop",
  "SCOOP_BRANCH": "master",
  "proxy": ":@127.0.0.1:10809",
  "aria2-warning-enabled": false
}
```

**Comment by lewis-yeung** [comment]
Compared to the stable release of Win11, the one on **Dev Channel** can be far too ahead. Can you make sure it is not a Windows bug?

**Comment by rashil2000** [comment]
I just updated to build 25182, and my shortcuts are still there. 

Nevertheless, this bug has been reported a few times before too, unfortunately this is a Windows quirk and Scoop can't do anything about it. The quick workaround is `scoop reset *`.
