### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Issam-seghir** [ScoopInstaller/Scoop#5128]
## Bug Report

First, I use the 22.01 version before I try to switch to the old version 21.7 with `scoop reset 7zip@21.7`
then i try to back to the new version and I can't !! 
A `not installed` message appears and the two versions are installed correctly !!

#### Additional context/output

![image](https://user-images.githubusercontent.com/74573675/187051148-3e9bea49-0b32-4226-a1a1-fef06c08a945.png)

### System details

**Windows version:** 10 pro 

**OS architecture:** 64bit

**PowerShell version:**
7.2.6

#### Scoop Configuration
SCOOP_REPO    : https://github.com/ScoopInstaller/Scoop
SCOOP_BRANCH  : master
alias         : @{gui=scoop-gui}
aria2-enabled : True

**Comment by rashil2000** [comment]
Something is wrong with your installation - it is not possible to have two apps with same name. Try uninstalling by `scoop uninstall 7zip`
