### ISSUE TITLE
[Bug] jsonpath convert datetime string with en-US culture datetime formatter

### ISSUE THREAD

**Issue by shiena** [ScoopInstaller/Scoop#5129]
#### Current Behavior

Getting the https://api.github.com/repos/akiyosi/goneovim/releases/tags/nightly with jsonpath `$.assets[?(@.name=='goneovim-windows.zip')].updated_at` returns `8/21/2022 4:19:49 AM` instead of `2022-08-21T04:19:49Z`

#### Expected Behavior

jsonpath should return `2022-08-21T04:19:49Z` without conversion

#### Additional context/output

This is because the github action container runs in the en-US culture.

#### Possible Solution

If you set InvariantCulture to CurrentCulture, it will not be converted, so it will be solved.

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** 7.2.6

#### Scoop Configuration

```json
{
  "lastupdate": "2022-08-29T03:03:07.7136108+09:00",
  "SCOOP_REPO": "https://github.com/lukesampson/scoop",
  "SCOOP_BRANCH": "master"
}
```

**Comment by rashil2000** [comment]
Hi! Can you make a PR for the fix?
