### ISSUE TITLE
[Bug] Cleanup does not remove download cache of uninstalled programs

### ISSUE THREAD

**Issue by OneYellowLemon** [ScoopInstaller/Scoop#5157]
## Bug Report
Running `scoop cleanup * --cache` is supposed to remove outdated download cache files, but it will not removed cached files for an app that was previously uninstalled.

#### Current Behavior

If you run `scoop cleanup * --cache`, it will not touch the download cache of apps that have been uninstalled.
#### Expected Behavior

Running `scoop cleanup * --cache` should remove old cached versions of uninstalled programs.
#### Additional context/output

I had previously installed an app, used it for a few weeks (and it received updates), and then uninstalled it. When I run `scoop cleanup * --cache`, it does not remove the downloaded version cache of that app.
### System details

**Windows version:**
Windows 11 Home (Windows 11 21H2 OS Build 22000.978)

**OS architecture:**
64-bit

**PowerShell version:**
```powershell
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      22000  832
```

#### Scoop Configuration

```json
{
    "lastupdate":  "2022-09-22T21:15:23.1969854-04:00",
    "SCOOP_REPO":  "https://github.com/lukesampson/scoop",
    "SCOOP_BRANCH":  "master"
}
```

**Comment by niheaven** [comment]
That's because scoop could not know 'outdated' version of uninstalled apps, or maybe it should remove all cache of that apps?

**Comment by OneYellowLemon** [comment]
Yeah, I think it should remove all cache of those apps as the cleanup command is used to free up disk space.

**Comment by rashil2000** [comment]
You can use the `scoop cache rm *` command for that.

`scoop cleanup` only deals with installed apps:
- `--cache` means clear the cached download of that particular installed app
- `*` means consider all installed apps

**Comment by dbthreee** [comment]
scoop cache rm * can't work but scoop cache rm <app_name> can work.
