### ISSUE TITLE
How to install several softwares that I use frequently?

### ISSUE THREAD

**Issue by git136975643** [ScoopInstaller/Scoop#5161]
I have installed several commonly used buckets，But I can't find the package I want。

qq:https://im.qq.com/download
feishu：https://www.feishu.cn
阿里云盘：https://yunpan.aliyun.com
```
scoop search qq
scoop search feishu
```
can't find

**Comment by rashil2000** [comment]
Search for your apps here: https://scoop.sh/#/apps?s=0&d=1&o=false

If it's not there you need to send PRs for their manifests to get added.
