### ISSUE TITLE
[Bug] Explicitly use Powershell's default Expand-Archive

### ISSUE THREAD

**Issue by hongxuchen** [ScoopInstaller/Scoop#5183]
#### Current Behavior

https://github.com/ScoopInstaller/Scoop/blob/master/lib/decompress.ps1#L243

is using a `Expand-Archive` which defaults to Microsoft Powershell's. However some people use `Pscx` which also has the function. And when Pscx's function overrides the default one, it will report the following error when using `scoop install go` (or many other packages).

```powershell
go1.19.2.windows-amd64.zip (155.8 MB) [=============================================================================================================================================================================================] 100%
Checking hash of go1.19.2.windows-amd64.zip ... ok.
Extracting go1.19.2.windows-amd64.zip ... Expand-Archive: D:\scoop\apps\scoop\current\lib\decompress.ps1:243
Line |
 243 |      Expand-Archive -Path $Path -DestinationPath $DestinationPath -For …
     |                                 ~~~~~~~~~~~~~~~~
     | A parameter cannot be found that matches parameter name 'DestinationPath'.

Exception: D:\scoop\apps\scoop\current\lib\core.ps1:642
Line |
 642 |          throw "Could not find '$(fname $from)'! (error $($proc.ExitCo …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not find 'go'! (error 16)
```

#### Expected Behavior

decompression and installation succeed.

#### Possible Solution

Explicitly use the default one by replacing the current line with
```powershell
Microsoft.PowerShell.Archive\Expand-Archive -Path $Path -DestinationPath $DestinationPath -Force
```

* See also the mentioned solution [here](https://github.com/PowerShell/Microsoft.PowerShell.Archive/issues/52).
* https://github.com/ScoopInstaller/Scoop/blob/master/test/Scoop-Decompress.Tests.ps1#L27 actually uses the explicit one.

### System details

**Windows version:** [e.g. 7, 8, 10, 11]
10

**OS architecture:** [e.g. 32bit, 64bit, arm64]
64bit

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]
7.2.6

**Additional software:** [(optional) e.g. ConEmu, Git]

https://github.com/Pscx/Pscx

#### Scoop Configuration

```json
{
  "lastupdate": "2022-10-13T18:24:55.5981183+08:00",
  "SCOOP_REPO": "https://github.com/lukesampson/scoop",
  "SCOOP_BRANCH": "master",
  "aria2-warning-enabled": false,
  "aria2-max-connection-per-server": 8,
  "aria2-split": 8,
  "rootPath": "D:\\scoop"
}
```

**Comment by niheaven** [comment]
What version of Pscx do you use? It has changed `Expand-Archive()` to `Expand-PscxArchive()` since 4.0.0-beta1, and is released since October 17, 2020.

**Comment by hongxuchen** [comment]
`gcm  Expand-Archive` tells me that I'm using `3.3.2`. I indeed have `4.0.0-beta4` installed however.

**Comment by hongxuchen** [comment]
confirmed that using `install-module pscx` defaults to 3.3.2
