### ISSUE TITLE
[Bug] Scoop fails if git is too old and doesn't explain why

### ISSUE THREAD

**Issue by idbrii** [ScoopInstaller/Scoop#5202]
#### Current Behavior

Scoop fails if git is too old.

I have a machine that I haven't used for a year. I ran `scoop update` and all was fine (well, first it ran out of space, but then I cleaned up and it ran fine). However, when checking status on a package, it barfed a ton of git errors about "error: unknown option \`show-current'"

#### Expected Behavior
Scoop either complains that git is out of date or automatically updates git when it updates itself.

Not sure if you want to maintain a minimum git version and block usage until it's upgraded? Or just add a warning? If there was already a warning on `scoop update`, there's no way I would have seen it. My screen buffer is 9000 lines long and the update log blew past that.

#### Additional context/output

I was running scoop from cmd.exe. Here's some of my output:

```
> scoop update
...
Scoop was updated successfully!

> scoop status vim-nightly
error: unknown option `show-current'
usage: git branch [<options>] [-r | -a] [--merged | --no-merged]
...
fatal: ambiguous argument 'HEAD..origin/': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

Name          Installed Version Latest Version   Missing Dependencies Info
----          ----------------- --------------   -------------------- ----
7zip          18.05             22.01
cmake         3.16.1            3.24.2
git           2.19.1.windows.1  2.38.0.windows.1
```

#### Workaround
Updating git manually fixed it.
```
> scoop update git
...
> scoop status vim-nightly
Scoop is up to date.
...
```
### System details

**Windows version:** Win10 21H2

**OS architecture:** 64bit

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]
5.1.18362.752

**Additional software:** none

#### Scoop Configuration

```json
{
    "scoop_branch":  "master",
    "last_update":  "2022-10-17T10:43:58.2477751-07:00",
    "scoop_repo":  "https://github.com/lukesampson/scoop"
}
```

**Comment by adityassharma-ss** [comment]
Have you tried installing a specific version of scoop on your machine? I faced the same issue but after trying `scoop install git@2.38.0` it worked for me.

**Comment by rashil2000** [comment]
`scoop status <app-name>` is not a Scoop command btw. It's just `scoop status`. In general, it is recommended to keep the latest version of Git, as it is an internal dependency for Scoop. 

Scoop does not update packages itself. User needs to do that.
