### ISSUE TITLE
[Bug] `scoop import scoopfile.json` outputs "Couldn't find manifest for 'main/<pkg> --arch arm64'."

### ISSUE THREAD

**Issue by giggio** [ScoopInstaller/Scoop#5208]
#### Current Behavior
Running `scoop import scoopfile.json` outputs several messages or error, like so:

```
❯ scoop import scoopfile.json
WARN  The 'extras' bucket already exists. To add this bucket again, first remove it by running 'scoop bucket rm extras'.
WARN  The 'main' bucket already exists. To add this bucket again, first remove it by running 'scoop bucket rm main'.
WARN  The 'versions' bucket already exists. To add this bucket again, first remove it by running 'scoop bucket rm versions'.
Couldn't find manifest for 'main/7zip --arch arm64'.
Couldn't find manifest for 'main/act --arch arm64'.
```

It's actually doznes of errors, I'm only showing 2. It's one for each pkg in the json file.

And nothing is being imported, no installations are happening.

#### Expected Behavior
Import succeeds.

#### Additional context/output
File was created in PowerShell Core 7, like this:

```powershell
scoop export | Out-File .\scoopfile.json   
```

This is a part of this file:

```json
{
    "apps": [
        {
            "Name": "7zip",
            "Updated": "2022-07-23T01:28:39.1460724-03:00",
            "Version": "22.01",
            "Source": "main",
            "Info": ""
        },
        {
            "Name": "act",
            "Updated": "2022-10-19T09:50:01.6658223-03:00",
            "Version": "0.2.32",
            "Source": "main",
            "Info": ""
        },
        {
            "Name": "ag",
            "Updated": "2022-10-19T10:56:21.8814541-03:00",
            "Version": "2.2.5",
            "Source": "main",
            "Info": ""
        },
        {
            "Name": "bat",
            "Updated": "2022-10-19T09:50:02.5155033-03:00",
            "Version": "0.22.1",
            "Source": "main",
            "Info": ""
        }
    ],
    "buckets": [
        {
            "Name": "extras",
            "Source": "https://github.com/ScoopInstaller/Extras",
            "Updated": "2022-10-19T09:31:37-03:00",
            "Manifests": 1708
        },
        {
            "Name": "main",
            "Source": "https://github.com/ScoopInstaller/Main",
            "Updated": "2022-10-19T09:33:37-03:00",
            "Manifests": 1100
        },
        {
            "Name": "versions",
            "Source": "https://github.com/ScoopInstaller/Versions",
            "Updated": "2022-10-19T06:34:24-03:00",
            "Manifests": 378
        }
    ]
}
```

I then tested the import and saw the error messages.
I tried uninstalling `ag` to see if it would import it, it didn't.

#### Possible Solution
N/A.

### System details

**Windows version:** 11 `Microsoft Windows [Version 10.0.22621.675]`

**OS architecture:** `64bit`

**PowerShell version:** `7.2.6`

**Additional software:** 

#### Scoop Configuration

```json
{
  "last_update": "2022-10-19T12:53:41.8855938-03:00",
  "scoop_repo": "https://github.com/lukesampson/scoop",
  "scoop_branch": "master"
}
```

**Comment by ahmadalli** [comment]
I'm having the same issue. After some digging up, I've found out that the `import` code uses `Info` to determine the architecture
https://github.com/ScoopInstaller/Scoop/blob/8aee6f99803d0f0aeab252e1d9d4848777185c51/libexec/scoop-import.ps1#L43-L49

which is empty in my case (after running `scoop export > scoop.json`)

**Comment by ohubaut** [comment]
Any idea when a release with this fix will be issued?
As there is no way with the get.scoop.sh to specify a release to use, this breaks our onboarding procedure since we have to manually patch the installation of each newcomer. :(

**Comment by niheaven** [comment]
Sorry, soon 😄
