### ISSUE TITLE
Download link with too many characters causes error

### ISSUE THREAD

**Issue by Vzz1c** [ScoopInstaller/Scoop#5214]
#### Current Behavior
Problems when downloading due to long link names, file names longer than 260 characters, or directory names longer than 246 characters

#### Expected Behavior
When the link name is too long, it should be intercepted

#### Additional context/output
<img width="693" alt="image_16" src="https://user-images.githubusercontent.com/49944812/197086270-ad69c045-7f82-4d22-99a9-ca1ebbb97577.png">

#### Possible Solution
Instead of naming the downloaded file in the form of [current filename + linked filename], provide a json field for downloading customizable filenames, or, when the linked name is too long, just use file + version, like this:
xxxx#1.2.3_dl.7z

### System details

**Windows version:** [e.g. 7, 8, 10, 11]
Windows 21H2
**OS architecture:** [e.g. 32bit, 64bit, arm64]
64bit
**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]
5.1.19041.1682
**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
{
    "proxy":  "127.0.0.1:10808",
    "default-architecture":  "64bit",
    "debug":  true,
    "last_update":  "2022-10-20T08:54:45.2933644+08:00",
    "scoop_branch":  "master",
    "scoop_repo":  "https://github.com/ScoopInstaller/Scoop"
}
```

**Comment by niheaven** [comment]
Duplicate with #4327

**Comment by Vzz1c** [comment]
> [与#43​​27](https://github.com/ScoopInstaller/Scoop/issues/4327)重复[](https://github.com/ScoopInstaller/Scoop/issues/4327)

When installing and downloading with install, it works fine, but when it is updated automatically, the file is too long when it needs t
<img width="685" alt="image_17" src="https://user-images.githubusercontent.com/49944812/197215816-2b86a979-f5eb-4baf-8a97-ff8fd2bf04b0.png">
o download the checksum hash.

**Comment by Vzz1c** [comment]
> [与#43​​27](https://github.com/ScoopInstaller/Scoop/issues/4327)重复[](https://github.com/ScoopInstaller/Scoop/issues/4327)

![image](https://user-images.githubusercontent.com/49944812/197307076-26d92b67-6056-42e9-a706-a02a7a7052b3.png)
checkver.ps1

**Comment by Vzz1c** [comment]
> > [与#43​​27](https://github.com/ScoopInstaller/Scoop/issues/4327)重复
> 
> 用install安装和下载的时候，运行正常，但是自动更新的时候，文件太长，需要下载校验和hash。 <img alt="image_17" width="685" src="https://user-images.githubusercontent.com/49944812/197215816-2b86a979-f5eb-4baf-8a97-ff8fd2bf04b0.png">

Actually I got it wrong and can't download
