### ISSUE TITLE
[Bug] `do_dl` after 2022-10-13 is no longer a recognized function

### ISSUE THREAD

**Issue by brian6932** [ScoopInstaller/Scoop#5215]
#### Current Behavior
https://github.com/ScoopInstaller/Extras/actions?query=created%3A%3E2022-10-13 before this point do_dl worked fine, but now manifests like spotify just fail, this is not exclusive to extras, it occurs on my personal repo as well.

#### Expected Behavior
Some function to download bins.

#### Additional context/output
Is there any alternative, or new function name for doing this?

**Comment by niheaven** [comment]
Please use `Invoke-WebRequest()` directly, `do_dl()` is refactored since v0.3.0, and this type of internal function shouldn't be used in manifest.
