### ISSUE TITLE
[Bug] "scoop list" unconditionally writes "Installed apps:" to console

### ISSUE THREAD

**Issue by milnak** [ScoopInstaller/Scoop#5216]
#### Current Behavior

`scoop list` outputs `Installed apps:` unconditionally.

Example:

```powershell
PS D:\temp\x\adjnamedflow> scoop list | Out-GridView
Installed apps:
```

#### Expected Behavior

no output to console should be written when using pipeline.  There doesn't seem to be any way to hide this output, either.

Maybe 'Installed apps:' should be removed entirely? It's pretty obvious what's being displayed when someone runs 'scoop list'.

### System details

Should be system independent, but I'm using Windows 11, 64-bit with PS 7.2.6 inside Windows Terminal

#### Scoop Configuration

```json
{
  "last_update": "2022-10-20T22:06:42.5802990-07:00",
  "cat_style": "plain",
  "alias": {
    "ua": "scoop-ua",
    "lsf": "scoop-lsf",
    "nfo": "scoop-nfo",
    "s": "scoop-s",
    "ls": "scoop-ls",
    "i": "scoop-i",
    "u": "scoop-u",
    "rm": "scoop-rm",
    "ca": "scoop-ca",
    "cu": "scoop-cu"
  },
  "aria2-warning-enabled": false,
  "show_manifest": true,
  "aria2-max-connection-per-server": "2",
  "scoop_repo": "https://github.com/ScoopInstaller/Scoop",
  "scoop_branch": "master"
}
```

**Comment by rashil2000** [comment]
Not a bug. The "Installed apps:" part is written using `Write-Host` which cannot be suppressed via pipeline. You can force-hide it via `scoop list 6> $null`
