### ISSUE TITLE
[Feature] Arbitrary scripts as a new checkver option

### ISSUE THREAD

**Issue by ev-dev** [ScoopInstaller/Scoop#5218]
#### Is your feature request related to a problem? Please describe.

Occasionally when creating/altering a manifest, it can be very difficult to design a stable checkver option, especially in cases where complex xpath/jsonpath/regex expressions are the only options. 

In these cases, I've tended to prototype the version extraction iteratively in my powershell REPL, until I've got an expression that seems to work for a few versions.

This made me think that maybe it would be pretty useful to allow manifest authors to write arbitrary powershell scripts as an alternative `checkver` option. Considering that this kind of arbitrary scripting is already possible within the pre/post (un)install manifest properties, it seemed like a potentially good feature to add.

#### Describe the solution you'd like

An update to the manifest schema enabling an additional `checkver` property named `script` alongside the current `github`/`regex`/`xpath`/`jsonpath`/etc properties, which allows for arbitrary powershell scripts to return the version during checkver execution.

#### Describe alternatives you've considered

Get really good at writing xpath expressions I guess? It's rare but hey when an app's only stable source of published versions is some complex xml feed containing multiple imported namespaces, what else can you do :(

**Comment by chawyehsu** [comment]
We already implemented this feature in #3900. Here is an [example](https://github.com/ScoopInstaller/Main/blob/96ea2fba5ab257e14e21766a18e700b616bb794d/bucket/refreshenv.json#L9) from the main bucket you can refer to.

The [wiki](https://github.com/ScoopInstaller/Scoop/wiki/App-Manifest-Autoupdate#adding-checkver-to-a-manifest) hasn't been updated yet, contributions to it are welcomed. :D

**Comment by rashil2000** [comment]
> The [wiki](https://github.com/ScoopInstaller/Scoop/wiki/App-Manifest-Autoupdate#adding-checkver-to-a-manifest) hasn't been updated yet, contributions to it are welcomed. :D

Updated.
