### ISSUE TITLE
[Bug] failed to compile c with clang

### ISSUE THREAD

**Issue by wsdjeg** [ScoopInstaller/Scoop#5219]
## Bug Report

the llvm has been installed via `scoop install llvm`, and `clang --version` is:

```
clang —version

clang version 15.0.3
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: D:\Scoop\apps\llvm\current\bin
```

#### Current Behavior

when compile a main.c file, I get following error:

```c
#include <stdio.h>
int main()
{
   printf("Hello, World!");
   return 0;
}
```

```
clang --target=x86_64-pc-windows-msvc main.c

clang: warning: unable to find a Visual Studio installation; try running Clang from a developer command prompt [-Wmsvc-not-found]
main.c:1:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
1 error generated.
```

#### Expected Behavior

clang work out of box.

### System details

**Windows version:** win 11

**OS architecture:** [64bit]

**Comment by rashil2000** [comment]
This has nothing to do with Scoop, you need to consult the LLVM docs to see how to deal with missing headers. Scoop just unarchives the LLVM package.

**Comment by wsdjeg** [comment]
maybe missing vs build tools, https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwiG24Ls54f7AhXHtlYBHXhtC4oQFnoECA8QAQ&url=https%3A%2F%2Fgithub.com%2Flukesampson%2Fscoop-extras%2Fissues%2F1861&usg=AOvVaw2B7E7RssbptOTFvzwNt3MB
