### ISSUE TITLE
[Bug] Scoop problems in powershell 7

### ISSUE THREAD

**Issue by rafaelledo** [ScoopInstaller/Scoop#5221]
#### Current Behavior

<code>scoop update</code>

<pre>commands: C:\Users\rafae\scoop\apps\scoop\current\bin\scoop.ps1:41
Line |
  41 |      ({ $subCommand -in (commands) }) {
     |                          ~~~~~~~~
     | The term 'Local:commands' is not recognized as a name of a cmdlet, function, script file, or
     | executable program. Check the spelling of the name, or if a path was included, verify that the path is
     | correct and try again.</pre>

#### Expected Behavior

<pre>Updating Scoop...
Updating 'main' bucket...
Scoop was updated successfully!</pre>

### System details

Windows 11 build 22621.675 (most update to 24/10/2022 - 08:41 UTC -3)

Powershell version
<pre>
Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      2      7</pre>

#### Scoop Configuration

```json
{
    "last_update":  "2022-10-24T08:17:27.8955051-03:00",
    "scoop_branch":  "master",
    "scoop_repo":  "https://github.com/ScoopInstaller/Scoop"
}
```
#### Note*

It works properly in Windows Powershell, only the Core bugs

**Comment by niheaven** [comment]
This is the output of `scoop update`? Or other command?

What's about just type `scoop`?

**Comment by rafaelledo** [comment]
Sorry, it's scoop update
<code>scoop update</code>.
For only <code>scoop</code>:
<pre>
commands: C:\Users\rafae\scoop\apps\scoop\current\libexec\scoop-help.ps1:28
Line |
  28 |  $commands = commands
     |              ~~~~~~~~
     | The term 'Local:commands' is not recognized as a name of a cmdlet, function, script file, or
     | executable program. Check the spelling of the name, or if a path was included, verify that the path is
     | correct and try again.

Usage: scoop <command> [<args>]

Available commands are listed below.

Type 'scoop help <command>' to get more help for a specific command.

Command    Summary
-------    -------
alias      Manage scoop aliases
bucket     Manage Scoop buckets
cache      Show or clear the download cache
cat        Show content of specified manifest. If available, `bat` will be used to pretty-print the JSON.
checkup    Check for potential problems
cleanup    Cleanup apps by removing old versions
config     Get or set configuration values
create     Create a custom app manifest
depends    List dependencies for an app, in the order they'll be installed
download   Download apps in the cache folder and verify hashes
export     Exports installed apps, buckets (and optionally configs) in JSON format
help       Show help for a command
hold       Hold an app to disable updates
home       Opens the app homepage
import     Imports apps, buckets and configs from a Scoopfile in JSON format
info       Display information about an app
install    Install apps
list       List installed apps
prefix     Returns the path to the specified app
reset      Reset an app to resolve conflicts
search     Search available apps
shim       Manipulate Scoop shims
status     Show status and check for new app versions
unhold     Unhold an app to enable updates
uninstall  Uninstall an app
update     Update apps, or Scoop itself
virustotal Look for app's hash or url on virustotal.com
which      Locate a shim/executable (similar to 'which' on Linux)
commands: C:\Users\rafae\scoop\apps\scoop\current\bin\scoop.ps1:41
Line |
  41 |      ({ $subCommand -in (commands) }) {
     |                          ~~~~~~~~
     | The term 'Local:commands' is not recognized as a name of a cmdlet, function, script file, or
     | executable program. Check the spelling of the name, or if a path was included, verify that the path is
     | correct and try again.


</pre>

**Comment by niheaven** [comment]
It seems like you defined another `commands` somewhere. So could you try start a fresh console and run `scoop`?

**Comment by rafaelledo** [comment]
I run a console out of Windows Terminal and got this:

<pre>
commands: C:\Users\rafae\scoop\apps\scoop\current\libexec\scoop-help.ps1:28
Line |
  28 |  $commands = commands
     |              ~~~~~~~~
     | The term 'Local:commands' is not recognized as a name of a cmdlet, function, script file, or
     | executable program. Check the spelling of the name, or if a path was included, verify that the path is
     | correct and try again.

Usage: scoop <command> [<args>]

Available commands are listed below.

Type 'scoop help <command>' to get more help for a specific command.

Command    Summary
-------    -------
alias      Manage scoop aliases
bucket     Manage Scoop buckets
cache      Show or clear the download cache
cat        Show content of specified manifest. If available, `bat` will be used to pretty-print the JSON.
checkup    Check for potential problems
cleanup    Cleanup apps by removing old versions
config     Get or set configuration values
create     Create a custom app manifest
depends    List dependencies for an app, in the order they'll be installed
download   Download apps in the cache folder and verify hashes
export     Exports installed apps, buckets (and optionally configs) in JSON format
help       Show help for a command
hold       Hold an app to disable updates
home       Opens the app homepage
import     Imports apps, buckets and configs from a Scoopfile in JSON format
info       Display information about an app
install    Install apps
list       List installed apps
prefix     Returns the path to the specified app
reset      Reset an app to resolve conflicts
search     Search available apps
shim       Manipulate Scoop shims
status     Show status and check for new app versions
unhold     Unhold an app to enable updates
uninstall  Uninstall an app
update     Update apps, or Scoop itself
virustotal Look for app's hash or url on virustotal.com
which      Locate a shim/executable (similar to 'which' on Linux)
commands: C:\Users\rafae\scoop\apps\scoop\current\bin\scoop.ps1:41
Line |
  41 |      ({ $subCommand -in (commands) }) {
     |                          ~~~~~~~~
     | The term 'Local:commands' is not recognized as a name of a cmdlet, function, script file, or
     | executable program. Check the spelling of the name, or if a path was included, verify that the path is
     | correct and try again.


</pre>

A similar message.

I already tried reinstall powershell in other versions. Scoop works properly in Windows Powershell, i don't know why it happens on the Core.

**Comment by rafaelledo** [comment]
I deleted and solved the bug, but what in the file is causing?

**Comment by niheaven** [comment]
The line `Set-Alias commands Show-Command` add `$local:commands` to your env, and scoop use `$commands` as subcommand param, so these cause the bug.

**Comment by rafaelledo** [comment]
Thank you
