### ISSUE TITLE
[Bug] `installer.args`, `Invoke-ExternalCommand` unexpected bug

### ISSUE THREAD

**Issue by HUMORCE** [ScoopInstaller/Scoop#5231]
## Bug Report

manifest: `extras/ida-free`

A:
```
...
    "installer": {
        "args": [
            "--mode",
            "unattended",
            "--prefix",
            "$dir"
        ]
    },
...
```

B:
```
...
    "installer": {
        "args": [
            "--mode unattended",
            "--prefix $dir",
        ]
    },
...
```

when I put some debug code around L788 of install.ps1 ,the debug output of both mafenist are same, but A works, B fails.https://github.com/ScoopInstaller/Scoop/blob/8aee6f99803d0f0aeab252e1d9d4848777185c51/lib/install.ps1#L778-L798

related: https://github.com/ScoopInstaller/Extras/pull/9603

#### Current Behavior
the installer of app cannot be executed properly with the correct args.

#### Expected Behavior
pass args normally, installation success.

#### Additional context/output
reproduced when install an older version of `extras/ida-free` too. e.g. [v7.7](https://github.com/ScoopInstaller/Extras/blob/b97c844934f6c6ab5cee194881b352d7b4b40f4f/bucket/ida-free.json)

#### Possible Solution
```
cd (scoop prefix scoop)
git revert 288aee9 # then resolve conflicts
```

### System details

**Windows version:** 11

**OS architecture:** 64bit

**PowerShell version:** pwsh core 7.2.6 and windows powershell 5.1

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
{
    "debug":  true,
    "last_update":  "2022-10-29T03:36:12.4060230+00:00",
    "scoop_branch":  "develop"
}
```

**Comment by HUMORCE** [comment]
caused by #5065(https://github.com/ScoopInstaller/Scoop/commit/288aee9ee99bc1cb48e3a1aa524a384777605c25)

https://github.com/ScoopInstaller/Scoop/blob/8aee6f99803d0f0aeab252e1d9d4848777185c51/lib/core.ps1#L531-L535

`ArgumentList is supported in PowerShell 6.1 and later (built on .NET Core 2.1+) `

Windows Powershell 5.1 was not considered in it, related: https://github.com/ScoopInstaller/Extras/issues/9583

**Comment by niheaven** [comment]
In WindowsPowerShell it should be fallback to 

https://github.com/ScoopInstaller/Scoop/blob/8aee6f99803d0f0aeab252e1d9d4848777185c51/lib/core.ps1#L536-L547

So does the `if ($Process.StartInfo.ArgumentList.Add)` work incorrectly?

If the two argument lists act differently, then it may be a bug of `L538`.

**Comment by HUMORCE** [comment]
no further review yet. but it is incompatible with the existing manifest in fact.

**Comment by niheaven** [comment]
Yes, it is the quote here cause these bugs... Will try to resolve it.

**Comment by HUMORCE** [comment]
if you replace L546 with `$s` or `"$s"` will fix installation of `extras/7tt`, but `extras/ida-free` still fail.

**Comment by niheaven** [comment]
`ida-free` should work if `$escapedArgs = $ArgumentList | ForEach-Object {` is replaced with `$escapedArgs = $ArgumentList -split ' ' | ForEach-Object {` I thought, but haven't tested.

**Comment by lewis-yeung** [comment]
> Simply change ```"`"$s`""``` to `"$s"` fixes the bug, but I'm not sure if this could introduce other bugs.

If you do this, a single argument containing any space characters will be incorrectly split.

**Comment by niheaven** [comment]
I've seen many manifests drop `installer.args` and use `Invoke-ExternalCommand` or `Start-Process` directly, and the arguments handler may be rewritten or redesigned.

**Comment by HUMORCE** [comment]
> I've seen many manifests drop installer.args and use Invoke-ExternalCommand or Start-Process directly

...the car is reversing, because it was impassable ahead.

**Comment by HUMORCE** [comment]
how about formatting the args before calling `Invoke-ExternalCommand`?

**Comment by chawyehsu** [comment]
https://github.com/chawyehsu/dorado/issues/684

So basically #5065 & #5066 not only breaks https://github.com/ScoopInstaller/Scoop/pull/5066#issuecomment-1372087032 but also all manifests using `installer.args`? Then sadly this refactoring is a big regression I believe. Look at the reference commits by @issaclin32 in #5065...

**Comment by rashil2000** [comment]
That's what I was saying all along too - it was a massive breaking change...

**Comment by HUMORCE** [comment]
The similar bug is happening with `Invoke-ExternalCommand`. https://github.com/ScoopInstaller/Extras/issues/10322
