### ISSUE TITLE
[Feature] scoop export doesn't export config or aliases

### ISSUE THREAD

**Issue by milnak** [ScoopInstaller/Scoop#5236]
#### Is your feature request related to a problem? Please describe.
`scoop export` is handy but it only exports buckets and apps, not config nor alias, making it harder to duplicate a configuration to a new machine.

#### Describe the solution you'd like
I've created a PowerShell app that does what I describe, but as it's not integrated into scoop, it's probably doing a whole bunch more work than it needs to.

App: https://gist.github.com/milnak/88d66ea79df519e3f07a30ee10531d5a

Sample output: https://gist.github.com/milnak/b0362b9caebf874a84579a784078ffe7

**Comment by niheaven** [comment]
```console
❯ scoop help export
Usage: scoop export > scoopfile.json

Options:
  -c, --config       Export the Scoop configuration file too
```

Alias is not exported now, but config could be exported.

**Comment by rashil2000** [comment]
Aliases cannot be exported as they are proxies to `scoop-<alias>.ps1` scripts inside the shim folder, each containing its own description and definition.

**Comment by JanecekPetr** [comment]
> Aliases cannot be exported as they are proxies to scoop-<alias>.ps1 scripts inside the shim folder, each containing its own description and definition.

I understand that this feature is not going to be implemented and am fine with it.

That said, the aliases being their own files is hardly a technical limitation, is it? If `scoop alias list` can correctly parse out the information from the file, I'm sure `scoop export` could, too. So, is this really a technical decision?

**Comment by rashil2000** [comment]
It is a bit of both. `scoop alias list` uses janky regex parsing of a non-standard text format, and I don't want to extend features built on it. It is not a robust method.
