### ISSUE TITLE
[Bug] Installing a specific version of a package should use the manifest for that version

### ISSUE THREAD

**Issue by adamency** [ScoopInstaller/Scoop#5239]
Currently when you try to install the specific version of a package with the syntax `<package>@<version>`, scoop will use the manifest for the most recent version instead of the manifest for the specified version. I am strongly willing to call that an actual bug since this will break in a myriad of cases when there's a very simple solution to this problem: simply using the manifest for that version, at least if one for that version exists in the bucket's repo history.

A simple example currently: I want to install `neovim@0.6.0` but scoop uses the manifest for [0.8.0](https://github.com/ScoopInstaller/Main/blob/87b3c9d05db49970ce8c6d1587c5f6dc50022942/bucket/neovim.json) , however the path to the zip download [was changed since 0.7.0](https://github.com/ScoopInstaller/Main/commit/6bdad1c46837525be4132d07eb24e440114a425c) and scoop fails because of such a trivial issue:

```
me@company 2022-11-03 11:36:24 AM C:\Users\me $ scoop install neovim@0.6.0
WARN  Given version (0.6.0) does not match manifest (0.8.0)
WARN  Attempting to generate manifest for 'neovim' (0.6.0)
Autoupdating neovim
Searching hash for nvim-win64.zip in https://github.com/neovim/neovim/releases/download/v0.6.0/nvim-win64.zip.sha256sum
Found: d46a161a8e025f8a03a75b1181372f2712116e4edf566b2569cdcc4f371f80c4 using Extract Mode
Writing updated neovim manifest
Installing 'neovim' (0.6.0) [64bit]
nvim-win64.zip (32.5 MB) [=============================================================================================================================================================================] 100%
Checking hash of nvim-win64.zip ... ok.
Extracting nvim-win64.zip ... Exception: C:\Users\me\scoop\apps\scoop\current\lib\core.ps1:638
Line |
 638 |          throw "Could not find '$(fname $from)'! (error $($proc.ExitCo …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not find 'nvim-win64'! (error 16)
```

The feature allowing to install old version will only be correctly implemented when `scoop install <package>@<version>` uses the `<version>` manifest for `<package>`.

**Comment by adamency** [comment]
Thanks @Ash258 for taking notice. Do you know of an easy workaround for my specific issue right now, like for instance if there's a way to manually give scoop the manifest to use when running `scoop install neovim@0.6.0` ?

**Comment by niheaven** [comment]
Duplicated with #3045.

And you are using a wrong URL, please try `scoop install https://github.com/ScoopInstaller/Main/raw/12397aec24981e0598f1efea9c76379be05ff55f/bucket/neovim.json`

**Comment by adamency** [comment]
Thanks @niheaven for pointing out my mistake for the URL.

However, I wouldn't call the current issue a duplicate of #3045. I saw it before making this post, but that "issue" is a vague and broad question about the general state of installing specific versions. It doesn't deal specifically with the point of using the manifest from the given version, neither in the title nor in the original post.

**Comment by niheaven** [comment]
It is in the discussion and there's a git log solution that we haven't implemented. This is a long lasting bug and we haven't started to solve it.
