### ISSUE TITLE
scoop does not work if I open another powershell tab

### ISSUE THREAD

**Issue by red-smeg** [ScoopInstaller/Scoop#5244]
Hi,

How do I persist across powershell tabs.  i open a new tab any apps I have installed no longer work ??

windows 11

**Comment by rasa** [comment]
@red-smeg Have you tried rebooting?

**Comment by lewis-yeung** [comment]
@red-smeg You have to restart your terminal. Scoop only adds paths of newly installed apps to the `PATH` environment variable in the current PowerShell session, while a new tab will inherit the current environment of the terminal app, which is not changed by Scoop.

**Comment by rashil2000** [comment]
Yes, restarting terminal (or the PC, although not required) should fix it
