### ISSUE TITLE
[Bug]: Installing MSI files via scoop may not play nicely with junction reparse points

### ISSUE THREAD

**Issue by quotidian-ennui** [ScoopInstaller/Scoop#5245]
## Bug Report

Note that this may not be a bug in scoop per-se; but I'm raising it as an issue since there could potentially have been a regression in the underlying powershell scripts.

Equally, the solution is appropriate, so this should be considered low-prority; but there are interesting side effects that might cascade as a thought experiment. Since you can mount a disk volume as a directory instead of a drive letter; might this have an effect on scoops behaviour if directory mounts are somewhat analagous to reparse points.

### Current Behavior

- Scoop was historically installed using the defaults
- C:\Users\lchan\scoop was made into a reparse point onto D:\Storage\Scoop (using `junction` from sysinternals); in my mind `~/scoop` is now a symbolic link to `d:\storage\scoop`

As of 2022-11-09 `scoop update aws` no longer works, 

- the MSI file is downloaded correctly, and starts when executed manually
- You get the dreaded, infamous _1622_ error that means nothing and yet everything.
- Note that zip file scoop updates still work as expected.

```console
PS C:\Users\lchan> scoop update aws
aws: 2.8.7 -> 2.8.11
Updating one outdated app:
Updating 'aws' (2.8.7 -> 2.8.11)
Downloading new version
Loading AWSCLIV2-2.8.11.msi from cache.
Checking hash of AWSCLIV2-2.8.11.msi ... ok.
Uninstalling 'aws' (2.8.7)
Removing shim 'aws.shim'.
Removing shim 'aws.exe'.
Removing shim 'aws_completer.shim'.
Removing shim 'aws_completer.exe'.
Unlinking ~\scoop\apps\aws\current
Installing 'aws' (2.8.11) [64bit] from main bucket
Loading AWSCLIV2-2.8.11.msi from cache.
Extracting AWSCLIV2-2.8.11.msi ... ERROR Exit code was 1622!
Failed to extract files from C:\Users\lchan\scoop\apps\aws\2.8.11\AWSCLIV2-2.8.11.msi.
Log file:
  ~\scoop\apps\aws\2.8.11\msi.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=aws%402.8.11%3a+decompress+error
```

### Expected Behavior

It previously worked, since I have updated to aws 2.8.7 with the junction reparse point in place.

### Possible Solution

Set the scoop ENV to point to `D:\Storage\Scoop` and everything now works. I'm guessing that the way scoop tries to decompress and extract MSI files has subtly changed, and reparse points aren't evaluated in the same way as previously.

```console
PS C:\Users\lchan> scoop update aws
aws: 2.8.7 -> 2.8.11
Updating one outdated app:
Updating 'aws' (2.8.7 -> 2.8.11)
Downloading new version
Loading AWSCLIV2-2.8.11.msi from cache.
Checking hash of AWSCLIV2-2.8.11.msi ... ok.
Uninstalling 'aws' (2.8.7)
Removing shim 'aws.shim'.
Removing shim 'aws.exe'.
Removing shim 'aws_completer.shim'.
Removing shim 'aws_completer.exe'.
Unlinking D:\Storage\scoop\apps\aws\current
Installing 'aws' (2.8.11) [64bit] from main bucket
Loading AWSCLIV2-2.8.11.msi from cache.
Extracting AWSCLIV2-2.8.11.msi ... done.
Linking D:\Storage\scoop\apps\aws\current => D:\Storage\scoop\apps\aws\2.8.11
Creating shim for 'aws'.
Creating shim for 'aws_completer'.
'aws' (2.8.11) was installed successfully!
PS C:\Users\lchan>
```

### System details

```
Edition	Windows 11 Pro
Version	21H2
Installed on	‎11/‎01/‎2022
OS build	22000.1219
Experience	Windows Feature Experience Pack 1000.22000.1219.0
```

- **PowerShell version:** 7.2.7
- **Additional software:** Running in Windows Terminal

#### Scoop Configuration

```json
{
  "alias": {
    "remove": "scoop-remove",
    "check-update": "scoop-check-update",
    "upgrade": "scoop-upgrade",
    "rm": "scoop-rm"
  },
  "aria2-warning-enabled": false,
  "last_update": "2022-11-10T08:46:26.8323254+00:00",
  "scoop_repo": "https://github.com/lukesampson/scoop",
  "scoop_branch": "master"
}
```

**Comment by niheaven** [comment]
Hmm, it's strange, since we haven't change decompression recently, or maybe I forgot it?

Could you set `scoop config use_lessmsi true` and try again?
