### ISSUE TITLE
[Bug] Error in some buckets when updating scoop

### ISSUE THREAD

**Issue by Issam-seghir** [ScoopInstaller/Scoop#5254]
#### Current Behavior
error in some buckets when updating scoop

#### Expected Behavior
update buckets without errors when updating scoop 

#### Additional context/output

```shell
Updating 'DoveBoy_Apps' bucket...
error: You have not concluded your merge (MERGE_HEAD exists).
hint: Please, commit your changes before merging.
fatal: Exiting because of unfinished merge.
Updating 'extras' bucket...
Deletion of directory '.github/ISSUE_TEMPLATE' failed. Should I try again? (y/n) y
```

### System details

**Windows version:** [10]

**OS architecture:** [64bit]

**PowerShell version:** [7.2.6]

#### Scoop Configuration

```json
{
  "alias": {
    "gui": "scoop-gui"
  },
  "aria2-enabled": true,
  "last_update": "2022-11-17T08:37:08.1142909+01:00",
  "scoop_branch": "master",
  "scoop_repo": "https://github.com/ScoopInstaller/Scoop"
}

```

**Comment by HUMORCE** [comment]
rm and re-add these buckets, if you don't want to deal anything about git.

**Comment by rashil2000** [comment]
> rm and re-add these buckets, if you don't want to deal anything about git.

Yep, a quickfix

**Comment by Issam-seghir** [comment]
How to fix this with git ? , I'm tired of this error every time i update scoop !!

**Comment by rashil2000** [comment]
This error should not occur every time with scoop update. Readding the bucket should fix it once and for all. Check your ~/.gitconfig settings if you have a conflicting setting.
