### ISSUE TITLE
[Bug] Loop in scoop import.

### ISSUE THREAD

**Issue by hungpham3112** [ScoopInstaller/Scoop#5256]
After testing some scripts with `scoop import`, I noticed that there is a bug with `scoop update` inside `scoop import` functionality.

Current behavior: 
Run `scoop import apps.txt`
![image](https://user-images.githubusercontent.com/75968004/202735610-81f0060d-bd06-469a-8df6-30031cb14467.png)

The loops:
![image](https://user-images.githubusercontent.com/75968004/202735684-34e5e1e5-575c-4b95-9b26-c84ebc6b9d1b.png)

Expected behavior:
`scoop import` run update only first time.

Possible Solution:

I searched and found a bug at `"$PSScriptRoot\..\libexec\scoop-import.ps1"` at line 61:

```
    & "$PSScriptRoot\scoop-install.ps1" $app$global$arch
```

It seems `scoop install` run and update at the same time in `scoop-install.ps1`. I suggest to add the update line before for-loop:
```
<-- Update maybe in here -->
foreach ($item in $import.apps) {
    $info = $item.Info -Split ', '
    $global = if ('Global install' -in $info) {
        ' --global'
    } else {
```
and add the flag `--no-update-scoop` like:

```
    & "$PSScriptRoot\scoop-install.ps1" --no-update-scoop $app$global$arch
```

I haven't tested this script yet so I need someone to confirm. Thank you.

**Comment by rashil2000** [comment]
Seems to be working fine here.

![image](https://user-images.githubusercontent.com/46838874/211072655-585f09bc-9869-440d-a1bf-df10415cca36.png)

Looks like the config file is not getting written to in your case. Can you check ~/.config/scoop/config.json once?

**Comment by thiagomajesk** [comment]
Noticed this today using Scoop `v0.3.1` too. Should we reopen the issue?

**Comment by rashil2000** [comment]
> Looks like the config file is not getting written to in your case. Can you check ~/.config/scoop/config.json once?

**Comment by thiagomajesk** [comment]
@rashil2000 The `~/.config/scoop/config.json` exists and it's written:

```json
{
  "last_update": "2023-10-16T20:23:11.7945122-03:00",
  "scoop_branch": "master",
  "scoop_repo": "https://github.com/ScoopInstaller/Scoop"
}
```

**Comment by rashil2000** [comment]
Does the timestamp change when you run `scoop update`?

**Comment by thiagomajesk** [comment]
Hi, @rashil2000! Yes, it does... This bug doesn't happen very often though. I first spotted this while scripting my [dotfiles](https://github.com/thiagomajesk/dotfiles).

**Comment by hungpham3112** [comment]
> Hi, @rashil2000! Yes, it does... This bug doesn't happen very often though. I first spotted this while scripting my [dotfiles](https://github.com/thiagomajesk/dotfiles).

The problem appear when I create the script for my [dotfiles](https://github.com/hungpham3112/.dotfilesWindows). `scoop update` loops many times, so I opened this issue. But @rashil2000 close too soon so I ignore the problem for a while. @rashil2000  Can you check if my solution above works? 

> Possible Solution:
> 
> I searched and found a bug at `"$PSScriptRoot\..\libexec\scoop-import.ps1"` at line 61:
> 
> ```
>     & "$PSScriptRoot\scoop-install.ps1" $app$global$arch
> ```
> 
> It seems `scoop install` run and update at the same time in `scoop-install.ps1`. I suggest to add the update line before for-loop:
> 
> ```
> <-- Update maybe in here -->
> foreach ($item in $import.apps) {
>     $info = $item.Info -Split ', '
>     $global = if ('Global install' -in $info) {
>         ' --global'
>     } else {
> ```
> 
> and add the flag `--no-update-scoop` like:
> 
> ```
>     & "$PSScriptRoot\scoop-install.ps1" --no-update-scoop $app$global$arch
> ```
