### ISSUE TITLE
[Bug] redshift-tray doesn't install properly (crc error?)

### ISSUE THREAD

**Issue by sKGu8gxV** [ScoopInstaller/Scoop#5260]
scoop install redshift-tray
Installing 'redshift-tray' (2.2.0) [64bit]
redshift-tray_2.2.0.zip (712,2 KB) [===============================================================================================] 100%
Checking hash of redshift-tray_2.2.0.zip ... ERROR Hash check failed!
App:         extras/redshift-tray
URL:         https://github.com/ltGuillaume/Redshift-Tray/releases/download/2.2.0/redshift-tray_2.2.0.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    983b9ddae91ab59e8282a0f5cda5ff3eb85b466c4438833cba7e35c089ff477a
Actual:      3b4f901e038b0e94ce85d78a3a7212f0139c92cd5983d0d55d383fe10ca2fe8f

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=redshift-tray%402.2.0%3a+hash+check+failed

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Extras/commit/78e44fe95c8d4491fa76ddb06bf46aae3dd44101
