### ISSUE TITLE
How do I remove a bucket?

### ISSUE THREAD

**Issue by Konglomneshued** [ScoopInstaller/Scoop#5261]
#### Current Behavior

I can add buckets but if I need to remove a bucket I no longer use, I am unable to find a command to do so.

#### Expected Behavior

I expected it would be `scoop bucket remove [bucket name]`, however, that's not valid.  I tried looking online, googling, scoop.sh, wiki page for buckets.  I found nothing.

#### Additional context/output

After I removed some apps I no longer use, the buckets are still sitting around and I have no use for them.

#### Possible Solution

Provide wiki information on how to remove buckets properly.  Or maybe have a command to do so.

### System details

**Windows version:** [e.g. 7, 8, 10, 11]
Windows 11

**OS architecture:** [e.g. 32bit, 64bit, arm64]
64bit

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]
PowerShell 7.3.0

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
//# Your configuration here

{
  "last_update": "2022-11-22T14:30:18.4536424-06:00",
  "scoop_branch": "master",
  "scoop_repo": "https://github.com/ScoopInstaller/Scoop"
}
```

**Comment by HUMORCE** [comment]
`scoop bucket rm <bucket_name>`


```
❯ scoop help
Usage: scoop <command> [<args>]

Available commands are listed below.

Type 'scoop help <command>' to get more help for a specific command.
...

❯ scoop help bucket
Usage: scoop bucket add|list|known|rm [<args>]
```

**Comment by Konglomneshued** [comment]
Thanks, I don't know how I missed that...
