### ISSUE TITLE
[Bug] `iwr -useb get.scoop.sh | iex` won't install on windows 7

### ISSUE THREAD

**Issue by mattjaf** [ScoopInstaller/Scoop#5262]
#### Current Behavior
![image](https://user-images.githubusercontent.com/5776918/203657400-af37d033-4bfa-443c-bb17-d4718646f106.png)

#### Expected Behavior
expected it to install...I'm on windows 7 and my version of powershell might not have iwr

#### Additional context/output
is there another way to install it?

#### Possible Solution
might have to update powershell or find a workaround

### System details

**Windows version:** 
windows 7

**OS architecture:** 
64 bit

**PowerShell version:** 
2.0

**Comment by rashil2000** [comment]
Minimum required PowerShell version for Scoop is 5.1. Follow this link to install it: https://learn.microsoft.com/en-us/powershell/scripting/windows-powershell/wmf/setup/install-configure?view=powershell-7.3
