### ISSUE TITLE
[Feature] provide an asdf like experience with scoopfile.json

### ISSUE THREAD

**Issue by airtonix** [ScoopInstaller/Scoop#5263]
## Feature Request

I use https://asdf-vm.com/ on linux and mac **a lot**... it replaces nvm, rvm, gvm etc and provides similar functionality for a boat load of other tools.

However, it's bash based. So here on windows it doesn't work.

But I notice that scoop has two things similar to asdf: 

- `~/scoop/shims` > `~/asdf/shims`
- `scoopfile.json` > [`.tool-versions`](https://asdf-vm.com/manage/configuration.html)

I want to have multiple versions of a thing installed and i want scoop to automatically run the right version of a tool based on the nearest `.scoopfile.json` found. If a scoopfile.json can't be found when it reaches my home folder then use one that is managed in `~/scoop/`

so if i have in `./scoopfile.json` : 

```json
{
  "apps": [
        {
            "Info": "",
            "Source": "main",
            "Name": "tar",
            "Version": "1.23",
            "Updated": "\/Date(1669110039762)\/"
        },
  ]
}

```
and i run : 

```powershell
> tar -v
```

it should end up running: `~/scoop/shims/tar` which then pipes through to `~/scoop/apps/tar/versions/1.23/tar`

If i switch to the parent directory, and there's no `scoopfile.json` found in any parent directory until my home directory. then when `~/scoopfile.json` contains: 
```json
{
  "apps": [
        {
            "Info": "",
            "Source": "main",
            "Name": "tar",
            "Version": "1.01",
             ...
        },
  ]
}
```

and i run : 

```powershell
> tar -v
```

it should end up running: `~/scoop/shims/tar` which then pipes through to `~/scoop/apps/tar/versions/1.01/tar`

---

I want to put a `scoopfile.json` into each of the git repos of the projects that I work on.

I want this `scoopfile.json` to drive how the `scoop/shims/*` binaries : 
- pick the right version of the tool i execute a binary found in the `scoopfile.json`
- install the version of the tool when i run `scoop install`

#### Is your feature request related to a problem? Please describe.

the `~/scoop/shims/*` should be thin wrappers that simply launch internal `scoopfile.json` resolving mechanism looking for `scoopfile.json` starting from the current `cwd` all the way up to the users home folder. When found, it looks inside and determines the version of the tool/program to use and redirects process stream to that binary in `~/scoop/installs/<app_tool_name>/<version>/`

**Comment by airtonix** [comment]
Having this feature, would propel Scoop to godtier dev tooling for windows developers not interested in launching their setup in wsl2.

**Comment by r15ch13** [comment]
So it works like a dependency manager like `npm` or `composer`?
Hm, but Scoop isn't able to reliably install old versions, because it lacks a history of old software versions.

**Comment by rashil2000** [comment]
This has been discussed before: https://github.com/ScoopInstaller/Scoop/discussions/4695

But yeah for the very reason that Scoop can't reliably install older versions - manifests are auto generated from the latest one and they most commonly are not compatible with older package versions - this won't be possible.

As explained in the linked discussion, it is possible to do it for very specific package managers like language/library package managers, but not for a generic package manager like Scoop.
