### ISSUE TITLE
Error updating bucket "main"

### ISSUE THREAD

**Issue by furopi** [ScoopInstaller/Scoop#5264]
Please help someone! I get an error when trying to update shown in the screenshot below. Thank you! 😊

<img width="675" alt="2022-11-24 (1)" src="https://user-images.githubusercontent.com/36579099/203773387-33aae9c4-9736-43fa-b424-7e76911dd355.png">

**Comment by rashil2000** [comment]
This should fix it:
```scoop bucket rm main
scoop bucket add main
```

**Comment by furopi** [comment]
Thank you sir! ❤️
