### ISSUE TITLE
[Feature] Offline install for scoop

### ISSUE THREAD

**Issue by roysubs** [ScoopInstaller/Scoop#5265]
#### Is your feature request related to a problem? Please describe.

I would like to avoid having to run the full scoop installation process on every new VM because it is quite slow. I would like to have instant access to scoop.

#### Describe the solution you'd like

I would like an offline scoop install, so that I can immediately have access to scoop in Hyper-V Windows VM's and the Windows Sandbox. i.e. not having to download scoop from the internet, not having to extract the zip's, just a pristine/vanilla scoop install folder that I can robocopy into the new system (so will be less than 1 second to do that) and then attach whatever environment variables and PATH settings are required to turn that folder into a full scoop installation that is fully usable inside that new VM. My goal is for this to simply be a normal scoop install, just without the internet download then 2x zip extractions that happen during the install etc. I've looked around the existing issues on here but found none that fit this desccription.

#### Describe alternatives you've considered

I have tried this myself and cannot get it to work. I installed vanilla scoop on a system. I then robocopy'd that to a backup location. I go to the VM. I robocopy scoop into place, I add the `shims` folder to the PATH, and ... nothing works. I would really like to get this working as I am creating lots of new VM's and the scoop internet install process can be quite slow, downloading the file, doing the 2x zip extractions (the second is particularly slow). It seems inefficient to have to download every time and do the extractions every time. How can we do an offline install for scoop as above? (Note that I have achieved the above with `chocolatey` to create an offline install of it so that I have instant access to that package manager just by robocopying into place and setting one environment variable and adding to the PATH, but I prefer scoop and so would like to use scoop as much as possible).

**Comment by rashil2000** [comment]
Hi, this issue is tracked here: #3505
