### ISSUE TITLE
[Bug] Git: Error in the HTTP2 Framing layer

### ISSUE THREAD

**Issue by couleurm** [ScoopInstaller/Scoop#5267]
#### Current Behavior
Hangs for a while, then throws:

![](https://media.discordapp.net/attachments/1044292853658042510/1044313382083375224/image.png)

#### Expected Behavior
Adds bucket like you'd expect to

#### Additional context/output
User tried deleting the Scoop folder and running get.scoop.sh again, did not help

### System details

**Windows version:** 10
**OS architecture:** 64bit
**PowerShell version:** 5.1
**Additional software:** Git
#### Scoop Configuration
Untouched

**Comment by HUMORCE** [comment]
```
> scoop bucket add ctt-utils https://github.com/couleur-tweak-tips/utils
Checking repo... OK
The ctt-utils bucket was added successfully.
```

I think this is due to a network issue.

**Comment by rashil2000** [comment]
I can't repro this either. Seems to be a one-off problem, like the one mentioned in the SO thread.
