### ISSUE TITLE
Cannot install package even the other failed installation was uninstalled

### ISSUE THREAD

**Issue by douyw** [ScoopInstaller/Scoop#5272]
#### Current Behavior

A failed installation will prevent installing other package.

#### Expected Behavior

A new package installing should be started successfully after the failed installation had been uninstalled.

#### Additional context/output

```
PS D:\_works> scoop -v
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'main' bucket:
2b1b40e49 (HEAD -> master, origin/master, origin/HEAD) chromedriver: Update to version 108.0.5359.71

PS D:\_works> scoop install innounp
Installing 'innounp' (0.50) [64bit] from main bucket
未能解析此远程名称: 'raw.githubusercontent.com'  (the Chinese text says: 'the remote host can not be resolved.')
URL https://raw.githubusercontent.com/ScoopInstaller/Binary/master/innounp/innounp050.rar is not valid
PS D:\_works> scoop uninstall innounp
ERROR 'innounp' isn't installed correctly.
Removing older version (0.50).
'innounp' was uninstalled.
PS D:\_works> **scoop install imagemagick**
**Installing 'innounp'** (0.50) [64bit] from main bucket    (_!!! installing imagemagick is expected here. !!!_)
未能解析此远程名称: 'raw.githubusercontent.com'
URL https://raw.githubusercontent.com/ScoopInstaller/Binary/master/innounp/innounp050.rar is not valid
```

### System details

**Windows version:**
10

**OS architecture:** 
64bit

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]
PS D:\_works> $($PSVersionTable.PSVersion)

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      19041  1682

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

PS D:\_works> cat ~/.config/scoop/config.json
{
    "last_update":  "2022-11-30T19:31:46.6264207+08:00",
    "scoop_branch":  "master",
    "scoop_repo":  "https://github.com/lukesampson/scoop"
}
```json
//# Your configuration here

**Comment by HUMORCE** [comment]
https://github.com/ScoopInstaller/Main/blob/b83932bd1e6250886bf7e14f946e0eeff78b1140/bucket/imagemagick.json#L16

`imagemagick` requires an inno unpacker to install, so it is expected behaviour.

**Comment by rashil2000** [comment]
Check your network, it is blocking github URLs

**Comment by douyw** [comment]
It's not a network blocking problem at all. I had uninstalled the `innounp` package, and I'm installing `imagemagick`, but `innounp` shows up again. The point is the following two lines (copied from above):

PS D:\_works> **scoop install imagemagick**
**Installing 'innounp'** (0.50) [64bit] from main bucket    (_!!! installing imagemagick is expected here. !!!_)

**Comment by rashil2000** [comment]
What's the output of `scoop install innounp`?

**Comment by niheaven** [comment]
No, it is network error here, `raw.githubusercontent.com` is blocked (by DNS cache pollution most times) by ISPs of some provinces of China.

**Comment by douyw** [comment]
@rashil2000 `scoop install innounp` outputs networking issue. Please see the above.

@niheaven I knew the network blocking thing.  I see a good networking can solve the issue.
 It's `scoop install A`, but `Installing B` will show up. `scoop uninstall B` does not work so well. 

Anyway, I just report the encounted issue, ignoring it or not at your disposal. I had stopped `scoop install imagemagick`.

By the way, I want to use imagemagick to resize image, finally I found another [mini tool](https://github.com/avaneev/avir) completed my goal perfectly.

**Comment by niheaven** [comment]
`imagemagick` needs `innounp` to unpack its installer, so if you don't have `innounp`, you cannot install `imagemagick`. When you uninstall `innounp`, you just remove a broken installation.

Use VPN, or change to other provinces that doesn't block `raw.githubusercontent.com` (Shanghai? I could ensure China Telecom in Guangdong blocks the URL)
