### ISSUE TITLE
[Bug] scoop packages work fine in powershell and can't be found in WSL, while I can invoke scoop version command fine

### ISSUE THREAD

**Issue by mattjaf** [ScoopInstaller/Scoop#5279]
#### Current Behavior
After installing pscale with scoop on powershell, I can access it fine on powershell, although in my WSL environment it throws:
```sh
mattj@MSI:~$ pscale version
Command 'pscale' not found, did you mean:
  command 'scale' from deb csound-utils (1:6.17.0~dfsg-3ubuntu1)
  command 'pfscale' from deb pftools (3.2.11-2)
Try: sudo apt install <deb name>
```

#### Expected Behavior
I would be able to access my installs on both environments, similar to how yarn works

#### Possible Solution
Maybe, i have to add something such as a bin to path?

### System details

**Windows version:** 
windows 11
**OS architecture:** 
64-bit
**PowerShell version:**
5.1.22621.608

#### Scoop Configuration

```json
{
    "last_update":  "2022-12-06T23:28:46.6313415-08:00",
    "scoop_repo":  "https://github.com/ScoopInstaller/Scoop",
    "scoop_branch":  "master"
}
```

### ScreenShot
![image](https://user-images.githubusercontent.com/5776918/206419357-b78b0be8-f3fe-49ee-90b4-bcbcd7a87885.png)

**Comment by mattjaf** [comment]
it worked fine when i typed `pscale.exe`

**Comment by rashil2000** [comment]
Ah yes, I forgot. The `.exe` extension is needed when calling Windows programs from WSL.

**Comment by mattjaf** [comment]
If you do not include the .exe extension when executing a command, WSL will think its a Linux command
