### ISSUE TITLE
[Feature] Allow specifying custom referer

### ISSUE THREAD

**Issue by sanyer** [ScoopInstaller/Scoop#5280]
#### Is your feature request related to a problem? Please describe.

I'm currently facing problems with downloading betas of msiafterburner and rtss from https://download-eu2.guru3d.com
It is a problem similar to sourceforge.net and portableapps.com - referer has to be empty.

#### Describe the solution you'd like
Add option to specify referer next to (or inside) url option of the manifest.

#### Describe alternatives you've considered
Adding each problematic domain is cumbersome. So, no other real alternative.

**Comment by chawyehsu** [comment]
You can use the custom headers to do so #5140

**Comment by HUMORCE** [comment]
> aria2-options:
>       Array of additional aria2 options.
>       See: 'https://aria2.github.io/manual/en/html/aria2c.html#options'

**Comment by rashil2000** [comment]
Yes, aria2 can be configured separately via its options

**Comment by sanyer** [comment]
Got it, thanks!
