### ISSUE TITLE
[Feature] add user define hooks

### ISSUE THREAD

**Issue by hosxy** [ScoopInstaller/Scoop#5283]
#### Is your feature request related to a problem? Please describe.

Sometimes I want to do some extra things it don't define in manifest file when app pre/post install or pre/post uninstall.

for example:
+ when I install a app, scoop maybe create many shims for me, but I want to remove some shims that I don't need. Then when app update the shims I have removed will go back, so I need remove it everytime when app update
+ like firefox, I want to enable userChromeJS support for it, I need to copy some files to firefox's install directory, so I will also do same things everytime when I update firefox
+ ...

#### Describe the solution you'd like

 Please add hook support that it can define by users, and it will be triggered when app pre/post install or pre/post uninstall.

**Comment by rashil2000** [comment]
The pre/post install or pre/post uninstall script fields are present exactly for this purpose. If you want customized behavior (which is different from what is present in official buckets), then you will have to create a custom manifest, sorry.
