### ISSUE TITLE
[Feature] Remove Robocopy dependency

### ISSUE THREAD

**Issue by ev-dev** [ScoopInstaller/Scoop#5288]
#### Is your feature request related to a problem? Please describe.

Although `Robocopy.exe` is a built-in system utility and available in virtually all Windows Desktop OS's, it is not something that is included in slimmed down versions of Windows such as NanoServer (https://hub.docker.com/_/microsoft-windows-nanoserver).

Consider removing robocopy as a dependency of scoop. 

#### Describe the solution you'd like

It appears only to be used in 2 places of this codebase: 
- The `movedir` function defined in `bin/core.ps1:621`, which itself is only used 6 times in 1 single file: `lib\decompress.ps1`
- The `bin/refresh.ps1:11` file
- Tests in `test/Scoop-Core.Tests.ps1` which only test for the existence of robocopy in the user's `$Env:Path` and the functionality of the `movedir` function

Indeed, RoboCopy is significantly faster than both the built-in PowerShell *-Item Cmdlets and even the .NET file operations.

However, my guess is that at the time robocopy was included in this codebase (appears to be at least 7+ years ago), the *-Item cmdlets were significantly slower than they are today (at least for PowerShell >v5 and likely still improved in v5 since then). Therefore, it seems unnecessary to require it as a dependency for scoop these days.

#### Describe alternatives you've considered

Currently working on a fork that simply changes the body of the `movedir` function to use the built-in PowerShell `Move-Item` cmdlet (would also try .NET methods if performance is really an issue)

**Comment by rashil2000** [comment]
The reason for using Robocopy is not just speed. `Move-Item` cmdlet does not preserve directory structure when moving multiple items, so Robocopy is necessary.
