### ISSUE TITLE
scoop acts wonky when (accidentally) run in wsl

### ISSUE THREAD

**Issue by milnak** [ScoopInstaller/Scoop#5302]
#### Current Behavior
scoop acts wonky when (accidentally) run in wsl.

Open a WSL window and try a scoop command.  You'll get errors and other issues.

#### Expected Behavior
scoop works, or bails if run within wsl, e.g. it fails with "scoop cannot be run in an WSL session."

**Comment by rashil2000** [comment]
What kind of errors? Please be specific and fill out the issue template.
