### ISSUE TITLE
[Feature] Prioritize default buckets over 3rd party buckets 

### ISSUE THREAD

**Issue by moltenform** [ScoopInstaller/Scoop#5304]
#### Is your feature request related to a problem? Please describe.
The problem is that when running `scoop install name-of-package`, all installed buckets are checked, and if `name-of-package` exists in a 3rd party bucket it can get picked up from there.

I want to be cautious when installing from non-default buckets and be intentional when getting from them. (If anything, I'd even be fine with a warning when installing from a non-default bucket).

Example:
I have the 3rd party `anderlli0053_DEV-tools` bucket installed.
I run `scoop install nodejs-lts`

Expected:
nodejs-lts exists in the `main` bucket, with a version just as recent, so it should be chosen.

Actual:
nodejs-lts is installed from the `anderlli0053_DEV-tools` bucket instead, a non-default one.

#### Describe the solution you'd like
Either

a) default buckets should take priority
or
b) show a "continue? yes/no" prompt when getting a package from a non-default bucket.

#### Describe alternatives you've considered

I know I can manually type `scoop install main/name-of-package` but there's also extras and so on.

**Comment by HUMORCE** [comment]
duplicated: #5131

btw, the `suggest` and `depends` of most of manifests in official buckets do not declare the source(bucket) of the app.
