### ISSUE TITLE
[Feature] Resume unfinished downloads due to connection lost

### ISSUE THREAD

**Issue by a0v0** [ScoopInstaller/Scoop#5306]
#### Is your feature request related to a problem? Please describe.
I am installing flutter. Its about 800 MB. Now scoop downloaded ~600mb but unfortunately my wifi stopped working. Now when i install it again it starts to download again from 0%.

#### Describe the solution you'd like
See https://stackoverflow.com/questions/45643061/aria2-continue-download

**Comment by rashil2000** [comment]
Aria2 already has this feature, see https://github.com/ScoopInstaller/Scoop/pull/3292
