### ISSUE TITLE
[Bug] Cannot add local bucket path as bucket

### ISSUE THREAD

**Issue by redactedscribe** [ScoopInstaller/Scoop#5314]
#### Current Behavior
I used to have a bucket added from a local bucket path but I just had to `scoop bucket rm mybucket` it because the drive letter has changed on my system and Scoop began to complain that it cannot find it any longer. Now when I try to re-add the bucket at its new location, I always get an error:

```powershell
scoop bucket add mybucket "E:\Scoop\mybucket"
ERROR E:\Scoop\mybucket is not a valid Git URL!
ERROR Please see https://git-scm.com/docs/git-clone#_git_urls for valid ones.
```

#### Expected Behavior
Add the local bucket.

#### Additional context/output
I'm sure this used to work (else how was `mybucket` originally added?) but after having done a search, I see [this comment](https://github.com/ScoopInstaller/Scoop/issues/4668#issuecomment-1014325807) from a ~year ago saying that Scoop doesn't even support adding local bucket paths... What am I missing?

### System details

**Windows version:** 11

**OS architecture:** 64bit

**PowerShell version:** 7.3.1

#### Scoop Configuration

```json
{
  "aria2-enabled": true,
  "shim": "kiennq",
  "last_update": "2022-12-30T13:09:19.6053214+02:00",
  "scoop_branch": "master",
  "scoop_repo": "https://github.com/ScoopInstaller/Scoop"
}
```

**Comment by HUMORCE** [comment]
Scoop used to support this.

refer: #4704

**Comment by lewis-yeung** [comment]
@redactedscribe You can use slashes instead of backslashes in the local path. The following works fine:

```powershell
scoop bucket add mybucket "E:/Scoop/mybucket"
```

**Comment by redactedscribe** [comment]
@lewis-yeung Thanks, that was it!
