### ISSUE TITLE
[Bug] tests fails (is_in_dir)

### ISSUE THREAD

**Issue by Valinor** [ScoopInstaller/Scoop#5334]
#### Current Behavior
Current test fail on "is_in_dir" test in Scoop-Install.Tests.ps1

#### Expected Behavior

All tests must pass

#### Additional context/output
Currently, on dev branch (and master), test for "**is_in_dir**" fails.
Where I read the code, it's seem legit, because the test seem not correct.

        is_in_dir 'C:\test' 'C:\foo' | Should -BeFalse 
        is_in_dir 'C:\test' 'C:\test\foo\baz.zip' | Should -BeTrue => \foo\baz.zip in c:\test

        is_in_dir 'test' "$PSScriptRoot"| Should -BeTrue => $PSScriptRoot is not in test, so BeFalse

#### Possible Solution
The correct way to test should be

        is_in_dir "$PSScriptRoot" 'test'| Should -BeTrue => test is in $PSScriptRoot, so BeTrue

**Comment by niheaven** [comment]
No, the test is not failed, though the test is incorrect...

`is_in_dir 'test' "$PSScriptRoot"` here compares two identical dir, and it should be changed to `is_in_dir 'test' "$PSCommandPath"`.

**Comment by niheaven** [comment]
It's strange here, what's your PS version? I've tested on PowerShell 7.3, and `fullpath` in `is_in_dir` will convert the path to absolute path, so the test passed.

**Comment by Valinor** [comment]
> It's strange here, what's your PS version? I've tested on PowerShell 7.3, and `fullpath` in `is_in_dir` will convert the path to absolute path, so the test passed.
You are absolutely right here. Test were done in 5.1.x
In 7.3, there is no problem.

I close this bug.

**Comment by niheaven** [comment]
OKOK, got the bug. Since `fullpath` uses `$ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath()` to expand path, the working dir matters here for `test` folder. If you run the test in `$scoopdir`, all tests passed, otherwise, this will fail.
