### ISSUE TITLE
[Feature] Improve search to allow hyphenated words that don't mach shims/binaries to be found

### ISSUE THREAD

**Issue by eugenesvk** [ScoopInstaller/Scoop#5338]
#### Is your feature request related to a problem? Please describe.
I was trying to find the `libjxl` package
`scoop-search.exe jpeg-xl` fails
`scoop-search.exe "jpeg xl"` fails

Even though  `"description": "JPEG XL image format (.jxl) encode/decode tools",` has the term

#### Describe the solution you'd like
I'd like for the search algorithm to be adjusted so that the description is also searched (and the hyphens could be ignored)

#### Describe alternatives you've considered
I've checked https://github.com/shilangyu/scoop-search, but it also suffers from the same issue (but boy is it faster, wish it were the default search command)

**Comment by rashil2000** [comment]
Descriptions are not looked up when searching, only the manifest name and the contained binaries (shims) are looked up. 

`scoop search jpeg xl` is nothing but `scoop search jpeg`, as any arguments after the third one are simply ignored.

**Comment by eugenesvk** [comment]
Ah, thanks for clarification!
Ok, let's assume there is no shell mistake and the command was `scoop search "jpeg xl"`
Should the description field be added to allow this human-readable search term to work (with or without a hyphen) while the binaries are much more terse?

**Comment by rashil2000** [comment]
Yes, description lookup is being tracked here https://github.com/ScoopInstaller/Scoop/issues/4412

I'll close this one in favour of that.
