### ISSUE TITLE
[Bug] Creating new shim fails due to relative path in git.ps1 shim

### ISSUE THREAD

**Issue by plicit** [ScoopInstaller/Scoop#5353]
#### Current Behavior
```
C:\# scoop install scrcpy
Installing 'scrcpy' (1.25) [64bit] from main bucket
Loading scrcpy-win64-v1.25.zip from cache.
Checking hash of scrcpy-win64-v1.25.zip ... ok.
Extracting scrcpy-win64-v1.25.zip ... done.
Running pre_install script...
Linking C:\Scoop\apps\scrcpy\current => C:\Scoop\apps\scrcpy\1.25
Creating shim for 'scrcpy'.
Creating shim for 'scrcpy-console'.
Creating shim for 'scrcpy-noconsole'.
Convert-Path: C:\Scoop\apps\scoop\current\lib\core.ps1:678
Line |
 678 |          $shimTarget | Convert-Path
     |                        ~~~~~~~~~~~~
     | Cannot find path 'C:\apps\git\current\cmd\git.exe' because it does not exist.

ERROR Can't shim 'C:\Scoop\shims\scrcpy-noconsole': 'git' is needed but not installed.
ERROR Please install git ('scoop install git') and try again.
```
#### Expected Behavior
Create the shims.

#### Additional context/output
`Get-CommandPath git` finds a `$comm.Path` of `C:\Scoop\shims\git.ps1` (the git.exe in that directory is ignored) and then calls:
`Get-ShimTarget ($comm.Path -replace '\.exe$', '.shim')`

In `Get-ShimTarget`:
`$ShimPath`: "C:\Scoop\shims\git.ps1"
`$shimTarget`: "..\apps\git\current\cmd\git.exe" is the relative path extracted from git.ps1
`$shimTarget | Convert-Path` resolves the relative path in the current directory which is unlikely to be the `shims` directory, so it fails.

#### Possible Solution
push and pop the shim directory so relative directories resolve correctly.  e.g.:
```powershell
function Get-ShimTarget($ShimPath) { 
# ...
        $ShimDir = ([System.IO.Path]::GetDirectoryName($ShimPath))
        PushD $ShimDir
        $shimTarget = $shimTarget | Convert-Path
        PopD
        return $shimTarget
```

I forked and can make a PR of the above, but maybe `Get-CommandPath` should also be updated to prefer the .exe/.shim?

### System details
**Windows version:** 10
**OS architecture:** 64bit
**PowerShell version:** 5.1.19041.2364
**Additional software:** git

#### Scoop Configuration
```json
{
  "last_update": "2023-01-20T21:04:15.0368524-06:00",
  "scoop_branch": "master",
  "scoop_repo": "https://github.com/ScoopInstaller/Scoop"
}
```

**Comment by rashil2000** [comment]
There shouldn't be a git.ps1 file in your shims directory. In fact, there shouldn't be any ps1 files at all, unless a particular package specifically creates it. Delete all ps1 files from the shims directory, and then run `scoop reset *`.

**Comment by plicit** [comment]
Thanks!  Scoop must have been updated to not create those .ps1 anymore.  Maybe my CWD modification to `Get-ShimTarget` is still useful to handle relative paths like the old .ps1 shims did.

**Comment by rashil2000** [comment]
The old .ps1 scripts were flaky and have been deprecated, so we shouldn't add workarounds to support them.
