### ISSUE TITLE
[Feature] GUI apps ran from the CLI should not be a running terminal process.

### ISSUE THREAD

**Issue by wtfzambo** [ScoopInstaller/Scoop#5354]
## Feature Request
As title says, GUI apps ran from the CLI should not be a running as a terminal process. I think this is potentially related to [this other issue](https://github.com/ScoopInstaller/Scoop/issues/1606).

#### Is your feature request related to a problem? Please describe.

Until 2-3 months ago, I was using the CLI to open most GUI apps. This was very convenient when dealing with apps that can interact with the working directory, for example, [Fork](https://git-fork.com/) or VSCode.

I could run `fork .` in a git repo, the app would open, and I could keep using the same terminal I ran the command from. This still works if calling the executable from the full path. E.g.:
> ![image](https://user-images.githubusercontent.com/47462792/213867624-de5356ba-51b4-4cea-8c51-9f6536fc1367.png)

Nowadays, however, the running a GUI app from the CLI spawns a process in the terminal. E.g.:
- In the case of Fork
> ![image](https://user-images.githubusercontent.com/47462792/213867915-d318ae1f-40c8-4807-8e79-634b5229d27a.png)

- Slack prints its logs
> ![image](https://user-images.githubusercontent.com/47462792/213867958-e12d9b4b-00cc-40ea-ac79-e80c8a2a99d2.png)

This behavior is not omnipresent on all GUI apps. For example, VSCode still works as expected, probably because it doesn't have a shim (see next screen). PyCharm on the other hand, has a shim but doesn't spawn a process. However, running `pycharm .` doesn't open it in the current directory.
> ![image](https://user-images.githubusercontent.com/47462792/213868076-59187eda-979f-46cb-910f-21bf87eb9f62.png)

#### Describe the solution you'd like

Running a GUI app from the CLI doesn't spawn a process. A drawback I guess is that one can't kill the app by pressing CTRL+C in the terminal, I assume.

#### Describe alternatives you've considered

So far, what I do is run a GUI app like this: `fork . &`. This allows me to keep using the same terminal but creates a process in the background, e.g.:

> ![image](https://user-images.githubusercontent.com/47462792/213868432-b5ab7b58-f924-4897-b0e7-5f95bff46b38.png)

**Comment by rashil2000** [comment]
Yeah, this is a known issue, being tracked in #1606
