### ISSUE TITLE
[Bug] Scoop wont install git 

### ISSUE THREAD

**Issue by TsunayoshiSawada** [ScoopInstaller/Scoop#5356]
## Bug Report
![image](https://user-images.githubusercontent.com/34431649/214226627-373f3054-81bc-49d3-8dae-ad0a672d9fb1.png)

#### Additional context/output
Git was annoying with warning messages, so wanted to reinstall it, uninstalled and then tried to reinstall. 
Now it wont install git, but also wont stop complaining that i didn't install it 

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:**
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      19041  2364

**Comment by HUMORCE** [comment]
How about this: `scoop install git -u`

**Comment by rashil2000** [comment]
> How about this: `scoop install git -u`

This is the correct workaround
