### ISSUE TITLE
[Bug] Unable to download release assets from private GitHub repositories

### ISSUE THREAD

**Issue by jeppefrandsen** [ScoopInstaller/Scoop#5357]
## Bug Report

GitHub has changed the required API headers lately causing download of release assets from private GitHub repositories not to work. See https://docs.github.com/en/rest/releases/assets?apiVersion=2022-11-28

#### Current Behavior
Download of release assets from private GitHub repositories does not work

#### Expected Behavior
Download works

#### Possible Solution
A small fix can be found here: https://github.com/polytech-com/Scoop/commit/e3d4113a83a048c68418b55f6087c20b4ac8b20c. Can do a PR when discussed.

### System details

**Windows version:** 11

**OS architecture:** arm64

**PowerShell version:**
```
$($PSVersionTable.PSVersion)

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      22000  1335
```

**Additional software:** git

#### Scoop Configuration

```json
{
    "last_update":  "2023-01-26T07:36:02.8236585+01:00",
    "use_external_7zip":  false,
    "gh_token":  "ghp_xxxxxxxx",
    "scoop_branch":  "master",
    "scoop_repo":  "https://github.com/ScoopInstaller/Scoop"
}
```

**Comment by rashil2000** [comment]
Please make a PR!

**Comment by qlyoung** [comment]
It appears this applies to all repositories, not just private ones.

![image](https://user-images.githubusercontent.com/6827003/215796917-a466baaf-4303-4ced-bc19-6765fdfde7c8.png)
