### ISSUE TITLE
[Bug] Helix: HELIX_RUNTIME envar missing, not setup during install

### ISSUE THREAD

**Issue by helmesjo** [ScoopInstaller/Scoop#5358]
#### Current Behavior
1. `scoop install helix`
2. `hx --tutor`
3. Blank buffer.

Same issue with themes, none are found.

#### Expected Behavior
Resources should be found. They are available at the same location as the executable.

#### Additional context/output
It works with `choco` installed helix.

#### Possible Solution
During install, scoop should setup this environment variable: `HELIX_RUNTIME=<scoop prefix helix>/runtime`

**Comment by rashil2000** [comment]
See https://github.com/ScoopInstaller/Main/pull/3780#issuecomment-1194433842

**Comment by helmesjo** [comment]
Odd, since evidently it did not work for me. Running scoop install inside mingw64 perhaps contributed? To solve it I had to add the envar manually.
