### ISSUE TITLE
[Bug] Scoop uses cygwin git instead of its own, resulting in path issues

### ISSUE THREAD

**Issue by pjeby** [ScoopInstaller/Scoop#5363]
#### Current Behavior
When running `scoop install`, scoop tries to update itself using the first `git` on the path -- which in my case is cygwin rather than msys.  This results in the behavior described in #2221 -- i.e. the update failing with a bad path.

#### Expected Behavior
Scoop should use the version of git it installed, regardless of the `PATH`.

#### Additional context/output
```
fatal: Invalid path '/cygdrive/e/Users/pje/cyghome/C:\Users\pje\scoop\apps\scoop\current\..\new': No such file or directory
Remove-Item: C:\Users\pje\scoop\apps\scoop\current\libexec\scoop-update.ps1:81
```

#### Possible Solution
I was able to fix this locally by changing this line of the `git_cmd` function (in core.ps1):

```ps1
    $cmd = "git $($args | ForEach-Object { "$_ " })"
```

to read instead:

```ps1
    $cmd = "$(versiondir 'git' 'current')\bin\git $($args | ForEach-Object { "$_ " })"
```

This explicitly invokes the current scoop-installed git version rather than whatever happens to be on the `PATH`.

### System details

**Windows version:** 7

**OS architecture:** 64-bit

**PowerShell version:** 7.1.7

#### Scoop Configuration

```json
{
  "last_update": "2023-01-30T04:37:18.9607384-05:00",
  "scoop_repo": "https://github.com/ScoopInstaller/Scoop",
  "scoop_branch": "master"
}
```

**Comment by rashil2000** [comment]
This is expected behavior. Scoop will use the first Git it finds on PATH - so that user's choice is preferred. Not everyone installs Git via Scoop.

**Comment by pjeby** [comment]
Weird -- I could've sworn that scoop installed git itself -- I certainly didn't ask it to do so.

**Comment by rashil2000** [comment]
The only applications Scoop is allowed to install itself are extraction utilities - 7zip, lessmsi, dark etc. 

Git is either installed by the user, or is installed as a dependency of another Scoop application.
