### ISSUE TITLE
scoop install fzf

### ISSUE THREAD

**Issue by TGAyouman** [ScoopInstaller/Scoop#5368]
❯ scoop install fzf
WARN  Purging previous failed installation of fzf.
Uninstalling 'fzf' ().
'fzf' was uninstalled.
Installing 'fzf' (0.37.0) [64bit]
The SSL connection could not be established, see inner exception.
URL https://hub.fastgit.org/junegunn/fzf/releases/download/0.37.0/fzf-0.37.0-windows_amd64.zip is not valid

**Comment by TGAyouman** [comment]
❯ scoop install fzf
WARN  Purging previous failed installation of fzf.
Uninstalling 'fzf' ().
'fzf' was uninstalled.
Installing 'fzf' (0.37.0) [64bit]
fzf-0.37.0-windows_amd64.zip (1.5 MB) [===>                                                                   ]   5%
 Received an unexpected EOF or 0 bytes from the transport stream.
URL https://hub.fastgit.org/junegunn/fzf/releases/download/0.37.0/fzf-0.37.0-windows_amd64.zip is not valid

**Comment by TGAyouman** [comment]
Latest problem encountered

**Comment by HUMORCE** [comment]
Cannot reproduce.

```
❯ scoop download fzf
INFO  Downloading 'fzf' [64bit] from main bucket
fzf-0.37.0-windows_amd64.zip (1.5 MB) [===================================================================================] 100%
Checking hash of fzf-0.37.0-windows_amd64.zip ... ok.
'fzf' (0.37.0) was downloaded successfully!
```

- `https://hub.fastgit.org/junegunn/fzf/releases/download/0.37.0/fzf-0.37.0-windows_amd64.zip` is not the original download link in the manifest. you are downloading this app from a github mirror.
- `Installing 'fzf' (0.37.0) [64bit]`, it looks like you are using an older version of Scoop or forks.

**Comment by HUMORCE** [comment]
If you are using mirror buckets or forks of Scoop, you will need to submit an issue to the corresponding repo.

```
scoop bucket list
scoop config
scoop --version
```
