### ISSUE TITLE
[Bug] New-Item: Incorret function pwsh 7

### ISSUE THREAD

**Issue by rafaeloledo** [ScoopInstaller/Scoop#5376]
#### Current Behavior

![image](https://user-images.githubusercontent.com/51183852/216792689-af754245-a07d-4af4-8d8c-11adda824260.png)

#### Expected Behavior

Install ``7zip`` like on my home directory:

![image](https://user-images.githubusercontent.com/51183852/216792982-4005d40a-90f5-47e1-975c-efa300c4095b.png)

#### Additional context/output

My scoop stopped working and i don't know why. I'm using an external ssd drive with ``exFAT``.

#### Possible Solution

I don't know if the reason is the external ssd ``exFAT`` partition, may i use ``NTFS``?

### System details

**Windows version:** [e.g. 7, 8, 10, 11]
11
**OS architecture:** [e.g. 32bit, 64bit, arm64]
64-bit

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]
5.1 and 7+

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
{
  "last_update": "2023-02-04T18:29:13.1907304-03:00",
  "root_path": "X:\\windows\\scoop",
  "scoop_repo": "https://github.com/ScoopInstaller/Scoop",
  "scoop_branch": "master"
}

```

**Comment by rafaeloledo** [comment]
I'll be testing installing scoop with another ssd drive with ``NTFS``. Please wait for more details in this comment.

**Comment by chawyehsu** [comment]
Yes. Scoop uses `NTFS Junctions` to work. There is a NTFS check with `scoop checkup`.

**Comment by rafaeloledo** [comment]
> 

Thank you for solving this question. Closing this issue.

**Comment by rafaeloledo** [comment]
> Yes. Scoop uses `NTFS Junctions` to work. There is a NTFS check with `scoop checkup`.

Thank you for solving this question. Closing this issue.
