### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by liugy111** [ScoopInstaller/Scoop#5397]
## Bug Report
I can't install latexindent in windows 10 using powershell.

#### Current Behavior

when input the command ——'scoop install latexindent'.

![屏幕截图 2023-02-20 200213](https://user-images.githubusercontent.com/59353225/220101529-60e5c11e-bcdf-4b99-bd41-bed21461440a.jpg)

### System details

**Windows version:** [e.g. 7, 8, 10, 11]
win10
**OS architecture:** [e.g. 32bit, 64bit, arm64]
64bit
**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]
![屏幕截图 2023-02-20 200659](https://user-images.githubusercontent.com/59353225/220101809-904195c2-5cf7-4be2-a9b3-7952baee0ae3.jpg)

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

![屏幕截图 2023-02-20 200842](https://user-images.githubusercontent.com/59353225/220102077-279b7f19-8f73-4311-86aa-018f22b5b9ad.jpg)

```json
//# Your configuration here
```

**Comment by liugy111** [comment]
![屏幕截图 2023-02-20 200213](https://user-images.githubusercontent.com/59353225/220101367-2b486af6-8163-46b1-98fa-3a984fcae29e.jpg)

**Comment by rashil2000** [comment]
Fixed https://github.com/ScoopInstaller/Main/commit/07c81b4931b6a5aa371f5b1dea1fcb014e8c4340
