### ISSUE TITLE
Update failed.

### ISSUE THREAD

**Issue by place76** [ScoopInstaller/Scoop#5403]
Hello, I don't know how to solve this problem

C:\Users\admin>scoop update
Updating Scoop...
hint: You have divergent branches and need to specify how to reconcile them.
hint: You can do so by running one of the following commands sometime before
hint: your next pull:
hint:
hint:   git config pull.rebase false  # merge
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint:
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
fatal: Need to specify how to reconcile divergent branches.
Update failed.

**Comment by tauinger-de** [comment]
Me too... What to do?
