### ISSUE TITLE
Why the 'nirsoft' bucket is not being maintained?

### ISSUE THREAD

**Issue by cvladan** [ScoopInstaller/Scoop#5406]
May I ask why the default 'nirsoft' bucket is set to this repository:

    https://github.com/kodybrown/scoop-nirsoft

when we have a seemingly more reliable option available:

    https://github.com/ScoopInstaller/Nirsoft

Shouldn't the latter be considered as the "official" one?
Either way, the first repository appears to be unmaintained.

![image](https://user-images.githubusercontent.com/1913156/221507361-79501937-9839-40f7-ad4f-e34a08e1a61a.png)

**Comment by cvladan** [comment]
I have just stumbled across this topic https://github.com/ScoopInstaller/Scoop/discussions/5293.
Please act as soon as possible, it would be greatly appreciated.

**Comment by rashil2000** [comment]
Discussed in #5293
