### ISSUE TITLE
[Bug] try to install older version of vscode, but failed

### ISSUE THREAD

**Issue by kaykouo** [ScoopInstaller/Scoop#5417]
C:\Users\Admin> scoop reset vscode@1.75.1
ERROR 'vscode (1.75.1)' isn't installed
C:\Users\Admin> scoop install vscode@1.75.1
WARN  Given version (1.75.1) does not match manifest (1.76.0)
WARN  Attempting to generate manifest for 'vscode' (1.75.1)
Autoupdating vscode
Searching hash for dl.7z in https://code.visualstudio.com/sha?build=stable
Found: 957941c9795bc9ac58ba67b8bc72fd5152d4eefb4b24bb55aa957458930b03a7 using Json Mode
Searching hash for dl.7z in https://code.visualstudio.com/sha?build=stable
Found: 310197686a2b7496048d98771c73cf26bf4a4b8ff5395c16692826fc12bafa2b using Json Mode
Searching hash for dl.7z in https://code.visualstudio.com/sha?build=stable
Found: caab47d3b724b31ac40d4d9dd4ac15c85dd1c007d148d570f514a3927991745f using Json Mode
Writing updated vscode manifest
Installing 'vscode' (1.75.1) [64bit]
dl.7z (125.2 MB) [========================================================================] 100%
Checking hash of dl.7z ... ERROR Hash check failed!
App:         vscode
URL:         https://update.code.visualstudio.com/1.75.1/win32-x64-archive/stable#/dl.7z
First bytes: 50 4B 03 04 14 00 00 00
Expected:    310197686a2b7496048d98771c73cf26bf4a4b8ff5395c16692826fc12bafa2b
Actual:      d231b591feb3f184ecf8eebeef54f821e6aa42f6f23cf0b308ac363a4d319575

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=vscode%401.76.0%3a+hash+check+failed

**Comment by rashil2000** [comment]
Use `scoop install vscode@1.75.1 -s`
