### ISSUE TITLE
Installing scoop :  The SSL connection could not be established

### ISSUE THREAD

**Issue by Oldmanpitsa54** [ScoopInstaller/Scoop#5419]
Trying to install scoop using powershell 7 I faced this exception: 

Invoke-Expression: Exception calling "DownloadFile" with "2" argument(s): "The SSL connection could not be established, see inner exception."

Any solutions in internet didn`t work.

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Scoop/issues?q=is%3Aissue+SSL+connection+is%3Aclosed
