### ISSUE TITLE
[Bug] Scoop excess lines at the end of scoop update * output in nushell

### ISSUE THREAD

**Issue by bboysnick5** [ScoopInstaller/Scoop#5420]
I just migrated to nushell. After executing scoop update *, it just printed a lot of errors at the end like following:

Can anyone advise?

#### Current Behavior

Scoop has excess lines at the end of scoop update * output in nushell, like below. It seems it treats my user home dir as the installed apps dir. I did an experiement of running 
```powershell
  Get-ChildItem $dir | Where-Object { $_.psiscontainer -and $_.name -ne 'scoop' } | ForEach-Object { $_.name }
```
which is enclosed in the installed_apps func in core.ps1 file directly in the powershell without specifying the $dir var. And the output are all the files and dirs in my home directory. Seems scoop somehow didn't correctly assign the value of $dir. 

```shell
Updating Scoop...
Updating 'extras' bucket...
Updating 'main' bucket...
Updating 'nerd-fonts' bucket...
Scoop was updated successfully!
ERROR '.Origin' isn't installed.
ERROR '.QtWebEngineProcess' isn't installed.
ERROR '.VirtualBox' isn't installed.
ERROR '.aws' isn't installed.
ERROR '.azure' isn't installed.
ERROR '.cache' isn't installed.
ERROR '.conda' isn't installed.
ERROR '.config' isn't installed.
```

#### Expected Behavior

```shell
Updating Scoop...
Updating 'extras' bucket...
Updating 'main' bucket...
Updating 'nerd-fonts' bucket...
Scoop was updated successfully!
```

### System details

**Windows version:** [e.g. 7, 8, 10, 11]
11
**OS architecture:** [e.g. 32bit, 64bit, arm64]
x64
**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]
7.3.3
**Additional software:** [(optional) e.g. ConEmu, Git]
nushell
#### Scoop Configuration

```json
{
  "last_update": "2023-03-05T11:41:51.7321302+08:00",
  "verbose": "0",
  "scoop_repo": "https://github.com/ScoopInstaller/Scoop",
  "scoop_branch": "master"
}```

**Comment by rashil2000** [comment]
Try `scoop update '*'` or `scoop update -a`. 

Nushell is globbing the * character, that's why this is happening.

**Comment by bboysnick5** [comment]
Beautiful. Lovely. Thanks.
