### ISSUE TITLE
`scoop export -c` does not export shim settings

### ISSUE THREAD

**Issue by eggbean** [ScoopInstaller/Scoop#5442]
Not really a bug as such, but there is not more suitable option.

`scoop export -c` doesn't seem to have any information on shim setup. I have spent some time setting adjusting shims to either use the `uutils-coreutils` or `busybox` commands, so I would like to be able to save those somewhere. Is there a file I could backup?

**Comment by eggbean** [comment]
I don't want all of them set to one or the other. I have specified most coreutils commands to use busybox, but some to be shimmed to uutils-coreutils, like ls for example.

Because I have set various shims one way or the other is why I would like to save the shim settings. Is there not a file where this configuration is which can be backed up>

**Comment by rashil2000** [comment]
> I have spent some time setting adjusting shims to either use the `uutils-coreutils` or `busybox` commands, so I would like to be able to save those somewhere. Is there a file I could backup?

How have you done this?

**Comment by rashil2000** [comment]
Closing this as shim information is not really stored anywhere - it's stateless. So we can't back it up. 

We might be able to help come up with a simple script to help restore the shims, see my previous question.

**Comment by eggbean** [comment]
Sorry, I forgot to reply.

I change shim using:

`scoop shim add <shim_name> <command_path> [<args>...]`

For example, I choose to use the uutils-coreutils version of ls instead of the busybox one. IIRC, that's because it handles slash/backslash paths a lot better.

So, yes - I can easily make a script to set them as before. For the time being I made a note of how the shims are set with:

`scoop shim list > scoopshimlist.txt`

Cheers.
