### ISSUE TITLE
[Bug] Handle error message if expired/invalid Github Token is used

### ISSUE THREAD

**Issue by r15ch13** [ScoopInstaller/Scoop#5449]
#### Current Behavior
If the configured Github Token `gh_token` is expired or invalid then a unhandled error message is shown

#### Expected Behavior
Handle message and suggest actions to user

#### Additional context/output
```pwsh
Installing 'fancontrol' (152) [64bit] from extras bucket
Invoke-RestMethod: X:\~projects\~powershell\scoop\lib\core.ps1:1241:14
Line |
1241 |  …        if ((Invoke-RestMethod -Uri $privateUrl -Headers $headers).Pri …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | {"message":"Bad credentials","documentation_url":"https://docs.github.com/rest"}
Starting download with aria2 ...
```

#### How to reproduce
```
scoop config gh_token asdf
scoop install <app>
```

### System details

**Windows version:** [e.g. 7, 8, 10, 11]

**OS architecture:** [e.g. 32bit, 64bit, arm64]

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
{
  "debug": true,
  "gh_token": "asdf",
  "aria2-warning-enabled": false,
  "scoop_branch": "develop",
  "scoop_repo": "https://github.com/ScoopInstaller/Scoop"
}
```

**Comment by maokwen** [comment]
```
Downloading new version
OperationStopped: C:\Users\maokw\scoop\apps\scoop\current\lib\install.ps1:111
Line |
 111 |          throw $e
     |          ~~~~~~~~
     | Response status code does not indicate success: 401 (Unauthorized).
```

**Comment by fvydjt** [comment]
This bug is really annoying. I encountered it and it wasted me a lot of time. What's more, I can't even find similar issues by searching the error message. Then I guess the problem may be caused by gh_token so I get here finally. By the way, it seems that the scoop wiki doesn't introduce the config.json.
