### ISSUE TITLE
[Feature] add multiple buckets with one command

### ISSUE THREAD

**Issue by soredake** [ScoopInstaller/Scoop#5477]
#### Is your feature request related to a problem? Please describe.
Right now if you try to do `scoop bucket add games extras` for example it will only add games bucket, there is no way to add two or more bucket with one command.

#### Describe the solution you'd like
Ability to install multiple buckets with `scoop bucket add`

#### Describe alternatives you've considered
foreach loop or something like this.

**Comment by HUMORCE** [comment]
I think this should be done by commands of SHELL.

```powershell
❯ 'games', 'extras' | foreach { scoop bucket add $_ }
```

For buckets not in known list, you need to specify 2 args: `<name>` and `<repo>`

```powershell
❯ @{
∙ "nuke"="https://github.com/HUMORCE/nuke.git"
∙ "example"="https://example.com/example/example_bucket.git"
∙ }.GetEnumerator() | foreach { scoop bucket add $_.Key $_.Value }
```

**Comment by soredake** [comment]
@HUMORCE i don't understand why this be implemented in scoop.

**Comment by HUMORCE** [comment]
Sorry, I'm not sure what you mean.

**Comment by rashil2000** [comment]
This should be easy enough to achieve using the shell pipeline, as @HUMORCE suggested. Implementing this internally would entail unnecessary complexities.

**Comment by soredake** [comment]
@rashil2000 you should close this as "not planned" rather than "completed".
