### ISSUE TITLE
[Bug] Scoop is trying to install to a different (empty) drive

### ISSUE THREAD

**Issue by majdf4** [ScoopInstaller/Scoop#5497]
## Bug Report
Scoop keeps trying to install to an "E:\" drive, which is my usb-c hub. It is empty and has nothing in it, as shown in a picture linked below

#### Current Behavior
Scoop is trying to install to a drive named "E:\"

#### Expected Behavior
Scoop is supposed to install to my home dir, without any issues

#### Additional context/output
```
PS C:\Users\user> iwr -useb get.scoop.sh | iex
Initializing...
Downloading ...
New-Item:
Line  |
 590 |              New-Item -Type Directory $SCOOP_APP_DIR | Out-Null
        |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        | The device is not ready. : 'E:\Scoop\apps\scoop\current'
```

### System details

**Windows version:** Windows 11

**OS architecture:** 64bit

**PowerShell version:** 7.3.4

### Images
![image](https://user-images.githubusercontent.com/77127406/235821108-d67fff85-4bf9-46fa-ae48-e96dab510331.png)
![image](https://user-images.githubusercontent.com/77127406/235821175-a064e004-c558-4fae-9626-4f1b8d37171b.png)

**Comment by HUMORCE** [comment]
Check your environment variable `$env:SCOOP`. maybe `$env:SCOOP_GLOBAL` should be checked as well.

https://github.com/ScoopInstaller/Scoop/wiki/Quick-Start#installing-scoop-to-custom-directory

**Comment by majdf4** [comment]
issue was fixed, thank you so much!
