### ISSUE TITLE
[Feature] How to set the update order of software?

### ISSUE THREAD

**Issue by berial** [ScoopInstaller/Scoop#5500]
#### Is your feature request related to a problem? Please describe.

`clash-chinese-patch` depends `clash-for-windows`. But when I use 'scoop update *' for updates, `clash-chinese-patch` always starts updating before `clash-for-windows` and prompts for failure.

#### Describe the solution you'd like

Can I customize an update order?

#### Describe alternatives you've considered

```
$ scoop update clash-for-windows # Step 1
$ scoop update clash-chinese-patch # Step 2
```

**Comment by HUMORCE** [comment]
**Manifest**
Copy `clash-for-windows` to your own bucket, use [this function](https://github.com/ScoopInstaller/Scoop/wiki/Pre-Post-(un)install-scripts#appdir) for copying files everytime of install|update.

**Alias**
```
scoop alias add add '$args | foreach { scoop install $_ }
scoop alias add up '$args | foreach { scoop update $_ }
```

**Comment by StarsbySea** [comment]
Another way to do it is that you hold the two apps mentioned earlier before updating all of them, then update all of them first, then unhold them afterwards, and then update them in the specified order. Sort of like this.
```pwsh
scoop hold clash-for-windows clash-chinese-patch
scoop update --all
scoop unhold clash-for-windows clash-chinese-patch
scoop update clash-for-windows
scoop update clash-chinese-patch
```
You can write a ps1 file to quickly perform the above actions.
If you have any more questions, feel free to leave your thoughts and if this solves your problem, please close the issue.
