### ISSUE TITLE
[Bug] Missing shim(s) after User-Account AdminRights-Revoke [Feature] CLI Hint/Info for this case

### ISSUE THREAD

**Issue by subsix-wow** [ScoopInstaller/Scoop#5501]
#### Current Behavior

1. I installed Scoop with the actual `UserA` being an Administrator Group-Member.
2. Installing several Apps (User- and Admin-Rights required ones) -> So far everything works.
3. Create new Account `UserB` - being a member of Administrator-Group aswell
5. Remove Administrator Group-Membership of `UserA`
6. Try to update any Admin-Rights required Application as `UserA`
7. Get an Error (German sorry!) similar to the following: 
8. `Aktualisierung anwenden...
Der Pfad "C:\Users\UserB\scoop\shims" kann nicht gefunden werden, da er nicht vorhanden ist.ERROR 'tailscale' isn't installed.`

#### Expected Behavior

1. Should update the Apps or point the user in the right direction as follows...

#### Possible Solution

1. Should advise/point the user to a possible workaround
2. Maybe some GitHub hosted FAQs/Wiki Link

### System details

**Windows version:** [e.g. 7, 8, 10, 11]
11
**OS architecture:** [e.g. 32bit, 64bit, arm64]
amd64
**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]
5.1.22621.963
**Additional software:** [(optional) e.g. ConEmu, Git]
WinGetUI, Windows-Terminal
#### Scoop Configuration

```json
{
    "last_update":  "2023-05-06T21:52:02.3757455+02:00",
    "scoop_branch":  "master",
    "scoop_repo":  "https://github.com/ScoopInstaller/Scoop"
}

```

**Comment by subsix-wow** [comment]
Please don't get mad at me... 
I've been searching for this issue on a well known Search-Engine before, even here through the existing issues...

If I might have missed something... Please advise me and don't be mad... 

Best wishes and keep up your awesome work!

**Comment by HUMORCE** [comment]
https://github.com/ScoopInstaller/Scoop/wiki/Global-Installs

**Comment by subsix-wow** [comment]
> https://github.com/ScoopInstaller/Scoop/wiki/Global-Installs

Thank you so far... Will try this, but still... This might be worth mentioning in the Console Output for other users, which might be facing that issue... 

Thanks again!

**Comment by subsix-wow** [comment]
Sorry for Double-Posting.

Is there a way to in-/uninstall Scoop Apps for a specific user? This might be helpful as well regarding Multi-User Administration (Like Force Un-/Install)

**Comment by HUMORCE** [comment]
> Try to update any Admin-Rights required Application as UserA
> Get an Error (German sorry!) similar to the following:
> Aktualisierung anwenden... Der Pfad "C:\Users\UserB\scoop\shims" kann nicht gefunden werden, da er nicht vorhanden ist.ERROR 'tailscale' isn't installed.

It looks like you are using a method like RUNAS to executing Scoop. you cannot install apps for userA in userB's environment without additional settings, by design.

**Comment by subsix-wow** [comment]
> > Try to update any Admin-Rights required Application as UserA
> > Get an Error (German sorry!) similar to the following:
> > Aktualisierung anwenden... Der Pfad "C:\Users\UserB\scoop\shims" kann nicht gefunden werden, da er nicht vorhanden ist.ERROR 'tailscale' isn't installed.
> 
> It looks like you are using a method like RUNAS to executing Scoop. you cannot install apps for userA in userB's environment without additional settings, by design.

Thanks for clarifying... I was able to partially fix my issue through reinstalling Scoop+Additions as `UserB` aswell with the `--global ` CLI addition...

Therefore I'll close this issue. Thank you very much for your time&effort.
