### ISSUE TITLE
[Wiki] App Manifest page does not list all supported architectures

### ISSUE THREAD

**Issue by tehmantra** [ScoopInstaller/Scoop#5509]
The App Manifest page lists the two available arcitectures as `32bit|64bit`.

This could be confusing for new contributors who might not include arm64 or other supported architectures.

For example: 
https://github.com/ScoopInstaller/Main/pull/4805

> - `architecture`: If the app has 32- and 64-bit versions, architecture can be used to wrap the differences ([example](https://github.com/ScoopInstaller/Main/blob/master/bucket/7zip.json)).
>     - `32bit|64bit`: contains architecture-specific instructions ...

(https://github.com/ScoopInstaller/Scoop/wiki/App-Manifests#optional-properties)

**Comment by HUMORCE** [comment]
Updated
