### ISSUE TITLE
Use proxy script

### ISSUE THREAD

**Issue by maximunited** [ScoopInstaller/Scoop#5510]
My corporate windows is configured to use a proxy script (https://some-domain.com/proxy.pac)
When using VPN or on the company network, a proxy is required. But when I'm home, a proxy is unreachable.

Please make scoop work with the proxy script or some other logic to detect automatically if proxy is needed or not.

I also tried using `default` or `currentuser@default`.

Doesn't work:
```
C:\Users\admin>scoop config proxy default
'proxy' has been set to 'default'

C:\Users\admin>scoop update
Updating Scoop...
fatal: unable to access 'https://github.com/ScoopInstaller/Scoop/': Could not resolve proxy: default
Update failed.
```

**Comment by HUMORCE** [comment]
`scoop config rm proxy`

**Comment by maximunited** [comment]
Thanks, I'm aware of how to delete the proxy. What I'm asking is how to change it dynamically every time I connect and disconnect to the VPN?

**Comment by HUMORCE** [comment]
Fallback to a direct connection is bad idea, when the user has explicitly set up a proxy server for Scoop.

Try wraping proxy server by these tools: `main/xray`, `main/v2ray`, `main/clash`
