### ISSUE TITLE
[Bug] Inproper behaviour of nmap shims creation

### ISSUE THREAD

**Issue by Mila-me** [ScoopInstaller/Scoop#5513]
#### Current Behavior
Cannot create shim for ndiff.exe, because there is no such file.

#### Expected Behavior
Create shim for ndiff.bat.

#### Additional context/output
 Creating shim for 'ndiff'.
 Can't shim 'ndiff.exe': File doesn't exist.

#### Possible Solution
Fix manifest to use ndiff.bat in place of ndiff.exe

### System details

**Windows version:** 11

**OS architecture:** 64bit

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration
```json
{
    "last_update":  "2023-05-23T01:07:24.9957585+02:00",
    "scoop_branch":  "master",
    "scoop_repo":  "https://github.com/ScoopInstaller/Scoop"
}
```

**Comment by HUMORCE** [comment]
https://github.com/ScoopInstaller/Main/pull/4826
