### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by keenam** [ScoopInstaller/Scoop#5524]
## Bug Report

git version 2.41.0.windows.1 
Portable version from scoop

#### Current Behavior
git fetch command line takes a long time.

git.exe fetch --all -v --progress
Fetching origin
1 [main] sh (2552) C:\Users\knam\scoop\apps\git\2.41.0.windows.1\usr\bin\sh.exe: *** fatal error - add_item ("\??\C:\Users\knam\scoop\apps\git\2.41.0.windows.1", "/", ...) failed, errno 1
Stack trace:
Frame         Function      Args
0007FFFFCD30  00021006116E (000210290E7A, 000210272B51, 00000000007F, 0007FFFF8B30) msys-2.0.dll+0x2116E
0007FFFFCD30  0002100469BA (000000000000, 0007FFFFCD30, 0001A1000010, 0007FFFFAC22) msys-2.0.dll+0x69BA
0007FFFFCD30  0002100469F2 (0007FFFF9BC0, 000000000001, 00000000007F, 000000000001) msys-2.0.dll+0x69F2
0007FFFFCD30  00021007E7B7 (000700000000, 000040000024, 000000000000, 000000000000) msys-2.0.dll+0x3E7B7
0007FFFFCD30  0002101832F5 (0002100731D4, 000000000000, 000000000000, 000000000000) msys-2.0.dll+0x1432F5
0007FFFFCD30  000210047012 (000000000000, 000000000000, 000000000000, 000000000000) msys-2.0.dll+0x7012
0007FFFFFFF0  000210045C86 (000000000000, 000000000000, 000000000000, 000000000000) msys-2.0.dll+0x5C86
0007FFFFFFF0  000210045D34 (000000000000, 000000000000, 000000000000, 000000000000) msys-2.0.dll+0x5D34
End of stack trace
Loaded modules:
000100400000 sh.exe
7FFEA9590000 ntdll.dll
7FFEA8740000 KERNEL32.DLL
7FFEA7060000 KERNELBASE.dll
7FFEA8800000 USER32.dll
7FFEA7490000 win32u.dll
7FFEA9520000 GDI32.dll
7FFEA6C70000 gdi32full.dll
7FFEA7550000 msvcp_win.dll
7FFEA7360000 ucrtbase.dll
000210040000 msys-2.0.dll
7FFEA8690000 advapi32.dll
7FFEA9420000 msvcrt.dll
7FFEA85E0000 sechost.dll
7FFEA9290000 RPCRT4.dll
7FFEA6470000 CRYPTBASE.DLL
7FFEA74C0000 bcryptPrimitives.dll
7FFEA85A0000 IMM32.DLL

#### Expected Behavior
command carried out successfully

### System details
Window 10
64bit

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]: 5.1.19041.3031

#### Scoop Configuration

```json
//# Your configuration here
```

**Comment by keenam** [comment]
workaround: rollback to **git version 2.40.1.windows.1**

**Comment by HUMORCE** [comment]
Please provide a minimal reproduction to confirm it is related to Scoop.

**Comment by keenam** [comment]
Sorry, I confirmed it's not related to the scoop but other library components
