### ISSUE TITLE
Trojan:Script/Wacatac.B!ml when updating (terraform 1.4.6 -> 1.5.0)

### ISSUE THREAD

**Issue by shellwhale** [ScoopInstaller/Scoop#5535]
When updating (terraform 1.4.6 -> 1.5.0)

![image](https://github.com/ScoopInstaller/Scoop/assets/36083584/46da88f6-9b3d-4cec-a91f-aa446d0d6cf9)
![image](https://github.com/ScoopInstaller/Scoop/assets/36083584/e057c3c1-236e-49bd-8d59-24da58a20953)

### System details

**Windows version:** [e.g. 7, 8, 10, 11]
10

**OS architecture:** [e.g. 32bit, 64bit, arm64]
64bit

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]
7.3.4

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
{
  "last_update": "2023-06-14T10:46:01.4851764+02:00",
  "scoop_branch": "master",
  "scoop_repo": "https://github.com/ScoopInstaller/Scoop"
}
```

**Comment by HUMORCE** [comment]
I think you should report this to [upstream](https://github.com/hashicorp/terraform).
