### ISSUE TITLE
[Feature] scoop.sh should allow filtering by buckets

### ISSUE THREAD

**Issue by milnak** [ScoopInstaller/Scoop#5553]
Couldn't figure out the best place to put this, but I like to browse https://scoop.sh/#/apps to find new scoop apps.  Currently it shows "Newest, official buckets only".  I'd love to be able to have it show "Newest, {main, extras} buckets only" (for example).

Any chance this could be added?

**Comment by HUMORCE** [comment]
> Couldn't figure out the best place

https://github.com/ScoopInstaller/scoopinstaller.github.io

**Comment by milnak** [comment]
thanks, I'll move this there.
