### ISSUE TITLE
[Bug] url_remote_filename function cannot fetch filename behind auto jump url

### ISSUE THREAD

**Issue by laris** [ScoopInstaller/Scoop#5555]
#### Current Behavior

I test one bucket win11sdk json file here:
https://github.com/tree-s/windowsSDK/blob/master/bucket/windows11SDK.json
In the json file, the url came from official ms website: [Windows SDK - Windows app development | Microsoft Developer](https://developer.microsoft.com/en-us/windows/downloads/windows-sdk/)
The download url are behind after https://go.microsoft.com/fwlink/?linkid=2237387
If we click the url or download it then it will return the true url:
https://download.microsoft.com/download/b/8/5/b85bd06f-491c-4c1c-923e-75ce2fe2378e/windowssdk/winsdksetup.exe

but the url_remote_filename function only analysis the url value:
    "url": "https://go.microsoft.com/fwlink/?linkid=2237387",

Then the return value will only remain **fwlink** as filename.
In install progress the hash stage will report error
```
scoop install .\windows11sdk_v1.json
Installing 'windows11sdk_v1' (10.0.22621.1778) [64bit]
fwlink (1.3 MB) [=============================================================================================] 100%
Checking hash of fwlink ... You cannot call a method on a null-valued expression.
At C:\Users\Laris\scoop\apps\scoop\current\lib\install.ps1:674 char:5
+     $actual = (Get-FileHash -Path $file -Algorithm $algorithm).Hash.T ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Get-Content : Could not find a part of the path 'C:\Users\Laris\scoop\apps\windows11sdk_v1\10.0.22621.1778\'.
At C:\Users\Laris\scoop\apps\scoop\current\lib\core.ps1:1176 char:16
+         return Get-Content $file -Encoding byte -TotalCount 8
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Laris\...0.0.22621.1778\:String) [Get-Content], DirectoryNotFo
   undException
    + FullyQualifiedErrorId : GetContentReaderDirectoryNotFoundError,Microsoft.PowerShell.Commands.GetContentCommand

ERROR Hash check failed!
App:         windows11sdk_v1
URL:         https://go.microsoft.com/fwlink/?linkid=2237387
First bytes:
Expected:    1bf94f7d2cf44cdf50124c3b5745a27b517367435f1bd5d0f127a33b2bd8344c
Actual:

Please try again or create a new issue by using the following link and paste your console output:
https:////

```

#### Expected Behavior

url_remote_filename can extract the true filename after jump to true download url.

#### Possible Solution

maybe any way to get the re-direct url to get filename.
or workaround to get the true url for url value, but it will cannot do automatically

### System details

**Windows version:** [e.g. 7, 8, 10, 11]
win11
**OS architecture:** [e.g. 32bit, 64bit, arm64]
64bit
**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
//# Your configuration here
```

**Comment by HUMORCE** [comment]
This is a bug of manifest not Scoop core.

Solution:

`"url": "https://go.microsoft.com/fwlink/?linkid=2237387",` => `"url": "https://go.microsoft.com/fwlink/?linkid=2237387#/winsdksetup.exe",`

**Comment by laris** [comment]
Thanks to learn it.
