### ISSUE TITLE
[Feature] install multi instance

### ISSUE THREAD

**Issue by avegetablechicken** [ScoopInstaller/Scoop#5557]
#### Is your feature request related to a problem? Please describe.
I installed 2 instances of scoop, one of them installed in %USERPROFILE% and the other in D:\tools (installed later than first one).  I have removed path of the second one from the Path environment and `which scoop` gets the %USERPROFILE% scoop. However, when I use `scoop` with any command, finally it turns out that it finds the D:\ scoop.

#### Describe the solution you'd like

`scoop` command should find related command

**Comment by HUMORCE** [comment]
In current situation, you are impossiable to installs two separate Scoop. (main reson is that config location)

if the config file is ignored, use `$env:SCOOP` to specify installation of Scoop your want.

related: https://github.com/ScoopInstaller/Scoop/pull/5544

**Comment by rashil2000** [comment]
Multiple instances of Scoop are not supported by design.
