### ISSUE TITLE
[Feature] Use PowerShell jobs for updating buckets 

### ISSUE THREAD

**Issue by he3als** [ScoopInstaller/Scoop#5561]
#### Is your feature request related to a problem? Please describe.
When installing or updating Scoop, Scoop has to use Git to fetch and update all of your buckets. However, doing this one after the other is pretty slow.

#### Describe the solution you'd like
Somehow multithreading or making the update process faster with buckets, which could be by using PowerShell jobs so that multiple buckets can be updated at once.

**Comment by r15ch13** [comment]
Already been implemented with #5122 but is currently in develop branch

**Comment by he3als** [comment]
Oh, nice. Any idea when it will be merged into master?
