### ISSUE TITLE
[Feature] support .tool-versions

### ISSUE THREAD

**Issue by simonmcconnell** [ScoopInstaller/Scoop#5564]
#### Is your feature request related to a problem? Please describe.
[asdf](https://asdf-vm.com/) uses `.tool-versions` to specify the specific versions of applications required for a project.  After setting `asdf` up, one can enter `asdf install` in the project directory and it will get the applications (if required) and set the correct version for that project.  `asdf` doesn't work on Windows, but we have `scoop`.  It would be nice to have this support on the Windows side of things.

#### Describe the solution you'd like

`.tool-versions`
```
erlang 25.3.2.2
elixir 1.14.5
```

```
cd myproject
scoop install
# scoop installs applications defined in .tool-versions
# scoop sets the versions of those applications to those defined in .tool-versions
```

#### Describe alternatives you've considered
- `scoop import` could support `.tool-versions`
- define a scoopfile for Windows and maintain both files, which isn't ideal.  However, if the packages are named differently in the `asdf` and `scoop` ecosystems, this would make more sense.

**Comment by rashil2000** [comment]
See https://github.com/ScoopInstaller/Scoop/discussions/4695
