### ISSUE TITLE
VirusTotal detections in compiled supporting excutables

### ISSUE THREAD

**Issue by J0-N3S** [ScoopInstaller/Scoop#5565]
#### Current Behavior
I get multiple VirusTotal detections when I upload the zip file of the repository.
https://www.virustotal.com/gui/file/ce4a3b99c686e8541e6a6684ea773def429017b41bebab6d4d70506781528fbc/relations

I saw that a similar issue was created in #4551 . This time the validator.exe is also included. Are these false positives?

**Files:**
Scoop-master\supporting\shims\71\shim.exe
https://www.virustotal.com/gui/file/70d4690b8ac3b3f715f537cdea6e07a39fda4bc0347bf6b958e4f3ff2f0e04d4
Scoop-master\supporting\shimexe\bin\shim.exe
https://www.virustotal.com/gui/file/9726c3a429009a5b22bd92cb8ab96724c670e164e7240e83f27b7c8b7bd1ca39
Scoop-master\supporting\validator\bin\validator.exe
https://www.virustotal.com/gui/file/40a70bee96d108701f8f2e81392f9b79fd003f1cb4e1653ad2429753153fd7ee

**Comment by HUMORCE** [comment]
> Are these false positives?

Yes

**Comment by J0-N3S** [comment]
Thx :-)

**Comment by HUMORCE** [comment]
Source codes:
`...\supporting\shimexe\bin\shim.exe`: https://github.com/ScoopInstaller/Shim
`...\supporting\shims\71\shim.exe`: https://github.com/71/scoop-better-shimexe
`...\supporting\validator\bin\validator.exe`: https://github.com/ScoopInstaller/Validator

---

`...\supporting\shims\kiennq\shim.exe`: https://github.com/kiennq/scoop-better-shimexe Current default shim, not on the list your provides.

**Comment by Ultrafeel** [comment]
is scoop-search a compiled supporting executable?
https://www.virustotal.com/gui/file/f4e580a394f02d951596c503c9f560bfad4208cea8b77c2f5960c0c2edc3e810/detection
is this a false positives?
@HUMORCE 
where to report it ?

**Comment by HUMORCE** [comment]
> is this a false positives?

Up to you, not anyone else. refer. https://go.dev/doc/faq#virus

> where to report it ?

You can query manifest informations via `scoop info <app>`, https://github.com/shilangyu/scoop-search
