### ISSUE TITLE
scoop shim list scoo* not work as expected (Options MatchTimeout RightToLeft)

### ISSUE THREAD

**Issue by gigberg** [ScoopInstaller/Scoop#5568]
To list all shims or matching shims, use the 'list' subcommand: scoop shim list [<shim_name>/<pattern>...]. However scoop shim list scoo* returns as follow:
![image](https://github.com/ScoopInstaller/Scoop/assets/81040793/ba3ca50e-07ec-436a-871d-d7f9619a08e5)
Obviously, this not output as expected. seem [this](https://github.com/ScoopInstaller/Scoop/pull/4736#issuecomment-1038977262):
![image](https://github.com/ScoopInstaller/Scoop/assets/81040793/3ca364c5-6df0-4254-b18c-196c68464916)

The related source code is [$shims.ForEach({ Get-ShimInfo $_ }) | Add-Member -TypeName 'ScoopShims' -PassThru](https://github.com/ScoopInstaller/Scoop/blob/f93028001fbe5c78cc41f59e3814d2ac8e595724/libexec/scoop-shim.ps1#L166), when I use vscode debug and  breakpoint in this line, and then run the same command in terminal manually "$shims.ForEach({ Get-ShimInfo $_ }) | Add-Member -TypeName 'ScoopShims' -PassThru", the outputs is right. 
![image](https://github.com/ScoopInstaller/Scoop/assets/81040793/339c553d-a5b6-474f-bb64-8932705025c0)

Anyway, I do not know what make this inconsistency. Could anybody give some help?

**Comment by rashil2000** [comment]
This is a regression from #5125 
/cc @niheaven @lewis-yeung

**Comment by niheaven** [comment]
Will check it. Too busy recently, sorry.

**Comment by lewis-yeung** [comment]
There is another bug: `scoop shim info scoo*` outputs this:

```
Name     : scoo*                                                                                                                            
Path     : <SCOOP_ROOT>\shims\scoo*.ps1
Source   : scoop
Type     : ExternalScript
IsGlobal : False
IsHidden : True
```

Related code:

https://github.com/ScoopInstaller/Scoop/blob/f93028001fbe5c78cc41f59e3814d2ac8e595724/libexec/scoop-shim.ps1#L168-L172

https://github.com/ScoopInstaller/Scoop/blob/f93028001fbe5c78cc41f59e3814d2ac8e595724/libexec/scoop-shim.ps1#L82-L89

A name containing wildcards (e.g., `*`) is directly passed to `Get-ShimPath` here.

**Comment by lewis-yeung** [comment]
This is not a bug, IMO. The `<pattern>` in the usage of `scoop shim list [<pattern>...]` is interpreted as a regular expression, and the regular expression `scoo*` does not match any shim names in this case.

As for the output

```
Options RightToLeft MatchTimeout
------- ----------- ------------
   None       False -00:00:00.0010000
```

is produced by the following code:

https://github.com/ScoopInstaller/Scoop/blob/f93028001fbe5c78cc41f59e3814d2ac8e595724/libexec/scoop-shim.ps1#L147

This can be discarded. If we add a `[void]`, it will disappear:

```powershell
[void][Regex]::New($pattern)
```
