### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by sleepyhollo** [ScoopInstaller/Scoop#5570]
#### Current Behavior
Attempting a run a python test with vim-test fails with "python not found" error

#### Expected Behavior
Vim-test should be able to run the test.

#### Additional context/output
```
"python3 -m unittest tests.NAME_OF_TEST"
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

shell returned 9009

Press ENTER or type command to continue
```

#### Possible Solution
Maybe the issue is in the pyunit.vim file (here))

### System details

**Windows version:** 10
**OS architecture:** 64 bit
**PowerShell version:** 5.1.19041.3031
**Additional software:** I am having this problem when i am running vim from command prompt using the [Windows Terminal Preview](https://github.com/microsoft/terminal) SW. However, the issue also happens with CMD

#### Scoop Configuration
I am not sure what this is. I do not have a scoop folder in my user/.config folder.

```json
//# Your configuration here
```

**Comment by sleepyhollo** [comment]
This is a vim-test bug. sorry for creating it here

**Comment by snowman** [comment]
why this issue has not title
