### ISSUE TITLE
[Feature]  Add a special hash case to use sha512 checksum in latest.yml file generated by electron

### ISSUE THREAD

**Issue by AkariiinMKII** [ScoopInstaller/Scoop#5579]
#### Is your feature request related to a problem? Please describe.

In many repositories, the `latest.yaml` file uploaded with electron apps contains encrypted sha512 value, I wonder if we could add a special hash case to decrypt and use it in hash field

#### Describe the solution you'd like

Here I found the code to [encrypt](https://github.com/electron-userland/electron-builder/issues/3119#issuecomment-1105400203) and [decrypt](https://github.com/electron-userland/electron-builder/issues/3913#issuecomment-1018263468) and verified on my machine.

Here is a example https://github.com/lnelab/lne_link/releases/tag/v2.1.1
```
akariiin@akariiin:~$ shasum -a 512 LINK.Setup.2.1.1.exe
4e077b02b8f5ea810670636cf9f71b6f2ef5931f09e4d78efec3c3cd0cffc005f9bc2105b2c949978f3e5e3d7c3c645cc5e8088baa2976aa4f19785b1ddefbc0  LINK.Setup.2.1.1.exe

akariiin@akariiin:~$ grep sha512 latest.yml
    sha512: Tgd7Arj16oEGcGNs+fcbby71kx8J5NeO/sPDzQz/wAX5vCEFsslJl48+Xj18PGRcxegIi6opdqpPGXhbHd77wA==
sha512: Tgd7Arj16oEGcGNs+fcbby71kx8J5NeO/sPDzQz/wAX5vCEFsslJl48+Xj18PGRcxegIi6opdqpPGXhbHd77wA==

akariiin@akariiin:~$ shasum -a 512 LINK.Setup.2.1.1.exe | cut -f1 -d\\ | xxd -r -p | base64
Tgd7Arj16oEGcGNs+fcbby71kx8J5NeO/sPDzQz/wAX5vCEFsslJl48+Xj18PGRcxegIi6opdqpPGXhbHd77wA==

akariiin@akariiin:~$ grep sha512 latest.yml | tail -n 1 | cut -d " " -f 2 | base64 -d |  hexdump -ve '1/1 "%.2x"'
4e077b02b8f5ea810670636cf9f71b6f2ef5931f09e4d78efec3c3cd0cffc005f9bc2105b2c949978f3e5e3d7c3c645cc5e8088baa2976aa4f19785b1ddefbc0%   
```
(Decrypt results came with an additional `%`)

**Comment by r15ch13** [comment]
This is already implemented. :smile:

Use it like this:
```json
    "autoupdate": {
        "url": "https://github.com/balena-io/etcher/releases/download/v$version/balenaEtcher-Setup-$version.exe#/dl.7z",
        "hash": {
            "url": "$baseurl/latest.yml",
            "regex": "sha512: $base64"
        }
    }
```

[More examples from extras bucket](https://github.com/search?q=repo%3AScoopInstaller%2FExtras+latest.yml+path%3A%2F%5Ebucket%5C%2F%2F&type=code)

**Comment by AkariiinMKII** [comment]
> This is already implemented. 😄 https://github.com/ScoopInstaller/Scoop/blob/f93028001fbe5c78cc41f59e3814d2ac8e595724/lib/autoupdate.ps1#L58C1-L68C6
> 
> Use it like this:
> 
> ```json
>     "autoupdate": {
>         "url": "https://github.com/balena-io/etcher/releases/download/v$version/balenaEtcher-Setup-$version.exe#/dl.7z",
>         "hash": {
>             "url": "$baseurl/latest.yml",
>             "regex": "sha512: $base64"
>         }
>     }
> ```
> 
> [More examples from extras bucket](https://github.com/search?q=repo%3AScoopInstaller%2FExtras+latest.yml+path%3A%2F%5Ebucket%5C%2F%2F&type=code)

Many thanks ^^
