### ISSUE TITLE
[Feature] Update the documentation

### ISSUE THREAD

**Issue by walpox** [ScoopInstaller/Scoop#5581]
## Feature Request

I am not sure whether updating the documentation is a feature request, a bug fix, a mix of both, or something else, so apologies in advance if the category of this issue is incorrect.

I have reviewed the [README.md](https://github.com/ScoopInstaller/Scoop/blob/master/README.md) file and made some changes such as:

- General changes to style to make the text more formal and concise.
- Fixed any typos I have encountered.
- Refactored the code blocks.
- Changed the links in the `Inspiration` section to those projects' homepages (as defined in their git repositories).
- Replaced the reference to the Scoop Directory service. It now points to ScoopSearch because the Scoop Directory page states it is deprecated.
- Refactored the HTML blocks and attempted to replace the deprecated 'align' attribute. However, it seems GitHub does not work well when centering HTML elements using the 'style' attribute instead.

Those changes are available on my fork here:
https://github.com/ScoopInstaller/Scoop/compare/master...walpox:Scoop:documentation

After your review, it can be decided whether or not to create the corresponding pull request.

Note:
In the PowerShell code block to install Scoop, I am not sure if the two comment lines should reside there or outside, would appreciate your feedback. Copy-pasting does not seem to be an issue, as the comments are ignored by the PowerShell terminal.

**Comment by walpox** [comment]
I have also added explicitly the HTTPS protocol in the "Invoke-RestMethod" cmdlet for security reasons. Otherwise, it uses HTTP implicitly to download the Scoop installation script.

**Comment by rashil2000** [comment]
Hi, could you please raise a PR? (targeting the `develop` branch)

**Comment by walpox** [comment]
> Hi, could you please raise a PR? (targeting the `develop` branch)

Consider it done: #5638.

**Comment by rashil2000** [comment]
Merged in #5638
