### ISSUE TITLE
[Bug] Uninstalling fails if wildcard character is used

### ISSUE THREAD

**Issue by kazum1kun** [ScoopInstaller/Scoop#5585]
#### Current Behavior

When uninstalling apps, if a wildcard character is used to match the app, the uninstallation would fail.

#### Expected Behavior

The uninstallation should proceed normally

#### Additional context/output

**This is the current behavior**
```
~ ❯ scoop uninstall bulk*
Uninstalling 'bulk*' (3.4.4.0).
Removing shortcut ~\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Scoop Apps\Bulk Rename Utility.lnk
Unlinking ~\scoop\apps\bulk*\current
Remove-Item: C:\Users\Kazuma\scoop\apps\scoop\current\lib\install.ps1:930
Line |
 930 |          Remove-Item $currentdir -Recurse -Force -ErrorAction Stop
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot remove item C:\Users\Kazuma\scoop\apps\bulk-rename-utility\current: Access to the path
     | 'C:\Users\Kazuma\scoop\apps\bulk-rename-utility\current' is denied.

~ ❯ scoop uninstall bulk-rename-utility
Uninstalling 'bulk-rename-utility' (3.4.4.0).
Removing shortcut ~\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Scoop Apps\Bulk Rename Utility.lnk
Unlinking ~\scoop\apps\bulk-rename-utility\current
'bulk-rename-utility' was uninstalled.
```

I tried to uninstall with admin rights (with the asterisk) and the same error follows. If I supply the full name the uninstallation proceeds normally (without admin rights).

#### Possible Solution

Perhaps check if the matched name is passed into the directory instead of the original query?

### System details

**Windows version:** [e.g. 7, 8, 10, 11] 11

**OS architecture:** [e.g. 32bit, 64bit, arm64] 64bit

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`] 7.3.5

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
{
  "last_update": "2023-07-22T18:06:49.8653668+08:00",
  "aria2-warning-enabled": false,
  "aria2-enabled": true,
  "scoop_branch": "master",
  "scoop_repo": "https://github.com/ScoopInstaller/Scoop"
}
```

**Comment by HUMORCE** [comment]
This feature does not exist. Uninstalling apps with wildcards is a dangerous operation.

alternative:
```
scoop alias add rm 'param($keyword)
foreach ($app in (scoop list)) { if ($app.Name -like "$keyword") { scoop uninstall $app.Name } }'
```

scoop rm key*
scoop rm *key
scoop rm \*key\*
scoop rm \*key1\*key2
...

**Comment by kazum1kun** [comment]
Gotcha, I will close this issue then.
