### ISSUE TITLE
[Feature] Better description for updating scoop error

### ISSUE THREAD

**Issue by doraeric** [ScoopInstaller/Scoop#5589]
#### Is your feature request related to a problem? Please describe.

It's not a real problem. Just an advice for better description for error handling.

#### Describe the solution you'd like

Currently, the [code](https://github.com/ScoopInstaller/Scoop/blob/f93028001f/libexec/scoop-update.ps1#L88) shows
```
Scoop update failed. Folder in use. Paste $newdir into $currentdir.
```
Since `.git` is a hidden folder, the user may copy contents except `.git` from old folder to new folder, resulting `.git` is still missing.
I think tell the user to rename folder would be a better choice.

#### Describe alternatives you've considered

Ask to user to rename folders may be a better choice, such as
```
Scoop update failed. Folder in use. Please rename folders $currentdir to `old` and $newdir to `current` manually.
```

**Comment by HUMORCE** [comment]
Basically, we just need to execute `scoop update` again when Scoop Core Dir are not  occupied.

**Comment by doraeric** [comment]
The problem is that the directory is occupied by scoop when running `scoop update`, so it needs to be fix by the user.
And if a user didn't copy the **hidden** `.git` folder from $newdir to old directory, he needs to copy everything from new directory every time.

**Comment by HUMORCE** [comment]
Scoop Core Dir will not be occupied when executing `scoop update`, unless you have opened it or it's sub-files in another program. e.g. A terminal cd to the dir

Of course, your change request for this instruction is correct, because the `.git` dir may not included when copying.
