### ISSUE TITLE
[Bug] Making a single file persistent creates directory symlink

### ISSUE THREAD

**Issue by LucasOe** [ScoopInstaller/Scoop#5591]
#### Current Behavior
When I try to make a single config file persistent, scoop creates a persistent symbolic link to a directory with the name of that file, instead of making said file persistent. For example, [this](https://github.com/LucasOe/scoop-lucasoe/blob/master/bucket/sfp.json) scoop app should make the file `SFP.config` persistent. The result of the installation looks like this, which breaks the app:

![image](https://github.com/ScoopInstaller/Scoop/assets/16548335/a89cae29-66ec-4e7f-a8fb-be65b7eda99d)

#### Expected Behavior
The system link that gets creates should be a file and not a directory.

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** 7.3.6

**Additional software:** Tested using pwsh v7.3.6 using ConEmu.

#### Scoop Configuration
```json
{
  "use_lessmsi": true,
  "last_update": "2023-07-26T17:25:23.5992526+02:00",
  "scoop_branch": "master",
  "scoop_repo": "https://github.com/ScoopInstaller/Scoop"
}
```

**Comment by r15ch13** [comment]
The `pre_install` script should create the config file.
Please uninstall it and remove the `SFP.config` directory from the persistent directory. (`%USERPROFILE%\scoop\persist\sfp\SFP.config`)
Then try installing it again.

**Comment by LucasOe** [comment]
Indeed, I was using an old copy of the app manifest without the `pre_install` script. Adding it fixes the problem, thanks!
