### ISSUE TITLE
[Feature] Installing PowerShell modules globally

### ISSUE THREAD

**Issue by gerardog** [ScoopInstaller/Scoop#5601]
#### Is your feature request related to a problem? Please describe.
Scoop currently does not support installing PowerShell modules globally. 

It throws the following error: `Installing PowerShell modules globally is not implemented!`
![image](https://github.com/ScoopInstaller/Scoop/assets/3901474/76f45b1c-f6e1-4bad-8693-b6ca0248118e)
 
Fixes: ScoopInstaller/Main#4989 & #5597 

#### Describe the solution you'd like
However, doing so may not be so hard:
- Installing a PS Module for the current user is [done by creating a directory junction](https://github.com/ScoopInstaller/Scoop/blob/f93028001fbe5c78cc41f59e3814d2ac8e595724/lib/psmodules.ps1#L29) from `$scoopdir\modules\$module_name` to the module location (in my case `~\scoop\apps\{app}\current`)
- Installing it globally can be done by linking `$env:ProgramFiles\WindowsPowerShell\Modules\$module_name` to the module location.
-

**Comment by Lutra-Fs** [comment]
Maybe #4135 could help?

**Comment by gerardog** [comment]
Implemented by ScoopInstaller/Scoop#5611
