### ISSUE TITLE
[Feature] Disable Icon Creation in Start Menu

### ISSUE THREAD

**Issue by SinaMobasheri** [ScoopInstaller/Scoop#5602]
## Feature Request
The ability to disable icon creation in the start menu is a reasonable option to have, basically, I use Scoop only for command line programs and never use GUI versions of programs like 7-Zip or DjView but I understand that many people do, so it would be helpful to have the option for removing it, also removing it manually is not a proper solution, cause maybe it will be recreated while installing other programs. but why? Because I mostly don't like to populate my start menu and I want to Scoop's affect zone remains inside the Scoop folder.

Hope it's reasonable and not an ocd 😄

**Comment by HUMORCE** [comment]
An artificial demand. If you don't use GUI programs, then why would you open the start menu?

Shortcuts allows Windows Search or 3rd party launcher(e.g. PowerToys Run, Wox, Keypirinha, Alfred, etc.) to index program faster and more accurately.

For advanced users, they don't open programs by clicking shortcut on start menu, instead, beginners need them.

Additionally, Scoop cannot completely disable shortcut creation, some shortcuts created by installer itself if the program are not full-portable.
