### ISSUE TITLE
Accidentally deleted an older version of something I have installed now scoop cleanup produces an error

### ISSUE THREAD

**Issue by Kamek437** [ScoopInstaller/Scoop#5610]
I know this isn't the right place for this but couldn't find a better place to ask.
So I'm on Windows 11 first off. I was trying to clear space with wizztree and accidentally deleted an older version of an app I installed with Scoop. Now when I run scoop cleanup I get this (running in an admin powershell) :
```
Removing sublime-text: 4-4143
Remove-Item: C:\Users\kamek\scoop\apps\scoop\current\libexec\scoop-cleanup.ps1:50
Line |
  50 |          Remove-Item $dir -ErrorAction Stop -Recurse -Force
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot remove item C:\Users\kamek\scoop\apps\sublime-text\4-4143\Data: Access to the path
     | 'C:\Users\kamek\scoop\apps\sublime-text\4-4143\Data' is denied.
```
I deleted that directory accidentally that's why it can't access it. I can't restore the files and I didn't know where to ask this. What can I do? Was thinking maybe I could reset the list of apps installed and cached versions or something? Has anyone else had an issue like this?

**Comment by Kamek437** [comment]
I figured it out, sorry my bad.

**Comment by MellowPhi** [comment]
@Kamek437 How did you fix this? I have a similar error when I try and run
`scoop cleanup --cache --all`

```
Removing ccleaner: 6.25.11131Remove-Item: C:\Users\John\scoop\apps\scoop\current\libexec\scoop-cleanup.ps1:50
Line |
  50 |          Remove-Item $dir -ErrorAction Stop -Recurse -Force
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Access to the path 'C:\Users\John\scoop\apps\ccleaner\6.25.11131\lc.dat' is denied.
```

**Comment by Kamek437** [comment]
Honestly, I don't remember. I reinstalled a lot of stuff, then I made sure the the permissions for that whole directory were right. I don't know if taking ownership of the directory did it, or reinstalling did it but it went away.
