### ISSUE TITLE
[Feature] Improved local `scoop search`

### ISSUE THREAD

**Issue by mathijshenquet** [ScoopInstaller/Scoop#5615]
## Feature Request

Currently `scoop search` is very slow and therefore not very useful. IIRC it does a linear search through all installed buckets and all included manifests looking for packages with a matching name or matcing binary. This is slow because all those, sometimes large, manifest files have to be opened one by one. The feature request is that local search on package name and binaries is fast enough to be useful.

#### Describe the solution you'd like

I propose that for each bucket a search index of the containing packages is maintained containing only the search relevant information. I.e. it contains the name and binaries of every package. Then search is done on this index. This has feature partity with the currenty search but is much quicker as these search index files are much smaller to read in. I already have a prototype of this implemented.

**Comment by mathijshenquet** [comment]
Here is the implemented prototype on a rather old branch:
 https://github.com/mathijshenquet/Scoop/blob/better-search/libexec/scoop-search.ps1

I will rebase and improve it once this issue is accepted.

**Comment by HUMORCE** [comment]
Indexing locally does not improve the user experience. because the index should be triggered when every commits, and Scoop buckets use rolling updates.

It's pointless if it need updated manually. If possible, indexing should be performed after buckets updated instead manually operation or before search.

---

Can you provide a performance comparison and the time it takes to creates the index?

**Comment by mathijshenquet** [comment]
Yeah I agree the cache should be invalidated on bucket update, this should be an easy extension.

I have updated the code to more closely resemble master and ran some testing. Here are the results

`master` branch:

```Powershell
# master branch
~ > Measure-Command { scoop search haskell } | Select-Object -Property TotalSeconds
Results from local buckets...

TotalSeconds
------------
       19,85
```

`better-search` branch:

```Powershell
~ > Measure-Command { scoop search haskell } | Select-Object -Property TotalSeconds

TotalSeconds
------------
        0,44

~ > Measure-Command { scoop search haskell -RebuildCache } | Select-Object -Property TotalSeconds

TotalSeconds
------------
        7,90
```

As you can see once the cache is built it is 2 orders of magnitude faster than the existing search. Curiously enough even building the cache seems to be faster. I'm not sure what is the cause of this but I will investigate the phenomena once this issue is accepted.

**Comment by mathijshenquet** [comment]
It looks like the reason that building the cache is faster is that the `Get-LocalBucket` or the `apps_in_bucket` cmdlets used to be faster in the past.

**Comment by mathijshenquet** [comment]
I narrowed down the regression in search times to the cmdlet `manifest_path` in `manifest.ps1`. With the current version

```
function manifest_path($app, $bucket) {
    (Get-ChildItem (Find-BucketDirectory $bucket) -Filter "$(sanitary_path $app).json" -Recurse).FullName
}
```

I get the 20 second search times but with the previous

```
function manifest_path($app, $bucket) {
    fullpath "$(Find-BucketDirectory $bucket)\$(sanitary_path $app).json"
}
```

It goes down to 8 seconds.

It seems like the nev ersion is searching for a file in all subdirectories. Is this really necessary? Don't all manifests have to be always located in `bucket/` subdirectory?

**Comment by mathijshenquet** [comment]
I have rebased the changes onto master here: https://github.com/ScoopInstaller/Scoop/compare/master...mathijshenquet:better-search-rebased. I also simplified the cache building code which now make the rebuild take 5s on my system. Thus on this branch a search with cached index takes 0.5 seconds, with a index rebuild it takes 5s, while a search on master takes 20s.

**Comment by mbalc** [comment]
as an alternative, wouldn't it be possible for you to somehow expose an api from whatever is being used in the https://scoop.sh search bar, and just connect to that instead?

**Comment by r15ch13** [comment]
Could you try https://github.com/ScoopInstaller/Scoop/pull/5324 and see if this works for you? The first search is still a bit slow, but after the filesystem cache warmed up every search takes 1-2 secs.

**Comment by rashil2000** [comment]
Hi all! The tracking issue for search perfomance is https://github.com/ScoopInstaller/Scoop/issues/4239. Please continue the discussion on that thread. 

Thanks!
