### ISSUE TITLE
[Feature] Automatically close open instances of app on uninstall/update

### ISSUE THREAD

**Issue by leumasme** [ScoopInstaller/Scoop#5617]
#### Is your feature request related to a problem? Please describe.

When updating apps via scoop, I often encounter the error
`ERROR The following instances of "___" are still running. Close them and try again.`
Nanually closing the applications each time is quite a hassle since I have a lot of scoop apps installed that are always running in the background (`powertoys`, `flow-launcher`, `deno` and `nodejs` as vscode background services, `telegram`, `trafficmonitor`, etc)

#### Describe the solution you'd like
Command line switch to enable automatic stopping of the processes that block the update/uninstall.  
This is already manually implemented by the `extras/everything` (& `versions/everything-[alpha/beta]`) manifest `pre_uninstall` script, for example, since `everything` is usually always running in the background
https://github.com/ScoopInstaller/Extras/blob/390271a6503acc2d8e63abf009cf4eca3d981cfe/bucket/everything.json#L46

#### Describe alternatives you've considered
Manually stopping the processes via task manager or cli is an option of course, but it makes the scoop update experience less nice than just running a command and waiting.  
Scoop already taunts the user with the information of which processes/PIDs exactly are blocking the action.

**Comment by nahid6970** [comment]
did u found  any solution? its so annoying to close the apps manually and then update and then start the app. 😟

**Comment by rashil2000** [comment]
Please check https://github.com/ScoopInstaller/Scoop/pull/4713#issuecomment-1033365448
