### ISSUE TITLE
[Feature] Persist non-existing files as files, not dirs

### ISSUE THREAD

**Issue by eugenesvk** [ScoopInstaller/Scoop#5621]
#### Is your feature request related to a problem? Please describe.
Non-existing (at install time) files can't be persisted as Scoop instead creates a folders

Think this is similar to https://github.com/ScoopInstaller/Scoop/issues/2394, but there the files existed so the issue was avoided

#### Describe the solution you'd like

A way to signal that an item is a file that should be persisted, not a directory, so then Scoop on install would create these files as empty in the persist directory and create links to them

#### Describe alternatives you've considered
Creating the links manually

**Comment by HUMORCE** [comment]
Creates file(s in `pre_install` stage, then persist it.

```
pre_install:
new-item $dir\settings -itemtype file
set-content -path $dir\config.ini -value 'auto_update=false' -encoding ascii

persist: [settings, config.ini]
```
