### ISSUE TITLE
[Feature] Add a way to self-sign scoop

### ISSUE THREAD

**Issue by D4RKW1NT3R** [ScoopInstaller/Scoop#5623]
#### Is your feature request related to a problem? Please describe.

I have an issue running scoop when script execution in powershell is set to all-signed. Scoop isn't able to run at all.
#### Describe the solution you'd like

One solution to this is doing something like this: https://stackoverflow.com/questions/84847/how-do-i-create-a-self-signed-certificate-for-code-signing-on-windows which entails making a self-signed certificate in windows, then signing the script (i.e scoop and any apps that need it) This can be fully automated or partly.
#### Describe alternatives you've considered

Making a seperate scoop install that does this for you since scoop is meant to not require you to have admin priveledges and to be portable and doing this would defeat that purpose therefore, seperate install. I was able to do this awhile back using a different link I found on the internet however I lost that link and I'm way too tired to find it currently, I will update the request if I find the link. (moral of the story, it can be done and after making the certificate you won't need to be admin anymore to sign scripts if I remember correctly.)

**Comment by rashil2000** [comment]
This has been discussed before: https://github.com/ScoopInstaller/Scoop/issues?q=is%3Aissue+signing+is%3Aclosed, and it was deemed it's not feasible with the current arrangement of the codebase.
