### ISSUE TITLE
[Feature] Easily machine-parseable output for `scoop search`, among other commands

### ISSUE THREAD

**Issue by TechStudent10** [ScoopInstaller/Scoop#5629]
#### Is your feature request related to a problem? Please describe.

I want to build a program that utilizes Scoop, more specifically `scoop search`. `scoop search` however isn't as machine-parseable as say, `choco search -r` where the `-r` flag means to "limit output to only essential information" a.k.a the package name and version.

#### Describe the solution you'd like

I would like something similar to `choco search -r` so I may easily do so. I searched around in issues and couldn't find anything. The help command for `scoop search` also doesn't have antyhing relating to this feature.

#### Describe alternatives you've considered

Obviously working through and parsing the commands the way they are.

**Comment by rashil2000** [comment]
The output of `scoop search` is a rich PSObject - which can be converted into any data exchange format like JSON, CSV, XML etc - easily parseable by machines. Example: 

`scoop search | ConvertTo-JSON`

**Comment by TechStudent10** [comment]
> The output of `scoop search` is a rich PSObject - which can be converted into any data exchange format like JSON, CSV, XML etc - easily parseable by machines. Example:
> 
> `scoop search | ConvertTo-JSON`

Is there a way to do this without Powershell?
