### ISSUE TITLE
[Feature] Update only relevant buckets to speed up installs/updates

### ISSUE THREAD

**Issue by Pyroglyph** [ScoopInstaller/Scoop#5635]
#### Is your feature request related to a problem? Please describe.

I have 7 buckets enabled. When I run `scoop install <whatever>` Scoop insists on updating every single bucket beforehand, which is rather slow and a bit wasteful. The same occurs when running `scoop update *`, even if there is only one package to update every bucket is still refreshed.

#### Describe the solution you'd like

To make installs/updates faster for users with many buckets, I think Scoop should check the user's local buckets for each requested package and then only update the buckets where those packages were found. If they were not found in any bucket, then fall back to the existing behaviour.

Here is some handy pseudocode:
```
if package name already exists in a bucket
    update that bucket only
else
    update all buckets (normal behaviour)
```

The only drawback I can think of is if a package was removed from one bucket and added to another with the same name. I'm not sure how often this happens but I think it's unlikely. In any case, with the solution I proposed the user merely has to run the command again to get the new package as the bucket where the package used to be would already be updated to remove it, causing Scoop to refresh them all anyway.

#### Describe alternatives you've considered

I have considered being more patient, but I like things to be fast :)

**Comment by rashil2000** [comment]
> I have 7 buckets enabled. When I run scoop install <whatever> Scoop insists on updating every single bucket beforehand, which is rather slow and a bit wasteful. 

This does not happen every time. Buckets are updated if they have been outdated for more than 3 hours. Scoop follows the rolling release model of updates - it insists on being as up to date as possible, by design.

Manifests, which contain upstream URLs, change very frequently, so the 3 hour window is present to prevent any mismatches that might occur in locally stored manifests vs. the remotely stored manifests.
