### ISSUE TITLE
[Bug]  (mirror.cyberbits.asia:443)

### ISSUE THREAD

**Issue by nahid6970** [ScoopInstaller/Scoop#5636]
❯ scoop update *
libreoffice: 7.6.1.1 -> 7.6.1.2
ruffle-nightly: 2023-09-07 -> 2023-09-08
Updating 2 outdated apps:
Updating 'libreoffice' (7.6.1.1 -> 7.6.1.2)
Downloading new version
OperationStopped: C:\Users\nahid\scoop\apps\scoop\current\lib\install.ps1:111
Line |
 111 |          throw $e
     |          ~~~~~~~~
     | No such host is known. (mirror.cyberbits.asia:443)

**Comment by rashil2000** [comment]
Please check your internet connection and see if the link https://downloadarchive.documentfoundation.org/libreoffice/old/7.6.1.2/win/x86_64/LibreOffice_7.6.1.2_Win_x86-64.msi is reachable.
