### ISSUE TITLE
Can't install Scoop [Bug] 

### ISSUE THREAD

**Issue by muffinV136** [ScoopInstaller/Scoop#5643]
I don't necessarily know how to explain this so I dropped a screenshot.

![screenshot](https://github.com/ScoopInstaller/Scoop/assets/66855676/f4917a07-af44-4db8-9022-85c195e3ce75)

**Windows version:**
Windows 10
**OS architecture:**
64bit
**PowerShell version:**
5.1.19041.3031

**Comment by r15ch13** [comment]
Seems there is a web filter running, which prevents you from accessing Github.com through PowerShell (https://www.securly.com)

**Comment by muffinV136** [comment]
i see now, thanks.
