### ISSUE TITLE
Scoop update removes settings for programs

### ISSUE THREAD

**Issue by guntern** [ScoopInstaller/Scoop#5652]
#### Current Behavior
I ran `scoop update *`, which updated e.g. Windows Terminal and Flow Launcher. Unfortunately, for both of these programs, the settings were not retained. Both started with standard settings the next time.

#### Expected Behavior
After updating, the old settings should still be used

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** 7.3.0

#### Scoop Configuration

```json
{
  "last_update": "2023-09-15T15:27:28.1021408+02:00",
  "scoop_branch": "master",
  "scoop_repo": "https://github.com/ScoopInstaller/Scoop"
}
```

I post this here rather in the bucket, because as two programs are affected the same way, it seems to be a more general issue rather than specific to the programs themself.

The settings are saved in `~\scoop\persist\...`, though.

**Comment by rashil2000** [comment]
Windows Terminal was recently modified (https://github.com/ScoopInstaller/Extras/pull/11335) to use the portable distribution. See the notes at https://github.com/ScoopInstaller/Extras/blob/master/bucket/windows-terminal.json#L30

Flow Launcher is also supposed to persist settings - see https://github.com/ScoopInstaller/Extras/blob/master/bucket/flow-launcher.json#L32. Can you manually check these locations?

**Comment by guntern** [comment]
Thanks @rashil2000 for pointing these out. Apparently I overlooked the warning message when upgrading Windows Terminal. There were several updates so I missed that one.

For FlowLauncher there seems to be no real explanation. I checked persistant settings and both WIndows Terminal and Flow Launcher have saved it there. So in theory it should work. I will keep my eyes open the next time.

**Comment by rashil2000** [comment]
No worries!
