### ISSUE TITLE
[Feature] Switching manifest

### ISSUE THREAD

**Issue by lwfld** [ScoopInstaller/Scoop#5656]
#### Is your feature request related to a problem? Please describe.

First I installed an application A from a third-party bucket, because I cannot find it from the official buckets.
But after a while the official bucket collected A(this application) and then the third party bucket removed its manifest, now I cannot update it again! And instead I have to reinstall it again? Any better solution to it?

#### Describe the solution you'd like

An option during update process, like `scoop update A -r [scoop bucket name or bucket link]`

#### Describe alternatives you've considered

Or another command to directly switch the manifest of an application?

**Comment by rashil2000** [comment]
You can modify the source bucket of the app by manually changing it in the ~\scoop\apps\<app-name>\current\install.json file.
