### ISSUE TITLE
[Feature]  Identify app by the bucket's url, not bucket's name

### ISSUE THREAD

**Issue by kaipol** [ScoopInstaller/Scoop#5659]
## Feature Request 
Indetify app source by bucket's url instead of bucket's name

#### Is your feature request related to a problem? Please describe.
 I changed the name of a bucket (because the origin name is too long) .But when I checked for updates, I can't find the latest app I installed from that  bucket though the latest version of the app is already available. Until I found that the name of that app source was still the origin name,so I changed the bucket name in `install.json` and finally I can update the app.

#### Describe your solution you'd like 
add the bucket's url into `install.json`, maybe a solution?

**Comment by rashil2000** [comment]
As a convention, to distinguish between different app sources, `install.json` follows these rules:
- bucket name is used for apps installed via the standard way. These apps have the ability to get updated via `scoop update`.
- URL is used for one-off apps installed via the `scoop install <remote-url>` command. These apps cannot be updated.
- file path is also used for one-off apps installed from the local filesystem. These apps also can't be updated.
