### ISSUE TITLE
[Bug] getopt.ps1 splits literal strings and full file paths into multiple strings

### ISSUE THREAD

**Issue by BinToss** [ScoopInstaller/Scoop#5688]
Linked Issues: #5313, #5326

#### Current Behavior

https://github.com/ScoopInstaller/Scoop/blob/f93028001fbe5c78cc41f59e3814d2ac8e595724/libexec/scoop-shim.ps1#L49
https://github.com/ScoopInstaller/Scoop/blob/f93028001fbe5c78cc41f59e3814d2ac8e595724/lib/getopt.ps1#L28

When a quoted string is present in `$Args`, it is treated as one string. get-opt.ps1 does not check for quoted strings and will split them if they contain spaces.

#### Expected Behavior

A path containing spaces should not be split if it is enclosed with single- or double-quotes.

test with...
```pwsh
scoop shim add edge 'C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe' '--' --global
```

#### Additional context/output
![image](https://github.com/ScoopInstaller/Scoop/assets/7243190/6cf8ba91-a886-4864-a777-6d30bd16ba6e)

#### Possible Solution

Splitting arguments by spaces is redundant. The `$Args` variable is an array of strings which have already been split by whitespace. Doing so again is redundant and can lead to issues like this one.
I recommend requiring users to enclose an arguments in in quotes if it must contain whitespace.

### System details

|    |    |
| -- | -- |
| Windows version | 11 |
| OS architecture | 64bit |
| PowerShell version | 7.3.7 |

#### Scoop Configuration

```json
{
  "last_update": "2023-10-11T02:06:48.3814390-07:00",
  "alias": {
    "upgrade": "scoop-upgrade"
  },
  "scoop_repo": "https://github.com/ScoopInstaller/Scoop",
  "scoop_branch": "master"
}

```

**Comment by hagaigold** [comment]
look like #5313 / #5326

**Comment by BinToss** [comment]
Ah, yes. It is a duplicate. I wonder why I those didn't turn up when I searched for existing issues...

Close this as Duplicate?

**Comment by hagaigold** [comment]
> Ah, yes. It is a duplicate. I wonder why I those didn't turn up when I searched for existing issues...
> 

you can switch to the `develop` branch, if you don't mind using the not released version.
