### ISSUE TITLE
[Bug] When I install Chormium usign -G it's still only possible to set it as default for HKCU

### ISSUE THREAD

**Issue by ne0YT** [ScoopInstaller/Scoop#5691]
#### Current Behavior
I can only set the chroimium browser which  installed using -g for my current user which installed it.

#### Expected Behavior
Tools instalkled using the option -G should be configurabel as standard-Apps for all users on my System.

#### Additional context/output
It is very important to me to have an updateable chromium browser on my RDS Setup.

#### Possible Solution
make -G (global) apps registered in a way that they can be set as default for all users.

### System details

**Windows version:**
2022 standard

**OS architecture:**
64bit

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]
5.1.20348.1366

**Additional software:** [(optional) e.g. ConEmu, Git]
I only installed chromium, git and 7zip usign scoop.

**Comment by rashil2000** [comment]
> make -G (global) apps registered in a way that they can be set as default for all users.

Scoop does not register applications. You can either manually do it, or the system will do it when you open Chromium for the first time.

**Comment by ne0YT** [comment]
@rashil2000 I think you missed the point.
I writ ethat I am actually registering the app, but it only works per user, only HKCU not HKCM. If you install chrome normally you can set it as standard in HKCM
