### ISSUE TITLE
My system is a 64-bit version. The architecture includes 64bit, 32bit, and arm64. When I executed install, the arm64 version was installed for me. The correct version should be 64bit

### ISSUE THREAD

**Issue by tianlongJ** [ScoopInstaller/Scoop#5705]
My system is a 64-bit version. The architecture includes 64bit, 32bit, and arm64. When I executed install, the arm64 version was installed for me. The correct version should be 64bit

**Comment by Aldo-f** [comment]
Can you provide some commands to reproduce this problem? 
Like this:
``` 
scoop install the-specific-app or-apps
```

So you mean that this code is probably giving a wrong result?
```
function Get-DefaultArchitecture {
    $arch = get_config DEFAULT_ARCHITECTURE
    $system = if (${env:ProgramFiles(Arm)}) {
        'arm64'
    } elseif ([System.Environment]::Is64BitOperatingSystem) {
        '64bit'
    } else {
        '32bit'
    }
    if ($null -eq $arch) {
        $arch = $system
    } else {
        try {
            $arch = Format-ArchitectureString $arch
        } catch {
            warn 'Invalid default architecture configured. Determining default system architecture'
            $arch = $system
        }
    }
    return $arch
}
```

Based on [this StackOverflow](https://stackoverflow.com/questions/74402454/what-is-each-program-files-folder-purpose-in-arm64-architecture), the directory `Program Files (Arm)` would only be needed for arm32 versions, not arm64.

**Comment by tianlongJ** [comment]
> Can you provide some commands to reproduce this problem? Like this:
> 
> ```
> scoop install the-specific-app or-apps
> ```
> 
> So you mean that this code is probably giving a wrong result?
> 
> ```
> function Get-DefaultArchitecture {
>     $arch = get_config DEFAULT_ARCHITECTURE
>     $system = if (${env:ProgramFiles(Arm)}) {
>         'arm64'
>     } elseif ([System.Environment]::Is64BitOperatingSystem) {
>         '64bit'
>     } else {
>         '32bit'
>     }
>     if ($null -eq $arch) {
>         $arch = $system
>     } else {
>         try {
>             $arch = Format-ArchitectureString $arch
>         } catch {
>             warn 'Invalid default architecture configured. Determining default system architecture'
>             $arch = $system
>         }
>     }
>     return $arch
> }
> ```
> 
> Based on [this StackOverflow](https://stackoverflow.com/questions/74402454/what-is-each-program-files-folder-purpose-in-arm64-architecture), the directory would only be needed for arm32 versions, not arm64.`Program Files (Arm)`

https://github.com/ScoopInstaller/Scoop/issues/5582
I found the solution in this issue, I closed this issue, I cloned the project and fixed it myself
