### ISSUE TITLE
[Bug] fatal: unable to access 'https://github.com/ScoopInstaller/Scoop/': Failed to connect to 127.0.0.1 port 7890 after 2056 ms: Couldn't connect to server

### ISSUE THREAD

**Issue by Outis9** [ScoopInstaller/Scoop#5713]
## Bug Report

 **fatal: unable to access 'https://github.com/ScoopInstaller/Scoop/': Failed to connect to 127.0.0.1 port 7890 after 2056 ms: Couldn't connect to server**

#### Current Behavior

When l execute "scoop update", the error occurred.
1. l have closed clash-for-windows which sets a proxy on 127.0.0.1:7890. And no other proxies are working.
2. The system proxy is off.
3. l have tried to reboot.
4. l have executed "scoop config rm proxy" to remove proxy settings in the configuration file.

But I still have this error.

When I turn on the clash-for-windows again which sets a proxy on 127.0.0.1:7890, this error disappears. But l no longer want to use this proxy.
#### Expected Behavior

l can change the proxy or remove the proxy.

### System details

**Windows version:** 11 pro 22h2

**OS architecture:** 64bit

**PowerShell version:** 7.3.9

#### Scoop Configuration

```json
{
  "root_path": "******",
  "global_path": "*********",
  "last_update": "2023-11-03T17:02:20.6037735+08:00",
  "aria2-warning-enabled": true,
  "aria2-enabled": true,
  "alias": {},
  "scoop_branch": "master",
  "scoop_repo": "https://github.com/ScoopInstaller/Scoop"
}
```

**Comment by r15ch13** [comment]
Can you try running `git pull` from `C:\Users\<user>\scoop\buckets\main`?
Also does `git config --list` output something about the proxy settings? (run command from the bucket directory like above)
What is the output of `$env:HTTPS_PROXY` or `$env:HTTP_PROXY`?

**Comment by Outis9** [comment]
> Can you try running `git pull` from `C:\Users\<user>\scoop\buckets\main`? Also does `git config --list` output something about the proxy settings? (run command from the bucket directory like above) What is the output of `$env:HTTPS_PROXY` or `$env:HTTP_PROXY`?

oh! Thanks a lot! l forgot that l have also set the proxy in the git configuration file,  l now removed it, and the problem is fixed.
