### ISSUE TITLE
cant install adb  Can't shim 'platform-tools\dmtracedump.exe': File doesn't exist. [Bug] 

### ISSUE THREAD

**Issue by nahid6970** [ScoopInstaller/Scoop#5719]
scoop install adb
Installing 'adb' (34.0.5) [64bit] from main bucket
Loading platform-tools_r34.0.5-windows.zip from cache
Checking hash of platform-tools_r34.0.5-windows.zip ... ok.
Extracting platform-tools_r34.0.5-windows.zip ... done.
Linking ~\scoop\apps\adb\current => ~\scoop\apps\adb\34.0.5
Creating shim for 'adb'.
Creating shim for 'dmtracedump'.
Can't shim 'platform-tools\dmtracedump.exe': File doesn't exist.

**Comment by rouvwhqk** [comment]
I have the same problem

**Comment by PrimeDominus** [comment]
Same here

**Comment by BruceKangCN** [comment]
I found that platform-tools_r34.0.5-windows no longer ships `dmtracedump.exe`. I delete the 13th line `"platform-tools\\dmtracedump.exe",` in `scoop/buckets/main/bucket/adb.json` then I can successfully update `adb`.

**Comment by Shuhib1924** [comment]
many thanks, i had a lot of struggle, after i've uninstalled adb, the version 34.0.4 works
`scoop install -g adb@34.0.4`

**Comment by eallion** [comment]
Same

**Comment by Actuallymax** [comment]
Same

**Comment by Leao9203** [comment]
Same

**Comment by noahziheng** [comment]
Same

**Comment by r15ch13** [comment]
Fixed with https://github.com/ScoopInstaller/Main/pull/5247

**Comment by eallion** [comment]
GJ!

**Comment by RedTomatoCat** [comment]
use platform-tools_r34.0.4-windows.zip


https://dl.google.com/android/repository/platform-tools_r34.0.4-windows.zip
