### ISSUE TITLE
[Bug] Symantec Endpoint Protection detects virus Heur.AdvML.D in latest shims

### ISSUE THREAD

**Issue by xxthunder** [ScoopInstaller/Scoop#5730]
#### Current Behavior
Scoop is currently not usable at my company due to (maybe) false positives of Symantec Endpoint Security. Newly created shims are detected as virus. So no apps can be installed/updated.

#### Expected Behavior
Shims shall work on PC's with Simantec Endpoint Protection.

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** default 5.1

**Additional software:** Symantec Endpoint Protection

**Comment by spider2048** [comment]
Were you using the develop branch?
Which applications did you try to install?

**Comment by xxthunder** [comment]
Yes, I am using the develop branch. It actually does not matter, what app I am installing. If scoop install or scoop reset creates a shim, the shim executable is detected as virus. A colleague of mine already sent an exemplary executable to Symantec, I am curios what they say. I created this issue in case somebody else is having the same problem.

**Comment by spider2048** [comment]
It is most likely a false positive, but I would like to have the problematic shim.

**Comment by r15ch13** [comment]
This is related to https://github.com/ScoopInstaller/Scoop/pull/5559 which modifies shims subsystem. The modified shim is reported as a false positive.

**Comment by xxthunder** [comment]
Hi, sorry for my late reply. I installed 7zip, totalcommander and sysinternals. All GUI shims were put into quarantine by our company's SEP installation. A colleague from IT sent an examplary GUI shim together with some information about how they are created to Broadcom. They confirmed the false positive and whitelisted the signature of the current GUI shim. After updating the virus definitions vi life update the problem was gone for me and all my colleagues.
