### ISSUE TITLE
[Feature] scoop status should update buckets

### ISSUE THREAD

**Issue by Skylark13** [ScoopInstaller/Scoop#5743]
#### Is your feature request related to a problem? Please describe.
Doing `scoop status` if any buckets are out of date prints a message saying that you need to perform `scoop update`. However, doing `scoop install <something>` does a `scoop update` prior to installing. 

#### Describe the solution you'd like
I don't see a case where you would NOT want to do a `scoop update` if you want to do a `scoop status`. You want to see if any apps are out of date, of course the bucket info needs to be updated prior to doing that. 

So I think `scoop status` should just update the buckets like `scoop install` does, instead of telling the user to do it. Why require two commands instead of one?

#### Describe alternatives you've considered
`scoop update && scoop status` 😉

**Comment by mattcargile** [comment]
`scoop status` is there to tell you when you need to `scoop update`. I don't think this is necessary.

**Comment by Skylark13** [comment]
No. If you run `scoop status` and your buckets are out of date, it does nothing and tells you to run `scoop update`.

```
> scoop status
WARN  Scoop bucket(s) out of date. Run 'scoop update' to get the latest changes.
> 
```

^^^^ That is an actual run of `scoop status` I just did.

I am saying this is unnecessary. It does nothing else than say you need to run `scoop update`. `scoop status` is there to tell you what is out of date, how can it know what is out of date if the buckets are not updated? So it should just do it instead of you having to do it.

I am not talking about `scoop update *` or `scoop update <app>`, just `scoop update` which just updates the buckets (and scoop itself).

**Comment by HUMORCE** [comment]
`scoop status` will check if it needs to update itself or the bucket, but it will not perform the update.

I don't think it should update buckets, it design for get current status.

---

btw. it runs a little slow! so I use `--local` option for skip the checks every time.

**Comment by Skylark13** [comment]
Looks like we understand the purpose of `scoop status` a bit differently.

From `scoop --help`:
```
status     Show status and check for new app versions
```

When buckets are out of date, `scoop status` does not check for new app versions, it just tells you to run `scoop update`. You run `scoop update`, and then `scoop status` will tell you if any of your installed apps are out of date. I am just saying, why are those two steps when they could be a single step.

Anyways, I thought my suggestion made perfect sense, but it looks like others have different opinions.

**Comment by HUMORCE** [comment]
If the **status** triggers updates, why do we need it? Instead of moving it to the last stage of the **update** command? each module should be kept as independent as possible.

I think you are requesting feature like `brew update`, it will update homebrew itself and checking what's outdated packages and what new packages being added.

Anyway, you can create alias for `scoop update; scoop status --local`, this does not require any changes to do what you need.
