### ISSUE TITLE
[Bug]  Multiple pup-ups when updating

### ISSUE THREAD

**Issue by amreus** [ScoopInstaller/Scoop#5744]
#### Current Behavior

When running `scoop update` I get multiple popups asking "How do you want to open this file?"

#### Additional context/output

I've been using/updating scoop for years. I'm not sure what changed or when. Within the last week or 2.

![2023-11-25_060738](https://github.com/ScoopInstaller/Scoop/assets/38442825/6c7cf19e-c0eb-4f02-b4f9-d716a2e2802e)

EDIT:

If I choose open with Notepad, the window title says "git" if that helps.  I realize it might not be the problem of `scoop` but I'm not sure where to look.

![2023-11-25_093810](https://github.com/ScoopInstaller/Scoop/assets/38442825/940e125d-14a1-4277-8a8f-ba3bf478e569)

### System details

Windows 10 Home 64
PowerShell v5.1.19041.3693

#### Scoop Configuration

```json
{
    "alias":  {
                  "update":  "scoop-update"
              },
    "last_update":  "2023-11-25T06:07:37.0636249-05:00",
    "scoop_branch":  "master",
    "scoop_repo":  "https://github.com/ScoopInstaller/scoop"
}

```

**Comment by HUMORCE** [comment]
```
Get-Command 'git' # OR scoop which git
where.exe git
```

Check these for 'git'.

**Comment by amreus** [comment]
Ah yep that was it. I had an empty file named `git` in a directory in my PATH. 😬

Not sure where it came from. Typo or mistyped command probably. How silly. Thanks.
