### ISSUE TITLE
Scoop breaks when setting alias for a cmdlet it uses? (get-filehash) [Bug] 

### ISSUE THREAD

**Issue by nicksettoon** [ScoopInstaller/Scoop#5750]
#### Current Behavior

using a custom bucket and manifest to install powershell 7.4.0, i noticed an issue after i set an alias for `Get-FileHash`

$PROFILE alias

```powershell
#sal -Name hash -Value get-filehash
```

#### Expected Behavior

scoop recognizes the architecture and installs the package correctly.

#### Additional context/output

seems to be the same thing as in: https://github.com/ScoopInstaller/Scoop/issues/4177

#### Possible Solution

I removed my alias and all is right with the world again

ideally though, i should be able to keep the alias

### System details

**Windows version:** 10
**OS architecture:** 64bit

**PowerShell version:** 

```powershell
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      19041  3693
```

#### Scoop Configuration

```json
{
    "last_update":  "2023-12-05T16:13:05.7479913-06:00",
    "proxy":  "redacted",
    "scoop_branch":  "master",
    "scoop_repo":  "https://github.com/ScoopInstaller/Scoop"
}
```

**Comment by HUMORCE** [comment]
Known issue, let's discuss it in #5196

**Comment by nicksettoon** [comment]
perfect! thanks!
