### ISSUE TITLE
[Feature] Wrapper access to Chocolatey packages

### ISSUE THREAD

**Issue by ymartin59** [ScoopInstaller/Scoop#5761]
#### Is your feature request related to a problem? Please describe.

I am transitioning from Chocolatey to Scoop but some applications are not available in Scoop.
And it is painful to maintain both package list and follow updates with these two tools.

#### Describe the solution you'd like

Would it be possible to create a "chocolatey" bucket where nuget packages are indexed as manifests,
so that scoop can install and track packages installation delegated to chocolatey.
Of course "chocolatey" itself would be a package to install this package manager itself, which scoop will invoke when working with "chocolatey" bucket.

**Comment by HUMORCE** [comment]
Scoop is a package manager(or package installer, defined in documentation/wiki) for Scoop manifests instead of manager of package managers.
