### ISSUE TITLE
[Bug] Get-Encoding will fail when charset is incorrect

### ISSUE THREAD

**Issue by ChrisCatCP** [ScoopInstaller/Scoop#5763]
#### Current Behavior
scoop update version by https://baoku.360.cn/soft/show/appid/1900021484

#### Expected Behavior
N/A

#### Additional context/output
```
lib\core.ps1:20:16
Exception calling "GetEncoding" with "1" argument(s): "'utf8' is not a supported encoding name
```
#### Possible Solution
```
        try{
            return [System.Text.Encoding]::GetEncoding($Matches[1])
        }
        catch{
            return [System.Text.Encoding]::GetEncoding('utf-8')
        }
```

### System details

**Windows version:** 11

**OS architecture:** 64bit

**PowerShell version:** 7.4.0

**Additional software:** N/A

#### Scoop Configuration
N/A

**Comment by HUMORCE** [comment]
It's a bug on this site, not Scoop.

---

For documented, put https://github.com/ScoopInstaller/Scoop/pull/5764#issuecomment-1868446950 here:

> This will fall back all incorrect charsets to UTF-8. For sample page, create checkver.script to handle it separately is enough, and report the issue to the site.
