### ISSUE TITLE
[Bug] Remove/deprecate/warn about aria2c

### ISSUE THREAD

**Issue by mwisnicki** [ScoopInstaller/Scoop#5771]
As per https://github.com/ScoopInstaller/Scoop/issues/5341#issuecomment-1381133285 and based on reports of random errors it seems that aria2c is known to not work.

I think in this situation it should be removed or at least there needs to be a warning about it in the app and documentation.

**Comment by mwisnicki** [comment]
Related: https://github.com/ScoopInstaller/Scoop/issues/4472

**Comment by HUMORCE** [comment]
This warning will always shows when download with ariac, unless users disables it actively.

```
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
```

**Comment by mwisnicki** [comment]
I think it should be more explicit and warn that aria2c has known issues and link to relevant ticket.

**Comment by rashil2000** [comment]
The warning is printed every time a download is done (i.e. installing, updating). It's already mentioned _"Should it cause issues..."_, telling users it has known issues. 

The warning is explicit enough.
