### ISSUE TITLE
[Feature] scoop install: add `--pin` option to pin packages after installing them

### ISSUE THREAD

**Issue by soredake** [ScoopInstaller/Scoop#5780]
#### Is your feature request related to a problem? Please describe.
I want to do installing & pinning in one command, chocolatey can do this as it has `--pin` option since 1.2.0 version:
```
     --pin, --pinpackage, --pin-package
     Pin Package - Add a pin to the package after install. Available in 1.2.0+
```

#### Describe the solution you'd like
Adding `--pin` option to pin package after installing it.

#### Describe alternatives you've considered
Doing `scoop hold`

**Comment by HUMORCE** [comment]
Define a alias via `scoop alias` or `scoop install <App>@<version>`.
