### ISSUE TITLE
[Feature]  Enable scoop configuration file at user desired location

### ISSUE THREAD

**Issue by rawhuul** [ScoopInstaller/Scoop#5781]
Hey there,

Currently, scoop looks for the config file at `~/.config/scoop/config.json`. While this works well for most use cases, it would be great to have more flexibility in terms of the location of the config file.

One use case for this is portability. I like to be able to carry scoop and apps in my portable SSD, while with the current implementation, the config file is always looked for in the user directory - which doesn't makes it truely portable.

To address this, I propose the addition of an environment variable `$SCOOP_CONFIG`. If this variable is set, scoop would scan for the config file at the specified location. If the variable is not set, the default behavior of looking for the config file in the user directory would be taken place.

**Comment by chawyehsu** [comment]
It's already available in develop branch #5369

**Comment by rawhuul** [comment]
When it is expected to land in main branch?
