### ISSUE TITLE
AppyFlowy 404

### ISSUE THREAD

**Issue by knightknight** [ScoopInstaller/Scoop#5787]
#### Current Behavior
```bash
scoop update *
```

```bash
Updating 'appflowy' (0.4.1 -> 0.4.2)
Downloading new version
OperationStopped: C:\Users\<username>\scoop\apps\scoop\current\lib\install.ps1:111
Line |
 111 |          throw $e
     |          ~~~~~~~~
     | The remote server returned an error: (404) Not Found.
```

#### Expected Behavior
All apps auto updates.

#### Additional context/output
-

#### Possible Solution
- When using `update *` scoop script could detect and skip apps where updates are failing after a number of retries. Then continue with the remaining updates.
- Update script outputs a bug list for failing apps for submission to Github

### System details

**Windows version:** 11

**OS architecture:** 64bit

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]
```bash
Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      4      1
```

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration
```json
{
  "aria2-enabled": false,
  "last_update": "2024-01-19T10:03:22.4234464+00:00",
  "scoop_branch": "master",
  "scoop_repo": "https://github.com/lukesampson/scoop"
}
```

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Scoop/issues/4135
