### ISSUE TITLE
[Bug] False positive or what?

### ISSUE THREAD

**Issue by katastrophe92** [ScoopInstaller/Scoop#5788]
Hello Scoop team and thank you for this must have troject! I have scoop installed on this PC for about 1 years and never happened something like this and do not know how or why this happened. Thank!

![20 January 22024 ⁓ 00⁚12⁚04 ⁓ 1920  ⁄1032](https://github.com/ScoopInstaller/Scoop/assets/103950507/5b4da1f8-35c6-4195-9a40-4cbd524b7c40)

**Comment by rashil2000** [comment]
Scoop-search is a project written in Golang. Golang binaries are often tagged falsely by Windows Defender, see https://go.dev/doc/faq#virus

**Comment by katastrophe92** [comment]
> Scoop-search is a project written in Golang. Golang binaries are often tagged falsely by Windows Defender, see https://go.dev/doc/faq#virus

@rashil2000 Thanks for the reply. In all the years I haven't had a problem with scoop or a virus detection. Should I just restore the file or reinstall scoop?

**Comment by rashil2000** [comment]
You can just restore the file
