### ISSUE TITLE
Not possible to install kicad-nightly

### ISSUE THREAD

**Issue by mesmariusz** [ScoopInstaller/Scoop#5791]
## Bug Report

Not possible to install kicad-nightly

#### Current Behavior
```
scoop install kicad-nightly
Installing 'kicad-nightly' (32877.9d452a6097) [64bit] from versions bucket
Serwer zdalny zwrócił błąd: (404) Nie znaleziono.
URL https://kicad-downloads.s3.cern.ch/windows/nightly/kicad-nightly-r32877.9d452a6097-x86_64.exe#/dl.7z is not valid
PS C:\Windows\system32>
```

### System details

**Windows version:** 11

**OS architecture:** 64bit, arm64

**Comment by rashil2000** [comment]
`kicad-nightly` gets updated daily, just run `scoop update` and then `scoop install kicad-nightly`.
