### ISSUE TITLE
[Feature] Access tokens support.

### ISSUE THREAD

**Issue by rendevor** [ScoopInstaller/Scoop#5792]
#### Is your feature request related to a problem? Please describe.

I use the scoop for some specific purposes and would like to granulate access to the packages. For that purpose, I've configured multiple gitlab-based buckets, and Artifactory repositories accordingly. 
Uploaded manifest files to the gitlab repos, and zip files to artifactory repos as well. Git under the hood works well - user can setup git to use his credentials from cache/credstorage. Fetching artifacts doesn't work as expected. I don't see any suitable place, how to provide user's private token to download binaries. Saving token in the url in the manifest file is a bad practice. To make everting workable, I have granted anonymous read access on Artifactory, that this is an insecure as well. 

#### Describe the solution you'd like
To make this more secured, two tokens could be in use: `-manifest_token` and `-packages_token` for installation command. For git and binary storage accordingly. 
`scoop install -manifest_token AAA -packages_token BBB hello-world`

#### Describe alternatives you've considered
Another option, or additional feature - add support of `Windows Credentials Manager` for sensitive information. Or some option to use environment variables like `SCOOP_MANIFEST_TOKEN` and `SCOOP_PACKAGES_TOKEN`.

P.S. If I've overlooked the solution somewhere, please point me to the right direction. Thank you in advance.

**Comment by rashil2000** [comment]
Access tokens can be configured via request headers, see https://github.com/ScoopInstaller/Scoop/pull/4254#issuecomment-1068514131 and https://github.com/ScoopInstaller/Scoop/discussions/5140#discussioncomment-3605435
