### ISSUE TITLE
[Bug] 32bit apps were installed on ~/scoop/shims

### ISSUE THREAD

**Issue by homoioi** [ScoopInstaller/Scoop#5796]
## Bug Report
32bit apps were installed on ~/scoop/shims

$ cd ~/scoop/shims
$ file 7z.exe 7z.shim
7z.exe:  PE32 executable (console) Intel 80386, for MS Windows, 4 sections
7z.shim: ASCII text, with CRLF line terminators
$ cat 7z.shim
path = "C:\Users\zhang\scoop\apps\7zip\current\7z.exe"

$ file ../apps/7zip/current/7z.exe
../apps/7zip/current/7z.exe: PE32+ executable (console) x86-64, for MS Windows, 6 sections

#### Current Behavior

32bit 7z is called.
#### Expected Behavior

64bit one is called.
### System details

**Windows version:** [e.g. 7, 8, 10, 11]
11
**OS architecture:** [e.g. 32bit, 64bit, arm64]
64bit
**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      22621  2506

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
//# Your configuration here
```

**Comment by rashil2000** [comment]
The shim helper file is 32bit, since it works on all architectures - we provide only one shim file.

The actual program (7z here) is 64bit - 7z runs as a 64bit process only.
