### ISSUE TITLE
[Bug] Updating pip fails with "The system can not find the path specified"

### ISSUE THREAD

**Issue by Roemer** [ScoopInstaller/Scoop#5806]
## Bug Report
After installing python311 with Scoop and trying to update pip with `python -m pip install --upgrade pip`, I get an error:
```
ERROR: Could not install packages due to an OSError: [WinError 3] The system can not find the path specified:
'C:\\appl\\scoop\\apps\\python311\\current\\Scripts\\pip.exe' ->
'C:\\appl\\scoop\\apps\\python311\\current\\Scripts\\pip.exe.deleteme'
```

#### Current Behavior
Pip cannot be updated.

#### Expected Behavior
Pip is updated

#### Additional context/output
/

#### Possible Solution
/

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** 5.1.19041.3930

**Additional software:** -

#### Scoop Configuration
```json
{
    "root_path":  "C:\\appl\\scoop",
    "last_update":  "2024-02-14T08:33:40.8996414+01:00",
    "scoop_branch":  "master",
    "scoop_repo":  "https://github.com/ScoopInstaller/Scoop"
}

```

**Comment by rashil2000** [comment]
See https://github.com/ScoopInstaller/Main/issues/5090
