### ISSUE TITLE
[Bug] scoop status doesn't show outdated apps that need an update

### ISSUE THREAD

**Issue by Pratik543** [ScoopInstaller/Scoop#5810]
#### Current Behavior
Running scoop status does not shows the outdated apps info that there are new app version to install  and when running scoop update * it updates scoop and then downloads all the outdated apps and their is no way to see the outdated apps right now
![image](https://github.com/ScoopInstaller/Scoop/assets/71585947/ae51580b-374f-494f-8ed1-eb6cd28e5582)

#### Expected Behavior
Running scoop status should show that scoop need  an update and a list of apps for update if it is there.

### System details

**Windows version:** [11]

**OS architecture:** [64bit]

**PowerShell version:** [7.4.1]

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
{
  "last_update": "2024-02-22T19:47:56.8171231+05:30",
  "scoop_repo": "https://github.com/ScoopInstaller/Scoop",
  "scoop_branch": "master"
}
```

**Comment by niheaven** [comment]
You should update scoop buckets first (`scoop update`), and then run `scoop status` to see outdated apps. The warning is there, right?

**Comment by Pratik543** [comment]
Yeah, Got it. I thought it was a bug. 👍🏼
