### ISSUE TITLE
[Feature] Find out parent of a package

### ISSUE THREAD

**Issue by sanskar-mk2** [ScoopInstaller/Scoop#5817]
#### Is your feature request related to a problem? Please describe.
I have a package that I have not installed myself
```
PS C:\Users\sohma_w4> scoop info dark


Name        : dark
Description : WiX (Windows Installer XML) Toolset Decompiler
Version     : 3.14
Bucket      : main
Website     : https://wixtoolset.org
License     : MS-RL
Updated at  : 24-Feb-24 18:00:08
Updated by  : github-actions[bot]
Installed   : 3.11.2
              3.14
Binaries    : dark.exe
```

#### Describe the solution you'd like
Maybe the package is installed from some other package as a dependency(?), I would like feature to draw a tree that tells what caused this to install, or maybe a field like `parent`

#### Describe alternatives you've considered
None I can think of right now.

**Comment by rashil2000** [comment]
Let's track this in #4276, i.e. dependency management.
