### ISSUE TITLE
When i do scoop update;  Unlink of file 'bucket/apifox.json' failed. Should I try again? (y/n)

### ISSUE THREAD

**Issue by DrVektor** [ScoopInstaller/Scoop#5819]
having this error Unlink of file 'bucket/apifox.json' failed. Should I try again? (y/n) but if i do scoop update as admin never gives this error. But if i install some app as admin it app having some troubles while starting. For example forkgram never startsup. For example webcord. İf i install webcord as admin it wont start.
PS $ scoop update
Updating Scoop...
Updating 'extras' bucket...
Unlink of file 'bucket/apifox.json' failed. Should I try again? (y/n) n
error: unable to unlink old 'bucket/apifox.json': Invalid argument
Unlink of file 'bucket/fork.json' failed. Should I try again? (y/n) n
error: unable to unlink old 'bucket/fork.json': Invalid argument
Unlink of file 'bucket/free42.json' failed. Should I try again? (y/n) n
error: unable to unlink old 'bucket/free42.json': Invalid argument
Unlink of file 'bucket/gdevelop.json' failed. Should I try again? (y/n) n
error: unable to unlink old 'bucket/gdevelop.json': Invalid argument
Unlink of file 'bucket/kiwi-for-gmail.json' failed. Should I try again? (y/n) n
error: unable to unlink old 'bucket/kiwi-for-gmail.json': Invalid argument
Unlink of file 'bucket/metasploit-framework.json' failed. Should I try again? (y/n) n
error: unable to unlink old 'bucket/metasploit-framework.json': Invalid argument
Unlink of file 'bucket/mongodb-compass.json' failed. Should I try again? (y/n) n
error: unable to unlink old 'bucket/mongodb-compass.json': Invalid argument
Updating files: 100% (7/7), done.
Updating 'main' bucket...
 * 1e07bcdc4 rcc: Update to version 17.18.0                              3 hours ago
 * 57541acfc rakudo-star: Update to version 2024.02-01                   3 hours ago
 * 9df647738 rakudo-moar: Update to version 2024.02-01                   3 hours ago
 * 8d865d5e7 kubescape: Update to version 3.0.4                          3 hours ago
 * 67633273b ipinfo-cli: Update to version 3.3.1                         3 hours ago
 * 6ec314802 edgedriver: Update to version 121.0.2277.128                3 hours ago
 * 691624577 winnfsd: Update to version 2.4.0                            7 hours ago
 * de87df31d vale: Update to version 3.2.1                               7 hours ago
 * ace6d41bb groovy: Update to version 4.0.19                            7 hours ago
 * 4b3677d8f gitql: Update to version 0.15.0                             7 hours ago
 * 4cafccbc7 edgedriver: Update to version 122.0.2365.63                 7 hours ago
 * 04ec36a46 dvc: Update to version 3.48.1                               7 hours ago
 * 775b6c95a direnv: Update to version 2.34.0                            7 hours ago
 * 034afdbb9 coredns: Update to version 1.11.1                           7 hours ago
Updating 'nerd-fonts' bucket...
Updating 'nirsoft' bucket...
error: cannot update the ref 'refs/remotes/origin/master': unable to append to '.git/logs/refs/remotes/origin/master': Permission denied
Updating 'nonportable' bucket

**Comment by HUMORCE** [comment]
Try re-add the Extras bucket: `scoop bucket rm extras; scoop bucket add extras`

**Comment by DrVektor** [comment]
i for got to say as Normal User. When i do scoop update as normal user. These are Happens

**Comment by DrVektor** [comment]
@HUMORCE Thank you. I have implemented your suggestion, let's see if it works.
