### ISSUE TITLE
Is this repository active?

### ISSUE THREAD

**Issue by giacomomasseron** [ScoopInstaller/Scoop#5820]
Hi,  
someone knows if this repository is still active?

Thanks

**Comment by dezren39** [comment]
yes and no. develop branch is still active and there are maintainers, but it's mostly 'stable' and doesn't have enough maintainers for much feature work. Scoop buckets are regularly, and often automatically, maintained. You can add your app in those buckets pretty easily, but you can also stand up your own bucket.

**Comment by giacomomasseron** [comment]
Why not merge it into the master branch?

**Comment by pidgeon777** [comment]
I also hope `scoop` is still maintained.

**Comment by junlongzzz** [comment]
`dev` 分支现在支持 `bucket` 内嵌套文件夹了吗？e.g. [ScoopInstaller/Tests](https://github.com/ScoopInstaller/Tests/tree/master/bucket)
