### ISSUE TITLE
[Feature] List old versions of all apps

### ISSUE THREAD

**Issue by xiaoxstz** [ScoopInstaller/Scoop#5826]
## Feature Request

Add a command to show all the old versions installed, so we can know what we need to cleanup

#### Is your feature request related to a problem? Please describe.

I want to cleanup the old versions of the apps. But I don't want to cleanup all, in case the current versions of some apps are unstable.

If I use `scoop cleanup *`, all the old versions will be cleaned. If not, I don't know what apps have old versions.

#### Describe the solution you'd like

The command can be `scoop cleanup --show` , `scoop list --old` or `scoop old`

The output can be

```txt
Old versions:

Name            OldVersion
----                -------
vscode           1.86.2,1.86.1
alist               3.31.0          
```

**Comment by goyalyashpal** [comment]
try `scoop cache`:

```console
$ scoop -h
  ...
cache      Show or clear the download cache
  ...

$ scoop cache

Total: 78 files, 4.0 GB
Name                       Version                     Length URL
----                       -------                     ------ ---
7zip                       23.01                      1933312 https_www.7-zip.org_a_7z2301-x64.msi
  ...
```

**Comment by xiaoxstz** [comment]
`scoop cache`  command is used to check cache (the folder `<scoop_root>/cache`), rather than installed versions of apps

**Comment by goyalyashpal** [comment]
so, u r talking about multiple installations of same app?

**Comment by xiaoxstz** [comment]
yes

**Comment by rashil2000** [comment]
Try this (in PowerShell): 

```pwsh
(scoop list).Name | % { scoop info $_ } | select name, installed | fl *
```

**Comment by lgranie** [comment]
`git log *$app_name*`  in your bucket
