### ISSUE TITLE
[Bug] Cleanup error when item not found.

### ISSUE THREAD

**Issue by sanskar-mk2** [ScoopInstaller/Scoop#5857]
#### Current Behavior
Cleaning up everything gives error.
```
scoop cleanup *

Removing android-clt: 9477386Get-Item : Cannot find path 'C:\Users\sohma_w4\scoop\apps\android-clt\9477386\build-tools' because it does not exist.
At C:\Users\sohma_w4\scoop\apps\scoop\current\lib\install.ps1:1182 char:23
+             $source = Get-Item "$dir\$source"
+                       ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\sohma_...386\build-tools:String) [Get-Item], ItemNotFoundExcep
   tion
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemCommand
```

#### Expected Behavior
Should have cleaned up smoothly and gracefully handled this error.

#### Possible Solution
Handle this particular error in the code. Meanwhile tell what can easily resolve this.

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]
| Major | Minor | Build | Revision |
|-------|-------|-------|----------|
| 5     | 1     | 19041 | 3031     |

#### Scoop Configuration

```json
{
    "last_update":  "2024-03-28T19:18:16.5259420+05:30",
    "scoop_branch":  "master",
    "scoop_repo":  "https://github.com/lukesampson/scoop"
}
```

**Comment by HUMORCE** [comment]
Fixed by #5552
