### ISSUE TITLE
[Feature] `checkver.ps1` only updates `version` if `$version` is used in `autoupdate`

### ISSUE THREAD

**Issue by goyalyashpal** [ScoopInstaller/Scoop#5888]
#### Is your feature request related to a problem? Please describe.

the `scoop/bin/checkver.ps1` does not update `"version": ` in the manifest file, if `$version` is not used in `"autoupdate": `

#### Describe the solution you'd like

the `version` is updated as per specified in `checkver` specification

### example manifest:

```json
{
    "$schema": "https://raw.github.com/ScoopInstaller/Scoop/master/schema.json",
    ...
    "checkver": {
        "url": "https://api.github.com/repos/eclipse-theia/theia/releases/latest",
        "jsonpath": "$.tag_name",
        "regex": "v([\\d.]+)"
    },
    "version": "1.48.2",
    "architecture": {
        "64bit": {
            "url": "https://www.eclipse.org/downloads/download.php?file=/theia/ide/latest/windows/TheiaIDESetup.exe&r=1",
            "hash": "e4481f5a6a5a1a5551c76e321e12522c300405b75dcb1d6fe0815680214d84a1"
        }
    }
}

```

### versions

```console
$ scoop --version | head -n2
Current Scoop version:
v0.3.1 - Released at 2022-11-15

```

**Comment by WenSimEHRP** [comment]
I think you should use `checkver.ps1 -u`, with the extra `-u` argument

**Comment by niheaven** [comment]
Ref: https://github.com/ScoopInstaller/Extras/blob/master/bucket/sysinternals.json

**Comment by goyalyashpal** [comment]
hey @niheaven ! are you sure that extras/sysinternals is related to this? i think u have replied to a wrong issue 😄

**Comment by niheaven** [comment]
Isn't it? Wow, sysinternals manifest's autoupdate url is a fixed one, and checkver will check version update and then update file hash.

**Comment by goyalyashpal** [comment]
ohkayh. the link was shared out of blue with no context, thats why i
couldnt relate.

but yeah, i have got the reason... even the fixed url will go in
auto-updaet to get updated. my mistake was thinking only `$version` using
things go there & hence omitting the entire auto-update object itaelf for
such manifests.

thanks for sharing. this scenario was coming agaon and again in front of me.
