### ISSUE TITLE
[Bug] use_isolate_path set to True doesn't create SCOOP_PATH in environment variables

### ISSUE THREAD

**Issue by RavenMacDaddy** [ScoopInstaller/Scoop#5906]
#### Current Behavior
With the release of v0.4.0, I was interested in this new config option, so I set it, restarted the shell; Windows Terminal running PowerShell Core (v7), and installed Python as this has the `env_add_path` variable and was referenced in the [PR for the feature](https://github.com/ScoopInstaller/Scoop/pull/5840).

SCOOP_PATH is not created in the environment variables. What am I missing?

#### Expected Behavior
Create SCOOP_PATH and add %SCOOP_PATH% to PATH as referenced for the feature.

#### Additional context/output
![image](https://github.com/ScoopInstaller/Scoop/assets/67732686/60a749d6-4d2a-49d3-8442-ff61a38583be)

![image](https://github.com/ScoopInstaller/Scoop/assets/67732686/4a6614be-937b-416a-841f-64db374c3dff)

![image](https://github.com/ScoopInstaller/Scoop/assets/67732686/28f08762-0422-4893-8f78-1e235706f71a)

#### Possible Solution
Not sure - I'm probably missing something, and appreciate any help to understand the feature better.

### System details

**Windows version:** 11

**OS architecture:** 64 bit

**PowerShell version:** 7.4.2

**Additional software:** Not sure of anything relevant to the bug.

**Comment by chawyehsu** [comment]
The right config name is `use_isolated_path`.
