### ISSUE TITLE
[Bug] Unable to update proxy app after updating to 0.4.0

### ISSUE THREAD

**Issue by yuenwk** [ScoopInstaller/Scoop#5908]
#### Current Behavior
I updated to version 0.4.0, but I am unable to update the proxy application.
With the proxy turned off, I cannot access the network. With the proxy turned on, I cannot pass detection. I noticed that the order of detections has been modified #5799.

#### Possible Solution
Could you provide an option to skip the detection?

### System details

**Windows version:** 10

**OS architecture:** 64bit

**Comment by qwertyhjklxyz** [comment]
`scoop download <app>`, then close the proxy app and `scoop update <app>`.

**Comment by yuenwk** [comment]
> `scoop download <app>`, then close the proxy app and `scoop update <app>`.

Thank you, I didn't notice that operation before.
