### ISSUE TITLE
[Bug] scoop update failed

### ISSUE THREAD

**Issue by Arteiimis** [ScoopInstaller/Scoop#5917]
#### Current Behavior
after running `scoop update`:
```
Updating Scoop...
Updating Buckets...
INFO  Converting 'main' bucket to git repo...
ERROR 'main' bucket not found.
Failed to remove local 'main' bucket.
```

### System details

**Windows version:** 
10

**OS architecture:** 
64bit

**PowerShell version:**
```
Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      4      1
```

#### Scoop Configuration
```json
{
  "last_update": "2024-04-20T02:16:43.5865197+08:00",
  "aria2-enabled": false,
  "scoop_repo": "https://github.com/ScoopInstaller/Scoop",
  "scoop_branch": "master"
}

```

**Comment by lentikr** [comment]
Same issue. It seems there must be a "main" bucket for the 0.4.0 version of scoop.

**Comment by qwertyhjklxyz** [comment]
add main bucket back or change the name of your bucket to main.

**Comment by globalepub** [comment]
Open new PoweShell and enter `scoop bucket add main`
Enter `scoop update`
