### ISSUE TITLE
[Feature] Skip the update process AFTER download the package.

### ISSUE THREAD

**Issue by kevinmatthe** [ScoopInstaller/Scoop#5922]
## Feature Request

Skip the update process AFTER download the package.

#### Is your feature request related to a problem? Please describe.

If I'm running a proxy applictaion, which is also a proxy used by scoop, when I try update it, it will skip and not download the package.

So the problem is, I can't install this application, since it's hard to get connection to bucket without this proxy, when I remove the proxy config, I cannot download it forever.

#### Describe the solution you'd like

Why not just download the package, and then skip the install program? By using this feature, people with such issue can easily download package to scoop cache and then quit the proxy application, scoop update again, the application can be updated.

**Comment by chawyehsu** [comment]
You can use `scoop download` to download the app without installing it.
