### ISSUE TITLE
[Bug] Uncommitted changes detected. Update aborted.

### ISSUE THREAD

**Issue by xiaoxstz** [ScoopInstaller/Scoop#5926]
#### Current Behavior

The output of `scoop status` tells me to run `scoop update`
```Shell
λ scoop status
WARN  Scoop out of date. Run 'scoop update' to get the latest changes.
```

But the `scoop update` came across this warning.

```Shell
λ scoop update
Updating Scoop...
WARN  Uncommitted changes detected. Update aborted.
Updating Buckets...
Scoop was updated successfully!
```

Then, let's run  `scoop status` again. The warning still is in the output

```Shell
λ scoop status
WARN  Scoop out of date. Run 'scoop update' to get the latest changes.
```

There was an issue #5458 before, but it was closed with no details.

#### Expected Behavior

No any warning.

### System details

**Windows version:** [e.g. 7, 8, 10, 11] 10

**OS architecture:** [e.g. 32bit, 64bit, arm64]: 64bit

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]

```Shell
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      19041  4291
```

**Additional software:** [(optional) e.g. ConEmu, Git]: ConEmu,Git

#### Scoop Configuration

```json
//# Your configuration here
{
    "last_update":  "2024-04-27T09:52:07.6653120+08:00",
    "aria2-enabled":  false,
    "scoop_repo":  "https://github.com/ScoopInstaller/Scoop",
    "scoop_branch":  "master"
}
```

**Comment by qwertyhjklxyz** [comment]
It may be related to #5910.

**Comment by mattia72** [comment]
> It may be related to #5915.

+1 I'm experiencing both both error.

**Comment by qwertyhjklxyz** [comment]
One temporary solution is to add the scoop folder to windows defender exclusions.

**Comment by xiaoxstz** [comment]
Yes. It is related to #5915 .

## Reason

This issue appears when something in `{UserProfile}\scoop\apps\scoop\current` changes. If you haven't done it, security software（such as `Windows Defender`) is to blame.


`{UserProfile}\scoop\apps\scoop\current` is a git repository. You can check all the changes using `git status`.

## Solution

1. Add the folder to the exclusion of `Windows Defender` (or other security software).
2. Revert the changes with git.

**Comment by Reeceeboii** [comment]
> Yes. It is related to #5915 .
> 
> ## Reason
> This issue appears when something in `{UserProfile}\scoop\apps\scoop\current` changes. If you haven't done it, security software（such as `Windows Defender`) is to blame.
> 
> `{UserProfile}\scoop\apps\scoop\current` is a git repository. You can check all the changes using `git status`.
> 
> ## Solution
> 1. Add the folder to the exclusion of `Windows Defender` (or other security software).
> 2. Revert the changes with git.

For those who may be unaware of how to do this:

1. You need to have `git` installed.
2. Open Windows Defender, go to `Virus & threat protection`, then `Manage settings` under `Virus & threat protection settings`. Right down the bottom, there is an `Add or remove exclusions` option. Add `C:\Users\<user>\scoop\apps\scoop\current` to exclusions.
3. Open a PowerShell session in that same directory, and do a `git status`. In my case, I saw that Windows Defender had kindly deleted `autoupdate.ps1`:
![image](https://github.com/ScoopInstaller/Scoop/assets/42159320/2b146cc6-53ba-4765-9264-2590b776737d)
4. Undo this deletion (and any other unintended changes to this directory) by running `git checkout .`
![image](https://github.com/ScoopInstaller/Scoop/assets/42159320/0b15bd9b-8c2b-45e1-8eb4-326d91fb1838)
5. Finally, do a `scoop update`

Everything should now be shiny and working again.

**Comment by wsw70** [comment]
> Yes. It is related to https://github.com/ScoopInstaller/Scoop/issues/5915 .

There must be another reason for this. Defender is not active on my machine (Defender-the-malware-defender, not Defender Firewall). The security of the host is based on an EDR (CrowdStrike) and there are no alerts related to scoop.

**Comment by wthueb** [comment]
> > Yes. It is related to #5915 .
> 
> There must be another reason for this. Defender is not active on my machine (Defender-the-malware-defender, not Defender Firewall). The security of the host is based on an EDR (CrowdStrike) and there are no alerts related to scoop.

I ended up here because I experienced the same issue. I also have CrowdStrike, and Windows Defender disabled. I would assume CrowdStrike is what's removing the file (I'm just a user, so I can't see any alert information).

**Comment by wsw70** [comment]
> I can't see any alert information

There are none in Crowdstrike's console.

**Comment by Reeceeboii** [comment]
> > > Yes. It is related to #5915 .
> > 
> > 
> > There must be another reason for this. Defender is not active on my machine (Defender-the-malware-defender, not Defender Firewall). The security of the host is based on an EDR (CrowdStrike) and there are no alerts related to scoop.
> 
> I ended up here because I experienced the same issue. I also have CrowdStrike, and Windows Defender disabled. I would assume CrowdStrike is what's removing the file (I'm just a user, so I can't see any alert information).

Uh oh... Crowdstrike! Hope you're okay!!!

**Comment by wsw70** [comment]
> Uh oh... CrowdStrike! Hope you're okay!!!

Yeah, this was a miserable and annoying glitch but fortunately no losses of data or need to reinstall.

**Comment by SpeedRanger** [comment]
> > Yes. It is related to [#5915](https://github.com/ScoopInstaller/Scoop/issues/5915) .
> > ## Reason
> > This issue appears when something in `{UserProfile}\scoop\apps\scoop\current` changes. If you haven't done it, security software（such as `Windows Defender`) is to blame.
> > `{UserProfile}\scoop\apps\scoop\current` is a git repository. You can check all the changes using `git status`.
> > ## Solution
> > 
> > 1. Add the folder to the exclusion of `Windows Defender` (or other security software).
> > 2. Revert the changes with git.
> 
> For those who may be unaware of how to do this:
> 
> 1. You need to have `git` installed.
> 2. Open Windows Defender, go to `Virus & threat protection`, then `Manage settings` under `Virus & threat protection settings`. Right down the bottom, there is an `Add or remove exclusions` option. Add `C:\Users\<user>\scoop\apps\scoop\current` to exclusions.
> 3. Open a PowerShell session in that same directory, and do a `git status`. In my case, I saw that Windows Defender had kindly deleted `autoupdate.ps1`:
>    ![image](https://github.com/ScoopInstaller/Scoop/assets/42159320/2b146cc6-53ba-4765-9264-2590b776737d)
> 4. Undo this deletion (and any other unintended changes to this directory) by running `git checkout .`
> 
> ![image](https://github.com/ScoopInstaller/Scoop/assets/42159320/0b15bd9b-8c2b-45e1-8eb4-326d91fb1838) 6. Finally, do a `scoop update`
> 
> Everything should now be shiny and working again.

You are a legend. This fixed the issue for me.
