### ISSUE TITLE
update buckets error

### ISSUE THREAD

**Issue by BlackCherryCat** [ScoopInstaller/Scoop#5927]
#### Current Behavior
when I run the scoop update command it throws a git error

#### Additional context/output
![image](https://github.com/ScoopInstaller/Scoop/assets/68470515/345122f1-a034-4bdc-b4b7-6c6e7123201d)

### System details

**Windows version:**
11

**OS architecture:** 
64bit

**PowerShell version:**
7.4.2

#### Scoop Configuration

```json
[config.json](https://github.com/ScoopInstaller/Scoop/files/15136893/config.json)
```

**Comment by qwertyhjklxyz** [comment]
In your bucket repository, the local branch may have some commits ahead of the remote branch.

**Comment by qwertyhjklxyz** [comment]
Go to each bucket repository directory and run `git pull` to to see if the above error occurs.

**Comment by BlackCherryCat** [comment]
Could you be more specific, please? the steps to reproduce what you say

**Comment by qwertyhjklxyz** [comment]
Take `main bucket` as an example:

The default bucket repository directory is `C:\Users\<username>\scoop\buckets`.
`cd C:\Users\<username>\scoop\buckets\main`, then run `git pull`.
If the above error occurs, you can solve the problem by doing the following:
```
cd
scoop bucket rm main
scoop bucket add main
```

**Comment by BlackCherryCat** [comment]
Thanks, it was the DoveBoy's scoop bucket Apps that gave me the error, and I was able to solve it thanks to the steps to follow that you gave me.

Here's the bucket that gave me the error
https://github.com/DoveBoy/Apps
