### ISSUE TITLE
[Bug] `scoop cache rm <app>` does not output the name of cache file.

### ISSUE THREAD

**Issue by qwertyhjklxyz** [ScoopInstaller/Scoop#5941]
#### Current Behavior

On develop branch:
```
$ scoop cache rm git
Removing ...
Deleted: 1 file, 59.8 MB
```
#### Expected Behavior

```
$ scoop cache rm git
Removing git@2.45.0...
Deleted: 1 file, 59.8 MB
```
#### Additional context/output

It's caused by #5929.
#### Possible Solution

https://github.com/ScoopInstaller/Scoop/blob/5b86c302e5c43e2edfcebfe7acec58ee81969c7f/libexec/scoop-cache.ps1#L51
replace `URL` with `name@version` or `name--version`.
### System details

**Windows version:** 11

**OS architecture:** 64

**PowerShell version:** 7.4.2

#### Scoop Configuration

```json
{
  "scoop_branch": "develop",
  "cat_style": "plain",
  "use_isolated_path": true,
  "use_sqlite_cache": true,
  "scoop_repo": "https://github.com/ScoopInstaller/Scoop"
}
```

**Comment by chawyehsu** [comment]
#5944
