### ISSUE TITLE
[Bug]  scoop update WARN

### ISSUE THREAD

**Issue by arch3rPro** [ScoopInstaller/Scoop#5943]
#### Current Behavior
when i update scoop ,it return the WARN:

Updating Scoop...
WARN  Overwriting shim ('scoop.ps1' -> 'scoop.ps1') installed from scoop
WARN  Overwriting shim ('scoop.cmd' -> 'scoop.ps1') installed from scoop
WARN  Overwriting shim ('scoop' -> 'scoop.ps1') installed from scoop
Updating Buckets...
Scoop was updated successfully!

#### Expected Behavior

No WARN

### System details

**Windows version:11**

**OS architecture:64bit** 

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]

**Additional software:scoop** 

#### Scoop Configuration

```json
//# Your configuration here
```

**Comment by HUMORCE** [comment]
Not a bug. I think your issue should be **Scoop should hide the shim override hints it creates by itself**. 

At least to me, I think it's expected. the WARN you facing came because shim dependency updates.
