### ISSUE TITLE
[Bug] using any package gives error

### ISSUE THREAD

**Issue by nirgranth** [ScoopInstaller/Scoop#5952]
#### Current Behavior
using any package gives error

scoop install neofetch
Installing 'neofetch' (7.1.0) [64bit] from 'main' bucket
neofetch (333.6 KB) [=========================================================================================] 100%
Checking hash of neofetch ... ok.
Linking ~\scoop\apps\neofetch\current => ~\scoop\apps\neofetch\7.1.0
Creating shim for 'neofetch'.
'neofetch' (7.1.0) was installed successfully!
'neofetch' suggests installing 'git'.

neofetch
/bin/bash: C:\Users\nirgr\scoop\apps\neofetch\current\neofetch: No such file or directory

#### Expected Behavior
work as expected

#### Additional context/output
I have WSL and Cygwin installed

### System details

**Windows version:** Win 11 Version 23H2 (0S Build 22631.3447)

**Comment by yoBlastic** [comment]
I have the same issue.  Worked fine until installed WSL

**Comment by niheaven** [comment]
New version of Windows has `base` under `system32`, and this is a bug caused by it. Fix is under development, please wait.

**Comment by yoBlastic** [comment]
> New version of Windows has `bash` under `system32`, and this is a bug caused by it. Fix is under development, please wait.
thank you

**Comment by nirgranth** [comment]
Running neofetch or ani-cli doesn't work, is this package related
It doesn't seem to be working
