### ISSUE TITLE
[Feature] SOCKS proxy support

### ISSUE THREAD

**Issue by soredake** [ScoopInstaller/Scoop#5953]
#### Is your feature request related to a problem? Please describe.
Right now, if I understand everything correctly, only http proxies are supported, https://github.com/ScoopInstaller/Scoop/wiki/Using-Scoop-behind-a-proxy, would be nice to have support for SOCKS proxies

#### Describe the solution you'd like
Adding support for socks proxy.

#### Describe alternatives you've considered
Using http proxy.

**Comment by HUMORCE** [comment]
PowerShell does not support SOCKS protocol.

**Comment by westfly** [comment]
I use tools gost in WSL to generate a http-proxy as describe in [How to convert a Socks5 proxy to HTTP proxy?](https://askubuntu.com/questions/1376705/how-to-convert-a-socks5-proxy-to-http-proxy)
