### ISSUE TITLE
[Bug] Removing buckets doesn't remove corresponding sqlite caches

### ISSUE THREAD

**Issue by chawyehsu** [ScoopInstaller/Scoop#5963]
## Bug Report

`scoop bucket rm <bucket>` Removing buckets doesn't clear corresponding sqlite caches

#### Current Behavior

```sh
scoop config use_sqlite_cache true
scoop bucket add versions
scoop bucket rm ersions
scoop search nodejs-nightly
# nodejs-nightly manfiest from the Versions bucket remains available
```

#### Expected Behavior

```
# nodejs-nightly manfiest from the Versions bucket should not be available
```

#### Possible Solution

Perform sqlite cache update when removing a bucket.

### System details

Irrelevant

#### Scoop Configuration

```
{
  ...
  "scoop_branch": "develop",
  "use_sqlite_cache": true
}
```

**Comment by niheaven** [comment]
Another tweak: remove cache when manifest is removed from bucket (or add a flag in database)
