### ISSUE TITLE
[Bug] Scoop now skips downloading setup package if the progrram is already running

### ISSUE THREAD

**Issue by xolve** [ScoopInstaller/Scoop#5970]
## Bug Report
Scoop now requires that current running program should be closed before it starts download of setup package. Earlier it used to download and then attempt to install or skip installation based on application running status.

#### Current Behavior
Scoop now requires that current running program should be closed before it starts download of setup package. Closing the application and waiting for download and installation is too much of time to wait.

#### Expected Behavior
Scoop should download the setup package before it attempt install or checks for running application before cancelling installation. This reduces the amount of time for which an app need to be stopped.

#### Additional context/output
Failed installation because firefox is already running.
```
~> scoop update firefox
firefox: 125.0.3 -> 126.0
Updating one outdated app:
Updating 'firefox' (125.0.3 -> 126.0)
ERROR The following instances of "firefox" are still running. Close them and try again.

Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
    378      67   300296     199496      39.03   1800   1 firefox
....



Running process detected, skip updating.
```

After closing firefox, download and installation proceeds
```
~> scoop update firefox
firefox: 125.0.3 -> 126.0
Updating one outdated app:
Updating 'firefox' (125.0.3 -> 126.0)
Downloading new version
Firefox%20Setup%20126.0.exe (61.4 MB) [=========================================================================================================================] 100%
Checking hash of Firefox%20Setup%20126.0.exe ... ok.
Uninstalling 'firefox' (125.0.3)
Removing shim 'firefox.shim'.
Removing shim 'firefox.exe'.
Unlinking ~\scoop\apps\firefox\current
Installing 'firefox' (126.0) [64bit] from 'extras' bucket
Loading Firefox%20Setup%20126.0.exe from cache
Extracting dl.7z ... done.
Linking ~\scoop\apps\firefox\current => ~\scoop\apps\firefox\126.0
Creating shim for 'firefox'.
Making <...>\firefox.exe a GUI binary.
Creating shortcut for Firefox (firefox.exe)
Creating shortcut for Firefox Profile Manager (firefox.exe)
Persisting distribution
Persisting profile
Running post_install script...
'firefox' (126.0) was installed successfully!
Notes
-----
To set profile 'Scoop' as *DEFAULT*, or profiles/settings was lost after update:
- Run 'Firefox Profile Manager', choose 'Scoop' then click 'Start Firefox'.
- Visit 'about:profiles' page in Firefox to check *DEFAULT* profile.
For details: https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles
```

### System details

**Windows version:** Windows 11

**OS architecture:** x86_64

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      22621  2506

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
{
    "last_update":  "2024-05-15T14:37:28.4192097+05:30",
    "scoop_branch":  "master",
    "scoop_repo":  "https://github.com/ScoopInstaller/Scoop"
}
```

**Comment by lisonge** [comment]
@niheaven 

hello, so how to set the default behavior of scoop is that download app file instead of stop download ?

manually invoking `scoop download` is cumbersome

**Comment by niheaven** [comment]
`scoop config ignore_running_processes true`

**Comment by lisonge** [comment]
thanks

**Comment by lisonge** [comment]
`ignore_running_processes` will break my program, my vscode display incorrectly

actually I want `only_download_if_processes_running`
