### ISSUE TITLE
Installing without adding to path

### ISSUE THREAD

**Issue by insertokername** [ScoopInstaller/Scoop#5974]
## Be able to install package without adding it to path

for my specific use case it would be extremely useful to completely ignore the env_add_path attributes while installing a package.

If this already exists in some shape i would really love to hear your solutions.

**Comment by niheaven** [comment]
Have you tried `use_isolated_path` feature?

**Comment by insertokername** [comment]
> Have you tried `use_isolated_path` feature?

Thank you so much for your answer!

This works perfectly!

**Comment by insertokername** [comment]
> Have you tried `use_isolated_path` feature?

Thank you very much it worked perfectly!
Sorry for the late reply i wanted to make sure it worked in my prpject before responding!
