### ISSUE TITLE
Autoupdate to manifest url

### ISSUE THREAD

**Issue by insertokername** [ScoopInstaller/Scoop#5977]
Hello everyone!

I was wondering if there was any way i could use the `autoupdate`  name@version feature with a manifest specified as a path and not from a bucket.

For example lets say i have a `manifest.json` that has an `autoupdate` field. If I were to run:

`scoop install ./manifest.json@20`

I would receive the error: `Couldn't find manifest for 'manifestjson@20'`

Is there any workaround to this? Any flags i could set?

**Comment by niheaven** [comment]
Unfortunately, this feature is not available in Scoop now. You need to create a manifest containing the correct version.

**Comment by insertokername** [comment]
Could i start development on this myself?

**Comment by insertokername** [comment]
Sorry for the many messages but i have been looking around in the source and i think i have found an easier way of just implementing the original feature i was looking for.

https://github.com/ScoopInstaller/Scoop/blob/d337bb1fa69a56637101254a1ac9e0ad13a12647/lib/core.ps1#L1174-L1180

Changing this regex to 
```
^(?:(?<bucket>[a-zA-Z0-9-_.]+)/)?(?<app>.*\.json|[a-zA-Z0-9-_.]+)(?:@(?<version>.*))?$'
```
(removing the `$` after .json) seems to accomplish exactly what i was looking for in the original request. Examining the regex more i can't seem to find any conflicts that may be caused by removing the `$` anchor.

Looking forward to your feedback!

**Comment by niheaven** [comment]
You are right, please submit a PR and I'll review it.
