### ISSUE TITLE
[Bug] After reinstalling, entering “scoop list” software name will print twice 重装后输入scoop list软件名会打印两次

### ISSUE THREAD

**Issue by xianyu23333** [ScoopInstaller/Scoop#5978]
#### Current Behavior
After reinstalling, entering “scoop list” software name will print twice 重装后输入scoop list软件名会打印两次

#### Additional context/output
![image](https://github.com/ScoopInstaller/Scoop/assets/50168997/c9e65e61-c943-45f5-9d40-1c21a067e056)

### System details

Windows 11

#### Scoop Configuration
{
  "last_update": "2024-05-18T21:38:10.4491386+08:00",
  "aria2-enabled": false,
  "aria2": "-enabled",
  "aria2-warning-enabled": true,
  "scoop_repo": "https://github.com/ScoopInstaller/Scoop",
  "scoop_branch": "master",
  "proxy": "127.0.0.1:7897",
  "global_path": "D:\\Scoop"
}

**Comment by HUMORCE** [comment]
Because the global dir and Scoop Core dir are same path.

Tracked here: #4424
