### ISSUE TITLE
[Bug] search command error MethodInvocationException

### ISSUE THREAD

**Issue by neederhow** [ScoopInstaller/Scoop#5980]
#### Current Behavior
print MethodInvocationException

#### Expected Behavior
show search result

#### Additional context/output
[log.txt](https://github.com/ScoopInstaller/Scoop/files/15374254/log.txt)

### System details

**Windows version:**  10 (19045.4412)

**OS architecture:**  64bit

**PowerShell version:** 
```shell
Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      2      6
```
**Additional software:**
git version 2.45.1.windows.1

#### Scoop Configuration

```json
{
  "aria2-max-connection-per-server": "16",
  "aria2-split": "16",
  "aria2-min-split-size": "1M",
  "global_path": "D:\\GlobalScoopApps",
  "last_update": "2024-05-20T15:12:32.3921906+08:00",
  "root_path": "D:\\Scoop",
  "aria2-enabled": false,
  "aria2-warning-enabled": false,
  "scoop_repo": "https://github.com/ScoopInstaller/Scoop",
  "scoop_branch": "master"
}
```

**Comment by niheaven** [comment]
Error of manifests. Please remove all unofficial buckets and try again.

**Comment by LuoHuiRu** [comment]
删除非官方存储桶中 App Manifests 中的注释，就不会报错了。
