### ISSUE TITLE
[Feature] Provide an option to download update and check after downloaded

### ISSUE THREAD

**Issue by WOSHIZHAZHA120** [ScoopInstaller/Scoop#5994]
#### Is your feature request related to a problem? Please describe.

I have a network application, I want update this application, but I need to use it to connect to the network, and when exiting, I will be disconnected from the network

#### Describe the solution you'd like

i want scoop provide an option to move process check step to after download, then can direct install from cache

#### Describe alternatives you've considered

I temporary using phone usb share network to instead now

**Comment by qwertyhjklxyz** [comment]
#5908
