### ISSUE TITLE
[Feature] Allow $version to be specified in 'shortcuts' field.

### ISSUE THREAD

**Issue by milnak** [ScoopInstaller/Scoop#5996]
#### Is your feature request related to a problem? Please describe.
Currently there's no way to use `$version` in shortcuts.  An [app I use](https://github.com/milnak/scoop-bucket/blob/main/bucket/synthtribe.json) has the exe named 'SYNTHTRIBE V2.7.4.exe".  

#### Describe the solution you'd like
Would be nice to have:

```json
"shortcuts": [
    [
        "SYNTHTRIBE V$version.exe",
        "SYNTHTRIBE"
    ]
],

```

#### Describe alternatives you've considered
I've worked around this by creating a pre_install that renames '*.exe' to a constant name.

**Comment by niheaven** [comment]
It could be, please add `shortcuts` field in `autoupdate`.

**Comment by milnak** [comment]
Are you saying that this already should work? If so, I'll try it.

**Comment by niheaven** [comment]
Yes, it already works now.

**Comment by milnak** [comment]
Thanks!
