### ISSUE TITLE
[Bug] Frequent script error involving setting environmental variables I think

### ISSUE THREAD

**Issue by CaptainFrosty** [ScoopInstaller/Scoop#5999]
#### Current Behavior
![image](https://github.com/ScoopInstaller/Scoop/assets/8523498/6429b488-4402-4ab4-bcf7-01d73108e0ad)

#### Expected Behavior
Haven't looked at `install.ps1` so not sure what it is trying to do

#### Additional context/output
Nothing seems amiss in my variables, haven't noticed any harm nor does it fail to complete update

### System details

**Windows version:** [e.g. 7, 8, 10, 11]
11 23H2

**OS architecture:** [e.g. 32bit, 64bit, arm64]
64-bit

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]
7.4.2 Core

**Additional software:** [(optional) e.g. ConEmu, Git]
It occurs when updating multiple things

#### Scoop Configuration

```json
 {
  "last_update": "2024-06-03T14:55:08.5062086-04:00",
  "aria2-enabled": true,
  "aria2-warning-enabled": false,
  "update-nightly": true,
  "cat_style": "bat",
  "virustotal_api_key": "XXXXXX",
  "default_architecture": "64bit",
  "scoop_repo": "https://github.com/ScoopInstaller/Scoop",
  "scoop_branch": "master"
}
```

**Comment by Roundlay** [comment]
Seeing the same issue when attempting to update/install Odin.
 
![image](https://github.com/ScoopInstaller/Scoop/assets/4133752/c91bf517-943a-4c36-b45f-34eef3b11261)

**Comment by HUMORCE** [comment]
Can it be reproduced in current version? relevant function has been modified.

@Roundlay The error caused by manifest not Scoop Core, please create issue in corresponding bucket repo if it still exists.
