### ISSUE TITLE
[Bug] "persist" is case sensitive!

### ISSUE THREAD

**Issue by milnak** [ScoopInstaller/Scoop#6007]
#### Current Behavior
I found this when I saw that nirsoft/usbdeview wasn't persisting configuration.

That manifest has:

```json
    "persist": [
        "usbdeview_lng.ini",
        "usbdeview.cfg"
    ],
```

but this doesn't persist as the configuration file is named `USBDeview.cfg`.  Window filenames are case-insensitive, and as such Scoop should be too, or at least check to see if the OS is case-sensitive first?

#### Expected Behavior
Should match case-insensitive.

**Comment by qwertyhjklxyz** [comment]
If these two files are not present or are not created in the `pre_install`, they will be persisted as folder.
