### ISSUE TITLE
How to Install Scoop in the current directory？

### ISSUE THREAD

**Issue by dbyoung720** [ScoopInstaller/Scoop#6018]
Install Scoop in the current directory, regardless of whether Scoop has already been installed.
How to write a cmd script?

**Comment by Ra2-IFV** [comment]
You'd better not, it's meaningless. I guess it won't be supported.

**Comment by HUMORCE** [comment]
You can do this with parameters: https://github.com/ScoopInstaller/Install?tab=readme-ov-file#advanced-installation

- For an override installation, you can simply run `rm <scoop_root_dir> -force` before install. 
- Scoop-related environment variables need to remove manually, if they are added before.
