### ISSUE TITLE
[Bug] git isnt installing

### ISSUE THREAD

**Issue by pixellord1** [ScoopInstaller/Scoop#6022]
#### Current Behavior
I write scoop install git but because it didn't install 7zip it couldn't install git.
#### Expected Behavior
it'll install git.
#### Additional context/output
```
WARN  Purging previous failed installation of 7zip.
ERROR '7zip' isn't installed correctly.
Removing older version (24.07).
'7zip' was uninstalled.
Installing '7zip' (24.07) [64bit] from 'main' bucket
Loading 7z2407-x64.msi from cache
Checking hash of 7z2407-x64.msi ... ok.
Extracting 7z2407-x64.msi ... ERROR Exit code was 1632!
The expression after "&" in the pipeline element produced an invalid object. The result of the expression should be 
the name of a command, script block, or CommandInfo object.
C:\Users\roman\scoop\apps\scoop\current\lib\core.ps1:273 character:18
+         return & $git @ArgumentList
+                  ~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : BadExpression

The expression after "&" in the pipeline element produced an invalid object. The result of the expression should be 
the name of a command, script block, or CommandInfo object.
C:\Users\roman\scoop\apps\scoop\current\lib\core.ps1:291 character:14
+     return & $git @ArgumentList
+              ~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : BadExpression

Failed to extract files from C:\Users\roman\scoop\apps\7zip\24.07\7z2407-x64.msi.
Log file:
  ~\scoop\apps\7zip\24.07\msi.log

Please try again or create a new issue by using the following link and paste your console output:
https://
```
### System details
Intel Core i5-4590S CPU @ 3.00Ghz, DDR3, Geforce GTX 1070
**Windows version:** [e.g. 7, 8, 10, 11]
11
**OS architecture:** [e.g. 32bit, 64bit, arm64]
64bit
**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]
5.1.22621.3672
**Additional software:** [(optional) e.g. ConEmu, Git]
-
#### Scoop Configuration

{
    "last_update":  "2024-06-21T09:30:44.5688879+03:00",
    "scoop_repo":  "https://github.com/ScoopInstaller/Scoop",
    "scoop_branch":  "master"
}

```json
//# Your configuration here
```
 i dont have it

**Comment by HUMORCE** [comment]
A `7zip` installation are required for installing `git`, but you are facing a `7zip` extraction error while installing, then you failed to install `git`.

This is usually caused by a msiexec process exception, go one of them:

- Restart the PC then retry.
- Switch to alternative MSI extractor: `scoop config use_lessmsi true` (Default: false)
- Resolve the msiexec exception then retry, If you know about it.

Learn more: https://learn.microsoft.com/en-us/windows/win32/msi/error-codes
