### ISSUE TITLE
[Bug] `scoop cleanup --all --cache` does not clean all cache

### ISSUE THREAD

**Issue by wickles** [ScoopInstaller/Scoop#6025]
#### Current Behavior

`scoop cleanup --all --cache` does not clear cached downloads for uninstalled apps from `~/scoop/cache`

#### Expected Behavior

All cached downloads for old versions and uninstalled apps should be be removed.

#### Additional context/output

Examples of apps with leftover files in the cache:

- fastcopy 5.3.0 .. 5.7.12
- git-with-openssh 2.42.0
- windowsdesktop-runtime-lts 6.0.21 .. 6.0.23
- mysql 8.3.0
- grep 3.11
- oh-my-posh 18.6.0 .. 18.8.1

Also cannot be cleared by specifying the app:

```
> scoop cleanup --cache mysql
ERROR 'mysql' isn't installed.
```

### System details

**Windows version:** 11

**OS architecture:** 64bit

**PowerShell version:** 7.4.2

#### Scoop Configuration

```json
{
  "last_update": "2024-06-22T13:19:28.4880705-07:00",
  "aria2-warning-enabled": false,
  "scoop_branch": "master",
  "scoop_repo": "https://github.com/ScoopInstaller/Scoop"
}
```

**Comment by HUMORCE** [comment]
`cleanup` work with installed manifests only.

```
scoop install app        # 1.0
scoop update app         # 1.5
scoop reset app@1.0
scoop cleanup app --cache
Removing app: 1.5

app --version
1.0

scoop cache app
Name Version Length
app  1.0     12345
```

**Comment by wickles** [comment]
Note for myself and any other readers: `scoop cache rm ...` is helpful here.
