### ISSUE TITLE
Updating pwsh fails, because scoop always uses pwsh during install

### ISSUE THREAD

**Issue by lynx-xdg** [ScoopInstaller/Scoop#6029]
#### Current Behavior
While trying to update pwsh, the install fails because running the install script uses an instance of pwsh.

#### Expected Behavior
When updating pwsh.exe scoop should use powershell.exe instead of pwsh.exe.

#### Additional context/output
The shim for scoop will switches to pwsh.exe, even when run by powershell.exe.

#### Source of the problem
The current scoop shim:
```powershell
@rem C:\Users\rikvd\scoop\apps\scoop\current\bin\scoop.ps1
@echo off
where /q pwsh.exe
if %errorlevel% equ 0 (
    pwsh -noprofile -ex unrestricted -file "C:\Users\rikvd\scoop\apps\scoop\current\bin\scoop.ps1"  %*
) else (
    powershell -noprofile -ex unrestricted -file "C:\Users\rikvd\scoop\apps\scoop\current\bin\scoop.ps1"  %*
)
```

### System details

**Windows version:** 11

**OS architecture:** 64bit

**PowerShell version:** 
``` 
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      22621  3672    
```

**Additional software:** `pwsh.exe` (installed via scoop) and `powershell.exe`

#### Scoop Configuration

```json
{
  "last_update": "2024-06-24T18:51:28.9137540+02:00",
  "scoop_branch": "master",
  "scoop_repo": "https://github.com/ScoopInstaller/Scoop"
}
```

**Comment by lynx-xdg** [comment]
I've got it working by modifying `shims/scoop.cmd` to always use `powershell` and only saw the error message after the install succeeded. The proposed 'fix' in the error message also doesn't work, since the shim will get used anyways, thus using `pwsh` again.

**Comment by niheaven** [comment]
Use Windows PowerShell while update pwsh.

**Comment by jcotton42** [comment]
@niheaven why does Scoop try to use PS7 anyhow? It seems it has to support both 5.1 and 7 anyhow, so why not just always use 5 to avoid this issue?

At the very least, I think scoop should output a warning when this situation occurs, because this also happens when running `scoop update` from `cmd` (which I do since it starts a little faster than WinPS).
