### ISSUE TITLE
[Bug] 7ZIPEXTRACT_USE_EXTERNAL 

### ISSUE THREAD

**Issue by thealjey** [ScoopInstaller/Scoop#6032]
#### Current Behavior
Why, oh please tell me why is 7ZIPEXTRACT_USE_EXTERNAL completely ignored?
I did find a few issues that have, supposedly, been fixed long ago.
But, evidently, the problem wasn't really fixed, because it is still tormenting me today, with all the latest versions of everything installed.
I do have 7zip installed globally using chocolatey and the `7z` command is globally available to powershell.

#### Expected Behavior
A global installation of 7zip used.

#### Additional context/output
```sh
PS C:\Users\aljey> (Get-Command '7z' -CommandType Application -ErrorAction Stop | Select-Object -First 1).Source
C:\ProgramData\chocolatey\bin\7z.exe

PS C:\Users\aljey> scoop config 7ZIPEXTRACT_USE_EXTERNAL true
'7ZIPEXTRACT_USE_EXTERNAL' has been set to 'true'

PS C:\Users\aljey> scoop install renpy
Installing '7zip' (24.07) [64bit] from 'main' bucket
The remote name could not be resolved: 'www.7-zip.org'
URL https://www.7-zip.org/a/7z2407-x64.msi is not valid
```

#### Possible Solution
Maybe don't ignore your own configuration options and show meaningful error messages instead of eagerly jumping into the installation of a package you were not asked to be installed??

Or, how about making it possible to specify `$7zPath` directly, removing the need for any searching at all?

### System details

**Windows version:** 11

**OS architecture:** 64bit

**PowerShell version:**
Major | Minor | Build | Revision
----- | ----- | ----- | --------
5   |   1   |   22621 | 3672

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration
```json
{
    "last_update":  "2024-06-28T00:16:41.7796475+03:00",
    "scoop_repo":  "https://github.com/ScoopInstaller/Scoop",
    "scoop_branch":  "master",
    "7zipextract_use_external":  true
}
```

**Comment by chawyehsu** [comment]
[`7ZIPEXTRACT_USE_EXTERNAL`](https://github.com/ScoopInstaller/Scoop/pull/5715/files)'s been deprecated, please run `scoop help config` to view the valid config options.

**Comment by thealjey** [comment]
@chawyehsu that one comment was more helpful to my nervous system, than the whole scoop website

have a lovely day and thank you very much!
