### ISSUE TITLE
[Bug] ConvertFrom-Json

### ISSUE THREAD

**Issue by QinHongZhe** [ScoopInstaller/Scoop#6033]
ConvertFrom-Json : 传入的数组无效，结尾多出了“,”。 (558): {
    "version": "2.0.6",
    "homepage": "https://freetimetech.com/windows-11-debloater-tool-debloat-gui/",
    "description": "A desktop search application",
    "license": "MIT",
    "url": "https://freetimetech.com/W11D/Windows11DebloaterV206.zip",
    "hash": "921fbc7e3d1b8b4a77cfec0948cbda6209ca1876e0e3ba10288253632fa269ee",
    "extract_dir": "Windows11DebloaterV206",
    "bin": [
        "Windows11Debloater.exe"
    ],
    "shortcuts": [
        [
            "Windows11Debloater.exe",
            "Windows 11 Debloater",
        ]
    ],
    "checkver": {
        "regex": "Windows 11 Debloater Tool | Debloat GUI \\(Updated.*V\\d+(\\.\\d+)+\\)"
    },
    "autoupdate": {
        "url": "https://freetimetech.com/W11D/Windows11DebloaterV$cleanversion.zip",
        "extract_dir": "Windows11DebloaterV$cleanversion"
    }
}
所在位置 D:\workspace\scoop_workspace\apps\scoop\current\libexec\scoop-search.ps1:97 字符: 66
+ ... e]::ReadAllText($_.FullName) | ConvertFrom-Json -ErrorAction Continue
+                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand

**Comment by niheaven** [comment]
Please check your manifest carefully or format it using an editor such as VSCode.

An invalid comma is added here:
```json
[
"Windows11Debloater.exe",
"Windows 11 Debloater",
]
```
