### ISSUE TITLE
[Bug] innounp still used by default, rather than innounp-unicode

### ISSUE THREAD

**Issue by wickles** [ScoopInstaller/Scoop#6040]
#### Current Behavior

#6028 was supposed to make `innounp-unicode` the default inno helper but it does not seem to be working as intended. 

I updated scoop to 0.5.0, uninstalled `innounp` and tried to install `ollama` with the same results as in https://github.com/ScoopInstaller/Main/pull/5920 because it still installs and uses `innounp` instead of `innounp-unicode`.

```
> scoop --version
Current Scoop version:
716b6db3 (HEAD -> master, tag: v0.5.0, origin/master, origin/HEAD) chore(release): Bump to version 0.5.0 (#6035)
...
> scoop install ollama
Installing 'innounp' (0.50) [64bit] from 'main' bucket
Loading innounp050.rar from cache.
Checking hash of innounp050.rar ... ok.
Extracting innounp050.rar ... done.
Linking ~\scoop\apps\innounp\current => ~\scoop\apps\innounp\0.50
Creating shim for 'innounp'.
'innounp' (0.50) was installed successfully!
Installing 'ollama' (0.1.48) [64bit] from 'main' bucket
Loading OllamaSetup.exe from cache.
Checking hash of OllamaSetup.exe ... ok.
Extracting OllamaSetup.exe ... ERROR Exit code was 1!
Failed to extract files from C:\Users\me\scoop\apps\ollama\0.1.48\OllamaSetup.exe.
Log file:
  ~\scoop\apps\ollama\0.1.48\innounp.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=ollama%400.1.48%3a+decompress+error
```

#### Expected Behavior

`innounp-unicode` should be installed and used as the default inno helper now.

#### Additional context/output

After I manually installed `innounp-unicode` it is now used as expected.

### System details

**Windows version:** 11

**OS architecture:** 64bit

**PowerShell version:** 7.4.3

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
{
  "last_update": "2024-07-04T21:48:43.8714325-07:00",
  "aria2-warning-enabled": false,
  "scoop_branch": "master",
  "scoop_repo": "https://github.com/ScoopInstaller/Scoop"
}
```

**Comment by qwertyhjklxyz** [comment]
It seems that `innounp-unicode` complements `innounp`, not replaces it, because `innounp-unicode` is in the `versions` repository rather than the `main` repository.

**Comment by kjxbyz** [comment]
@qwertyhjklxyz How do I specify `innounp-unicode` when running `scoop install`?

**Comment by qwertyhjklxyz** [comment]
> How do I specify `innounp-unicode` when running `scoop install`?

`scoop install` cannot specify which `innounp` to use.
When `innounp-unicode` is installed, it will use `innounp-unicode` instead of `innounp`.

**Comment by kjxbyz** [comment]
It doesn't work for me.

**Comment by wickles** [comment]
Try uninstalling `innounp` as well.

**Comment by niheaven** [comment]
Just install `innounp-unicode`, if installed, scoop will use it as default.

**Comment by kcrkor** [comment]
`innounp` is still causing havoc. maybe scoop can default to `innounp-unicode`.

See all the[ issues collecting in the extras bucket](https://github.com/ScoopInstaller/Extras/issues?q=is%3Aissue+is%3Aclosed+decompress+error).
