### ISSUE TITLE
[Bug] Environment variables in env_set are not correctly replaced after version 0.5.0

### ISSUE THREAD

**Issue by Vixb1122** [ScoopInstaller/Scoop#6043]
## Bug Report
Assume the scoop path is D:\Scoop, the application name is trilium, and the configuration is as follows:
```
"env_set": {
    "TRILIUM_DATA_DIR": "$persist_dir\\trilium-data"
}
```
#### Current Behavior

In the environment variables, the value of TRILIUM_DATA_DIR is $persist_dir\\trilium-data.

#### Expected Behavior
In the environment variables, the value of TRILIUM_DATA_DIR should be D:\Scoop\persist\trilium\trilium-data.

#### Possible Solution
Revert to the behavior of the previous version.

### System details

**Windows version:**  11

**OS architecture:** 64bit

**PowerShell version:** 
```
Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      4      3
```

**Additional software:** 

#### Scoop Configuration
```
{
  "last_update": "2024-07-06T13:01:04.5869117+08:00",
  "scoop_repo": "https://github.com/ScoopInstaller/Scoop",
  "scoop_branch": "master",
  "use_sqlite_cache": true
}
```

**Comment by qwertyhjklxyz** [comment]
@niheaven Restore the previous version's behavior by adding `$persist_dir`, or change the app manifest to adapt to the changes?

**Comment by niheaven** [comment]
Okay, it's a bug from #5968, I'll fix it soon.

**Comment by Vixb1122** [comment]
Hope to release a new version based on this fix as soon as possible. @niheaven

**Comment by Jordan-Haidee** [comment]
It seems that this fix didn't take effect at all now, which caused all python virtual envs on my computer was destoryed.😭 @niheaven 
![image](https://github.com/ScoopInstaller/Scoop/assets/85778126/853804e3-97b9-403f-9b1f-c3baeb83e5c5)

**Comment by niheaven** [comment]
The fix has been applied to the `develop` branch; please reset any applications that were impacted.

**Comment by fritzmg** [comment]
Is there a way to downgrade scoop temporarily to be able to fix this issue?

**Comment by Vixb1122** [comment]
> Is there a way to downgrade scoop temporarily to be able to fix this issue?

scoop config scoop_branch develop

**Comment by W1M0R** [comment]
This effects the rustup package as well.
