### ISSUE TITLE
[Feature] Specify indent size / tab width in VSCode settings and/or editorconfig

### ISSUE THREAD

**Issue by o-l-a-v** [ScoopInstaller/Scoop#6065]
#### Is your feature request related to a problem? Please describe.

Scoop has requirements to JSON indent type (spaces) and size (4) which could easily be enforced inside `.vscode\settings.json` and/or with EditorConfig.

##### VSCode settings

Example:

```json
{
  ...
  "[json]": {
    "editor.autoIndent": "full",
    "editor.defaultFormatter": "vscode.json-language-features",
    "editor.detectIndentation": false,
    "editor.formatOnSave": true,
    "editor.indentSize": 4
  },
  ...
}
```

##### EditorConfig

* About EditorConfig: <https://editorconfig.org/>
* EditorConfig extension: <https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig>
* Sample `.editorconfig` file:
  ```text
  root = true
  [*.json]
  indent_style = space
  indent_size = 4
  ``` 

#### Describe the solution you'd like

Add config to overwrite JSON indent type (spaces) and size (4) to all Scoop repositories.

#### Describe alternatives you've considered

None yet.

**Comment by niheaven** [comment]
There's an `.editorconfig` file w/ indent size 4 already.

**Comment by o-l-a-v** [comment]
Yes, wow, how did I not see that. Maybe because it does not _actually_ override my own VSCode preferences for JSON.

Will look more into how EditorConfig works, or doesn't.
