### ISSUE TITLE
[Bug] scoop hold <apps> not works for multiple apps

### ISSUE THREAD

**Issue by ShuguangSun** [ScoopInstaller/Scoop#6077]
#### Current Behavior
When I do `scoop hold curl ffmpeg`, it just holds curl but ignores ffmpeg in the most recent version of scoop. It has been to hold both curl and ffmpeg at one command before.

#### Expected Behavior
The help message says `Usage: scoop hold <apps>` which sounds like we can put more than one app after `hold` and it has done like like this.

**Comment by niheaven** [comment]
![image](https://github.com/user-attachments/assets/d47709d0-3b22-445e-83bc-d5f2f20cce98)

It works fine, is there more info?

**Comment by ShuguangSun** [comment]
Just did a further explore. It seems that if one of the apps has be on hold, the apps after that one will not be proceeded. for example:
```
scoop unhold 7zip innounp
scoop hold 7zip
scoop hold 7zip innounp
```
and scoop will stop and say `INFO  '7zip' is already held.`.
