### ISSUE TITLE
A command that can check app updates, but leave a choice to user whether to update it.

### ISSUE THREAD

**Issue by 0x0501** [ScoopInstaller/Scoop#6117]
#### Is your feature request related to a problem? Please describe.

When I want to update apps, I have one way but only one way to update it by hitting `scoop update -a`. And I don't know what version my app is and what version this app is gonna be updated to. So I'm wandering if there's a possibility that I could check apps version and their latest release version in one command like `scoop update check` or `scoop update -c` for example. This command should print some of info like this:

```bash
Installed apps:

Name           Current Version         Latest                   Source   Updated               Info
----           ----------------        -------                  ------   -------               ----
7zip               24.07               24.09                    main     2024-08-06 20:37:09
```

For better visibility, the `latest` column might set its items to green or other color.

On current Scoop version, if I want to "check apps' version", I have to:

1. check every apps I suppose to update later with `-v` or `-version` parameter.
2. compare its current version with `scoop info [app_name]`.
3. take them into consideration whether i want to update it.

This is how I did, take `git` as an example:

get the installed version:

```bash
git version
``` 
then. check the latest version:

```bash
scoop info git
```

update it though:

```bash
scoop update git
```

**Comment by HUMORCE** [comment]
You can list upgradable apps by executing `scoop status`.

**Comment by 0x0501** [comment]
Wow. Thanks, I didn't know that.
