### ISSUE TITLE
[RFD] Implement a shim priority/alternatives system

### ISSUE THREAD

**Issue by rkitover** [ScoopInstaller/Scoop#6125]
#### Is your feature request related to a problem? Please describe.

Yesterday I installed the "busybox" package because I wanted to try it out for some things. It overwrote the shims for the "grep", "awk", "unzip", etc. packages with its own. I will have to redo my Scoop installation now, possibly with "busybox" being installed first in the order of packages so that its shims are overwritten by the GNU utilities etc..

#### Describe the solution you'd like

Distributions like Debian have an "alternatives" system with default priorities for packages with the same command invocation. For example, you may have POSIX awk and GNU awk installed at the same time, in which case GNU awk would have a higher default prirority and the `awk` command would invoke it by default.

#### Describe alternatives you've considered

In this particular case, what I am going to do for now is put "busybox" first in the package order in my install script.

**Comment by niheaven** [comment]
`scoop shim alter xxx` should do the work.

**Comment by rkitover** [comment]
Sorry I did not know about this command, I see it is already an alternatives system.

The issue is that shims do not have priorities.

If I have GNU grep installed, I am more likely to want the `grep` command to invoke it rather than the POSIX grep from busybox which is more limited, likewise for awk etc..

And currently this is determined solely by package installation order, with whatever is installed later in the sequence overwriting the shim.

There were 16 shims I had to alter after installing busybox to reset the commands to the packages for them.

In this particular case, the busybox package could just set the priority for its shims to `-1` or whatever, the priorities would not have to be specified for every package.

**Comment by HUMORCE** [comment]
Excute `scoop reset <app>` after busybox installed/updated.

```
❯ scoop which grep
~\scoop\apps\grep\current\grep.exe

❯ scoop reset busybox
Resetting busybox (5398-g89ae34445).
Linking ~\scoop\apps\busybox\current => ~\scoop\apps\busybox\5398-g89ae34445
...
Creating shim for 'grep'.
WARN  Overwriting shim ('grep.exe' -> 'busybox.exe') installed from grep
...

❯ scoop which grep
~\scoop\apps\busybox\current\busybox.exe

❯ scoop reset grep
Resetting grep (3.11).
Linking ~\scoop\apps\grep\current => ~\scoop\apps\grep\3.11
Creating shim for 'grep'.
WARN  Overwriting shim ('grep.exe' -> 'grep.exe') installed from busybox
...

❯ scoop which grep
~\scoop\apps\grep\current\grep.exe
```

**Comment by rkitover** [comment]
Thank you.

So that's easier than `shim alter`, but it does not address the issues I described.

Would you consider supporting defining shims with a completely optional priority for the overwrite behavior?

**Comment by rkitover** [comment]
I'd like to expolain my interest in this.

I maintain a Windows developer manual [here](https://github.com/rkitover/windows-dev-guide) and I recently added the busybox package and uses for it.

This shim overwriting behavior really sucks, if there is no good solution I will have to do something like make a script to update Scoop, and I would really prefer to not do that.

**Comment by HUMORCE** [comment]
You can create a copy of these manifests and maintain them on your own bucket.

**Comment by rkitover** [comment]
@HUMORCE

Looks like you gave me a good solution in the other issue. I looked at the `busybox` and `busybox-lean` manifests, and they use the same binary. So all I have to do is use `busybox-lean` and just create the shims I want.

So that will work for me, but I still think specifying a shim priority would be a very good feature to add.
