### ISSUE TITLE
[Bug] function Remove-Path not found (e.g. when updating go)

### ISSUE THREAD

**Issue by furopi** [ScoopInstaller/Scoop#6130]
#### Current Behavior
Updating go prompts with the following message:
`Downloading new version`
`Loading go1.23.0.windows-amd64.zip from cache.`
`Uninstalling 'go' (1.22.4)`
`Running uninstaller script...`
`INFO  Removing 'C:\Users\h4vvk\go\bin' from PATH...`
`ERROR The term 'Remove-Path' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.`
`ERROR This application failed to update: go`

#### Expected Behavior
Run without errors, seems like the powershell function "Remove-Path" is missing. Any help much appreciated, thanks for the hard work!

### System details

**Windows version:** 11 (Insider Preview Canary 27695)

**OS architecture:** 64bit

**PowerShell version:** 7.4.5

**Additional software:** none

**Comment by HUMORCE** [comment]
Please provide Scoop's configuration.

**Comment by furopi** [comment]
Thanks for your reply! Here's the configuration:

```
{
    "scoop_repo":  "https://github.com/Ash258/Scoop-Core",
    "root_path":  "C:\\Users\\h4vvk\\scoop",
    "global_path":  "C:\\ProgramData\\scoop",
    "use_isolated_path":  false,
    "last_update":  "2024-06-27T09:13:49.146522+02:00",
    "alias":  {
                  "update-all":  "scoop-update-all",
                  "cache-show-all":  "scoop-cache-show-all",
                  "cache-rm-all":  "scoop-cache-rm-all",
                  "cleanup-all":  "scoop-cleanup-all",
                  "list-all":  "scoop-list-all",
                  "info-all":  "scoop-info-all",
                  "search-info":  "scoop-search-info",
                  "bucket-origin":  "scoop-bucket-origin"
              },
    "aria2-warning-enabled":  false,
    "lastupdate":  "258|2024-09-05 09:49:06",
    "SCOOP_BRANCH":  "main"
}
```

**Comment by HUMORCE** [comment]
```
"scoop_repo":  "https://github.com/Ash258/Scoop-Core",
```

You are using a forked Scoop.

https://github.com/ScoopInstaller/Scoop/blob/859d1db51bcc840903d5280567846ae2f7207ca2/lib/system.ps1#L173-L176
