### ISSUE TITLE
[Bug]    anything can't  be     installed  

### ISSUE THREAD

**Issue by Super1Windcloud** [ScoopInstaller/Scoop#6137]
**update  normal**
![image](https://github.com/user-attachments/assets/af041dc7-af91-43d2-ac8c-74842340a230)

*but    install  everything  all pop  up  unknown  host* 
![image](https://github.com/user-attachments/assets/7b6d4c75-0487-46be-b087-29de9ba98746)

**Comment by HUMORCE** [comment]
Why don't you provide the relevant information just follow the issue template?

**Comment by Super1Windcloud** [comment]
sorry ,  win11 x64, Powershell7 , 
config.json 
> {
  "last_update": "2024-09-17T12:55:48.0821003+08:00",
  "scoop_repo": "https://github.com/ScoopInstaller/Scoop",
  "scoop_branch": "master",
  "set": "proxy",
  "proxy": "http://127.0.0.1:7890"
}


scoop path  :   A:\scoop  


what reason maybe

**Comment by Super1Windcloud** [comment]
goodbye scoop , after  reinstall ,   still  so,  just a  garbage

**Comment by HUMORCE** [comment]
You have an unreliable proxy server or wrong config of Clash for Windows.

> just a garbage

Yes, sir.

**Comment by Super1Windcloud** [comment]
> You have an unreliable proxy server or wrong config of Clash for Windows.您的代理服务器不可靠或 Clash for Windows 配置错误。
> 
> > just a garbage 只是一个垃圾
> 
> Yes, sir. 是的，先生。

to be clear  , proxy is completely   corrent  ,    winget  and  choco all  can  run  install normally ,   it's unrelated   to proxy 


## this  problem is  very  fantasy ,    removing   proxy  also lead to  same result .

**Comment by Super1Windcloud** [comment]
#  Can you capture exactly what error is preventing access here



![image](https://github.com/user-attachments/assets/e36f1217-25a3-4a06-bcc7-cd1a686b816b)

**Comment by Super1Windcloud** [comment]
# can't   parse  this url  host , why ?    I can  access it by   Chrome,    but  scoop can't  parse url  ?  

![image](https://github.com/user-attachments/assets/6e73c274-3886-4f08-96c5-bfedaa353aa7)

**Comment by Super1Windcloud** [comment]
# what the fuck ?   all normal ,    scoop just is a  joke 

![image](https://github.com/user-attachments/assets/16f6c09f-1778-4ecd-8ab6-f68927449a7a)
![image](https://github.com/user-attachments/assets/58fad1ac-8735-4c58-9631-dad44d60633b)
![image](https://github.com/user-attachments/assets/8ddb28fc-1e81-4ab9-ba29-60c948363b64)

**Comment by HUMORCE** [comment]
I have reproduce it, and found:

You should set proxy to `127.0.0.1:7890` without protocol.

```
❯ scoop config proxy 127.0.0.1:5555
'proxy' has been set to '127.0.0.1:5555'

❯ scoop download 7zip
INFO  Downloading '7zip' [64bit] from main bucket
7z2408-x64.msi (1.9 MB) [=====================================================================================] 100%
Checking hash of 7z2408-x64.msi ... ok.
'7zip' (24.08) was downloaded successfully!

❯ scoop cache rm *
Removing 7zip#24.08#71f2568.msi...
Deleted: 1 file, 1.9 MB

❯ scoop config proxy http://127.0.0.1:5555
'proxy' has been set to 'http://127.0.0.1:5555'

❯ scoop download 7zip
INFO  Downloading '7zip' [64bit] from main bucket
No such host is known. (http:80)
ERROR URL https://www.7-zip.org/a/7z2408-x64.msi is not valid
```

`scoop help config`:
```
...
proxy: [username:password@]host:port
      By default, Scoop will use the proxy settings from Internet Options, but with anonymous authentication.

      * To use the credentials for the current logged-in user, use 'currentuser' in place of username:password
      * To use the system proxy settings configured in Internet Options, use 'default' in place of host:port
      * An empty or unset value for proxy is equivalent to 'default' (with no username or password)
      * To bypass the system proxy and connect directly, use 'none' (with no username or password)
...
```

**Comment by Super1Windcloud** [comment]
#  What a stupid setup  ,  
# Don't know how stupid people would filter out the protocol and there are no error messages yet

**Comment by HUMORCE** [comment]
```
-SIT collage OSS enthusiastic
+SIT college OSS toxic

git add -A
git commit -m 'profile: Fix typo and correct wording'
git push --force
```
