### ISSUE TITLE
    [Feature]      the  function  " bin_match_json  " default    throws   error   message  by   TryGetProperty ,  so  add try catch  to  handle it to    ignore ouput   on console  

### ISSUE THREAD

**Issue by Super1Windcloud** [ScoopInstaller/Scoop#6140]
#   the  function  " bin_match_json  " default    throws   error   message  by   TryGetProperty ,  so  add try catch  to  handle it to    ignore #  ouput   on console  

![image](https://github.com/user-attachments/assets/aea6902e-f3b3-4f36-9c1a-7136c19c9b16)
# *source*  
![40c63b1bfcf680066a017442cd8a78d](https://github.com/user-attachments/assets/1d09a077-dc71-4c17-982f-48a688b7c6a5)

# *to change* 
![85f7c4f8651396be0abbccdaa29d306](https://github.com/user-attachments/assets/fe7f69a0-472f-4dcf-bb1e-400c68b6b4a1)

**Comment by Orion-zhen** [comment]
I encountered the same error. Only powershell 7 will throw this error message, while windows powershell (the older one default in windows) won't.

![image](https://github.com/user-attachments/assets/a4a76a9f-3dc4-4270-ac27-2ed38d694e6f)

**Comment by niheaven** [comment]
![image](https://github.com/user-attachments/assets/95f32027-918d-44f6-bee7-68346be696fb)

**Comment by Super1Windcloud** [comment]
#  @niheaven    you  should   firstly     run command  `scoop bucket add   sm  https://github.com/okibcn/ScoopMaster`

**Comment by Super1Windcloud** [comment]
everything I want  is  in it  ,    what a  such  wonderful bucket

**Comment by niheaven** [comment]
The bucket is unofficial and not well-maintained, containing some wrong manifests in the bucket subdirectory (such as `bcc.json`, `apache-vc14.json`, etc.).

Please submit a PR to the bucket's repository to address the bug.

_Originally posted by @niheaven in https://github.com/ScoopInstaller/Scoop/issues/6151#issuecomment-2404064844_

**Comment by Super1Windcloud** [comment]
666
