### ISSUE TITLE
[Feature] When an app is installed by scoop, it later updated should installed to the same location

### ISSUE THREAD

**Issue by aiyolo** [ScoopInstaller/Scoop#6145]
#### Is your feature request related to a problem? Please describe.
I installed some apps using scoop, however, when I later update theses apps(not from scoop), a new install location is created, which causes me have two same apps.

#### Describe the solution you'd like

I hope, the app is updated to the same install location as it installed by scoop. Although, I know I can updated app by scoop command. But sometimes, some apps will pops up a update notificaiton, it's so easy to click update button from the app.

**Comment by HUMORCE** [comment]
This can only be done by pre-disabling or deleting something in the relevant manifests: https://github.com/search?q=repo%3AScoopInstaller%2FExtras%20disable&type=code

You can create related issues in corresponding bucket.
