### ISSUE TITLE
Installing ruby and ruby19

### ISSUE THREAD

**Issue by rioka** [ScoopInstaller/Scoop#615]
I've tried to install both ruby and ruby19; at the end, I get both version installed, but no shims created for the two versions; path variable contains both folders, and both "scoop reset x" results in nothing.

To switch from one version to the other, I have manually update the value for path variable.

**Comment by deevus** [comment]
@rioka Can you provide any output from `scoop reset ruby`?

**Comment by zatchgordon** [comment]
I'm having the same problem. 
`scoop reset ruby`

results in `resetting ruby (2.3.1)`

`ruby --version` = `ruby 1.9.3p551 (2014-11-13) [i386-mingw32]`

**Comment by zatchgordon** [comment]
After running `scoop reset ruby`
this time I closed and reopened command prompt and 
`ruby --version`
returned 
`ruby 2.3.1p112 (2016-04-26 revision 54768) [x64-mingw32]`
