### ISSUE TITLE
[Bug]  hello ,  hleper   , god  blessing you  , I  wonder  to   know that   why   %scoop%\persist  still existes   when  I  scoop    uninstall nvm  or  volta     . 

### ISSUE THREAD

**Issue by Super1Windcloud** [ScoopInstaller/Scoop#6173]
win11  , scoop@latest  

# I  wonder  to   know that   why   %scoop%\persist  still existes   when  I  scoop    uninstall nvm  or  volta     . 

![image](https://github.com/user-attachments/assets/ae5aa76c-f2c8-4a66-95f1-9938525d9bf7)

**Comment by r15ch13** [comment]
This is not a bug. `%scoop%\persist` stores your program settings.
You can add the `--purge`-flag to the uninstall command to remove these files for each app, too.
Like: `scoop uninstall --purge nvm` or `scoop uninstall --purge volta`
