### ISSUE TITLE
Using Scoop install mysql-shell and can not connect root@localhost:3306

### ISSUE THREAD

**Issue by MaxforCherubim** [ScoopInstaller/Scoop#6217]
#### Current Behavior

```
scoop isntall mysql-shell
mysqlsh -u root
```

- `Scoop` silently installed `mysql-shell` for me and didn't ask me to set a password, so I thought it was the same as installing `MySQL` with `brew` and the password was empty. 
- But the result still requires my password when linking to root.

#### Expected Behavior

**Please provide the password for 'root@localhost': (empty)**

```SQL
MySQL Shell 9.0.1

Copyright (c) 2016, 2024, Oracle and/or its affiliates.
Oracle is a registered trademark of Oracle Corporation and/or its affiliates.
Other names may be trademarks of their respective owners.

Type '\help' or '\?' for help; '\quit' to exit.
Creating a session to 'root@localhost'
MySQL Error 2003 (HY000): Can't connect to MySQL server on 'localhost:3306' (10061)
```

#### Possible Solution

- I have tried various possible passwords, but none of them work. This indicates that **Scoop** set an initial password for me when installing **mysql-shell**
- I want to find `mysql.err` or `mysql.log`, or `my.ini`. But I couldn't find it in the **mysql-shell** installation directory, I don't know what to do.

### System details

**Windows version:** **11**

**PowerShell version:** 

| Major | Minor | Patch |
|---|---|---|
| 7 | 4 | 6 |

#### Scoop Configuration

```json
{
  "last_update": "2024-10-17T21:26:22.6287846+08:00",
  "scoop_repo": "https://github.com/ScoopInstaller/Scoop",
  "scoop_branch": "master"
}
```

**Comment by HUMORCE** [comment]
`mysql-shell` does not provide a mysql service for user.

I think you should confirm that MYSQL is running on that port, because MYSQL error 2003 usually means that the target service does not exist or unable to access.

https://dev.mysql.com/doc/refman/8.4/en/can-not-connect-to-server.html

**Comment by MaxforCherubim** [comment]
> `mysql-shell` does not provide a mysql service for user.
> 
> I think you should confirm that MYSQL is running on that port, because MYSQL error 2003 usually means that the target service does not exist or unable to access.
> 
> https://dev.mysql.com/doc/refman/8.4/en/can-not-connect-to-server.html

Yes, you are right.
Thanks very much for your reply.
