### ISSUE TITLE
[Bug]  what the fuck ?  are you kidding ?  

### ISSUE THREAD

**Issue by Super1Windcloud** [ScoopInstaller/Scoop#6221]
![image](https://github.com/user-attachments/assets/d4054761-5315-4242-bb82-c228208363c2)

**Comment by milnak** [comment]
```PowerShell
> scoop bucket add php
Checking repo... OK
INFO  Updating cache...
The php bucket was added successfully.
```

No repro for me.  How about next time you provide a bug report that doesn't look like it's coming from a 6th grader?
